### ISSUE TITLE
docs: explain component name resolution

### ISSUE THREAD

**Issue by driss-chelouati** [nuxt/framework#1035]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v14.17.3`
- Nuxt Version:     `3-3.0.0-27235989.d52b1e8`
- Package Manager:  `Yarn`
- Bundler:          `Webpack`
- User Config:      `alias`, `buildModules`, `css`
- Runtime Modules:  `-`
- Build Modules:    `nuxt-windicss@1.2.5`
------------------------------

### Describe the bug

I have a Button component.
When I put it under ./components, Nuxt finds it and loads it
If I put it inside one or more nested subfolders (`./components/base/button/Button.vue`), Nuxt cannot resolve it.
Since there is nothing for now in the components section of the documentation, is there something Iam missing?

### Reproduction

Create a component : `Button.vue` under 

`./components/base/button/Button.vue`

Nuxt won't be able to resolve it when you call it in your template:

```javascript
<template>
  <NuxtLayout  name="minimal">
     <div>
          <Button/>
     </div>
  </NuxtLayout>
</template>
```

### Additional context

Button.vue file 
```javascript
<script setup lang="ts"></script>

<template>
  <button class="button button-primary button-lg button-rounded-md">
    <slot></slot>
  </button>
</template>

<style lang="postcss" scoped>
.button {
  @apply font-roboto outline-none focus:outline-none leading-5;

  transition: background-color 0.3s, opacity 0.3s, color 0.3s, box-shadow 0.3s;

  &.button-sm {
    @apply h-8 px-3 py-1 text-sm;
  }

  &.button-md {
    @apply h-10 px-4 py-2 text-sm;
  }

  &.button-lg {
    @apply h-12 px-5 py-3;
  }

  &.button-xl {
    @apply h-14 px-10 py-4;
  }

  &.button-rounded-sm {
    @apply rounded-sm;
  }

  &.button-rounded {
    @apply rounded;
  }

  &.button-rounded-md {
    @apply rounded-md;
  }

  &.button-rounded-lg {
    @apply rounded-lg;
  }

  &.button-rounded-xl {
    @apply rounded-xl;
  }

  &.button-pill {
    @apply rounded-full;
  }

  &.button-default {
    @apply text-gray-400 bg-white border font-normal hover:shadow-sm;
    @apply dark:text-white dark:bg-gray-800 border border-gray-300 dark:border-gray-700;
  }

  &:not(.loading) {
    .animate-spin {
      display: none;
    }
  }

  &.button-loading {
    .animate-spin {
      display: block;
    }
  }
}

.button-default {
  @apply text-gray-400 bg-white border hover:shadow-sm;
  @apply dark:text-white dark:bg-gray-800  border dark:border-gray-700;
}

.button-primary {
  @apply text-white bg-primary hover:bg-accent;
}

.button-accent {
  @apply text-white bg-accent hover:bg-primary;
}

.button-green {
  @apply text-white bg-green-400 hover:bg-green-500;
}

.button-indigo {
  @apply text-white bg-indigo-400 hover:bg-indigo-500;
}

.button-blue {
  @apply text-white bg-blue-500 hover:bg-blue-600;
}

.button-yellow {
  @apply text-white bg-yellow-400 hover:bg-yellow-500;
}

.button-pink {
  @apply text-white bg-pink-500 hover:bg-pink-600;
}

.button-red {
  @apply text-white bg-red-500 hover:bg-red-600;
}

.button-dark {
  @apply text-white bg-gray-800 hover:bg-gray-900;
}

.button-t-green {
  @apply text-white bg-t-green-medium hover:bg-t-green-heavy;
}

.button-t-orange {
  @apply text-white bg-t-orange-medium hover:bg-t-orange-heavy;
}

.button-t-purple {
  @apply text-white bg-t-purple-medium hover:bg-t-purple-heavy;
}

.button-t-blue {
  @apply text-white bg-t-blue-medium hover:bg-t-blue-heavy;
}

/* ==========================================================================
3. Outlined Buttons
========================================================================== */

.button-primary-outlined {
  @apply bg-transparent border text-primary border-primary hover:bg-primary hover:text-white font-normal;
}

.button-accent-outlined {
  @apply bg-transparent border text-accent border-accent hover:bg-accent hover:text-white font-normal;
}

.button-green-outlined {
  @apply bg-transparent border text-green-500 border-green-500 hover:bg-green-500 hover:text-white font-normal;
}

.button-indigo-outlined {
  @apply bg-transparent border text-indigo-500 border-indigo-500 hover:bg-indigo-500 hover:text-white font-normal;
}

.button-blue-outlined {
  @apply bg-transparent border text-blue-500 border-blue-500 hover:bg-blue-500 hover:text-white font-normal;
}

.button-yellow-outlined {
  @apply bg-transparent border text-yellow-400 border-yellow-400 hover:bg-yellow-400 hover:text-white font-normal;
}

.button-pink-outlined {
  @apply bg-transparent border text-pink-500 border-pink-500 hover:bg-pink-500 hover:text-white font-normal;
}

.button-red-outlined {
  @apply bg-transparent border text-red-500 border-red-500 hover:bg-red-500 hover:text-white font-normal;
}

.button-dark-outlined {
  @apply bg-transparent border text-gray-800 border-gray-800 hover:bg-gray-800 hover:text-white font-normal dark:text-gray-500 dark:border-gray-500 dark:hover:border-gray-1000 dark:hover:bg-gray-1000 dark:hover:text-gray-100;
}

.button-t-green-outlined {
  @apply font-normal transition duration-75 bg-transparent border text-t-green-medium border-current hover:bg-t-green-medium hover:text-white;
}

.button-t-orange-outlined {
  @apply bg-transparent border text-t-orange-medium border-current hover:bg-t-orange-medium hover:text-white font-normal;
}

.button-t-purple-outlined {
  @apply bg-transparent border text-t-purple-medium border-current hover:bg-t-purple-medium hover:text-white font-normal;
}

.button-t-blue-outlined {
  @apply bg-transparent border text-t-blue-medium border-current hover:bg-t-blue-medium hover:text-white font-normal;
}

.button-disabled {
  @apply opacity-50 cursor-not-allowed;
}

</style>
```

### Logs

```shell
[Vue warn]: Failed to resolve component: Button
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
Server Side Rendering Error: TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at normalizePropsOptions (/home/cssninja/projects/tailfox-nuxt/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:2673:11)
    at createComponentInstance (/home/cssninja/projects/tailfox-nuxt/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6099:23)
    at renderComponentVNode (/home/cssninja/projects/tailfox-nuxt/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:197:22)
    at Module.ssrRenderComponent (/home/cssninja/projects/tailfox-nuxt/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:623:12)
    at file:///home/cssninja/projects/tailfox-nuxt/.nuxt/dist/server/server.mjs:2077:37
    at renderFnWithContext (/home/cssninja/projects/tailfox-nuxt/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:402:21)
    at Module.ssrRenderSlot (/home/cssninja/projects/tailfox-nuxt/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:635:21)
    at _sfc_ssrRender (file:///home/cssninja/projects/tailfox-nuxt/.nuxt/dist/server/server.mjs:1989:25)
    at renderComponentSubTree (/home/cssninja/projects/tailfox-nuxt/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:263:13)
[Vue warn]: Failed to resolve component: Button
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
Server Side Rendering Error: TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at normalizePropsOptions (/home/cssninja/projects/tailfox-nuxt/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:2673:11)
    at createComponentInstance (/home/cssninja/projects/tailfox-nuxt/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6099:23)
    at renderComponentVNode (/home/cssninja/projects/tailfox-nuxt/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:197:22)
    at Module.ssrRenderComponent (/home/cssninja/projects/tailfox-nuxt/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:623:12)
    at file:///home/cssninja/projects/tailfox-nuxt/.nuxt/dist/server/server.mjs:2077:37
    at renderFnWithContext (/home/cssninja/projects/tailfox-nuxt/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:402:21)
    at Module.ssrRenderSlot (/home/cssninja/projects/tailfox-nuxt/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:635:21)
    at _sfc_ssrRender (file:///home/cssninja/projects/tailfox-nuxt/.nuxt/dist/server/server.mjs:1989:25)
    at renderComponentSubTree (/home/cssninja/projects/tailfox-nuxt/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:263:13)
[Vue warn]: Failed to resolve component: Button
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
Server Side Rendering Error: TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at normalizePropsOptions (/home/cssninja/projects/tailfox-nuxt/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:2673:11)
    at createComponentInstance (/home/cssninja/projects/tailfox-nuxt/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6099:23)
    at renderComponentVNode (/home/cssninja/projects/tailfox-nuxt/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:197:22)
    at Module.ssrRenderComponent (/home/cssninja/projects/tailfox-nuxt/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:623:12)
    at file:///home/cssninja/projects/tailfox-nuxt/.nuxt/dist/server/server.mjs:2077:37
    at renderFnWithContext (/home/cssninja/projects/tailfox-nuxt/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:402:21)
    at Module.ssrRenderSlot (/home/cssninja/projects/tailfox-nuxt/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:635:21)
    at _sfc_ssrRender (file:///home/cssninja/projects/tailfox-nuxt/.nuxt/dist/server/server.mjs:1989:25)
    at renderComponentSubTree (/home/cssninja/projects/tailfox-nuxt/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:263:13)
```

**Comment by danielroe** [comment]
You would reference that button as `<BaseButton>` as it is constructed from the path segments: `Base` + `Button` + `Button`, with duplicated segments disappearing.

We need to add some docs on this, so I'll leave this open until I've done that.
