### ISSUE TITLE
Auto import components nested folders

### ISSUE THREAD

**Issue by Patrick-Remy** [nuxt/framework#1044]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.15.4`
- Nuxt Version:     `3-3.0.0-27237089.3e38eb8`
- Package Manager:  `npm`
- Bundler:          `Webpack`
- User Config:      `target`, `srcDir`, `css`, `plugins`, `components`, `build`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Describe the bug

Not sure if it's a breaking change or only currently not implemented. In my projects I configure auto-import like this for example

```ts
// nuxt.config.ts
components: [
    '~/components',
    '~/components/base',
  ],
```

But when I use components of `base` without prefixing them, I'll get errors like 
```
[Vue warn]: Failed to resolve component: Button
```

Using it as `BaseButton` indeed still works.

### Reproduction

To be added, if I know it's not a known breaking change.

### Logs

```shell
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
Server Side Rendering Error: TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at normalizePropsOptions (xxx/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:2673:11)
    at createComponentInstance (xxx/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6099:23)
    at renderComponentVNode (xxx/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:197:22)
    at Module.ssrRenderComponent (xxx/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:623:12)
    at _sfc_ssrRender (file://xxx/.nuxt/dist/server/server.mjs:1968:31)
    at renderComponentSubTree (xxx/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:263:13)
    at renderComponentVNode (xxx/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:214:16)
    at renderVNode (xxx/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:304:22)
    at renderComponentSubTree (xxx/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:269:13)
```

**Comment by danielroe** [comment]
@Patrick-Remy We don't currently support this kind of configuration. See http://v3.nuxtjs.org/docs/directory-structure/components

**Comment by Patrick-Remy** [comment]
As it worked in nuxt 2, I think it should be mentioned somewhere in a migration guide?

**Comment by nathanchase** [comment]
I use:
```
components: [
    { path: '~/components', pathPrefix: false },
  ],
```
very happily in Nuxt 2, and have 102 working components in any number of subfolders with their given names. 

It would be great if there was some way Nuxt 3 could support this, without having to prefix all the folder names to components.

**Comment by danielroe** [comment]
This should now be configurable in Nuxt 3 in `nuxt.config` with https://github.com/nuxt/framework/pull/1988.

**Comment by Patrick-Remy** [comment]
Yes, it is now possible, thanks for that! While back-migrating my components, I found this (not sure how it was in Nuxt 2), if you have this config:
```ts
// nuxt.config.ts
components: [
    '~/components',
    '~/components/layout',
],
```
and a component named `TheNavigation` inside `~/components/layout` and you still reference it as `LayoutTheNavigation` you'll receive this error:
```
Invalid value used as weak map key
  at WeakMap.set (<anonymous>)  
  at normalizePropsOptions (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:2694:11)  
  at createComponentInstance (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6121:23)  
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:197:22)  
  at Module.ssrRenderComponent (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:623:12)  
  at _sfc_ssrRender (file:///Users/patrick/Documents/PAT%20Development/Kunden/BBZ/bld-website-nuxt2/.nuxt/dist/server/server.mjs:16746:31)  
  at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:263:13)  
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:214:16)  
  at renderVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:304:22)  
  at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:269:13)
[Vue warn]: Failed to resolve component: Layout TheNavigation
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
```

If I correct it to `TheNavigation` it works well, but the error is a bit unconvenient.

**Comment by alexcroox** [comment]
Has anyone tried this with a custom `srcDir`? It doesn't seem to work for me, reproduction link:

https://codesandbox.io/s/patient-dream-dgrf5?file=/nuxt.config.ts

**Comment by danielroe** [comment]
@alexcroox - the directories are prefixed to the name of the component file name - see https://codesandbox.io/s/nice-robinson-5kz9r?file=/src/app.vue. See https://v3.nuxtjs.org/docs/directory-structure/components#component-names for more information on how this happens, and how to disable it.

**Comment by alexcroox** [comment]
@danielroe yes that was the default behaviour in Nuxt 2 too. However you could disable it in Nuxt 2, and have no prefix on any nested components using `pathPrefix: false`. I've tried that in the sandbox above to no avail.

**Comment by danielroe** [comment]
This isn't connected to `srcDir`, but is definitely an issue (only for customising the root `~/components` directory). I've raised a new issue: https://github.com/nuxt/framework/issues/2748
