### ISSUE TITLE
Build fails missing .nuxt/tsconfig.json

### ISSUE THREAD

**Issue by bicouy0** [nuxt/framework#1048]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v14.18.0`
- Nuxt Version:     `3-3.0.0-27237303.6acfdcd`
- Package Manager:  `Yarn`
- Bundler:          `Webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Describe the bug

Build fails with a plugin and tsconfig.json extending generated .nuxt/tsconfig.json

### Reproduction

Using a starter with `tsconfig.json` with : 

```json
{
  "extends": "./.nuxt/tsconfig.json"
}
```

And adding a simple `plugins/test.ts` : 

```ts
import { defineNuxtPlugin } from '#app'
export default defineNuxtPlugin(nuxt => {})
```

Running `yarn dev` is OK, but `yarn build` fails 

```
yarn run v1.22.15
$ nuxt build
Nuxt CLI v3.0.0-27237303.6acfdcd                                                                                              22:30:53
✔ Generated nuxt.d.ts                                                                                                         22:30:54

 ERROR  [vite:esbuild] failed to resolve "extends":"./.nuxt/tsconfig.json" in /home/bicou/tmp/nuxt3-app/tsconfig.json         22:30:55
file: /home/bicou/tmp/nuxt3-app/plugins/test.ts


 ERROR  failed to resolve "extends":"./.nuxt/tsconfig.json" in /home/bicou/tmp/nuxt3-app/tsconfig.json                        22:30:55

  at resolveExtends (node_modules/vite/dist/node/chunks/dep-713b45e1.js:22044:11)
  at parseExtends (node_modules/vite/dist/node/chunks/dep-713b45e1.js:22028:34)
  at parse$e (node_modules/vite/dist/node/chunks/dep-713b45e1.js:21979:24)
  at async loadTsconfigJsonForFile (node_modules/vite/dist/node/chunks/dep-713b45e1.js:22311:24)
  at async transformWithEsbuild (node_modules/vite/dist/node/chunks/dep-713b45e1.js:22157:36)
  at async Object.transform (node_modules/vite/dist/node/chunks/dep-713b45e1.js:22241:32)
  at async ModuleLoader.addModuleSource (node_modules/rollup/dist/shared/rollup.js:22105:30)
  at async ModuleLoader.fetchModule (node_modules/rollup/dist/shared/rollup.js:22158:9)
  at async Promise.all (index 2)
  at async ModuleLoader.fetchStaticDependencies (node_modules/rollup/dist/shared/rollup.js:22193:34)

error Command failed with exit code 1.
```

### Additional context

Seems like build command load plugins before generating .nuxt/tsconfig.json ...

**Comment by wobsoriano** [comment]
Can confirm this. My nuxi info

```
- Operating System: `Darwin`
- Node Version:     `v16.3.0`
- Nuxt Version:     `3-3.0.0-27235989.d52b1e8`
- Package Manager:  `npm`
- Bundler:          `Webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
```

**Comment by bicouy0** [comment]
Maybe `./tsconfig.nuxt.json` is a better location than `./.nuxt/tsconfig.json`

**Comment by productdevbook** [comment]
some: https://github.com/productdevbook/nuxt3-app
