### ISSUE TITLE
Cannot restart nuxt:  resolver.resolveModule is not a function   

### ISSUE THREAD

**Issue by aslero** [nuxt/framework#1100]
```
at node_modules/@nuxtjs/style-resources/lib/module.js:35:43
  at Array.reduce (<anonymous>)
  at node_modules/@nuxtjs/style-resources/lib/module.js:34:42
  at Array.reduce (<anonymous>)
  at retrieveStyleArrays (node_modules/@nuxtjs/style-resources/lib/module.js:32:25)
  at Object.nuxtStyledResources (node_modules/@nuxtjs/style-resources/lib/module.js:50:60)
  at installModule (node_modules/@nuxt/kit/dist/index.mjs:1196:17)
  at initNuxt (node_modules/nuxt3/dist/index.mjs:817:11)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6763:9)
```
```

My nuxt.config.js

import { defineNuxtConfig } from "nuxt3";

export default defineNuxtConfig({

  css: [
    "@/assets/css/fonts.css",
    "@/assets/css/reset.css",
    "@/assets/css/desktop/button.scss"
  ],

  buildModules: [
    '@nuxtjs/style-resources',
    '@nuxtjs/svg',
  ],

  styleResources: {
    scss: [
      '~/assets/scss/variables.scss'
    ],
  },

});
```

**Comment by webdelin** [comment]
![Bildschirmfoto 2022-03-30 um 12 47 49](https://user-images.githubusercontent.com/21138899/160814990-053fadc4-53ce-4fb6-821a-bc0248af0e00.png)
![Bildschirmfoto 2022-03-30 um 12 49 07](https://user-images.githubusercontent.com/21138899/160814993-fa5d4476-ad4a-4cd2-8f80-6db43d48ccc9.png)
`"@nuxtjs/markdownit"`
`
  markdownit: {
    preset: 'default',
    linkify: true,
    breaks: true,
    use: [
      'markdown-it-div',
      'markdown-it-attrs'
    ]
  },`

**Comment by webdelin** [comment]
## @nuxtjs/markdownit on nuxt3 not working?
