### ISSUE TITLE
Fresh Nuxt 2 with Nuxt Bridge cannot be run

### ISSUE THREAD

**Issue by Jamiewarb** [nuxt/framework#1127]
### Environment

Nuxt CLI v3.0.0-27238235.a1bcc53                                      21:12:48
RootDir: /Users/jamie/Sites/big-night/bridge-test                     21:12:49
Nuxt project info:                                                    21:12:49

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.18.1`
- Nuxt Version:     `2.16.0-27226092.034b9901`
- Package Manager:  `Yarn`
- Bundler:          `Webpack`
- User Config:      `head`, `css`, `plugins`, `components`, `buildModules`, `modules`, `build`
- Runtime Modules:  `-`
- Build Modules:    `@nuxt/bridge@3.0.0-27238235.a1bcc53`

### Describe the bug

When creating a fresh installation of Nuxt 2, and adding Nuxt Bridge, the resulting build doesn't not work.

## Reproduction Steps

- Run `yarn create nuxt-app project-name`, with installation steps shown in section below
- `cd project-name`
- Follow instructions to add Nuxt Bridge from https://v3.nuxtjs.org/getting-started/bridge/
- Run `yarn build`. Observe successful build
- Run `yarn start`. Observe successful server start
- Open localhost:3000, observe error in console, and web page does not work

```bash
 ERROR  A dynamic import callback was not specified.                  21:08:40

  at new NodeError (internal/errors.js:322:7)
  at exports.importModuleDynamicallyCallback (internal/process/esm_loader.js:34:9)
  at server.js:51:122
  at new Promise (<anonymous>)
  at Function.requireEnsure [as e] (server.js:49:28)
  at _0540da9a (server.js:17521:60)
  at server.js:13939:27
  at server.js:13925:23
  at Array.reduce (<anonymous>)
  at server.js:13923:38
```

## Further information

Please see this repository that shows reproduction: https://github.com/hex-digital/bridge-test/
Pull it down, run `yarn build && yarn start`, navigate to the URL and observe the problem.

Please see this pull request that shows the exact steps taken to install Nuxt Bridge: https://github.com/hex-digital/bridge-test/pull/1/files

### Additional context

When Nuxt 2 was installed, the following steps were chosen:

```bash
create-nuxt-app v3.7.1
✨  Generating Nuxt.js project in bridge-test
? Project name: bridge-test
? Programming language: JavaScript
? Package manager: Yarn
? UI framework: None
? Nuxt.js modules: 
? Linting tools: 
? Testing framework: None
? Rendering mode: Universal (SSR / SSG)
? Deployment target: Server (Node.js hosting)
? Development tools:
? What is your GitHub username? jamiewarb
? Version control system: Git
```

**Comment by Jamiewarb** [comment]
More information about the above comment from @SuddenlyRust in case it helps: that starter repo is using `node .output/server/index.mjs` in place of `nuxt start`, which allows it to run
