### ISSUE TITLE
Cannot start nuxt:  Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by yk-sgr** [nuxt/framework#1163]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.10.0`
- Nuxt Version:     `3-3.0.0-27242539.adf4970`
- Package Manager:  `Yarn`
- Bundler:          `Webpack`
- User Config:      `meta`, `build`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Describe the bug

When I run `yarn dev` I receive the following error and nuxt cannot be started.

```
 ERROR  Cannot start nuxt:  Cannot read properties of undefined (reading 'map')                                                                                                                                              12:36:20  

  at Object.getContents (/G:/xxx/web/node_modules/nuxt3/dist/index.mjs:259:34)
  at compileTemplate (/G:/xxx/web/node_modules/@nuxt/kit/dist/index.mjs:963:21)
  at /G:/xxx/web/node_modules/nuxt3/dist/index.mjs:940:28
  at Array.map (<anonymous>)
  at generateApp (/G:/xxx/web/node_modules/nuxt3/dist/index.mjs:939:35)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async build (/G:/xxx/web/node_modules/nuxt3/dist/index.mjs:977:3)
  at async load (/G:/xxx/web/node_modules/nuxi/dist/chunks/dev.mjs:6756:9)
  at async Object.invoke (/G:/xxx/web/node_modules/nuxi/dist/chunks/dev.mjs:6786:5)
  at async _main (/G:/xxx/web/node_modules/nuxi/dist/chunks/index.mjs:417:7)
```

### Reproduction

`yarn dev`

### Additional context

I inspected the error and I think I found some kind of reason.

`G:\xxx\web\node_modules\nuxt3\dist\index.mjs`
=> Original Code `${options.components.map((c) => {`
The problem is that `options.components` is undefined.

Updating the snippet to the following works though.
`options.options.components`

**Comment by wobsoriano** [comment]
Same problem here

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.11.0`
- Nuxt Version:     `3.0.0-27244261.c49f9ca`
- Package Manager:  `Yarn`
- Bundler:          `Vite`
- User Config:      `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

```ts
import { defineNuxtConfig } from 'nuxt3'

export default defineNuxtConfig({
    vite: {
        resolve: {
            alias: {
            }
        }
    }
})
```

Adding an `resolve.alias` to vite gives `Cannot read properties of undefined (reading 'map')`
