### ISSUE TITLE
how can switch from nitro to node.js?

### ISSUE THREAD

**Issue by xiaobai-world** [nuxt/framework#1216]
### Environment

➜  nuxt3-app npx nxui info
npx: installed 68 in 4.355s

-------
nuxt3:version  3.0.0-27243104.5e903ae

### Describe the bug

nitro is not compatible with node.js

### Reproduction

// server/api/hello.ts
```typescript
import axios from 'axios';

import type { IncomingMessage, ServerResponse } from 'http'

export default async (req: IncomingMessage, res: ServerResponse) => {
  return new Promise((resolve) => {
    if (req.method === 'GET') {
      axios.get(`http://localhost:3005${req.url}`, { responseType: 'stream' }).then(res => {
        res.data.pipe(res)
      })
    }
  })
}
```

### Logs

```shell
Nuxt CLI v3.0.0-27243104.5e903ae

  > Local:    http://localhost:3000/ 
  > Network:  http://192.168.101.100:3000/

ℹ Vite warmed up in 649ms
✔ Generated nuxt.d.ts
✔ Vite server built in 1320ms
✔ Nitro built in 204 ms
(node:4589) UnhandledPromiseRejectionWarning: TypeError: dest.on is not a function
    at IncomingMessage.Readable.pipe (internal/streams/readable.js:657:8)
    at file:///Users/jack/Desktop/nuxt3-app/.nuxt/nitro/index.mjs:120:19
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4589) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4589) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by danielroe** [comment]
That error is caused by `res` shadowing the `res` variable provided by Nitro. This works fine:
```js
import type { IncomingMessage, ServerResponse } from 'http'
import axios from 'axios'

export default (req: IncomingMessage, res: ServerResponse) => {
  return new Promise(() => {
    if (req.method === 'GET') {
      axios.get('https://jsonplaceholder.cypress.io/todos/1', { responseType: 'stream' }).then((r) => {
        r.data.pipe(res)
      })
    }
  })
}
```

As a side note, piping will not work when there is a pure local fetch (initiated by `$fetch`, or `useFetch`).
