### ISSUE TITLE
require is not defined in ES module scope

### ISSUE THREAD

**Issue by productdevbook** [nuxt/framework#1315]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.18.1`
- Nuxt Version:     `3.0.0-27245975.d1214c9`
- Package Manager:  `Yarn`
- Bundler:          `Vite`
- User Config:      `buildModules`, `build`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.0.8`
------------------------------

### Describe the bug
https://unpkg.com/browse/@headlessui/vue@1.4.1/dist/headlessui.esm.js

<img width="1249" alt="CleanShot 2021-10-21 at 14 36 57@2x" src="https://user-images.githubusercontent.com/38668796/138269359-5e3cc680-23ac-41d3-bed7-a35431c567ad.png">

### Reproduction

https://github.com/productdevbook/nuxt3-app/tree/headlessui-next

### Logs

```shell
require is not defined in ES module scope, you can use import instead
  at $id_5e685441 (file://./.nuxt/dist/server/server.mjs:2431:15)  
  at __instantiateModule__ (file://./.nuxt/dist/server/server.mjs:5435:9)  
  at __ssrLoadModule__ (file://./.nuxt/dist/server/server.mjs:5383:25)  
  at ssrImport (file://./.nuxt/dist/server/server.mjs:5407:13)  
  at $id_832b5324 (file://./.nuxt/dist/server/server.mjs:826:37)  
  at async __instantiateModule__ (file://./.nuxt/dist/server/server.mjs:5435:3)
require is not defined in ES module scope, you can use import instead
  at $id_5e685441 (file://./.nuxt/dist/server/server.mjs:2431:15)  
  at __instantiateModule__ (file://./.nuxt/dist/server/server.mjs:5435:9)  
  at __ssrLoadModule__ (file://./.nuxt/dist/server/server.mjs:5383:25)  
  at ssrImport (file://./.nuxt/dist/server/server.mjs:5407:13)  
  at $id_832b5324 (file://./.nuxt/dist/server/server.mjs:826:37)  
  at async __instantiateModule__ (file://./.nuxt/dist/server/server.mjs:5435:3)
```

**Comment by pi0** [comment]
I track down `require` issue to pinia module. [plugin](https://github.com/posva/pinia/blob/v2/packages/nuxt/src/templates/plugin.ts#L2) is importing from main module wrongly

**Comment by productdevbook** [comment]
:( yes thats true thank you,
who is the problem here?
![CleanShot 2021-10-21 at 20 22 40@2x](https://user-images.githubusercontent.com/38668796/138326881-13b336e4-5d57-4914-9a27-a0ed92050a8a.png)
