### ISSUE TITLE
ERROR  object is not iterable (cannot read property Symbol(Symbol.iterator))

### ISSUE THREAD

**Issue by jankaderabek** [nuxt/framework#1335]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.11.1`
- Nuxt Version:     `3.0.0-27247403.694e95b`
- Package Manager:  `npm`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Describe the bug

There is and error after `npm run dev` with modified package.json: 

```
jankaderabek@Jan-MacBook-Pro-2 nuxt3-async-data-ssr-error % npm run dev

> dev
> nuxt dev


Nuxt CLI v3.0.0-27247403.694e95b                                      21:34:35

 ERROR  object is not iterable (cannot read property Symbol(Symbol.iterator))

  at new Set (<anonymous>)
  at node_modules/nuxi/dist/chunks/dev.mjs:4424:20
  at ModuleJob.run (node:internal/modules/esm/module_job:183:25)
  at async Loader.import (node:internal/modules/esm/loader:178:24)
  at async _main (node_modules/nuxi/dist/chunks/index.mjs:395:17)
```

### Reproduction

https://stackblitz.com/edit/github-hfd1pl?file=package.json

**Comment by pi0** [comment]
Seems a regression of https://github.com/unjs/unbuild/commits/main with `nuxi` bundle

**Comment by pi0** [comment]
Thanks for reporting. Should be solved shortly in next `nuxi` release
