### ISSUE TITLE
Exports is not defined in ES module scope

### ISSUE THREAD

**Issue by niko577** [nuxt/framework#1573]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v17.0.1`
- Nuxt Version:     `3.0.0-27258294.bdbfa36`
- Package Manager:  `npm@8.1.0`
- Bundler:          `Vite`
- User Config:      `vite`, `css`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Describe the bug

After updating to version `3.0.0-27258294.bdbfa36` I am unable to start the project. 

In my browser:
![image](https://user-images.githubusercontent.com/54767664/139412184-1106a9eb-3582-4c49-a3fe-fd404b05dcac.png)

### Reproduction

The problem is in my current project but also in a newly created one, so I'm not sending my repo.
I also tried to create new project on node version 16.11.1 and there is also the same problem.

### Logs

```shell
WARN  [SSR] Error transforming ./node_modules/hookable/dist/index.mjs: Error: Missing "./dist/index.mjs" export in "hookable" package                                                                  11:33:21

 WARN  [SSR] Error transforming ./node_modules/vue/server-renderer/index.js: Error: Missing "./server-renderer/index.js" export in "vue" package                                                        11:33:21

 WARN  [SSR] Error transforming ./node_modules/murmurhash-es/dist/index.mjs: Error: Missing "./dist/index.mjs" export in "murmurhash-es" package                                                        11:33:21

 WARN  [SSR] Error transforming ./node_modules/ohmyfetch/dist/index.mjs: Error: Missing "./dist/index.mjs" export in "ohmyfetch" package                                                                11:33:22

√ Vite server built in 3319ms                                                                                                                                                                           11:33:23
√ Nitro built in 121 ms                                                                                                                                                                                 11:33:23
(node:4704) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
exports is not defined in ES module scope
  at $id_60f0615f (file:///***/.nuxt/dist/server/server.mjs:121:23)
  at __instantiateModule__ (file:///***/.nuxt/dist/server/server.mjs:11371:9)
  at __ssrLoadModule__ (file:///***/.nuxt/dist/server/server.mjs:11318:25)
  at ssrImport (file:///***/.nuxt/dist/server/server.mjs:11343:13)
  at $id_880f8d98 (file:///***/.nuxt/dist/server/server.mjs:15:37)
  at __instantiateModule__ (file:///***/.nuxt/dist/server/server.mjs:11371:9)
  at __ssrLoadModule__ (file:///***/.nuxt/dist/server/server.mjs:11318:25)
  at file:///***/.nuxt/dist/server/server.mjs:11384:22
  at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
  at async Promise.all (index 0)
exports is not defined in ES module scope
  at $id_60f0615f (file:///***/.nuxt/dist/server/server.mjs:121:23)
  at __instantiateModule__ (file:///***/.nuxt/dist/server/server.mjs:11371:9)
  at __ssrLoadModule__ (file:///***/.nuxt/dist/server/server.mjs:11318:25)
  at ssrImport (file:///***/.nuxt/dist/server/server.mjs:11343:13)
  at $id_880f8d98 (file:///***/.nuxt/dist/server/server.mjs:15:37)
  at __instantiateModule__ (file:///***/.nuxt/dist/server/server.mjs:11371:9)
  at __ssrLoadModule__ (file:///***/.nuxt/dist/server/server.mjs:11318:25)
  at file:///***/.nuxt/dist/server/server.mjs:11384:22
  at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
  at async Promise.all (index 0)
```

**Comment by viceroyshayer** [comment]
+1.
If you comment out the line `Object.defineProperty(exports, "__esModule", { value: true });` it shows the next line using `require` not being defined. In a stackoverflow post from 4yrs ago, they advised changing `module to commonjs` and `target below es6` in `compiler options`. I have tried changing this in my tsconfig to no avail.
Looking forward to a  fix.

**Comment by ziyali** [comment]
same

**Comment by gustojs** [comment]
Same thing here, on Windows 10 with Node 16.11.1 and 16.13.0.

**Comment by cdwmhcc** [comment]
Same thing here, on Windows 10 with Node 16.12.0.Nuxt CLI v3.0.0-27258467.4e424d0

**Comment by Ttou** [comment]
same

**Comment by skashif18** [comment]
same issue

did anyone find any solution

**Comment by ejames17** [comment]
i solved it by changing  module.exports  to export default.

**Comment by netbounty** [comment]
Had the same issue with node version 16.x. Changed the version to 14.16.1, now it's working fine for me
