### ISSUE TITLE
SSR Error when adding plugin

### ISSUE THREAD

**Issue by selucaciu** [nuxt/framework#1629]
### Environment

- Operating System: `Linux`
- Node Version:     `v14.18.1`
- Nuxt Version:     `3.0.0-27258467.4e424d0`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `ssr`, `plugins`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Describe the bug

Hello,

I've started a new project with Nuxt 3 and was trying to import the codemirror library as a plugin but I can't get it to work.
Is this a bug or am I doing something wrong?

The error is as follows:
[vite] Internal server error: Failed to resolve import "~plugins/codemirror.js" from "virtual:D:\projects\code-editor.nuxt\plugins\client.mjs". Does the file exist?

### Reproduction

https://codesandbox.io/s/nostalgic-bell-du05c

### Logs

```shell
ERROR  6:29:38 PM [vite] Internal server error: Failed to resolve import "~plugins/codemirror.js" from "virtual:/sandbox/.nuxt/plugins/client.mjs". Does the file exist?
  Plugin: vite:import-analysis
  File: virtual:/sandbox/.nuxt/plugins/client.mjs
```

**Comment by danielroe** [comment]
You shouldn't add plugins manually to your `nuxt.config` as they are automatically imported. But in addition, the path should be `~/plugins/codemirror.js` not `~plugins/codemirror.js`.

**Comment by selucaciu** [comment]
Hi @danielroe , thank you for the quick response. 
I noticed they are imported automatically but the problem was how do I disable the SSR for a plugin?

**Comment by danielroe** [comment]
Just name it `codemirror.client.js`. More info https://v3.nuxtjs.org/docs/directory-structure/plugins

**Comment by selucaciu** [comment]
I removed the entry from nuxt.config and tried updating the file name to codemirror.client.js but it did not help.
Getting a 500 error:
```
Invalid value used as weak map key
at WeakMap.set ()
at normalizePropsOptions (D:\projects\code-editor\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:2673:11)
at createComponentInstance (D:\projects\code-editor\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:6099:23)
at renderComponentVNode (D:\projects\code-editor\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:198:22)
at Module.ssrRenderComponent (D:\projects\code-editor\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:624:12)
at _sfc_ssrRender (file:///D:/projects/code-editor/.nuxt/dist/server/server.mjs:2025:31)
at renderComponentSubTree (D:\projects\code-editor\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:264:13)
at renderComponentVNode (D:\projects\code-editor\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:215:16)
at renderVNode (D:\projects\code-editor\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:305:22)
at renderVNode (D:\projects\code-editor\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:311:17)
```
Also I tried the same plugin in Nuxt 2 and it works.

**Comment by danielroe** [comment]
@selucaciu The issue is that you only inject the component on client side, but you are using the component it registers on server side. The error you are getting is telling you that Vue doesn't know what component to render.

**Comment by selucaciu** [comment]
@danielroe I thought the <client-only> component skips rendering your component on the server side.
I wrapped the <codemirror> component with the <client-only> component but the error is still showing up.

**Comment by danielroe** [comment]
@selucaciu Track #646 - it's not implemented yet in Nuxt 3.
