### ISSUE TITLE
 UnhandledPromiseRejectionWarning: TypeError: Invalid value used as weak map key

### ISSUE THREAD

**Issue by brpaz** [nuxt/framework#1630]
### Environment

- Operating System: `Linux`
- Node Version:     `v14.18.0`
- Nuxt Version:     `3.0.0-27258467.4e424d0`
- Package Manager:  `yarn@1.22.15`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Describe the bug

Within an application created with `nuxi init` and not code changes, when I build for production and try to execute it using node it gives the following error when accessing the application url:

```
(node:331859) UnhandledPromiseRejectionWarning: TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at normalizePropsOptions (file:///home/bruno/Code/Playground/nuxt3-app/.output/server/chunks/index.mjs:3989:11)
    at createComponentInstance (file:///home/bruno/Code/Playground/nuxt3-app/.output/server/chunks/index.mjs:6789:23)
    at renderComponentVNode (file:///home/bruno/Code/Playground/nuxt3-app/.output/server/chunks/index.mjs:9763:22)
    at Object.ssrRenderComponent (file:///home/bruno/Code/Playground/nuxt3-app/.output/server/chunks/index.mjs:10189:12)
    at _sfc_ssrRender (file:///home/bruno/Code/Playground/nuxt3-app/.output/server/chunks/app/server.mjs:4262:32)
    at renderComponentSubTree (file:///home/bruno/Code/Playground/nuxt3-app/.output/server/chunks/index.mjs:9829:13)
    at renderComponentVNode (file:///home/bruno/Code/Playground/nuxt3-app/.output/server/chunks/index.mjs:9780:16)
    at Object.ssrRenderComponent (file:///home/bruno/Code/Playground/nuxt3-app/.output/server/chunks/index.mjs:10189:12)
    at default (file:///home/bruno/Code/Playground/nuxt3-app/.output/server/chunks/app/server.mjs:4246:36)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:331859) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:331859) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:331859) UnhandledPromiseRejectionWarning: TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at normalizePropsOptions (file:///home/bruno/Code/Playground/nuxt3-app/.output/server/chunks/index.mjs:3989:11)
    at createComponentInstance (file:///home/bruno/Code/Playground/nuxt3-app/.output/server/chunks/index.mjs:6789:23)
    at renderComponentVNode (file:///home/bruno/Code/Playground/nuxt3-app/.output/server/chunks/index.mjs:9763:22)
    at Object.ssrRenderComponent (file:///home/bruno/Code/Playground/nuxt3-app/.output/server/chunks/index.mjs:10189:12)
    at _sfc_ssrRender (file:///home/bruno/Code/Playground/nuxt3-app/.output/server/chunks/app/server.mjs:4262:32)
    at renderComponentSubTree (file:///home/bruno/Code/Playground/nuxt3-app/.output/server/chunks/index.mjs:9829:13)
    at renderComponentVNode (file:///home/bruno/Code/Playground/nuxt3-app/.output/server/chunks/index.mjs:9780:16)
    at Object.ssrRenderComponent (file:///home/bruno/Code/Playground/nuxt3-app/.output/server/chunks/index.mjs:10189:12)
    at default (file:///home/bruno/Code/Playground/nuxt3-app/.output/server/chunks/app/server.mjs:4246:36)
(node:331859) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
```

### Reproduction

```
npx nuxi init nuxt3-app
yarn install && yarn build
node .output/server/index.mjs
```
Access localhost:3000 on web browser

**Comment by danielroe** [comment]
See https://github.com/nuxt/framework/issues/953#issuecomment-942411190.
