### ISSUE TITLE
Cannot read properties of undefined (reading 'content-type') in express js

### ISSUE THREAD

**Issue by martiliones** [nuxt/framework#1684]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.10.0`
- Nuxt Version:     `3.0.0-27265876.3cd4494`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `serverMiddleware`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Describe the bug

`serverMiddleware` doesn't work with `express.js (4.17.1)` and throws "`Cannot read properties of undefined (reading 'content-type')`" error

### Reproduction

Clone a repository with the bug and run it as dev server
```bash
$ git clone https://github.com/martiliones/nuxt-express-bug
$ yarn install
$ yarn dev
```

Open `http://localhost/projects/` in your browser

### Additional context

I tested `serverMiddleware` with h3 and it works just fine:
```js
// api/index.js
import { createApp } from 'h3'

const app = createApp()
app.use('/projects', () => JSON.stringify([
    {
      name: 'asdsad',
      type: ['asdsad', 'asdsad']
    }
]))
```

### Logs

```shell
Cannot read properties of undefined (reading 'content-type')
  at ServerResponse.getHeader (node:_http_outgoing:597:24)  
  at ServerResponse.res.get (./node_modules/express/lib/response.js:789:15)  
  at ServerResponse.json (./node_modules/express/lib/response.js:263:13)  
  at file://./.nuxt/nitro/index.mjs:139:7  
  at Layer.handle [as handle_request] (./node_modules/express/lib/router/layer.js:95:5)  
  at next (./node_modules/express/lib/router/route.js:137:13)  
  at Route.dispatch (./node_modules/express/lib/router/route.js:112:3)  
  at Layer.handle [as handle_request] (./node_modules/express/lib/router/layer.js:95:5)  
  at ./node_modules/express/lib/router/index.js:281:22  
  at Function.process_params (./node_modules/express/lib/router/index.js:335:12)
```

**Comment by n3wsw3** [comment]
The problem only seems to exist when the API is used while SSR. Requesting with postman does not throw any errors.

**Comment by calumk** [comment]
Any news on this ?
Endpoints work just fine for me, but it fails when called using useFetch

**Comment by martiliones** [comment]
@calumk Nah, I'm just using Nuxt 2 now

Going to debug this in free time

**Comment by danielroe** [comment]
If you want to debug it, the issue is that `express` sets the prototype of `req`/`res` to be the native Node classes, rather than the `unenv`-provided classes we're using in Nuxt. That means the internal object that Node uses to store headers is undefined and can't be read from.

**Comment by SchneiderOr** [comment]
Ive also facing same issue, any workaround worth trying here?

**Comment by calumk** [comment]
Using the direct full URL eg 


 http://localhost:3000/api/whatever 


Instead of 


api/whatever 


Worked for me ....

**Comment by SchneiderOr** [comment]
> Using the direct full URL eg
> 
> http://localhost:3000/api/whatever
> 
> Instead of
> 
> api/whatever
> 
> Worked for me ....

Thanks for the quick reply! it is indeed working to me as well :)

**Comment by MikeyBeLike** [comment]
So is this a bug then? Using the full url works for me but would love to have the url relative

**Comment by ShaggyTech** [comment]
I’m not sure what are the full implications of using only the express Router instead of using the full express app.  That being said i did find that doing the following will make the content-type error go away:

```js
// Using the full express app this way will give the error:
import express from ‘express’
const app = express()
// …

// Using only the Express Router
import { Router } from ‘express’
const app = Router()
// …
```

I ran into other problems doing it this way, issues to do with sessions and cookies.  So i’m not confident this is not creating new problems but it may help someone else find a better solution.

**Comment by n3wsw3** [comment]
I ended up writing my own router based on h3 that can handle different request methods and route parameters. It's probably not the best approach, but if anyone wants to use it here it is: [router.ts](https://github.com/n3wsw3/todo-app-with-api-auth/blob/master/server/utils/router.ts)

**Comment by jewpaltz** [comment]
> Using the direct full URL eg
> 
> http://localhost:3000/api/whatever
> 
> Instead of
> 
> api/whatever
> 
> Worked for me ....

Thank you. That worked (in my dev environment)
But that is going to get complicated in a hosting environment

**Comment by SchneiderOr** [comment]
We eventually ended up setting an env variable called API_BASE which points to the api internal url that is used as the base for our fetch, we have one for each environment, bit annoying but manageable, will be more difficult if we will have dynamic preview environments without static domains..

**Comment by calumk** [comment]
> > Using the direct full URL eg
> > http://localhost:3000/api/whatever
> > Instead of
> > api/whatever
> > Worked for me ....
> 
> Thank you. That worked (in my dev environment) But that is going to get complicated in a hosting environment

Yeah it is obviosly not ideal, I dont know why this solves it, it was just trial and error that i stumbled on it - I was originally convinced that I was just pulling the wrong endpoint, or had an extra ```/``` or something  - so I tried it on a whim

**Comment by danielroe** [comment]
Using the full URL prevents Nitro from making a local call. So it's a workaround with a performance cost.

**Comment by niwla23** [comment]
I am also having this issue. Any proper fixes known?

**Comment by n3wsw3** [comment]
The "fix" for this is using h3 instead of express. Since my last comment, h3 now supports HTTP methods and path parameters (in other words DON'T use the one I shared in a previous comment. It is a 100% worse than their implementation and is not maintained).

The fix will most likely be on express' side since they are the ones overriding the objects with the wrong prototype.

**Comment by niwla23** [comment]
can someone explain to me how these local requests work?

**Comment by mfulop** [comment]
So according to [this comment](https://github.com/expressjs/express/issues/4950#issuecomment-1186575620), something like this should work:
```
import { IncomingMessage } from 'unenv/runtime/node/http/_request'
import { ServerResponse } from 'unenv/runtime/node/http/_response'

const app = express()

Object.setPrototypeOf(Object.getPrototypeOf(app.request), IncomingMessage.prototype)
Object.setPrototypeOf(Object.getPrototypeOf(app.response), ServerResponse.prototype)
```
... but it does not seem to fix the issue (for me, anyways - I'm struggling with this whenever an express route throws an error)

**Comment by dennisquan** [comment]
I'm also having this problem -- mainly because I need to reuse complex middleware that is somewhat Express-coupled. I think there are two problems: (1) that Express overrides the req/res prototypes; (2) APIs exposed via an Express-embedded-in-h3/nitro/nuxtjs server need to be handled both via server-side-only **and** from external requests, and the req/res prototypes needed for these two scenarios **are different**.

It seems like there are 3 possible solutions:
(1) Change h3 to (have the option to) not use node.http's res/req objects for incoming HTTP requests, so that overriding Express's prototypes as indicated in the last comment might work across both kinds of API requests. (I would think this would be somewhat complicated.)
(2) Change the server-side-only fake res/req (unenv/runtime/fetch/call.mjs) to (have the option to) use the native node.http res/req objects instead. (Don't know how accessible these objects are for direct instantiation though..)
(3) Change unjs's polyfill-ish IncomingMessage/ServerResponse objects to more closely mirror nodejs'. (I would think this would become a maintenance nightmare over time if nodejs evolves their impls.)

Would any of the above be viable changes to nuxt/unjs?

**Comment by niwla23** [comment]
If none of these can be implemented until Nuxt 3.0.0 releases I think an option for disabling local calls would make sense. This would still allow using relative routes but with a performance penalty. It could just use the loopback interface on the server and the public url on the client then.

**Comment by luischinchillagarcia** [comment]
@niwla23 

If you don't mind me asking: how would this look like in an express app? I'm not entirely understanding

**Comment by niwla23** [comment]
When you request /test from SSR it seems to make a local request that is not going through the loopback interface but somehow stays in the process, at least that is how I understand it. But this feature only seems to work with h3, so it would be nice to have an option to have nuxt SSR make these requests over the loopback interface.

So on the Server Side `/test` would simply be a request to `http://localhost:3000/test` and on the client side it would still be `/test`, but handled by the browser resulting in https://yourpublichhost.com/test.

Hopes this makes sense, but maybe I don't understand correctly how local calls to h3 work.

**Comment by HendrikJan** [comment]
I've set "SSR: false", so would not expect a local call to be made.
I get this error when running "nuxi build".
I'm not getting this error with "nuxi dev".

**Comment by HendrikJan** [comment]
This piece of code fixes half of the problem:
```javascript
import { IncomingMessage } from 'unenv/runtime/node/http/_request'
import { ServerResponse } from 'unenv/runtime/node/http/_response'

const app = express()

Object.setPrototypeOf(Object.getPrototypeOf(app.request), IncomingMessage.prototype)
Object.setPrototypeOf(Object.getPrototypeOf(app.response), ServerResponse.prototype)
```

After this *fix*, The error changes from "Cannot __read__ ..." to "Cannot __set__ properties of undefined (setting 'content-type')"

**Comment by minthukhant-thedeveloper** [comment]
I removed  express.urlencoded({extended: true}) and it works.
