### ISSUE TITLE
[unhandledRejection] Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by chz** [nuxt/framework#1687]
### Environment

```
- Operating System: `Darwin`
- Node Version:     `v14.18.1`
- Nuxt Version:     `2.16.0-27266415.3ab12f9f`
- Package Manager:  `yarn@1.22.15`
- Bundler:          `Webpack`
- User Config:      `head`, `css`, `plugins`, `components`, `buildModules`, `modules`, `build`
- Runtime Modules:  `-`
- Build Modules:    `@nuxt/bridge@3.0.0-27266907.929a634`
```

### Describe the bug

```
 ERROR  [unhandledRejection] Cannot set headers after they are sent to the client                                                                                                                     14:23:45

  at new NodeError (internal/errors.js:322:7)
  at ServerResponse.setHeader (_http_outgoing.js:561:11)
  at send (node_modules/webpack-dev-middleware/dist/utils/compatibleAPI.js:68:7)
  at processRequest (node_modules/webpack-dev-middleware/dist/middleware.js:186:31)
  at ready (node_modules/webpack-dev-middleware/dist/utils/ready.js:11:12)
  at Object.middleware (node_modules/webpack-dev-middleware/dist/middleware.js:44:24)
  at node_modules/pify/index.js:33:11
  at new Promise (<anonymous>)
  at Object.<anonymous> (node_modules/pify/index.js:6:9)
  at Object.apply (node_modules/pify/index.js:80:20)
  at WebpackBundler.middleware (node_modules/@nuxt/webpack-edge/dist/webpack.js:1909:37)
  at middleware (node_modules/@nuxt/nitro/dist/index.mjs:1809:50)
  at node_modules/h3/dist/index.mjs:111:24
  at new Promise (<anonymous>)
  at callHandle (node_modules/h3/dist/index.mjs:108:10)
  at Object.handle (node_modules/h3/dist/index.mjs:104:12)
```

### Reproduction

Fresh install nuxt 2 and migrate to bridge following: https://v3.nuxtjs.org/getting-started/bridge

**Comment by Dinibewerbig** [comment]
Same problem here.

**Comment by Luferov** [comment]
I'm gotting this error when use apollo subscription. Maybe h3 have problem with sockets?

**Comment by Luferov** [comment]
When i use my MacBook i got this error, but if i use ubuntu os it's work fine!
I think this error in nodejs base macOS.
Because of, do reproduction almost impossible.

**Comment by misaon** [comment]
This is not bug only in Nuxt 2 bridge, this hapnes in Nuxt 3 too, when you use Nuxt under reverse proxy (descripted by @Diizzayy here https://github.com/nuxt/framework/issues/1021#issuecomment-947123482), Nitro or some base server logic in Nuxt part not process headers properly. @danielroe @pi0

**Comment by danielroe** [comment]
I'm closing as there is no reproduction provided. If you can provide one, I'll happily reopen.

**Comment by misaon** [comment]
@danielroe try run Nuxt3 Inside Docker with simple Nginx proxy_pass and you will get this error

**Comment by danielroe** [comment]
If you can provide me a reproduction, I'll do so 😊

**Comment by acidjazz** [comment]
I am getting this at times when I try to fetch a cookie with `useCookie`

**Comment by danielroe** [comment]
What is the content of your middleware?

**Comment by acidjazz** [comment]
> What is the content of your middleware?

```ts
import { useNuxtApp } from '#app'

export default defineNuxtRouteMiddleware(to => {
  const { $api } = useNuxtApp()
  if (to.path !== $api.config.redirect.logout && $api.loggedIn.value === false)
    return navigateTo($api.config.redirect.logout)
})
```


I think I tracked it down to when I do this in my auth library:


```ts
  private getToken(): string {
    if (this.config.req) return useCookie(this.config.req, 'token')
    return this.cookies.get('token')
  }
```

`this.config.req` is an instance of `IncomingRequest` from http

**Comment by Bjunk** [comment]
Same issue in Nuxt3 clean installation when I used public folder for an image tag start showing same error. If I use an external image src error disappear.

**Comment by birdlavv** [comment]
Could this be related to https://github.com/unjs/h3/issues/21 & https://github.com/unjs/h3/issues/35?

**Comment by Zac-Zajdel** [comment]
Same issue while using Mac OS on Apple Silicon. I do not have the same issue on Ubuntu or Windows.

**Comment by acidjazz** [comment]
<img width="897" alt="image" src="https://user-images.githubusercontent.com/967369/162595901-b984ae2b-fa8c-4a38-998a-d8b6371312a0.png">
