### ISSUE TITLE
Dynamic glob imports does not work with vite

### ISSUE THREAD

**Issue by pi0** [nuxt/framework#1693]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v14.16.0`
- Nuxt Version:     `3.0.0-27265876.3cd4494`
- Package Manager:  `npm@7.17.0`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Describe the bug

Unpredictable dynamic imports like `import(`~/data/${name}json)` does not work with vite (dev-bundler)

### Reproduction

https://stackblitz.com/edit/github-obezmd?file=app.vue

### Additional context

As a workaround, one can use webpack using `vite: false` in `nuxt.config`.

Missing implementation is [here](https://github.com/nuxt/framework/blob/9b8d44d130fb85397053185924f3b6b86243b362/packages/vite/src/dev-bundler.ts#L158) but we probably need more to fix this.

### Logs

```shell
Cannot read properties of undefined (reading 'stubModule')
at __instantiateModule__ (file://./.nuxt/dist/server/server.mjs:1771:11)
at __ssrLoadModule__ (file://./.nuxt/dist/server/server.mjs:1762:25)
at ssrImport (file://./.nuxt/dist/server/server.mjs:1787:13)
at ssrDynamicImport (file://./.nuxt/dist/server/server.mjs:1798:12)
at eval (file://./.nuxt/dist/server/server.mjs:1678:70)
at Module.withAsyncContext (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7295:21)
at setup (file://./.nuxt/dist/server/server.mjs:1678:47)
at _sfc_main.setup (file://./.nuxt/dist/server/server.mjs:1708:23)
at callWithErrorHandling (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6615:22)
at setupStatefulComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6241:29)
```

**Comment by AbrahemAlhofe** [comment]
Is there is any update on this issue because i have the same problem

**Comment by pi0** [comment]
@AbrahemAlhofe Unfortunately not yet. We would probably need a better vite dev SSR implementation (with on-demand bundling server) to make this possible.

**Comment by Blakeinstein** [comment]
Do we have an existing workaround? Or is putting images in public the only way to go?

**Comment by lacorde** [comment]
I would also be interested in a work around !

**Comment by Blakeinstein** [comment]
> I would also be interested in a work around !

Current workaround is to use webpack as the bundler instead of vite.

in your nuxt.config.ts set
```ts
export default defineNuxtConfig({
  ...
  vite: false,
  ...
})
```

**Comment by jerrywu001** [comment]
can not use unocss with `vite: false`

**Comment by b-avb** [comment]
Any other solution using vite and ssr?

**Comment by antfu** [comment]
Just checked, it works with vite-node, with:

```ts
export default defineNuxtConfig({
  experimental: {
    viteNode: true
  }
})
```

However, even it works in the runtime, the warning is still thrown by Vite. To bypass the warning, add `/* @vite-ignore */` to your import statement:

```ts
const pkg = await import(/* @vite-ignore */ '~/' + 'package.json').then((r) => r.default);
```

/cc @pi0 @patak-dev do you think we should be an option for vite to bypass this warning in this condition, or maybe this is just an anti-pattern we should ask users to be explicit about it?

**Comment by patak-dev** [comment]
We have a PR that should further help here:
- https://github.com/vitejs/vite/pull/7485

About the warning, I think it is too strict. But these are quite useful in most cases. I wonder if we should have a global option to disable them, or if we should not warn by default and have a new flag that would warn about "possible" issues that users could use to debug these problems.

**Comment by caoxiemeihao** [comment]
Now, I'll try [vite-plugin-dynamic-import](https://www.npmjs.com/package/vite-plugin-dynamic-import) to fix this error.  
But in the end, I hope it can be integrated into vite.

```js
import { defineNuxtConfig } from 'nuxt3';
import dynamicImport from 'vite-plugin-dynamic-import';

// https://v3.nuxtjs.org/docs/directory-structure/nuxt.config
export default defineNuxtConfig({
  vite: {
    plugins: [
      dynamicImport(),
    ],
  },
});

```

**Comment by silencerspirit** [comment]
Resolve problem by creating [functional component](https://github.com/jpkleemans/vite-svg-loader/issues/24#issuecomment-1162181560)

**Comment by zhouzilong2020** [comment]
> Now, I try to use [vite-plugin-dynamic-import](https://www.npmjs.com/package/vite-plugin-dynamic-import) to resolve this problem. But in the end, I hope it can be integrated into vite.
> 
> ```js
> import { defineNuxtConfig } from 'nuxt3';
> import dynamicImport from 'vite-plugin-dynamic-import';
> 
> // https://v3.nuxtjs.org/docs/directory-structure/nuxt.config
> export default defineNuxtConfig({
>   vite: {
>     plugins: [
>       dynamicImport(),
>     ],
>   },
> });
> ```

Cloud you please provide some demo on how to use this? 
I try this plugin but got ```Cannot read properties of undefined (reading 'stubModule')``` everytime.

**Comment by caoxiemeihao** [comment]
@zhouzilong2020 
`vite-plugin-import` is easy to use, It may not be the cause of your BUG.  
Can you provide a minimized demo? I may need to Debug it.

**Comment by mlsjla** [comment]
```
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
  at <[id] onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > key="/article/view/47492998283395072" > 
```

**Comment by engenes** [comment]
does this issue seem to have been fixed?
https://github.com/vitejs/vite/blob/v3.0.4/packages/vite/CHANGELOG.md#304-2022-07-29

**Comment by ennioVisco** [comment]
Indeed, besides, since `rc.9` `vite-node` is the new default. This issue should be closed. cc @pi0

**Comment by danielroe** [comment]
Thanks! Example: https://stackblitz.com/edit/github-l4ercq.

**Comment by lacorde** [comment]
@danielroe I'm trying to dynamically import images from the assets folder, using your stackblitz example.
```
<script setup>
const val = 'img';
const img = await import(`~/assets/images/${val}.png`).then((r) => r.default);
</script>
```
But I get the following error :
`TypeError: Failed to resolve module specifier '~/assets/images/img.png'`

Is it the right way of doing this ? What am I doing wrong ?

**Comment by danielroe** [comment]
@lacorde That sounds right. What's not working? Do you have a reproduction?

**Comment by lacorde** [comment]
My bad it was an unrelated issue, the code I provided works great for images !
Thank you for the quick answer.
