### ISSUE TITLE
[BUG] When trying to use Vue3-click-away with Pages directory

### ISSUE THREAD

**Issue by fmcdigital** [nuxt/framework#1695]
### Environment

npm run dev

### Describe the bug

When trying to use a custom directive like `v-click-away` and pages directory at same time, an error is thrown.

### Reproduction

1. Access the working sandbox: https://codesandbox.io/s/infallible-river-1be8h?file=/app.vue
2. Create a Pages directory and re-render, the following error will appear: Invalid value used as weak map key

Reproduction link with the issue: https://codesandbox.io/s/small-thunder-uro91?file=/pages/index.vue

### Logs

```shell
[Vue warn]: Failed to resolve component: App
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
Invalid value used as weak map key
  at WeakMap.set (<anonymous>)
  at normalizePropsOptions (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:2689:11)
  at createComponentInstance (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6115:23)
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:197:22)
  at Module.ssrRenderComponent (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:623:12)
  at _sfc_ssrRender (file://./.nuxt/dist/server/server.mjs:2020:31)
  at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:263:13)
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:214:16)
  at ./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:456:30
  at Generator.next (<anonymous>)
```

**Comment by danielroe** [comment]
This isn't caused by creating a pages directory - it's reproducible on https://codesandbox.io/s/infallible-river-1be8h?file=/app.vue too. The issue is that you haven't registered the clickaway directive on server-side.
