### ISSUE TITLE
Can't handle 

### ISSUE THREAD

**Issue by negezor** [nuxt/framework#1718]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.11.1`
- Nuxt Version:     `2.16.0-27267854.3ab12f9f`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Webpack`
- User Config:      `rootDir`, `modulesDir`, `dev`, `bridge`, `vite`, `env`, `publicRuntimeConfig`, `head`, `modules`, `css`, `buildModules`, `plugins`, `pwa`, `loading`, `build`, `telemetry`
- Runtime Modules:  `cookie-universal-nuxt@2.1.5`
- Build Modules:    `@nuxt/bridge@3.0.0-27267528.292b524`

### Describe the bug

Parsing error when using [numeric separator](https://github.com/tc39/proposal-numeric-separator)

### Reproduction

Any use of numeric separator
```ts
const randomNumber = 15_000;
```

### Logs

```shell
Module parse failed: Identifier directly after number (2:24)
File was processed with these loaders:
 * ../../node_modules/unplugin/dist/webpack/loaders/transform.js
 * ../../node_modules/babel-loader/lib/index.js
 * ../../node_modules/unplugin/dist/webpack/loaders/transform.js
You may need an additional loader to handle the result of these loaders.
| import{provide,inject,ref}from'@vue/composition-api';const kSnackbarQueue=Symbol('snackbarQueue');// 10 seconds
> const DEFAULT_TIMEOUT=10_000;export const provideSnackbar=()=>{provide(kSnackbarQueue,ref([]));};export const useSnackbar=()=>{const queue=inject(kSnackbarQueue);if(!queue){throw new Error('Snackbar not provided to App');}const remove=id=>{queue.value=queue.value.filter(item=>item.id!==id);};const add=options=>{var _options$timeout;const id=options.id||String(Math.random());const hasPreviousItem=queue.value.some(item=>item.id===id);if(hasPreviousItem){return;}queue.value.push({id,text:options.text,interval:setTimeout(()=>{remove(id);// eslint-disable-next-line no-undef
| },(_options$timeout=options.timeout)!==null&&_options$timeout!==void 0?_options$timeout:DEFAULT_TIMEOUT)});};return{queue,add,remove};};
  at Object../app/hooks/use-snackbar.ts (./app/.nuxt/dist/server/server.js:14729:7)  
  at __webpack_require__ (./app/.nuxt/dist/server/server.js:27:30)  
  at Module.../../node_modules/unplugin/dist/webpack/loaders/transform.js?!../../node_modules/babel-loader/lib/index.js?!../../node_modules/vue-loader/lib/index.js?!../../node_modules/unplugin/dist/webpack/loaders/transform.js?!../../node_modules/unplugin/dist/webpack/loaders/transform.js?!./app/layouts/dashboard.js?vue&type=script&lang=ts& (./app/.nuxt/dist/server/server.js:2473:77)  
  at __webpack_require__ (./app/.nuxt/dist/server/server.js:27:30)  
  at Module../app/layouts/dashboard.js?vue&type=script&lang=ts& (./app/.nuxt/dist/server/server.js:15608:395)  
  at __webpack_require__ (./app/.nuxt/dist/server/server.js:27:30)  
  at Module../app/layouts/dashboard.js (./app/.nuxt/dist/server/server.js:15569:97)  
  at __webpack_require__ (./app/.nuxt/dist/server/server.js:27:30)  
  at Module../app/.nuxt/App.js (./app/.nuxt/dist/server/server.js:5818:80)  
  at __webpack_require__ (./app/.nuxt/dist/server/server.js:27:30)
```
```

**Comment by danielroe** [comment]
**Repro**: https://codesandbox.io/s/staging-pond-9qt1g
