### ISSUE TITLE
(node:26630) Warning: To load an ES module - TipTap/vue-3

### ISSUE THREAD

**Issue by yustarandomname** [nuxt/framework#1911]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v17.0.1`
- Nuxt Version:     `3.0.0-27277498.850ef69`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `css`, `buildModules`, `meta`, `vite`, `vue`
- Runtime Modules:  `-`
- Build Modules:    `@nuxtjs/pwa@3.3.5`
------------------------------

### Reproduction

https://codesandbox.io/s/proud-microservice-wj1ke?file=/pages/index.vue

### Describe the bug

Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)

Is what is displayed when I import `@tiptap/vue-3` to my nuxt3 project. 

Are there any quick fixes or workarounds?

### Logs

```shell
(node:115) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/sandbox/node_modules/@popperjs/core/lib/enums.js:1
export var top = 'top';
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:199:29)
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async __instantiateModule__ (file:///sandbox/.nuxt/dist/server/server.mjs:26241:3)
[Vue Router warn]: uncaught error during route navigation:
Error: [vite dev] Error loading external "/sandbox/node_modules/@popperjs/core/lib/enums.js".
    at file:///sandbox/.nuxt/dist/server/server.mjs:22626:262
    at async __instantiateModule__ (file:///sandbox/.nuxt/dist/server/server.mjs:26241:3)
[vite dev] Error loading external "/sandbox/node_modules/@popperjs/core/lib/enums.js".
  at file://./.nuxt/dist/server/server.mjs:22626:262
  at async __instantiateModule__ (file://./.nuxt/dist/server/server.mjs:26241:3)
(node:115) UnhandledPromiseRejectionWarning: Error: [vite dev] Error loading external "/sandbox/node_modules/@popperjs/core/lib/enums.js".
    at file:///sandbox/.nuxt/dist/server/server.mjs:22626:262
    at async __instantiateModule__ (file:///sandbox/.nuxt/dist/server/server.mjs:26241:3)
(node:115) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:115) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Vue Router warn]: uncaught error during route navigation:
TypeError: Cannot read property '__vccOpts' of undefined
    at /sandbox/node_modules/vue-router/dist/vue-router.cjs.js:2022:55
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Cannot read property '__vccOpts' of undefined
  at ./node_modules/vue-router/dist/vue-router.cjs.js:2022:55
  at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:115) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '__vccOpts' of undefined
    at /sandbox/node_modules/vue-router/dist/vue-router.cjs.js:2022:55
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:115) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
```

**Comment by danielroe** [comment]
This is an issue originating with `@popperjs/core`. See https://v3.nuxtjs.org/concepts/esm for more info.

**Comment by geetfun** [comment]
Thanks @danielroe for the link.

That seemed to fix it.

```
// nuxt.config.ts or similar
export default defineNuxtConfig({
  build: {
    transpile: ['@popperjs']
  },
})
```
