### ISSUE TITLE
Polyfill cjs globals for vite

### ISSUE THREAD

**Issue by pi0** [nuxt/framework#1922]
Ref #1835, #1862

Vite considers source input as native ESM while some dependencies might depend on Node.js/CJS globals like `module` and `global`. Doing polyfill can mitigate this potential issue (also making it more consistent with webpack that handles CJS at some level)

We can do it with unenv (#1502) or before that...

**Comment by abhay-agarwal** [comment]
For certain libraries, e.g. `@segment/analytics-next`, doing a `yarn build` yields the error `ReferenceError: Can't find variable: global`. I am able to solve this in my development environment by adding a polyfill to my vite configuration:

```ts
export default defineNuxtConfig({
  vite: {
    define: {
      global: {},
    },
  }
})
```

but when I try to build using `yarn build` I receive the following error:

```
 ERROR  Unexpected token (Note that you need plugins to import files that are not JavaScript)                    15:05:04
file: /Users/abhay/workspace/poly/client/node_modules/nuxt/dist/pages/runtime/router.mjs:69:4
67:   nuxtApp._activeRoute = reactive(activeRoute);
68:   nuxtApp._middleware = nuxtApp._middleware || {
69:     global: [],
        ^
70:     named: {}
71:   };


 ERROR  Unexpected token (Note that you need plugins to import files that are not JavaScript)                    15:05:04

  at error (node_modules/rollup/dist/shared/rollup.js:198:30)
  at Module.error (node_modules/rollup/dist/shared/rollup.js:12521:16)
  at Module.tryParse (node_modules/rollup/dist/shared/rollup.js:12897:25)
  at Module.setSource (node_modules/rollup/dist/shared/rollup.js:12800:24)
  at ModuleLoader.addModuleSource (node_modules/rollup/dist/shared/rollup.js:22264:20)

error Command failed with exit code 1.
```

Any ideas of how to fix?

**Comment by LuXDAmore** [comment]
+1
