### ISSUE TITLE
exports is not defined is ES module scope - still not working

### ISSUE THREAD

**Issue by sweepy84** [nuxt/framework#2070]
### Environment

Nuxt project info:                                                                                                                                                                           20:15:00

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27292434.d68318f`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `build`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/sweepy84/nuxt3

### Describe the bug

A fresh nuxt3 project fails when installing 'aws-amplify' as a plugin.

### Replication of Bug

Steps performed
1. npx nuxi init nuxt3
2. yarn install
3. yarn add aws-amplify
4. Added 'amplify.ts' to /plugins directory
5. Added transpiling config to 'nuxt.config.ts'
6. yarn dev

### Additional context

I know this was logged here https://github.com/nuxt/framework/issues/1573
and was supposed to be fixed with mlly fix but this did not solve problem for me even with latest fixes!

### Logs

```shell
exports is not defined in ES module scope
  at $id_8b3bdae3 (file://./.nuxt/dist/server/server.mjs:3539:23)  
  at __instantiateModule__ (file://./.nuxt/dist/server/server.mjs:31429:9)  
  at __ssrLoadModule__ (file://./.nuxt/dist/server/server.mjs:31376:25)  
  at ssrImport (file://./.nuxt/dist/server/server.mjs:31401:13)  
  at $id_d9f142a1 (file://./.nuxt/dist/server/server.mjs:3206:37)  
  at async __instantiateModule__ (file://./.nuxt/dist/server/server.mjs:31429:3)
```

**Comment by sweepy84** [comment]
Nuxt project info:                                                                                                                                                                          

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27292434.d68318f`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `build`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

**Comment by AXSJ** [comment]
I am having the exact same issue

**Comment by danielroe** [comment]
This is an upstream issue, likely with the aws libraries. You can read more in https://v3.nuxtjs.org/concepts/esm/.

I'll leave this open for now (pending further investigation) in case there's anything we can do to improve matters within nuxt.

**Comment by sweepy84** [comment]
Hi @danielroe  - appreciate the response.

**Comment by sweepy84** [comment]
hi @danielroe - appreciate the response.

However I'm still struggling to understand how I can solve this problem so I can use Amplify (and other libraries) with Nuxt3.

**Comment by joshkoppang** [comment]
Same for us with [Solana Wallet Adapter](https://github.com/solana-labs/wallet-adapter). When we follow the chain with transpile, we just end up with 'require is not defined.' We are willing to push on upstream providers, but need direction on what needs to be done.

**Comment by sweepy84** [comment]
Getting so many of these errors - SO MANY package developers use folders rather the mis/cjs extensions. I think its appropriate to address this in a way that caters to current conventions.

**Comment by joshkoppang** [comment]
Any direction/help here? Happy to push on other providers, but want something that works.

**Comment by timhanlon** [comment]
@joshkoppang I eventually got it to build: https://stillearly.io/article/how-i-got-solana-working-with-nuxt-3/

**Comment by ennioVisco** [comment]
Refer to https://github.com/nuxt/framework/issues/2874#issuecomment-1046285059 for a solution of the issue (at least in the case of `aws-amplify`).
