### ISSUE TITLE
Calling `useRuntimeConfig` in plugin scope raise exception

### ISSUE THREAD

**Issue by farnabaz** [nuxt/framework#2161]
### Environment

```
------------------------------
- Operating System: `Linux`
- Node Version:     `v14.18.1`
- Nuxt Version:     `2.16.0-27298095.ab1c6cb4`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Webpack`
- User Config:      `plugins`, `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `@nuxt/bridge@3.0.0-27296423.f3082ca`
------------------------------
```

### Reproduction

SandBox: https://codesandbox.io/s/admiring-kowalevski-ohcub?file=/nuxt.config.js

### Describe the bug

Calling `useRuntimeConfig` inside a plugin raise `nuxt app instance unavailable` exception

### Logs

```shell
nuxt app instance unavailable
  at useNuxtApp (./.nuxt/dist/server/server.js:2752:13)
  at useRuntimeConfig (./.nuxt/dist/server/server.js:3084:78)
  at ./.nuxt/dist/server/server.js:20957:79
  at createApp (./.nuxt/dist/server/server.js:1121:85)
  at async module.exports../.nuxt/server.js.__webpack_exports__.default (./.nuxt/dist/server/server.js:1783:7)
  at async renderToString (file://./node_modules/vue-bundle-renderer/dist/index.mjs:254:19)
  at async renderMiddleware (file://./.nuxt/nitro/index.mjs:186:20)
  at async handle (file://./node_modules/h3/dist/index.mjs:598:19)
```

**Comment by pi0** [comment]
Thanks for making reprodution. I think we need same patch of nuxt 3 (https://github.com/nuxt/framework/pull/2114) for bridge's plugin ececutation

**Comment by danielroe** [comment]
For `useNuxtApp` support in Bridge, you'll need to wrap it in `defineNuxtPlugin`

https://codesandbox.io/s/condescending-dirac-kynuw?file=/plugins/test.ts
