### ISSUE TITLE
__vite_ssr_import_3__.omit

### ISSUE THREAD

**Issue by productdevbook** [nuxt/framework#2178]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27296423.f3082ca`
- Package Manager:  `yarn@1.22.15`
- Bundler:          `Vite`
- User Config:      `server`, `head`, `buildModules`, `build`, `unocss`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `@unocss/nuxt@0.12.2`, `@vueuse/core/nuxt@7.0.0`, `@pinia/nuxt@0.1.5`
------------------------------

### Reproduction
brach: vite_ssr_import
[vite_ssr_import](https://github.com/productdevbook/nuxt3-bug/tree/vite_ssr_import)

### Describe the bug

yarn dev

### Logs

```shell
__vite_ssr_import_3__.omit is not a function
  at ReactiveEffect.fn (file://./.nuxt/dist/server/server.mjs:20735:83)  
  at ReactiveEffect.run (./node_modules/@vue/reactivity/dist/reactivity.cjs.js:164:29)  
  at ComputedRefImpl.get value [as value] (./node_modules/@vue/reactivity/dist/reactivity.cjs.js:1075:39)  
  at unref (./node_modules/@vue/reactivity/dist/reactivity.cjs.js:989:29)  
  at Object.get (./node_modules/@vue/reactivity/dist/reactivity.cjs.js:992:37)  
  at Object.get (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5900:34)  
  at file://./.nuxt/dist/server/server.mjs:20891:13  
  at Module.ssrRenderSlot (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:663:9)  
  at _sfc_ssrRender (file://./.nuxt/dist/server/server.mjs:20887:25)  
  at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:263:13)
```

**Comment by danielroe** [comment]
Would you provide a minimal reproduction? 🙏

**Comment by productdevbook** [comment]
@danielroe yes sure, brach: vite_ssr_import
[vite_ssr_import](https://github.com/productdevbook/nuxt3-bug/tree/vite_ssr_import)

**Comment by danielroe** [comment]
It's an issue with lodash - use instead;
```js
import omit from 'lodash/omit'
```
