### ISSUE TITLE
Internal server error - Object(...) is not a function on page load

### ISSUE THREAD

**Issue by kadlinobit** [nuxt/framework#2233]
### Environment

- Operating System: `Linux`
- Node Version:     `v14.17.3`
- Nuxt Version:     `2.16.0-27296655.ab1c6cb4`
- Package Manager:  `npm@6.14.13`
- Bundler:          `Webpack`
- User Config:      `bridge`, `head`, `css`, `plugins`, `components`, `buildModules`, `modules`, `i18n`, `axios`, `auth`, `strapi`, `build`, `publicRuntimeConfig`, `privateRuntimeConfig`
- Runtime Modules:  `@nuxtjs/axios@5.13.6`, `@nuxtjs/auth@4.9.1`, `@nuxtjs/strapi@0.3.4`, `@nuxtjs/i18n@7.2.0`
- Build Modules:    `@nuxtjs/eslint-module@3.0.2`, `@nuxt/bridge@3.0.0-27296423.f3082ca`

### Reproduction

Github repo (nuxt-3-bridge branch)
https://github.com/kadlinobit/djspot-fe/tree/nuxt-3-bridge

### Describe the bug

When nuxt server is starting, there is a warning message:
```
 in ./.nuxt/runtime.app.plugin.75f1febc.mjs                                                                                                                                    
"export 'createHooks' was not found in 'hookable'       
```
Nuxt starts, but when I try to load homepage, I get this error:
```
Object(...) is not a function
  at module.exports../.nuxt/runtime.app.plugin.75f1febc.mjs.__webpack_exports__.default (./.nuxt/dist/server/server.js:5378:79)  
  at createApp (./.nuxt/dist/server/server.js:2868:105)  
  at async module.exports../.nuxt/server.js.__webpack_exports__.default (./.nuxt/dist/server/server.js:5547:7)  
  at async renderToString (file://./node_modules/vue-bundle-renderer/dist/index.mjs:254:19)  
  at async renderMiddleware (file://./.nuxt/nitro/index.mjs:186:20)  
  at async handle (file://./node_modules/h3/dist/index.mjs:598:19)
```

**Comment by danielroe** [comment]
Could you manually upgrade `hookable` or run `yarn add --dev hookable` to your project?

**Comment by kadlinobit** [comment]
> Could you manually upgrade `hookable` or run `yarn add --dev hookable` to your project?

Did that, now the dev server fails on startup with following error:

```
/home/kadlino/projects/djspot/djspot-fe/node_modules/@nuxt/bridge/bin/nuxt.mjs:2
import 'nuxi/cli'
       ^^^^^^^^^^

SyntaxError: Unexpected string
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```
Also tried deleting node_modules and reinstall the whole project, but didn't help.

**Comment by danielroe** [comment]
@kadlinobit For that issue, follow https://github.com/nuxt/framework/issues/2006 (or install `@nuxt/kit-edge` explicitly or use a newer version of npm):
```json
{
  "devDependencies": {
    "@nuxt/kit": "npm:@nuxt/kit-edge@3.0.0-27296423.f3082ca"
  }
}
```

After installing `@nuxt/kit`, I encountered https://github.com/nuxt/framework/issues/1151 - I've documented a workaround there.

**Comment by justindasilva** [comment]
> yarn add --dev hookable

I was getting:
```
Object(...) is not a function
  at module.exports../.nuxt/runtime.app.plugin.14a29de2.mjs.__webpack_exports__.default (./.nuxt/dist/server/server.js:744:1094) 
```

and this solved my issue.
