### ISSUE TITLE
useCookies causes Nuxt not to work compiled on Windows

### ISSUE THREAD

**Issue by frbuceta** [nuxt/framework#2248]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27303148.ac98373`
- Package Manager:  `npm@8.1.0`
- Bundler:          `Vite`
- User Config:      `css`, `watch`, `build`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://codesandbox.io/s/gfoqc

### Describe the bug

It seems that when Nuxt is compiled and used (compiled) on Windows it fails by using the useCookies function.On macOS it works!

### Logs

```shell
TypeError: Cannot read properties of undefined (reading 'default')
    at useCookie (file:///C:/Users/josea/Documents/GitHub/mailchimp-campaign-creator/.output/server/chunks/server.mjs:3628:84)
    at setup (file:///C:/Users/josea/Documents/GitHub/mailchimp-campaign-creator/.output/server/chunks/server.mjs:6852:20)
    at _sfc_main$2.setup (file:///C:/Users/josea/Documents/GitHub/mailchimp-campaign-creator/.output/server/chunks/server.mjs:7065:25)
    at callWithErrorHandling (file:///C:/Users/josea/Documents/GitHub/mailchimp-campaign-creator/.output/server/chunks/index2.mjs:7159:22)
    at setupStatefulComponent (file:///C:/Users/josea/Documents/GitHub/mailchimp-campaign-creator/.output/server/chunks/index2.mjs:6875:29)
    at setupComponent (file:///C:/Users/josea/Documents/GitHub/mailchimp-campaign-creator/.output/server/chunks/index2.mjs:6856:11)
    at renderComponentVNode (file:///C:/Users/josea/Documents/GitHub/mailchimp-campaign-creator/.output/server/chunks/index2.mjs:9765:17)
    at renderVNode (file:///C:/Users/josea/Documents/GitHub/mailchimp-campaign-creator/.output/server/chunks/index2.mjs:9871:22)
    at renderComponentSubTree (file:///C:/Users/josea/Documents/GitHub/mailchimp-campaign-creator/.output/server/chunks/index2.mjs:9836:13)
    at file:///C:/Users/josea/Documents/GitHub/mailchimp-campaign-creator/.output/server/chunks/index2.mjs:9778:29
[Vue warn]: Component  is missing template or render function.
```

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏

**Comment by frbuceta** [comment]
> Would you provide a reproduction? 🙏

How do I reproduce it in a Windows environment?

I am using it as follows:
```
<script setup>
...
const locales = [
  { code: 'es', name: { 'es': 'Español', 'en': 'Spanish' } },
  { code: 'en', name: { 'es': 'Inglés', 'en': 'English' } }
]
const locale = useCookie('locale')
locale.value = locale.value || 'es'
...
</script>
```

and

<script>
...
export default {
...
  setup: () => ({
    ...
    t$: function (path) {
      const locale = ref('es')
      // const locale = useCookie('locale')
      return _.get(messages, `${locale.value}.${path}`, messages['en'][path])
    }
  })
...
}
</script>

**Comment by frbuceta** [comment]
> @frbuceta By a reproduction, I mean:
> 
> > Please provide a link to a repo that can reproduce the problem you ran into. A [minimal reproduction](https://v3.nuxtjs.org/community/reporting-bugs#create-a-minimal-reproduction) is required unless you are absolutely sure that the issue is obvious and the provided information is enough to understand the problem. If a report is vague (e.g. just a generic error message) and has no reproduction, it will receive a "need reproduction" label. If no reproduction is provided we might close it.

It seems that codesandbox also fails, I have already uploaded the reproduction.

**Comment by nndnha** [comment]
I think there is a typo error in this line that causes this bug https://github.com/nuxt/framework/blob/010febd1b3dde2bdac2f246156724bbb2571932b/packages/nuxt3/src/app/composables/cookie.ts#L28

It should be **opts.default** instead of **_opts.default**

**Comment by danielroe** [comment]
@frbuceta It sounds to me like it might be a browser compatibility issue, if it's reproducing on the codesandbox (but only on Windows). What browsers are you testing this with, and which versions?
