### ISSUE TITLE
Adding plugin causes: Error loading external "fs"

### ISSUE THREAD

**Issue by tony19** [nuxt/framework#2257]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.12.0`
- Nuxt Version:     `3.0.0-27306529.1ef6e3f`
- Package Manager:  `npm@8.1.0`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt3-plugins-bug-error-loading-external-fs?file=plugins/my-plugin.ts

Steps to reproduce:

1. Scaffold new Nuxt 3 project with `npx nuxi init my-project`
2. Create `plugins/my-plugin.ts` with the following contents:

```typescript
import { defineNuxtPlugin } from 'nuxt3'
export default defineNuxtPlugin(nuxtApp => {})
```

 3. Observe the error in the terminal

### Describe the bug

Setting up a Nuxt plugin per the [docs](https://v3.nuxtjs.org/docs/directory-structure/plugins#vue-plugins) results in this error:

```
Error transforming /home/projects/nuxt3-plugins-bug-error-loading-external-fs/node_modules/@nuxt/nitro/dist/index.mjs: Error: Parse failure: Unexpected token (808:8)
Contents of line 808:       ""development"": nitroContext._nuxt.dev ? '"development"' : '"production"',
⋮
Error loading external "fs"
```

### Logs

```shell
Nuxt CLI v3.0.0-27306529.1ef6e3f                                                                                                                         18:05:56
                                                                                                                                                         18:05:57
  > Local:    http://localhost:3000/ 
  > Network:  http://192.168.1.104:3000/

ℹ Vite warmed up in 460ms                                                                                                                                18:06:01

 WARN  6:06:04 PM [vite] Failed to load source map for /node_modules/webpack-virtual-modules/lib/index.js.                                               18:06:04


 WARN  6:06:04 PM [vite] Failed to load source map for /node_modules/table/dist/src/index.js.                                                            18:06:04


 WARN  [SSR] Error transforming /home/projects/nuxt3-plugins-bug-error-loading-external-fs/node_modules/@nuxt/nitro/dist/index.mjs: Error: Parse failure: Unexpected token (808:8)
Contents of line 808:       ""development"": nitroContext._nuxt.dev ? '"development"' : '"production"',

✔ Vite server built in 5579ms                                                                                                                            18:06:07
✔ Nitro built in 167 ms                                                                                                                                  18:06:07
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/projects/nuxt3-plugins-bug-error-loading-external-fs/fs' imported from /home/projects/nuxt3-plugins-bug-error-loading-external-fs/.nuxt/dist/server/server.mjs
    at https://nuxt3-plugins-bug-error-loading-external-fs.w.staticblitz.com/blitz.6c82f838340a5d37c50f004ca724bcc8f75bc71c.js:6:478785
    at https://nuxt3-plugins-bug-error-loading-external-fs.w.staticblitz.com/blitz.6c82f838340a5d37c50f004ca724bcc8f75bc71c.js:6:478832
    at Loader.defaultResolve [as _resolve] (https://nuxt3-plugins-bug-error-loading-external-fs.w.staticblitz.com/blitz.6c82f838340a5d37c50f004ca724bcc8f75bc71c.js:6:478838)
    at Loader.resolve (https://nuxt3-plugins-bug-error-loading-external-fs.w.staticblitz.com/blitz.6c82f838340a5d37c50f004ca724bcc8f75bc71c.js:6:864915)
    at Loader.getModuleJob (https://nuxt3-plugins-bug-error-loading-external-fs.w.staticblitz.com/blitz.6c82f838340a5d37c50f004ca724bcc8f75bc71c.js:6:866839)
    at Loader.import (https://nuxt3-plugins-bug-error-loading-external-fs.w.staticblitz.com/blitz.6c82f838340a5d37c50f004ca724bcc8f75bc71c.js:6:865931)
    at importModuleDynamically (https://nuxt3-plugins-bug-error-loading-external-fs.w.staticblitz.com/blitz.6c82f838340a5d37c50f004ca724bcc8f75bc71c.js:6:736323)
    at r.importModuleDynamicallyCallback (https://nuxt3-plugins-bug-error-loading-external-fs.w.staticblitz.com/blitz.6c82f838340a5d37c50f004ca724bcc8f75bc71c.js:6:249478)
    at _0x1c5be0 (https://nuxt3-plugins-bug-error-loading-external-fs.w.staticblitz.com/blitz.6c82f838340a5d37c50f004ca724bcc8f75bc71c.js:11:191910)
    at $id_dce7cce0 (file:///home/projects/nuxt3-plugins-bug-error-loading-external-fs/.nuxt/dist/server/server.mjs:2926:98) {
  code: 'ERR_MODULE_NOT_FOUND'
}
[vite dev] Error loading external "fs".
  at async eval (file://./.nuxt/nitro/index.mjs:149:24)  
  at async renderMiddleware (file://./.nuxt/nitro/index.mjs:193:20)  
  at async handle (file://./node_modules/h3/dist/index.mjs:635:19)
```

**Comment by danielroe** [comment]
You should either rely on auto-imports for `defineNuxtPlugin`, or import it from `#app`. [Docs](https://v3.nuxtjs.org/docs/directory-structure/plugins/).

**Comment by Baroshem** [comment]
It helped my case too. Thanks @danielroe ! 

In my case the issue was caused by using:
```ts
import { useNuxtApp, useState } from "nuxt3"
```
In my composable but I was using #app in my plugin so at first I did not know why it does not work.

You have to make sure that you are not mixing #app with nuxt3 anywhere in your app nor external plugin.
