### ISSUE TITLE
Built project fails to import uuid package

### ISSUE THREAD

**Issue by n3wsw3** [nuxt/framework#2371]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v17.1.0`
- Nuxt Version:     `3.0.0-27319101.3e82f0f`
- Package Manager:  `npm@8.1.2`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

1. Run `npx nuxi init nux3-app`
2. Add `server/api/test.ts`
```ts
import { v4 } from "uuid";

export default () => {
  return v4();
};
```
3. `npm i uuid`
4. `npm i -D @types/uuid`
5. Change `app.vue`
```vue
<template>
  <div>
    {{ hu }}
  </div>
</template>

<script lang="ts" setup>
const hu = ref<string>(await $fetch("/api/test"));
</script>
```
6. `npm run build`
7. `node .output/server/index.mjs`
8. goto `localhost:3000`

### Describe the bug

Building the project causes the package `uuid` to fail to be imported. The problem does not exist when running the dev server.

### Logs

```shell
Cannot find module '/home/me/dev/nuxt3-app/.output/server/node_modules/uuid/wrapper.mjs' imported from /home/me/dev/nuxt3-app/.output/server/chunks/test.mjs
  at new NodeError (node:internal/errors:371:5)  
  at finalizeResolution (node:internal/modules/esm/resolve:394:11)  
  at moduleResolve (node:internal/modules/esm/resolve:915:10)  
  at defaultResolve (node:internal/modules/esm/resolve:1005:11)  
  at ESMLoader.resolve (node:internal/modules/esm/loader:475:30)  
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:245:18)  
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:79:40)  
  at link (node:internal/modules/esm/module_job:78:36)
```

**Comment by danielroe** [comment]
Let's follow in https://github.com/nuxt/framework/issues/2050.

**Comment by 5v3n-08** [comment]
When I use this work around, I get the following error:

```
m.default is not a function
  at file://./.nuxt/dist/server/server.mjs:10:126  
  at processTicksAndRejections (node:internal/process/task_queues:96:5)  
  at async renderToString (file://./node_modules/vue-bundle-renderer/dist/index.mjs:248:19)  
  at async renderMiddleware (file://./.nuxt/nitro/index.mjs:191:20)  
  at async handle (file://./node_modules/h3/dist/index.mjs:601:19)
```

**Comment by fosterdouglas** [comment]
> [<img alt="@danielroe" width="20" height="20" src="https://avatars.githubusercontent.com/u/28706372?s=60&amp;u=4a401a8a0f03e301ab349d6ecf5d4df0225f0cc5&amp;v=4">](/danielroe) [danielroe](/danielroe) added [ bug ](/nuxt/framework/labels/bug) [ nitro ](/nuxt/framework/labels/nitro) and removed [ nuxt3 ](/nuxt/framework/labels/nuxt3) [ pending triage ](/nuxt/framework/labels/pending%20triage) labels [25 days ago](#event-5760424423)

I'm getting the same error with the same setup @5v3n-08 did you find a way around this?

**Comment by pi0** [comment]
Hi. I'm moving this issue to https://github.com/unjs/nitro/issues/87 in order to track.
