### ISSUE TITLE
Cannot start nuxt: Named export 'ESBuildMinifyPlugin' not found

### ISSUE THREAD

**Issue by gsmeira** [nuxt/framework#2372]
### Environment

- Operating System: `Linux`
- Node Version: `v16.13.0`
- Nuxt Version: `3.0.0-27319101.3e82f0f`
- Package Manager: `yarn@1.22.15`
- Bundler: `Webpack`
- User Config: `vite`
- Runtime Modules: `-`
- Build Modules:  `-`

### Reproduction

1. `npx nuxi init nuxt3-app`
2. `cd nuxt3-app`
3. `yarn install`
4. Add `vite: false` to `nuxt.config.js`
5. `yarn dev`

### Describe the bug

```
ERROR  Cannot start nuxt:  Named export 'ESBuildMinifyPlugin' not found. The requested module 'esbuild-loader' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'esbuild-loader';
const { ESBuildMinifyPlugin } = pkg;


  import { ESBuildMinifyPlugin } from 'esbuild-loader';
  ^^^^^^^^^^^^^^^^^^^
  SyntaxError: Named export 'ESBuildMinifyPlugin' not found. The requested module 'esbuild-loader' is a CommonJS module, which may not support all module.exports as named exports.
  CommonJS modules can always be imported via the default export, for example using:
  
  import pkg from 'esbuild-loader';
  const { ESBuildMinifyPlugin } = pkg;
  
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:181:5)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
  at async bundle (node_modules/nuxt3/dist/index.mjs:1156:31)
  at async build (node_modules/nuxt3/dist/index.mjs:1132:3)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6719:9)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6756:5)
  at async _main (node_modules/nuxi/dist/chunks/index.mjs:382:7)

```

**Comment by kenta92** [comment]
+1

**Comment by danielroe** [comment]
For now, you can workaround this by pinning `esbuild-loader` to the previous minor version. For example, with yarn:
```json
  "resolutions": {
    "esbuild-loader": "2.16.0"
  }
```

**Comment by tianz-1992** [comment]
+1

**Comment by bashess** [comment]
it works also with npm 8.3.0 
```
  "overrides": {
    "esbuild-loader": "2.16.0"
  }
```

**Comment by myso-kr** [comment]
+1

**Comment by wangjing013** [comment]
same issue
