### ISSUE TITLE
Upgrade project fails on esbuild dependency

### ISSUE THREAD

**Issue by nandi95** [nuxt/framework#2457]
### Environment

```
------------------------------
- Operating System: `Darwin`
- Node Version:     `v17.0.1`
- Nuxt Version:     `3.0.0-27333290.a1a2d2f`
- Package Manager:  `npm@8.1.0`
- Bundler:          `Webpack`
- User Config:      `publicRuntimeConfig`, `srcDir`, `ssr`, `target`, `vite`, `typescript`, `build`, `meta`, `css`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
```

### Reproduction

https://github.com/nandi95/nuxt-starter

Install this with `npm ci` then try and upgrade nuxt

### Describe the bug

After upgrading nuxt version I get an error with esbuild

I tried to step through which version breaks it, and it seems this happens as soon as I install: (which makes no sense to me 😳 )
https://github.com/nuxt/framework/commit/fb33033f454e53cf3a65ccd81678200df428cdbd

### Additional context

The diff of all changes from the curretn version to the latest: https://github.com/nuxt/framework/compare/1c88580...daec432

### Logs

```shell
ERROR  Cannot start nuxt:  Named export 'ESBuildMinifyPlugin' not found. The requested module 'esbuild-loader' is a CommonJS module, which may not support all module.exports as named exports.              10:57:05
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'esbuild-loader';
const { ESBuildMinifyPlugin } = pkg;


  import { ESBuildMinifyPlugin } from 'esbuild-loader';
  ^^^^^^^^^^^^^^^^^^^
  SyntaxError: Named export 'ESBuildMinifyPlugin' not found. The requested module 'esbuild-loader' is a CommonJS module, which may not support all module.exports as named exports.
  CommonJS modules can always be imported via the default export, for example using:
  
  import pkg from 'esbuild-loader';
  const { ESBuildMinifyPlugin } = pkg;
  
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:181:5)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
  at async bundle (node_modules/nuxt3/dist/index.mjs:1156:31)
  at async build (node_modules/nuxt3/dist/index.mjs:1132:3)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6719:9)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6756:5)
  at async _main (node_modules/nuxi/dist/chunks/index.mjs:382:7)
```
```

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/framework/issues/2372
