### ISSUE TITLE
Fresh Nuxt 2 and Bridge giving errors in components when using v-on events - `defineComponent is not defined`

### ISSUE THREAD

**Issue by Jamiewarb** [nuxt/framework#2466]
### Environment

Nuxt CLI v3.0.0-27333388.c824905                                                                                                  16:10:20
RootDir: /Users/jamie/Sites/bignight/define-component                                                                             16:10:20
Nuxt project info:                                                                                                                16:10:20

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `2.16.0-27332655.777a4b7f`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Webpack`
- User Config:      `head`, `css`, `plugins`, `components`, `buildModules`, `modules`, `build`
- Runtime Modules:  `-`
- Build Modules:    `@nuxtjs/stylelint-module@4.1.0`, `@nuxt/bridge@3.0.0-27333388.c824905`
------------------------------

### Reproduction

Please see this repo for a full reproduction: https://github.com/Jamiewarb/repro-define-component

### Describe the bug

When adding a component that handles an event with `v-on`, I'm sometimes getting the error `defineComponent is not defined`.

In the reproduction, this only occurs when there are two elements in the component that both handle an event.

### Logs

```shell
ERROR  [worker] defineComponent is not defined                                                                                   16:05:32

  at Module../node_modules/unplugin/dist/webpack/loaders/transform.js?!./node_modules/babel-loader/lib/index.js?!./node_modules/vue-loader/lib/index.js?!./node_modules/unplugin/dist/webpack/loaders/transform.js?!./node_modules/unplugin/dist/webpack/loaders/transform.js?!./components/Test.vue?vue&type=script&lang=js& (.nuxt/dist/server/server.js:6838:30)
  at __webpack_require__ (.nuxt/dist/server/server.js:27:30)
  at Module../components/Test.vue?vue&type=script&lang=js& (.nuxt/dist/server/server.js:2700:390)
  at __webpack_require__ (.nuxt/dist/server/server.js:27:30)
  at Module../components/Test.vue (.nuxt/dist/server/server.js:2666:92)
  at __webpack_require__ (.nuxt/dist/server/server.js:27:30)
  at Module../.nuxt/components/index.js (.nuxt/dist/server/server.js:367:78)
  at __webpack_require__ (.nuxt/dist/server/server.js:27:30)
  at Module../.nuxt/components/plugin.js (.nuxt/dist/server/server.js:817:64)
  at __webpack_require__ (.nuxt/dist/server/server.js:27:30)
```

**Comment by Jamiewarb** [comment]
@danielroe Not sure if at all related, but I see the same error in #2465 when discussing vue test utils

**Comment by rvmourik** [comment]
@Jamiewarb I am experiencing the same, did you find any other solutions besides importing it with an alias.

**Comment by rodrigogs** [comment]
Same here :/

**Comment by Tyraxaes** [comment]
Same problem here, without alias is not possible to work around it. Any solutions?

**Comment by danielroe** [comment]
cc: @antfu
