### ISSUE TITLE
Vue Luxon gives unexpected token 'export'

### ISSUE THREAD

**Issue by yustarandomname** [nuxt/framework#2467]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27333388.c824905`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://codesandbox.io/s/holy-smoke-de3gv?file=/plugins/luxon.ts

### Describe the bug

Vue Luxon `SyntaxError: Unexpected token 'export'`. Is there a quick workaround for this issue.
Luxon has a vanilla js package as well, however the node version is more useful for use. 

### Additional context

[luxon documentation](https://moment.github.io/luxon)

### Logs

```shell
export class InvalidDateTimeError extends LuxonError {
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:199:29)
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async __instantiateModule__ (file:///sandbox/.nuxt/dist/server/server.mjs:9842:3)
[vite dev] Error loading external "/sandbox/node_modules/luxon/src/errors.js".
  at file://./.nuxt/dist/server/server.mjs:4848:254
```

**Comment by danielroe** [comment]
Hopefully this will be helpful: https://v3.nuxtjs.org/concepts/esm/

**Comment by danielroe** [comment]
I had a brief look and it doesn't seem that `vue-luxon` has support for Vue 3, but if it did, this would help:

```js
import { defineNuxtConfig } from "nuxt3";

// https://v3.nuxtjs.org/docs/directory-structure/nuxt.config
export default defineNuxtConfig({
  build: { transpile: [/luxon/] }
});
```
