### ISSUE TITLE
could not download https://github.com/nuxt/starter/archive/xxx.tar.gz

### ISSUE THREAD

**Issue by phgap** [nuxt/framework#2529]
### Environment

Nuxt CLI v3.0.0-27338323.1e98259
RootDir: /Users/xxx/vue-tutorial
Nuxt project info:

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `0.0.0`
- Package Manager:  `unknown`
- Bundler:          `Webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

run the command to create nuxt 3 project
```sh
% npx nuxi init nuxt3-app
```
> the archive/xxx.tar.gz file could be downloaded via my web browser

### Describe the bug

the following error is shown after run command

```sh
Nuxt CLI v3.0.0-27338323.1e98259                                                                                                            14:17:30

 ERROR  could not download https://github.com/nuxt/starter/archive/4c952d210cf85df8211ecb14994e46e5e1175d8a.tar.gz                          14:17:31

  at Degit._cloneWithTar (/usr/local/lib/node_modules/nuxi/node_modules/nuxi-edge/dist/chunks/init.mjs:9819:10)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async Degit.clone (/usr/local/lib/node_modules/nuxi/node_modules/nuxi-edge/dist/chunks/init.mjs:9614:4)
  at async Object.invoke (/usr/local/lib/node_modules/nuxi/node_modules/nuxi-edge/dist/chunks/init.mjs:10190:7)
  at async _main (/usr/local/lib/node_modules/nuxi/node_modules/nuxi-edge/dist/chunks/index.mjs:384:7)
```

**Comment by phgap** [comment]
when I run the the following command, it seems like I am being redirected.

```sh
% curl -I https://github.com/nuxt/starter/archive/4c952d210cf85df8211ecb14994e46e5e1175d8a.tar.gz
```
and it outputs:
```sh
HTTP/1.1 302 Found
Server: GitHub.com
Date: Fri, 24 Dec 2021 07:00:07 GMT
Content-Type: text/html; charset=utf-8
Vary: X-PJAX, X-PJAX-Container, Accept-Encoding, Accept, X-Requested-With
permissions-policy: interest-cohort=()
Location: https://codeload.github.com/nuxt/starter/tar.gz/4c952d210cf85df8211ecb14994e46e5e1175d8a
Cache-Control: max-age=0, private
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 0
Referrer-Policy: no-referrer-when-downgrade
Expect-CT: max-age=2592000, report-uri="https://api.github.com/_private/browser/errors"
Content-Security-Policy: default-src 'none'; base-uri 'self'; block-all-mixed-content; child-src github.com/assets-cdn/worker/ gist.github.com/assets-cdn/worker/; connect-src 'self' uploads.github.com objects-origin.githubusercontent.com www.githubstatus.com collector.githubapp.com api.github.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com cdn.optimizely.com logx.optimizely.com/v1/events translator.github.com wss://alive.github.com *.actions.githubusercontent.com wss://*.actions.githubusercontent.com online.visualstudio.com/api/v1/locations raw.githubusercontent.com github-production-repository-image-32fea6.s3.amazonaws.com github-production-release-asset-2e65be.s3.amazonaws.com insights.github.com; font-src github.githubassets.com; form-action 'self' github.com gist.github.com objects-origin.githubusercontent.com; frame-ancestors 'none'; frame-src render.githubusercontent.com viewscreen.githubusercontent.com notebooks.githubusercontent.com; img-src 'self' data: github.githubassets.com identicons.github.com collector.githubapp.com github-cloud.s3.amazonaws.com secured-user-images.githubusercontent.com/ *.githubusercontent.com; manifest-src 'self'; media-src github.com user-images.githubusercontent.com/; script-src github.githubassets.com; style-src 'unsafe-inline' github.githubassets.com; worker-src github.com/assets-cdn/worker/ gist.github.com/assets-cdn/worker/
Content-Length: 154
X-GitHub-Request-Id: 400A:1258:1DE50:41565:61C56FFE
```

**Comment by danielroe** [comment]
Could you provide a bit more info? And check your firewall settings, etc.? I can't reproduce this.

**Comment by pintoflager** [comment]
I'm running into this as well when trying to install nuxi into a container
```
RUN npm install --global nuxt/cli nuxi@latest
```

I have the same workflow for nuxt2 with the create-nuxt-app tool and that works fine
```
RUN npm install --global create-nuxt-app
CMD [ "sleep", "infinity" ]
```

**Comment by olegpopovskiy** [comment]
facing the same problem..
