### ISSUE TITLE
Production build + custom vue lib + ssr

### ISSUE THREAD

**Issue by Jamshoot66** [nuxt/framework#2530]
### Environment

```
npx nuxi info:
------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-27338323.1e98259`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
```

vue version `3.2.26` (same for nuxt project and vue lib) 

### Reproduction

https://github.com/Jamshoot66/nuxt3-ui-lib-example
There are two projects:
- `nuxt-project` - project to reproduce the bug
commands to start project:
   - `yarn`
   - `yarn build && yarn start`

- `ui-lib` - example of external lib. Also, it is published to npm as `ui-lib-for-nuxt-slot-issue`

### Describe the bug

I'm working on vue3 ui library and trying to add SSR support. So, the problem is SSR fails after production build (`yarn build && yarn start`).
There are 2 components in the example
1. Simple hello world component `HelloWorld`
2. Component with slot `HelloSlot`

Both of them leads to errors in production build:
`[Vue warn]: [@vue/server-renderer] Invalid VNode type: Symbol(Fragment) (symbol)` 
Yes, it's market as warn, but the component does not render on the server-side and it is an error to me.

Slotted component `HelloSlot` throws
`TypeError: Cannot read properties of null (reading 'isCE')`, 'couse `currentRenderingInstance` is null

nuxt config:
```
export default defineNuxtConfig({
  vite: {
    resolve: {
      alias: {
        "@vue": path.resolve(__dirname, './node_modules/@vue'),
        "vue": path.resolve(__dirname, './node_modules/vue'),
      },

      // error when use dedupe:
      // "require is not defined in ES module scope, you can use import instead"
      // fixing server.mjs does not help with ssr issue
      // dedupe: ['vue', '@vue'],
      preserveSymlinks: false,
    }
  }
})
```

### Additional context

Only production build

### Logs

```shell
[Vue warn]: [@vue/server-renderer] Invalid VNode type: Symbol(Fragment) (symbol)
TypeError: Cannot read properties of null (reading 'isCE')
    at renderSlot (/Users/jamshoot/Documents/projects/__tests/nuxt3/nuxt3-ui-lib-example/nuxt-project/.output/server/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5799:34)
    at Proxy.render (/Users/jamshoot/Documents/projects/__tests/nuxt3/nuxt3-ui-lib-example/nuxt-project/.output/server/node_modules/ui-lib-for-nuxt-slot-issue/dist/ui-lib-for-nuxt-slot-issue.common.js:245:301)
    at renderComponentRoot (file:///Users/jamshoot/Documents/projects/__tests/nuxt3/nuxt3-ui-lib-example/nuxt-project/.output/server/chunks/index.mjs:2019:44)
    at renderComponentSubTree (file:///Users/jamshoot/Documents/projects/__tests/nuxt3/nuxt3-ui-lib-example/nuxt-project/.output/server/chunks/index.mjs:9866:51)
    at renderComponentVNode (file:///Users/jamshoot/Documents/projects/__tests/nuxt3/nuxt3-ui-lib-example/nuxt-project/.output/server/chunks/index.mjs:9811:16)
    at Object.ssrRenderComponent (file:///Users/jamshoot/Documents/projects/__tests/nuxt3/nuxt3-ui-lib-example/nuxt-project/.output/server/chunks/index.mjs:10220:12)
    at _sfc_ssrRender (file:///Users/jamshoot/Documents/projects/__tests/nuxt3/nuxt3-ui-lib-example/nuxt-project/.output/server/chunks/app/server.mjs:3263:32)
    at renderComponentSubTree (file:///Users/jamshoot/Documents/projects/__tests/nuxt3/nuxt3-ui-lib-example/nuxt-project/.output/server/chunks/index.mjs:9860:13)
    at renderComponentVNode (file:///Users/jamshoot/Documents/projects/__tests/nuxt3/nuxt3-ui-lib-example/nuxt-project/.output/server/chunks/index.mjs:9811:16)
    at renderVNode (file:///Users/jamshoot/Documents/projects/__tests/nuxt3/nuxt3-ui-lib-example/nuxt-project/.output/server/chunks/index.mjs:9901:22)
```

**Comment by dergunovs** [comment]
Same error.

**Comment by phoenix-ru** [comment]
This is caused by a duplication of Vue in your dependencies. You need to dedupe it. Your options are:
1. Change all your imports to directly import from `'vue'`, not from `'@vue/...'`;
2. In case you want to use dedupe, I'd recommend you write a special polyfill for CommonJS libraries. I have implemented one in my example repo (this is Webpack): https://github.com/phoenix-ru/nuxt3-module-federation-example/blob/f9ffe07d6a504a1049bb0248c4b2fb1807a8cc44/packages/nuxt3-app/modules/build/plugins/NuxtModuleFederationPlugin.ts#L39

**Comment by dergunovs** [comment]
> 

1. All imports are from "vue".
2. Library is completly ESM, build with Rollup. With Vite or Vue CLI 5 or Nuxt3 with ClientOnly everything is ok. In SSR mode i got this error.

**Comment by djschilling** [comment]
@dergunovs did you find a solution to your problem?

we can also not find a place where we use a different import.

**Comment by dergunovs** [comment]
> 

No, I switched to next.js.

**Comment by th3l0g4n** [comment]
I have exactly the same issue.
The library my app is consuming is built using vite lib mode.

**Comment by alex00888** [comment]
Same problem :(
I'm using vue-splide and the error appears when running in production mode

**Comment by zefman** [comment]
I have this same issue. Adding the library to build.transpile doesn't seem to help. Has anyone else solved this?

**Comment by carbontwelve** [comment]
@zefman adding to `build.transpile` didn't work for me but adding to `vite.optimizeDeps.include` did, e.g:

```
vite: {
    logLevel: "info",
    optimizeDeps: {
        include: [
            '@moonminer/common',
            '@moonminer/orm',
            '@moonminer/universe',
            '@headlessui/vue',
            'vue'
        ]
    }
},
```

**Comment by Lilja** [comment]
I added a [replication stackblitz](https://stackblitz.com/edit/nuxt-starter-9yvfvf) for this problem.

- Open a new terminal
- run `nuxt generate`:
![image](https://user-images.githubusercontent.com/6134511/173937107-3a4cc2de-f626-4ee5-9b11-d0663910e3e5.png)

**Comment by danielroe** [comment]
This is no longer reproducible on latest Nuxt. We now enable vue as an external by default, and dedupe vue in the client build.

**Comment by rahulkumarsingh73690** [comment]
@danielroe Still not sure how to use any vue plugin in nuxt 😐
