### ISSUE TITLE
polyfill imports are stripped from final build output

### ISSUE THREAD

**Issue by newbeea** [nuxt/framework#2561]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v14.17.2`
- Nuxt Version:     `3.0.0-27338323.1e98259`
- Package Manager:  `pnpm@6.22.2`
- Bundler:          `Vite`
- User Config:      `build`, `buildModules`, `apollo`, `unocss`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `@vueuse/nuxt@7.3.0`, `@unocss/nuxt@0.16.4`, `@pinia/nuxt@0.1.6`, `graphql-codegen-module`, `./modules/apollo-module.ts`

### Reproduction

https://codesandbox.io/s/young-bird-cvsbm?file=/server/api/graphql.ts

### Describe the bug

type-graphql unable to be used in server/api/graphql.ts
because the polyfill (import 'reflect-metadata') removed in ./nuxt/nitro/index.mjs
then type-graphql throw error

 

### Logs

ERROR  [worker] Looks like you've forgot to provide experimental metadata API polyfill. Please read the installation instruction for more details.                                                   18:50:29

  at async Loader.import (internal/modules/esm/loader.js:177:24)                                   modules\type-graphql\dist\metadata\utils.js:42:15)
  at async Object.loadESM (internal/process/esm_loader.js:68:5)                                    aphql\dist\metadata\metadata-storage.js:27:17)
                                                                                                   ype-graphql\dist\metadata\getMetadataStorage.js:6:87)
                                                                                                   e-graphql\dist\schema\schema-generator.js:48:34)
 WARN  [worker] Looks like you've forgot to provide experimental metadata API polyfill. Please readodules\type-graphql\dist\schema\schema-generator.js:26:14) the installation instruction for more details.                                                    l\dist\utils\buildSchema.js:20:55)
18:50:29

  at Object.ensureReflectMetadataExists (node_modules\.pnpm\type-graphql@1.1.1_graphql@15.8.0\node_modules\type-graphql\dist\metadata\utils.js:42:15)
  at new MetadataStorage (node_modules\.pnpm\type-graphql@1.1.1_graphql@15.8.0\node_modules\type-graphql\dist\metadata\metadata-storage.js:27:17)
  at Object.getMetadataStorage (node_modules\.pnpm\type-graphql@1.1.1_graphql@15.8.0\node_modules\t the installation instruction for more details.                                                    18:50:29  ype-graphql\dist\metadata\getMetadataStorage.js:6:87)
  at Function.checkForErrors (node_modules\.pnpm\type-graphql@1.1.1_graphql@15.8.0\node_modules\typmodules\type-graphql\dist\metadata\utils.js:42:15)e-graphql\dist\schema\schema-generator.js:48:34)                                                   aphql\dist\metadata\metadata-storage.js:27:17)
  at Function.generateFromMetadataSync (node_modules\.pnpm\type-graphql@1.1.1_graphql@15.8.0\node_mype-graphql\dist\metadata\getMetadataStorage.js:6:87)odules\type-graphql\dist\schema\schema-generator.js:26:14)                                         e-graphql\dist\schema\schema-generator.js:48:34)
  at buildSchemaSync (node_modules\.pnpm\type-graphql@1.1.1_graphql@15.8.0\node_modules\type-graphqodules\type-graphql\dist\schema\schema-generator.js:26:14)l\dist\utils\buildSchema.js:20:55)                                                                 l\dist\utils\buildSchema.js:20:55)
  at /C:/Users/XPF/Desktop/workspace/nuxt/antfu-nuxt/.nuxt/nitro/index.mjs:151:16
  at ModuleJob.run (internal/modules/esm/module_job.js:169:25)
  at async Loader.import (internal/modules/esm/loader.js:177:24)
  at async Object.loadESM (internal/process/esm_loader.js:68:5)

**Comment by NexZhu** [comment]
Same issue, unable to use `type-graphql`

**Comment by newbeea** [comment]
> Same issue, unable to use `type-graphql`
`import * as Reflect from 'reflect-metadata'` will be removed in nitro/index.mjs

I resolved this by using "Reflect" in code, see here [nuxt3-apollo-starter](https://github.com/newbeea/nuxt3-apollo-starter/blob/master/server/api/graphql.ts)

**Comment by NexZhu** [comment]
For now, I'm using this woraround in ` package.json`
```json
    "overrides": {
      "@nuxt/kit": "npm:@nuxt/kit-edge@^3.0.0-rc.4-27588443.cf25525",
      "jiti": "npm:@daotl/jiti@^1.13.1"
    }
```

**Comment by danielroe** [comment]
You should be able to add this to your `nuxt.config` to add any modules with side-effects to an allow list:

```js
import { defineNuxtConfig } from "nuxt";

// https://v3.nuxtjs.org/docs/directory-structure/nuxt.config
export default defineNuxtConfig({
  nitro: {
    moduleSideEffects: ["reflect-metadata"]
  }
});
```
