### ISSUE TITLE
nuxi build does not include required files from firebase

### ISSUE THREAD

**Issue by AlexDicy** [nuxt/framework#2583]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-27338323.1e98259`
- Package Manager:  `npm@8.3.0`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/AlexDicy/nuxt-min-reproduction

Run `npm install`, `nuxi build`, `nuxi preview`. Open the preview.

### Describe the bug

The module `@firebase/firestore` is not imported correctly when the server is built.

The firestore module needs file in the `src` folder located in `node_modules\@firebase\firestore\dist\src`,
such as `.output\server\node_modules\@firebase\firestore\dist\src\protos\google\firestore\v1\firestore.proto`.

These files are not being transferred.
`~/.output/server/node_modules`
![image](https://user-images.githubusercontent.com/11839341/147881313-ceb76590-8b7d-4dbf-93fa-14737e4d7b21.png)
`~/node_modules`
![image](https://user-images.githubusercontent.com/11839341/147881303-7f5cde4d-b494-432b-8c01-555b07f3fd38.png)

Resulting in a server crash:
```
Listening on http://localhost:3000
[2022-01-02T15:46:00.532Z]  @firebase/firestore: Firestore (9.6.1): INTERNAL UNHANDLED ERROR:  Error: ENOENT: no such file or directory, open 'D:\Documents\IdeaProjects\nuxt-min-reproduction\.output\server\node_modules\@firebase\firestore\dist\src\protos\google\firestore\v1\firestore.proto'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at fetch (D:\Documents\IdeaProjects\nuxt-min-reproduction\.output\server\node_modules\protobufjs\src\root.js:172:34)
    at Root.load (D:\Documents\IdeaProjects\nuxt-min-reproduction\.output\server\node_modules\protobufjs\src\root.js:206:13)
    at Root.loadSync (D:\Documents\IdeaProjects\nuxt-min-reproduction\.output\server\node_modules\protobufjs\src\root.js:247:17)
    at Object.loadProtosWithOptionsSync (D:\Documents\IdeaProjects\nuxt-min-reproduction\.output\server\node_modules\@grpc\proto-loader\build\src\util.js:66:29)
    at loadSync (D:\Documents\IdeaProjects\nuxt-min-reproduction\.output\server\node_modules\@grpc\proto-loader\build\src\index.js:194:31)
    at loadProtos (file:///D:/Documents/IdeaProjects/nuxt-min-reproduction/.output/server/node_modules/@firebase/firestore/dist/index.node.mjs:14500:31)
    at newConnection (file:///D:/Documents/IdeaProjects/nuxt-min-reproduction/.output/server/node_modules/@firebase/firestore/dist/index.node.mjs:14522:20)
    at OnlineComponentProvider.createDatastore (file:///D:/Documents/IdeaProjects/nuxt-min-reproduction/.output/server/node_modules/@firebase/firestore/dist/index.node.mjs:18436:28)
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

Error: ENOENT: no such file or directory, open 'D:\Documents\IdeaProjects\nuxt-min-reproduction\.output\server\node_modules\@firebase\firestore\dist\src\protos\google\firestore\v1\firestore.proto'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at Root.load (D:\Documents\IdeaProjects\nuxt-min-reproduction\.output\server\node_modules\protobufjs\src\root.js:206:13)

    at newConnection (file:///D:/Documents/IdeaProjects/nuxt-min-reproduction/.output/server/node_modules/@firebase/firestore/dist/index.node.mjs:14522:20)
    at OnlineComponentProvider.createDatastore (file:///D:/Documents/IdeaProjects/nuxt-min-reproduction/.output/server/node_modules/@firebase/firestore/dist/index.node.mjs:18436:28) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'D:\\Documents\\IdeaProjects\\nuxt-min-reproduction\\.output\\server\\node_modules\\@firebase\\firestore\\dist\\src\\protos\\google\\firestore\\v1\\firestore.proto'
}
```

There is no issue when running the server using `npm run dev`.

I have tried configuring modules, buildModules, transpile settings, in nuxt.config.ts without any success.
Looks like it's a known issue within the Angular framework, and is solved by marking `@firebase/firestore` as an external dependency during the build process for the server

**Comment by pi0** [comment]
Hi. I've moved this to relavant repo https://github.com/unjs/nitro/issues/84
