### ISSUE TITLE
m.default is not a function (momentjs)

### ISSUE THREAD

**Issue by 5v3n-08** [nuxt/framework#2584]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27338323.1e98259`
- Package Manager:  `npm@8.1.0`
- Bundler:          `Vite`
- User Config:      `css`, `buildModules`, `build`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.1.8`, `@nuxtjs/moment@1.6.1`

### Reproduction

I created a new stackblitz project for reproduction: [https://stackblitz.com/edit/github-b92pu2?file=app.vue](https://stackblitz.com/edit/github-b92pu2?file=app.vue)

### Describe the bug

I have a problem with using the library [momentjs](https://momentjs.com/), but I think this can be a nuxt bug.
When I try to use a function of momentjs, I get the 500 error nuxt screen with following error message:

```
m.default is not a function
  at file://./.nuxt/dist/server/server.mjs:10:126  
  at processTicksAndRejections (node:internal/process/task_queues:96:5)  
  at async renderToString (file://./node_modules/vue-bundle-renderer/dist/index.mjs:248:19)  
  at async renderMiddleware (file://./.nuxt/nitro/index.mjs:191:20)  
```

### Logs

```
(node:8) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/home/projects/github-b92pu2/node_modules/moment/dist/moment.js:5662
export default hooks;
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (https://github-b92pu2.w.staticblitz.com/blitz.bc2b78560fa0e6097e7f69d4e820659cab64d2c5.js:6:166885)
    at Module._compile (https://github-b92pu2.w.staticblitz.com/blitz.bc2b78560fa0e6097e7f69d4e820659cab64d2c5.js:6:167517)
    at Object.Module._extensions..js (https://github-b92pu2.w.staticblitz.com/blitz.bc2b78560fa0e6097e7f69d4e820659cab64d2c5.js:6:168239)
    at Module.load (https://github-b92pu2.w.staticblitz.com/blitz.bc2b78560fa0e6097e7f69d4e820659cab64d2c5.js:6:166317)
    at Function.Module._load (https://github-b92pu2.w.staticblitz.com/blitz.bc2b78560fa0e6097e7f69d4e820659cab64d2c5.js:6:163857)
    at _0xb18891.executionFunctionOrLineOffset (https://github-b92pu2.w.staticblitz.com/blitz.bc2b78560fa0e6097e7f69d4e820659cab64d2c5.js:6:738392)
[vite dev] Error loading external "/home/projects/github-b92pu2/node_modules/moment/dist/moment.js".
  at eval (file://./.nuxt/dist/server/server.mjs:1997:282)  
  at async __instantiateModule__ (file://./.nuxt/dist/server/server.mjs:2107:3)
m.default is not a function
  at eval (file://./.nuxt/dist/server/server.mjs:19:126)  
  at async renderToString (file://./node_modules/vue-bundle-renderer/dist/index.mjs:258:19)  
  at async renderMiddleware (file://./.nuxt/nitro/index.mjs:198:20)  
  at async handle (file://./node_modules/h3/dist/index.mjs:635:19)
```

**Comment by itshizhan** [comment]
see: https://v3.nuxtjs.org/concepts/esm

**Comment by Techassi** [comment]
Similiar issue I have on a clean install via `npx nuxi init nuxt3-app`

```
m.default is not a function
  at file://../.nuxt/dist/server/server.mjs:10:126
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async renderToString (file://../node_modules/vue-bundle-renderer/dist/index.mjs:248:19)
  at async renderMiddleware (file://../.nuxt/nitro/index.mjs:191:20)
  at async handle (file://../node_modules/h3/dist/index.mjs:601:19)
```

**Comment by rburns629** [comment]
> Similiar issue I have on a clean install via `npx nuxi init nuxt3-app`
> 
> ```
> m.default is not a function
>   at file://../.nuxt/dist/server/server.mjs:10:126
>   at processTicksAndRejections (node:internal/process/task_queues:96:5)
>   at async renderToString (file://../node_modules/vue-bundle-renderer/dist/index.mjs:248:19)
>   at async renderMiddleware (file://../.nuxt/nitro/index.mjs:191:20)
>   at async handle (file://../node_modules/h3/dist/index.mjs:601:19)
> ```

I was having the same issue. Thought it was my build and attempted to do a clean install. Same issue kept happening. Seems to be specifically with build: `v3.0.0-27338323.1e98259`. Even the starter CodeSandBox online environment is affected. I used the package-lock.json file from the StackBlitz playground to downgrade to verson: `v3.0.0-27265876.3cd4494`, which seemed to do the trick

**Comment by leechuanfeng** [comment]
Yup me too. I commented in a similar issue here: https://github.com/nuxt/framework/issues/2601

**Comment by danielroe** [comment]
As @itshizhan points out, this is an upstream issue with momentjs. You could add it to `build.transpile` to work around the issue. Or find a replacement, as moment is now legacy and not recommended for new projects in any case.

**Comment by Techassi** [comment]
I don't even use `momentjs`. This is a clean install **without** any dependencies I added via `npm i / yarn add`. 

More context:

```
WARN [SSR] Error transforming ../node_modules/nuxt3/dist/app/bootstrap.mjs: Cannot read properties of undefined (reading 'uid')

  at Object.statSync (node_modules\graceful-fs\polyfills.js:313:17)
  at isFile (node_modules\resolve\lib\sync.js:12:23)
  at loadpkg (node_modules\resolve\lib\sync.js:138:14)
  at loadAsFileSync (node_modules\resolve\lib\sync.js:107:19)
  at Function.resolveSync [as sync] (node_modules\resolve\lib\sync.js:93:17)
  at resolveFrom$3 (node_modules\vite\dist\node\chunks\dep-76613303.js:3911:29)
  at resolvePackageData (node_modules\vite\dist\node\chunks\dep-76613303.js:30046:19)
  at node_modules\vite\dist\node\chunks\dep-76613303.js:30426:15
  at Array.find (<anonymous>)
  at tryNodeResolve (node_modules\vite\dist\node\chunks\dep-76613303.js:30425:44)

√ Vite server built in 50ms                                                                                                                                              
√ Nitro built in 298 ms

m.default is not a function
  at file://../.nuxt/dist/server/server.mjs:10:126
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async renderToString (file://../node_modules/vue-bundle-renderer/dist/index.mjs:248:19)
  at async renderMiddleware (file://../.nuxt/nitro/index.mjs:191:20)
  at async handle (file://../node_modules/h3/dist/index.mjs:601:19)
```
