### ISSUE TITLE
500 m.default is not a function

### ISSUE THREAD

**Issue by hemant-kumar-esc** [nuxt/framework#2601]
### Environment

Nuxt CLI v3.0.0-27338323.1e98259

Nuxt project info:                                                                                           
------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v14.17.3`
- Nuxt Version:     `3.0.0-27338323.1e98259`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

getting error on newly created nuxt3 app

yarn dev -o

have tried with npm in different directory but same error

### Describe the bug

500
m.default is not a function
at file:///C:/wamp64/www/nuxt3-app/.nuxt/dist/server/server.mjs:10:126
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async renderToString (file:///C:/wamp64/www/nuxt3-app/node_modules/vue-bundle-renderer/dist/index.mjs:248:19)
at async renderMiddleware (file:///C:/wamp64/www/nuxt3-app/.nuxt/nitro/index.mjs:191:20)
at async handle (file:///C:/wamp64/www/nuxt3-app/node_modules/h3/dist/index.mjs:601:19)

### Logs

```shell
[SSR] Error transforming C:/wamp64/www/nuxt3-app/node_modules/nuxt3/dist/app/bootstrap.mjs: Cannot read property 'uid' of undefined

  at Object.statSync (node_modules\graceful-fs\polyfills.js:313:17)
  at isFile (node_modules\resolve\lib\sync.js:12:23)
  at loadpkg (node_modules\resolve\lib\sync.js:138:14)
  at loadAsFileSync (node_modules\resolve\lib\sync.js:107:19)
  at Function.resolveSync [as sync] (node_modules\resolve\lib\sync.js:93:17)
  at resolveFrom$3 (node_modules\vite\dist\node\chunks\dep-76613303.js:3911:29)
  at resolvePackageData (node_modules\vite\dist\node\chunks\dep-76613303.js:30046:19)
  at node_modules\vite\dist\node\chunks\dep-76613303.js:30426:15
  at Array.find (<anonymous>)
  at tryNodeResolve (node_modules\vite\dist\node\chunks\dep-76613303.js:30425:44)

√ Vite server built in 129ms                                                                                  10:17:51
√ Nitro built in 338 ms                                                                                       10:17:51
m.default is not a function
  at file:///C:/wamp64/www/nuxt3-app/.nuxt/dist/server/server.mjs:10:126
  at async renderToString (file:///C:/wamp64/www/nuxt3-app/node_modules/vue-bundle-renderer/dist/index.mjs:248:19)
  at async renderMiddleware (file:///C:/wamp64/www/nuxt3-app/.nuxt/nitro/index.mjs:191:20)
  at async handle (file:///C:/wamp64/www/nuxt3-app/node_modules/h3/dist/index.mjs:601:19)
```

**Comment by leechuanfeng** [comment]
Me too, I have the same error in my existing project that was working before. It occurs after doing a yarn upgrade.

You can reproduce it by getting an existing project: (e.g.https://github.com/leechuanfeng/nuxt3-minimal)

After `yarn install`, it will still be able to work.
But after `yarn upgrade`, it will show this error.

**Comment by Lycoon** [comment]
Same error using Node `16.13.1`

**Comment by danielroe** [comment]
closing to track in #2599
