### ISSUE TITLE
[SSR] Apollo is not working in production

### ISSUE THREAD

**Issue by Luferov** [nuxt/framework#2603]
### Environment

- Operating System: `ubuntu 21.10`
- Nuxt CLI v3.0.0-27338323.1e98259
- Node `16.12.0`
- Package Manager: `yarn@1.22.17`
- Bundler: webpack
- Runtime Modules: `@nuxtjs/apollo`

### Reproduction

Link to sendbox: https://codesandbox.io/s/crazy-brown-2llyj

To reproduce it:
- `yarn run build`
- `export NUXT_PORT=4000 && yarn run start`
- Open in browser.

nuxt.config.ts
```js
import { defineNuxtConfig } from "@nuxt/bridge";

export default defineNuxtConfig({
  alias: {
    tslib: "tslib/tslib.es6.js"
  },
  ssr: true,
  target: "server",
  publicRuntimeConfig: {
    API_URL: "https://rickandmortyapi.com/graphql",
    API_URL_BROWSER: "https://rickandmortyapi.com/graphql"
  },
  head: {
    title: "Nuxt.js starter for CSB",
    meta: [
      { charset: "utf-8" },
      { name: "viewport", content: "width=device-width, initial-scale=1" },
      {
        hid: "description",
        name: "description",
        content: "Official Nuxt.js starter for CodeSandBox"
      }
    ],
    link: [{ rel: "icon", type: "image/x-icon", href: "/favicon.ico" }]
  },
  components: false,
  modules: ["@nuxtjs/apollo"],
  css: [],
  plugins: [],

  apollo: {
    includeNodeModules: true,
    clientConfigs: {
      default: "~/plugins/apollo.ts"
    }
  },
  build: {
    transpile: [
      "@apollo/client",
      "@apollo/client/core",
      "graphql",
      "ts-invariant",
      "tslib",
      "subscriptions-transport-ws",
      "cross-fetch/polyfill",
      "universal-cookie",
      "node-fetch"
    ]
  }
});

```

### Describe the bug

In develop mode it works as it should. But if I run the project in ssr mode, then computed is not calculated based on the result of the apollo query.

### Logs

```shell
$ nuxi preview
Nuxt CLI v3.0.0-27338323.1e98259                                                         14:26:22
ℹ Node.js version: 16.12.0                                                               14:26:22
ℹ Preset: server                                                                         14:26:22
ℹ Working dir: .output                                                                   14:26:22
ℹ Starting preview command: node ./server/index.mjs                                      14:26:22
                                                                                         14:26:22
Listening on http://localhost:4000
Cannot read properties of undefined (reading 'results')
  at VueComponent.episodesResult (file://./server/chunks/app/pages/index.mjs:89:32)
  at Watcher2.get (file://./server/chunks/app/server.mjs:5132:29)
  at Watcher2.evaluate (file://./server/chunks/app/server.mjs:5200:25)
  at VueComponent.computedGetter [as episodesResult] (file://./server/chunks/app/server.mjs:5341:21)
  at VueComponent.render (file://./server/chunks/app/pages/index.mjs:69:175)
  at file://./server/chunks/app/server.mjs:2267:29
  at activateCurrentInstance (file://./server/chunks/app/server.mjs:2227:16)
  at VueComponent.$options.render (file://./server/chunks/app/server.mjs:2266:20)
  at VueComponent.Vue3._render (file://./server/chunks/app/server.mjs:4577:26)
  at file://./server/chunks/app/vue2.mjs:20:69207
```

**Comment by Luferov** [comment]
If build via `nuxt build` and run in production mode use `node .output/server/index.mjs` got same problem.

**Comment by Luferov** [comment]
I was able to start production using:
- `bridge.nitro = false` in nuxt.config.ts
- `yarn run nuxt build` 
- `yarn run nuxt start`
But, i want use nitro. 

Maybe this will help. While I figured out that Vue builds dependencies in computed. And when calculating, it calls them. However, no dependencies occur when building dependencies. Ie, nitro collects somehow wrong.

**Comment by newbeea** [comment]
My template [nuxt3-apollo-starter](https://github.com/newbeea/nuxt3-apollo-starter) may help you

**Comment by Luferov** [comment]
Now, its work correctly in production mode!
