### ISSUE TITLE
playground fails with `vite: false`

### ISSUE THREAD

**Issue by danielroe** [nuxt/framework#2614]
Error:

```
 ERROR  in ./node_modules/@nuxt/ui/dist/components/NuxtExampleLayout.vue?vue&type=template&id=1165068e&ts=true                 friendly-errors 10:31:21

Module parse failed: Unexpected token (8:30)
File was processed with these loaders:
 * ./node_modules/unplugin/dist/webpack/loaders/transform.js
 * ./node_modules/unplugin/dist/webpack/loaders/transform.js
 * ./node_modules/vue-loader/dist/templateLoader.js
 * ./node_modules/vue-loader/dist/index.js
 * ./node_modules/unplugin/dist/webpack/loaders/transform.js
You may need an additional loader to handle the result of these loaders.
| 
| 
> export function ssrRender(_ctx: any,_push: any,_parent: any,_attrs: any,$props: any,$setup: any,$data: any,$options: any) {
|   const _component_NLink = __nuxt_component_0!
|   const _component_NCard = __nuxt_component_1!

Cannot find package 'uno.css' imported from /Users/daniel/code/nuxt/framework/playground/.nuxt/dist/server/server.mjs
  at packageResolve (internal/modules/esm/resolve.js:650:9)  
  at moduleResolve (internal/modules/esm/resolve.js:691:18)  
  at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:805:11)  
  at Loader.resolve (internal/modules/esm/loader.js:88:40)  
  at Loader.getModuleJob (internal/modules/esm/loader.js:241:28)  
  at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:72:40)  
  at link (internal/modules/esm/module_job.js:71:36)
```

cc: @antfu

**Comment by pi0** [comment]
Is this issue probably related to unocss?

**Comment by danielroe** [comment]
It seems so. It's not replicable when copying the playground out of the monorepo.

**Comment by antfu** [comment]
I will need to investigate further since somehow the virtual module does not get resolved in Webpack 5's server build

**Comment by danielroe** [comment]
This reproduces within this monorepo:

Set `vite: false` within `playground/nuxt.config.ts` and run `yarn play`.

**Comment by phoenix-ru** [comment]
Hi, I've noticed the same bug which happens with `normalize.css`. Somehow the `.css` in the end tries to resolve locally instead of linking an external package. I could only fix it by using npm alias and referring to `normalize-css` instead:
`"normalize-css": "npm:normalize.css@^8.0.1"`

**Comment by danielroe** [comment]
I believe we can close this in favour of https://github.com/nuxt/framework/issues/2447
