### ISSUE TITLE
TypeError: __vite_ssr_import_0__.getter is not a function

### ISSUE THREAD

**Issue by olivervorasai** [nuxt/framework#2627]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-27356801.e9128f3`
- Package Manager:  `npm@8.1.2`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://codesandbox.io/s/strange-dream-z9zzc?file=/app.vue

### Describe the bug

When using a Yup schema that contains a conditional (require this field if another field is true) an SSR error occurs.

This error does not seem to occur if the schema declaration happens after the component is mounted.

### Logs

```shell
[Vue warn]: Unhandled error during execution of setup function
  at <App>
(node:117) UnhandledPromiseRejectionWarning: TypeError: __vite_ssr_import_0__.getter is not a function
    at new Reference (file:///sandbox/.nuxt/dist/server/server.mjs:3269:54)
    at file:///sandbox/.nuxt/dist/server/server.mjs:2504:64
    at Array.map (<anonymous>)
    at StringSchema.when (file:///sandbox/.nuxt/dist/server/server.mjs:2504:53)
    at setup (file:///sandbox/.nuxt/dist/server/server.mjs:1889:48)
    at _sfc_main.setup (file:///sandbox/.nuxt/dist/server/server.mjs:1910:23)
    at callWithErrorHandling (/sandbox/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6650:22)
    at setupStatefulComponent (/sandbox/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6276:29)
    at setupComponent (/sandbox/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6232:11)
    at renderComponentVNode (/sandbox/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:198:17)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:117) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:117) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by danielroe** [comment]
The issue here is that yup doesn't provide a valid ESM export for `module`. See https://v3.nuxtjs.org/concepts/esm. A workaround is:

```js
import { defineNuxtConfig } from 'nuxt3'

// https://v3.nuxtjs.org/docs/directory-structure/nuxt.config
export default defineNuxtConfig({
  alias: {
    yup: 'yup/lib/index.js'
  }
})

```

**Comment by olivervorasai** [comment]
@danielroe Thank you for the quick response! The work that the Nuxt team has done is truly amazing.
