### ISSUE TITLE
[SSR] Error transforming C:/XXXXXXXXXXXXXX/node_modules/nuxt3/dist/app/bootstrap.mjs: Faile d to resolve import "#build/plugins" from "node_modules\nuxt3\dist\app\bootstrap.mjs". Does the file exist?

### ISSUE THREAD

**Issue by AndreyKindin** [nuxt/framework#2711]
### Environment

Nuxt CLI v3.0.0-27367970.e0fec80                                                                            16:20:55
Nuxt project info:                                                                                          16:20:58

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27367970.e0fec80`
- Package Manager:  `npm@8.1.1`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Clean installation of the nuxt 3

### Describe the bug

[SSR] Error transforming C:/xxx/node_modules/nuxt3/dist/app/bootstrap.mjs: Faile
d to resolve import "#build/plugins" from "node_modules\nuxt3\dist\app\bootstrap.mjs". Does the file exist?

### Logs

```shell
[SSR] Error transforming C:/Users/akind/Documents/develop/wmm2/node_modules/nuxt3/dist/app/bootstrap.mjs: Faile
d to resolve import "#build/plugins" from "node_modules\nuxt3\dist\app\bootstrap.mjs". Does the file exist?

  at formatError (node_modules\vite\dist\node\chunks\dep-48c3e8a4.js:36769:46)
  at TransformContext.error (node_modules\vite\dist\node\chunks\dep-48c3e8a4.js:36765:19)
  at normalizeUrl (node_modules\vite\dist\node\chunks\dep-48c3e8a4.js:73694:26)
  at async TransformContext.transform (node_modules\vite\dist\node\chunks\dep-48c3e8a4.js:73834:57)
  at async Object.transform (node_modules\vite\dist\node\chunks\dep-48c3e8a4.js:36985:30)
  at async doTransform (node_modules\vite\dist\node\chunks\dep-48c3e8a4.js:52057:29)

  m.default is not a function
  at file:///XXXXXXXXX/.nuxt/dist/server/server.mjs:10:126
  at async renderToString (file:///XXXXXXXXX/node_modules/vue-bundle-renderer/dist/index.m
js:247:19)
  at async renderMiddleware (file:///XXXXXXXXX/.nuxt/nitro/index.mjs:191:20)
  at async handle (file:///XXXXXXXXX/node_modules/h3/dist/index.mjs:601:19)
m.default is not a function
  at file:///XXXXXXXXX/.nuxt/dist/server/server.mjs:10:126
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async renderToString (file:///XXXXXXXXX/node_modules/vue-bundle-renderer/dist/index.m
js:247:19)
  at async renderMiddleware (file:///XXXXXXXXX/.nuxt/nitro/index.mjs:191:20)
  at async handle (file:///XXXXXXXXX/node_modules/h3/dist/index.mjs:601:19)
```

**Comment by jshimkoski** [comment]
Seeing this issue as well.

**Comment by pi0** [comment]
Seems related to recent vite 2.7.11 regression (https://github.com/nuxt/framework/issues/2706) releasing a hotfix shortly.

**Comment by AndreyKindin** [comment]
quick and dirty solution
`npm i -D vite@2.7.10`

**Comment by ludo237** [comment]
> quick and dirty solution `npm i -D vite@2.7.10`

Doesn't seem to work `yarn add vite@2.7.10`

**Comment by pi0** [comment]
Should be fixed in the latest npm publish. Please use `npx nuxi upgrade --force`.

**Comment by jshimkoski** [comment]
Works like a charm. Thanks @pi0!
