### ISSUE TITLE
Error 500: m.default is not a function

### ISSUE THREAD

**Issue by Dono7** [nuxt/framework#2712]
### Environment

`npx nuxi info` result : 
- Operating System: `Windows_NT`
- Node Version:     `v16.13.2`
- Nuxt Version:     `0.0.0`
- Package Manager:  `unknown`
- Bundler:          `Webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

More details from package.json : 
```js
"devDependencies": {
  "nuxt3": "latest"
}
```
More details from yarn.lock : 
```
"nuxi@npm:nuxi-edge@3.0.0-27367970.e0fec80":
  version "3.0.0-27367970.e0fec80"

nuxt3@latest:
  version "3.0.0-27367970.e0fec80"
```

### Reproduction

Bug Reproductible by going at the [Nuxt 3 - Installation](https://v3.nuxtjs.org/getting-started/installation) page and opening a demo on [CodeSandBox](https://codesandbox.io/s/github/nuxt/starter/tree/v3-codesandbox?file=/package.json). Or by simply starting a new project, with the starting commands : 
```
npx nuxi init nuxt3-app
code nuxt3-app
yarn install
yarn dev -o
```
 
It seems like the bug does not happen on the [StackBlitz](https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz) for some reasons.

### Describe the bug

I just started a fresh new Nuxt3 project from scratch. It shows a warning about a file "bootstrap.mjs" when trying to launch the development mode. When trying to access the application (by going to http://localhost:3000/ for example), then it displays more errors in console. The homepage cannot be accessed and displays a 500 - internal server error message.

Screenshot from the CodeSandBox demo : 

![image](https://user-images.githubusercontent.com/35794293/149355986-46ba6456-8bb4-483a-8d33-23ceaf42017d.png)

### Logs

```shell
(All the file links are obfuscated with a double '@@' symbol to hide my personal computer path)

---------------

Console logs when starting the development mode with `yarn dev` : 

Nuxt CLI v3.0.0-27367970.e0fec80

  > Local:    http://localhost:3000/
  > Network:  http://192.168.1.79:3000/

i Vite warmed up in 49ms

 WARN  [SSR] Error transforming C:/Users/donov/Documents/GitHub/nuxt-with-strapi/nuxt-frontend/node_modules/nuxt3/dist/app/bootstrap.mjs: Failed to resolve import "#build/plugins" from "node_modules\nuxt3\dist\app\bootstrap.mjs". Does the file exist?

  at formatError (node_modules\vite\dist\node\chunks\dep-48c3e8a4.js:36769:46)
  at TransformContext.error (node_modules\vite\dist\node\chunks\dep-48c3e8a4.js:36765:19)
  at normalizeUrl (node_modules\vite\dist\node\chunks\dep-48c3e8a4.js:73694:26)
  at async TransformContext.transform (node_modules\vite\dist\node\chunks\dep-48c3e8a4.js:73834:57)
  at async Object.transform (node_modules\vite\dist\node\chunks\dep-48c3e8a4.js:36985:30)
  at async doTransform (node_modules\vite\dist\node\chunks\dep-48c3e8a4.js:52057:29)

√ Vite server built in 59ms
√ Nitro built in 175 ms

---------------

Logs once trying to access the homepage : 

m.default is not a function
  at file:@@/nuxt-frontend/.nuxt/dist/server/server.mjs:10:126
  at async renderToString (file:@@/node_modules/vue-bundle-renderer/dist/index.mjs:247:19)  
  at async renderMiddleware (file:@@/.nuxt/nitro/index.mjs:191:20)
  at async handle (file:@@/node_modules/h3/dist/index.mjs:601:19)
m.default is not a function
  at file:@@/.nuxt/dist/server/server.mjs:10:126
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async renderToString (file:@@/node_modules/vue-bundle-renderer/dist/index.mjs:247:19)  
  at async renderMiddleware (file:@@/.nuxt/nitro/index.mjs:191:20)
  at async handle (file:@@/node_modules/h3/dist/index.mjs:601:19)

----------------

What is displayed on the homepage in the browser : 

500
m.default is not a function
at file:@@/.nuxt/dist/server/server.mjs:10:126
at async renderToString (file:@@/node_modules/vue-bundle-renderer/dist/index.mjs:247:19)
at async renderMiddleware (file:@@/.nuxt/nitro/index.mjs:191:20)
at async handle (file:@@/node_modules/h3/dist/index.mjs:601:19)
```

**Comment by Dono7** [comment]
Someone wrote another issue of the same bug at the same time. Wich makes this issue a duplicate of #2711

**Comment by Dono7** [comment]
Bug fixed in a new release. Can be updated with `npx nuxi upgrade --force` 👍
