### ISSUE TITLE
useRoute throws 

### ISSUE THREAD

**Issue by not-Ryan** [nuxt/framework#2757]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0-27368185.a4f300b`
- Package Manager:  `yarn@1.22.5`
- Bundler:          `Vite`
- User Config:      `css`, `meta`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

- Create a fresh project with pages, layout.
- Create page with `/test/[assignmentId].vue`
- Use the following code:

```vue
<script>
const route = useRoute();

const assugbmentId = route?.params?.assignmentId;
console.log(route, assignmentId);
</script>

<template>
  <div>
    {{ route }}
  </div>
</template>
```

- Call the page.

### Describe the bug

Whenever I use `useRoute()` with server side rendering on, I receive the error:
```
ERROR  [worker] nuxt instance unavailable 

  at Module.useNuxtApp (.nuxt/dist/server/server.mjs:279:13)
  at Module.useRoute (.nuxt/dist/server/server.mjs:2635:32)
  at $id_722676ce (.nuxt/dist/server/server.mjs:2577:37)
  at async __instantiateModule__ (.nuxt/dist/server/server.mjs:3739:3)


 ERROR  [proxy] connect ENOENT /tmp/nitro/worker-127151-1.sock 
  at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1161:16)
```

### Additional context

My server structure:
```
project/
├─ package.json
├─ layouts/
│  ├─ default.vue
│  └─ default.vue
├─ pages/
│  ├─ index.vue
│  └─ editor/
│     ├─ index.vue
│     └─ [assignmentId].vue
└─ nuxt.config.ts
```

### Logs

```shell
Nuxt CLI v3.0.0-27368185.a4f300b                                                 13:56:16
                                                                                 13:56:16
  > Local:    http://localhost:3000/ 

ℹ Vite warmed up in 157ms                                                        13:56:17
✔ Vite server built in 1216ms                                                    13:56:18
✔ Nitro built in 110 ms                                                          13:56:19
[Vue Router warn]: uncaught error during route navigation:

 ERROR  [worker] nuxt instance unavailable                                       13:56:19

  at Module.useNuxtApp (.nuxt/dist/server/server.mjs:279:13)
  at Module.useRoute (.nuxt/dist/server/server.mjs:2635:32)
  at $id_722676ce (.nuxt/dist/server/server.mjs:2577:37)
  at async __instantiateModule__ (.nuxt/dist/server/server.mjs:3739:3)


 ERROR  [proxy] connect ENOENT /tmp/nitro/worker-127151-1.sock                   13:56:19

  at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1161:16)
```

**Comment by danielroe** [comment]
`useRoute` needs to be called within setup. I suspect you mean to have `<script setup>` instead of `<script>`

**Comment by not-Ryan** [comment]
I'm such an idiot. Thank you :face_exhaling:
