### ISSUE TITLE
`require(` in comments breaks auto-imports

### ISSUE THREAD

**Issue by terion-name** [nuxt/framework#2762]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.12.0`
- Nuxt Version:     `3.0.0-27356801.e9128f3`
- Package Manager:  `yarn@1.22.4`
- Bundler:          `Vite`
- User Config:      `buildModules`, `build`, `intlify`, `publicRuntimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `@intlify/nuxt3@0.1.10`
------------------------------

### Reproduction

app.vue:

```
<script>
export default defineComponent({
  head() {
      return {
          // htmlAttrs: {
          //     lang: this.$i18n.locale
          // },
          // title: this.$tr('meta.title'),
          // meta: [
          //     { hid: 'robots', name: 'robots', content: 'index, follow' },
          //     { hid: 'mobile-web-app-capable', name: 'mobile-web-app-capable', content: 'no' },
          //     { hid: 'apple-mobile-web-app-title', name: 'apple-mobile-web-app-title', content: this.$tr('meta.title_short') },
          //     { hid: 'og:site_name', name: 'og:site_name', content: this.$tr('meta.title_short') },
          //     { hid: 'description', name: 'description', content: this.$tr('meta.desc') },
          //     { hid: 'og:title', name: 'og:title', content: this.$tr('meta.title_short') },
          //     { hid: 'og:description', name: 'og:description', content: this.$tr('meta.desc') },
          //     // { hid: 'og:image', name: 'og:image', content: '~/assets/img/sharing.png' },
          // ],
          // link: [
          //     ...this.$i18n.locales
          //     .map(locale => ({ rel: 'alternate', href: $config.BASE_URL + this.$localePath(this.$route.path, locale.code), hreflang: locale.code })),
          //     ...this.$i18n.locales
          //     .map(locale => ({ rel: 'alternate', href: $config.BASE_URL + this.$localePath(this.$route.path, locale.code), hreflang: locale.iso })),
          //     { rel: 'alternate', href: $config.BASE_URL + this.$localePath(this.$route.path, 'uk'), hreflang: 'x-default' },
          //     { rel: 'canonical', href: $config.BASE_URL + this.$localePath(this.$route.path, this.$i18n.locale) },
          //     // { rel: 'icon', type: 'image/png', href: `${require('~/assets/img/fav-32.png')}`, sizes: '32x32' },
          //     // { rel: 'icon', type: 'image/png', href: `${require('~/assets/img/fav-64.png')}`, sizes: '64x64' },
          //     // { rel: 'icon', type: 'image/png', href: `${require('~/assets/img/fav-256.png')}`, sizes: '256x256' },
          // ]
      }
  },

})
</script>
```

### Describe the bug

Use sample above. Like this, with commented out block. Run yarn dev and navigate to page. Fails:
```
500
require is not defined
at $id_2b46e842 (file://./.nuxt/dist/server/server.mjs:24025:50)
at __instantiateModule__ (file://./.nuxt/dist/server/server.mjs:25952:9)
at __ssrLoadModule__ (file://./.nuxt/dist/server/server.mjs:25899:25)
at ssrImport (file://./.nuxt/dist/server/server.mjs:25924:13)
at $id_d7918914 (file://./.nuxt/dist/server/server.mjs:24005:37)
at __instantiateModule__ (file://./.nuxt/dist/server/server.mjs:25952:9)
at __ssrLoadModule__ (file://./.nuxt/dist/server/server.mjs:25899:25)
at ssrImport (file://./.nuxt/dist/server/server.mjs:25924:13)
at $id_fef466a9 (file://./.nuxt/dist/server/server.mjs:42:37)
at async __instantiateModule__ (file://./.nuxt/dist/server/server.mjs:25952:3)
```

If remove comments entirely — error disappears

**Comment by danielroe** [comment]
The issue here is that by using `require(` in the comments the auto-imports plugin is fooled into thinking we're in a CJS context.
