### ISSUE TITLE
The requested module 'process' does not provide an export named 'on'

### ISSUE THREAD

**Issue by skf-funzt** [nuxt/framework#2784]
### Environment

```zsh
Nuxt CLI v3.0.0-27375427.d07d572                          
RootDir: /home/stephan/projects/web030/it-visualisierung  
Nuxt project info:                                        

------------------------------
- Operating System: `Linux`
- Node Version:     `v14.17.0`
- Nuxt Version:     `2.15.8`
- Package Manager:  `yarn@3.1.1`
- Bundler:          `Webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
```

### Reproduction

https://codesandbox.io/s/dry-architecture-tdsx9?file=/server/api/test.ts

### Describe the bug

If one of the dependencies uses the package `process` the es build with vite or webpack fails with the following error that the `process` package does not export `on`.

### Logs

```shell
ERROR  [worker] The requested module 'process' does not provide an export named 'on'

  import { on } from 'process';
  ^^
  SyntaxError: The requested module 'process' does not provide an export named 'on'
  at ModuleJob._instantiate (internal/modules/esm/module_job.js:124:21)
  at async ModuleJob.run (internal/modules/esm/module_job.js:179:5)
  at async Loader.import (internal/modules/esm/loader.js:178:24)
  at async Object.loadESM (internal/process/esm_loader.js:68:5)


 WARN  [worker] The requested module 'process' does not provide an export named 'on'

  import { on } from 'process';
  ^^
  SyntaxError: The requested module 'process' does not provide an export named 'on'
  at ModuleJob._instantiate (internal/modules/esm/module_job.js:124:21)
  at async ModuleJob.run (internal/modules/esm/module_job.js:179:5)
  at async Loader.import (internal/modules/esm/loader.js:178:24)
  at async Object.loadESM (internal/process/esm_loader.js:68:5)
```

**Comment by danielroe** [comment]
Just change this to `import process from 'process'`.

[Example](https://codesandbox.io/s/gallant-heyrovsky-bdor2?file=/server/api/test.ts).

**Comment by skf-funzt** [comment]
Thank you for the reply and for the example. Indeed that's the solution.

For me the `process` package is imported by another package I use, so I worked around by creating a separate package within my monorep so that I have an empty module and a usable CommonJS package for the server's API.

/close
