### ISSUE TITLE
Page layout not working as intended

### ISSUE THREAD

**Issue by dajooo** [nuxt/framework#2914]
### Environment

Nuxt CLI v3.0.0-27385496.7a1cf62
RootDir: /home/projects/github-sbeq6a
Nuxt project info:

------------------------------
- Operating System: `Linux`
- Node Version:     `v14.16.0`
- Nuxt Version:     `3.0.0-27385496.7a1cf62`
- Package Manager:  `npm@7.17.0`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-sbeq6a

### Describe the bug

When using the definePageMeta composable to define the pages layout, it continues using the default layout, if you set the layout to false and try to use the NuxtLayout component, like described in the [docs](https://v3.nuxtjs.org/docs/directory-structure/layouts#example-using-with-slots), it is working. The problem here is, if you now try to switch to a different page, you only get a white screen and the given error log in the browsers console.

### Logs

```shell
client.ts:22 [vite] connecting...
client.ts:52 [vite] connected.
runtime-core.esm-bundler.js:1326 <Suspense> is an experimental feature and its API will likely change.
runtime-core.esm-bundler.js:38 [Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://new-issue.vuejs.org/?repo=vuejs/core 
  at <BaseTransition mode="out-in" appear=false persisted=false  ... > 
  at <Transition name="layout" mode="out-in" > 
  at <RouterView > 
  at <NuxtPage> 
  at <App> 
  at <NuxtRoot>
warn2 @ runtime-core.esm-bundler.js:38
logError @ runtime-core.esm-bundler.js:212
handleError @ runtime-core.esm-bundler.js:204
callWithErrorHandling @ runtime-core.esm-bundler.js:158
flushJobs @ runtime-core.esm-bundler.js:394
Promise.then (async)
queueFlush @ runtime-core.esm-bundler.js:285
queueJob @ runtime-core.esm-bundler.js:279
(anonymous) @ runtime-core.esm-bundler.js:5139
triggerEffects @ reactivity.esm-bundler.js:358
triggerRefValue @ reactivity.esm-bundler.js:959
(anonymous) @ reactivity.esm-bundler.js:1090
triggerEffects @ reactivity.esm-bundler.js:358
triggerRefValue @ reactivity.esm-bundler.js:959
set value @ reactivity.esm-bundler.js:1003
finalizeNavigation @ vue-router.esm-bundler.js?v=ca1ca381:3187
(anonymous) @ vue-router.esm-bundler.js?v=ca1ca381:3060
Promise.then (async)
pushWithRedirect @ vue-router.esm-bundler.js?v=ca1ca381:3031
push @ vue-router.esm-bundler.js?v=ca1ca381:2962
navigate @ vue-router.esm-bundler.js?v=ca1ca381:2089
callWithErrorHandling @ runtime-core.esm-bundler.js:155
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:164
invoker @ runtime-dom.esm-bundler.js:366
runtime-dom.esm-bundler.js:10 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'insertBefore')
    at insert (runtime-dom.esm-bundler.js:10:16)
    at processCommentNode (runtime-core.esm-bundler.js:4519:13)
    at patch (runtime-core.esm-bundler.js:4471:17)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5107:17)
    at ReactiveEffect.run (reactivity.esm-bundler.js:160:29)
    at updateComponent (runtime-core.esm-bundler.js:4968:26)
    at processComponent (runtime-core.esm-bundler.js:4901:13)
    at patch (runtime-core.esm-bundler.js:4489:21)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5107:17)
    at ReactiveEffect.run (reactivity.esm-bundler.js:160:29)
insert @ runtime-dom.esm-bundler.js:10
processCommentNode @ runtime-core.esm-bundler.js:4519
patch @ runtime-core.esm-bundler.js:4471
componentUpdateFn @ runtime-core.esm-bundler.js:5107
run @ reactivity.esm-bundler.js:160
updateComponent @ runtime-core.esm-bundler.js:4968
processComponent @ runtime-core.esm-bundler.js:4901
patch @ runtime-core.esm-bundler.js:4489
componentUpdateFn @ runtime-core.esm-bundler.js:5107
run @ reactivity.esm-bundler.js:160
updateComponent @ runtime-core.esm-bundler.js:4968
processComponent @ runtime-core.esm-bundler.js:4901
patch @ runtime-core.esm-bundler.js:4489
componentUpdateFn @ runtime-core.esm-bundler.js:5107
run @ reactivity.esm-bundler.js:160
updateComponent @ runtime-core.esm-bundler.js:4968
processComponent @ runtime-core.esm-bundler.js:4901
patch @ runtime-core.esm-bundler.js:4489
componentUpdateFn @ runtime-core.esm-bundler.js:5107
run @ reactivity.esm-bundler.js:160
callWithErrorHandling @ runtime-core.esm-bundler.js:155
flushJobs @ runtime-core.esm-bundler.js:394
Promise.then (async)
queueFlush @ runtime-core.esm-bundler.js:285
queueJob @ runtime-core.esm-bundler.js:279
(anonymous) @ runtime-core.esm-bundler.js:5139
triggerEffects @ reactivity.esm-bundler.js:358
triggerRefValue @ reactivity.esm-bundler.js:959
(anonymous) @ reactivity.esm-bundler.js:1090
triggerEffects @ reactivity.esm-bundler.js:358
triggerRefValue @ reactivity.esm-bundler.js:959
set value @ reactivity.esm-bundler.js:1003
finalizeNavigation @ vue-router.esm-bundler.js?v=ca1ca381:3187
(anonymous) @ vue-router.esm-bundler.js?v=ca1ca381:3060
Promise.then (async)
pushWithRedirect @ vue-router.esm-bundler.js?v=ca1ca381:3031
push @ vue-router.esm-bundler.js?v=ca1ca381:2962
navigate @ vue-router.esm-bundler.js?v=ca1ca381:2089
callWithErrorHandling @ runtime-core.esm-bundler.js:155
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:164
invoker @ runtime-dom.esm-bundler.js:366
```

**Comment by mlsjla** [comment]
Same problem...

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/framework/issues/2867#issuecomment-1021568632
