### ISSUE TITLE
Error on Startup after Migration to Nuxt Bridge on Fresh Project

### ISSUE THREAD

**Issue by timgoeller** [nuxt/framework#2934]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.11.0`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Webpack`
- User Config:      `target`, `head`, `css`, `plugins`, `components`, `buildModules`, `modules`, `vuetify`, `build`
- Runtime Modules:  `-`
- Build Modules:    `@nuxtjs/vuetify@1.12.3`
------------------------------

### Reproduction

https://github.com/timgoeller/nuxt-bug

### Describe the bug

When generating a new empty Nuxt 2 project and applying the steps provided in the Nuxt Bridge getting started guide (https://v3.nuxtjs.org/getting-started/bridge/), calling `yarn dev` throws an error when using `nuxi dev` (using `nuxt` still works).

The error message is as follows:
```
 ERROR  Cannot read properties of undefined (reading 'callHook')                                                                           16:23:36

  at Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6773:31)
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async _main (node_modules/nuxi/dist/chunks/index.mjs:384:7)
```
I think it might have to do with this recent change, even though it seems like no one else encountered this issue yet: https://github.com/nuxt/framework/commit/4bd7adae4a7d43f7b906abec1149688d307954a3#diff-86f78f1673e500e055e8a1f266252abe62af18f0b52424f09275d7f2b1e96d3f

### Logs

```shell
yarn run v1.22.17
$ nuxi dev
Nuxt CLI v3.0.0-27386759.b449d0b                                                                                                           16:23:25
                                                                                                                                           16:23:25
  > Local:    http://localhost:3000/
  > Network:  http://192.168.0.31:3000/

ℹ Preparing project for development                                                                                                        16:23:28
ℹ Initial build may take a while                                                                                                           16:23:28
ℹ Discovered Components: .nuxt/components/readme.md                                                                                        16:23:28
✔ Builder initialized                                                                                                                      16:23:28
✔ Nuxt files generated                                                                                                                     16:23:28

✔ Client
  Compiled successfully in 7.54s

✔ Server
  Compiled successfully in 6.49s

ℹ Waiting for file changes                                                                                                                 16:23:36

 ERROR  Cannot read properties of undefined (reading 'callHook')                                                                           16:23:36

  at Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6773:31)
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async _main (node_modules/nuxi/dist/chunks/index.mjs:384:7)
```

**Comment by Dell-it** [comment]
You are not alone, I also faced the same problem

**Comment by danielroe** [comment]
Looking at this, the issue is caused by not using Bridge. (You need to [update your nuxt.config](https://v3.nuxtjs.org/getting-started/bridge#update-nuxtconfig).)

**Comment by wolzey** [comment]
I have an updated config and still am experiencing this issue.

**Comment by danielroe** [comment]
@wolzey Would you share a reproduction?

**Comment by wolzey** [comment]
@danielroe thanks for re-opening and the quick response. I re-applied the changes to upgrade to Nuxt 3 using Bridge and am no longer getting the error. I think we can mark this one down as a user error and re-close. Thanks!

**Comment by neothon** [comment]
I am still getting the same issue but while using nuxt bridge. I haven't tried upgrading to Nuxt 3 yet though.

**Comment by Torgian** [comment]
I'm receiving the same error, but on an older project running nuxtJS and Vue 2, along with Vuetify.

Environment:

```
------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.2`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `yarn@1.22.4`
- Builder:          `webpack`
- User Config:      `bridge`, `env`, `serverMiddleware`, `head`, `css`, `router`, `modules`, `plugins`, `build`, `buildModules`, `optimizedImages`
- Runtime Modules:  `@nuxtjs/axios@5.13.6`, `@nuxtjs/auth@4.9.1`, `cookie-universal-nuxt@2.1.5`, `@nuxtjs/toast@3.3.1`, `@nuxtjs/vuetify@1.12.3`, `nuxt-user-agent@1.2.2`
- Build Modules:    `@nuxt/typescript-build@2.1.0`, `@aceforth/nuxt-optimized-images@1.4.0`
------------------------------
```

Error: 

```
 ERROR  Cannot read properties of undefined (reading 'callHook')                                                                                  13:54:25

  at Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6803:31)
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:46:20)
```


Here is a list of modules I'm using, though I'm not sure this matters:

```
"dependencies": {
    "@mdi/js": "^6.5.0",
    "@nuxtjs/auth": "^4.9.1",
    "@nuxtjs/axios": "^5.9.5",
    "@nuxtjs/pwa": "^3.0.0-0",
    "@nuxtjs/toast": "^3.3.0",
    "@nuxtjs/vuetify": "^1.9.0",
    "chart.js": "^2.9.3",
    "cookie-universal-nuxt": "^2.0.19",
    "cross-env": "^7.0.0",
    "encoding-japanese": "^1.0.30",
    "epic-spinners": "^1.1.0",
    "exceljs": "^4.3.0",
    "lodash": "^4.7.0",
    "nuxt-edge": "latest",
    "nuxt-user-agent": "^1.2.2",
    "papaparse": "^5.3.1",
    "validatorjs": "^3.17.1",
    "vue-chartjs": "^3.5.0",
    "vue-tippy": "^4.0.3",
    "zxcvbn": "^4.4.2"
  },
  "devDependencies": {
    "@aceforth/nuxt-optimized-images": "^1.4.0",
    "@nuxt/bridge": "npm:@nuxt/bridge-edge",
    "@nuxt/types": "^2.14.12",
    "@nuxt/typescript-build": "^2.0.3",
    "@nuxtjs/eslint-config": "^1.0.1",
    "@nuxtjs/eslint-module": "^3.0.2",
    "@vue/test-utils": "^1.0.3",
    "babel-eslint": "^10.0.1",
    "babel-jest": "^27.4.0",
    "eslint": "^6.1.0",
    "eslint-plugin-nuxt": "^3.1.0",
    "imagemin-pngquant": "^9.0.1",
    "imagemin-svgo": "^9.0.0",
    "jest": "^27.1.0",
    "js-yaml-loader": "^1.2.2",
    "json-loader": "^0.5.7",
    "prettier": "^2.5.1",
    "pug": "^3.0.0",
    "pug-plain-loader": "^1.0.0",
    "stylus": "^0.56.0",
    "stylus-loader": "^3.0.2",
    "vue-jest": "^4.0.0-0",
    "webp-loader": "^0.6.0"
  }
}

```

### Note: 

I know that `    "@nuxt/typescript-build": "^2.0.3",` should be removed, but when I remove that, I get errors with importing files in the `utilities` folder. I left it in and instead passed this to the `Nuxt.config.js` file:

```
  bridge: {
    typescript: false,
  },
```

I'm at a loss.

**Comment by Remo** [comment]
Same for me, I even got a test repo where it happens: https://github.com/Remo/laravel-nuxt-bridge
