### ISSUE TITLE
[worker] __vite_ssr_import_8__.extend is not a function

### ISSUE THREAD

**Issue by bynicodevelop** [nuxt/framework#2969]
### Environment

Nuxt CLI v3.0.0-27376943.f219f63
Nuxt project info: 

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.12.0`
- Nuxt Version:     `3.0.0-27376943.f219f63`
- Package Manager:  `yarn@1.22.10`
- Bundler:          `Vite`
- User Config:      `srcDir`, `css`, `build`, `serverMiddleware`, `publicRuntimeConfig`, `privateRuntimeConfig`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

When I make a change to my code.
On a fairly advanced project.

### Describe the bug

I have this error which is displayed and which ends up blocking the refresh of my page
(apart from hot reload)

```
 ERROR  [worker] __vite_ssr_import_8__.extend is not a function                                                                              12:00:15

  at setup (.nuxt/dist/server/server.mjs:38489:27)
  at _sfc_main.setup (.nuxt/dist/server/server.mjs:38636:23)
  at callWithErrorHandling (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:157:22)
  at setupStatefulComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6964:29)
  at setupComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6920:11)
  at renderComponentVNode (node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:198:17)
  at renderVNode (node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:304:22)
  at renderVNode (node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:310:17)
  at renderComponentSubTree (node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:269:13)
  at renderComponentVNode (node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:214:16)
  at renderVNode (node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:304:22)
  at renderComponentSubTree (node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:221:9)
  at renderComponentVNode (node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:214:16)
  at renderVNode (node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:304:22)
  at renderComponentSubTree (node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:269:13)
  at renderComponentVNode (node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:214:16)


 ERROR  [proxy] connect ENOENT /var/folders/62/ssjss8m51ml_tpwwz59c3s2c0000gn/T/nitro/worker-98248-6.sock                                    12:00:16

  at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1161:16)
```

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏 I would guess it might be a vue import in a component library - perhaps add that library to your build.transpile array?

**Comment by bynicodevelop** [comment]
I am trying to find the cause of this problem. But I can't find what allows me to reproduce this error.

It happens when I make a change in the code.

Just before I have this type of message:

```
[Vue warn]: Unhandled error during execution of setup function 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > key="/adminer/projects/qsdsqd-88tsv89/editors/tweets/" >
__vite_ssr_import_8__.extend is not a function
  at setup (file://./.nuxt/dist/server/server.mjs:38525:27)  
  at _sfc_main.setup (file://./.nuxt/dist/server/server.mjs:38672:23)  
  at callWithErrorHandling (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:157:22)  
  at setupStatefulComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6964:29)  
  at setupComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6920:11)  
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:198:17)  
  at renderVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:304:22)  
  at renderVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:310:17)  
  at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:269:13)  
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:214:16)  
  at renderVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:304:22)  
  at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:221:9)  
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:214:16)  
  at renderVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:304:22)  
  at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:269:13)  
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:214:16)
[Vue warn]: Unhandled error during execution of setup function 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > key="/adminer/projects/qsdsqd-88tsv89/editors/tweets/" >
```

And I don't use `Vue.extend` 😉

I'm trying to see if it's from a specific package 🤷🏻‍♂️

**Comment by bynicodevelop** [comment]
OK, I think I have a lead...

It is by integrating the following package: "vue3-date-time-picker" (https://vue3datepicker.com/)

I create a plugin like this:

datepicker.client.ts
```
import { defineNuxtPlugin } from '#app'
import Datepicker from 'vue3-date-time-picker';
import 'vue3-date-time-picker/dist/main.css'

export default defineNuxtPlugin((nuxtApp) => {
    nuxtApp.vueApp.component('Datepicker', Datepicker);
})
```

Then I import the component into my code as follows:

```
<template>
<div>
// Code HTML
<Datepicker v-model="date" range :minDate="new Date()" />
// Code HTML
</div>
</template>

<script>
const props = defineProps({
  date: {
    type: Object,
    default: null,
  },
});
</script>
```

And suddenly I got the following error:

```
[Vue warn]: Failed to resolve component: Datepicker
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
Invalid value used as weak map key
  at WeakMap.set (<anonymous>)  
  at normalizePropsOptions (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3382:11)  
  at createComponentInstance (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6838:23)  
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:197:22)  
  at Module.ssrRenderComponent (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:623:12)  
  at _sfc_ssrRender (file://./.nuxt/dist/server/server.mjs:46491:31)  
  at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:263:13)  
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:214:16)  
  at Module.ssrRenderComponent (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:623:12)  
  at _sfc_ssrRender (file://./.nuxt/dist/server/server.mjs:46413:31)  
  at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:263:13)  
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:214:16)  
  at renderVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:304:22)  
  at renderVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:310:17)  
  at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:269:13)  
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:214:16)
[Vue warn]: Failed to resolve component: Datepicker
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
```

then :

```
 ERROR  [worker] Invalid value used as weak map key                                                                                          17:19:05

  at WeakMap.set (<anonymous>)
  at normalizePropsOptions (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3382:11)
  at createComponentInstance (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6838:23)
  at renderComponentVNode (node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:197:22)
  at Module.ssrRenderComponent (node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:623:12)
  at _sfc_ssrRender (.nuxt/dist/server/server.mjs:46491:31)
  at renderComponentSubTree (node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:263:13)
  at renderComponentVNode (node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:214:16)
  at Module.ssrRenderComponent (node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:623:12)
  at _sfc_ssrRender (.nuxt/dist/server/server.mjs:46413:31)
  at renderComponentSubTree (node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:263:13)
  at renderComponentVNode (node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:214:16)
  at renderVNode (node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:304:22)
  at renderVNode (node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:310:17)
  at renderComponentSubTree (node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:269:13)
  at renderComponentVNode (node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:214:16)


 ERROR  [proxy] connect ENOENT /var/folders/62/ssjss8m51ml_tpwwz59c3s2c0000gn/T/nitro/worker-19365-1.sock                                    17:19:06

  at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1161:16)
```

**Comment by bynicodevelop** [comment]
Ok I solved the problem It came from the name of the plugin file. 

I removed the ".client" 

However, I would like to understand why I had this "bug". 🤔

**Comment by danielroe** [comment]
Probably because you only installed the component on client side, but you were still trying to use it within a bit of your template that was rendered on SSR.
