### ISSUE TITLE
Cannot read properties of null (reading 'parentNode')

### ISSUE THREAD

**Issue by nurdism** [nuxt/framework#2985]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v14.18.1`
- Nuxt Version:     `3.0.0-27389502.88da719`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `ssr`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

use this [sandbox](https://codesandbox.io/s/tender-kare-e87h0), Visit `${url}/organization/365824000000000003/template/new` click on the "a" link then the "b" link and this error is thrown:

```
runtime-core.esm-bundler.js:38 [Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://new-issue.vuejs.org/?repo=vuejs/core 
  at <Transition name="page" mode="out-in" > 
  at <Dashboard name="dashboard" > 
  at <AsyncComponentWrapper name="dashboard" > 
  at <NuxtLayout name="dashboard" > 
  at <BaseTransition mode="out-in" appear=false persisted=false  ... > 
  at <Transition name="layout" mode="out-in" > 
  at <RouterView > 
  at <NuxtPage> 
  at <App> 
  at <NuxtRoot>
```
```
runtime-dom.esm-bundler.js:35 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'parentNode')
    at parentNode (runtime-dom.esm-bundler.js:35:30)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5109:17)
    at ReactiveEffect.run (reactivity.esm-bundler.js:160:29)
    at updateComponent (runtime-core.esm-bundler.js:4968:26)
    at processComponent (runtime-core.esm-bundler.js:4901:13)
    at patch (runtime-core.esm-bundler.js:4489:21)
    at patchKeyedChildren (runtime-core.esm-bundler.js:5262:17)
    at patchChildren (runtime-core.esm-bundler.js:5205:21)
    at processFragment (runtime-core.esm-bundler.js:4886:17)
    at patch (runtime-core.esm-bundler.js:4482:17)
```

### Describe the bug

hooks `page:start` and `page:finish` don't seem to fire on pages  `${url}/organization/*` and an error is thrown when using `await` in the `<script setup>` and then navigating to a new page. 

I don't know if this is due to the page structure or the the way the pages are set up. It's taken me all day to get this error to reproduce and the only way I've gotten this to throw is with this folder structure and by 
* first visiting a page that doesn't use await in the `<script setup>` 
* then visiting a page that does us await
* then by using vue-router to navigate to another page

**Comment by rvmourik** [comment]
Don't now if it is helpful, but I experienced some similar errors while developing our app. In the end it was caused by a transition component as the root component in the template. Navigating between routes sometimes caused the `parentNode` issue.

Also our pages setup looks a lot like yours, so maybe it is helpful :-)

**Comment by nurdism** [comment]
@rvmourik is on the right track, I went ahead and recreated the [`<NuxtPage />`](https://github.com/nuxt/framework/blob/main/packages/nuxt3/src/pages/runtime/page.ts) component, when I remove the [`<Transition />`](https://github.com/nuxt/framework/blob/main/packages/nuxt3/src/pages/runtime/page.ts#L31) before the `<NuxtLayout />` the error does not pop up, but the `page:start` and the `page:finish` are still not firing

**Comment by rvmourik** [comment]
> @rvmourik is on the right track, I went ahead and recreated the [`<NuxtPage />`](https://github.com/nuxt/framework/blob/main/packages/nuxt3/src/pages/runtime/page.ts) component, when I remove the [`<Transition />`](https://github.com/nuxt/framework/blob/main/packages/nuxt3/src/pages/runtime/page.ts#L31) before the `<NuxtLayout />` the error does not pop up, but the `page:start` and the `page:finish` are still not firing

I did the exact same thing to work around the error, it might be related to the combination of dynamic routes and nested pages.

**Comment by anburocky3** [comment]
I too face the same problem, i did created a `div` parent of `app.vue` and the link is navigating now, but i see the following error consoled.

```
vue.js?v=2018aa88:103 [Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://new-issue.vuejs.org/?repo=vuejs/core 
  at <Anonymous> 
  at <App key=1 > 
  at <NuxtRoot>
warn @ vue.js?v=2018aa88:103
logError @ vue.js?v=2018aa88:257
handleError @ vue.js?v=2018aa88:249
callWithErrorHandling @ vue.js?v=2018aa88:206
flushJobs @ vue.js?v=2018aa88:396
Promise.then (async)
queueFlush @ vue.js?v=2018aa88:311
queueJob @ vue.js?v=2018aa88:305
(anonymous) @ vue.js?v=2018aa88:4057
triggerEffects @ chunk-ABITFNDB.js?v=2018aa88:571
triggerRefValue @ chunk-ABITFNDB.js?v=2018aa88:1072
(anonymous) @ chunk-ABITFNDB.js?v=2018aa88:1196
triggerEffects @ chunk-ABITFNDB.js?v=2018aa88:571
triggerRefValue @ chunk-ABITFNDB.js?v=2018aa88:1072
(anonymous) @ chunk-ABITFNDB.js?v=2018aa88:1196
triggerEffects @ chunk-ABITFNDB.js?v=2018aa88:571
triggerRefValue @ chunk-ABITFNDB.js?v=2018aa88:1072
(anonymous) @ chunk-ABITFNDB.js?v=2018aa88:1196
triggerEffects @ chunk-ABITFNDB.js?v=2018aa88:571
triggerRefValue @ chunk-ABITFNDB.js?v=2018aa88:1072
(anonymous) @ chunk-ABITFNDB.js?v=2018aa88:1196
triggerEffects @ chunk-ABITFNDB.js?v=2018aa88:571
triggerRefValue @ chunk-ABITFNDB.js?v=2018aa88:1072
set value @ chunk-ABITFNDB.js?v=2018aa88:1115
finalizeNavigation @ vue-router.esm-bundler.js?v=2018aa88:3194
(anonymous) @ vue-router.esm-bundler.js?v=2018aa88:3067
Promise.then (async)
pushWithRedirect @ vue-router.esm-bundler.js?v=2018aa88:3038
push @ vue-router.esm-bundler.js?v=2018aa88:2966
navigate @ vue-router.esm-bundler.js?v=2018aa88:2093
callWithErrorHandling @ vue.js?v=2018aa88:204
callWithAsyncErrorHandling @ vue.js?v=2018aa88:212
invoker @ vue.js?v=2018aa88:6193
vue.js?v=2018aa88:5960 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'parentNode')
    at parentNode (vue.js?v=2018aa88:5960:30)
    at ReactiveEffect.componentUpdateFn [as fn] (vue.js?v=2018aa88:4035:35)
    at ReactiveEffect.run (chunk-ABITFNDB.js?v=2018aa88:399:19)
    at callWithErrorHandling (vue.js?v=2018aa88:204:32)
    at flushJobs (vue.js?v=2018aa88:396:9)
```

Is this vue bug?

**Comment by danielroe** [comment]
The original reproduction now longer gives this error, when wrapping `<NuxtPage>`:

```diff
  <template>
+   <div>
      <NuxtPage />
+   </div>
  </template>
```

See https://codesandbox.io/s/immutable-fast-kv6yh0

**Comment by anburocky3** [comment]
Yes, I was having my code like this

```html
<template>
    <NuxtLayout>
        <NuxtPage />
    </NuxtLayout>
</template>
```

Wrapping the `<NuxtLayout>` with `div` fixed the issue.

**Comment by anburocky3** [comment]
> @danielroe @anburocky3 I ran into this problem too, adding div wraps to NuxtPage didn't fix it either. Router. push or NuxtLink can be used to jump to the page normally. However, if you jump to the page after refreshing the browser, a parentNode problem will occur. Finally, refresh the browser to display the page.

Any reproduction steps? Try to upgrade to nuxt3 latest and retry it.

**Comment by Guovin** [comment]
> > @danielroe @anburocky3 I ran into this problem too, adding div wraps to NuxtPage didn't fix it either. Router. push or NuxtLink can be used to jump to the page normally. However, if you jump to the page after refreshing the browser, a parentNode problem will occur. Finally, refresh the browser to display the page.
> 
> Any reproduction steps? Try to upgrade to nuxt3 latest and retry it.
I'm using the latest version of Nuxt3, which I suspect is due to useLazyAsyncData. When I used Axios, I had 500 errors when I refreshed the page. To solve this problem, I used useLazyAsyncData to get the request data, but after refreshing the page, I couldn't redirect the route.

**Comment by Guovin** [comment]
> I'm using the latest version of Nuxt3, which I suspect is due to useLazyAsyncData. When I used Axios, I had 500 errors when I refreshed the page. To solve this problem, I used useLazyAsyncData to get the request data, but after refreshing the page, I couldn't redirect the route.

I'm using the latest version of Nuxt3, which I suspect is due to useLazyAsyncData. When I used Axios, I had 500 errors when I refreshed the page. To solve this problem, I used useLazyAsyncData to get the request data, but after refreshing the page, I couldn't redirect the route.

**Comment by Guovin** [comment]
> > @danielroe @anburocky3 I ran into this problem too, adding div wraps to NuxtPage didn't fix it either. Router. push or NuxtLink can be used to jump to the page normally. However, if you jump to the page after refreshing the browser, a parentNode problem will occur. Finally, refresh the browser to display the page.
> 
> Any reproduction steps? Try to upgrade to nuxt3 latest and retry it.

Finally, I close SSR and solve this problem.

**Comment by potatozerg** [comment]
My local works fine, but when I deploy on dev(firebase), I got the same error whenever I route to another page.

**Comment by tinegaCollins** [comment]
> > > @danielroe @anburocky3 I ran into this problem too, adding div wraps to NuxtPage didn't fix it either. Router. push or NuxtLink can be used to jump to the page normally. However, if you jump to the page after refreshing the browser, a parentNode problem will occur. Finally, refresh the browser to display the page.
> > 
> > 
> > Any reproduction steps? Try to upgrade to nuxt3 latest and retry it.
> 
> Finally, I close SSR and solve this problem.

i am using nuxt3 but i am still getting this error

**Comment by tinegaCollins** [comment]
i created a new nuxt application and transferred my files to the new application following the rules from the nuxt3 docs. problem fixed.

**Comment by aurendev** [comment]
> i created a new nuxt application and transferred my files to the new application following the rules from the nuxt3 docs. problem fixed.

how ?

**Comment by rvmourik** [comment]
> > i created a new nuxt application and transferred my files to the new application following the rules from the nuxt3 docs. problem fixed.
> 
> how ?

make sure when a component like  `NuxtLayout` or `NuxtPage` is the root-node (first in template) to be wrapped within a `div`.

**Comment by Deyjandi** [comment]
In my case this bug happens when switching between pages with different layouts defined in definePageMeta, regardless the parent of NuxtPage element.

**Comment by jshimkoski** [comment]
This bit me as well.

Dynamic route with nested pages was throwing the error when navigating around.

Wrapping `NuxtLayout` with a `<div>` fixed the issue for me.

**Comment by tinegaCollins** [comment]
try wrapping all the elements on the page in one single element
the NUXTlayout should be in the div

**Comment by kstraszewski** [comment]
I am getting excaly the same error when try to navigate between routes. All my pages have this structure:
<img width="401" alt="image" src="https://user-images.githubusercontent.com/10195995/176666636-131df3dc-1996-4249-bafe-50fc9034ff85.png">

**Comment by n00kii** [comment]
I am also having this error, was there any resolution reached? my `pages/` looks like this: 
```
pages
└── [group]
    ├── index.vue
    └── [id].vue
```
and my `app.vue` is this: (the `<v-xxx>` components are of the `vuetify` library)
```html
<v-app>
    <Header />
    <v-main>
        <v-container class="my-4">
            <NuxtLayout>
                <NuxtPage />
            </NuxtLayout>
        </v-container>
    </v-main>
    <Footer />
</v-app>
```
When I generate my app (`target: static`) and try to navigate to a `page/[group]` from the home page, this error appears and navigation fails. If I then refresh, I can navigate freely across all of my application, until I refresh again while on the home page.

**Comment by Fred-grais** [comment]
Any news on this? I'm having the same exact error in my Nuxt3 RC 6 app

**Comment by adamkasper** [comment]
In RC 8 still the same problem

**Comment by codeflorist** [comment]
apart from this solution provided by @danielroe ...

> ```diff
>   <template>
> +   <div>
>       <NuxtPage />
> +   </div>
>   </template>
> ```

... i found that components having another component as their root-element also was cause of this problem. wrapping these with a html-element (e.g. `div`) solved the problem for me.

**Comment by LynxTR** [comment]
Plus,

You can meet with this issue while using nested layouts. You have to append page-key attribute to it.

**Comment by michealroberts** [comment]
I'm seeing this error with the above solution from @codeflorist in rc-9:

```
[Vue warn]: Unhandled error during execution of setup function 
  at <RouterView name=undefined route=undefined >
[nitro] [dev] [unhandledRejection] TypeError: Cannot read properties of null (reading 'parent')
```
My app.vue component:

```
<template>
  <div>
    <NuxtPage />
  </div>
</template>
```

My pages/index.vue component:

```
<template>
  <div>
    <h1>Index page</h1>
  </div>
</template>

<script setup lang="ts"></script>
```

That's the only changes I have made to the base rc-9 installation ...

**Comment by JFGHT** [comment]
Having this in RC9 too. Why is this classified as minor bug by the way?

**Comment by danielroe** [comment]
If you are experiencing this, would you provide a stackblitz reproduction so we can look into it? 🙏

**Comment by JFGHT** [comment]
I managed to fix it by upgrading and fixing a bunch of dependencies. Too bad I cannot say what my changes were because I lost track at some point.

**Comment by NexZhu** [comment]
Same issue on rc.8

**Comment by NexZhu** [comment]
My workaround: `vue-router` version to `4.0.16`

**Comment by nikowonde** [comment]
@danielroe I made quick repro: https://stackblitz.com/edit/github-zjms7z?file=app.vue which seems to cause similar error I am facing on my project. Clicking any of the links on /page.vue seems to cause it. Not sure if similar problem for others.

**Comment by codingcn** [comment]
Same issue on rc.11

**Comment by codingcn** [comment]
```
runtime-dom.esm-bundler.js:13 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'parentNode')
    at remove (runtime-dom.esm-bundler.js:13:30)
    at Object.remove (runtime-core.esm-bundler.js:6469:13)
    at unmount (runtime-core.esm-bundler.js:6079:28)
    at unmountComponent (runtime-core.esm-bundler.js:6183:13)
    at unmount (runtime-core.esm-bundler.js:6068:13)
    at unmountChildren (runtime-core.esm-bundler.js:6212:13)
    at unmount (runtime-core.esm-bundler.js:6086:17)
    at unmountComponent (runtime-core.esm-bundler.js:6183:13)
    at unmount (runtime-core.esm-bundler.js:6068:13)
    at unmountComponent (runtime-core.esm-bundler.js:6183:13)
```

**Comment by ww-lemon** [comment]
I had same issue, wrapping `<NuxtLayout>` with `<div>` and explicitly defining layout in each page solved the problem for me.

```
layouts
└── default.vue
└── empty.vue
```

**/app.vue**
```
<template>
  <div>
    <NuxtLayout>
      <NuxtLoadingIndicator />
      <NuxtPage />
    </NuxtLayout>
  </div>
</template>
```

**piece of code in each page /pages**

```
definePageMeta({
  layout: 'default',
  ....
})
```

**Comment by FinnPaes** [comment]
Having the same issue here, tried all fixes mentioned above, didn't solve it in my case :/

**Comment by mannyyang** [comment]
I've been pulling my hair out trying to figure out what was throwing this error and in my case I was able to get it resolved by removing any top level `await` functions in my vue components.

**Comment by codingcn** [comment]
I solved this problem by using `<client-only></client-only>` on the outer layer of sub components

**Comment by secretlifeof** [comment]
> I've been pulling my hair out trying to figure out what was throwing this error and in my case I was able to get it resolved by removing any top level `await` functions in my vue components.

Version:  rc.11

Can confirm something similar.

This doesn't work in `pages/index.tsx`
```
export default defineComponent({
  async setup(props) {
    return () => <div>JAA</div>;
  },
});
```

but this works
```
export default defineComponent({
  setup(props) {
    return () => <div>JAA</div>;
  },
});
```

Server side rendering seems to work. But changing the JSX, causing HMR, leaves the before mentioned error message in the console.

**Comment by steklopod** [comment]
Same for me when I change pages with different layouts
<img width="1289" alt="Снимок экрана 2022-10-09 в 12 19 05" src="https://user-images.githubusercontent.com/29500153/194751265-43678490-e2cb-418d-acba-0c52403dc0a4.png">

> layouts/blank.vue
```vue
<script setup lang="ts">
import { useCustomizerStore } from '@/stores/customizer'

const customizer = useCustomizerStore()
useMeta({
  title: 'AdminPro NuxtJs Dashboard'
})
</script>

<template>
  <v-app
    :theme="customizer.darktheme ? 'dark' : 'light'"
    :class="[customizer.mini_sidebar ? 'mini-sidebar' : '', 'horizontalLayout']"
  >
    <v-main>
      <v-container>
        <slot />
      </v-container>
    </v-main>
  </v-app>
</template>
```

> When redirected to simple main page
```vue
<template>
  <v-container>
    BUTTON
    <v-icon :icon="mdiFacebook" />
  </v-container>
</template>

<script setup lang="ts">
import { mdiFacebook } from '@mdi/js'

const env = useRuntimeConfig()

definePageMeta({ layout: 'blank' })
useMeta({ title: 'Colaba - DEV' })
</script>
```

**Comment by steklopod** [comment]
Got the same error. Fixed by adding  wrapper tag `<v-no-ssr>` around `<v-snackbar>`:

But it took a long time to find this place
```vue
 <v-no-ssr>
      <v-snackbar v-model="snackbar.show" top multi-line :timeout="snackbar.timeout" :color="snackbar.color">
        {{ snackbar.text }}
        <template #actions>
          <v-btn color="secondary" @click="snackbar.show = false">
            Close
          </v-btn>
        </template>
      </v-snackbar>
    </v-no-ssr>
```

**Comment by secretlifeof** [comment]
The only fix for me was to disable transitions. Took me a while figuring out how this is done with TSX.

app.vue
```
<script lang="tsx" setup></script>
<template>
  <div>
    <NuxtPage :transition="false" />
  </div>
</template>
```

defineMetaPage cannot be used inside TSX files since it's compiled away. https://v3.nuxtjs.org/api/utils/define-page-meta/#definepagemeta. This is off topic, but does anybody know how to use this API with JSX/TSX files?

**Comment by EvanSchleret** [comment]
I have same issue in one of my project. I just created new Nuxt 3 project with two basics layouts for the test.  Here's my few files :

_app.vue_
```vue
<template>
  <div>
    <NuxtLayout>
      <NuxtLoadingIndicator />
      <NuxtPage />
    </NuxtLayout>
  </div>
</template>
```

_layouts/default.vue_
```vue
<template>
  <div>
    <Header></Header>
  </div>

  <div>
    <slot></slot>
  </div>
</template>
```

_layouts/custom.vue_
```vue
<template>
  <div>
    <CustomHeader></CustomHeader>
  </div>

  <slot></slot>
</template>
```

_components/Header.vue_
```vue
<template>
  <div>
    <NuxtLink to="/">Home</NuxtLink>
    <NuxtLink to="about">About</NuxtLink>
  </div>
</template>
```

_components/CustomHeader_
```vue
<template>
  <div>
    <NuxtLink to="/">Home</NuxtLink>
    <NuxtLink to="about">About</NuxtLink>
    <NuxtLink to="https://www.google.com" target="_blank">Google !</NuxtLink>
  </div>
</template>
```

_pages/index.vue_
```vue
<template>
  <div>
    Hello World !
  </div>
</template>

<script setup>
definePageMeta({
  layout: 'default'
})
</script>
```

_pages/contact.vue_
```vue
<template>
  <div>
    Contact us
  </div>
</template>

<script setup>
definePageMeta({
  layout: 'custom'
})
</script>
```

Just changing from one layout to the other cause the bug, except that I haven't any errors in console 🤡 

The root cause seems to be the layout change.

When using the overriding layout, it works (https://v3.nuxtjs.org/guide/directory-structure/layouts#overriding-a-layout-on-a-per-page-basis). On the other hand, the transition between the pages is perceptible...

I'm really not a nuxt expert, so hopefully my comment will be helpful to someone in finding out the real problem.

**Comment by sangyookim-ogq** [comment]
I'm experiencing the same errors. However, it happens in the following.

Situation: 

I have a page that loads list of data from async setup. The list fetching fetches different data depending on query parameters of route. 

All works fine, BUT,

when I navigate away from said list page, but forward back into the page, lets say

/list
->
/list?someQuery=123

The error occurs and app breaks.

so basically, if I forward into /list and wait for it to load, then forward into /list?someQuery=123, it works FINE.

BUT, when I forward into /list/someQuery=123 before /list finishes running, the error occurs. It doesnt even matter if I remove every related HTML (template) and leave it as <div></div>.

**Comment by Vincebe** [comment]
Ran into similar issue. Had to remove <NuxtLayout> from app.

**Comment by localusercamp** [comment]
I had this problem with this configuration
![image](https://user-images.githubusercontent.com/45385480/209166819-bce397f6-ac3b-4154-9252-3a727928e4dd.png)

To fix it i transferred `[id]/main.vue` and `[id]/media.vue` to components and remove `[id]` folder.
May be it will help somebody.

**Comment by Teplophizik** [comment]
> I had this problem with this configuration ![image](https://user-images.githubusercontent.com/45385480/209166819-bce397f6-ac3b-4154-9252-3a727928e4dd.png)
> 
> To fix it i transferred `[id]/main.vue` and `[id]/media.vue` to components and remove `[id]` folder. May be it will help somebody.

There was the same problem. At first it was solved the same way. Then I realised that this solution was not suitable. It took me a long time to figure out what the problem was. It turned out that when switching from one page with nested pages to another page with nested pages, <NuxtPage /> didn't seem to have time to change. This causes the props to be undefined and everything crashes. Invented this:
```
const nestedShowed = ref(true);
const router = useRouter();
router.beforeEach((to, from) => {
  if (to.fullPath.split("/")[1] !== from.fullPath.split("/")[1]) {
    nestedShowed.value = false;
  }
});
<NuxtPage v-if="nestedShowed" :club="mainInfo" />
```
This disables <NuxtPage /> first, and only then goes to the new page.

Translated with www.DeepL.com/Translator (free version)

**Comment by localusercamp** [comment]
@Teplophizik Хорооош =)
For me it was not so critical so I easily switched from pages to components. But this bug can be very annoying in deeply nested layouts...

**Comment by kaboume** [comment]
Hi,
I have the same issue with Nuxt + Vuetify.
When I change the route (router.push('...')), I'm getting this errors :
```

TypeError: Cannot read properties of null (reading 'parentNode')
    at remove (runtime-dom.esm-bundler.js:13:30)
    at Object.remove (runtime-core.esm-bundler.js:6503:13)
    at unmount (runtime-core.esm-bundler.js:6108:28)
    at unmountChildren (runtime-core.esm-bundler.js:6241:13)
    at unmount (runtime-core.esm-bundler.js:6121:17)
    at unmountComponent (runtime-core.esm-bundler.js:6212:13)
    at unmount (runtime-core.esm-bundler.js:6097:13)
    at unmountComponent (runtime-core.esm-bundler.js:6212:13)
    at unmount (runtime-core.esm-bundler.js:6097:13)
    at unmountChildren (runtime-core.esm-bundler.js:6241:13)
```

**Comment by sangyoo91** [comment]
Hopefully, this gets fixed so that we don't have to use messy workarounds..

**Comment by manniL** [comment]
It can only be fixed if someone can provide an up-to-date reproduction 👀

**Comment by EvanSchleret** [comment]
I reproduced it with the example I showed last time.  The only case where the bug recurs is when I use the Teleport tag on a dom element such as a div with an id.

**Comment by manniL** [comment]
> I reproduced it with the example I showed last time. The only case where the bug recurs is when I use the Teleport tag on a dom element such as a div with an id.

Could you provide a link to a CodeSandbox, StackBlitz or Git repo for the reproduction? ☺️

**Comment by WalterKstro** [comment]
I have the next problem, when change between pages and make a request to api, show me this error 
`TypeError: i.value is null`

**Comment by Teplophizik** [comment]
> It can only be fixed if someone can provide an up-to-date reproduction 👀

@manniL 
repro - https://stackblitz.com/edit/nuxt-starter-mwn7h2

For example, if navigate from:
- test-bad to test-bad2 - props.data2 = null for nested page. Page must be reloaded;
- test-bad to test-good2 - props.data2 = null  for nested page. Page must be reloaded;
- test-bad to test-good - props.data for nested page remains the same at first;

test-good/test-good2 - everything I could think of to make the behaviour expected

**Comment by MosheL** [comment]
Hi ! I am receive the same error on production build.

````
import  SnippetArticleTop from './SnippetArticleTop'
export default {
  name: 'SnippetArticleData',
  components: {
    SnippetArticleTop,
  .....
`````
works (on production build)


``````
const SnippetArticleTop = defineAsyncComponent(() => import('./SnippetArticleTop'))
//with the same code
``````
not work. I suspect the  defineAsyncComponent has a null parent or similar but I did not deeply understand what realy going on.


Thanks.
