### ISSUE TITLE
Can't push global middleware to global middleware list in plugins (Production only)

### ISSUE THREAD

**Issue by huuhait** [nuxt/framework#2999]
### Describe the bug

![image](https://user-images.githubusercontent.com/40519768/151709658-ff10720b-1d20-4891-95e1-33c67904e6b6.png)

### Logs

```shell
Cannot read properties of undefined (reading 'push')
  at addRouteMiddleware (file://./.output/server/chunks/app/server.mjs:4299:36)  
  at file://./.output/server/chunks/app/server.mjs:18190:3  
  at callWithNuxt (file://./.output/server/chunks/app/server.mjs:1066:20)  
  at applyPlugin (file://./.output/server/chunks/app/server.mjs:1023:29)  
  at applyPlugins (file://./.output/server/chunks/app/server.mjs:1032:11)  
  at async createNuxtAppServer (file://./.output/server/chunks/app/server.mjs:19406:5)  
  at async renderToString (file://./.output/server/chunks/app/render.mjs:258:19)  
  at async renderMiddleware (file://./.output/server/chunks/app/render.mjs:575:20)  
  at async handle (file://./.output/server/node_modules/h3/dist/index.mjs:601:19)
```

**Comment by huuhait** [comment]
any idea?

**Comment by wobsoriano** [comment]
Can confirm this. A simple middleware plugin like this:

```ts
export default defineNuxtPlugin(() => {
  const user = useUser();
  addRouteMiddleware(
    'auth',
    (to) => {
      if (to.path === '/' && user.value) {
        return navigateTo('/private');
      }

      if (to.path !== '/' && !user.value) {
        return navigateTo('/');
      }

      return;
    },
    { global: true }
  );
});
```

Works on dev. Error on prod:

```
Cannot read properties of undefined (reading 'push')
  at addRouteMiddleware (file://./.output/server/chunks/app/server.mjs:3383:36)
  at file://./.output/server/chunks/app/server.mjs:3573:3
  at callWithNuxt (file://./.output/server/chunks/app/server.mjs:335:20)
  at applyPlugin (file://./.output/server/chunks/app/server.mjs:292:29)
  at applyPlugins (file://./.output/server/chunks/app/server.mjs:301:11)
  at async createNuxtAppServer (file://./.output/server/chunks/app/server.mjs:4000:5)
  at async renderToString (file://./.output/server/chunks/app/render.mjs:258:19)
  at async renderMiddleware (file://./.output/server/chunks/app/render.mjs:575:20)
  at async handle (file://./.output/server/node_modules/h3/dist/index.mjs:601:19)
```

**Comment by huuhait** [comment]
sloved use .global.ts file to create global middleware

for example:
example.global.ts
