### ISSUE TITLE
`randomFillSync` is not exported by `unenv` when building for Cloudflare

### ISSUE THREAD

**Issue by SebJansen** [nuxt/framework#3001]
### Environment

Nuxt CLI v3.0.0-27385496.7a1cf62
RootDir: /home/seb/Code/neo
Nuxt project info: 

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.7.0`
- Nuxt Version:     `3.0.0-27385496.7a1cf62`
- Package Manager:  `npm@7.20.3`
- Bundler:          `Vite`
- User Config:      `buildModules`, `publicRuntimeConfig`, `privateRuntimeConfig`, `unocss`
- Runtime Modules:  `-`
- Build Modules:    `@unocss/nuxt@0.18.1`
------------------------------

### Reproduction

Have an API route make use of `jose.importJWK` and `jose.jwtVerify`, try to build for Cloudflare.

This problem does not appear when targeting Netlify, or Vercel, for example.

### Describe the bug

Cannot use `randomFillSync` when building and targetting for Cloudflare, not exported to mock environment.

### Additional context

I can provide a clean minimal project wherein the problem can be reproduced and inspected by somebody else, if that would be helpful.

I apologize for not understanding Next's internals, but from the logs it gives me the impression that there's an interaction between Nuxt and Unenv. The 'mock' Cloudflare environment used when building, assumes that `randomFillSync` is not supported (in the real production Workers environment).

Is there a mistake on my side, because `panva/jose` docs clearly state that the library is Cloudflare Workers-compatible, and it makes use of `randomFillSync`, which would imply that the jose-maintainers are of the conviction that Cloudflare Workers supports `randomFillSync`. I couldn't find clear confirmation of this in Cloudflare's docs, but I suspect it is supported, which would mean that the 'mock Cloudflare proxy' is missing an export even though it should be exported.

### Logs

```shell
`ERROR  Rollup error: 'randomFillSync' is not exported by node_modules/unenv/runtime/mock/proxy.mjs, imported by node_modules/jose/dist/node/esm/runtime/random.js`

`ERROR  'randomFillSync' is not exported by node_modules/unenv/runtime/mock/proxy.mjs, imported by node_modules/jose/dist/node/esm/runtime/random.js`


  at error (node_modules/rollup/dist/es/shared/rollup.js:10373:30)
  at Module.error (node_modules/rollup/dist/es/shared/rollup.js:12297:16)
  at Module.getVariableForExportName (node_modules/rollup/dist/es/shared/rollup.js:12462:29)
  at Module.traceVariable (node_modules/rollup/dist/es/shared/rollup.js:12663:47)
  at ModuleScope.findVariable (node_modules/rollup/dist/es/shared/rollup.js:11469:39)
  at ReturnValueScope.findVariable (node_modules/rollup/dist/es/shared/rollup.js:6454:38)
  at Identifier.bind (node_modules/rollup/dist/es/shared/rollup.js:5969:40)
  at CallExpression.bind (node_modules/rollup/dist/es/shared/rollup.js:4577:23)
  at CallExpression.bind (node_modules/rollup/dist/es/shared/rollup.js:8926:15)
  at ArrowFunctionExpression.bind (node_modules/rollup/dist/es/shared/rollup.js:4577:23)
```
```

**Comment by SebJansen** [comment]
oops, I just learned that `randomFillSync` is not supported on Workers, which means I may need to investigate further at `panva/jose`
