### ISSUE TITLE
Nuxt Bridge in lerna monorepo doesn't recognise @nuxt/bridge

### ISSUE THREAD

**Issue by rr235** [nuxt/framework#3003]
### Environment

```
Nuxt CLI v3.0.0-27389502.88da719
RootDir: /Users/rr235/Code/lerna-nuxt-3-tryout
Nuxt project info: 

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.18.0`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `yarn@1.22.15`
- Bundler:          `Webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt.js/issues/new

👉 Suggest an improvement: https://github.com/nuxt/nuxt.js/discussions/new

👉 Read documentation: https://nuxtjs.org
```

### Reproduction

clone repo [lerna-nuxt3-tryout](https://github.com/rr235/lerna-nuxt3-tryout)
- `yarn install`
- `yarn dev`

### Describe the bug

`app-1` created using `yarn create nuxt-app app-1` inside `packages` runs fine as expected before bridge upgrade.
After following steps in [Bridge Migration Guide](https://v3.nuxtjs.org/getting-started/bridge), I get the following error

```
Nuxt CLI v3.0.0-27389502.88da719                                                                                                         08:38:26
                                                                                                                                         08:38:26
  > Local:    http://localhost:3000/ 
  > Network:  http://192.168.178.63:3000/
  > Network:  http://10.114.0.6:3000/


 ERROR  Cannot start nuxt:  Cannot find module '@nuxt/bridge'                                                                            08:38:28
Require stack:
- /Users/rr235/Code/lerna-nuxt-3-tryout/packages/app-1/nuxt.config.js

  Require stack:
  - nuxt.config.js
  at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
  at Function.resolve (internal/modules/cjs/helpers.js:99:19)
  at _resolve (/Users/rr235/Code/lerna-nuxt-3-tryout/node_modules/jiti/dist/jiti.js:1:192625)
  at jiti (/Users/rr235/Code/lerna-nuxt-3-tryout/node_modules/jiti/dist/jiti.js:1:194612)
  at nuxt.config.js:1:177
  at jiti (/Users/rr235/Code/lerna-nuxt-3-tryout/node_modules/jiti/dist/jiti.js:1:196093)
  at Object.loadNuxtConfig (/Users/rr235/Code/lerna-nuxt-3-tryout/node_modules/@nuxt/config-edge/dist/config.js:816:15)
  at loadNuxt (/Users/rr235/Code/lerna-nuxt-3-tryout/node_modules/@nuxt/core-edge/dist/core.js:387:35)
  at loadNuxt (/Users/rr235/Code/lerna-nuxt-3-tryout/node_modules/@nuxt/kit/dist/index.mjs:650:22)
  at async load (/Users/rr235/Code/lerna-nuxt-3-tryout/node_modules/nuxi/dist/chunks/dev.mjs:6729:25)
  at async Object.invoke (/Users/rr235/Code/lerna-nuxt-3-tryout/node_modules/nuxi/dist/chunks/dev.mjs:6771:5)
  at async _main (/Users/rr235/Code/lerna-nuxt-3-tryout/node_modules/nuxi/dist/chunks/index.mjs:384:7)

```

**Comment by danielroe** [comment]
It's important that you install bridge using an alias as [indicated in the docs](https://v3.nuxtjs.org/getting-started/bridge#install-nuxt-bridge).

```diff
   "dependencies": {
-    "@nuxt/bridge-edge": "^3.0.0-27389502.88da719"
+    "@nuxt/bridge": "npm:@nuxt/bridge-edge@^3.0.0-27389502.88da719"
   }
```
