### ISSUE TITLE
pages with `abortNavigation` hang on initial load in SSR

### ISSUE THREAD

**Issue by danielroe** [nuxt/framework#3186]
### Environment

- Operating System: `Darwin`
- Node Version:     `v14.18.3`
- Nuxt Version:     `3.0.0`
- Package Manager:  `yarn@3.1.1`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/nuxt-starter-pqvm9x?file=middleware%2Fsecret.ts

Visit `/secret`

### Describe the bug

An initial load of `/secret` results in a hanging page.

**Comment by oysandvik94** [comment]
I dont know if this is the same, but "abortNavigation()" just straight up crashes the server on initial load. For example, if I have some middleware that triggers "abortNavigation()" when I navigate inside the page it will just abort and throw an error in the console. If the "abortNavigation()" triggers on pageload then it just straight up crashes with:

> Error: test
    at abortNavigation (file:///frontend/.output/server/chunks/app/server.mjs:3428:40)
    at file:///frontend/.output/server/chunks/app/server.mjs:8279:10
    at callWithNuxt (file:///frontend/.output/server/chunks/app/server.mjs:341:21)
    at file:///frontend/.output/server/chunks/app/server.mjs:8332:28
    at file:///frontend/.output/server/chunks/app/server.mjs:1436:33
    at new Promise (<anonymous>)
    at file:///frontend/.output/server/chunks/app/server.mjs:1416:18
    at file:///frontend/.output/server/chunks/app/server.mjs:1997:65
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.

Maybe I'm misusing this, but if I'm not then I'd say this is pretty serious issue?

**Comment by danielroe** [comment]
@oysandvik94 Yes please ❤️
