### ISSUE TITLE
firebase v9 not work in dev mode (No Firebase App '[DEFAULT]')

### ISSUE THREAD

**Issue by niklv** [nuxt/framework#3287]
### Environment

Nuxt CLI v3.0.0-27415326.3c563fa
RootDir: /Users/niklvov/Projects/fj_web_boilerplate
Nuxt project info:

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-27415326.3c563fa`
- Package Manager:  `npm@8.3.1`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

I want to create a firebase plugin that provides auth module

`npm i firebase`

```typescript
// nuxt.config.ts
import { defineNuxtConfig } from 'nuxt3'

export default defineNuxtConfig({})


// plugins/firebase.ts
import { initializeApp } from 'firebase/app'
import { getAuth } from 'firebase/auth'

export default defineNuxtPlugin(() => {
  // if you have a firebase project you can pass your credentials, for minimal reproduction see notes below
  initializeApp({ }) 
  return {
    provide: {
      auth: getAuth()
    }
  }
})
```

Then i run `npx nuxi dev`, and open `http://localhost:3000`.
In server console I get this error:

```
Nuxt CLI v3.0.0-27415326.3c563fa

> Local:    http://localhost:3000/
> Network:  http://192.168.1.121:3000/

ℹ Vite warmed up in 838ms
ℹ Vite warmed up in 2272ms
✔ Vite server built in 5550ms
✔ Nitro built in 780 ms

Firebase: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp() (app/no-app).
  at getApp (file://./node_modules/@firebase/app/dist/esm/index.esm2017.js:459:29)
  at Module.getAuth (file://./node_modules/@firebase/auth/dist/node-esm/index-2bbaab7c.js:5980:24)
  at file://./.nuxt/dist/server/server.mjs:2170:35
  at callWithNuxt (file://./.nuxt/dist/server/server.mjs:262:20)
  at applyPlugin (file://./.nuxt/dist/server/server.mjs:213:29)
  at Module.applyPlugins (file://./.nuxt/dist/server/server.mjs:223:11)
  at async createNuxtAppServer (file://./.nuxt/dist/server/server.mjs:51:5)
  at async renderToString (file://./node_modules/vue-bundle-renderer/dist/index.mjs:247:19)
  at async renderMiddleware (file://./.nuxt/nitro/index.mjs:206:20)
  at async handle (file://./node_modules/h3/dist/index.mjs:601:19)
```
Even if i pass corrent config into `initializeApp` if fails to with same error.

But if I run `npx nuxi build && npx nuxi preview` and open `http://localhost:3000`.
In server console I get different error:
```
Nuxt CLI v3.0.0-27415326.3c563fa

ℹ Node.js version: 16.14.0
ℹ Preset: server
ℹ Working dir: .output
ℹ Starting preview command: node ./server/index.mjs
Listening on http://localhost:3000/

Firebase: Error (auth/invalid-api-key).
  at createErrorInternal (file://./server/node_modules/@firebase/auth/dist/node-esm/index-2bbaab7c.js:466:40)  
  at _assert (file://./server/node_modules/@firebase/auth/dist/node-esm/index-2bbaab7c.js:470:15)  
  at file://./server/node_modules/@firebase/auth/dist/node-esm/index-2bbaab7c.js:5919:13  
  at Component.instanceFactory (file://./server/node_modules/@firebase/auth/dist/node-esm/index-2bbaab7c.js:5936:11)  
  at Provider.getOrInitializeService (file://./server/node_modules/@firebase/component/dist/esm/index.esm2017.js:290:39)  
  at Provider.initialize (file://./server/node_modules/@firebase/component/dist/esm/index.esm2017.js:234:31)  
  at initializeAuth (file://./server/node_modules/@firebase/auth/dist/node-esm/index-2bbaab7c.js:584:27)  
  at getAuth (file://./server/node_modules/@firebase/auth/dist/node-esm/index-2bbaab7c.js:5985:12)  
  at file://./server/chunks/app/server.mjs:3254:13  
  at callWithNuxt (file://./server/chunks/app/server.mjs:335:20)
```

Error is different.
And if i pass correct config into `initializeApp` it did not fails at all. 
This marks that production build code is working properly and dev code not.

### Describe the bug

Nuxt3 fails in dev mode with firebase-js-sdk module.
Production build is works as expected.

**Comment by Diizzayy** [comment]
@niklv This issue you're having occurs because your plugins attempts to initialize firebase in server side, where as it should only occur in browser.

Your firebase plugin needs to be changed to a client-only plugin.

`nuxt.config.ts`
```js
import { defineNuxtConfig } from "nuxt3";

export default defineNuxtConfig({
  publicRuntimeConfig: {
    firebaseConfig: {},
  },
});
```

`plugins/firebase.client.ts`: this is a working code snippet from my personal project
```js
import { getApps, initializeApp } from "firebase/app";
import { getAuth, setPersistence, inMemoryPersistence } from "firebase/auth";

export default defineNuxtPlugin(() => {
  try {
    if (getApps().length === 0) {
      const { firebaseConfig } = useRuntimeConfig();
      if (firebaseConfig) initializeApp(firebaseConfig);
    }

    const auth = getAuth();
    if (auth) setPersistence(auth, inMemoryPersistence);
  } catch (e) {
    console.error(e);
  }
});
```

also, with firebase v9. I think it's very pointless to provide / inject anything from firebase

**Comment by niklv** [comment]
@Diizzayy I what to use firebase-js-sdk in ssr to. So i what to initialize in server and client plugin.
Answer no covered issue that is initialize ok in production build and no initialized in development build.
@danielroe please reopen

**Comment by danielroe** [comment]
I'll convert this to a discussion 👍
