### ISSUE TITLE
Cannot read properties of undefined (reading 'getSSRProps')

### ISSUE THREAD

**Issue by ilouHD** [nuxt/framework#3324]
### Environment

Nuxt CLI v3.0.0-27419629.87eb7d0
RootDir: D:\develop\nuxt3-app
Nuxt project info:

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.11.1`
- Nuxt Version:     `3.0.0-27419629.87eb7d0`
- Package Manager:  `npm@8.0.0`
- Bundler:          `Vite`
- User Config:      `css`, `nitro`, `vue`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

I have the following repo/branch: https://github.com/ilouHD/nuxt3-booking-system/tree/test/nuxt
1. Clone it using `git clone --branch test/nuxt https://github.com/ilouHD/nuxt3-booking-system/`
2. Install the dependencies using `npm install`
3. Rename `config.example.json` to `config.json`
4. Start it using `npm run dev -- -o` or `npm run restart` (but I would prefer starting the dev-server)

### Describe the bug

After starting the software (as stated in "Reproduction") you may try to access the software using "localhost:3000". It will throw an error 500 saying
```
Failed to resolve directive: clickaway
Cannot read properties of undefined (reading 'getSSRProps')
```
This error is thrown by a client-side-only directive I added in `plugins/clickaway.client.ts`. Using the vue/compilerOptions in `nuxt.config.ts` I set the directive to require a runtime. I use it in the `components/DatePicker.vue`.

If accessing the page through "http://localhost:3000/settings" and then navigating back to the page "Kalender" using the navigation bar at the top, the directive also works as expected.

### Additional context

Due to exams in the university, I didn't manage to work on the project, but after upgrading it to the newest version of nuxt the problem occurs. I'm pretty sure the error wasn't there before the upgrade.

### Logs

```shell
[Vue warn]: Failed to resolve directive: clickaway
Cannot read properties of undefined (reading 'getSSRProps')
  at Module.ssrGetDirectiveProps (D:\develop\nuxt3-app\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:967:42)
  at _sfc_ssrRender (file:///D:/develop/nuxt3-app/.nuxt/dist/server/server.mjs:2694:141)
  at renderComponentSubTree (D:\develop\nuxt3-app\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:269:13)
  at renderComponentVNode (D:\develop\nuxt3-app\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:214:16)
  at Module.ssrRenderComponent (D:\develop\nuxt3-app\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:629:12)
  at _sfc_ssrRender (file:///D:/develop/nuxt3-app/.nuxt/dist/server/server.mjs:2487:31)
  at renderComponentSubTree (D:\develop\nuxt3-app\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:269:13)
  at D:\develop\nuxt3-app\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:211:29
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by ilouHD** [comment]
After reading the docs and a lot of testing I found out I just had to rename my plugin file from `clickaway.client.ts` to `clickaway.ts`.
