### ISSUE TITLE
Auto compiler fails with error when changing route from nuxt2 to nuxt3 syntax

### ISSUE THREAD

**Issue by TomMiller-mas** [nuxt/framework#3350]
### Environment

Nuxt CLI v3.0.0-27424151.dbab979                                                                              23:32:13
RootDir: C:\devSandbox-Tom\DevFork-Tom\MAS-Auth\mas-auth-web                                                  23:32:15
Nuxt project info:                                                                                            23:32:15

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-27424151.dbab979`
- Package Manager:  `npm@8.5.1`
- Bundler:          `Vite`
- User Config:      `typescript`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

route:  
   pages/user/_id/index.vue

change route to:
  pages/user/[id]/index.vue

### Describe the bug

auto recompile fails with the following bug

The number of foldable regions is limited to a maximum of 5000. Increase configuration option ['Folding Maximum Regions'](command:workbench.action.openSettings?["editor.foldingMaximumRegions"]) to enable more.

### Additional context

If I ctrl+c to stop the server/session and do a full build (npm run build) and then restart the server (npm run dev), everything works fine. I get a similar error when changing it at a file level.

pages/users/_id.vue to pages/users/[id].vue

Once again, if I ctrl+c out and build and then go back and run the server, it works as expected.

### Logs

```shell
from console:

                                                                                                                                23:26:40

 ERROR  11:26:40 PM [vite] Internal server error: Failed to resolve import "C:/devSandbox-Tom/DevFork-Tom/MAS-Auth/mas-auth-web/pages/customer/_id/index.vue?macro=true" from "virtual:C:\devSandbox-Tom\DevFork-Tom\MAS-Auth\mas-auth-web\.nuxt\routes.mjs". Does the file exist?
  Plugin: vite:import-analysis
  File: virtual:C:/devSandbox-Tom/DevFork-Tom/MAS-Auth/mas-auth-web/.nuxt/routes.mjs
  1  |  import { meta as CDevSandboxTomDevForkTomMASAuthMasAuthWebPagesCustomerIdIndexVueMeta } from "C:/devSandbox-Tom/DevFork-Tom/MAS-Auth/mas-auth-web/pages/customer/_id/index.vue?macro=true";
     |                                                                                                ^
  2  |  import { meta as CDevSandboxTomDevForkTomMASAuthMasAuthWebPagesCustomerIndexVueMeta } from "C:/devSandbox-Tom/DevFork-Tom/MAS-Auth/mas-auth-web/pages/customer/index.vue?macro=true";
  3  |  import { meta as CDevSandboxTomDevForkTomMASAuthMasAuthWebPagesIndexVueMeta } from "C:/devSandbox-Tom/DevFork-Tom/MAS-Auth/mas-auth-web/pages/index.vue?macro=true";
      at formatError (C:\devSandbox-Tom\DevFork-Tom\MAS-Auth\mas-auth-web\node_modules\vite\dist\node\chunks\dep-971d9e33.js:38082:46)
      at TransformContext.error (C:\devSandbox-Tom\DevFork-Tom\MAS-Auth\mas-auth-web\node_modules\vite\dist\node\chunks\dep-971d9e33.js:38078:19)
      at normalizeUrl (C:\devSandbox-Tom\DevFork-Tom\MAS-Auth\mas-auth-web\node_modules\vite\dist\node\chunks\dep-971d9e33.js:69803:26)
      at async TransformContext.transform (C:\devSandbox-Tom\DevFork-Tom\MAS-Auth\mas-auth-web\node_modules\vite\dist\node\chunks\dep-971d9e33.js:69943:57)
      at async Object.transform (C:\devSandbox-Tom\DevFork-Tom\MAS-Auth\mas-auth-web\node_modules\vite\dist\node\chunks\dep-971d9e33.js:38318:30)
      at async doTransform (C:\devSandbox-Tom\DevFork-Tom\MAS-Auth\mas-auth-web\node_modules\vite\dist\node\chunks\dep-971d9e33.js:53014:29)


 ERROR  11:26:41 PM [vite] Internal server error: Failed to resolve import "C:/devSandbox-Tom/DevFork-Tom/MAS-Auth/mas-auth-web/pages/customer/_id/index.vue?macro=true" from "virtual:C:\devSandbox-Tom\DevFork-Tom\MAS-Auth\mas-auth-web\.nuxt\routes.mjs". Does the file exist?
  Plugin: vite:import-analysis
  File: virtual:C:/devSandbox-Tom/DevFork-Tom/MAS-Auth/mas-auth-web/.nuxt/routes.mjs
  1  |  import { meta as CDevSandboxTomDevForkTomMASAuthMasAuthWebPagesCustomerIdIndexVueMeta } from "C:/devSandbox-Tom/DevFork-Tom/MAS-Auth/mas-auth-web/pages/customer/_id/index.vue?macro=true";
     |                                                                                                ^
  2  |  import { meta as CDevSandboxTomDevForkTomMASAuthMasAuthWebPagesCustomerIndexVueMeta } from "C:/devSandbox-Tom/DevFork-Tom/MAS-Auth/mas-auth-web/pages/customer/index.vue?macro=true";
  3  |  import { meta as CDevSandboxTomDevForkTomMASAuthMasAuthWebPagesIndexVueMeta } from "C:/devSandbox-Tom/DevFork-Tom/MAS-Auth/mas-auth-web/pages/index.vue?macro=true";
      at formatError (C:\devSandbox-Tom\DevFork-Tom\MAS-Auth\mas-auth-web\node_modules\vite\dist\node\chunks\dep-971d9e33.js:38082:46)
      at TransformContext.error (C:\devSandbox-Tom\DevFork-Tom\MAS-Auth\mas-auth-web\node_modules\vite\dist\node\chunks\dep-971d9e33.js:38078:19)
      at normalizeUrl (C:\devSandbox-Tom\DevFork-Tom\MAS-Auth\mas-auth-web\node_modules\vite\dist\node\chunks\dep-971d9e33.js:69803:26)
      at async TransformContext.transform (C:\devSandbox-Tom\DevFork-Tom\MAS-Auth\mas-auth-web\node_modules\vite\dist\node\chunks\dep-971d9e33.js:69943:57)
      at async Object.transform (C:\devSandbox-Tom\DevFork-Tom\MAS-Auth\mas-auth-web\node_modules\vite\dist\node\chunks\dep-971d9e33.js:38318:30)
      at async doTransform (C:\devSandbox-Tom\DevFork-Tom\MAS-Auth\mas-auth-web\node_modules\vite\dist\node\chunks\dep-971d9e33.js:53014:29)

Cannot read properties of undefined (reading 'forEach')
  at createRouterMatcher (C:\devSandbox-Tom\DevFork-Tom\MAS-Auth\mas-auth-web\node_modules\vue-router\dist\vue-router.cjs.js:1468:12)
  at Module.createRouter (C:\devSandbox-Tom\DevFork-Tom\MAS-Auth\mas-auth-web\node_modules\vue-router\dist\vue-router.cjs.js:2795:21)
  at file:///C:/devSandbox-Tom/DevFork-Tom/MAS-Auth/mas-auth-web/.nuxt/dist/server/server.mjs:1849:40
  at callWithNuxt (file:///C:/devSandbox-Tom/DevFork-Tom/MAS-Auth/mas-auth-web/.nuxt/dist/server/server.mjs:263:20)
  at applyPlugin (file:///C:/devSandbox-Tom/DevFork-Tom/MAS-Auth/mas-auth-web/.nuxt/dist/server/server.mjs:214:29)
  at Module.applyPlugins (file:///C:/devSandbox-Tom/DevFork-Tom/MAS-Auth/mas-auth-web/.nuxt/dist/server/server.mjs:224:11)
  at async createNuxtAppServer (file:///C:/devSandbox-Tom/DevFork-Tom/MAS-Auth/mas-auth-web/.nuxt/dist/server/server.mjs:51:5)
  at async renderToString (file:///C:/devSandbox-Tom/DevFork-Tom/MAS-Auth/mas-auth-web/node_modules/vue-bundle-renderer/dist/index.mjs:247:19)
  at async renderMiddleware (file:///C:/devSandbox-Tom/DevFork-Tom/MAS-Auth/mas-auth-web/.nuxt/nitro/index.mjs:206:20)
  at async handle (file:///C:/devSandbox-Tom/DevFork-Tom/MAS-Auth/mas-auth-web/node_modules/h3/dist/index.mjs:601:19)
Cannot read properties of undefined (reading 'forEach')
  at createRouterMatcher (C:\devSandbox-Tom\DevFork-Tom\MAS-Auth\mas-auth-web\node_modules\vue-router\dist\vue-router.cjs.js:1468:12)
  at Module.createRouter (C:\devSandbox-Tom\DevFork-Tom\MAS-Auth\mas-auth-web\node_modules\vue-router\dist\vue-router.cjs.js:2795:21)
  at file:///C:/devSandbox-Tom/DevFork-Tom/MAS-Auth/mas-auth-web/.nuxt/dist/server/server.mjs:1849:40
  at callWithNuxt (file:///C:/devSandbox-Tom/DevFork-Tom/MAS-Auth/mas-auth-web/.nuxt/dist/server/server.mjs:263:20)
  at applyPlugin (file:///C:/devSandbox-Tom/DevFork-Tom/MAS-Auth/mas-auth-web/.nuxt/dist/server/server.mjs:214:29)
  at Module.applyPlugins (file:///C:/devSandbox-Tom/DevFork-Tom/MAS-Auth/mas-auth-web/.nuxt/dist/server/server.mjs:224:11)
  at async createNuxtAppServer (file:///C:/devSandbox-Tom/DevFork-Tom/MAS-Auth/mas-auth-web/.nuxt/dist/server/server.mjs:51:5)
  at async renderToString (file:///C:/devSandbox-Tom/DevFork-Tom/MAS-Auth/mas-auth-web/node_modules/vue-bundle-renderer/dist/index.mjs:247:19)
  at async renderMiddleware (file:///C:/devSandbox-Tom/DevFork-Tom/MAS-Auth/mas-auth-web/.nuxt/nitro/index.mjs:206:20)
  at async handle (file:///C:/devSandbox-Tom/DevFork-Tom/MAS-Auth/mas-auth-web/node_modules/h3/dist/index.mjs:601:19)

 WARN  [SSR] Error transforming virtual:C:/devSandbox-Tom/DevFork-Tom/MAS-Auth/mas-auth-web/.nuxt/routes.mjs: Failed to resolve import "C:/devSandbox-Tom/DevFork-Tom/MAS-Auth/mas-auth-web/pages/customer/_id/index.vue?macro=true" from "virtual:C:\devSandbox-Tom\DevFork-Tom\MAS-Auth\mas-auth-web\.nuxt\routes.mjs". Does the file exist?
  at formatError (node_modules\vite\dist\node\chunks\dep-971d9e33.js:38082:46)
  at TransformContext.error (node_modules\vite\dist\node\chunks\dep-971d9e33.js:38078:19)
  at normalizeUrl (node_modules\vite\dist\node\chunks\dep-971d9e33.js:69803:26)
  at async TransformContext.transform (node_modules\vite\dist\node\chunks\dep-971d9e33.js:69943:57)
  at async Object.transform (node_modules\vite\dist\node\chunks\dep-971d9e33.js:38318:30)
  at async doTransform (node_modules\vite\dist\node\chunks\dep-971d9e33.js:53014:29)
```

**Comment by danielroe** [comment]
I believe this should now be resolved with the latest version of `vite`, if you run `npx nuxi upgrade`. Let me know if not and I'll reopen.

**Comment by TomMiller-mas** [comment]
I have tested both use cases and it is fixed.
