### ISSUE TITLE
Nuxi Build Error Within NPM Workspaces (Chart.js)

### ISSUE THREAD

**Issue by Lozoute** [nuxt/framework#3443]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v17.1.0`
- Nuxt Version:     `3.0.0-27434419.754ff0c`
- Package Manager:  `npm@8.5.2`
- Bundler:          `Vite`
- User Config:      `srcDir`, `buildModules`, `build`, `vite`, `publicRuntimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.1.8`

### Reproduction

- Clone https://github.com/Lozoute/Nuxt3-ChartJS
- npm install
- Go to packages/client and nuxi build

### Describe the bug

Hello, I am using `chart.js` via `vue-chart-3` in my Nuxt3 project.

It works fine when I am in dev mode `nuxi dev` but when I try to build with `nuxi build` I have the error above.

It looks like it's searching for the file in the wrong place but it will bug only if you are in a npm workspace, in a more simple repo it works fine...

### Logs

```shell
nuxi build

Nuxt CLI v3.0.0-27434419.754ff0c
vite v2.8.5 building for production...
transforming...
18:30:06 [vite] new dependencies found: vue, pinia/dist/pinia.mjs, chart.js, updating...
i Vite warmed up in 4456ms
18:30:10 [vite] ✨ dependencies updated, reloading page...
✓ 1029 modules transformed.
rendering chunks...
../.nuxt/dist/client/logo.68eba098.svg      2.68 KiB
../.nuxt/dist/client/manifest.json          2.22 KiB
../.nuxt/dist/client/index-7ec8442c.mjs     0.18 KiB / gzip: 0.17 KiB
../.nuxt/dist/client/index-71d22a04.mjs     0.19 KiB / gzip: 0.17 KiB
../.nuxt/dist/client/index-6f46002b.mjs     7.64 KiB / gzip: 2.16 KiB
../.nuxt/dist/client/index-dd96ca73.mjs     0.18 KiB / gzip: 0.17 KiB
../.nuxt/dist/client/index-6d116a94.mjs     0.18 KiB / gzip: 0.17 KiB
../.nuxt/dist/client/index-7bf35269.mjs     1.78 KiB / gzip: 0.96 KiB
../.nuxt/dist/client/signin-d7e392ef.mjs    0.27 KiB / gzip: 0.22 KiB
../.nuxt/dist/client/entry.e073093e.css     17.56 KiB / gzip: 4.25 KiB
../.nuxt/dist/client/default-811517e5.mjs   69.67 KiB / gzip: 18.06 KiB
../.nuxt/dist/client/entry-570198c5.mjs     328.68 KiB / gzip: 117.41 KiB
i Client built in 9312ms
i Building server...
vite v2.8.5 building SSR bundle for production...
transforming...
✓ 94 modules transformed.
rendering chunks...
../.nuxt/dist/server/server.mjs   176.85 KiB
√ Server built in 567ms
i Nitro preset is server
i Cleaning up .output
start Generating public...
√ Generated public .output/public
start Building server...

 ERROR  Rollup error: File D:\Projects\Clients\ToteemCO\Toteem\packages\client\chart.js does not exist.


 ERROR  File D:\Projects\Clients\ToteemCO\Toteem\packages\client\chart.js does not exist.

  at Job.emitDependency (D:\Projects\Clients\ToteemCO\Toteem\node_modules\@vercel\nft\out\node-file-trace.js:280:23)
  at async Promise.all (index 29)
  at async nodeFileTrace (D:\Projects\Clients\ToteemCO\Toteem\node_modules\@vercel\nft\out\node-file-trace.js:32:5)
  at async Object.buildEnd (/D:/Projects/Clients/ToteemCO/Toteem/node_modules/@nuxt/nitro/dist/index.mjs:292:29)
  at async Promise.all (index 0)
  at async rollupInternal (/D:/Projects/Clients/ToteemCO/Toteem/node_modules/rollup/dist/es/shared/rollup.js:23519:5)
  at async _build (/D:/Projects/Clients/ToteemCO/Toteem/node_modules/@nuxt/nitro/dist/index.mjs:1089:18)
  at async /D:/Projects/Clients/ToteemCO/Toteem/node_modules/nuxt3/dist/chunks/nitro-legacy.mjs:64:7
  at async build (/D:/Projects/Clients/ToteemCO/Toteem/node_modules/nuxt3/dist/chunks/index.mjs:1343:5)
  at async Object.invoke (/D:/Projects/Clients/ToteemCO/Toteem/node_modules/nuxi/dist/chunks/build.mjs:33:5)

npm ERR! Lifecycle script `build` failed with error:
```

**Comment by BeeeQueue** [comment]
Can confirm this issue, seems to be importing packages with `.js` suffixes breaks resolving when building for production.

Trying to import `chart.js` using Nuxt `v3.0.0-27467464.a0c4d6e`
