### ISSUE TITLE
Issue with using `<script lang="tsx">` in `~/pages`

### ISSUE THREAD

**Issue by danielroe** [nuxt/framework#3488]
```
WARN  [SSR] Error transforming /pages/tkvs/index.vue?vue&type=script&lang.tsx&macro=true: Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.

  at formatError (node_modules/.pnpm/vite@2.8.5_sass@1.49.9/node_modules/vite/dist/node/chunks/dep-ff3ab196.js:38098:46)
  at TransformContext.error (node_modules/.pnpm/vite@2.8.5_sass@1.49.9/node_modules/vite/dist/node/chunks/dep-ff3ab196.js:38094:19)
  at TransformContext.transform (node_modules/.pnpm/vite@2.8.5_sass@1.49.9/node_modules/vite/dist/node/chunks/dep-ff3ab196.js:69779:22)
  at async Object.transform (node_modules/.pnpm/vite@2.8.5_sass@1.49.9/node_modules/vite/dist/node/chunks/dep-ff3ab196.js:38334:30)
  at async doTransform (node_modules/.pnpm/vite@2.8.5_sass@1.49.9/node_modules/vite/dist/node/chunks/dep-ff3ab196.js:53030:29)
```

_Originally posted by @xiao-e-yun in https://github.com/nuxt/framework/issues/3477#issuecomment-1057283192_

**Comment by bittermeatball** [comment]
@danielroe i meet this issue if i use `.tsx` file or use `<script lang="tsx">` for page component
![image](https://user-images.githubusercontent.com/46400321/167452793-d2c11325-b860-4913-8bf2-d99497906fa4.png)

I tried to create a reproduction on stackblitz but see the exact same bug as you mentioned above instead lol
https://stackblitz.com/edit/nuxt-starter-akprnd?file=pages/index.vue

**My current workaround is to have my `.tsx` components separated and import them into the `.vue` page component**

**Comment by alxpereira** [comment]
+1

**Comment by baiwusanyu-c** [comment]
![image](https://user-images.githubusercontent.com/32354856/169729049-b9f4fd77-102a-4836-84d3-109751e1519b.png)
+1
