### ISSUE TITLE
Maximum call stack size exceeded for Button component

### ISSUE THREAD

**Issue by joshwcorbett** [nuxt/framework#3506]
### Environment

Nuxt CLI v3.0.0-27424151.dbab979
RootDir: /Users/josh/Repositories/fnf-next
Nuxt project info:

------------------------------
- Operating System: `Darwin`
- Node Version:     `v17.5.0`
- Nuxt Version:     `3.0.0-27424151.dbab979`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `ssr`, `css`, `components`, `publicRuntimeConfig`, `buildModules`, `modules`, `build`
- Runtime Modules:  `@storyblok/nuxt@3.0.0-beta.3`
- Build Modules:    `@pinia/nuxt@0.1.8`, `@vueuse/nuxt@7.6.2`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-op7gqa?devtoolsheight=33&file=app.vue

### Describe the bug

Creating a Button named `Button` living inside a Button folder within components and using that button results in an "Error 500: Maximum Stack Size Exceeded".

Naming the component `Btn` instead of `Button` across file and parent folder fixes the issue.

### Logs

```shell
~/projects/github-op7gqa 1m 28s
Nuxt CLI v3.0.0-27265876.3cd4494                                            13:35:09
                                                                            13:35:10
  > Local:    http://localhost:3000/ 
  > Network:  http://192.168.1.104:3000/

ℹ Vite warmed up in 127ms                                                   13:35:11
✔ Vite server built in 844ms                                                13:35:12
✔ Nitro built in 525 ms                                                     13:35:13
Maximum call stack size exceeded
  at finishComponentSetup (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6355:9)  
  at handleSetupResult (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6300:5)  
  at setupStatefulComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6263:13)  
  at setupComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6197:11)  
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:198:17)  
  at Module.renderVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:304:22)  
  at _sfc_ssrRender (file://./.nuxt/dist/server/server.mjs:1621:25)  
  at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:263:13)  
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:214:16)  
  at renderVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:304:22)
(node:38) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
    at String.match (<anonymous>)
    at getType (/home/projects/github-op7gqa/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:2704:43)
    at assertType (/home/projects/github-op7gqa/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:2773:26)
    at validateProp (/home/projects/github-op7gqa/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:2753:45)
    at validateProps (/home/projects/github-op7gqa/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:2729:9)
    at initProps (/home/projects/github-op7gqa/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:2435:9)
    at setupComponent (/home/projects/github-op7gqa/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6194:5)
    at renderComponentVNode (/home/projects/github-op7gqa/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:198:17)
    at renderVNode (/home/projects/github-op7gqa/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:304:22)
    at renderComponentSubTree (/home/projects/github-op7gqa/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:269:13)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:38) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:38) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:38) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
    at setupStatefulComponent (/home/projects/github-op7gqa/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6240:20)
    at setupComponent (/home/projects/github-op7gqa/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6197:11)
    at renderComponentVNode (/home/projects/github-op7gqa/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:198:17)
    at Module.renderVNode (/home/projects/github-op7gqa/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:304:22)
    at _sfc_ssrRender (file:///home/projects/github-op7gqa/.nuxt/dist/server/server.mjs:1621:25)
    at renderComponentSubTree (/home/projects/github-op7gqa/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:263:13)
    at renderComponentVNode (/home/projects/github-op7gqa/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:214:16)
    at renderVNode (/home/projects/github-op7gqa/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:304:22)
    at renderComponentSubTree (/home/projects/github-op7gqa/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:269:13)
    at renderComponentVNode (/home/projects/github-op7gqa/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:214:16)
(node:38) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

**Comment by jiblett1000** [comment]
I did some futzing around with the stackblitz @joshwcorbett had posted on discord and deduced that there isn't an error with the way the components were set up but his issue related to his use of `:is` and `:as`. I believe this can be closed. However, maybe @joshwcorbett would like to open another issue for the other use case?

**Comment by danielroe** [comment]
Yes, this isn't a Nuxt error, and arguably is designed behaviour.

Note the same behaviour with vite: https://stackblitz.com/edit/vitejs-vite-mrfhxq?file=src%2Fmain.js&terminal=dev. This is likely because within a component named 'Button' you're using `component is="button"`, and there's an exception for this:

> Registration is not required if you pass the component itself to is rather than its name, e.g. in <script setup>.

**Comment by jiblett1000** [comment]
@danielroe It seemed to me it was because he was passing `button` or `a`  to the `:is` prop. I'm guessing `:is` is reserved for nuxt components rather than html elements and the use of `:as`.
