### ISSUE TITLE
@rollup/plugin-graphql does not work (Unexpected token error)

### ISSUE THREAD

**Issue by jerryjappinen** [nuxt/framework#3589]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-27447229.20f3171`
- Package Manager:  `npm@8.3.1`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Minimal repro: https://github.com/jerryjappinen/nuxt3-gql-test

This repo is a clean Nuxt3 app, with `@rollup/plugin-graphql` installed and added as a plugin. `App.vue` attempts to load the `.gql` file but fails.

To reproduce:

1. Clone the repo
2. Install dependencies with `npm i`
3. `npm run build`

The same happens on dev server with slightly different log output.

### Describe the bug

After installing the plugin and importing a `.gql` file, I get an `Unexpected token (1:6)` error. The content of the (valid) `.gql` file doesn't seem to make a difference, it will always throw this error. (See log output below.)

### Additional context

I have a Nuxt 3 project where `@rollup/plugin-graphql` used to work, but I'm now getting this issue consistently. The plugin has not been updated in 4 months so I think this is an issue with Nuxt 3.

#### `nuxi build`

```shell
nuxt3-gql-test/ npm run build

> build
> nuxi build

Nuxt CLI v3.0.0-27447229.20f3171

 ERROR  [rollup-plugin-dynamic-import-variables] Unexpected token (1:6)
file: /Users/jerryjappinen/Development/nuxt3-gql-test/GetItemsQuery.gql:1:6


 ERROR  Unexpected token (1:6)

  at Parser.pp$4.raise (node_modules/rollup/dist/shared/rollup.js:19636:13)
  at Parser.pp$9.unexpected (node_modules/rollup/dist/shared/rollup.js:16932:8)
  at Parser.pp$9.semicolon (node_modules/rollup/dist/shared/rollup.js:16909:66)
  at Parser.pp$8.parseExpressionStatement (node_modules/rollup/dist/shared/rollup.js:17392:8)
  at Parser.pp$8.parseStatement (node_modules/rollup/dist/shared/rollup.js:17125:24)
  at Parser.pp$8.parseTopLevel (node_modules/rollup/dist/shared/rollup.js:16989:21)
  at Parser.parse (node_modules/rollup/dist/shared/rollup.js:16762:15)
  at Function.parse (node_modules/rollup/dist/shared/rollup.js:16812:35)
  at Graph.contextParse (node_modules/rollup/dist/shared/rollup.js:22958:38)
  at Object.transform (node_modules/vite/dist/node/chunks/dep-9c153816.js:28694:27)


 ERROR  [!] Error: unfinished hook action(s) on exit:

(vite:load-fallback) load "/Users/jerryjappinen/Development/nuxt3-gql-test/node_modules/nuxt3/dist/meta/runtime/composables.mjs"
(vite:load-fallback) load "/Users/jerryjappinen/Development/nuxt3-gql-test/node_modules/ohmyfetch/dist/index.mjs"
(vite:load-fallback) load "/Users/jerryjappinen/Development/nuxt3-gql-test/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js"
(vite:load-fallback) load "/Users/jerryjappinen/Development/nuxt3-gql-test/node_modules/@vueuse/head/dist/index.mjs"
(vite:load-fallback) load "/Users/jerryjappinen/Development/nuxt3-gql-test/node_modules/ufo/dist/index.mjs"
(vite:load-fallback) load "/Users/jerryjappinen/Development/nuxt3-gql-test/node_modules/h3/dist/index.mjs"
(vite:load-fallback) load "/Users/jerryjappinen/Development/nuxt3-gql-test/node_modules/hookable/dist/index.mjs"
(vite:load-fallback) load "/Users/jerryjappinen/Development/nuxt3-gql-test/node_modules/nuxt3/dist/app/compat/legacy-app.mjs"
(vite:load-fallback) load "/Users/jerryjappinen/Development/nuxt3-gql-test/node_modules/nuxt3/dist/app/composables/component.mjs"
(vite:load-fallback) load "/Users/jerryjappinen/Development/nuxt3-gql-test/node_modules/nuxt3/dist/app/composables/asyncData.mjs"
(vite:load-fallback) load "/Users/jerryjappinen/Development/nuxt3-gql-test/node_modules/nuxt3/dist/app/composables/hydrate.mjs"
(vite:load-fallback) load "/Users/jerryjappinen/Development/nuxt3-gql-test/node_modules/nuxt3/dist/app/composables/state.mjs"
(vite:load-fallback) load "/Users/jerryjappinen/Development/nuxt3-gql-test/node_modules/nuxt3/dist/app/composables/fetch.mjs"
(vite:load-fallback) load "/Users/jerryjappinen/Development/nuxt3-gql-test/node_modules/nuxt3/dist/app/composables/cookie.mjs"
(vite:load-fallback) load "/Users/jerryjappinen/Development/nuxt3-gql-test/node_modules/nuxt3/dist/app/composables/ssr.mjs"
(vite:load-fallback) load "/Users/jerryjappinen/Development/nuxt3-gql-test/node_modules/nuxt3/dist/app/composables/router.mjs"
```

#### `nuxi dev`

```sh
ℹ Vite warmed up in 137ms
ℹ Vite warmed up in 272ms

 WARN  [SSR] Error transforming /Users/jerryjappinen/Development/nuxt3-gql-test/GetItemsQuery.gql: Parse failure: Unexpected token (1:6)
Contents of line 1: query GetItemsQuery {

  Contents of line 1: query GetItemsQuery {
  at ssrTransform (node_modules/vite/dist/node/chunks/dep-9c153816.js:52135:15)
  at doTransform (node_modules/vite/dist/node/chunks/dep-9c153816.js:53052:48)

✔ Vite server built in 305ms
✔ Nitro built in 144 ms
```

**Comment by kenta92** [comment]
+1 on Windows
