### ISSUE TITLE
generate error when `build.ssr === false`

### ISSUE THREAD

**Issue by caikan** [nuxt/framework#3689]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.12.0`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `npm@8.1.0`
- Builder:          `webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://codesandbox.io/s/generate-error-3zw7in?file=/nuxt.config.ts

`npm run generate`

### Describe the bug

I just want to `nuxi generate` static pages , but errors will occur if I don't turn on `build.ssr`.

```js
import { defineNuxtConfig } from "@nuxt/bridge";

export default defineNuxtConfig({
  target: 'static',
  ssr: false,
  build: {
    ssr: true,
  },
  bridge: {
    vite: !true,
    meta: true,
  },
  components: true,
})
```

### Logs

```shell
ℹ Production build                                                                                                          03:29:26
ℹ Bundling only for client side                                                                                             03:29:26
ℹ Target: static                                                                                                            03:29:26
ℹ Using components loader to optimize imports                                                                               03:29:26
ℹ Discovered Components: node_modules/.cache/nuxt/components/readme.md                                                      03:29:26
✔ Builder initialized                                                                                                       03:29:26
✔ Nuxt files generated                                                                                                      03:29:26

✔ Client
  Compiled successfully in 15.79s


Hash: d3a3b9fc7d499e7afd9b
Version: webpack 4.46.0
Time: 15789ms
Built at: 03/16/2022 3:29:42 AM
                         Asset       Size  Chunks                         Chunk Names
../server/client.manifest.json   12.5 KiB          [emitted]
                    338ee91.js   2.29 KiB       3  [emitted] [immutable]  runtime
                    6c4b2de.js    219 KiB       1  [emitted] [immutable]  commons/app
                    9a3cfdb.js    122 KiB       4  [emitted] [immutable]  vendors/app
                      LICENSES  472 bytes          [emitted]
                    c050f99.js  126 bytes       0  [emitted] [immutable]  app
                    f07e37a.js  459 bytes       2  [emitted] [immutable]  pages/index
 + 1 hidden asset
Entrypoint app = 338ee91.js 6c4b2de.js 9a3cfdb.js c050f99.js
ℹ Nitro preset is server                                                                                                    03:29:42
ℹ Cleaning up .output                                                                                                       03:29:42
ℹ Generating output directory: public/         
start Building server...                                                                                                    03:29:42

 ERROR  Rollup error: Could not load /sandbox/node_modules/.cache/nuxt/dist/server/server.mjs (imported by node_modules/@nuxt/nitro/dist/runtime/app/render.mjs): ENOENT: no such file or directory, open '/sandbox/node_modules/.cache/nuxt/dist/server/server.mjs'


 FATAL  Could not load /sandbox/node_modules/.cache/nuxt/dist/server/server.mjs (imported by node_modules/@nuxt/nitro/dist/runtime/app/render.mjs): ENOENT: no such file or directory, open '/sandbox/node_modules/.cache/nuxt/dist/server/server.mjs'




   ╭────────────────────────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                                    │
   │   ✖ Nuxt Fatal Error                                                                               │
   │                                                                                                    │
   │   Error: Could not load /sandbox/node_modules/.cache/nuxt/dist/server/server.mjs (imported by      │
   │   node_modules/@nuxt/nitro/dist/runtime/app/render.mjs): ENOENT: no such file or directory, open   │
   │   '/sandbox/node_modules/.cache/nuxt/dist/server/server.mjs'                                       │
   │                                                                                                    │
   ╰────────────────────────────────────────────────────────────────────────────────────────────────────╯


 ERROR  Command failed with exit code 1: npx nuxt generate                                                                  03:29:43

  at makeError (node_modules/nuxi/dist/chunks/index3.mjs:1242:11)
  at handlePromise (node_modules/nuxi/dist/chunks/index3.mjs:2071:26)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async Object.invoke (node_modules/nuxi/dist/chunks/generate.mjs:42:7)
  at async _main (node_modules/nuxi/dist/chunks/index.mjs:384:7)
```

**Comment by danielroe** [comment]
Looks like it might be the same as https://github.com/nuxt/framework/issues/886. Let's track there instead.
