### ISSUE TITLE
Unable to develop module according to docs guide

### ISSUE THREAD

**Issue by kecrily** [nuxt/framework#3760]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v17.7.1`
- Nuxt Version:     `3.0.0-27459267.f69126e`
- Package Manager:  `pnpm@6.32.3`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

1. `pnpm dlx nuxi  -t module my-module`
2. `cd my-module`
3. `pnpm install --shamefully-hoist`
4. `pnpm run dev:prepare`
5. `pnpm run dev`
6. Open website

### Describe the bug

When developing modules according to the documentation guidelines, the site opens and keeps loading, while the console outputs an error message.

### Logs

<details>
<summary>Details</summary>

```shell
> nuxt-module-build --stub && nuxi prepare playground
Nuxt CLI v3.0.0-27459267.f69126e                                                                                  14:07:39
                                                                                                                  14:07:39
  > Local:    http://localhost:3000/ 
  > Network:  http://198.18.0.1:3000/
  > Network:  http://192.168.3.3:3000/
  > Network:  http://172.21.192.1:3000/
  > Network:  http://192.168.224.1:3000/

i Vite client warmed up in 68ms                                                                                   14:07:48
i Vite server warmed up in 55ms                                                                                   14:07:48

 WARN  [SSR] Error transforming C:/Users/kecrily/Desktop/dev/vue/my-module/node_modules/.pnpm/nuxt3@3.0.0-27459267.f69126e/node_modules/nuxt3/dist/app/entry: Missing "./playground/.nuxt/css" export in "my-module" package

  at bail (node_modules\.pnpm\vite@2.8.6\node_modules\vite\dist\node\chunks\dep-9c153816.js:28849:8)
  at resolve (node_modules\.pnpm\vite@2.8.6\node_modules\vite\dist\node\chunks\dep-9c153816.js:28926:10)
  at resolveExports (node_modules\.pnpm\vite@2.8.6\node_modules\vite\dist\node\chunks\dep-9c153816.js:29549:12)
  at resolveDeepImport (node_modules\.pnpm\vite@2.8.6\node_modules\vite\dist\node\chunks\dep-9c153816.js:29565:26)
  at tryNodeResolve (node_modules\.pnpm\vite@2.8.6\node_modules\vite\dist\node\chunks\dep-9c153816.js:29349:20)
  at Context.resolveId (node_modules\.pnpm\vite@2.8.6\node_modules\vite\dist\node\chunks\dep-9c153816.js:29166:28)
  at Object.resolveId (node_modules\.pnpm\vite@2.8.6\node_modules\vite\dist\node\chunks\dep-9c153816.js:38271:55)
  at async Context.resolve (node_modules\.pnpm\vite@2.8.6\node_modules\vite\dist\node\chunks\dep-9c153816.js:38050:23)      
  at async Object.resolveId (node_modules\.pnpm\vite@2.8.6\node_modules\vite\dist\node\chunks\dep-9c153816.js:38271:32)     
  at async TransformContext.resolve (node_modules\.pnpm\vite@2.8.6\node_modules\vite\dist\node\chunks\dep-9c153816.js:38050:23)

√ Vite server built in 123ms                                                                                      14:07:48
√ Nitro built in 469 ms                                                                                           14:07:49
_createApp is not a function
  at renderToString (file:///C:/Users/kecrily/Desktop/dev/vue/my-module/node_modules/.pnpm/vue-bundle-renderer@0.3.5/node_modules/vue-bundle-renderer/dist/index.mjs:247:25)
  at async renderMiddleware (file:///C:/Users/kecrily/Desktop/dev/vue/my-module/playground/.nuxt/nitro/index.mjs:208:20)
  at async handle (file:///C:/Users/kecrily/Desktop/dev/vue/my-module/node_modules/.pnpm/h3@0.4.2/node_modules/h3/dist/index.mjs:278:19)

 ERROR  [proxy] socket hang up                                                                                    14:09:54  

  at connResetException (node:internal/errors:692:14)
  at Socket.socketOnEnd (node:_http_client:466:23)
  at Socket.emit (node:events:539:35)
  at Socket.emit (node:domain:475:12)
  at endReadableNT (node:internal/streams/readable:1342:12)
  at processTicksAndRejections (node:internal/process/task_queues:83:21)


 ERROR  [worker] Worker terminated due to reaching memory limit: JS heap out of memory                            14:09:55  

  at new NodeError (node:internal/errors:372:5)
  at Worker.[kOnExit] (node:internal/worker:276:26)
  at Worker.<computed>.onexit (node:internal/worker:198:20)
```
</details>

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/module-builder/issues/22
