### ISSUE TITLE
Parse error in app.vue in a fresh, blank Nuxt 3 app

### ISSUE THREAD

**Issue by jerryjappinen** [nuxt/framework#3793]
### Environment

```
- Operating System: `Darwin`
- Node Version:     `v14.19.0`
- Nuxt Version:     `3.0.0-27460489.53fbca7`
- Package Manager:  `npm@6.14.16`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
```

### Reproduction

See full repro in this video:

https://user-images.githubusercontent.com/1101002/159128054-318e0071-6f8c-49ad-839d-2553ed270063.mp4

`package-lock.json` created in this video: https://gist.github.com/jerryjappinen/f9b1e6839074d33a7232130a3187588b

### Describe the bug

When I create a new, blank app with `nuxi init`, the app is created without errors. However, when trying to build it after installing dependencies, the build consistently fails with this error:

```sh
 ERROR  [vite:build-import-analysis] Parse error @:1:47                         17:41:17
file: /Users/jerryjappinen/Development/nuxt3-app/app.vue:4:7
2:   <div>
3:     <NuxtWelcome />
4:   </div>
          ^
5: </template>
```

This happens consistently every time I create a new app with `nuxi init`. I've encountered this the first time around 12 March or so but haven't been able to isolate the exact version.

### Logs

```shell
Development/ npx nuxi init nuxt3-app
Nuxt CLI v3.0.0-27444434.856c01a                                                17:40:09
ℹ cloned nuxt/starter#v3 to /Users/jerryjappinen/Development/nuxt3-app          17:40:10
                                                                                17:40:10
 🎉  Another super-excellent Nuxt project just made! Next steps:

     📁  `cd nuxt3-app`

     💿  Install dependencies with `npm install` or `yarn install`

     🚀  Start development server with `npm run dev` or `yarn dev`

     

Development/ cd nuxt3-app/

nuxt3-app/ nvm use 14
Now using node v14.19.0 (npm v6.14.16)

nuxt3-app/ npm i
npm WARN deprecated node-pre-gyp@0.13.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future

> esbuild@0.14.27 postinstall /Users/jerryjappinen/Development/nuxt3-app/node_modules/esbuild
> node install.js

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-android-64@0.14.27 (node_modules/esbuild/node_modules/esbuild-android-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-android-64@0.14.27: wanted {"os":"android","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-darwin-arm64@0.14.27 (node_modules/esbuild/node_modules/esbuild-darwin-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-darwin-arm64@0.14.27: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-freebsd-arm64@0.14.27 (node_modules/esbuild/node_modules/esbuild-freebsd-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-freebsd-arm64@0.14.27: wanted {"os":"freebsd","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-android-arm64@0.14.27 (node_modules/esbuild/node_modules/esbuild-android-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-android-arm64@0.14.27: wanted {"os":"android","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-freebsd-64@0.14.27 (node_modules/esbuild/node_modules/esbuild-freebsd-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-freebsd-64@0.14.27: wanted {"os":"freebsd","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-32@0.14.27 (node_modules/esbuild/node_modules/esbuild-linux-32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-32@0.14.27: wanted {"os":"linux","arch":"ia32"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-64@0.14.27 (node_modules/esbuild/node_modules/esbuild-linux-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-64@0.14.27: wanted {"os":"linux","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-arm@0.14.27 (node_modules/esbuild/node_modules/esbuild-linux-arm):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-arm@0.14.27: wanted {"os":"linux","arch":"arm"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-arm64@0.14.27 (node_modules/esbuild/node_modules/esbuild-linux-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-arm64@0.14.27: wanted {"os":"linux","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-mips64le@0.14.27 (node_modules/esbuild/node_modules/esbuild-linux-mips64le):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-mips64le@0.14.27: wanted {"os":"linux","arch":"mips64el"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-s390x@0.14.27 (node_modules/esbuild/node_modules/esbuild-linux-s390x):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-s390x@0.14.27: wanted {"os":"linux","arch":"s390x"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-openbsd-64@0.14.27 (node_modules/esbuild/node_modules/esbuild-openbsd-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-openbsd-64@0.14.27: wanted {"os":"openbsd","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-ppc64le@0.14.27 (node_modules/esbuild/node_modules/esbuild-linux-ppc64le):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-ppc64le@0.14.27: wanted {"os":"linux","arch":"ppc64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-riscv64@0.14.27 (node_modules/esbuild/node_modules/esbuild-linux-riscv64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-riscv64@0.14.27: wanted {"os":"linux","arch":"riscv64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-sunos-64@0.14.27 (node_modules/esbuild/node_modules/esbuild-sunos-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-sunos-64@0.14.27: wanted {"os":"sunos","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-netbsd-64@0.14.27 (node_modules/esbuild/node_modules/esbuild-netbsd-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-netbsd-64@0.14.27: wanted {"os":"netbsd","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-windows-32@0.14.27 (node_modules/esbuild/node_modules/esbuild-windows-32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-windows-32@0.14.27: wanted {"os":"win32","arch":"ia32"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-windows-64@0.14.27 (node_modules/esbuild/node_modules/esbuild-windows-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-windows-64@0.14.27: wanted {"os":"win32","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-windows-arm64@0.14.27 (node_modules/esbuild/node_modules/esbuild-windows-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-windows-arm64@0.14.27: wanted {"os":"win32","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})
npm WARN node-fetch@2.6.7 requires a peer of encoding@^0.1.0 but none is installed. You must install peer dependencies yourself.

added 649 packages from 341 contributors and audited 667 packages in 19.168s

102 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


nuxt3-app/ npx nuxi info
Nuxt CLI v3.0.0-27460489.53fbca7                                                17:41:05
RootDir: /Users/jerryjappinen/Development/nuxt3-app                             17:41:06
Nuxt project info:                                                              17:41:06

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.19.0`
- Nuxt Version:     `3.0.0-27460489.53fbca7`
- Package Manager:  `npm@6.14.16`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

👉 Report an issue: https://github.com/nuxt/framework/issues/new                17:41:06

👉 Suggest an improvement: https://github.com/nuxt/framework/discussions/new

👉 Read documentation: https://v3.nuxtjs.org


nuxt3-app/ npm run build

> @ build /Users/jerryjappinen/Development/nuxt3-app
> nuxi build

Nuxt CLI v3.0.0-27460489.53fbca7                                                17:41:14

 ERROR  [vite:build-import-analysis] Parse error @:1:47                         17:41:17
file: /Users/jerryjappinen/Development/nuxt3-app/app.vue:4:7
2:   <div>
3:     <NuxtWelcome />
4:   </div>
          ^
5: </template>


 ERROR  Parse error @:1:47                                                      17:41:17

  at parse$g (node_modules/vite/dist/node/chunks/dep-9c153816.js:19338:353)
  at Object.transform (node_modules/vite/dist/node/chunks/dep-9c153816.js:21010:27)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `nuxi build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jerryjappinen/.npm/_logs/2022-03-19T15_41_17_140Z-debug.log
```

**Comment by ennioVisco** [comment]
Ok, I am getting crazy as well with this, seems [related to this Vite issue](https://github.com/vitejs/vite/issues/4067), but I'm not sure.

**Comment by danielroe** [comment]
The issue here is your version of npm is not installing `@nuxt/ui-templates` as a dependency of `nuxt3`.

You can verify this by running `npm list @nuxt/ui-templates`. Here's the output.

```bash
❯ npm list @nuxt/ui-templates
/tmp/nuxt3-app
└─┬ nuxt3@3.0.0-27460489.53fbca7
  ├─┬ @nuxt/nitro@npm:@nuxt/nitro-edge@3.0.0-27460489.53fbca7
  │ └── @nuxt/ui-templates@npm:@nuxt/ui-templates-edge@0.0.0-27455683.83d2457  (@nuxt/ui-templates) invalid
  └── UNMET DEPENDENCY @nuxt/ui-templates@npm:@nuxt/ui-templates-edge@latest

npm ERR! missing: @nuxt/ui-templates@npm:@nuxt/ui-templates-edge@latest, required by nuxt3@3.0.0-27460489.53fbca7
npm ERR! invalid: @nuxt/ui-templates-edge@0.0.0-27455683.83d2457 /tmp/nuxt3-app/node_modules/@nuxt/nitro/node_modules/@nuxt/ui-templates
```

Note that it is in `nuxt3`'s dependencies: https://github.com/nuxt/framework/blob/fb150825ceebbffddd49b312962bef9e6f3ed1b5/packages/nuxt3/package.json#L32-L36

I'm not sure what we can do from a nuxt perspective, but you can either use `npm@8` or manually run `npm install @nuxt/ui-templates@npm:@nuxt/ui-templates-edge@latest`.

cc: @pi0

**Comment by danielroe** [comment]
Closing in favour of https://github.com/nuxt/framework/issues/3608
