### ISSUE TITLE
ERROR [vite] Internal server error: URI malformed   

### ISSUE THREAD

**Issue by jasonkhanlar** [nuxt/framework#3796]
### Environment

Nuxt CLI v3.0.0-27460489.53fbca7                                                                                                                                                     01:09:13
RootDir: /root/node.js/nuxt3/server/api                                                                                                                           01:09:14
Nuxt project info:                                                                                                                                                                   01:09:14

------------------------------
- Operating System: `Linux`
- Node Version:     `v17.7.2`
- Nuxt Version:     `3.0.0-27460489.53fbca7`
- Package Manager:  `npm@8.5.5`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Visit a path that uses % incorrectly

### Describe the bug

I think this is a bug in Nuxt 3 dev environment: http://domain.com:3000/%2:  (add %2: to the path, or any other malformed URI)

```
 ERROR  1:01:55 AM [vite] Internal server error: URI malformed
      at decodeURI (<anonymous>)
      at viteTransformMiddleware (/root/node.js/node_modules/vite/dist/node/chunks/dep-9c153816.js:53115:19)
      at call (/root/node.js/node_modules/vite/dist/node/chunks/dep-9c153816.js:41576:7)
      at next (/root/node.js/node_modules/vite/dist/node/chunks/dep-9c153816.js:41520:5)
      at /root/node.js/node_modules/vite/dist/node/chunks/dep-9c153816.js:52764:28
      at viteServePublicMiddleware (root/node.js/node_modules/vite/dist/node/chunks/dep-9c153816.js:52803:9)
      at call (/root/node.js/node_modules/vite/dist/node/chunks/dep-9c153816.js:41576:7)
      at next (/root/node.js/node_modules/vite/dist/node/chunks/dep-9c153816.js:41520:5)
      at next (/root/node.js/node_modules/vite/dist/node/chunks/dep-9c153816.js:41498:14)
      at next (/root/node.js/node_modules/vite/dist/node/chunks/dep-9c153816.js:41498:14)
```

**Comment by danielroe** [comment]
Would you raise an issue on https://github.com/vitejs/vite please? 🙏 

It's reproducible with https://stackblitz.com/edit/vitejs-vite-ztmssn, for example.

**Comment by danielroe** [comment]
Here's the upstream issue: https://github.com/vitejs/vite/issues/6482. I'm going to close the issue here, but feel free to track it there.
