### ISSUE TITLE
Using server middlewares breaks both dev and build servers

### ISSUE THREAD

**Issue by arthur-bri** [nuxt/framework#3807]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-27460489.53fbca7`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `typescript`, `build`, `vite`, `css`, `buildModules`, `unocss`, `fifteenSitemap`, `serverMiddleware`, `meta`, `publicRuntimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `@unocss/nuxt@0.22.7`, `@vueuse/nuxt@7.5.3`, `./modules/nuxt/i18n`, `./modules/nuxt/sitemap`, `./modules/nuxt/version`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-kc5f98

### Describe the bug

When a `serverMiddleware` array is defined in `nuxt.config.ts`, Nuxt throws an error.

I will update this issue when I find the commit which introduced this apparent bug. 

### Logs

```shell
ERROR  Cannot start nuxt:  Cannot read properties of undefined (reading 'handle')                       
  at Function.use (node_modules/connect/index.js:87:21)
  at Object.set [as setLegacyMiddleware] (node_modules/@nuxt/nitro/dist/index.mjs:1898:13)
  at eval (node_modules/nuxt3/dist/chunks/nitro-legacy.mjs:70:17)
  at async initNuxt (node_modules/nuxt3/dist/chunks/index.mjs:1117:3)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6762:9)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6803:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:57:7)
```

**Comment by Aareksio** [comment]
I believe the key is `handle` not `handler`. After changing it, the middleware works, although `path` is not respected. For `health` endpoint you can use `/server/api` directory, [documented here](https://v3.nuxtjs.org/docs/directory-structure/server/#api-routes).

Not sure if `path` parameter is obsolete, but a little further into the doc it is suggested that middleware from `/server/middleware` runs on all routes and must include logic to [prevent it from executing it on unintended paths](https://v3.nuxtjs.org/docs/directory-structure/server/#server-middleware).

**Comment by danielroe** [comment]
Workaround for now is:

```diff
import { defineNuxtConfig } from 'nuxt3';

// https://v3.nuxtjs.org/docs/directory-structure/nuxt.config
export default defineNuxtConfig({
  serverMiddleware: [
    {
-     path: '/_/health',
+     route: '/_/health',
-     handler: '~/server/health.ts',
+     handle: '~/server/health.ts',
    },
  ],
});
```

**Comment by danielroe** [comment]
This is caused by https://github.com/nuxt/framework/issues/3800, because the _same_ object is inserted twice, so when we delete its properties on parsing it the first time, we inadvertently create a `{}` serverMiddleware:

https://github.com/nuxt/framework/blob/03d5fdde2d13fb4d900040c2a6f127c2347b11e1/packages/nitro/src/server/middleware.ts#L91-L92

Let's follow at https://github.com/nuxt/framework/issues/3800.

cc: @pi0
