### ISSUE TITLE
some auto imports are no longer working with unimport

### ISSUE THREAD

**Issue by safejace** [nuxt/framework#3977]
### Environment

Nuxt CLI v3.0.0-27477996.646c2f6
RootDir: /Users/jace.bennest/Development/safecom2
Nuxt project info: 

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-27477996.646c2f6`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `publicRuntimeConfig`, `components`, `css`, `build`, `buildModules`, `modules`, `sanity`, `tailwindcss`
- Runtime Modules:  `@nuxtjs/sanity@1.1.1`
- Build Modules:    `@pinia/nuxt@0.1.8`, `@nuxtjs/tailwindcss@5.0.2`, `@safesoftware/safebase-vue/nuxt@0.0.3`
------------------------------

*** Works with this env vvv***
Nuxt CLI v3.0.0-27459267.f69126e

### Reproduction

n/a

### Describe the bug

`useSanity()` is not defined
`groq` is not defined

### Logs

```shell
✔ Nitro built in 87 ms
groq is not defined
  at file://./.nuxt/dist/server/server.mjs:11300:17  
  at callWithNuxt (file://./.nuxt/dist/server/server.mjs:371:20)  
  at applyPlugin (file://./.nuxt/dist/server/server.mjs:322:29)  
  at Module.applyPlugins (file://./.nuxt/dist/server/server.mjs:332:11)  
  at async createNuxtAppServer (file://./.nuxt/dist/server/server.mjs:38:7)  
  at async renderToString (file://./node_modules/vue-bundle-renderer/dist/index.mjs:247:19)  
  at async renderMiddleware (file://./.nuxt/nitro/index.mjs:208:20)  
  at async handle (file://./node_modules/h3/dist/index.mjs:278:19)
groq is not defined
  at file://./.nuxt/dist/server/server.mjs:11300:17  
  at callWithNuxt (file://./.nuxt/dist/server/server.mjs:371:20)  
  at applyPlugin (file://./.nuxt/dist/server/server.mjs:322:29)  
  at Module.applyPlugins (file://./.nuxt/dist/server/server.mjs:332:11)  
  at processTicksAndRejections (node:internal/process/task_queues:96:5)  
  at async createNuxtAppServer (file://./.nuxt/dist/server/server.mjs:38:7)  
  at async renderToString (file://./node_modules/vue-bundle-renderer/dist/index.mjs:247:19)  
  at async renderMiddleware (file://./.nuxt/nitro/index.mjs:208:20)  
  at async handle (file://./node_modules/h3/dist/index.mjs:278:19)
groq is not defined
  at file://./.nuxt/dist/server/server.mjs:11300:17  
  at callWithNuxt (file://./.nuxt/dist/server/server.mjs:371:20)  
  at applyPlugin (file://./.nuxt/dist/server/server.mjs:322:29)  
  at Module.applyPlugins (file://./.nuxt/dist/server/server.mjs:332:11)  
  at processTicksAndRejections (node:internal/process/task_queues:96:5)  
  at async createNuxtAppServer (file://./.nuxt/dist/server/server.mjs:38:7)  
  at async renderToString (file://./node_modules/vue-bundle-renderer/dist/index.mjs:247:19)  
  at async renderMiddleware (file://./.nuxt/nitro/index.mjs:208:20)  
  at async handle (file://./node_modules/h3/dist/index.mjs:278:19)
```

**Comment by antfu** [comment]
@safejace Can you share a minimal reproduction so I could have a look? Thanks.

**Comment by safejace** [comment]
@danielroe `useSanity` was throwing errors, but that was while i was trying to diagnose (ie throwing spaghetti at the wall to see what sticks) the issue.

but only the `groq` issue is repeatable for me with consistency

**Comment by danielroe** [comment]
same issue with template literal: https://github.com/nuxt/framework/issues/4004

**Comment by procrates** [comment]
Any news? Simple queries works without qroq but when it comes to object notation like slug.current, it dosnt seem to resolve.
