### ISSUE TITLE
date-fns/locale with build mode: infinite loop error reporting

### ISSUE THREAD

**Issue by Baiyuetribe** [nuxt/framework#3988]
### Environment

windos11 && linux

### Reproduction

https://stackblitz.com/edit/github-4tzzdh?file=app.vue

### Describe the bug

Development mode is normal, after build infinite loop error reporting
```
❯ Directory import '/home/projects/github-4tzzdh/.output/server/node_modules/date-fns/locale' is not supported resolving ES modules imported from /home/projects/github-4tzzdh/.output/server/chunks/app/server.mjs
Did you mean to import date-fns/locale/index.js?
  at InternalError.get (https://github-4tzzdh.w.staticblitz.com/blitz.31afbfcfe1b0985e8cbdb27d44e16766166a118e.js:6:292359)  
  at defaultResolve (https://github-4tzzdh.w.staticblitz.com/blitz.31afbfcfe1b0985e8cbdb27d44e16766166a118e.js:6:579750)  
  at ESMLoader.resolve (https://github-4tzzdh.w.staticblitz.com/blitz.31afbfcfe1b0985e8cbdb27d44e16766166a118e.js:6:1056167)  
  at ESMLoader.getModuleJob (https://github-4tzzdh.w.staticblitz.com/blitz.31afbfcfe1b0985e8cbdb27d44e16766166a118e.js:6:1053892)  
  at https://github-4tzzdh.w.staticblitz.com/blitz.31afbfcfe1b0985e8cbdb27d44e16766166a118e.js:6:1010426  
  at _0x5cd016.link (https://github-4tzzdh.w.staticblitz.com/blitz.31afbfcfe1b0985e8cbdb27d44e16766166a118e.js:15:248273)  
  at https://github-4tzzdh.w.staticblitz.com/blitz.31afbfcfe1b0985e8cbdb27d44e16766166a118e.js:6:1010387
```

**Comment by danielroe** [comment]
Just follow the instructions in the message, and it works fine.

**Comment by Baiyuetribe** [comment]
@[danielroe](https://github.com/danielroe)
Can you help me to correct the connection, I have tried many times but it doesn't work, can you give some key codes?
Reproduction:https://stackblitz.com/edit/github-4tzzdh?file=app.vue

**Comment by Baiyuetribe** [comment]
In the file`nuxt.config.js`,Everything is fine after this setting, is there any problem with this?
```
        ssr: {
            noExternal: [ "date-fns"],  
        },
```

**Comment by danielroe** [comment]
This is what the error message told you to do:

```diff
- import { es, zhCN } from 'date-fns/locale'
+ import { es, zhCN } from 'date-fns/locale/index.js'
```

But yes, I see no problem with transpiling `date-fns`.
