### ISSUE TITLE
`views/document.template.mjs` isn't immediately available

### ISSUE THREAD

**Issue by danielroe** [nuxt/framework#399]
nitro _can_ throw a mix of errors on first build (when running `nu dev`). This eventually resolves but it spams the console and is due to the template not being in vfs

```
import htmlTemplate from '/framework/playground/.nuxt/views/document.template.mjs';
       ^^^^^^^^^^^^
SyntaxError: The requested module '/framework/playground/.nuxt/views/document.template.mjs' does not provide an export named 'default'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:120:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:165:5)
    at async Loader.import (internal/modules/esm/loader.js:177:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
```
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/framework/playground/.nuxt/views/document.template.mjs' imported from /framework/playground/.nuxt/nitro/index.mjs
    at finalizeResolution (internal/modules/esm/resolve.js:271:11)
    at moduleResolve (internal/modules/esm/resolve.js:694:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:805:11)
    at Loader.resolve (internal/modules/esm/loader.js:88:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:241:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:72:40)
    at link (internal/modules/esm/module_job.js:71:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

**Comment by pi0** [comment]
Is it possible probably sharing your repository with me or daniel?

**Comment by Fontinalis** [comment]
@pi0 @danielroe With any questions regarding the repository, please contact me at barnabas@agema.io

**Comment by vanling** [comment]
@pi0 Maybe this helps in finding where issue might be

I had this error as wel on clean nuxt2 + bridge.
After i reverted everything back to nuxt2 only i found the missing file above the project folder. 

not found `/something-app.domainname.com/.nuxt/views/document.template.mjs`
this file was in newly created folder outside of nuxt project and _app_ was replaced by _document_
`/something-document.domainname.com/.nuxt/views/document.template.mjs`

Not sure if @Fontinalis has a similar foldername with a "reserved word" as projectname.

**Comment by Fontinalis** [comment]
@vanling This could be it! Now that you were saying, I also found the missing file in `/document.domain.com/.nuxt/views/document.template.mjs`. The original app folder is the similar to yours, `/app.domain.com/`

**Comment by vanling** [comment]
@Fontinalis maybe fixed in https://github.com/nuxt/framework/pull/1624 ?
