### ISSUE TITLE
Cannot start nuxt:  The requested module '@nuxt/kit' does not provide an export named 'addAutoImport' 

### ISSUE THREAD

**Issue by Gyurmatag** [nuxt/framework#4035]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-27480376.fdd38f9`
- Package Manager:  `npm@8.3.1`
- Builder:          `vite`
- User Config:      `buildModules`, `modules`, `intlify`, `alias`, `css`, `colorMode`, `build`, `publicRuntimeConfig`, `meta`
- Runtime Modules:  `@nuxtjs/color-mode@3.0.2`
- Build Modules:    `@intlify/nuxt3@0.1.10`, `@pinia/nuxt@0.1.8`

### Reproduction

Cannot reproduces in StackBlitz. Only in local.

### Describe the bug

After deleting package-lock.json and node_modules folder and doing a fresh clean install to the latest version of Nuxt, I've got this error when runnig 'nuxi dev':

>  ERROR  Cannot start nuxt:  The requested module '@nuxt/kit' does not provide an export named 'addAutoImport'                                                                                                                                                                                      

### Logs

```shell
import { defineNuxtModule, createResolver, addTemplate, addPlugin, addComponent, isNuxt2, addAutoImport } from '@nuxt/kit';
  ^^^^^^^^^^^^^
  SyntaxError: The requested module '@nuxt/kit' does not provide an export named 'addAutoImport'
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:127:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:191:5)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
  at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
  at async installModule (node_modules/nuxt3/node_modules/@nuxt/kit/dist/index.mjs:380:3)
  at async initNuxt (node_modules/nuxt3/dist/chunks/index.mjs:1152:7)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6752:9)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6793:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:46:7)
```

**Comment by danielroe** [comment]
It's likely an issue that one of your modules is depending on an old version of Nuxt kit, and this is being hoisted to the top level. Try adding the following to your package.json:

```json
{
  "dependencies": {
    "@nuxt/kit": "npm:@nuxt/kit-edge@latest"
  }
}
```

**Comment by Gyurmatag** [comment]
Thank you very much! It's working now.
