### ISSUE TITLE
Problem with paths.mjs at windows

### ISSUE THREAD

**Issue by gitFoxCode** [nuxt/framework#4056]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27480376.fdd38f9`
- Package Manager:  `npm@8.1.4`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Just follow the documentation using windows: https://v3.nuxtjs.org/docs/advanced/modules/

1. `npx nuxi init -t module my-module`
2. `cd my-module`
3. `npm install`
4. `npm run dev:prepare`
5. `npm run dev`

### Describe the bug

The error is probably related to paths in windows, because on other operating systems everything works fine

### Additional context

I have checked this error with a few people and the problem only occurs on windows.  (or maybe I'm doing something wrong)

### Logs

```shell
i Vite client warmed up in 35ms                                                                               08:43:10
i Vite server warmed up in 17ms                                                                               08:43:10

 WARN  [SSR] Error transforming C:/Users/Sebek/OneDrive/Dokumenty/Programming/my-module/node_modules/nuxt3/dist/app/entry: Missing "./playground/.nuxt/paths.mjs" export in "my-module" package

  at bail (node_modules\vite\dist\node\chunks\dep-611778e0.js:37559:8)
  at resolve (node_modules\vite\dist\node\chunks\dep-611778e0.js:37636:10)
  at resolveExports (node_modules\vite\dist\node\chunks\dep-611778e0.js:38302:12)
  at resolveDeepImport (node_modules\vite\dist\node\chunks\dep-611778e0.js:38320:31)
  at tryNodeResolve (node_modules\vite\dist\node\chunks\dep-611778e0.js:38093:20)
  at Context.resolveId (node_modules\vite\dist\node\chunks\dep-611778e0.js:37901:28)
  at Object.resolveId (node_modules\vite\dist\node\chunks\dep-611778e0.js:36470:55)
  at async Context.resolve (node_modules\vite\dist\node\chunks\dep-611778e0.js:36244:23)
  at async Object.resolveId (node_modules\vite\dist\node\chunks\dep-611778e0.js:36470:32)
  at async TransformContext.resolve (node_modules\vite\dist\node\chunks\dep-611778e0.js:36244:23)
√ Vite server built in 34ms                                                                                   08:43:10
√ Nitro built in 202 ms                                                                                       08:43:10
_createApp is not a function
  at renderToString (file:///C:/Users/Sebek/OneDrive/Dokumenty/Programming/my-module/node_modules/vue-bundle-renderer/dist/index.mjs:247:25)
  at async renderMiddleware (file:///C:/Users/Sebek/OneDrive/Dokumenty/Programming/my-module/playground/.nuxt/nitro/index.mjs:208:20)
  at async handle (file:///C:/Users/Sebek/OneDrive/Dokumenty/Programming/my-module/node_modules/h3/dist/index.mjs:278:19)
```
```

**Comment by pi0** [comment]
Hi @gitFoxCode. This seems related to https://github.com/nuxt/module-builder/issues/22. Do you mind creating a package.json in `playground` directory to see if fixes issue?

**Comment by gitFoxCode** [comment]
> Hi @gitFoxCode. This seems related to [nuxt/module-builder#22](https://github.com/nuxt/module-builder/issues/22). Do you mind creating a package.json in `playground` directory to see if fixes issue?

Yes, this is exactly the same error. Thanks a lot! I searched for this error under other phrases

**Comment by marty-mcgee** [comment]
Just to confirm the solution for me on Windows 11 for this exact same error message:

1. Added an empty object {} "package.json" file to the "/playground" directory.
2. Ran "npm run dev:prepare", so .nuxt and node_modules in playground are generated.
3. I can now run "npm run dev" as expected.

However, there are additional errors that occur at this point, but unrelated to this exact error.
