### ISSUE TITLE
Running `yarn dev` fails on clean nuxt install

### ISSUE THREAD

**Issue by kreejzak** [nuxt/framework#4099]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-27486132.e1e3f50`
- Package Manager:  `yarn@1.22.15`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

create new nuxt project following official docs and try yarn or npm run dev

### Describe the bug

when running `yarn dev` the script is stuck with the following output and browser is stuck on the `Starting nuxt` page

### Logs

```shell
Nuxt CLI v3.0.0-27486132.e1e3f50                                                                                                                                                         16:38:43
                                                                                                                                                                                         16:38:43
  > Local:    http://localhost:3000/ 
  > Network:  http://192.168.1.100:3000/


 ERROR  Failed to resolve import "/Users/user_name/project_name/node_modules/nuxt3/dist/head/runtime/lib/vueuse-head.plugin" from "virtual:/Users/user_name/project_name/.nuxt/plugins/client.mjs". Does the file exist?

ℹ Vite client warmed up in 1090ms                                                                                                                                                        16:38:49
ℹ Vite server warmed up in 360ms                                                                                                                                                         16:38:49
✔ Vite server built in 732ms                                                                                                                                                             16:38:49
✔ Nitro built in 166 ms                                                                                                                                                                  16:38:49
[Vue warn]: Unhandled error during execution of setup function 
  at <Welcome>

 ERROR  [worker] __vite_ssr_import_0__.useMeta is not a function                                                                                                                         16:38:50

  at setup (.nuxt/dist/server/server.mjs:2293:23)
  at _sfc_main.setup (.nuxt/dist/server/server.mjs:2337:23)
  at callWithErrorHandling (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:157:22)
  at setupStatefulComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6977:29)
  at setupComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6933:11)
  at renderComponentVNode (node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:198:17)
  at Module.ssrRenderComponent (node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:629:12)
  at _sfc_ssrRender (.nuxt/dist/server/server.mjs:2226:31)
  at renderComponentSubTree (node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:269:13)
  at renderComponentVNode (node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:214:16)


 ERROR  [proxy] connect ENOENT /var/folders/fh/d8579ktx5gl4fdp3dxty9jbc0000gn/T/nitro/worker-61145-1.sock                                                                                16:38:50

  at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1161:16)
```

**Comment by kreejzak** [comment]
Probably fixed by #4101 
Closing issue
