### ISSUE TITLE
Can't create brand new nuxt3 project

### ISSUE THREAD

**Issue by davidedisalvo** [nuxt/framework#4132]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v14.17.3`
- Nuxt Version:     `3.0.0-27487398.da46b8d`
- Package Manager:  `npm@6.14.13`
- Builder:          `vite`
- User Config:      `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.1.8`

### Reproduction

Can't give a link to a repo because the bug appear when creating a new project.

### Describe the bug

After running 
`npx nuxi init nuxt3-app`
`cd nuxt-3-app`
`npm install`

I have this error on my terminal:

` ERROR  16:11:39 [vite] Internal server error: Failed to parse source for import analysis because the content contains invalid JS syntax. Install @vitejs/plugin-vue to handle .vue files.                             16:11:39  
  Plugin: vite:import-analysis
  File: C:/Users/ddisalvo/Desktop/sites/ic-fan-facing-template/app.vue
  1  |  import { default as __nuxt_component_0 } from null;
     |                                                ^
  2  |  const _sfc_main = {}
  3  |  import { resolveComponent as _resolveComponent, createVNode as _createVNode, openBlock as _openBlock, createElementBlock as _createElementBlock } from "vue"
      at formatError (C:\Users\ddisalvo\Desktop\sites\ic-fan-facing-template\node_modules\vite\dist\node\chunks\dep-611778e0.js:36296:46)
      at TransformContext.error (C:\Users\ddisalvo\Desktop\sites\ic-fan-facing-template\node_modules\vite\dist\node\chunks\dep-611778e0.js:36292:19)
      at TransformContext.transform (C:\Users\ddisalvo\Desktop\sites\ic-fan-facing-template\node_modules\vite\dist\node\chunks\dep-611778e0.js:59615:22)
      at async Object.transform (C:\Users\ddisalvo\Desktop\sites\ic-fan-facing-template\node_modules\vite\dist\node\chunks\dep-611778e0.js:36533:30)
      at async doTransform (C:\Users\ddisalvo\Desktop\sites\ic-fan-facing-template\node_modules\vite\dist\node\chunks\dep-611778e0.js:55507:29)`

If I try to delete the `<NuxtWelcome/>` component from `<App />` the error change into this:

` ERROR  16:20:55 [vite] Internal server error: Failed to resolve import "@nuxt/ui-templates/templates/error-404.vue" from "node_modules\nuxt3\dist\app\components\nuxt-error-page.vue". Does the file exist?           16:20:55  
  Plugin: vite:import-analysis
  File: C:/Users/ddisalvo/Desktop/sites/ic-fan-facing-template/node_modules/nuxt3/dist/app/components/nuxt-error-page.vue
  1  |  import Error404 from '@nuxt/ui-templates/templates/error-404.vue'
     |                        ^
  2  |  import Error500 from '@nuxt/ui-templates/templates/error-500.vue'
  3  |  import ErrorDev from '@nuxt/ui-templates/templates/error-dev.vue'
      at formatError (C:\Users\ddisalvo\Desktop\sites\ic-fan-facing-template\node_modules\vite\dist\node\chunks\dep-611778e0.js:36296:46)
      at TransformContext.error (C:\Users\ddisalvo\Desktop\sites\ic-fan-facing-template\node_modules\vite\dist\node\chunks\dep-611778e0.js:36292:19)
      at normalizeUrl (C:\Users\ddisalvo\Desktop\sites\ic-fan-facing-template\node_modules\vite\dist\node\chunks\dep-611778e0.js:59668:26)
      at async TransformContext.transform (C:\Users\ddisalvo\Desktop\sites\ic-fan-facing-template\node_modules\vite\dist\node\chunks\dep-611778e0.js:59817:57)
      at async Object.transform (C:\Users\ddisalvo\Desktop\sites\ic-fan-facing-template\node_modules\vite\dist\node\chunks\dep-611778e0.js:36533:30)
      at async doTransform (C:\Users\ddisalvo\Desktop\sites\ic-fan-facing-template\node_modules\vite\dist\node\chunks\dep-611778e0.js:55507:29)`

**Comment by danielroe** [comment]
This is a known bug with `npm@6`. You can follow the workarounds here: https://github.com/nuxt/framework/issues/3608#issuecomment-1073803039.
