### ISSUE TITLE
`#nitro` is not defined

### ISSUE THREAD

**Issue by ikadix** [nuxt/framework#4158]
### Environment

❯ npx nuxi info
Nuxt CLI v3.0.0-27488877.2bedebe                                                                                                                                       13:44:19
RootDir: /home/projects/github-lpk18d                                                                                                                                  13:44:22
Nuxt project info:                                                                                                                                                     13:44:22

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-27488877.2bedebe`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-lpk18d?file=package.json

### Describe the bug

Creating a new project with the most recent nuxt version results in a failing dev server.

### Logs

```shell
ERROR  [worker reload] [worker init]Package import specifier "#nitro" is not defined in package /home/projects/github-lpk18d/node_modules/nuxt3/package.json imported from /home/projects/github-lpk18d/node_modules/nuxt3/dist/core/runtime/nitro/paths.mjs

  at TypeError.get (https://github-lpk18d.w.staticblitz.com/blitz.31afbfcfe1b0985e8cbdb27d44e16766166a118e.js:6:292359)
  at https://github-lpk18d.w.staticblitz.com/blitz.31afbfcfe1b0985e8cbdb27d44e16766166a118e.js:6:986991
  at Array.forEach (<anonymous>)
  at TryGetAllProperties (https://github-lpk18d.w.staticblitz.com/blitz.31afbfcfe1b0985e8cbdb27d44e16766166a118e.js:6:986899)
  at serializeError (https://github-lpk18d.w.staticblitz.com/blitz.31afbfcfe1b0985e8cbdb27d44e16766166a118e.js:6:987576)
  at process.workerOnGlobalUncaughtException [as _fatalException] (https://github-lpk18d.w.staticblitz.com/blitz.31afbfcfe1b0985e8cbdb27d44e16766166a118e.js:6:1613913)
  at Object.triggerUncaughtException (https://github-lpk18d.w.staticblitz.com/blitz.31afbfcfe1b0985e8cbdb27d44e16766166a118e.js:15:325916)
  at i.loadESM (https://github-lpk18d.w.staticblitz.com/blitz.31afbfcfe1b0985e8cbdb27d44e16766166a118e.js:6:268244)
  at async handleMainPromise (https://github-lpk18d.w.staticblitz.com/blitz.31afbfcfe1b0985e8cbdb27d44e16766166a118e.js:6:989191)
```

**Comment by pi0** [comment]
Working on it (#4157) sorry for regression.

**Comment by ikadix** [comment]
Sorry didn't check PRs first :see_no_evil:

Thanks :raised_hands:

**Comment by AndreyYolkin** [comment]
> Working on it (#4157) sorry for regression.

Sorry, but I tried to delete node_modules. .nuxt, package-lock, then reinstalled all dependencies, and still have this error on bridge.

<details><summary>Nuxi info</summary>

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `npm@8.5.0`
- Builder:          `webpack`
- User Config:      `buildModules`, `bridge`
- Runtime Modules:  `-`
- Build Modules:    `@nuxtjs/vuetify@1.12.3`, `@nuxt/bridge@3.0.0-27488954.9fbb9be`

</details>

<details><summary>Log</summary>

```
node[2162]: ../src/node_file-inl.h:160:node::fs::FSReqPromise<AliasedBufferT>::~FSReqPromise() [with AliasedBufferT = node::AliasedBufferBase<double, v8::Float64Array>]: Assertion `finished_' failed.
 1: 0xb09980 node::Abort() [node]
 2: 0xb099fe  [node]

 ERROR  [worker reload] [worker init]Package import specifier "#nitro" is not defined in package /home/user/platform/node_modules/@nuxt/bridge/package.json imported from /home/user/platform/node_modules/@nuxt/bridge/dist/runtime/nitro/paths.mjs                                                                            17:46:37

  at new NodeError (node:internal/errors:371:5)
  at throwImportNotDefined (node:internal/modules/esm/resolve:442:9)
  at packageImportsResolve (node:internal/modules/esm/resolve:819:3)
  at moduleResolve (node:internal/modules/esm/resolve:973:21)
  at defaultResolve (node:internal/modules/esm/resolve:1080:11)
  at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:79:40)
  at link (node:internal/modules/esm/module_job:78:36)

 3: 0xb048ca  [node]
 4: 0xb100d2 node::fs::FSReqAfterScope::~FSReqAfterScope() [node]
 5: 0xb105be node::fs::AfterOpenFileHandle(uv_fs_s*) [node]
 6: 0x155ebed  [node]
 7: 0x15633c6  [node]
 8: 0x1575af4  [node]
 9: 0x1563d18 uv_run [node]
10: 0xa43dd5 node::SpinEventLoop(node::Environment*) [node]
11: 0xbd3262 node::worker::Worker::Run() [node]
12: 0xbd39f8  [node]
13: 0x7f7541d8ed80  [/lib/x86_64-linux-gnu/libpthread.so.0]
14: 0x7f7541cb9b6f clone [/lib/x86_64-linux-gnu/libc.so.6]
Aborted
```

</details>

https://github.com/AndreyYolkin/reproduction

**Comment by todaynogada** [comment]
I also have that error. So I'm temporarily running pm2 with npm run dev.
I hope the error is resolved soon.
