### ISSUE TITLE
'useHead is not defined' error when hot reloading from nuxt3

### ISSUE THREAD

**Issue by n0ch4t** [nuxt/framework#4189]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0-27486226.7a70644`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `meta`, `css`, `buildModules`, `intlify`, `vite`, `router`, `build`
- Runtime Modules:  `-`
- Build Modules:    `@intlify/nuxt3@0.1.10`

### Reproduction

https://github.com/n0ch4t/nuxt3-starter

### Describe the bug

If 'hot reload' occurs after a slight modification of the code, the error often appears

### Logs

```shell
500
useHead is not defined

at setup (file://./.nuxt/dist/server/server.mjs:9140:5)
at _sfc_main.setup (file://./.nuxt/dist/server/server.mjs:9179:23)
at callWithErrorHandling (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:157:22)
at setupStatefulComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6977:29)
at setupComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6933:11)
at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:198:17)
at renderVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:310:22)
at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:275:13)
at ./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:211:29
```

**Comment by danielroe** [comment]
The reproduction you've shared is using a version of Nuxt that is [four months old](https://github.com/n0ch4t/nuxt3-starter/blob/master/package-lock.json#L7283).

`useMeta` was renamed to `useHead` in https://github.com/nuxt/framework/pull/4066, and it's likely you have a dependency that's using the new name, but your Nuxt version doesn't support it.

If you still encounter it after upgrading, would you provide a minimal reproduction with the latest Nuxt, and I'll take a look?

**Comment by n0ch4t** [comment]
I updated the version and the error disappeared, but there was a problem that a 404 error occurred after hot reload
When I refresh, it works normally.

**Comment by danielroe** [comment]
That doesn't sound related to this issue - perhaps you could raise a new issue with a reproduction? :pray:
