### ISSUE TITLE
Failed to resolve dependencies when starting Nuxt under workspaces

### ISSUE THREAD

**Issue by eden** [nuxt/framework#4217]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v17.8.0`
- Nuxt Version:     `3.0.0-27490192.4253d2e`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

1. Create a minimal workspace: `echo '{"private": true, "workspaces": ["app"]}' > package.json`
2. Create the starter nuxt 3 app inside the same directory: `npx nuxi init app`
3. Update `app/package.json` to add a name and version (since yarn 1.x requires this in its workspaces).
    * `sed -i '' 's/"private"/"name":"app","version":"1.0.0","private"/' app/package.json`
4. The cwd should look like this:
```
./app
./app/app.vue
./app/README.md
./app/.gitignore
./app/package.json
./app/nuxt.config.ts
./app/tsconfig.json
./package.json
```
6. Run `yarn` to setup the workspace
7. Test out the workspace's dev: `yarn workspace app dev` -- this works
8. Build: `yarn workspace app build` -- this fails (see logs)

### Describe the bug

Unable to build a nuxt 3 app within a yarn 1.x workspace. Development works fine. Build will also work if I nuke the workspace's `node_modules` and link it directly to the parent directory's `node_modules`.

### Logs

```shell
Nuxt CLI v3.0.0-27490192.4253d2e                                                                              14:58:13
ℹ Client built in 659ms                                                                                       14:58:15
ℹ Vite client warmed up in 661ms                                                                              14:58:15
ℹ Building server...                                                                                          14:58:15
✔ Server built in 241ms                                                                                       14:58:15
✔ Generated public .output/public                                                                       nitro 14:58:15
start Building server...                                                                                nitro 14:58:15

 WARN  '@nuxt/devalue' is imported by ../node_modules/nuxt3/dist/core/runtime/nitro/renderer.mjs, but could not be resolved – treating it as an external dependency


 WARN  '@vue/runtime-dom' is imported by @vue/runtime-dom?commonjs-external, but could not be resolved – treating it as an external dependency


 WARN  '@vue/shared' is imported by @vue/shared?commonjs-external, but could not be resolved – treating it as an external dependency


 ERROR  Rollup error: Could not load vue/server-renderer (imported by .nuxt/dist/server/server.mjs): ENOENT: no such file or directory, open 'vue/server-renderer'


 ERROR  Could not load vue/server-renderer (imported by .nuxt/dist/server/server.mjs): ENOENT: no such file or directory, open 'vue/server-renderer'



error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /opt/homebrew/Cellar/node/17.8.0/bin/node
Arguments: /opt/homebrew/lib/node_modules/yarn/lib/cli.js build
Directory: /Users/eden/dev/example2/app
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
```

**Comment by exreplay** [comment]
I was able to get rid of the error by updating the nitro aliases:

```ts
import { defineNuxtConfig } from 'nuxt3';
import path from 'path';

export default defineNuxtConfig({
  nitro: {
    alias: {
      'vue/server-renderer': path.resolve(
        __dirname,
        '../../../node_modules/vue/server-renderer'
      ),
      'vue/compiler-sfc': path.resolve(
        __dirname,
        '../../../node_modules/vue/compiler-sfc'
      )
    }
  }
});
```

But when i try to run the built project, i get the following error:

```
[nitro] [request error] Cannot assign to read only property '__esModule' of object '#<Object>'
  at ./server/chunks/app/server.mjs:94:35
  at Array.forEach (<anonymous>)
  at ./server/chunks/app/server.mjs:93:25
  at ./server/chunks/app/server.mjs:97:2
  at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
  at async ./server/chunks/handlers/renderer.mjs:50:24
  at async ./server/chunks/handlers/renderer.mjs:108:20
  at async [path to my project]/node_modules/h3/dist/index.mjs:416:19
```

While building i also get a lot of warnings :

```
 WARN  '@vue/runtime-dom' is imported by @vue/runtime-dom?commonjs-external, but could not be resolved – treating it as an external dependency


 WARN  '@vue/shared' is imported by @vue/shared?commonjs-external, but could not be resolved – treating it as an external dependency


 WARN  '@vue/server-renderer' is imported by @vue/server-renderer?commonjs-external, but could not be resolved – treating it as an external dependency


 WARN  '@nuxt/devalue' is imported by ../../../node_modules/nuxt3/dist/core/runtime/nitro/renderer.mjs, but could not be resolved – treating it as an external dependency


 WARN  'vue-bundle-renderer' is imported by ../../../node_modules/nuxt3/dist/core/runtime/nitro/renderer.mjs, but could not be resolved – treating it as an external dependency


 WARN  'marked' is imported by .nuxt/dist/server/server.mjs, but could not be resolved – treating it as an external dependency


 WARN  Multiple major versions of package node-fetch are being externalized. Picking latest version.
  - [path to my project]/node_modules/node-fetch@2.6.7
  - [path to my project]/node_modules/nitropack/node_modules/node-fetch@3.2.3
```

When i alias all the warnings, i still get an error

```
Cannot destructure property 'createComponentInstance' of 'vue.ssrUtils' as it is undefined.
```

**Comment by exodusanto** [comment]
In the `manifest.json` in `.output/public/_nuxt` the entry file point the wrong folder:

```json
{
  "../../node_modules/nuxt3/dist/app/entry.mjs": {
    "file": "entry-cb1a8fa5.mjs",
    "src": "../../node_modules/nuxt3/dist/app/entry.mjs",
    "isEntry": true,
    "dynamicImports": [
      "pages/index.vue",
      "pages/login.vue",
      "pages/me/index.vue",
      "pages/me/todos/[id].vue",
      "middleware/auth.ts"
    ],
    "css": [
      "entry.3d17baad.css"
    ]
  },
....
```

**Comment by mrauhu** [comment]
Same issue with NPM Workspaces.

Temporary fix is to change Nuxt 3 version in `package.json`:

```json5
{
  // ...
  "devDependencies": {
    "nuxt3":  "3.0.0-27488831.368610e",
    // ...
  }
}
```

**Comment by mrauhu** [comment]
Also there is a better workaround from @danielroe:

> A workaround for now is to run `yarn nuxi build app` (from the workspace root) rather than `yarn workspace app build`.

If you have a Nuxt 3 application in the `packages/app` directory you can do the same with NPM:

## A. `npx`

```
npx nuxi dev packages/app
```

```
npx nuxi build packages/app
```

## B. `package.json` and `npm run`

1. Change `package.json`:

    ```json5
    {
      "scripts": {
        "dev": "nuxi dev packages/app",
        "build": "nuxi build packages/app",
        // ...
      },
      // ...
    }
    ```

2. Run commands as usual:

    ```
    npm run dev
    ```
    
    ```
    npm run build
    ```

**Comment by hi94740** [comment]
Thank you @danielroe for the workaround!

**Comment by ffxsam** [comment]
Using yarn 3.x here, and I get a slightly different error:

```
$ yarn workspace nuxt build
Internal Error: nuxt@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at tF.getCandidates (/Users/samh/Code/vite-ssr-sst/.yarn/releases/yarn-3.2.0.cjs:437:4480)
    at wd.getCandidates (/Users/samh/Code/vite-ssr-sst/.yarn/releases/yarn-3.2.0.cjs:395:1281)
    at /Users/samh/Code/vite-ssr-sst/.yarn/releases/yarn-3.2.0.cjs:441:7765
    at Pg (/Users/samh/Code/vite-ssr-sst/.yarn/releases/yarn-3.2.0.cjs:394:11098)
    at le (/Users/samh/Code/vite-ssr-sst/.yarn/releases/yarn-3.2.0.cjs:441:7745)
```

But @danielroe's workaround works great. 👍

**Comment by antfu** [comment]
I will try to investigate

**Comment by antfu** [comment]
It will be fixed by
- https://github.com/unjs/nitro/pull/136
- https://github.com/nuxt/framework/pull/4488

**Comment by mklueh** [comment]
> ```js
>    "nuxt3": "3.0.0-27488831.368610e",
> ```

This as well as the other fixes won't work for me. I get

```
 ERROR  Cannot find module 'nuxt'
Require stack:
- /home/user/workspace/nuxt3-multi-page/apps/first-app/index.js

  Require stack:
  - index.js
  at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
  at Function.resolve (node:internal/modules/cjs/helpers:108:19)
  at Function._resolve [as resolve] (/home/user/workspace/nuxt3-multi-page/node_modules/jiti/dist/jiti.js:1:192841)
  at resolveModule (/home/user/workspace/nuxt3-multi-page/node_modules/@nuxt/kit/dist/index.mjs:236:29)
  at importModule (/home/user/workspace/nuxt3-multi-page/node_modules/@nuxt/kit/dist/index.mjs:259:24)
  at loadNuxt (/home/user/workspace/nuxt3-multi-page/node_modules/@nuxt/kit/dist/index.mjs:656:43)
  at async Object.invoke (/home/user/workspace/nuxt3-multi-page/node_modules/nuxi/dist/chunks/build.mjs:28:18)
  at async _main (/home/user/workspace/nuxt3-multi-page/node_modules/nuxi/dist/cli.mjs:46:20)

Warning: @nrwl/run-commands command "nuxt build" exited with non-zero status code
```

What is the difference between the "nuxt":"3.0.0" and  "nuxt3": "3.0.0-27488831.368610e" dependencies?

**Comment by mrauhu** [comment]
@mklueh, please, use Nuxt 3 RC1.

See: https://github.com/nuxt/framework/pull/4449

**Comment by mklueh** [comment]
@antfu 
Thanks. I'm using NX and I had to add

```
  "resolutions": {
    "nitropack": "0.3.7"
  },
```

to my package.json in order to get it working
