### ISSUE TITLE
Invalid value used as weak map key

### ISSUE THREAD

**Issue by productdevbook** [nuxt/framework#4227]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-27491748.3186841`
- Package Manager:  `yarn@1.22.10`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-twtnms

### Describe the bug

yarn dev and see problem

### Logs

```shell
[Vue warn]: Failed to resolve component: NuxtPage
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[nitro] [request error] Invalid value used as weak map key
  at WeakMap.set (<anonymous>)  
  at normalizePropsOptions (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3384:11)  
  at createComponentInstance (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6851:23)  
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:197:22)  
  at Module.ssrRenderComponent (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:629:12)  
  at eval (./.nuxt/dist/server/server.mjs:2977:37)  
  at renderFnWithContext (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:844:21)  
  at Module.ssrRenderSlot (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:641:21)  
  at _sfc_ssrRender (./.nuxt/dist/server/server.mjs:3102:25)  
  at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:269:13)
[Vue warn]: Failed to resolve component: NuxtPage
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[nitro] [dev] [unhandledRejection] TypeError: Invalid value used as weak map key
[Vue warn]: Failed to resolve component: NuxtPage
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[nitro] [dev] [unhandledRejection] TypeError: Invalid value used as weak map key
[Vue warn]: Failed to resolve component: NuxtPage
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[nitro] [dev] [unhandledRejection] TypeError: Invalid value used as weak map key
[Vue warn]: Failed to resolve component: NuxtPage
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[nitro] [dev] [unhandledRejection] TypeError: Invalid value used as weak map key
```

**Comment by Aareksio** [comment]
`page/` -> `pages/`

If you stumbled upon this issue in search, the exact error can also appear when you forget to include `{}` inside `defineNuxtConfig`. There are other ways to get it too, check your configuration and make sure all is according to docs.

**Comment by danielroe** [comment]
As @Aareksio says, `<NuxtPage>` is not available if you do not have a `pages/` folder in your source directory.

**Comment by tintin10q** [comment]
I have the same error now but with a `pages` directory in the source directory in nuxt 3

**Comment by Aareksio** [comment]
I haven't worked on nuxt 3 project for a while, but it can also happen when you use component that does not exist. I heard running `build` instead of `dev` prints a more precise error, maybe try that

**Comment by Phyllon** [comment]
Solved by adding this to `nuxt.config.ts`:
```
export default defineNuxtConfig({
    vue: {
      compilerOptions: {
        isCustomElement: (tag) => ['NuxtPage'].includes(tag),
      },
    },
  }
});
```

**Comment by tiendatleo** [comment]
Facing to the issue, too.
node v16.16.0
nuxt ^3.0.0-rc.6
