### ISSUE TITLE
`nuxi dev` does not work properly

### ISSUE THREAD

**Issue by kecrily** [nuxt/framework#4255]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.14.1`
- Nuxt Version:     `3.0.0-27494471.1091d45`
- Package Manager:  `pnpm@6.32.4`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

```
pnpm run nuxi dev
```

### Describe the bug

`nuxi dev` does not work properly

### Logs

```shell
ERROR  Failed to resolve force included dependency: vue                                                    
      20:50:20


 ERROR  Failed to resolve import "ufo" from "virtual:C:\Users\kecrily\Desktop\nuxt-app\.nuxt\paths.mjs". Does the file exist?


 ERROR  Failed to resolve import "vue" from "virtual:C:\Users\kecrily\Desktop\nuxt-app\.nuxt\components.plugin.mjs". Does the file exist?


 ERROR  Failed to resolve import "vue" from "app.vue". Does the file exist?                                 
      20:50:21

i Vite client warmed up in 8228ms                                                                           
      20:50:28
i Vite server warmed up in 5749ms                                                                           
      20:50:28
√ Vite server built in 8106ms                                                                               
      20:50:31

 ERROR  [worker reload] [worker init] Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'

  at new NodeError (node:internal/errors:371:5)
  at throwIfUnsupportedURLProtocol (node:internal/modules/esm/resolve:1035:11)
  at defaultResolve (node:internal/modules/esm/resolve:1105:3)
  at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:79:40)
  at link (node:internal/modules/esm/module_job:78:36)

√ Nitro built in 2325 ms                                                                                    
nitro 20:50:33

 ERROR  [worker reload] [worker init] Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'

  at new NodeError (node:internal/errors:371:5)
  at throwIfUnsupportedURLProtocol (node:internal/modules/esm/resolve:1035:11)
  at defaultResolve (node:internal/modules/esm/resolve:1105:3)
  at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:79:40)
  at link (node:internal/modules/esm/module_job:78:36)
```

**Comment by ghostchan** [comment]
I'm having the same error.

**Comment by genesem** [comment]
Operating System: Windows_NT
Node Version: v16.14.2 (LTS)
Yarn, 1.22
---

  "name": "nuxt3",
  "version": "3.0.0-27491748.3186841",
 -- all works fine.

when upgraded to:
  "name": "nuxt3",
  "version": "3.0.0-27494471.1091d45",

got an errors with 'nuxi dev':



'''√ Vite server built in 1235ms                                                                                 19:21:00

 ERROR  [worker reload] [worker init] Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'

  at new NodeError (node:internal/errors:371:5)
  at throwIfUnsupportedURLProtocol (node:internal/modules/esm/resolve:1035:11)
  at defaultResolve (node:internal/modules/esm/resolve:1105:3)
  at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:79:40)
  at link (node:internal/modules/esm/module_job:78:36)

√ Nitro built in 253 ms                                                                                 nitro 19:21:00

 ERROR  [worker reload] [worker init] Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'

  at new NodeError (node:internal/errors:371:5)
  at throwIfUnsupportedURLProtocol (node:internal/modules/esm/resolve:1035:11)
  at defaultResolve (node:internal/modules/esm/resolve:1105:3)
  at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:79:40)
  at link (node:internal/modules/esm/module_job:78:36)
'''

**Comment by danielroe** [comment]
Would you confirm whether you're still experiencing this on the latest version of Nuxt + nitro? (And if so, provide a reproduction?) 🙏

**Comment by kecrily** [comment]
It still exists in the latest version (`v3.0.0-27495135.4d1a6ba`), but the error log has changed

<details>
<summary>Details</summary>

```
 ERROR  Failed to resolve force included dependency: vue                                          09:40:20  


 ERROR  Failed to resolve import "ufo" from "virtual:C:\Users\kecrily\Desktop\nuxt-app\.nuxt\paths.mjs". Does the file exist?


 ERROR  Failed to resolve import "vue" from "virtual:C:\Users\kecrily\Desktop\nuxt-app\.nuxt\components.plugin.mjs". Does the file exist?


 ERROR  Failed to resolve import "vue" from "app.vue". Does the file exist?                       09:40:22  

i Vite server warmed up in 8628ms                                                                 09:40:31
i Vite client warmed up in 11316ms                                                                09:40:31
√ Vite server built in 11173ms                                                                    09:40:34

 ERROR  [worker reload] [worker init] Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'

  at new NodeError (node:internal/errors:371:5)
  at throwIfUnsupportedURLProtocol (node:internal/modules/esm/resolve:1035:11)
  at defaultResolve (node:internal/modules/esm/resolve:1105:3)
  at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:79:40)
  at link (node:internal/modules/esm/module_job:78:36)

√ Nitro built in 3247 ms                                                                    nitro 09:40:37

 ERROR  09:40:41 [vite] Internal server error: Failed to resolve import "ufo" from "virtual:C:\Users\kecrily\Desktop\nuxt-app\.nuxt\paths.mjs". Does the file exist?
  Plugin: vite:import-analysis
  File: virtual:C:/Users/kecrily/Desktop/nuxt-app/.nuxt/paths.mjs
  1  |  import { joinURL } from 'ufo'
     |                           ^
  2  |  const appConfig = {"baseURL":"/","buildAssetsDir":"/_nuxt/","assetsPath":{},"cdnURL":"","head":{"charset":"utf-8","viewport":"width=device-width, initial-scale=1","meta":[],"link":[],"style":[],"script":[]}} 
  3  |  export const baseURL = () => appConfig.baseURL
      at formatError (C:\Users\kecrily\Desktop\nuxt-app\node_modules\.pnpm\vite@2.9.1\node_modules\vite\dist\node\chunks\dep-611778e0.js:36296:46)
      at TransformContext.error (C:\Users\kecrily\Desktop\nuxt-app\node_modules\.pnpm\vite@2.9.1\node_modules\vite\dist\node\chunks\dep-611778e0.js:36292:19)
      at normalizeUrl (C:\Users\kecrily\Desktop\nuxt-app\node_modules\.pnpm\vite@2.9.1\node_modules\vite\dist\node\chunks\dep-611778e0.js:59668:26)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async TransformContext.transform (C:\Users\kecrily\Desktop\nuxt-app\node_modules\.pnpm\vite@2.9.1\node_modules\vite\dist\node\chunks\dep-611778e0.js:59817:57)
      at async Object.transform (C:\Users\kecrily\Desktop\nuxt-app\node_modules\.pnpm\vite@2.9.1\node_modules\vite\dist\node\chunks\dep-611778e0.js:36533:30)
      at async doTransform (C:\Users\kecrily\Desktop\nuxt-app\node_modules\.pnpm\vite@2.9.1\node_modules\vite\dist\node\chunks\dep-611778e0.js:55507:29)
```

</details>

The minimum reproduction is

```bash
pnpm dlx nuxi create
cd nuxi-app
pnpm i
pnpm dev
```

then open web

**Comment by danielroe** [comment]
Great. It seems this issue is resolved.

@kecrily Note that you currently need to use `--shamefully-hoist` with pnpm.

**Comment by Mnigos** [comment]
still got this error

<img width="725" alt="Screenshot 2022-05-10 at 17 56 45" src="https://user-images.githubusercontent.com/56691628/167671319-9b9dd820-7cb2-4e60-baaf-fba44fbfeb74.png">

**Comment by danielroe** [comment]
In that case, would you open a new issue with a reproduction?

**Comment by nicolay-zlobin** [comment]
I upgraded  node to latest lts v16.16.0 (was v16.13.1) and did fresh re-install with pnpm. Now error seems gone

**Comment by rifton007** [comment]
node v18.4.0
pnpm 7.5.1
---
remake `pnpm i --shamefully-hoist` after that it works
