### ISSUE TITLE
Error: Cannot find module "server.mjs"

### ISSUE THREAD

**Issue by HendrikJan** [nuxt/framework#4277]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v14.19.1`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `npm@8.6.0`
- Builder:          `webpack`
- User Config:      `rootDir`, `bridge`, `telemetry`, `nitro`, `head`, `css`, `plugins`, `components`, `buildModules`, `modules`, `compilerOptions`, `build`, `watchers`, `ssr`
- Runtime Modules:  `-`
- Build Modules:    `@nuxt/bridge@3.0.0-27495135.4d1a6ba`
------------------------------

### Reproduction

* Clone https://github.com/HendrikJan/nuxt-bridge-error-demo
* Run `npm install`
* Run `npx nuxi dev`
* Go to `http://localhost:3000/`
* See the error in your terminal and in your browser

### Describe the bug

Since a recent update I cannot get Nuxt to work anymore.
The application builds without errors, but when loading the page I get the 500 status with the error.

The error in the terminal is this:
```
✔ Builder initialized                                                                                                                                                                                  09:18:46
✔ Nuxt files generated                                                                                                                                                                                 09:18:46

✔ Client
  Compiled successfully in 3.12s

✔ Nitro built in 269 ms                                                                                                                                                                          nitro 09:18:50
ℹ Waiting for file changes                                                                                                                                                                             09:18:50
[nitro] [request error] Cannot find module '/home/haaiee/Projects/Docker/nuxt-bridge-error-demo/.nuxt/dist/server/server.mjs' imported from /home/haaiee/Projects/Docker/nuxt-bridge-error-demo/.nuxt/dev/index.mjs
  at new NodeError (internal/errors.js:322:7)  
  at finalizeResolution (internal/modules/esm/resolve.js:318:11)  
  at moduleResolve (internal/modules/esm/resolve.js:776:10)  
  at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:887:11)  
  at Loader.resolve (internal/modules/esm/loader.js:89:40)  
  at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)  
  at Loader.import (internal/modules/esm/loader.js:177:28)  
  at importModuleDynamically (internal/modules/esm/translators.js:114:35)  
  at exports.importModuleDynamicallyCallback (internal/process/esm_loader.js:30:14)  
  at ./.nuxt/dev/index.mjs:371:66
```

**Comment by danielroe** [comment]
Closing to follow in https://github.com/nuxt/framework/issues/886.

**Comment by HendrikJan** [comment]
@danielroe The other issue (#886) is for "build". This issue is when running "nuxi dev".

**Comment by DreadIsBack** [comment]
Confirm. Tested on 3.0.0-27496606.e43ba6e

I get this error when execute `npm run dev`:
` ERROR  Rollup error:  Could not load file:///D:/Work/GitHub/MyProj/MyProj.Web/frontend/.nuxt/dist/server/server.mjs (imported by node_modules/nuxt3/dist/core/runtime/nitro/renderer.mjs): ENOENT: no such file or directory, open 'D:\Work\GitHub\MyProj\MyProj.Web\frontend\file:\D:\Work\GitHub\NewExactWorld\ExactWorld.Web\frontend\.nuxt\dist\server\server.mjs'`

Looks lite file path incorrectly builded: `D:\Work\GitHub\MyProj\MyProj.Web\frontend\file:\D:\Work\GitHub\NewExactWorld\ExactWorld.Web\frontend\.nuxt\dist\server\server.mjs`

**Comment by crazymind** [comment]
Confirm. Same as here #4231 
Disable nitro brings other problems with it (as example $fetch is not available). Therefore not a solution.
