### ISSUE TITLE
Nuxi generate on Windows throws error during prerender

### ISSUE THREAD

**Issue by markusgeert** [nuxt/framework#4330]
### Environment

Windows 10
Node 16.14.1
Nuxt v3.0.0-27497374.59593a0 (latest)

### Reproduction

Locally, on windows:
```
npx nuxi init nuxt3-bug
cd nuxt3-bug
npm i
npx nuxi generate
```

### Describe the bug

The `nuxi generate` command throws a `paths must be valid file:// URLs` error when trying to generate a fresh Nuxt project on a Windows machine.

The error seems to be the same as the one described in #4256, but in a different context.

From what I could gather, this error is thrown by the nitropack/prerender function, where the import statement on line 30 receives an invalid filepath.

### Logs

```shell
Nuxt CLI v3.0.0-27497374.59593a0                                                                                                      
i Client built in 6453ms                                                                                                              
i Building server...                                                                                                                  
i Vite client warmed up in 7422ms                                                                                                     
√ Server built in 2504ms                                                                                                              
√ Generated public .output/public                                                                                               
start Preparing prerenderer...                                                                                                 

 ERROR  Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'

  at new NodeError (node:internal/errors:371:5)
  at throwIfUnsupportedURLProtocol (node:internal/modules/esm/resolve:1035:11)
  at defaultResolve (node:internal/modules/esm/resolve:1105:3)
  at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
  at ESMLoader.import (node:internal/modules/esm/loader:332:22)
  at importModuleDynamically (node:internal/modules/esm/translators:106:35)
  at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
  at prerender (/C:/PATHTOPROJECT/nuxt3-bug/node_modules/nitropack/dist/chunks/prerender.mjs:2153:39)
  at async /C:/PATHTOPROJECT/nuxt3-bug/node_modules/nuxt3/dist/index.mjs:1215:9
```

**Comment by aesdotjs** [comment]
Really need this to be able to debug generation on windows dev environnement

**Comment by danielroe** [comment]
This is no longer reproducible on latest Nuxt + nitro.

**Comment by aesdotjs** [comment]
Great! thank you Daniel ♥


Le jeu. 15 sept. 2022 à 14:55, Daniel Roe ***@***.***> a
écrit :
