### ISSUE TITLE
Build fails for nitro preset Cloudflare

### ISSUE THREAD

**Issue by marshallswain** [nuxt/framework#4403]
### Environment

With @pinia/nuxt installed, Nitro/Cloudflare build fails due to an unenv proxy-related error.

### Reproduction

I've installed @pinia/nuxt and pinia in this StackBlitz reproduction.  Then run the build scripts.

https://stackblitz.com/edit/github-8cjrqx?file=package.json

- `npm run build` completes the build without error
- `npm run build:cloudflare` fails with the above error. 

I don't have enough knowledge of the internals to know why this only fails with the nitro cloudflare preset.

### Describe the bug

Nitro/Cloudflare build fails with the following error message:

```
Nuxt CLI v3.0.0-27501460.04a72f8                                                                                           20:56:46
ℹ Client built in 1003ms                                                                                                   20:56:49
ℹ Vite client warmed up in 1014ms                                                                                          20:56:49
ℹ Building server...                                                                                                       20:56:49
✔ Server built in 284ms                                                                                                    20:56:49
✔ Generated public .output/public                                                                                    nitro 20:56:49
start Building server...                                                                                             nitro 20:56:49

 ERROR  Rollup error: 'setupDevtoolsPlugin' is not exported by node_modules/unenv/runtime/mock/proxy.mjs, imported by node_modules/pinia/dist/pinia.mjs


 ERROR  'setupDevtoolsPlugin' is not exported by node_modules/unenv/runtime/mock/proxy.mjs, imported by node_modules/pinia/dist/pinia.mjs

  at error (node_modules/rollup/dist/es/shared/rollup.js:1829:30)
  at Module.error (node_modules/rollup/dist/es/shared/rollup.js:12390:16)
  at Module.traceVariable (node_modules/rollup/dist/es/shared/rollup.js:12748:29)
  at ModuleScope.findVariable (node_modules/rollup/dist/es/shared/rollup.js:11378:39)
  at FunctionScope.findVariable (node_modules/rollup/dist/es/shared/rollup.js:6346:38)
  at ChildScope.findVariable (node_modules/rollup/dist/es/shared/rollup.js:6346:38)
  at Identifier.bind (node_modules/rollup/dist/es/shared/rollup.js:7637:40)
  at CallExpression.bind (node_modules/rollup/dist/es/shared/rollup.js:5211:23)
  at CallExpression.bind (node_modules/rollup/dist/es/shared/rollup.js:8819:15)
  at ExpressionStatement.bind (node_modules/rollup/dist/es/shared/rollup.js:5211:23)
```

### Additional context

Maybe related issue?

https://github.com/nuxt/framework/issues/4154

**Comment by danielroe** [comment]
This should be resolved as of RC5. Please let me know if not and I can reopen.
