### ISSUE TITLE
`abortNavigation` causing production server crash

### ISSUE THREAD

**Issue by antfu** [nuxt/framework#4418]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-27501460.04a72f8`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-eblmj9?file=middleware%2Findex.global.ts

### Describe the bug

- npm run build
- npm run start

### Logs

```shell
H3Error: Route navigation aborted: /
    at createError (file:///home/projects/github-eblmj9/.output/server/chunks/app/server.mjs:2584:15)
    at eval (file:///home/projects/github-eblmj9/.output/server/chunks/app/server.mjs:3881:35) {
  statusCode: 500,
  statusMessage: 'Route navigation aborted: /'
}
```

**Comment by dungonfq** [comment]
Same issue, it stopped my server while running `npm run start` immediately 😓

<img width="955" alt="abortNavigation-stop-server" src="https://user-images.githubusercontent.com/57652048/163971008-c7d66fb5-36e3-4175-bff1-2e9d443a75ab.png">

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/framework/issues/3242...
