### ISSUE TITLE
Cannot start nuxt:  Cannot find module 'nuxt'

### ISSUE THREAD

**Issue by weleo** [nuxt/framework#4457]
### Environment

- Operating System: `Darwin`
- Node Version:     `v17.7.1`
- Nuxt Version:     `3.0.0-27507520.e006c56`
- Package Manager:  `npm@8.5.2`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

`npx nuxi init` with `nuxt3: "3.0.0-27507520.e006c56"`

### Describe the bug

since `3.0.0-27507520.e006c56`: `Error: Cannot start nuxt:  Cannot find module 'nuxt'`

- Every commit before works as intended.
- Every commit after throws the same error.

### Logs

```
ERROR  Cannot start nuxt:  Cannot find module 'nuxt'
Require stack:
- /Users/weleo/nuxt-app/index.js

  Require stack:
  - index.js
  at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
  at Function.resolve (node:internal/modules/cjs/helpers:108:19)
  at Function._resolve [as resolve] (node_modules/jiti/dist/jiti.js:1:192841)
  at resolveModule (node_modules/@nuxt/kit/dist/index.mjs:236:29)
  at importModule (node_modules/@nuxt/kit/dist/index.mjs:259:24)
  at loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:656:43)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6733:23)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6777:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:46:20)
```

**Comment by danielroe** [comment]
apologies for the inconvenience - things are happening in the background 😉

**Comment by tiborpino** [comment]
Also experienced today. Removed yarn.lock and node_modules directory. Then fresh yarn install solved the problem.

**Comment by itzaks** [comment]
> Also experienced today. Removed yarn.lock and node_modules directory. Then fresh yarn install solved the problem.

Tried this but it's still failing on build on Netlify for me.

**Comment by zelid** [comment]
Same thing noticed just now.

```
Nuxt CLI v3.0.0-rc.0-27507653.98586bc                                                                                                 15:27:58
                                                                                                                                      15:27:58
  > Local:    http://localhost:3000/
  > Network:  http://172.16.120.167:3000/


 ERROR  Cannot start nuxt:  Cannot find module 'nuxt'                                                                                 15:27:58
Require stack:
- /Users/alex/Workspace/wpoint/wpoint/index.js

  Require stack:
  - index.js
  at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
  at Function.resolve (node:internal/modules/cjs/helpers:108:19)
  at Function._resolve [as resolve] (node_modules/.pnpm/jiti@1.13.0/node_modules/jiti/dist/jiti.js:1:192841)
  at resolveModule (node_modules/.pnpm/@nuxt+kit-edge@3.0.0-rc.0-27507653.98586bc/node_modules/@nuxt/kit-edge/dist/index.mjs:236:29)
  at importModule (node_modules/.pnpm/@nuxt+kit-edge@3.0.0-rc.0-27507653.98586bc/node_modules/@nuxt/kit-edge/dist/index.mjs:259:24)
  at loadNuxt (node_modules/.pnpm/@nuxt+kit-edge@3.0.0-rc.0-27507653.98586bc/node_modules/@nuxt/kit-edge/dist/index.mjs:656:43)
  at async load (node_modules/.pnpm/nuxi-edge@3.0.0-rc.0-27507653.98586bc/node_modules/nuxi-edge/dist/chunks/dev.mjs:6733:23)
  at async Object.invoke (node_modules/.pnpm/nuxi-edge@3.0.0-rc.0-27507653.98586bc/node_modules/nuxi-edge/dist/chunks/dev.mjs:6777:5)
  at async _main (node_modules/.pnpm/nuxi-edge@3.0.0-rc.0-27507653.98586bc/node_modules/nuxi-edge/dist/cli.mjs:46:20)
```

**Comment by Lmmmmmm-bb** [comment]
> Also experienced today. Removed yarn.lock and node_modules directory. Then fresh yarn install solved the problem.

I am using pnpm@6.32.8 and it doesn't work for me.

**Comment by y-migita** [comment]
> Also experienced today. Removed yarn.lock and node_modules directory. Then fresh yarn install solved the problem.
I get the same error in my local environment with version `3.0.0-rc.0-27507653.98586bc`.

**Comment by pi0** [comment]
Please follow the [instructions here](https://github.com/nuxt/framework/discussions/2883) in order to update nuxt3 dependency. Sorry for inconveniences during rc release.

**Comment by andysay** [comment]
> Please follow the [instructions here](https://github.com/nuxt/framework/discussions/2883) in order to update nuxt3 dependency. Sorry for the inconvenience during the RC release.

after change nuxt3 on nuxt now have >

Cannot start nuxt:  Cannot find module '@nuxt/vite-builder'

**Comment by danielroe** [comment]
If you're still encountering this issue after following the instructions above, please let me know and I'll reopen.
