### ISSUE TITLE
Can't add Vue files as templates with Vite

### ISSUE THREAD

**Issue by danielroe** [nuxt/framework#454]
If you run something like:
```js
addTemplate({
  filename: 'error.vue',
  src: resolve(runtimeDir, 'error.vue')
})
```

Vite will throw the following error:
```
[vite:import-analysis] Parse error @:2:40
file: virtual:/framework/examples/with-errors/.nuxt/error.vue:2:39
1: <template>
2:   <div> page, thank you very much</div>
                                          ^
3: </template>
[error] Cannot start nuxt:  Error: Parse error @:2:40
    at parse$e (/framework/node_modules/vite/dist/node/chunks/dep-c1a9de64.js:28927:353)
    at Object.transform (/framework/node_modules/vite/dist/node/chunks/dep-c1a9de64.js:29158:27) {
  idx: 50,
  pos: 50,
  loc: {
    column: 39,
    file: '\x00virtual:/framework/examples/with-errors/.nuxt/error.vue',
    line: 2
  },
  frame: '1: <template>\n' +
    '2:   <div> page, thank you very much</div>\n' +
    '                                          ^\n' +
    '3: </template>',
  id: '\x00virtual:/framework/examples/with-errors/.nuxt/error.vue',
  hook: 'transform',
  code: 'PLUGIN_ERROR',
  plugin: 'vite:import-analysis',
  watchFiles: [
    '/framework/packages/nuxt3/src/app/entry.ts',
    '/framework/packages/nuxt3/src/app/index.ts',
    '\x00virtual:/framework/examples/with-errors/.nuxt/css.mjs',
    '\x00virtual:/framework/examples/with-errors/.nuxt/plugins/server.mjs',
    '\x00virtual:/framework/examples/with-errors/.nuxt/app.mjs',
    '/framework/packages/nuxt3/src/meta/runtime/lib/vueuse-head.plugin.ts',
    '/framework/packages/nuxt3/src/meta/runtime/plugin.ts',
    '/framework/packages/nuxt3/src/pages/runtime/router.ts',
    '/framework/packages/nitro/src/runtime/app/nitro.client.mjs',
    '/framework/packages/nuxt3/src/pages/runtime/app.vue',
    '\x00virtual:/framework/examples/with-errors/.nuxt/global-imports.mjs',
    '/framework/packages/nuxt3/src/app/plugins/preload.server.ts',
    '/framework/packages/nuxt3/src/meta/runtime/index.ts',
    '/framework/node_modules/ohmyfetch/dist/index.mjs',
    '/framework/packages/nuxt3/src/app/nuxt.ts',
    '/framework/packages/nuxt3/src/app/composables/index.ts',
    '/framework/node_modules/@vueuse/head/dist/index.mjs',
    '/framework/node_modules/vue-router/dist/vue-router.esm-bundler.js',
    '/framework/packages/nuxt3/src/pages/runtime/page.vue',
    '/framework/packages/nuxt3/src/pages/runtime/layout.ts',
    '/framework/packages/nuxt3/src/meta/runtime/components.ts',
    '/framework/packages/nuxt3/src/meta/runtime/composables.ts',
    '\x00virtual:/framework/examples/with-errors/.nuxt/routes.mjs',
    '\x00virtual:/framework/examples/with-errors/.nuxt/meta.config.mjs',
    '/framework/examples/with-errors/pages/_error.vue',
    '/framework/examples/with-errors/pages/index.vue',
    '/framework/node_modules/destr/dist/index.mjs',
    '/framework/node_modules/ohmyfetch/node_modules/ufo/dist/index.mjs',
    '/framework/packages/nuxt3/src/app/composables/errors.ts',
    '\x00virtual:/framework/examples/with-errors/.nuxt/error.vue'
  ]
}
```

**Comment by richardeschloss** [comment]
That's cool but I think the `components:dirs` hook would be even easier to use?
