### ISSUE TITLE
 Cannot find package '/usr/src/app/.output/server/node_modules/ufo

### ISSUE THREAD

**Issue by dungonfq** [nuxt/framework#4585]
### Environment

Production & Staging

### Reproduction

Cannot reproduce

### Describe the bug

Im trying to upgrade `"nuxt": "^3.0.0-rc.1"` in my application on Staging & Production. We use Docker + Jenkins to build & deploy. The application was built succesfully. But when I access the site, it loads infinitely and then stops the server.

Error log:
```
> fe-customer-account@1.0.0 start
> node .output/server/index.mjs

node:internal/process/esm_loader:94
    internalBinding('errors').triggerUncaughtException(
                              ^
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '/usr/src/app/.output/server/node_modules/ufo/' imported from /usr/src/app/.output/server/index.mjs
Did you mean to import ufo/dist/index.cjs?
    at new NodeError (node:internal/errors:371:5)
    at legacyMainResolve (node:internal/modules/esm/resolve:336:9)
    at packageResolve (node:internal/modules/esm/resolve:919:14)
    at moduleResolve (node:internal/modules/esm/resolve:978:18)
    at defaultResolve (node:internal/modules/esm/resolve:1080:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:79:40)
    at link (node:internal/modules/esm/module_job:78:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

1. As mentioned in https://github.com/nuxt/framework/discussions/4479, we need to remove `.nuxt`, `package.lock.json`, `yarn.lock` and `node_modules`. But I'm not confident on this solution since I have no control on Production & Staging project folder.
2. Additionally, a possible cause can be from my server middleware. I'm using runtime config to create proxy middleware
```js
import createProxy from '~/services/server/proxy'

const config = useRuntimeConfig()
const proxyMiddleware = createProxy(config.public.API_HOST)

/**
 * @param {import('http').IncomingMessage} req
 * @param {import('http').ServerResponse} res
 * @param {Function} next
 */
export default async (req, res) => {
  // Workaround for h3 not awaiting next.
  await new Promise<void>((resolve, reject) => {
    const next = (err?: unknown) => {
      if (err) {
        reject(err)
      } else {
        resolve()
      }
    }

    // @ts-expect-error -- incompatible types express.Request and http.IncomingMessage. This still works though.
    proxyMiddleware(req, res, next)
  })
}

``` 

Do you guys have any idea about this missing module `ufo`? I would like to try as many solutions as possible.

### Additional context

Btw, I really happy Nuxt 3 was ready to release. My appreciation & big thanks to the team <3

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏

**Comment by dungonfq** [comment]
@danielroe sorry I can't. It only happens on Staging + Production which is deployed by Jenkin + Docker. I have no problem with the new Nuxt version on my local + feature envs. Seem like caching is root cause

**Comment by danielroe** [comment]
Yes, when you rebuild the `.output` folder is entirely regenerated. Do you have any more information about your deployment environment or process? When you say you can't ensure that lockfile & node_modules are cleared, that raises a number of questions for me. Presumably you could run build the Dockerfile locally? Does that make a difference?

**Comment by dungonfq** [comment]
Thank @danielroe, I will touch base with DevOps to found more evidences. Btw, for now I can show u our log files.

1.
[jenkin-build-ouput.txt](https://github.com/nuxt/framework/files/8554218/jenkin-build-ouput.txt)
The build stage starts from `[Pipeline] { (Build And Publish)`

2. Dockerfile
```
FROM node:16.14.2-alpine

# Create app directory
WORKDIR /usr/src/app
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./
COPY yarn.lock ./

# Remove old build
RUN rm -rf node_modules .nuxt .output

# If you are building your code for production
# RUN npm install --only=production
RUN yarn install
#RUN npm install acorn-dynamic-import --save-dev
# Bundle app source
COPY . .
RUN yarn build
ENV HOST 0.0.0.0
ENV PORT 3000
EXPOSE 3000
CMD [ "yarn", "start" ]
```

4. Related Jenkins stages
```
stage("Build And Publish") {
            when {
                branch "main"
                //tag "*"
            }
            steps {
                withCredentials([[
                $class: "AmazonWebServicesCredentialsBinding",
                credentialsId: "jenkins-ecr-user",
                accessKeyVariable: "AWS_ACCESS_KEY_ID",
                secretKeyVariable: "AWS_SECRET_ACCESS_KEY"
            ]]) {
                script {
                    sh '''
                        $(aws ecr get-login --no-include-email --region eu-central-1)
                        docker build -t ${IMAGE_NAME}:${GIT_SHORT} -f Dockerfile .
                        docker push ${IMAGE_NAME}:${GIT_SHORT}
                    '''
                }
            }
            }
        }

        
        stage("Staging Deploy") {
            when {
                branch "main"
            }
            steps {
                withCredentials([
                    string(credentialsId: 'CUSTACCOUNT_STAGING_GTM_ID', variable: 'STAGING_GTM_ID'),
                ]){
                    withAWS(role:'eks-admin', roleAccount:'589767178493', credentials:'jenkins-ec2-user') {
                        script {
                            sh '''
                                aws eks --region eu-central-1 update-kubeconfig --name cluster-staging
                                helm upgrade --install --namespace development fe-customer-account  ./deployment \
                                    --set env.api_host=http://backend-application.sandbox \
                                    --set env.default_locale=de \
                                    --set env.gtm_id=GTM-NLW8SSG \
                                    --set env.user_centrics_id=H1OWkToWN \
                                    --set image.tag=${GIT_SHORT}
                            '''
                        }
                    }
                }
                office365ConnectorSend (
                    color: '#00FF00',
                    message: "Deploy of fe-customer-account ${GIT_SHORT} successful on Staging",
                    webhookUrl: 'https://roadsurfer.webhook.office.com/webhookb2/8d75c9f5-c5d0-49dc-8d22-5a32f840a8c7@573ae0ae-0a5d-4098-8813-0f140a1c85da/JenkinsCI/bc838cfcc93b4690a716e3fb636f5fc5/686da0f9-7f13-4d6b-86e0-afa1977e8c24',
                    factDefinitions:[
                        [ name: "Commit Message", template: "${COMMIT_MESSAGE}"],
                    ]
                )

            }
            post {
                always {
                    jiraSendDeploymentInfo site: 'roadsurfer.atlassian.net', environmentId: 'staging-eu', environmentName: 'Staging EU', environmentType: 'staging'
                }
            }
        }
 ```

`Presumably, you could run build the Dockerfile locally? Does that make a difference?`
- Yes, I also try on another environment + Jenkin pipeline. The project works well, no issue with nuxt version `3.0.0-rc.1`

**Comment by pi0** [comment]
@dungonfq Can you please possibly inspect the docker image to ensure `.output/server/node_moduls` is included?

**Comment by falstack** [comment]
@pi0 
``` sh
[GET] /
09:48:21:61
Function Status:
None
Edge Status:
500
Duration:
42.06 ms
Init Duration:
N/A
Memory Used:
14 MB
ID:
hkg1::srmnm-1650937701903-d04bac03b09d
User Agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
2022-04-26T01:48:21.791Z	undefined	ERROR	Error [ERR_INVALID_PACKAGE_CONFIG]: Invalid package config /var/task/node_modules/ufo/package.json while importing "ufo" from /var/task/index.mjs. Unexpected token } in JSON at position 976
    at new NodeError (internal/errors.js:322:7)
    at getPackageConfig (internal/modules/esm/resolve.js:145:11)
    at packageResolve (internal/modules/esm/resolve.js:719:27)
    at moduleResolve (internal/modules/esm/resolve.js:773:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:887:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:76:40)
    at link (internal/modules/esm/module_job.js:75:36) {
  code: 'ERR_INVALID_PACKAGE_CONFIG'
}
RequestId: 570db881-881c-4f64-b9e0-e14572ca495c Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

**Comment by zernonia** [comment]
I had similar error earlier. Turns out that my favicon wasn't configured properly. I fix it by updating my `nuxt.config.ts`.
Not sure if it provides any insight to your issue.

![image](https://user-images.githubusercontent.com/59365435/165213433-753c4454-c633-469b-8ba9-047fb4a141f9.png)

**Comment by dungonfq** [comment]
Hi @danielroe @pi0 , thank you for supporting me on this issue.

I found the root cause in Jenkinsfile. Since I'm running both Test + Build & Deploy, the pipeline run `yarn install` multiple times. Therefore, my `node_modules`, `.nuxt`, `.output` was cached.

Here is my Jenkinsfile, if I comment 2 first stages (Build test & Test) => my staging work well without any problem.
```
pipeline {
    agent any
    environment {
        REPOSITORY_NAME = "fe-customer-account"
        ECR_REGISTRY = "722465641242.dkr.ecr.eu-central-1.amazonaws.com/"
        USER_CENTRICS_ID="H1OWkToWN"
        IMAGE_NAME = "${ECR_REGISTRY}${REPOSITORY_NAME}"
        GIT_SHORT = sh (script: '''git log -1 --pretty=format:%h''', returnStdout:true)
        COMMIT_MESSAGE = sh (script: '''git log -1 --pretty=format:%s''', returnStdout:true)
    }
    stages {
        // stage("Build test") {
        //     parallel {
        //         stage('Test image') {
        //             steps{
        //                 script {
        //                     sh '''
        //                         docker build -t ${IMAGE_NAME}:test -f Dockerfile .
        //                     '''
        //                 }
        //             }
        //         }
        //     }
        // }

        // stage('Test') {
        //     steps {
        //         script {
        //             docker.image('${IMAGE_NAME}:test').inside() {
        //                 sh '''
        //                     npm install
        //                     npm run prepare
        //                     npm run test
        //                 '''
        //             }
        //         }
        //     }
        //     post {
        //         always {
        //             jiraSendBuildInfo site: 'roadsurfer.atlassian.net'
        //         }
        //     }
        // }

        stage("Build And Publish") {
            when {
                branch "main"
                //tag "*"
            }
            steps {
                withCredentials([[
                $class: "AmazonWebServicesCredentialsBinding",
                credentialsId: "jenkins-ecr-user",
                accessKeyVariable: "AWS_ACCESS_KEY_ID",
                secretKeyVariable: "AWS_SECRET_ACCESS_KEY"
            ]]) {
                script {
                    sh '''
                        $(aws ecr get-login --no-include-email --region eu-central-1)
                        docker build -t ${IMAGE_NAME}:${GIT_SHORT} -f Dockerfile .
                        docker push ${IMAGE_NAME}:${GIT_SHORT}
                    '''
                }
            }
            }
        }

        
        stage("Staging Deploy") {
            when {
                branch "main"
            }
            steps {
                withCredentials([
                    string(credentialsId: 'CUSTACCOUNT_STAGING_GTM_ID', variable: 'STAGING_GTM_ID'),
                ]){
                    withAWS(role:'eks-admin', roleAccount:'589767178493', credentials:'jenkins-ec2-user') {
                        script {
                            sh '''
                                aws eks --region eu-central-1 update-kubeconfig --name cluster-staging
                                helm upgrade --install --namespace development fe-customer-account  ./deployment \
                                    --set env.api_host=http://backend-application.sandbox \
                                    --set env.default_locale=de \
                                    --set env.gtm_id=GTM-NLW8SSG \
                                    --set env.user_centrics_id=H1OWkToWN \
                                    --set image.tag=${GIT_SHORT}
                            '''
                        }
                    }
                }
                office365ConnectorSend (
                    color: '#00FF00',
                    message: "Deploy of fe-customer-account ${GIT_SHORT} successful on Staging",
                    webhookUrl: 'https://roadsurfer.webhook.office.com/webhookb2/8d75c9f5-c5d0-49dc-8d22-5a32f840a8c7@573ae0ae-0a5d-4098-8813-0f140a1c85da/JenkinsCI/bc838cfcc93b4690a716e3fb636f5fc5/686da0f9-7f13-4d6b-86e0-afa1977e8c24',
                    factDefinitions:[
                        [ name: "Commit Message", template: "${COMMIT_MESSAGE}"],
                    ]
                )

            }
            post {
                always {
                    jiraSendDeploymentInfo site: 'roadsurfer.atlassian.net', environmentId: 'staging-eu', environmentName: 'Staging EU', environmentType: 'staging'
                }
            }
        }

        stage("Verify Prod Deploy") {
            when {
                branch "main"
            }
            steps {
                timeout(time: 1, unit: 'HOURS') {
                    input message: 'Deploy to Production?', ok: 'Deploy'
                }
            }
        }

        stage("Production Deploy") {
            when {
                branch "main"
            }
            steps {
                withCredentials([
                    string(credentialsId: 'CUSTACCOUNT_STAGING_GTM_ID', variable: 'STAGING_GTM_ID')
                ]){
                    withAWS(role:'eks-admin-full-prod', roleAccount:'589767178493', credentials:'jenkins-ec2-user') {
                        script {
                            sh '''
                                aws eks --region eu-central-1 update-kubeconfig --name cluster-prod
                                helm upgrade --install --namespace production -f ./deployment/values-prod.yaml fe-customer-account ./deployment \
                                    --set env.api_host=http://backend-application \
                                    --set env.default_locale=de \
                                    --set env.gtm_id=GTM-P7CPWW \
                                    --set env.user_centrics_id=H1OWkToWN \
                                    --set image.tag=${GIT_SHORT}
                            '''
                        }
                    }
                }
                office365ConnectorSend (
                    color: '#00FF00',
                    message: "Deploy of fe-customer-account ${GIT_SHORT} successful on Production",
                    webhookUrl: 'https://roadsurfer.webhook.office.com/webhookb2/8d75c9f5-c5d0-49dc-8d22-5a32f840a8c7@573ae0ae-0a5d-4098-8813-0f140a1c85da/JenkinsCI/2a9c2f9977374998a46eb384c094ca62/686da0f9-7f13-4d6b-86e0-afa1977e8c24',
                    factDefinitions:[
                        [ name: "Commit Message", template: "${COMMIT_MESSAGE}"],
                    ]
                )
            }
            post {
                always {
                    jiraSendDeploymentInfo site: 'roadsurfer.atlassian.net', environmentId: 'prod-eu', environmentName: 'Production EU', environmentType: 'production'
                }
            }
        }
    }

    post {
        always {
            sh '''
                docker rmi -f ${IMAGE_NAME}:test
                docker rmi -f ${IMAGE_NAME}:${GIT_SHORT}
            '''
            cleanWs()
        }
    }
}
```

In short, nuxt `v3.0.0-rc.1` was upgraded successfully 🙌🏻

**Comment by pi0** [comment]
Thanks for the update @dungonfq and the nice hearing upgrade is now success! I've made #4632 nuxt could be better to detect such collision.
