### ISSUE TITLE
Get many WARN  message when build project

### ISSUE THREAD

**Issue by chenly** [nuxt/framework#4638]
### Environment

Nuxt project info:                                                                                                                  01:42:51

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `npm@8.5.2`
- Builder:          `vite`
- User Config:      `app`, `css`, `buildModules`, `build`, `windicss`
- Runtime Modules:  `-`
- Build Modules:    `nuxt-windicss@2.3.1`
------------------------------

### Reproduction

npm run build

### Describe the bug

Get many WARN  message when build project ( A init project)

### Logs

```shell
> build
> nuxt build

Nuxt CLI v3.0.0-rc.1                                                                                                                01:34:07
i Vite client warmed up in 1998ms                                                                                                   01:34:14
i Client built in 5703ms                                                                                                            01:34:18
i Building server...                                                                                                                01:34:18
√ Server built in 3314ms                                                                                                            01:34:21
√ Generated public .output/public                                                                                             nitro 01:34:21
start Building server...                                                                                                      nitro 01:34:21

 WARN  'node:stream' is imported by node_modules/node-fetch/src/index.js, but could not be resolved – treating it as an external dependency


 WARN  'node:http' is imported by node_modules/node-fetch/src/index.js, but could not be resolved – treating it as an external dependency


 WARN  'node:zlib' is imported by node_modules/node-fetch/src/index.js, but could not be resolved – treating it as an external dependency


 WARN  'node:https' is imported by node_modules/node-fetch/src/index.js, but could not be resolved – treating it as an external dependency


 WARN  'node:buffer' is imported by node_modules/node-fetch/src/index.js, but could not be resolved – treating it as an external dependency


 WARN  'node:http' is imported by node_modules/node-fetch/src/headers.js, but could not be resolved – treating it as an external dependency


 WARN  'node:stream' is imported by node_modules/node-fetch/src/body.js, but could not be resolved – treating it as an external dependency


 WARN  'node:fs' is imported by node_modules/fetch-blob/from.js, but could not be resolved – treating it as an external dependency  01:34:26


 WARN  'node:buffer' is imported by node_modules/node-fetch/src/body.js, but could not be resolved – treating it as an external dependency


 WARN  'node:path' is imported by node_modules/fetch-blob/from.js, but could not be resolved – treating it as an external dependency


 WARN  'node:util' is imported by node_modules/node-fetch/src/body.js, but could not be resolved – treating it as an external dependency


 WARN  'node:util' is imported by node_modules/node-fetch/src/request.js, but could not be resolved – treating it as an external dependency


 WARN  'node:util' is imported by node_modules/node-fetch/src/headers.js, but could not be resolved – treating it as an external dependency


 WARN  'node:url' is imported by node_modules/node-fetch/src/request.js, but could not be resolved – treating it as an external dependency


 WARN  'node:net' is imported by node_modules/node-fetch/src/utils/referrer.js, but could not be resolved – treating it as an external dependency

start Writing server bundle...                                                                                                nitro 01:34:29
√ Server built                                                                                                                nitro 01:34:30
  ├─ .output/server/package.json (422 B) (224 B gzip)
  ├─ .output/server/index.mjs.map (105 B) (100 B gzip)
  ├─ .output/server/index.mjs (392 B) (225 B gzip)
  ├─ .output/server/chunks/vue3.mjs.map (359 B) (238 B gzip)
  ├─ .output/server/chunks/vue3.mjs (317 B) (226 B gzip)
  ├─ .output/server/chunks/static.mjs.map (2.24 kB) (609 B gzip)
  ├─ .output/server/chunks/static.mjs (5.39 kB) (1.72 kB gzip)
  ├─ .output/server/chunks/server.mjs.map (409 kB) (48.1 kB gzip)
  ├─ .output/server/chunks/server.mjs (423 kB) (78 kB gzip)
  ├─ .output/server/chunks/renderer.mjs.map (30 kB) (4.82 kB gzip)
  ├─ .output/server/chunks/renderer.mjs (23.5 kB) (6.51 kB gzip)
  ├─ .output/server/chunks/node-server.mjs.map (15.2 kB) (2.82 kB gzip)
  ├─ .output/server/chunks/node-server.mjs (12.5 kB) (4.06 kB gzip)
  ├─ .output/server/chunks/index.mjs.map (1.81 MB) (84.2 kB gzip)
  ├─ .output/server/chunks/index.mjs (405 kB) (92.2 kB gzip)
  ├─ .output/server/chunks/client.manifest.mjs.map (2.22 kB) (465 B gzip)
  └─ .output/server/chunks/client.manifest.mjs (2.57 kB) (532 B gzip)
Σ Total size: 3.67 MB (462 kB gzip)
√ You can preview this build using node .output/server/index.mjs                                                              nitro 01:34:30
```

**Comment by pi0** [comment]
Would you please provide a minimal reproduction? 🙏🏼 Does it happens with a fresh nuxt 3 project as well?

**Comment by chenly** [comment]
yes happen with a fresh nuxt 3 project

**Comment by danielroe** [comment]
I can confirm as well, but only on windows. 👍

**Comment by Beiri22** [comment]
The same happens with a project here, only on windows.

**Comment by kathleeens** [comment]
That happened to me too. On windows

**Comment by psycho-neon** [comment]
This happens to me as well. Fresh project -> then proceed with building the project without modifying anything.

**Comment by aslero** [comment]
Who solved this problem?

I have one like this:

```
npm run build

> build
> nuxt build

Nuxt CLI v3.0.0-rc.1                                                                                                                                                                                      15:46:50  
i Vite client warmed up in 2914ms                                                                                                                                                                         15:46:57  
i Client built in 3611ms                                                                                                                                                                                  15:46:58  
i Building server...                                                                                                                                                                                      15:46:58  
√ Server built in 707ms                                                                                                                                                                                   15:46:58  
√ Generated public .output/public                                                                                                                                                                   nitro 15:46:58  
start Building server...                                                                                                                                                                            nitro 15:46:58  

 WARN  'node:http' is imported by node_modules/node-fetch/src/index.js, but could not be resolved – treating it as an external dependency                                                                 15:47:02


 WARN  'node:buffer' is imported by node_modules/node-fetch/src/index.js, but could not be resolved – treating it as an external dependency                                                               15:47:02


 WARN  'node:zlib' is imported by node_modules/node-fetch/src/index.js, but could not be resolved – treating it as an external dependency                                                                 15:47:02


 WARN  'node:stream' is imported by node_modules/node-fetch/src/index.js, but could not be resolved – treating it as an external dependency                                                               15:47:02


 WARN  'node:stream' is imported by node_modules/node-fetch/src/body.js, but could not be resolved – treating it as an external dependency                                                                15:47:02


 WARN  'node:path' is imported by node_modules/fetch-blob/from.js, but could not be resolved – treating it as an external dependency                                                                      15:47:02


 WARN  'node:fs' is imported by node_modules/fetch-blob/from.js, but could not be resolved – treating it as an external dependency                                                                        15:47:02


 WARN  'node:https' is imported by node_modules/node-fetch/src/index.js, but could not be resolved – treating it as an external dependency                                                                15:47:02


 WARN  'node:buffer' is imported by node_modules/node-fetch/src/body.js, but could not be resolved – treating it as an external dependency                                                                15:47:02


 WARN  'node:http' is imported by node_modules/node-fetch/src/headers.js, but could not be resolved – treating it as an external dependency                                                               15:47:02  


 WARN  'node:util' is imported by node_modules/node-fetch/src/body.js, but could not be resolved – treating it as an external dependency                                                                  15:47:02  


 WARN  'node:util' is imported by node_modules/node-fetch/src/request.js, but could not be resolved – treating it as an external dependency                                                               15:47:02  


 WARN  'node:util' is imported by node_modules/node-fetch/src/headers.js, but could not be resolved – treating it as an external dependency                                                               15:47:02  


 WARN  'node:url' is imported by node_modules/node-fetch/src/request.js, but could not be resolved – treating it as an external dependency                                                                15:47:02  


 WARN  'node:net' is imported by node_modules/node-fetch/src/utils/referrer.js, but could not be resolved – treating it as an external dependency                                                         15:47:02  


 ERROR  Rollup error: Unexpected character '@' (Note that you need plugins to import files that are not JavaScript)                                                                                 nitro 15:47:02  


 ERROR  Unexpected character '@' (Note that you need plugins to import files that are not JavaScript)                                                                                                     15:47:02  

  at error (/D:/projects/projects/nuxt3/node_modules/rollup/dist/es/shared/rollup.js:1829:30)
  at Module.error (/D:/projects/projects/nuxt3/node_modules/rollup/dist/es/shared/rollup.js:12406:16)
  at Module.tryParse (/D:/projects/projects/nuxt3/node_modules/rollup/dist/es/shared/rollup.js:12783:25)
  at Module.setSource (/D:/projects/projects/nuxt3/node_modules/rollup/dist/es/shared/rollup.js:12688:24)
  at ModuleLoader.addModuleSource (/D:/projects/projects/nuxt3/node_modules/rollup/dist/es/shared/rollup.js:22144:20)
```

**Comment by aesdotjs** [comment]
Note that this "ERROR  Unexpected character '@' (Note that you need plugins to import files that are not JavaScript)" also happens on netlify

**Comment by aslero** [comment]
I have a tailwindcss and it seems to have installed all the plugins

**Comment by Beiri22** [comment]
We also experience the problem on rc0 rc1 rc2 and different checkouts of edge

**Comment by aesdotjs** [comment]
Ok, It appears the problems fixed itself by removing node_modules, .nuxt, .output, yarn.lock and yarn install

**Comment by aesdotjs** [comment]
It was really a weird issue. On netlify on first deploy it crashed with the same error. Then I tried Clear cache and redeploy and it worked (a bit like removing node_modules).

**Comment by aesdotjs** [comment]
But now the deployed site throw an error 500 (0 , import_core2.default) is not a function

**Comment by aesdotjs** [comment]
And i'm using it this way https://vuelidate-next.netlify.app/advanced_usage.html#using-an-object-of-refs
Weird thing is that it throws no errors on nuxt dev nor nuxt generate but it does when using `node .output/server/index.mjs`

**Comment by danielroe** [comment]
This is no longer reproducible for me with a new nuxt project on windows.
