### ISSUE TITLE
Cannot convert object to primitive value at ssrCompile

### ISSUE THREAD

**Issue by chakraecho** [nuxt/framework#4661]
### Environment

Nuxt CLI v3.0.0-rc.1                                                                                                  11:41:57
RootDir: /home/jhuang/projets/nuxt3                                                   11:41:59
Nuxt project info:                                                                                                    11:41:59

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `npm@8.3.0`
- Builder:          `vite`
- User Config:      `components`, `hooks`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

`app.vue`
```vue
<template>
  <div>
    <Test />
  </div>
</template>

<script>
import {defineNuxtComponent} from "#app";
import Test from "./components/test"

export default defineNuxtComponent({
  components: {
    Test
  }
})
</script>
```

`components/test.ts`
```ts
import {defineNuxtComponent} from "#app";

export default defineNuxtComponent({
    name: "TestCompile",
    template: "<div>test</div>"
})
```
`nuxt.config.ts`
```ts

import {defineNuxtConfig} from 'nuxt'

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({


    components: {
        global: false
    },
    hooks: {
        'vite:extendConfig': (config, {isClient, isServer}) => {
            if(isClient)
            config.resolve.alias.vue = 'vue/dist/vue.esm-bundler.js';
        },

    },

})
```

- run `npm run build`
- run `npm run preview`
- open  http://0.0.0.0:3000/
- Error in console : 
```
file:///home/jhuang/projets/nuxt3/.output/server/chunks/index.mjs:9869
    return (compileCache[cacheKey] = Function('require', code)(commonjsRequire));
                                     ^

TypeError: Cannot convert object to primitive value
    at Function (<anonymous>)
    at ssrCompile (file:///home/jhuang/projets/nuxt3/.output/server/chunks/index.mjs:9869:38)
    at renderComponentSubTree (file:///home/jhuang/projets/nuxt3/.output/server/chunks/index.mjs:9960:30)
    at renderComponentVNode (file:///home/jhuang/projets/nuxt3/.output/server/chunks/index.mjs:9946:16)
    at Object.ssrRenderComponent (file:///home/jhuang/projets/nuxt3/.output/server/chunks/index.mjs:10361:12)
    at _sfc_ssrRender (file:///home/jhuang/projets/nuxt3/.output/server/chunks/app/server.mjs:4048:32)
    at renderComponentSubTree (file:///home/jhuang/projets/nuxt3/.output/server/chunks/index.mjs:10001:13)
    at renderComponentVNode (file:///home/jhuang/projets/nuxt3/.output/server/chunks/index.mjs:9946:16)
    at Object.ssrRenderComponent (file:///home/jhuang/projets/nuxt3/.output/server/chunks/index.mjs:10361:12)
    at default (file:///home/jhuang/projets/nuxt3/.output/server/chunks/app/server.mjs:4022:42)

 ERROR  Command failed with exit code 1: node ./server/index.mjs                                                      11:47:51

  at makeError (node_modules/nuxi/dist/chunks/index5.mjs:1242:11)
  at handlePromise (node_modules/nuxi/dist/chunks/index5.mjs:2071:26)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async Object.invoke (node_modules/nuxi/dist/chunks/preview.mjs:224:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:46:20)
```

### Describe the bug

I'm trying to use the template key in the component object of defineNuxtConfig to load components with dynamic templates.
However the server seems to crash when it tries to compile the template server-side. It happens in production but not in dev.

seems like there's a TODO remining in `.output/server/chunks/index.mjs` at line 9841
```js
function ssrCompile(template, instance) {
    // TODO: This is copied from runtime-core/src/component.ts and should probably be refactored
    const Component = instance.type;
    const { isCustomElement, compilerOptions } = instance.appContext.config;
    const { delimiters, compilerOptions: componentCompilerOptions } = Component;
    const finalCompilerOptions = shared.extend(shared.extend({
        isCustomElement,
        delimiters
    }, compilerOptions), componentCompilerOptions);
    finalCompilerOptions.isCustomElement =
        finalCompilerOptions.isCustomElement || shared.NO;
    finalCompilerOptions.isNativeTag = finalCompilerOptions.isNativeTag || shared.NO;
    const cacheKey = JSON.stringify({
        template,
        compilerOptions: finalCompilerOptions
    }, (key, value) => {
        return shared.isFunction(value) ? value.toString() : value;
    });
    const cached = compileCache[cacheKey];
    if (cached) {
        return cached;
    }
    finalCompilerOptions.onError = (err) => {
        {
            throw err;
        }
    };
    const { code } = compilerSsr.compile(template, finalCompilerOptions);
    return (compileCache[cacheKey] = Function('require', code)(commonjsRequire));
}
```

**Comment by danielroe** [comment]
As part of the nitro build, we explicitly mock the SSR vue compiler once built:

https://github.com/nuxt/framework/blob/650d12fa9c2bb3dc45310fc3f805c627779914f5/packages/nuxt/src/core/nitro.ts#L75-L78

The TODO item you're seeing is coming from Vue core:

https://github.com/vuejs/core/blob/main/packages/server-renderer/src/helpers/ssrCompile.ts#L27-L30

It might be worth considering enabling runtime compilation of templates via opt-in - what do you think @pi0?

**Comment by pi0** [comment]
Enabling the opt-in option to use runtime compiler seems a good idea!

**Comment by chakraecho** [comment]
it would be very interesting to get the option to enable the runtime compiler in the nuxt.config file. Is the option going to be in the initial release if added ?

Is it possible to change the ssr compiler through the nitro option in the nuxt config ? 

```js
    nitro: defineNitroConfig({
        plugins: [path.join(__dirname, "./nitro/nitro")],
    })
```

it seems that the plugin file is not called

**Comment by chakraecho** [comment]
```js
function ssrCompile(template, instance) {
    // TODO: This is copied from runtime-core/src/component.ts and should probably be refactored
    const Component = instance.type;
    const { isCustomElement, compilerOptions } = instance.appContext.config;
    const { delimiters, compilerOptions: componentCompilerOptions } = Component;
    const finalCompilerOptions = shared.extend(shared.extend({
        isCustomElement,
        delimiters
    }, compilerOptions), componentCompilerOptions);
    finalCompilerOptions.isCustomElement =
        finalCompilerOptions.isCustomElement || shared.NO;
    finalCompilerOptions.isNativeTag = finalCompilerOptions.isNativeTag || shared.NO;
    const cacheKey = JSON.stringify({
        template,
        compilerOptions: finalCompilerOptions
    }, (key, value) => {
        return shared.isFunction(value) ? value.toString() : value;
    });
    const cached = compileCache[cacheKey];
    if (cached) {
        return cached;
    }
    finalCompilerOptions.onError = (err) => {
        {
            throw err;
        }
    };
    const { code } = compilerSsr.compile(template, finalCompilerOptions);
    
    return (compileCache[cacheKey] = Function('require', code)(commonjsRequire);
}
```
I just checked was was the code variable at the last line. I don't know why but the const {code} is already a render function. Does nitro use the ssrCompiler by default ?

Changing the line 9870 in the compiled nuxt at .output/server/chuncks/index.mjs by :
```js
return (compileCache[cacheKey] = typeof code === 'string' ?  Function('require', code)(commonjsRequire): code);
```
would solve the issue. This line seems to be retrieved from @vue/server-renderer/dist/server-renderer.cjs{.prod}.js at line 106.

**Comment by chakraecho** [comment]
@danielroe It works !  I can confirm that the const {code} is a string when the component template is pre-compiled and is a render function when the component template use the template option.
`components/SupraTest.ts`
```ts
import {defineNuxtComponent} from "#app";
import {inject} from "#imports";
import {h} from "vue"

export default defineNuxtComponent({
    name: "SupraTest",

    setup(){

        const template = inject<{template:string}>("data")

        if(!template){
            throw new Error("template not injected")
        }

        return {
            template
        }
    },

    render(){
        return h({
            name: "renderTemplate",

            template: this.template.template
        })
    }
})
```

I'm injecting data from an useAsyncData function in app.vue to simulate the call to an external api to retrieve templates.
`app.vue`
```vue
<template>
  hello
  <div v-if="loaded">

    <SupraTest/>
    <Test/>
    <TrueSFC></TrueSFC>
  </div>
</template>

<script>
import {defineNuxtComponent} from "#app";
import Test from "./components/test"
import SupraTest from "./components/SupraTest";
import TrueSFC from "./components/TrueSFC";
import {provide, useAsyncData, watch, ref} from "#imports"

export default defineNuxtComponent({
  name: "App",

  components: {
    Test,
    SupraTest,
    TrueSFC
  },


  setup() {

    const loaded = ref(false);

    const loadedData = reactive({
      template: ""
    })

    const data = useAsyncData("data", async () => {

      function timeout(ms) {
        return new Promise(resolve => setTimeout(resolve, ms));
      }

      await timeout(4000);

      return {
        template: "<div> world, this is a Template loaded from afaaaarrr </div>"
      }
    }).then(({data}) => {
      loaded.value = true;
      loadedData.template = data.value.template
    })
    
    provide("data", loadedData)
    
    return {
      loaded,
      data
    }
  }
})
</script>
```

![image](https://user-images.githubusercontent.com/63512348/165543043-23cde028-2d98-4cec-8172-a0eafeab1193.png)

**Comment by chakraecho** [comment]
can i add the @rollup/plugin-commonjs to the rollup plugins ? I get the error ```` Could not dynamically require "vue/server-renderer". Please configure the dynamicRequireTargets or/and ignoreDynamicRequires option of @rollup/plugin-commonjs appropriately for this require call to work.```` when it tries to ssrCompile(). I've added tp
`nuxt.config.ts`
````ts

    nitro: defineNitroConfig({
      hooks: {
        "rollup:before": (nitro) => {

          nitro.options.rollupConfig.plugins.push(commonjs({
            dynamicRequireTargets: [
              "/node_modules/vue",
              "vue/server-renderer"
            ]
          }))

          debugger
        },
      },        
    })
````
 but it doesn't work. The built file at 
`.output/server/chunks/index.mjs` 
still have
```js
function commonjsRequire(path) {
	throw new Error('Could not dynamically require "' + path + '". Please configure the dynamicRequireTargets or/and ignoreDynamicRequires option of @rollup/plugin-commonjs appropriately for this require call to work.');
}
```

instead of the method to require the vue packages

**Comment by chakraecho** [comment]
I've found a way to enable the ssr runtime compiler but i have to replace the @rollup/plugin-commonjs that is already set by nitro
`nuxt.config.ts`
```ts

export default defineNuxtConfig({
    alias: {
        '@vue/compiler-core': '@vue/compiler-core' ,
        '@vue/compiler-dom':'@vue/compiler-dom',
        '@vue/compiler-ssr':'@vue/compiler-ssr' ,
        '@vue/devtools-api':'@vue/devtools-api' ,
        // @rollup/plugin-commonjs doesn't recognize export * ?
        "vue/server-renderer" :  "@vue/server-renderer/dist/server-renderer.cjs.prod.js",
        "@vue/server-renderer": "@vue/server-renderer"
    },

    hooks: {
    'vite:extendConfig': (config, { isClient, isServer }) => {
        if (isClient) {
            config.resolve.alias.vue = 'vue/dist/vue.esm-bundler'
        }
        },
    },

    nitro: defineNitroConfig({
        hooks: {
        "rollup:before": (nitro) => {
            
            if(!nitro.options.dev){
                // get the index of @rollup/plugin-commonjs set by nitro
                const indexOfCommonJsPlugin = nitro.options.rollupConfig.plugins.findIndex((plugin) => {
                    if(typeof plugin !== "boolean"){
                        return plugin.name === "commonjs"
                    }
                })

                if(indexOfCommonJsPlugin >= 0) {
                    // replace the @rollup/plugin-commonjs set by nitro
                    nitro.options.rollupConfig.plugins.splice(indexOfCommonJsPlugin, 1, commonjs({
                        dynamicRequireTargets: [
                            './node_modules/@vue/compiler-core',
                            './node_modules/@vue/compiler-dom',
                            './node_modules/@vue/compiler-ssr',
                            './node_modules/@vue/devtools-api',
                            "./node_modules/vue/server-renderer",
                            "./node_modules/@vue/server-renderer"
                        ],
                        strictRequires: "debug"
                    }))
                }
                debugger

            } 
          
        },
        },         
    })

})

`````
Nitro doesn't seem to provide any option to set the dynamicRequireTargets, is this the only way to set the renderer ?

**Comment by huang-julien** [comment]
link to Nitro PR https://github.com/unjs/nitro/pull/187
the feature will be refactored if PR is accepted

**Comment by huang-julien** [comment]
link to Nitro PR https://github.com/unjs/nitro/pull/187
the feature will be refactored if the PR is accepted

**Comment by fago** [comment]
we also ran into this when prototyping a nuxt3 of https://github.com/drunomics/nuxtjs-drupal-ce - we are using the vue run-time compiler to render markup with custom-elements provided by the CMS.

**Comment by tkjaergaard** [comment]
Any workarounds on this? I've tried to use your config @huang-julien but without luck on the rc-4 release.

`CompilerSsr` in `.output/chunks/server/handlers/renderer.mjs` still points to the mock resulting in the `TypeError: Cannot convert object to primitive value`.

**Comment by huang-julien** [comment]
> Any workarounds on this? I've tried to use your config @huang-julien but without luck on the rc-4 release.
> 
> `CompilerSsr` in `.output/chunks/server/handlers/renderer.mjs` still points to the mock resulting in the `TypeError: Cannot convert object to primitive value`.

@tkjaergaard this is my latest config for nuxt rc3, it should work for rc4 too. I think this can be refactored with the vueExternals option
```ts

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({

  srcDir: './src',

  components: false,

  nitro: {
    commonJS: {
      dynamicRequireTargets: [
        './node_modules/@vue/compiler-core',
        './node_modules/@vue/compiler-dom',
        './node_modules/@vue/compiler-ssr',
        './node_modules/vue/server-renderer',
        // allow h(), you can remove it if you use only objects to define vue components
        './node_modules/vue'
      ]
    },
    externals: {
      // no need for devtools -- should be mocked
      traceOptions: {
        ignore: (file) => {
          return /@vue(\/|\\)devtools-api/.test(file)
        }
      }
    }
  },

  alias: {
    '@vue/compiler-core': '@vue/compiler-core',
    '@vue/compiler-dom': '@vue/compiler-dom',
    '@vue/compiler-ssr': '@vue/compiler-ssr',
    'vue/server-renderer': 'vue/server-renderer'
  },

  hooks: {
    'vite:extendConfig': (config, { isClient, isServer }) => {
      if (isClient) {
        config.resolve.alias.vue = 'vue/dist/vue.esm-bundler'
      }
    }
  },

  vite: {
    plugins: [
      eslintPlugin()
    ]
  }
})

```

**Comment by tkjaergaard** [comment]
@huang-julien It worked 🙌  Thank you soo much.. I've spent way too many hours wrapping my head around this 🤯

**Comment by huang-julien** [comment]
@tkjaergaard I'm not about about this , based on the externalVue option, this "might" work. I haven't tested it yet

```ts
export default defineNuxtConfig({

  srcDir: './src',

  components: false,

  nitro: {
    externals: {
      // no need for devtools -- should be mocked
      traceOptions: {
        ignore: (file) => {
          return /@vue(\/|\\)devtools-api/.test(file)
        }
      }
    }
  },

  hooks: {
    'vite:extendConfig': (config, { isClient, isServer }) => {
      if (isClient) {
        config.resolve.alias.vue = 'vue/dist/vue.esm-bundler'
      }
    }
  },

  experimental: {
    externalVue: true
  },

  vite: {
    plugins: [
      eslintPlugin()
    ]
  }
})
```

**Comment by tkjaergaard** [comment]
Cool! It dosen't work though 🙂 

```
Cannot find module '[...]/.output/server/node_modules/vue/server-renderer/index.js'
```

But cool if we're able to simplify it to that amount of config 🙂

**Comment by huang-julien** [comment]
@tkjaergaard i just tried the last config i've posted [here](https://github.com/huang-julien/nuxt-3/tree/dev/test-vue-externals) . It does works but i also have the log about not finding the module server renderer which is weird since the file send to the bundle has a .mjs extension and the log indicate [dev].
```
[nitro] [dev] [unhandledRejection] Error: Cannot find module 'D:\GIT\nuxt-3\playground\.output\server\node_modules\vue\server-renderer\index.js'
```
@danielroe is it normal to get some logs with `[dev]` on prod ?

**Comment by huang-julien** [comment]
> > Any workarounds on this? I've tried to use your config @huang-julien but without luck on the rc-4 release.
> > `CompilerSsr` in `.output/chunks/server/handlers/renderer.mjs` still points to the mock resulting in the `TypeError: Cannot convert object to primitive value`.
> 
> @tkjaergaard this is my latest config for nuxt rc3, it should work for rc4 too. I think this can be refactored with the vueExternals option
> 
> ```ts
> // https://v3.nuxtjs.org/api/configuration/nuxt.config
> export default defineNuxtConfig({
> 
>   srcDir: './src',
> 
>   components: false,
> 
>   nitro: {
>     commonJS: {
>       dynamicRequireTargets: [
>         './node_modules/@vue/compiler-core',
>         './node_modules/@vue/compiler-dom',
>         './node_modules/@vue/compiler-ssr',
>         './node_modules/vue/server-renderer',
>         // allow h(), you can remove it if you use only objects to define vue components
>         './node_modules/vue'
>       ]
>     },
>     externals: {
>       // no need for devtools -- should be mocked
>       traceOptions: {
>         ignore: (file) => {
>           return /@vue(\/|\\)devtools-api/.test(file)
>         }
>       }
>     }
>   },
> 
>   alias: {
>     '@vue/compiler-core': '@vue/compiler-core',
>     '@vue/compiler-dom': '@vue/compiler-dom',
>     '@vue/compiler-ssr': '@vue/compiler-ssr',
>     'vue/server-renderer': 'vue/server-renderer'
>   },
> 
>   hooks: {
>     'vite:extendConfig': (config, { isClient, isServer }) => {
>       if (isClient) {
>         config.resolve.alias.vue = 'vue/dist/vue.esm-bundler'
>       }
>     }
>   },
> 
>   vite: {
>     plugins: [
>       eslintPlugin()
>     ]
>   }
> })
> ```

@shtse8 this config should work, except if you use webpack. In this case you should modify the 'webpack:extendConfig' hook instead of 'vite:extendConfig'. 

@shtse8 @tkjaergaard i've published a module to avoid changing the ocnfig in nuxt.config.ts [nuxt-runtime-compiler](https://www.npmjs.com/package/nuxt-runtime-compiler)

**Comment by Hyperblaster** [comment]
@huang-julien your code has helped us get our dynamic components rendering. However we're hitting one issue that i can't figure out that appears to be related:
https://github.com/nuxt/framework/issues/5868

I have a compact reproduction available here:
https://github.com/Hyperblaster/nuxt3-error-example

**Comment by huang-julien** [comment]
@Hyperblaster 
yes i've ran into this issue too. I've managed to work around this by compiling the template into render function with compile() from the vue package.
Instead of using template, prefer using compile  
```ts
import {defineNuxtComponent} from "#imports";
import {compile} from "vue";

export default defineNuxtComponent({
  render: compile(template)
})
```

**Comment by Hyperblaster** [comment]
@huang-julien you are an absolute legend! Thank you, that solved it!

**Comment by huang-julien** [comment]
@Hyperblaster I'm an idiot, vue compiler use estree-walker and babel-parser and i forgot to unmock it. nuxt-runtime-compiler and the PR has been updated. 
There's the updated config, now you should be able to use `template` :
`````ts
// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  nitro: {
    commonJS: {
      dynamicRequireTargets: [
        './node_modules/@vue/compiler-core',
        './node_modules/@vue/compiler-dom',
        './node_modules/@vue/compiler-ssr',
        './node_modules/vue/server-renderer',
        // allow h(), you can remove it if you use only objects to define vue components
        './node_modules/vue'
      ]
    },
  },

  alias: {
    '@vue/compiler-core': '@vue/compiler-core',
    '@vue/compiler-dom': '@vue/compiler-dom',
    '@vue/compiler-ssr': '@vue/compiler-ssr',
    'vue/server-renderer': 'vue/server-renderer',
    'estree-walker': 'estree-walker',
    '@babel/parser': '@babel/parser'
  },

  hooks: {
    'vite:extendConfig': (config, { isClient, isServer }) => {
      if (isClient) {
        config.resolve.alias.vue = 'vue/dist/vue.esm-bundler'
      }
    }
  }
})
````

**Comment by Hyperblaster** [comment]
Ahh nice. The compile function works great and solved my problem, but i’m sure this will be very helpful for others.

Thanks for your help and work!

**Comment by andrewspy** [comment]
@huang-julien I'm using the latest version of nuxt@3.0.0-rc-8 with nuxt-runtime-compiler, and it is throwing an out of memory error when served with `nuxt preview` (`nuxt dev` is working fine),

```
[nuxt] [request error] [unhandled] [500] Cannot find module 'C:\my-app\.output\server\node_modules\estree-walker\dist\esm\estree-walker.js' imported from C:\my-app\.output\server\chunks\renderer.mjs
Did you mean to import estree-walker/dist/umd/estree-walker.js?
  at new NodeError (node:internal/errors:372:5)
  at finalizeResolution (node:internal/modules/esm/resolve:437:11)
  at moduleResolve (node:internal/modules/esm/resolve:1009:10)
  at defaultResolve (node:internal/modules/esm/resolve:1218:11)
  at ESMLoader.resolve (node:internal/modules/esm/loader:580:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:294:18)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:80:40)
  at link (node:internal/modules/esm/module_job:78:36)
```

I have tried to reproduce with minimal code, but everything seems to work fine. In my use case, I am serving `no-ssr` on specific paths (https://github.com/nuxt/framework/discussions/1230). Do you have any idea what might cause the error?
