### ISSUE TITLE
Cannot start nuxt on version v3.0.0-rc.2-27526179.f74a523

### ISSUE THREAD

**Issue by bynicodevelop** [nuxt/framework#4773]
### Environment

Nuxt CLI v3.0.0-rc.2-27526179.f74a523

Nuxt project info: 

------------------------------
- Operating System: `Darwin`
- Node Version:     `v17.7.1`
- Nuxt Version:     `2.15.8`
- Package Manager:  `yarn@1.22.10`
- Builder:          `webpack`
- User Config:      `modules`, `publicRuntimeConfig`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.0.3`
- Build Modules:    `-`
------------------------------

### Reproduction

It was just after the nuxi update that the error occurred.

It's on a project already advanced in developer.

### Describe the bug

It was after updating the nuxt version that I got the following error:

```
ERROR  Cannot start nuxt:  

Vue packages version mismatch:

- vue@3.2.33
- vue-server-renderer@2.6.14

This may cause things to work incorrectly. Make sure to use the same version for both.


  
  Vue packages version mismatch:
  
  - vue@3.2.33
  - vue-server-renderer@2.6.14
  
  This may cause things to work incorrectly. Make sure to use the same version for both.
  
  at Object.<anonymous> (node_modules/vue-server-renderer/index.js:8:9)
  at Module._compile (node:internal/modules/cjs/loader:1099:14)
  at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
  at Module.load (node:internal/modules/cjs/loader:975:32)
  at Function.Module._load (node:internal/modules/cjs/loader:822:12)
  at Module.require (node:internal/modules/cjs/loader:999:19)
  at require (node:internal/modules/cjs/helpers:102:18)
  at Object.<anonymous> (node_modules/@nuxt/vue-renderer/dist/vue-renderer.js:19:27)
  at Module._compile (node:internal/modules/cjs/loader:1099:14)
  at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
```

**Comment by pi0** [comment]
It seems you are using Nuxt 2 or Bridge?

**Comment by bynicodevelop** [comment]
I ran the command: npm why vue

```
vue@3.2.33
node_modules/vue
  vue@"^3.2.33" from nuxt3@3.0.0-rc.2-27526179.f74a523
  node_modules/nuxt3
    dev nuxt3@"^3.0.0-rc.2-27526179.f74a523" from the root project
  peer vue@"^3.2.0" from vue-router@4.0.14
  node_modules/vue-router
    vue-router@"^4.0.14" from nuxt3@3.0.0-rc.2-27526179.f74a523
    node_modules/nuxt3
      dev nuxt3@"^3.0.0-rc.2-27526179.f74a523" from the root project
  peer vue@"^3.0.5" from vue3-player-video@1.2.5
  node_modules/vue3-player-video
    vue3-player-video@"^1.2.5" from the root project
  peer vue@"^3.2.0" from @headlessui/vue@1.6.0
  node_modules/@headlessui/vue
    @headlessui/vue@"^1.5.0" from the root project
  peer vue@">= 3" from @heroicons/vue@1.0.6
  node_modules/@heroicons/vue
    @heroicons/vue@"^1.0.6" from the root project
  peer vue@"3.2.33" from @nuxt/vite-builder@3.0.0-rc.2-27526179.f74a523
  node_modules/@nuxt/vite-builder
    @nuxt/vite-builder@"npm:@nuxt/vite-builder-edge@3.0.0-rc.2-27526179.f74a523" from nuxt3@3.0.0-rc.2-27526179.f74a523
    node_modules/nuxt3
      dev nuxt3@"^3.0.0-rc.2-27526179.f74a523" from the root project
  peer vue@"^3.2.25" from @vitejs/plugin-vue@2.3.1
  node_modules/@vitejs/plugin-vue
    @vitejs/plugin-vue@"^2.3.1" from @nuxt/vite-builder@3.0.0-rc.2-27526179.f74a523
    node_modules/@nuxt/vite-builder
      @nuxt/vite-builder@"npm:@nuxt/vite-builder-edge@3.0.0-rc.2-27526179.f74a523" from nuxt3@3.0.0-rc.2-27526179.f74a523
      node_modules/nuxt3
        dev nuxt3@"^3.0.0-rc.2-27526179.f74a523" from the root project
  peer vue@"3.2.33" from @vue/server-renderer@3.2.33
  node_modules/@vue/server-renderer
    @vue/server-renderer@"3.2.33" from vue@3.2.33
  peer vue@">=3" from @vueuse/head@0.7.6
  node_modules/@vueuse/head
    @vueuse/head@"^0.7.6" from nuxt3@3.0.0-rc.2-27526179.f74a523
    node_modules/nuxt3
      dev nuxt3@"^3.0.0-rc.2-27526179.f74a523" from the root project

vue@2.6.14
node_modules/@nuxt/vue-app/node_modules/vue
  vue@"^2.6.14" from @nuxt/vue-app@2.15.8
  node_modules/@nuxt/vue-app
    @nuxt/vue-app@"2.15.8" from nuxt@2.15.8
    node_modules/nuxt
      nuxt@"^2.15.8" from the root project
    @nuxt/vue-app@"2.15.8" from @nuxt/builder@2.15.8
    node_modules/@nuxt/builder
      @nuxt/builder@"2.15.8" from nuxt@2.15.8
      node_modules/nuxt
        nuxt@"^2.15.8" from the root project
  peer vue@"^2.6.14" from vuex@3.6.2
  node_modules/@nuxt/vue-app/node_modules/vuex
    vuex@"^3.6.2" from @nuxt/vue-app@2.15.8
    node_modules/@nuxt/vue-app
      @nuxt/vue-app@"2.15.8" from nuxt@2.15.8
      node_modules/nuxt
        nuxt@"^2.15.8" from the root project
      @nuxt/vue-app@"2.15.8" from @nuxt/builder@2.15.8
      node_modules/@nuxt/builder
        @nuxt/builder@"2.15.8" from nuxt@2.15.8
        node_modules/nuxt
          nuxt@"^2.15.8" from the root project

vue@2.6.14
node_modules/@nuxt/vue-renderer/node_modules/vue
  vue@"^2.6.14" from @nuxt/vue-renderer@2.15.8
  node_modules/@nuxt/vue-renderer
    @nuxt/vue-renderer@"2.15.8" from nuxt@2.15.8
    node_modules/nuxt
      nuxt@"^2.15.8" from the root project
    @nuxt/vue-renderer@"2.15.8" from @nuxt/server@2.15.8
    node_modules/@nuxt/server
      @nuxt/server@"2.15.8" from nuxt@2.15.8
      node_modules/nuxt
        nuxt@"^2.15.8" from the root project
      @nuxt/server@"2.15.8" from @nuxt/core@2.15.8
      node_modules/@nuxt/core
        @nuxt/core@"2.15.8" from nuxt@2.15.8
        node_modules/nuxt
          nuxt@"^2.15.8" from the root project
```

npm why vue-server-renderer

```
vue-server-renderer@2.6.14
node_modules/vue-server-renderer
  vue-server-renderer@"^2.6.14" from @nuxt/vue-renderer@2.15.8
  node_modules/@nuxt/vue-renderer
    @nuxt/vue-renderer@"2.15.8" from nuxt@2.15.8
    node_modules/nuxt
      nuxt@"^2.15.8" from the root project
    @nuxt/vue-renderer@"2.15.8" from @nuxt/server@2.15.8
    node_modules/@nuxt/server
      @nuxt/server@"2.15.8" from nuxt@2.15.8
      node_modules/nuxt
        nuxt@"^2.15.8" from the root project
      @nuxt/server@"2.15.8" from @nuxt/core@2.15.8
      node_modules/@nuxt/core
        @nuxt/core@"2.15.8" from nuxt@2.15.8
        node_modules/nuxt
          nuxt@"^2.15.8" from the root project
```

**Comment by bynicodevelop** [comment]
> It seems you are using Nuxt 2 or Bridge?

Yet the command that installed my project was that of nuxt3

`npx nuxi init DIRECTORY`

**Comment by pi0** [comment]
I think for some reason you accidentally reverted to Nuxt 2. Please manually check nuxt dependency in `package.json` to be `3.0.0-rc.2`

**Comment by bynicodevelop** [comment]
> I think for some reason you accidentally reverted to Nuxt 2. Please manually check nuxt dependency in `package.json` to be `3.0.0-rc.2`

Oh no !

It's a problem on my side, I'm not on the right version
