### ISSUE TITLE
Could not start Nuxt 3 sandbox on CodeSandbox iOS

### ISSUE THREAD

**Issue by lucpotage** [nuxt/framework#4803]
### Environment

Nuxt v3.0.0-rc.2

Not a regression

### Reproduction

https://codesandbox.io/s/jgo3l1

### Describe the bug

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /private/var/mobile/Containers/Data/Application/…/Documents/sandboxes/jgo3l1/src/node_modules/nuxt/bin/nuxt.mjs
    at Module.load (internal/modules/cjs/loader.js:1007:11)
    at Function.Module._load (internal/modules/cjs/loader.js:903:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at MessagePort.<anonymous> (internal/main/worker_thread.js:167:24)
    at MessagePort.emit (events.js:321:20)
    at MessagePort.onmessage (internal/worker/io.js:78:8)

**Comment by danielroe** [comment]
It seems to be working fine once I changed the command from `nuxi` to `nuxi dev` and removed the stray end tag in the template:

https://codesandbox.io/s/quiet-hill-gz01pg

**Comment by lucpotage** [comment]
Thank you Daniel. It actually did not solve my issue on iPad. Since it works well on the web, it's not related to Nuxt and I will open an issue in CodeSandbox repo instead.
