### ISSUE TITLE
 Importing directly from a nuxt.config file is not allowed

### ISSUE THREAD

**Issue by aslero** [nuxt/framework#4817]
### Environment

npx nuxi info

### Reproduction

npx nuxi info

### Describe the bug

` ERROR  Importing directly from a nuxt.config file is not allowed. Instead, use runtime config or a module. [importing /nuxt.config.ts from index.html]                                                   14:18:22`

```
 ERROR  Importing directly from a nuxt.config file is not allowed. Instead, use runtime config or a module. [importing /nuxt.config.ts.cjs from index.html]                                               14:18:22

i Vite client warmed up in 1510ms                                                                                                                                                                         14:18:23

 ERROR  nuxt3/nuxt cannot be imported directly. Instead, import runtime Nuxt composables from #app or #imports. [importing nuxt from nuxt.config.ts]    
```

**Comment by mctweb** [comment]
Can you provide a reproduction? 
It looks like this is by design rather than in issue, however a reproduction would be required to confirm.

**Comment by aslero** [comment]
https://github.com/aslero/nuxt3

**Comment by aslero** [comment]
and for

```
npm run build

> build
> nuxt build

Nuxt CLI v3.0.0-rc.1                                                                                                                                                                                      14:54:38  

 ERROR  Importing directly from a nuxt.config file is not allowed. Instead, use runtime config or a module. [importing /nuxt.config.ts from index.html]                                                   14:54:43


 ERROR  Importing directly from a nuxt.config file is not allowed. Instead, use runtime config or a module. [importing /nuxt.config.ts.cjs from index.html]                                               14:54:43

i Vite client warmed up in 2842ms                                                                                                                                                                         14:54:45
i Client built in 3481ms                                                                                                                                                                                  14:54:46
i Building server...                                                                                                                                                                                      14:54:46
√ Server built in 848ms                                                                                                                                                                                   14:54:46
√ Generated public .output/public                                                                                                                                                                   nitro 14:54:47
start Building server...                                                                                                                                                                            nitro 14:54:47

 WARN  'node:stream' is imported by node_modules/node-fetch/src/index.js, but could not be resolved – treating it as an external dependency                                                               14:54:50


 WARN  'node:https' is imported by node_modules/node-fetch/src/index.js, but could not be resolved – treating it as an external dependency                                                                14:54:50


 WARN  'node:zlib' is imported by node_modules/node-fetch/src/index.js, but could not be resolved – treating it as an external dependency                                                                 14:54:50


 WARN  'node:fs' is imported by node_modules/fetch-blob/from.js, but could not be resolved – treating it as an external dependency                                                                        14:54:50


 WARN  'node:buffer' is imported by node_modules/node-fetch/src/index.js, but could not be resolved – treating it as an external dependency                                                               14:54:50


 WARN  'node:http' is imported by node_modules/node-fetch/src/index.js, but could not be resolved – treating it as an external dependency                                                                 14:54:50


 WARN  'node:http' is imported by node_modules/node-fetch/src/headers.js, but could not be resolved – treating it as an external dependency                                                               14:54:50


 WARN  'node:path' is imported by node_modules/fetch-blob/from.js, but could not be resolved – treating it as an external dependency                                                                      14:54:50


 WARN  'node:stream' is imported by node_modules/node-fetch/src/body.js, but could not be resolved – treating it as an external dependency                                                                14:54:50


 WARN  'node:buffer' is imported by node_modules/node-fetch/src/body.js, but could not be resolved – treating it as an external dependency                                                                14:54:50


 WARN  'node:util' is imported by node_modules/node-fetch/src/headers.js, but could not be resolved – treating it as an external dependency                                                               14:54:50


 WARN  'node:util' is imported by node_modules/node-fetch/src/body.js, but could not be resolved – treating it as an external dependency                                                                  14:54:50


 WARN  'node:util' is imported by node_modules/node-fetch/src/request.js, but could not be resolved – treating it as an external dependency                                                               14:54:50  


 WARN  'node:url' is imported by node_modules/node-fetch/src/request.js, but could not be resolved – treating it as an external dependency                                                                14:54:50  


 WARN  'node:net' is imported by node_modules/node-fetch/src/utils/referrer.js, but could not be resolved – treating it as an external dependency                                                         14:54:50  


 ERROR  Rollup error: Unexpected character '@' (Note that you need plugins to import files that are not JavaScript)                                                                                 nitro 14:54:50  


 ERROR  Unexpected character '@' (Note that you need plugins to import files that are not JavaScript)  
```

**Comment by mctweb** [comment]
Your `tailwind.config.js` file needs edited to remove `nuxt.config`. See below for commented out line.
``` module.exports = {
  prefix: 'tw-',
  content: [
    './components/**/*.{js,vue,ts}',
    './layouts/**/*.vue',
    './pages/**/*.vue',
    './plugins/**/*.{js,ts}',
    // './nuxt.config.{js,ts}',
  ],
```

See https://github.com/nuxt/framework/issues/2886 for the same problem.

**Comment by aslero** [comment]
Well thank you. Next issue above on build

**Comment by mctweb** [comment]
Build warnings are the same with me, however I don't have the 2 errors. What environment are you building on?

**Comment by aslero** [comment]
- Operating System: Windows 11
- Node Version: v16.14.0
- Nuxt Version: 3.0.0-rc.1
- Package Manager: npm@8.5.2
- Builder: vite

**Comment by aslero** [comment]
> I don't get the 2 errors. What environment are you building on?
> 
> #4638 for warnings

```
 ERROR  Rollup error: Unexpected character '@' (Note that you need plugins to import files that are not JavaScript)                                                                                 nitro 15:47:02  


 ERROR  Unexpected character '@' (Note that you need plugins to import files that are not JavaScript)                                                                                                     15:47:02  

  at error (/D:/projects/projects/nuxt3/node_modules/rollup/dist/es/shared/rollup.js:1829:30)
  at Module.error (/D:/projects/projects/nuxt3/node_modules/rollup/dist/es/shared/rollup.js:12406:16)
  at Module.tryParse (/D:/projects/projects/nuxt3/node_modules/rollup/dist/es/shared/rollup.js:12783:25)
  at Module.setSource (/D:/projects/projects/nuxt3/node_modules/rollup/dist/es/shared/rollup.js:12688:24)
  at ModuleLoader.addModuleSource (/D:/projects/projects/nuxt3/node_modules/rollup/dist/es/shared/rollup.js:22144:20)
```

**Comment by aslero** [comment]
and how to be now? refuse tailwind?

**Comment by aslero** [comment]
And did Nuxt work for you with Tailwind?

**Comment by danielroe** [comment]
I think your second issue is the same as https://github.com/nuxt/framework/issues/4638. Let's follow it there.
