### ISSUE TITLE
[request error] useHead is not defined

### ISSUE THREAD

**Issue by bynicodevelop** [nuxt/framework#4820]
### Environment

Nuxt CLI v3.0.0-rc.2                                                            
Nuxt project info:                                                              

------------------------------
- Operating System: `Darwin`
- Node Version:     `v17.7.1`
- Nuxt Version:     `3.0.0-rc.2`
- Package Manager:  `yarn@1.22.10`
- Builder:          `vite`
- User Config:      `modules`, `publicRuntimeConfig`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.0.4`
- Build Modules:    `-`
------------------------------

### Reproduction

Context:

This is a site I've been working on for several days.
No problem so far.

No noticeable change.
By the magic of development, this happened during a coffee break :)

Dependances : 

```
"devDependencies": {
    "@nuxtjs/tailwindcss": "^5.0.2",
    "nuxt": "nuxt3@latest"
  },
  "dependencies": {
    "@headlessui/vue": "^1.5.0",
    "@heroicons/vue": "^1.0.6",
    "@tailwindcss/aspect-ratio": "^0.4.0",
    "@tailwindcss/forms": "^0.5.0",
    "@tailwindcss/typography": "^0.5.2",
    "aws-sdk": "^2.1122.0",
    "dayjs": "^1.11.1",
    "firebase": "^9.6.11",
    "firebase-admin": "^10.0.2",
    "firebase-functions": "^3.20.1",
    "jsonwebtoken": "^8.5.1",
    "lodash": "^4.17.21",
    "mailchimp-api-v3": "^1.15.0",
    "markdown-it": "^12.3.2",
    "markdown-it-metadata-block": "^1.0.2",
    "node-fetch": "^3.2.4",
    "stripe": "^8.219.0",
    "uuid": "^8.3.2",
    "vue-scrollto": "^2.20.0",
    "yup": "^0.32.11"
  }
```

I tried with : 

"nuxt": "3.0.0-rc.1" or "nuxt": "3.0.0-rc.2"

The problem is in a layout `courses`

I use composable like this:

```
const title = "Site name"

useHead({
  title,
});
```

other information :

Whatever the composable (custom or not) the comsables do not seem to be recognized.

Example: `ref('')`

### Describe the bug

```
[Vue warn]: Unhandled error during execution of setup function 
  at <Courses >
[nuxt] [request error] useHead is not defined
  at setup (./.nuxt/dist/server/server.mjs:3957:1)  
  at _sfc_main.setup (./.nuxt/dist/server/server.mjs:4197:23)  
  at callWithErrorHandling (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:157:22)  
  at setupStatefulComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7027:29)  
  at setupComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6982:11)  
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:198:17)  
  at renderVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:310:22)  
  at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:275:13)  
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:214:16)  
  at renderVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:310:22)  
  at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:275:13)  
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:214:16)  
  at renderVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:310:22)  
  at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:221:9)  
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:214:16)  
  at renderVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:310:22)
[nitro] [dev] [unhandledRejection] ReferenceError: useHead is not defined
```

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏

**Comment by danielroe** [comment]
[More info about what a minimal reproduction is.](https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction).

**Comment by karimh777** [comment]
_`useHead()` not defined_ also in Nuxtjs version `3.0.0-rc.3`. This error appears when using `javascript` not `typescript`.

**Comment by danielroe** [comment]
@karimh777 Please provide a reproduction and I'll take a look.

**Comment by karimh777** [comment]
[Here a simple reproduction](https://stackblitz.com/edit/github-5vpty7) running `npm run lint` shows the error.

**Comment by danielroe** [comment]
@karimh777 That isn't the original reported issue - it's a lint configuration issue.
