### ISSUE TITLE
Cannot start nuxt:  Cannot find module 'nuxt' 

### ISSUE THREAD

**Issue by cathats** [nuxt/framework#4866]
### Environment

Nuxt CLI v3.0.0-rc.2-27530889.9e5a3cd                    
Nuxt project info: 
------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.18.1`
- Nuxt Version:     `0.10.0-27212458.6329a68`
- Package Manager:  `yarn@1.22.17`
- Builder:          `webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

"dependencies": {
    "dotenv": "^16.0.0",
    "nuxt3": "3.0.0-rc.2",
    "pathe": "^0.2.0",
    "postcss": "~6.0.0",
    "postcss-px-to-viewport": "^1.1.1"
  },

`npx nuxi info`：
Nuxt CLI v3.0.0-rc.2-27530889.9e5a3cd  
------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.18.1`
- Nuxt Version:     `0.10.0-27212458.6329a68`
- Package Manager:  `yarn@1.22.17`
- Builder:          `webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Describe the bug

When I reinstall the package, I get a startup error。

### Logs

```shell
Cannot start nuxt:  Cannot find module 'nuxt'                                                                                   15:27:23
Require stack:
- /Users/maomaotou/Documents/WebProject/[CLI]框架/tjlt-common-cli-nuxt/index.js

  Require stack:
  - index.js
  at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
  at Function.resolve (internal/modules/cjs/helpers.js:99:19)
  at Function._resolve [as resolve] (node_modules/jiti/dist/jiti.js:1:192841)
  at resolveModule (/Users/maomaotou/Documents/WebProject/[CLI]%E6%A1%86%E6%9E%B6/tjlt-common-cli-nuxt/node_modules/@nuxt/kit/dist/index.mjs:242:29)
  at importModule (/Users/maomaotou/Documents/WebProject/[CLI]%E6%A1%86%E6%9E%B6/tjlt-common-cli-nuxt/node_modules/@nuxt/kit/dist/index.mjs:265:24)
  at loadNuxt (/Users/maomaotou/Documents/WebProject/[CLI]%E6%A1%86%E6%9E%B6/tjlt-common-cli-nuxt/node_modules/@nuxt/kit/dist/index.mjs:666:92)
  at async load (/Users/maomaotou/Documents/WebProject/[CLI]%E6%A1%86%E6%9E%B6/tjlt-common-cli-nuxt/node_modules/nuxt3/node_modules/nuxi/dist/chunks/dev.mjs:6733:23)
  at async Object.invoke (/Users/maomaotou/Documents/WebProject/[CLI]%E6%A1%86%E6%9E%B6/tjlt-common-cli-nuxt/node_modules/nuxt3/node_modules/nuxi/dist/chunks/dev.mjs:6777:5)
  at async _main (/Users/maomaotou/Documents/WebProject/[CLI]%E6%A1%86%E6%9E%B6/tjlt-common-cli-nuxt/node_modules/nuxt3/node_modules/nuxi/dist/cli.mjs:46:20)
```

**Comment by cathats** [comment]
已发现问题

**Comment by yoruponder** [comment]
> 

是啥问题，我也报这个。。。。

**Comment by yoruponder** [comment]
https://github.com/nuxt/framework/discussions/2883
