### ISSUE TITLE
`nuxt/app` imports are being externalised

### ISSUE THREAD

**Issue by bbrn** [nuxt/framework#4901]
### Environment

Nuxt CLI v3.0.0-rc.2
RootDir: /sandbox
Nuxt project info:

------------------------------
- Operating System: `Linux`
- Node Version:     `v14.18.1`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://codesandbox.io/s/vigilant-architecture-p2ojsw?file=/app.vue

### Describe the bug

When running `nuxt preview` the following error is thrown when trying to use `useState`:

> [nuxt] [request error] nuxt instance unavailable
  at useNuxtApp (./server/node_modules/nuxt/dist/app/nuxt.mjs:119:13)
  at useState (./server/node_modules/nuxt/dist/app/composables/state.mjs:4:16)
  at useMessage (./server/chunks/app/server.mjs:3734:26)
  at setup (./server/chunks/app/server.mjs:3927:21)
  at _sfc_main.setup (./server/chunks/app/server.mjs:3941:23)
  at callWithErrorHandling (./server/chunks/index.mjs:1986:23)
  at setupStatefulComponent (./server/chunks/index.mjs:7580:30)
  at setupComponent (./server/chunks/index.mjs:7561:12)
  at renderComponentVNode (./server/chunks/index.mjs:9930:17)
  at Object.ssrRenderComponent (./server/chunks/index.mjs:10361:12)

### Additional context

When running `nuxt dev` everything works fine.

### Logs

```shell
[nuxt] [request error] nuxt instance unavailable
  at useNuxtApp (./server/node_modules/nuxt/dist/app/nuxt.mjs:119:13)
  at useState (./server/node_modules/nuxt/dist/app/composables/state.mjs:4:16)
  at useMessage (./server/chunks/app/server.mjs:3734:26)
  at setup (./server/chunks/app/server.mjs:3927:21)
  at _sfc_main.setup (./server/chunks/app/server.mjs:3941:23)
  at callWithErrorHandling (./server/chunks/index.mjs:1986:23)
  at setupStatefulComponent (./server/chunks/index.mjs:7580:30)
  at setupComponent (./server/chunks/index.mjs:7561:12)
  at renderComponentVNode (./server/chunks/index.mjs:9930:17)
  at Object.ssrRenderComponent (./server/chunks/index.mjs:10361:12)
```

**Comment by danielroe** [comment]
There are two comments:

1. you are importing `useState` from `nuxt/app`. If you don't want to use auto-imports, we advise directly importing from `#imports` instead.
2. You are not returning a value from the default function - `() => {}` is a void function, `() => ({})` returns an empty object, which is probably what you wanted

Having said that, this is definitely a bug. You can workaround, even with your code as is, by adding `nuxt` to your `build.transpile` array - and that should not be required.

**Comment by dargmuesli** [comment]
@danielroe the proposed workaround, adding `nuxt` (or `nuxt-edge`) to `build.transpile`, does not work for me. I'm trying to fix https://github.com/nuxt-community/color-mode-module/issues/124.
