### ISSUE TITLE
Package import specifier "#internal/nitro/utils" is not defined

### ISSUE THREAD

**Issue by nndnha** [nuxt/framework#4927]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.3-27536597.3359b3b`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-q6dwzn?file=app.vue

### Describe the bug

Couldn't start the dev server with `yarn dev`:

```
TypeError [ERR_PACKAGE_IMPORT_NOT_DEFINED]: Package import specifier "#internal/nitro/utils" is not defined in package /home/projects/github-q6dwzn/node_modules/nuxt/package.json imported from /home/projects/github-q6dwzn/node_modules/nuxt/dist/core/runtime/nitro/error.mjs
    at TypeError.get (https://github-q6dwzn.w.staticblitz.com/blitz.4f2f7bcfc5ca816e127013c0d93c6fde53389605.js:6:292359)
    at https://github-q6dwzn.w.staticblitz.com/blitz.4f2f7bcfc5ca816e127013c0d93c6fde53389605.js:6:974307
    at Array.forEach ()
    at TryGetAllProperties (https://github-q6dwzn.w.staticblitz.com/blitz.4f2f7bcfc5ca816e127013c0d93c6fde53389605.js:6:974215)
    at serializeError (https://github-q6dwzn.w.staticblitz.com/blitz.4f2f7bcfc5ca816e127013c0d93c6fde53389605.js:6:974892)
    at process.workerOnGlobalUncaughtException [as _fatalException] (https://github-q6dwzn.w.staticblitz.com/blitz.4f2f7bcfc5ca816e127013c0d93c6fde53389605.js:6:1604782)
    at Object.triggerUncaughtException (https://github-q6dwzn.w.staticblitz.com/blitz.4f2f7bcfc5ca816e127013c0d93c6fde53389605.js:15:331982)
    at i.loadESM (https://github-q6dwzn.w.staticblitz.com/blitz.4f2f7bcfc5ca816e127013c0d93c6fde53389605.js:6:246617)
    at async handleMainPromise (https://github-q6dwzn.w.staticblitz.com/blitz.4f2f7bcfc5ca816e127013c0d93c6fde53389605.js:6:988909)
```

**Comment by kreejzak** [comment]
Having the same issue

**Comment by lyykfi** [comment]
the same. npm

**Comment by pi0** [comment]
For the context, this issue appeared after #4915. We detected and reverted this PR for now. The latest release of nuxt3 edge channel and rc3 should be fine.

**Comment by homerjam** [comment]
I have this issue when trying to deploy to Vercel, I'm using Nuxt 2 + bridge (node 16)

```
----------------- Nuxt build -----------------
--
11:20:30.818 | Running nuxt build --standalone --no-lock --config-file "nuxt.config.js" /vercel/path0/packages/fokus-cms
11:22:41.203 | ✔ Generated public .vercel_build_output/static
11:22:41.204 | ℹ Prerendering routes
11:22:41.500 |  
11:22:41.500 | FATAL  Package import specifier "#nitro/utils" is not defined in package /vercel/path0/packages/fokus-cms/node_modules_dev/@nuxt/bridge/package.json imported from /vercel/path0/packages/fokus-cms/node_modules_dev/@nuxt/bridge/dist/runtime/nitro/error.mjs
11:22:41.500 |  
11:22:41.500 | at new NodeError (internal/errors.js:322:7)
11:22:41.501 | at throwImportNotDefined (internal/modules/esm/resolve.js:326:9)
11:22:41.501 | at packageImportsResolve (internal/modules/esm/resolve.js:642:3)
11:22:41.501 | at moduleResolve (internal/modules/esm/resolve.js:768:21)
11:22:41.501 | at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:887:11)
11:22:41.501 | at Loader.resolve (internal/modules/esm/loader.js:89:40)
11:22:41.501 | at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
11:22:41.501 | at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:76:40)
11:22:41.501 | at link (internal/modules/esm/module_job.js:75:36)
11:22:41.501 |  
11:22:41.509 |  
11:22:41.510 | ╭──────────────────────────────────────────────────────────────────────────────╮│                                                                              ││   ✖ Nuxt Fatal Error                                                         ││                                                                              ││   TypeError [ERR_PACKAGE_IMPORT_NOT_DEFINED]: Package import specifier       ││   "#nitro/utils" is not defined in package                                   ││   /vercel/path0/packages/fokus-cms/node_modules_dev/@nuxt/bridge/package.j   ││   son                                                                        ││   imported from                                                              ││   /vercel/path0/packages/fokus-cms/node_modules_dev/@nuxt/bridge/dist/runt   ││   ime/nitro/error.mjs                                                        ││                                                                              │╰──────────────────────────────────────────────────────────────────────────────╯
11:22:41.510 |  
11:22:41.558 | Error: Command failed with exit code 1: npx nuxt build --standalone --no-lock --config-file "nuxt.config.js" /vercel/path0/packages/fokus-cms
11:22:41.558 | at makeError (/vercel/a34eae6992882c4f/.build-utils/.builder/node_modules/execa/lib/error.js:60:11)
11:22:41.558 | at handlePromise (/vercel/a34eae6992882c4f/.build-utils/.builder/node_modules/execa/index.js:118:26)
11:22:41.558 | at processTicksAndRejections (internal/process/task_queues.js:95:5)
11:22:41.559 | at async Object.build (/vercel/a34eae6992882c4f/.build-utils/.builder/node_modules/@nuxtjs/vercel-builder/lib/index.js:347:3) {
11:22:41.559 | shortMessage: 'Command failed with exit code 1: npx nuxt build --standalone --no-lock --config-file "nuxt.config.js" /vercel/path0/packages/fokus-cms',
11:22:41.559 | command: 'npx nuxt build --standalone --no-lock --config-file "nuxt.config.js" /vercel/path0/packages/fokus-cms',
11:22:41.559 | escapedCommand: 'npx nuxt build --standalone --no-lock "--config-file \\"nuxt.config.js\\"" "/vercel/path0/packages/fokus-cms"',
11:22:41.559 | exitCode: 1,
11:22:41.559 | signal: undefined,
11:22:41.559 | signalDescription: undefined,
11:22:41.559 | stdout: undefined,
11:22:41.559 | stderr: undefined,
11:22:41.559 | failed: true,
11:22:41.559 | timedOut: false,
11:22:41.559 | isCanceled: false,
11:22:41.559 | killed: false
11:22:41.559 | }

```

```
{
  "scripts": {
    "dev": "nuxi dev",
    "build": "nuxi build",
    "start": "nuxi preview",
  },
  "dependencies": {
    "@nuxtjs/auth-next": "5.0.0-1613647907.37b1156",
    "nuxt-edge": "2.16.0-27606262.123206cb"
  },
  "devDependencies": {
    "@nuxt/bridge": "npm:@nuxt/bridge-edge@3.0.0-27566698.2b0045e",
    "@nuxt/postcss8": "^1.1.3",
    "@nuxt/types": "^2.15.7",
    "@vue/runtime-dom": "^3.2.37",
    "nuxt-esbuild": "^1.1.0"
  },
}

```

Also when testing locally with `npx nuxt build --standalone --no-lock --config-file "nuxt.config.js"` I get this

```
✖ Nuxt Fatal Error                                                                                                 
││                                                                                                                      
││   Error: Could not load                                                                                              
││   /Users/jameshomer/Projects/fokus/packages/fokus-cms/.nuxt/dist/server/server.mjs (imported by                      
││   ../../node_modules/.pnpm/@nuxt+bridge-edge@3.0.0-27566698.2b0045e_3co246d6r3h2r7n37lretfsxaq/node_modules/@nuxt/   
││   bridge-edge/dist/runtime/nitro/renderer.mjs):                                                                      
││   ENOENT: no such file or directory, open                                                                            
││   '/Users/jameshomer/Projects/fokus/packages/fokus-cms/.nuxt/dist/server/server.mjs'   
```
