### ISSUE TITLE
nuxt.options.serverHandlers is not iterable

### ISSUE THREAD

**Issue by madeofcloud** [nuxt/framework#5025]
I was having an issue in only Nuxt v3.0.0-rc.3 but not in v3.0.0-rc.2

This is the error message:

```
Nuxt CLI v3.0.0-rc.3

 ERROR  nuxt.options.serverHandlers is not iterable

  at resolveHandlers (/project/node_modules/nuxt/dist/index.mjs:1240:37)
  at initNitro (/project/node_modules/nuxt/dist/index.mjs:1112:43)
  at initNuxt (/project/node_modules/nuxt/dist/index.mjs:1341:9)
  at async loadNuxt (/project/node_modules/nuxt/dist/index.mjs:1358:5)
  at async loadNuxt (/project/node_modules/@nuxt/kit/dist/index.mjs:657:19)
```

I am confused at why it works in rc2 but not in rc3.

**Comment by madeofcloud** [comment]
I was able to solve the issue somehow. It just worked with v3.0.0-rc.3 all of a sudden.

**Comment by taybenlor** [comment]
I had this error today after upgrading from `rc1` to `rc3` and fixed it with an `npm upgrade` I'm guessing it was an incompatibility between nitro versions for `rc1` and `rc3`.
