### ISSUE TITLE
Error 500 Invalid route component with fresh install and pages/index.vue 

### ISSUE THREAD

**Issue by Arrogance** [nuxt/framework#5084]
### Environment

```
root@82dc903bf667:/app# npx nuxi info
Nuxt CLI v3.0.0-rc.3                                                                                          17:27:36

 ERROR  Command failed: npm --version                                                                         17:27:36

  at checkExecSyncError (node:child_process:817:11)
  at execSync (node:child_process:888:15)
  at getPackageManagerVersion (node_modules/nuxi/dist/chunks/packageManagers.mjs:21:10)
  at Object.invoke (node_modules/nuxi/dist/chunks/info.mjs:92:31)
  at _main (node_modules/nuxi/dist/cli.mjs:46:30)
```

Dunno why this command is failing with a fresh and latest node version.

### Reproduction

Run, within a docker image (or even outside, same problems):

- `npx nuxi init nuxt-app`
- Add a new `index.vue` on `./pages` folder with the content:
```
<template>
  <div>
    Hello Moto
  </div>
</template>
```
- Add `<NuxtPage />` (or not, same error) to `app.vue`.

### Describe the bug

Trying to add a new default route fails on a fresh install. I've tried it on a Windows WSL2 env, Linux and inside a Docker with latest stable node image.

I've tried to remove the `app.vue`, to add the `<NuxtPage />`. Same error:

```
500
Invalid route component

at extractComponentsGuards (./node_modules/vue-router/dist/vue-router.cjs.js:1978:27)
at ./node_modules/vue-router/dist/vue-router.cjs.js:3133:22
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async ./.nuxt/dist/server/server.mjs:2506:7
at async Object.callAsync (./node_modules/unctx/dist/index.mjs:45:16)
at async applyPlugin (./.nuxt/dist/server/server.mjs:340:23)
at async Module.applyPlugins (./.nuxt/dist/server/server.mjs:350:5)
at async createNuxtAppServer (./.nuxt/dist/server/server.mjs:46:7)
at async Object.renderToString (./node_modules/vue-bundle-renderer/dist/index.mjs:252:19)
at async ./.nuxt/dev/index.mjs:465:20
```

### Logs

```shell
[Vue Router warn]: Component "default" in record with path "/" is not a valid component. Received "C:\\Users\\raya\\Proyectos\\welike-web\\pages\\index.vue".
[Vue Router warn]: uncaught error during route navigation:
Error: Invalid route component
    at extractComponentsGuards (/app/node_modules/vue-router/dist/vue-router.cjs.js:1978:27)
    at /app/node_modules/vue-router/dist/vue-router.cjs.js:3133:22
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///app/.nuxt/dist/server/server.mjs:2506:7
    at async Object.callAsync (file:///app/node_modules/unctx/dist/index.mjs:45:16)
    at async applyPlugin (file:///app/.nuxt/dist/server/server.mjs:340:23)
    at async Module.applyPlugins (file:///app/.nuxt/dist/server/server.mjs:350:5)
    at async createNuxtAppServer (file:///app/.nuxt/dist/server/server.mjs:46:7)
    at async Object.renderToString (file:///app/node_modules/vue-bundle-renderer/dist/index.mjs:252:19)
    at async file:///app/.nuxt/dev/index.mjs:465:20
[Vue Router warn]: uncaught error during route navigation:
TypeError: __vite_ssr_import_8__.globalMiddleware is not iterable
    at file:///app/.nuxt/dist/server/server.mjs:2515:65
    at /app/node_modules/vue-router/dist/vue-router.cjs.js:1925:35
    at new Promise (<anonymous>)
    at /app/node_modules/vue-router/dist/vue-router.cjs.js:1899:18
    at /app/node_modules/vue-router/dist/vue-router.cjs.js:3409:65
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[nuxt] [request error] Invalid route component
  at extractComponentsGuards (./node_modules/vue-router/dist/vue-router.cjs.js:1978:27)
  at ./node_modules/vue-router/dist/vue-router.cjs.js:3133:22
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async ./.nuxt/dist/server/server.mjs:2506:7
  at async Object.callAsync (./node_modules/unctx/dist/index.mjs:45:16)
  at async applyPlugin (./.nuxt/dist/server/server.mjs:340:23)
  at async Module.applyPlugins (./.nuxt/dist/server/server.mjs:350:5)
  at async createNuxtAppServer (./.nuxt/dist/server/server.mjs:46:7)
  at async Object.renderToString (./node_modules/vue-bundle-renderer/dist/index.mjs:252:19)
  at async ./.nuxt/dev/index.mjs:465:20
[Vue Router warn]: uncaught error during route navigation:
TypeError: __vite_ssr_import_8__.globalMiddleware is not iterable
    at file:///app/.nuxt/dist/server/server.mjs:2515:65
    at /app/node_modules/vue-router/dist/vue-router.cjs.js:1925:35
    at new Promise (<anonymous>)
    at /app/node_modules/vue-router/dist/vue-router.cjs.js:1899:18
    at /app/node_modules/vue-router/dist/vue-router.cjs.js:3409:65
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by Arrogance** [comment]
After a few removals and reinstall, it seems to work. The .nuxt/dev folder was not updated successfully after changing folders.
