### ISSUE TITLE
The requested module does not provide an export named 'createDefu'

### ISSUE THREAD

**Issue by M1seRy** [nuxt/framework#5153]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.16.0`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `npm@6.14.11`
- Builder:          `webpack`
- User Config:      `telemetry`, `hooks`, `mode`, `target`, `head`, `css`, `plugins`, `components`, `modules`, `build`, `srcDir`, `server`, `loading`, `render`, `publicRuntimeConfig`, `privateRuntimeConfig`, `proxy`, `serverMiddleware`, `router`, `bridge`, `buildModules`
- Runtime Modules:  `@nuxtjs/proxy@2.1.0`, `@nuxt/http@0.5.13`, `@nuxtjs/device@1.2.7`, `@nuxtjs/svg@0.1.12`
- Build Modules:    `@nuxt/bridge@3.0.0-27545203.75e046f`
------------------------------

### Reproduction

Need some helps when i use `npm run dev` run dev environment get The above error, thanks ~

### Describe the bug

use `npm i` install packages and `npm run dev` run dev environment:

error logs:

```
 ERROR  [worker reload] [worker init] The requested module 'file:///Users/w/workspace/node_modules/defu/dist/defu.mjs' does not provide an export named 'createDefu'

  import { createDefu } from 'node_modules/defu/dist/defu.mjs';
  ^^^^^^^^^^
  SyntaxError: The requested module 'node_modules/defu/dist/defu.mjs' does not provide an export named 'createDefu'
  at ModuleJob._instantiate (internal/modules/esm/module_job.js:104:21)
  at async ModuleJob.run (internal/modules/esm/module_job.js:149:5)
  at async Loader.import (internal/modules/esm/loader.js:166:24)
  at async Object.loadESM (internal/process/esm_loader.js:68:5)
```

and use `npm why defu` :

```
✦ ❯ npm-why defu
  Who required defu:
  web > @nuxt/bridge > unplugin-vue2-script-setup > defu@5.0.1
  web > nuxt-edge > @nuxt/cli-edge > @nuxt/config-edge > defu@5.0.1
  web > nuxt-edge > @nuxt/cli-edge > defu@5.0.1
  web > nuxt-edge > @nuxt/config-edge > defu@5.0.1
  web > nuxt-edge > @nuxt/core-edge > @nuxt/config-edge > defu@5.0.1
  web > nuxt-edge > @nuxt/core-edge > @nuxt/server-edge > @nuxt/vue-renderer-edge > defu@5.0.1
  web > nuxt-edge > @nuxt/core-edge > @nuxt/server-edge > serve-placeholder > defu@5.0.1
  web > nuxt-edge > @nuxt/generator-edge > defu@5.0.1
  web > nuxt-edge > @nuxt/loading-screen > defu@5.0.1
  web > nuxt-edge > @nuxt/server-edge > @nuxt/vue-renderer-edge > defu@5.0.1
  web > nuxt-edge > @nuxt/server-edge > serve-placeholder > defu@5.0.1
  web > nuxt-edge > @nuxt/telemetry > defu@5.0.1
  web > nuxt-edge > @nuxt/vue-renderer-edge > defu@5.0.1
```

**Comment by dzcpy** [comment]
Same issue

**Comment by MelvinSnijders** [comment]
Same issue here!

**Comment by felix-berlin** [comment]
Same issue 😞
