### ISSUE TITLE
Nuxi Build plugin access in setup

### ISSUE THREAD

**Issue by lperez22** [nuxt/framework#5250]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.18.0`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `alias`, `nitro`, `build`, `meta`, `css`, `vite`, `vue`, `hooks`, `components`, `runtimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-hifwx8?file=plugins%2Ffirst.js,pages%2FTest.vue,plugins%2Fsecond.js

### Describe the bug

I'm trying to upgrade from an older version of BETA and I followed the breaking changes tracker from this discussion https://github.com/nuxt/framework/discussions/2883. I have address all the breaking changes and in yarn dev everything is working fine. But in build I'm running into many errors because it seems that auto imports for plugins isn't working. I'm only getting some of my plugins, but when I try to access other plugins I'm getting undefined. Here is how we are using plugins in a page component in setup
```
<script setup>
  const { $gql, $page } = useNuxtApp();
  const page = await $page.getPage()
</script>
```
I only have access to $gql and settings is undefined. The same with my reproduction in setup 

### Additional context

This only happens when I run yarn build && yarn start, I'm also getting this strange error stating the $fetch1 is not a function which I've pasted below.
The version of nuxt 3 that I was coming from is: 3.0.0-27389502.88da719

### Logs

```shell
TypeError: Cannot read property 'getPage' of undefined
    at file:///Users/lperez/code/web-vue/.output/server/chunks/app/server.mjs:43734:15
    at Object.withAsyncContext (file:///Users/lperez/code/web-vue/.output/server/chunks/handlers/renderer.mjs:8459:22)
    at setup (file:///Users/lperez/code/web-vue/.output/server/chunks/app/server.mjs:43733:79)
    at _sfc_main$1R.setup (file:///Users/lperez/code/web-vue/.output/server/chunks/app/server.mjs:43758:26)
    at callWithErrorHandling (file:///Users/lperez/code/web-vue/.output/server/chunks/handlers/renderer.mjs:2524:23)
    at setupStatefulComponent (file:///Users/lperez/code/web-vue/.output/server/chunks/handlers/renderer.mjs:8165:30)
    at setupComponent (file:///Users/lperez/code/web-vue/.output/server/chunks/handlers/renderer.mjs:8146:12)
    at renderComponentVNode (file:///Users/lperez/code/web-vue/.output/server/chunks/handlers/renderer.mjs:10493:17)
    at renderVNode (file:///Users/lperez/code/web-vue/.output/server/chunks/handlers/renderer.mjs:10616:22)
    at renderVNode (file:///Users/lperez/code/web-vue/.output/server/chunks/handlers/renderer.mjs:10622:17)
[Vue warn]: Component ContentPage is missing template or render function.
[nuxt] [request error] fetch$1 is not a function
  at Object.graph (./.output/server/chunks/app/server.mjs:24004:30)
  at Object.query (./.output/server/chunks/app/server.mjs:23976:58)
  at async ./.output/server/chunks/app/server.mjs:28753:112
  at async Object.callAsync (./.output/server/node_modules/unctx/dist/index.mjs:45:16)
  at async applyPlugin (./.output/server/chunks/app/server.mjs:5984:33)
  at async applyPlugins (./.output/server/chunks/app/server.mjs:5993:5)
  at async createNuxtAppServer (./.output/server/chunks/app/server.mjs:31450:7)
  at async Object.renderToString (./.output/server/chunks/handlers/renderer.mjs:258:19)
  at async ./.output/server/chunks/handlers/renderer.mjs:11193:20
  at async ./.output/server/node_modules/h3/dist/index.mjs:417:19
```

**Comment by danielroe** [comment]
This seems to work fine in your stackblitz - both in dev & build.

**Comment by lperez22** [comment]
Ok I tracked the real problem, I was wrong about plugins not loading in build, what is happening is that we have a plugin that is shared between other plugins to make graph calls. We are using the isomorphic-fetch package and in dev the import is a function, but in build it is an empty object. So that in turn breaks our other plugins that depend on the graph calls, I have updated the stackblitz which is more in line how we are using this

**Comment by lperez22** [comment]
Hey @danielroe is this something that I should bring up in the isomorphic-fetch github or is that package not compatible with nitro?

**Comment by JulianMar** [comment]
Why are you not just using the `useFetch` helper? It should work with it.

**Comment by danielroe** [comment]
You should likely not use `isomorphic-fetch` as Nuxt already polyfills fetch into both server + client-side.

Nitro currently aliases this to an empty file: https://github.com/unjs/unenv/blob/fb9709b272d0a01287fffa3ad91e94d3844594b7/src/presets/node.ts#L9

If you need to use it, add the following to Nuxt config - though as above, I would recommend not using it:
```js
  alias: {
    'isomorphic-fetch': 'isomorphic-fetch'
  },
```
