### ISSUE TITLE
error with camelcase middleware is hard to see

### ISSUE THREAD

**Issue by YusufcanY** [nuxt/framework#5311]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-pxu5y9?file=pages/index.vue

### Describe the bug

When trying to use a middleware with camelCase name giving weird error.

### Logs

```shell
500
setup is not a function

at fn (./.nuxt/dist/server/server.mjs:404:27)
at Object.callAsync (./node_modules/unctx/dist/index.mjs:60:19)
at Module.callWithNuxt (./.nuxt/dist/server/server.mjs:406:23)
at eval (./.nuxt/dist/server/server.mjs:2555:50)
```

**Comment by YusufcanY** [comment]
I noticed, when you are defining page meta for middleware you need to write to write with kebab-case. Right now its works but its need to be in doc
```js
definePageMeta({
  middleware: 'test-mid',
});
```

**Comment by danielroe** [comment]
You should find that immediately above that error you are given the information about what :

```ts
Unknown middleware: testMid. Valid options are test-mid.
[Vue Router warn]: uncaught error during route navigation:
TypeError: setup is not a function
    at fn (file:///Users/daniel/code/nuxt/framework/playground/.nuxt/dist/server/server.mjs:458:27)
    at Object.callAsync (file:///Users/daniel/code/nuxt/framework/node_modules/unctx/dist/index.mjs:41:19)
    at Module.callWithNuxt (file:///Users/daniel/code/nuxt/framework/playground/.nuxt/dist/server/server.mjs:460:23)
    at file:///Users/daniel/code/nuxt/framework/playground/.nuxt/dist/server/server.mjs:2549:50
```

But we should suppress the following error entirely to foreground the more important error. 👍
