### ISSUE TITLE
Firebase CLI Deployment Error - Nuxt 3

### ISSUE THREAD

**Issue by abhirakshit** [nuxt/framework#5339]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.18.1`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `yarn@1.22.4`
- Builder:          `vite`
- User Config:      `nitro`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Created a default Nuxt 3 repo and followed the instructions here
https://github.com/nuxt/framework/issues/1398

### Describe the bug

I am trying to deploy a minimal nuxt 3 application to firebase hosting and getting this error. I followed the instructions provided [here](https://github.com/nuxt/framework/issues/1398) but it doesn't seem to work for me.

[debug] [2022-06-07T20:14:12.246Z] Could not find functions.yaml. Must use http discovery
[debug] [2022-06-07T20:14:12.264Z] Error: spawn ./node_modules/.bin/firebase-functions ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
[error] 
[error] Error: An unexpected error has occurred.

### Logs

```shell
[info] === Deploying to 'conneczen-nuxt'...
[info] 
[info] i  deploying functions, hosting 
[info] ✔  functions: Finished running predeploy script. 
[debug] [2022-06-07T20:14:08.826Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/conneczen-nuxt [none]
[debug] [2022-06-07T20:14:09.329Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/conneczen-nuxt 200
[debug] [2022-06-07T20:14:09.330Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/conneczen-nuxt {"projectId":"conneczen-nuxt","projectNumber":"215700003590","displayName":"Conneczen-Nuxt","name":"projects/conneczen-nuxt","resources":{"hostingSite":"conneczen-nuxt"},"state":"ACTIVE"}
[info] i  functions: ensuring required API cloudfunctions.googleapis.com is enabled... 
[info] i  functions: ensuring required API cloudbuild.googleapis.com is enabled... 
[debug] [2022-06-07T20:14:09.333Z] >>> [apiv2][query] GET https://serviceusage.googleapis.com/v1/projects/conneczen-nuxt/services/cloudfunctions.googleapis.com [none]
[debug] [2022-06-07T20:14:09.335Z] >>> [apiv2][query] GET https://serviceusage.googleapis.com/v1/projects/conneczen-nuxt/services/runtimeconfig.googleapis.com [none]
[debug] [2022-06-07T20:14:09.337Z] >>> [apiv2][query] GET https://serviceusage.googleapis.com/v1/projects/conneczen-nuxt/services/cloudbuild.googleapis.com [none]
[debug] [2022-06-07T20:14:09.338Z] >>> [apiv2][query] GET https://serviceusage.googleapis.com/v1/projects/conneczen-nuxt/services/artifactregistry.googleapis.com [none]
[debug] [2022-06-07T20:14:09.849Z] <<< [apiv2][status] GET https://serviceusage.googleapis.com/v1/projects/conneczen-nuxt/services/runtimeconfig.googleapis.com 200
[debug] [2022-06-07T20:14:09.849Z] <<< [apiv2][body] GET https://serviceusage.googleapis.com/v1/projects/conneczen-nuxt/services/runtimeconfig.googleapis.com [omitted]
[debug] [2022-06-07T20:14:09.851Z] <<< [apiv2][status] GET https://serviceusage.googleapis.com/v1/projects/conneczen-nuxt/services/artifactregistry.googleapis.com 200
[debug] [2022-06-07T20:14:09.851Z] <<< [apiv2][body] GET https://serviceusage.googleapis.com/v1/projects/conneczen-nuxt/services/artifactregistry.googleapis.com [omitted]
[debug] [2022-06-07T20:14:09.852Z] <<< [apiv2][status] GET https://serviceusage.googleapis.com/v1/projects/conneczen-nuxt/services/cloudbuild.googleapis.com 200
[debug] [2022-06-07T20:14:09.852Z] <<< [apiv2][body] GET https://serviceusage.googleapis.com/v1/projects/conneczen-nuxt/services/cloudbuild.googleapis.com [omitted]
[info] ✔  functions: required API cloudbuild.googleapis.com is enabled 
[debug] [2022-06-07T20:14:09.854Z] <<< [apiv2][status] GET https://serviceusage.googleapis.com/v1/projects/conneczen-nuxt/services/cloudfunctions.googleapis.com 200
[debug] [2022-06-07T20:14:09.854Z] <<< [apiv2][body] GET https://serviceusage.googleapis.com/v1/projects/conneczen-nuxt/services/cloudfunctions.googleapis.com [omitted]
[info] ✔  functions: required API cloudfunctions.googleapis.com is enabled 
[debug] [2022-06-07T20:14:09.855Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/conneczen-nuxt/adminSdkConfig [none]
[debug] [2022-06-07T20:14:10.150Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/conneczen-nuxt/adminSdkConfig 200
[debug] [2022-06-07T20:14:10.150Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/conneczen-nuxt/adminSdkConfig {"projectId":"conneczen-nuxt","storageBucket":"conneczen-nuxt.appspot.com"}
[debug] [2022-06-07T20:14:10.151Z] >>> [apiv2][query] GET https://runtimeconfig.googleapis.com/v1beta1/projects/conneczen-nuxt/configs [none]
[debug] [2022-06-07T20:14:10.423Z] <<< [apiv2][status] GET https://runtimeconfig.googleapis.com/v1beta1/projects/conneczen-nuxt/configs 200
[debug] [2022-06-07T20:14:10.423Z] <<< [apiv2][body] GET https://runtimeconfig.googleapis.com/v1beta1/projects/conneczen-nuxt/configs {}
[info] i  functions: preparing codebase default for deployment 
[debug] [2022-06-07T20:14:10.428Z] Validating nodejs source
[debug] [2022-06-07T20:14:12.244Z] > [functions] package.json contents: {
  "private": true,
  "type": "module",
  "main": "./index.mjs",
  "dependencies": {
    "firebase-functions-test": "latest",
    "firebase-admin": "10.2.0",
    "firebase-functions": "3.21.2",
    "abort-controller": "3.0.0",
    "agent-base": "6.0.2",
    "ajv": "6.12.6",
    "arrify": "2.0.1",
    "assert-plus": "1.0.0",
    "asn1": "0.2.6",
    "async-retry": "1.3.3",
    "asynckit": "0.4.0",
    "aws-sign2": "0.7.0",
    "aws4": "1.11.0",
    "bcrypt-pbkdf": "1.0.2",
    "base64-js": "1.5.1",
    "bignumber.js": "9.0.2",
    "buffer-equal-constant-time": "1.0.1",
    "buffer-from": "1.1.2",
    "caseless": "0.12.0",
    "combined-stream": "1.0.8",
    "compressible": "2.0.18",
    "configstore": "5.0.1",
    "cookie-es": "0.5.0",
    "core-util-is": "1.0.2",
    "cors": "2.8.5",
    "crypto-random-string": "2.0.0",
    "debug": "4.3.4",
    "delayed-stream": "1.0.0",
    "destr": "1.1.1",
    "dicer": "0.3.1",
    "dot-prop": "5.3.0",
    "duplexify": "4.1.2",
    "ecc-jsbn": "0.1.2",
    "ecdsa-sig-formatter": "1.0.11",
    "ent": "2.2.0",
    "encoding": "0.1.13",
    "end-of-stream": "1.4.4",
    "event-target-shim": "5.0.1",
    "extend": "3.0.2",
    "extsprintf": "1.4.1",
    "fast-deep-equal": "3.1.3",
    "fast-json-stable-stringify": "2.1.0",
    "fast-text-encoding": "1.0.3",
    "forever-agent": "0.6.1",
    "form-data": "2.3.3",
    "gaxios": "4.3.3",
    "gcp-metadata": "4.3.1",
    "functional-red-black-tree": "1.0.1",
    "google-auth-library": "7.14.1",
    "google-gax": "2.30.5",
    "google-p12-pem": "3.1.4",
    "graceful-fs": "4.2.10",
    "h3": "0.7.8",
    "gtoken": "5.3.2",
    "har-schema": "2.0.0",
    "har-validator": "5.1.5",
    "has-flag": "4.0.0",
    "hash-stream-validation": "0.2.4",
    "hookable": "5.1.1",
    "http-proxy-agent": "5.0.0",
    "http-signature": "1.2.0",
    "https-proxy-agent": "5.0.1",
    "iconv-lite": "0.6.3",
    "imurmurhash": "0.1.4",
    "inherits": "2.0.4",
    "is-obj": "2.0.0",
    "is-stream": "2.0.1",
    "is-stream-ended": "0.1.4",
    "is-typedarray": "1.0.0",
    "isstream": "0.1.2",
    "jose": "2.0.5",
    "json-bigint": "1.0.0",
    "jsbn": "0.1.1",
    "json-schema": "0.4.0",
    "json-schema-traverse": "0.4.1",
    "json-stringify-safe": "5.0.1",
    "jsonwebtoken": "8.5.1",
    "jsprim": "1.4.2",
    "jwa": "2.0.0",
    "jwks-rsa": "2.1.4",
    "jws": "4.0.0",
    "limiter": "1.1.5",
    "lodash": "4.17.21",
    "lodash.camelcase": "4.3.0",
    "lodash.clonedeep": "4.5.0",
    "lodash.includes": "4.3.0",
    "lodash.isboolean": "3.0.3",
    "lodash.isinteger": "4.0.4",
    "lodash.isnumber": "3.0.3",
    "lodash.isplainobject": "4.0.6",
    "lodash.isstring": "4.0.1",
    "lodash.once": "4.1.1",
    "long": "4.0.0",
    "lru-cache": "4.0.2",
    "lru-memoizer": "2.1.4",
    "make-dir": "3.1.0",
    "mime": "3.0.0",
    "mime-db": "1.51.0",
    "mime-types": "2.1.34",
    "ms": "2.1.2",
    "node-fetch": "2.6.7",
    "node-fetch-native": "0.1.3",
    "node-forge": "1.3.1",
    "oauth-sign": "0.9.0",
    "object-assign": "4.1.1",
    "object-hash": "3.0.0",
    "ohash": "0.1.0",
    "ohmyfetch": "0.4.18",
    "once": "1.4.0",
    "p-limit": "3.1.0",
    "performance-now": "2.1.0",
    "proto3-json-serializer": "0.1.9",
    "protobufjs": "6.11.3",
    "pseudomap": "1.0.2",
    "psl": "1.8.0",
    "pump": "3.0.0",
    "pumpify": "2.0.1",
    "qs": "6.5.2",
    "radix3": "0.1.2",
    "readable-stream": "3.6.0",
    "request": "2.88.2",
    "retry": "0.13.1",
    "retry-request": "4.2.2",
    "safe-buffer": "5.2.1",
    "safer-buffer": "2.1.2",
    "scule": "0.2.1",
    "semver": "6.3.0",
    "signal-exit": "3.0.7",
    "source-map": "0.6.1",
    "sshpk": "1.16.1",
    "source-map-support": "0.5.21",
    "stream-events": "1.0.5",
    "stream-shift": "1.0.1",
    "streamsearch": "1.1.0",
    "string_decoder": "1.3.0",
    "stubs": "3.0.0",
    "supports-color": "7.2.0",
    "teeny-request": "7.2.0",
    "tough-cookie": "2.5.0",
    "tr46": "0.0.3",
    "tslib": "2.4.0",
    "tunnel-agent": "0.6.0",
    "tweetnacl": "0.14.5",
    "typedarray-to-buffer": "3.1.5",
    "ufo": "0.8.4",
    "unenv": "0.5.2",
    "unique-string": "2.0.0",
    "unstorage": "0.4.1",
    "uri-js": "4.4.1",
    "util-deprecate": "1.0.2",
    "uuid": "3.4.0",
    "vary": "1.1.2",
    "verror": "1.10.0",
    "webidl-conversions": "3.0.1",
    "whatwg-url": "5.0.0",
    "wrappy": "1.0.2",
    "write-file-atomic": "3.0.3",
    "xdg-basedir": "4.0.0",
    "yallist": "2.1.2",
    "yocto-queue": "0.1.0",
    "@firebase/component": "0.5.13",
    "@firebase/database-compat": "0.1.8",
    "@firebase/logger": "0.3.2",
    "@firebase/util": "1.5.2",
    "@google-cloud/firestore": "4.15.1",
    "@google-cloud/paginator": "3.0.7",
    "@google-cloud/projectify": "2.1.1",
    "@google-cloud/promisify": "2.0.4",
    "@google-cloud/storage": "5.20.5",
    "@grpc/grpc-js": "1.6.7",
    "@grpc/proto-loader": "0.6.13",
    "@panva/asn1.js": "1.0.0",
    "@tootallnate/once": "2.0.0",
    "@protobufjs/aspromise": "1.1.2",
    "@protobufjs/base64": "1.1.2",
    "@protobufjs/codegen": "2.0.4",
    "@protobufjs/eventemitter": "1.1.0",
    "@protobufjs/fetch": "1.1.0",
    "@protobufjs/float": "1.0.2",
    "@protobufjs/inquire": "1.1.0",
    "@protobufjs/path": "1.1.2",
    "@protobufjs/pool": "1.1.0",
    "@protobufjs/utf8": "1.1.0"
  },
  "engines": {
    "node": "14"
  }
}
[debug] [2022-06-07T20:14:12.244Z] Building nodejs source
[debug] [2022-06-07T20:14:12.245Z] Analyzing nodejs backend spec
[debug] [2022-06-07T20:14:12.246Z] Could not find functions.yaml. Must use http discovery
[debug] [2022-06-07T20:14:12.264Z] Error: spawn ./node_modules/.bin/firebase-functions ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
[error] 
[error] Error: An unexpected error has occurred.
```

**Comment by abhirakshit** [comment]
Found same issue with existing ticket: https://github.com/nuxt/framework/issues/4961
Closing this.
