### ISSUE TITLE
Failed to load component `hgroup` - HTML5 attribute

### ISSUE THREAD

**Issue by Sigmanificient** [nuxt/framework#5384]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `target`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

> `index.vue`
```vue
<template>
<hgroup>
  <h1>heading</h1>
  <h2>sub-heading</h2>
</hgroup>
</template>
```

### Describe the bug

`hgroup` is a html5 attribute but nuxt is trying to load it as a component

### Logs

```shell
ℹ Vite client warmed up in 1034ms                                                                                                                                                                                   
ℹ Vite server warmed up in 104ms                                                                                                                                                                                    
✔ Vite server built in 719ms                                                                                                                                                                                        
✔ Nitro built in 292 ms                                                                                                                                                                                             
[Vue warn]: Failed to resolve component: hgroup
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[Vue warn]: Failed to resolve component: menuitem
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[nitro] [dev] [unhandledRejection] TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at normalizePropsOptions (.../node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3966:11)
    at createComponentInstance (.../node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6957:23)
    at renderComponentVNode (.../node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:171:22)
    at Module.ssrRenderComponent (.../node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:608:12)
    at _sfc_ssrRender (file://.../.nuxt/dist/server/server.mjs:3805:31)
    at renderComponentSubTree (.../node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:253:13)
    at renderComponentVNode (.../node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:188:16)
    at renderVNode (.../node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:295:22)
    at renderComponentSubTree (.../node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:259:13)
[Vue warn]: Failed to resolve component: hgroup
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[Vue warn]: Failed to resolve component: menuitem
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[nitro] [dev] [unhandledRejection] TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at normalizePropsOptions (.../node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3966:11)
    at createComponentInstance (.../node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6957:23)
    at renderComponentVNode (.../node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:171:22)
    at Module.ssrRenderComponent (.../node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:608:12)
    at _sfc_ssrRender (file://.../.nuxt/dist/server/server.mjs:3805:31)
    at renderComponentSubTree (.../node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:253:13)
    at renderComponentVNode (.../node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:188:16)
    at renderVNode (.../node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:295:22)
    at renderComponentSubTree (.../node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:259:13)
[Vue warn]: Failed to resolve component: hgroup
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[Vue warn]: Failed to resolve component: menuitem
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[nitro] [dev] [unhandledRejection] TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at normalizePropsOptions (.../node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3966:11)
    at createComponentInstance (.../node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6957:23)
    at renderComponentVNode (.../node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:171:22)
    at Module.ssrRenderComponent (.../node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:608:12)
    at _sfc_ssrRender (file://.../.nuxt/dist/server/server.mjs:3805:31)
    at renderComponentSubTree (.../node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:253:13)
    at renderComponentVNode (.../node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:188:16)
    at renderVNode (.../node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:295:22)
    at renderComponentSubTree (.../node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:259:13)
✔ Vite server built in 121ms
✔ Vite server built in 53ms
```

**Comment by huang-julien** [comment]
hasn't it been excluded from the W3C HTML specs ? if you really want to use it, try 
```ts
export default defineNuxtConfig({
    vue: {
     compilerOptions: {
         isCustomElement: (tag) => tag === "hgroup"
     }   
    }
})
````

**Comment by danielroe** [comment]
It is a deprecated element. You can raise it upstream at https://github.com/vuejs/core.

**Comment by Sigmanificient** [comment]
Do you have an official list for html5 that are not depreciated? That would help me a lot

**Comment by danielroe** [comment]
Check https://github.com/vuejs/core/blob/b2bac9fa1763ab895f9bea18ef83d58673e1a4ec/packages/shared/src/domTagConfig.ts#L6 for a list of supported HTML tags in Vue.

**Comment by ennioVisco** [comment]
> Do you have an official list for html5 that are not depreciated? That would help me a lot Apparently, my list is not up to day

You can just check the list of tags at: https://developer.mozilla.org/en-US/docs/Web/HTML/Element?retiredLocale=it

AFAIK hgroup is the only dubious one. The source of the doubt comes from the fact that it is deprecated by W3C but not by WHATWG, and it is objectively ambiguous (read more at the previous link)

**Comment by Sigmanificient** [comment]
> > Do you have an official list for html5 that are not depreciated? That would help me a lot Apparently, my list is not up to day
> 
> You can just check the list of tags at: https://developer.mozilla.org/en-US/docs/Web/HTML/Element?retiredLocale=it
> 
> AFAIK hgroup is the only dubious one. The source of the doubt comes from the fact that it is deprecated by W3C but not by WHATWG, and it is objectively ambiguous (read more at the previous link)

Well, thanks for the clarifications, i guess i will dig further in this `hgroup` rabbit hole ^^

I guess this issue is sorted, right?

**Comment by weo3dev** [comment]
I'm really struggling to find _where_ the W3C has marked `hgroup` as deprecated. The screenshot below shows the latest/greatest via the editor's copy. Elsewhere on the page are multiple examples of showing how to use `hgroup`. 

Kinda feel like all parties involved (Vue team as well) have pulled the trigger way too soon. Some of the arguments against `hgroup` could also be used against `nav` and `aside` and yet those are acceptable and compile just fine.

Not laying this at the feet of the Nuxt team; I am knocking here on this thread to see if anyone else can point me _exactly_ where W3C says 'deprecated', because I cannot find it. Please forgive me if I am missing something obvious.

Will be starting a conversation with Vue team on this, as it simply seems an unnecessary, specially-excluded tag.

![Screen Shot 2022-11-14 at 6 40 49 PM](https://user-images.githubusercontent.com/2545610/201813362-31ae79f9-5c78-4bf4-a99d-af12446960f7.png)

**Comment by ennioVisco** [comment]
> I'm really struggling to find _where_ the W3C has marked `hgroup` as deprecated. The screenshot below shows the latest/greatest via the editor's copy. Elsewhere on the page are multiple examples of showing how to use `hgroup`.
> 
> Kinda feel like all parties involved (Vue team as well) have pulled the trigger way too soon. Some of the arguments against `hgroup` could also be used against `nav` and `aside` and yet those are acceptable and compile just fine.
> 
> Not laying this at the feet of the Nuxt team; I am knocking here on this thread to see if anyone else can point me _exactly_ where W3C says 'deprecated', because I cannot find it. Please forgive me if I am missing something obvious.
> 
> Will be starting a conversation with Vue team on this, as it simply seems an unnecessary, specially-excluded tag.
> 
> ![Screen Shot 2022-11-14 at 6 40 49 PM](https://user-images.githubusercontent.com/2545610/201813362-31ae79f9-5c78-4bf4-a99d-af12446960f7.png)
> 
> Thanks to [huang-julien](https://github.com/huang-julien) for the shortcut to sanity. Thank you!
> 
> EDIT: adding a thank you

If you just check 5  messages above yours, I'm pointing to the exact conversation on MDN on the topic.
The tldr is that WHATWG and W3C don't agree on the spec of this element (or didn't at the time, not sure now).
