### ISSUE TITLE
pnpm support without `--shamefully-hoist`

### ISSUE THREAD

**Issue by pi0** [nuxt/framework#5411]
History: #581

We have progressively improved plug-and-play support over time and almost all underlying packages including nitro support and are tested against pnpm. 

Last step is making nuxt 3 working with pnpm out of the box before migrating modules and templates from first-class yarn to pnpm.

Using pnpm without `--shamefully-hoist` is possible today 🥳 but requires explicitly installing `vue` and `ufo` dependencies and we don't want this since Nuxt was always a zero-config package and we need to add deps of all nuxt modules as well this way.

One obvious solution is that same as Nitro, we internally (also for `unimport` ~> https://github.com/unjs/unimport/issues/69) resolve them to their full path but we also need to support non-resolved implicit imports in templates as modules might have similar implicit dependencies in their scope and they need to be resolved as well. I think this can be done using a custom resolver for vite (and webpack).

**Comment by jpsc** [comment]
It would be nice if fixing this also fixes for `pnpm workspaces` which it doesn't, even with `--shamefully-hoist` .
We have another [issue for workspaces](https://github.com/nuxt/framework/issues/158) that is probably closer to the issue.

**Comment by asonnleitner** [comment]
> It would be nice if fixing this also fixes for `pnpm workspaces` which it doesn't, even with `--shamefully-hoist` .
> We have another [issue for workspaces](https://github.com/nuxt/framework/issues/158) that is probably closer to the issue.

I have a fully functional monorepo using pnpm workspaces, including cached docker build layers and deployment into k8s. Just by using --shamefully-hoist

**Comment by jpsc** [comment]
@asonnleitner I'm assuming that's not anywhere public? I've tried multiple times when on rc.1. I would love to check and compare it.

**Comment by asonnleitner** [comment]
@jpsc yeah, it's private, but if you could make a simple example monorepo, I could take a look at it over the next week and check what's causing the troubles

**Comment by YannicEl** [comment]
@jpsc there are two ways i have found to use pnpm workspaces with nuxt3

1. Have a `.npmrc` file with `shared-workspace-lockfile=false` in your root folder and a `.npmrc` file with `shamefully-hoist=true` in your nuxt subfolder.  I use that approche here: https://github.com/YannicEl/try-finger/tree/dev

2. Have a `.npmrc` file with `shamefully-hoist=true` in your root folder. I use that approche here: https://github.com/YannicEl/hans

**Comment by amery** [comment]
I have an skeleton monorepo at https://gitlab.com/licensly/licensly/-/tree/shamefully-hoist. without `shamefully-hoist` I have to manually add `jiti`, `typescript`, `ufo` and `vue` to each package

and despite that it `nuxt generate` fails with `(undefinedms) (ReferenceError: Response is not defined)`  https://github.com/nuxt/framework/discussions/5471. it only works with `shamefully-hoist` enabled.

to make it worse `nuxt dev` doesn't work at all on fresh projects using pnpm anymore.  https://github.com/nuxt/framework/issues/5516

**Comment by jpsc** [comment]
> @jpsc there are two ways i have found to use pnpm workspaces with nuxt3
> 
>     1. Have a `.npmrc` file with `shared-workspace-lockfile=false` in your root folder and a `.npmrc` file with `shamefully-hoist=true` in your nuxt subfolder.  I use that approche here: https://github.com/YannicEl/try-finger/tree/dev
This option works if you go into each directory and do `pnpm install` but that kinda defeats doing a single install at once.
> 
>     2. Have a `.npmrc` file with `shamefully-hoist=true` in your root folder. I use that approche here: https://github.com/YannicEl/hans
This option seems counter-intuitive to force all packages to behave like that because of a limitation.


@asonnleitner, if by any chance you have the time I've created a minimal reproducible repo [here](https://github.com/jpsc/my-monorepo-repo).

Much appreciated!

**Comment by bluwy** [comment]
Besides needing to install `vue` and `ufo`. I also needed to install `node-fetch-native` to fix the `(undefinedms) (ReferenceError: Response is not defined)` error in generate, and update `.npmrc` with:

```
public-hoist-pattern[]=@vue/*
```

To fix some `useSSRContext` errors in dev/generate/build.

<details>
<summary>error logs</summary>

```
[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: Server rendering context not provided. Make sure to only call useSSRContext() conditionally in the server build.
[Vue warn]: Unhandled error during execution of setup function 
  at <NuxtRoot>
[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'modules')
  at _sfc_main.setup (./.nuxt/dist/server/server.mjs:15281:16)  
  at callWithErrorHandling (/Users/bjorn/Work/oss/whyframe/node_modules/.pnpm/@vue+runtime-core@3.2.37/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:157:22)  
  at setupStatefulComponent (/Users/bjorn/Work/oss/whyframe/node_modules/.pnpm/@vue+runtime-core@3.2.37/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7084:29)  
  at setupComponent (/Users/bjorn/Work/oss/whyframe/node_modules/.pnpm/@vue+runtime-core@3.2.37/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7039:11)  
  at renderComponentVNode (/Users/bjorn/Work/oss/whyframe/node_modules/.pnpm/@vue+server-renderer@3.2.37_vue@3.2.37/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:172:17)  
  at renderToString (/Users/bjorn/Work/oss/whyframe/node_modules/.pnpm/@vue+server-renderer@3.2.37_vue@3.2.37/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:446:26)  
  at Object.renderToString$1 [as renderToString] (./.nuxt/dev/index.mjs:469:24)  
  at Object.renderToString (/Users/bjorn/Work/oss/whyframe/node_modules/.pnpm/vue-bundle-renderer@0.4.2/node_modules/vue-bundle-renderer/dist/runtime.mjs:173:40)  
  at async ./.nuxt/dev/index.mjs:516:21  
  at async ./.nuxt/dev/index.mjs:106:22
```
</details>

**Comment by bmulholland** [comment]
I read through the associated issues, but couldn't understand the current status of yarn PnP support. Does the work enabling pnpm without hoisting also enable Yarn's PnP feature? Meaning Yarn Berry Plug 'n' Play isn't currently supported, but is being (indirectly) worked on.

**Comment by amery** [comment]
> I read through the associated issues, but couldn't understand the current status of yarn PnP support. Does the work enabling pnpm without hoisting also enable Yarn's PnP feature? Meaning Yarn Berry Plug 'n' Play isn't currently supported, but is being (indirectly) worked on.

rc.11 still doesn't work without `shamefully-hoist=true` on `.npmrc` for pnpm workspaces at least

**Comment by manniL** [comment]
Should be resolved with rc.11 via https://github.com/nuxt/framework/pull/7895

**Comment by amery** [comment]
I just created a sample project, just nuxi init, moved into a subproject and set srcDir. it got rc12. can't find vue.

https://github.com/amery/nuxt3-5411

```
$ git clone github.com/amery/nuxt3-5411
$ cd nuxt3-5411/apps/nuxt-app
$ pnpm i
$ pnpm serve
Nuxt 3.0.0-rc.12 with Nitro 0.6.0

  > Local:    http://localhost:3000/ 
  > Network:  http://172.17.0.2:3000/

 WARN  Failed to resolve dependency: vue, present in 'optimizeDeps.include'

 ERROR  The following dependencies are imported but could not be resolved:

  vue (imported by /home/amery/projects/xxx/nuxt3-5411/node_modules/.pnpm/nuxt@3.0.0-rc.12/node_modules/nuxt/dist/app/entry.mjs)

Are they installed?

ℹ Vite client warmed up in 112ms
✔ Nitro built in 944 ms
```

**Comment by manniL** [comment]
Yup, as I wrote, still work in progress - my bad ☺️

**Comment by amery** [comment]
> Yup, as I wrote, still work in progress - my bad

yes, but I thought a proper test case was useful to add :stuck_out_tongue_closed_eyes:

**Comment by manniL** [comment]
It definitely is 😋

**Comment by bmulholland** [comment]
Glad to see there's movement on this. I didn't get an answer to my question, though, and I don't want it to be lost: _when this issue is closed, will Yarn Berry PnP support work too?_ If not, is there a separate place that is being tracked? I couldn't find one; they've all been closed in favour of this issue, which doesn't mention yarn at all.

**Comment by Germain-condo-group** [comment]
Any workaround with explicit dependencies in package.json?
I tried but it still ain't working:
```ts
{
  "name": "myname",
  "private": true,
  "version": "0.0.1",
  "scripts": {
    "start:dev": "nuxt dev",
    "start": "nuxt dev",
    "watch": "nuxt dev",
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "nuxt": "3.0.0-rc.12",
    "vue": "^3.2.37",
    "ufo": "^0.8.6",
    "defu": "^6.1.0",
    "typescript": "^4.7.3",
    "jiti": "^1.16.0"
  }
}
```

**Comment by bluwy** [comment]
I was able to get it working in [my side project](https://github.com/bluwy/whyframe/blob/master/playground/nuxt/package.json) with:

```ini
# .npmrc
public-hoist-pattern[]=@vue/*
```

```
pnpm add -D vue node-fetch-native ufo
```
