### ISSUE TITLE
Nuxt 3.x.x latest doesn'

### ISSUE THREAD

**Issue by buffet-time** [nuxt/framework#5422]
### Environment

Nuxt project info:                                                                                            00:52:35

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `pnpm@7.2.0`
- Builder:          `vite`
- User Config:      `app`, `css`, `ignore`, `modules`, `typescript`
- Runtime Modules:  `@nuxt/typescript-build@2.1.0`, `@nuxtjs/tailwindcss@5.1.2`, `unplugin-icons/nuxt`, `@nuxtjs/eslint-module@3.1.0`
- Build Modules:    `-`
------------------------------

### Reproduction

[This branch](https://github.com/leaderboardsgg/leaderboard-site/tree/fixEslint) of a repo i'm working in to upgrade from Nuxt 2 to Nuxt 3 (rewriting) 

On Windows (I'm on 11 but someone on 10 said it also doesn't work)

1) clone repo
2) checkout to `fixEslint` branch
3) `pnpm install`
4) `pnpm build`
5) Observe the below console to see what is reproduced. Which is not seen on Ubuntu 22.04

### Describe the bug

On Windows 11 I get the following when running `pnpm build` (`nuxt build`)

But on Ubuntu Latest I don't and it builds successfully. 
```
/e/Programming/leaderboard-site (fixEslint)
$ pnpm build

> leaderboardsgg@3.0.0 build E:\Programming\leaderboard-site
> nuxt build

Nuxt CLI v3.0.0-rc.3                                                                                          00:54:57

 WARN  [kit] [compat] Using extendBuild in Nuxt 3 has no effect. Instead call extendWebpackConfig and extendViteConfig.

i Using Tailwind CSS from ~/assets\css\tailwind.css                                          nuxt:tailwindcss 00:54:59
i Merging Tailwind config from ~/tailwind.config.js                                          nuxt:tailwindcss 00:54:59

 WARN  [kit] [compat] Using extendBuild in Nuxt 3 has no effect. Instead call extendWebpackConfig and extendViteConfig.


 WARN  Sourcemap for "E:/Programming/leaderboard-site/pages/__tests__/index.test.ts" points to missing source files


 ERROR  This module cannot be imported in the Vue part of your app. [importing @nuxt/kit from node_modules/.pnpm/@nuxt+test-utils-edge@3.0.0-rc.3-27581242.8831e4a_jldfnizaobxnhpuvkzs4jcgpqe/node_modules/@nuxt/test-utils-edge/dist/index.mjs]


 ERROR  [vite]: Rollup failed to resolve import "vitest/dist/node.js" from "node_modules/.pnpm/@nuxt+test-utils-edge@3.0.0-rc.3-27581242.8831e4a_jldfnizaobxnhpuvkzs4jcgpqe/node_modules/@nuxt/test-utils-edge/dist/index.mjs".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`


 ERROR  [vite]: Rollup failed to resolve import "vitest/dist/node.js" from "node_modules/.pnpm/@nuxt+test-utils-edge@3.0.0-rc.3-27581242.8831e4a_jldfnizaobxnhpuvkzs4jcgpqe/node_modules/@nuxt/test-utils-edge/dist/index.mjs".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`

  This is most likely unintended because it can break your application at runtime.
  If you do want to externalize this module explicitly add it to
  `build.rollupOptions.external`
  at onRollupWarning (node_modules\.pnpm\vite@2.9.12\node_modules\vite\dist\node\chunks\dep-8f5c9290.js:41772:19)
  at onwarn (node_modules\.pnpm\vite@2.9.12\node_modules\vite\dist\node\chunks\dep-8f5c9290.js:41588:13)
  at Object.onwarn (node_modules\.pnpm\rollup@2.75.6\node_modules\rollup\dist\shared\rollup.js:23224:13)
  at ModuleLoader.handleResolveId (node_modules\.pnpm\rollup@2.75.6\node_modules\rollup\dist\shared\rollup.js:22508:26)
  at ModuleLoader.resolveDynamicImport (node_modules\.pnpm\rollup@2.75.6\node_modules\rollup\dist\shared\rollup.js:22560:120)
  at async node_modules\.pnpm\rollup@2.75.6\node_modules\rollup\dist\shared\rollup.js:22455:32

 ELIFECYCLE  Command failed with exit code 1.
```

### Additional context

My guesss as is mentioned in the logs it's regarding Vite/ Vitest. But I really haven't seen how they are the problem in this case and I tried using nuxt ignore file to ignore the test files but it still fails out.

**Comment by danielroe** [comment]
I can't say for sure, but try removing: `@nuxt/typescript-build` and `@nuxtjs/eslint-module` from your modules. The first is not required, and neither are supported.

**Comment by buffet-time** [comment]
I tried that @danielroe still getting the same console results back (but that's good info to know)
