### ISSUE TITLE
error TS2451: Cannot redeclare block-scoped variable

### ISSUE THREAD

**Issue by hermesalvesbr** [nuxt/framework#5439]
### Environment

```
npx nuxi info
Nuxt CLI v3.0.0-rc.3-27584539.9d28c0a                                                                                                                                 09:19:21
RootDir: /home/hermes/Projetos/nuxt/painel-sapl                                                                                                                       09:19:23
Nuxt project info:                                                                                                                                                    09:19:23

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.3-27584539.9d28c0a`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `publicRuntimeConfig`, `components`, `buildModules`, `tailwindcss`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `@nuxtjs/tailwindcss@5.1.2`
------------------------------

👉 Report an issue: https://github.com/nuxt/framework/issues/new                                                                                                      09:19:23

👉 Suggest an improvement: https://github.com/nuxt/framework/discussions/new

👉 Read documentation: https://v3.nuxtjs.org

```

### Reproduction

Type tsc for typescript check.

```
tsc
composables/useSessaoPlenaria.ts:129:9 - error TS2451: Cannot redeclare block-scoped variable 'useSessaoPlenaria'.

129   const useSessaoPlenaria: typeof SessaoPlenaria
            ~~~~~~~~~~~~~~~~~

  .nuxt/types/auto-imports.d.ts:79:9
    79   const useSessaoPlenaria: typeof import('../../composables/useSessaoPlenaria')['default']
               ~~~~~~~~~~~~~~~~~
    'useSessaoPlenaria' was also declared here.

composables/useUtils.ts:21:9 - error TS2451: Cannot redeclare block-scoped variable 'useUtils'.

21   const useUtils: typeof Utilities
           ~~~~~~~~

  .nuxt/types/auto-imports.d.ts:83:9
    83   const useUtils: typeof import('../../composables/useUtils')['default']
               ~~~~~~~~
    'useUtils' was also declared here.

nuxt.config.ts:2:32 - error TS7016: Could not find a declaration file for module '@tailwindcss/typography'. '/home/hermes/Projetos/nuxt/painel-sapl/node_modules/@tailwindcss/typography/src/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/tailwindcss__typography` if it exists or add a new declaration (.d.ts) file containing `declare module '@tailwindcss/typography';`

2 import tailwindTypography from '@tailwindcss/typography'
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~


Found 3 errors in 3 files.

Errors  Files
     1  composables/useSessaoPlenaria.ts:129
     1  composables/useUtils.ts:21
     1  nuxt.config.ts:2

```

### Describe the bug

It is checking the files in the .nuxt folder even though it says it should be ignored.

With that, you are not validating the typescript when you type tsc.

**tsconfig.json**
```
{
  "compilerOptions": {
    "module": "es2022",
    "esModuleInterop": true,
    "preserveConstEnums": true,
    "moduleResolution": "Node",
    "strict": true,
    "sourceMap": true,
    "target": "es2017"
  },
  "exclude": [
    ".nuxt/types/**"
  ],
  // https://v3.nuxtjs.org/concepts/typescript
  "extends": "./.nuxt/tsconfig.json"
}
```

### Additional context

If I put the .nuxt in eslintignore it doesn't work anymore.

**Comment by danielroe** [comment]
I can't replicate this. Does this still happen for you?

By the way, you should be able to run `npx nuxi typecheck` (or `npx vue-tsc --noEmit` - but you may need to install typescript or vue-tsc dependencies) for more accurate type-checking with Vue.

**Comment by hermesalvesbr** [comment]
_Thank you for your time with this issue._ 

Yes, the problem persist. I updated the tsconfig.json for not exclude .nuxt/types:

```
{
  "compilerOptions": {
    "module": "es2022",
    "esModuleInterop": true,
    "preserveConstEnums": true,
    "moduleResolution": "Node",
    "strict": true,
    "sourceMap": true,
    "target": "es2017"
  },
  // https://v3.nuxtjs.org/concepts/typescript
  "extends": "./.nuxt/tsconfig.json"
}
```
### npx nuxi typecheck
```
Nuxt CLI v3.0.0-rc.4                                                                                                                                                18:51:38
ℹ Using Tailwind CSS from ~/assets/css/tailwind.css                                                                                                nuxt:tailwindcss 18:51:39
ℹ Merging Tailwind config from ~/tailwind.config.js                                                                                                nuxt:tailwindcss 18:51:39
composables/useSessaoPlenaria.ts:129:9 - error TS2451: Cannot redeclare block-scoped variable 'useSessaoPlenaria'.

129   const useSessaoPlenaria: typeof SessaoPlenaria
            ~~~~~~~~~~~~~~~~~

  .nuxt/types/auto-imports.d.ts:79:9
    79   const useSessaoPlenaria: typeof import('../../composables/useSessaoPlenaria')['default']
               ~~~~~~~~~~~~~~~~~
    'useSessaoPlenaria' was also declared here.

composables/useUtils.ts:21:9 - error TS2451: Cannot redeclare block-scoped variable 'useUtils'.

21   const useUtils: typeof Utilities
           ~~~~~~~~

  .nuxt/types/auto-imports.d.ts:83:9
    83   const useUtils: typeof import('../../composables/useUtils')['default']
               ~~~~~~~~
    'useUtils' was also declared here.


Found 2 errors in 2 files.

Errors  Files
     1  composables/useSessaoPlenaria.ts:129
     1  composables/useUtils.ts:21

 ERROR  Command failed with exit code 2: vue-tsc --noEmit                                                                                                           18:51:42

  at makeError (node_modules/nuxi/dist/chunks/index5.mjs:1242:11)
  at handlePromise (node_modules/nuxi/dist/chunks/index5.mjs:2071:26)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async Object.invoke (node_modules/nuxi/dist/chunks/typecheck.mjs:41:7)
  at async _main (node_modules/nuxi/dist/cli.mjs:46:20)

```
### Maybe this problem was here: composables/useUtils.ts
```
class Utilities {
  nuxtApp = useNuxtApp()
  format(datef: Date) {
    const dateFormatter = new Intl.DateTimeFormat('pt-BR').format(datef)
    return dateFormatter
  }

  clock() {
    const currentTime = ref(new Date())
    const updateCurrentTime = () => {
      currentTime.value = new Date()
    }
    const updateTimeInterval = setInterval(updateCurrentTime, 1000)
    return {
      currentTime
    }
  }
}

declare global {
  const useUtils: typeof Utilities
}
export default Utilities
```
Because i define "useUtils" and .nuxt/types/auto-imports.d.ts:83:9 make the same thing.

**Comment by danielroe** [comment]
Yes. You don't need to define the type yourself - Nuxt does it for you. 👍
