### ISSUE TITLE
ERROR  Rollup error: Identifier 'useRuntimeConfig' has already been declared (Note that you need plugins to import files that are not JavaScript)

### ISSUE THREAD

**Issue by jamaluddinrumi** [nuxt/framework#5458]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `typescript`, `css`, `modules`, `runtimeConfig`, `buildModules`, `storyblok`, `build`
- Runtime Modules:  `-`
- Build Modules:    `@nuxtjs/tailwindcss@5.1.2`, `@vueuse/nuxt@8.6.0`, `@nuxtjs/partytown@1.2.1`, `@storyblok/nuxt@4.0.1`
------------------------------

### Reproduction

https://github.com/jamaluddinrumi/getanah.v3

### Describe the bug

yarn build is taking so long & end up with `ERROR  Rollup error: Identifier 'useRuntimeConfig' has already been declared (Note that you need plugins to import files that are not JavaScript)`

![Screen Shot 2022-06-14 at 6 56 36 PM](https://user-images.githubusercontent.com/446780/173571833-203d5e33-a854-45d5-88bb-2f52d5957ea8.png)

### Logs
```
yarn run v1.22.19
$ nuxi build
Nuxt CLI v3.0.0-rc.4                                                                                                                              18:12:39
ℹ Using Tailwind CSS from ~/assets/css/tailwind.css                                                                              nuxt:tailwindcss 18:12:50
ℹ Merging Tailwind config from ~/tailwind.config.js                                                                              nuxt:tailwindcss 18:12:50
ℹ Vite client warmed up in 42097ms                                                                                                                18:13:43
ℹ Client built in 56477ms                                                                                                                         18:13:57
ℹ Building server...                                                                                                                              18:13:58

 WARN  @storyblok/nuxt doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.

✔ Server built in 21451ms                                                                                                                         18:14:19
✔ Generated public .output/public                                                                                                           nitro 18:14:20
start Building server...                                                                                                                    nitro 18:14:20
        
 WARN  rollup-plugin-inject: failed to parse /www/getanah.v3/.nuxt/dist/server/server.mjs. Consider restricting the plugin to particular files via options.include


 ERROR  Rollup error: Identifier 'useRuntimeConfig' has already been declared (Note that you need plugins to import files that are not JavaScript)


 ERROR  Identifier 'useRuntimeConfig' has already been declared (Note that you need plugins to import files that are not JavaScript)              18:40:02

  at error (node_modules/rollup/dist/es/shared/rollup.js:1858:30)
  at Module.error (node_modules/rollup/dist/es/shared/rollup.js:12422:16)
  at Module.tryParse (node_modules/rollup/dist/es/shared/rollup.js:12799:25)
  at Module.setSource (node_modules/rollup/dist/es/shared/rollup.js:12704:24)
  at ModuleLoader.addModuleSource (node_modules/rollup/dist/es/shared/rollup.js:22178:20)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Command failed: node /Volumes/HDD/gangsar/.yvm/versions/v1.22.19/bin/yarn.js build
```

**Comment by loremru** [comment]
Same
