### ISSUE TITLE
definePageMete is not defined

### ISSUE THREAD

**Issue by zhouzilong2020** [nuxt/framework#5486]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `pnpm@6.32.3`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

1. Follow everything **exactly** listed at the [Quick Start Session](https://v3.nuxtjs.org/getting-started/quick-start).
2. Create ```pages``` and ```layouts``` folders.
3. Create a customized layout, and follow everything **exactly** listed at [layouts](https://v3.nuxtjs.org/guide/directory-structure/layouts) and [pages](https://v3.nuxtjs.org/guide/directory-structure/pages)
4. Try to start the server, got ```definePageMete is not defined```

Here is a reproduction repo: https://github.com/zhouzilong2020/nuxt3-definePageMete

### Describe the bug

definePageMete is not defined.

I noticed that there are some discussions at Jan, but I still came into the same issue.

### Additional context

SOS

### Logs

```shell
at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > key="/" >
[nuxt] [request error] definePageMete is not defined
  at setup (./.nuxt/dist/server/server.mjs:2838:5)  
  at _sfc_main.setup (./.nuxt/dist/server/server.mjs:2857:23)  
  at callWithErrorHandling (./node_modules/.pnpm/@vue+runtime-core@3.2.37/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:157:22)  
  at setupStatefulComponent (./node_modules/.pnpm/@vue+runtime-core@3.2.37/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7084:29)  
  at setupComponent (./node_modules/.pnpm/@vue+runtime-core@3.2.37/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7039:11)  
  at renderComponentVNode (./node_modules/.pnpm/@vue+server-renderer@3.2.37_vue@3.2.37/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:172:17)  
  at renderVNode (./node_modules/.pnpm/@vue+server-renderer@3.2.37_vue@3.2.37/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:295:22)  
  at renderVNode (./node_modules/.pnpm/@vue+server-renderer@3.2.37_vue@3.2.37/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:301:17)  
  at renderComponentSubTree (./node_modules/.pnpm/@vue+server-renderer@3.2.37_vue@3.2.37/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:259:13)  
  at renderComponentVNode (./node_modules/.pnpm/@vue+server-renderer@3.2.37_vue@3.2.37/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:188:16)
[nitro] [dev] [unhandledRejection] ReferenceError: definePageMete is not defined
    at setup (file:///Users/zhouzilong/nuxt3/nuxt-app/.nuxt/dist/server/server.mjs:2838:5)
    at _sfc_main.setup (file:///Users/zhouzilong/nuxt3/nuxt-app/.nuxt/dist/server/server.mjs:2857:23)
    at callWithErrorHandling (/Users/zhouzilong/nuxt3/nuxt-app/node_modules/.pnpm/@vue+runtime-core@3.2.37/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:157:22)
    at setupStatefulComponent (/Users/zhouzilong/nuxt3/nuxt-app/node_modules/.pnpm/@vue+runtime-core@3.2.37/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7084:29)
    at setupComponent (/Users/zhouzilong/nuxt3/nuxt-app/node_modules/.pnpm/@vue+runtime-core@3.2.37/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7039:11)
    at renderComponentVNode (/Users/zhouzilong/nuxt3/nuxt-app/node_modules/.pnpm/@vue+server-renderer@3.2.37_vue@3.2.37/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:172:17)
    at renderVNode (/Users/zhouzilong/nuxt3/nuxt-app/node_modules/.pnpm/@vue+server-renderer@3.2.37_vue@3.2.37/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:295:22)
    at renderVNode (/Users/zhouzilong/nuxt3/nuxt-app/node_modules/.pnpm/@vue+server-renderer@3.2.37_vue@3.2.37/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:301:17)
    at renderComponentSubTree (/Users/zhouzilong/nuxt3/nuxt-app/node_modules/.pnpm/@vue+server-renderer@3.2.37_vue@3.2.37/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:259:13)
    at renderComponentVNode (/Users/zhouzilong/nuxt3/nuxt-app/node_modules/.pnpm/@vue+server-renderer@3.2.37_vue@3.2.37/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:188:16)```
```

**Comment by jkirkpatrick** [comment]
In your repo there appears to be a [typo](https://github.com/zhouzilong2020/nuxt3-definePageMete/blob/3b6f440171578db02d02527564fca8a068f0a7bc/nuxt-app/pages/index.vue#L6). I did not read all of the instructions you followed to see if the documentation is correct, however the [changing the layout](https://v3.nuxtjs.org/guide/directory-structure/layouts/#example-changing-the-layout) example does show correct usage.

The name of the function should be `definePageMeta` - note the last character in the function name is 'a' (as opposed to 'e' as you have written)

```ts
<script lang="ts" setup>
definePageMeta({ 
  // your code here
});
</script>
```

**Comment by Aynh** [comment]
That's a typo, `definePageMete` should've be `definePageMeta`.

**Comment by sppmstar** [comment]
i tried the code example above and get this error:

```
[nitro] [dev] [unhandledRejection] ReferenceError: definePageMeta is not defined
    at setup (file:///Users/sperica/Temp/lineup-editor/playground/.nuxt/dist/server/server.mjs:3473:5)
    at _sfc_main.setup (file:///Users/sperica/Temp/lineup-editor/playground/.nuxt/dist/server/server.mjs:3495:23)
    at callWithErrorHandling (/Users/sperica/Temp/lineup-editor/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:157:22)
    at setupStatefulComponent (/Users/sperica/Temp/lineup-editor/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7084:29)
    at setupComponent (/Users/sperica/Temp/lineup-editor/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7039:11)
    at renderComponentVNode (/Users/sperica/Temp/lineup-editor/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:172:17)
    at Module.ssrRenderComponent (/Users/sperica/Temp/lineup-editor/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:608:12)
    at default (file:///Users/sperica/Temp/lineup-editor/playground/.nuxt/dist/server/server.mjs:2707:37)
    at Module.ssrRenderSuspense (/Users/sperica/Temp/lineup-editor/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:946:9)
    at _sfc_ssrRender (file:///Users/sperica/Temp/lineup-editor/playground/.nuxt/dist/server/server.mjs:2702:25)
```

**Comment by danielroe** [comment]
Would you provide a reproduction?
