### ISSUE TITLE
upgrading to rc.4 causing `nuxi dev` error although `nuxi build` succeeded

### ISSUE THREAD

**Issue by NexZhu** [nuxt/framework#5488]
### Environment

Centos 9
Node.js v16.15.1
Nuxt 3.0.0-rc.4

### Reproduction

.

### Describe the bug

My project works fine with rc.3, after upgrading to rc.4, this issue appeared, causing `nuxi dev` to hang up:
https://github.com/nuxt/framework/issues/5235

Then after upgrading `nitropack` to `4.8.0`, `nuxi build` succeeded but now `nuxi dev` failed with this error:
```
[nuxt] [request error] _47root_47dev_47web_47baas_45front_47_46nuxt_47components_46plugin_46mjs is not defined
  at $id_70e40f96 (./.nuxt/dist/server/server.mjs:1658:3)  
  at async __instantiateModule__ (./.nuxt/dist/server/server.mjs:23596:3)
```

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏
