### ISSUE TITLE
Client plugins throw "Property accessed during render, but is not defined on the instance." when referenced.

### ISSUE THREAD

**Issue by Curstantine** [nuxt/framework#5514]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v18.3.0`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `yarn@3.2.1`
- Builder:          `vite`
- User Config:      `typescript`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

1. Init from the official template.
2. Add a plugin with `.client` prefix.
3. Make the plugin provide something from `NuxtApp` instance.
4. Reference the provided data inside the "app" (See screenshot)

### Describe the bug

App fails to render when a property provided by the `NuxtApp` is referenced while throwing "Property accessed during render, but is not defined on the instance.", though removing the prefix makes it work, but that revokes access to client side properties.

Screenshots:

![image](https://user-images.githubusercontent.com/69104500/174436244-54236f56-3b85-4609-bc7d-a84db3e4c83f.png)

### Logs

```shell
Nuxt CLI v3.0.0-rc.4                                                                                                   
 > Local:    http://localhost:3000/


 ERROR  (node:12412) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

i Vite client warmed up in 2948ms                                                                                      17:34:45
i Vite server warmed up in 1605ms                                                                                      17:34:46
√ Vite server built in 3153ms                                                                                          17:34:48
√ Nitro built in 3182 ms                                                                                         nitro 17:34:51
[Vue warn]: Property "$test" was accessed during render but is not defined on instance.
[nitro] [dev] [unhandledRejection] TypeError: _ctx.$test is not a function
    at _sfc_ssrRender (file:///<REDACTED>/frontend/.nuxt/dist/server/server.mjs:3407:106)
    at renderComponentSubTree (<REDACTED>\frontend\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:253:13)
    at renderComponentVNode (<REDACTED>\frontend\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:188:16)
    at Module.ssrRenderComponent (<REDACTED>\frontend\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:608:12)
    at default (file:///<REDACTED>/frontend/.nuxt/dist/server/server.mjs:2660:37)
    at Module.ssrRenderSuspense (<REDACTED>\frontend\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:946:9)
    at _sfc_ssrRender (file:///<REDACTED>/frontend/.nuxt/dist/server/server.mjs:2655:25)
    at renderComponentSubTree (<REDACTED>\frontend\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:253:13)
    at renderComponentVNode (<REDACTED>\frontend\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:188:16)
    at renderToString (<REDACTED>\frontend\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:446:26)
[Vue warn]: Property "$test" was accessed during render but is not defined on instance.
[nitro] [dev] [unhandledRejection] TypeError: _ctx.$test is not a function
    at _sfc_ssrRender (file:///<REDACTED>/frontend/.nuxt/dist/server/server.mjs:3407:106)
    at renderComponentSubTree (<REDACTED>\frontend\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:253:13)
    at renderComponentVNode (<REDACTED>\frontend\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:188:16)
    at Module.ssrRenderComponent (<REDACTED>\frontend\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:608:12)
    at default (file:///<REDACTED>/frontend/.nuxt/dist/server/server.mjs:2660:37)
    at Module.ssrRenderSuspense (<REDACTED>\frontend\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:946:9)
    at _sfc_ssrRender (file:///<REDACTED>/frontend/.nuxt/dist/server/server.mjs:2655:25)
    at renderComponentSubTree (<REDACTED>\frontend\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:253:13)
    at renderComponentVNode (<REDACTED>\frontend\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:188:16)
    at renderToString (<REDACTED>\frontend\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:446:26)
```

**Comment by danielroe** [comment]
I'm afraid that is expected. If you only inject a property on client side, but try to reference it on server-side, Nuxt is right to throw an error. What you can do is create two plugins, one server and one client, that inject the same property with different behaviour.

**Comment by Al-Planet** [comment]
> I'm afraid that is expected. If you only inject a property on client side, but try to reference it on server-side, Nuxt is right to throw an error. What you can do is create two plugins, one server and one client, that inject the same property with different behaviour.

how to diff between client side and server ? 
how about config
