### ISSUE TITLE
nuxt generate fails with [request error] navigator is not defined

### ISSUE THREAD

**Issue by kitsune-guuji** [nuxt/framework#5572]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `typescript`, `modules`, `css`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.1.3`, `@pinia/nuxt@0.1.9`, `@nuxtjs/color-mode@3.1.4`
- Build Modules:    `-`
------------------------------

### Reproduction

Reproduction steps are very unclear, please, refer to additional context.

### Describe the bug

Using `nuxt generate` fails while `ssr: false` is not in the nuxt config file.

### Additional context

I've been trying to move to Nuxt in order to gain some benefits of prerendring. Before actually trying it, I have had set these settings: 
  - `ssr: false`
  - `target: "static"`

After I finished migrating all my components and other code, I have deleted those settings and tried to use `yarn generate` and it failed with `navigator is not defined`. It also looks like `ssr` setting is the one that causes such behavior.

Here is the [permalink to the code](https://github.com/kitsune-guuji/gvp/tree/538823650b01c5d43d78dc527381500b87a132b0) (the repo contains a git submodule just in case someone wants to clone it and try). 

P.S. This might not even be an issue with Nuxt itself, but with my code, however the error message is very vague and for someone who has little experience it's quite hard to figure out what's wrong here, some help would be really appreciated :( 

### Logs

```shell
$ yarn generate

yarn run v1.22.17
$ nuxt generate
Nuxt CLI v3.0.0-rc.4                                                           21:12:04
ℹ Using default Tailwind CSS file from runtime/tailwind.css   nuxt:tailwindcss 21:12:05
ℹ Merging Tailwind config from ~/tailwind.config.js           nuxt:tailwindcss 21:12:05
ℹ Vite client warmed up in 1077ms                                              21:12:07
ℹ Client built in 4194ms                                                       21:12:10
ℹ Building server...                                                           21:12:10
✔ Server built in 904ms                                                        21:12:11
✔ Generated public .output/public                                        nitro 21:12:11
ℹ Initializing prerenderer                                               nitro 21:12:11
ℹ Prerendering 1 initial routes with crawler                             nitro 21:12:13

 ERROR  [nuxt] [request error] navigator is not defined                        21:12:14
  at ./.nuxt/prerender/chunks/app/server.mjs:6500:16  
  at fn (./.nuxt/prerender/chunks/app/server.mjs:3530:27)  
  at Object.callAsync (./node_modules/unctx/dist/index.mjs:41:19)  
  at callWithNuxt (./.nuxt/prerender/chunks/app/server.mjs:3532:23)  
  at applyPlugin (./.nuxt/prerender/chunks/app/server.mjs:3492:39)  
  at applyPlugins (./.nuxt/prerender/chunks/app/server.mjs:3501:11)  
  at async createNuxtAppServer (./.nuxt/prerender/chunks/app/server.mjs:6917:7)  
  at async Object.renderToString (./.nuxt/prerender/chunks/renderer.mjs:270:19)  
  at async ./.nuxt/prerender/chunks/renderer.mjs:13011:20  
  at async ./node_modules/h3/dist/index.mjs:420:19


 ERROR  [unhandledRejection] navigator is not defined                          21:12:14

  at ReactiveEffect.fn (.nuxt/prerender/chunks/app/server.mjs:6726:7)
  at ReactiveEffect.run (.nuxt/prerender/chunks/renderer.mjs:1378:25)
  at ComputedRefImpl.get value [as value] (.nuxt/prerender/chunks/renderer.mjs:2346:39)
  at Object.unref (.nuxt/prerender/chunks/renderer.mjs:2254:31)
  at .nuxt/prerender/chunks/app/server.mjs:6743:182
  at renderComponentSubTree (.nuxt/prerender/chunks/renderer.mjs:12143:13)
  at renderComponentVNode (.nuxt/prerender/chunks/renderer.mjs:12078:16)
  at renderVNode (.nuxt/prerender/chunks/renderer.mjs:12185:22)
  at renderVNodeChildren (.nuxt/prerender/chunks/renderer.mjs:12200:9)
  at renderElementVNode (.nuxt/prerender/chunks/renderer.mjs:12251:17)


 ERROR  [nitro] [dev] [unhandledRejection] ReferenceError: navigator is not defined

  ├─ / (383ms) (Error: [500] Internal Server Error)                      nitro 21:12:14
✔ You can now deploy .output/public to any static hosting!                     21:12:14
```

**Comment by danielroe** [comment]
Somewhere in your code (or more likely a library you are depending on) there is a reference to the global `navigator`. This doesn't exist on SSR - hence the error.

**Comment by kitsune-guuji** [comment]
> Somewhere in your code (or more likely a library you are depending on) there is a reference to the global `navigator`. This doesn't exist on SSR - hence the error.

Oh, I see, makes sense now. Tomorrow I will definitely look for the source of the problem, thank you very much! ❤️

**Comment by kitsune-guuji** [comment]
Found what was causing the issue and fixed it. Thank you very much once again!
