### ISSUE TITLE
`HOST` env variable incorrectly used

### ISSUE THREAD

**Issue by tamasfe** [nuxt/framework#5651]
### Environment

```
------------------------------
- Operating System: `Linux`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `yarn@3.2.1`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
```

### Reproduction

```sh
HOST=whatever yarn dev --host 127.0.0.1
```

### Describe the bug

If the `HOST` environment variable is set, pretty much all operations fail with the following opaque error message:

```
ERROR  Unable to obtain an available random port number!                                                                                                                                                           
  at getRandomPort (node_modules/nuxi/dist/chunks/index7.mjs:199:11)
  at async getPort (node_modules/nuxi/dist/chunks/index7.mjs:192:25)
  at async listen (node_modules/nuxi/dist/chunks/index7.mjs:664:16)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6716:22)
  at async _main (node_modules/nuxi/dist/cli.mjs:46:20)
```

Any `--host` or `--port` flags are also ignored.

**Comment by danielroe** [comment]
I think we could possibly improve the error message in https://github.com/unjs/get-port-please/, but the use of this environment variable to set the host is documented here: https://v3.nuxtjs.org/api/commands/dev#nuxi-dev.

**Comment by tamasfe** [comment]
I don't think it's _just_ a documentation/error message issue:
- I would expect the `--host` and `--port` cli argument to override whatever env vars are set
- The use of the `HOST` env var just leads to conflicts like this one and does not make too much sense since a properly prefixed `NUXT_HOST` exists
