### ISSUE TITLE
nuxt/bridge - cannot find module 'nuxt' at startup

### ISSUE THREAD

**Issue by kadlinobit** [nuxt/framework#5692]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.15.1`
- Nuxt Version:     `2.16.0-27610581.123206cb`
- Package Manager:  `npm@8.11.0`
- Builder:          `webpack`
- User Config:      `alias`, `head`, `css`, `plugins`, `components`, `buildModules`, `modules`, `i18n`, `axios`, `build`, `publicRuntimeConfig`, `privateRuntimeConfig`, `bridge`
- Runtime Modules:  `@nuxtjs/axios@5.13.6`, `@nuxtjs/auth-next@5.0.0-1641536721.10cfcc9`, `@nuxtjs/i18n@7.2.2`
- Build Modules:    `@nuxtjs/eslint-module@3.1.0`, `@pinia/nuxt@0.1.9`, `@nuxt/bridge@3.0.0-27611430.cf4761a`

### Reproduction

[https://github.com/kadlinobit/djspot-fe/tree/vuex-to-pinia](https://github.com/kadlinobit/djspot-fe/tree/vuex-to-pinia)
Branch: vuex-to-pinia

### Describe the bug

After fresh installation, when running dev server (nuxi dev) there is an error:

```sh
 ERROR  Cannot start nuxt:  Cannot find module 'nuxt'                                                                                     19:47:24
Require stack:
- /Users/kadlec/projects/djspot-fe/index.js

  Require stack:
  - index.js
  at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
  at Function.resolve (node:internal/modules/cjs/helpers:108:19)
  at Function._resolve [as resolve] (node_modules/jiti/dist/jiti.js:1:108226)
  at resolveModule (node_modules/@nuxt/kit/dist/index.mjs:276:29)
  at importModule (node_modules/@nuxt/kit/dist/index.mjs:299:24)
  at loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:690:92)
  at async load (node_modules/@nuxt/bridge/node_modules/nuxi/dist/chunks/dev.mjs:6740:23)
  at async Object.invoke (node_modules/@nuxt/bridge/node_modules/nuxi/dist/chunks/dev.mjs:6786:5)
  at async _main (node_modules/@nuxt/bridge/node_modules/nuxi/dist/cli.mjs:46:20)
```

### Logs

```shell
Nuxt CLI v3.0.0-rc.4                                                                                                                      19:47:24
                                                                                                                                          19:47:24
  > Local:    http://localhost:3000/ 
  > Network:  http://192.168.0.102:3000/


 ERROR  Cannot start nuxt:  Cannot find module 'nuxt'                                                                                     19:47:24
Require stack:
- /Users/kadlec/projects/djspot-fe/index.js

  Require stack:
  - index.js
  at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
  at Function.resolve (node:internal/modules/cjs/helpers:108:19)
  at Function._resolve [as resolve] (node_modules/jiti/dist/jiti.js:1:108226)
  at resolveModule (node_modules/@nuxt/kit/dist/index.mjs:276:29)
  at importModule (node_modules/@nuxt/kit/dist/index.mjs:299:24)
  at loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:690:92)
  at async load (node_modules/@nuxt/bridge/node_modules/nuxi/dist/chunks/dev.mjs:6740:23)
  at async Object.invoke (node_modules/@nuxt/bridge/node_modules/nuxi/dist/chunks/dev.mjs:6786:5)
  at async _main (node_modules/@nuxt/bridge/node_modules/nuxi/dist/cli.mjs:46:20)
```

**Comment by brogier** [comment]
Just updated to RC4 and noticed

```

  "devDependencies": {
    "nuxt": "3.0.0-rc.4"
  },
```

used to be "nuxt3": "latest"

Also change the top line in nuxt.config.ts to `import { defineNuxtConfig } from 'nuxt'` instead of nuxt3

**Comment by AndreyYolkin** [comment]
> Just updated to RC4 and noticed
> 
> ```
> 
>   "devDependencies": {
>     "nuxt": "3.0.0-rc.4"
>   },
> ```
> 
> used to be "nuxt3": "latest"
> 
> Also change the top line in nuxt.config.ts to `import { defineNuxtConfig } from 'nuxt'` instead of nuxt3

Author used nuxt 2 with bridge, which does not have nuxt3 or rc packages. But I got the same error yesterday in my nuxt2b app
