### ISSUE TITLE
npm run build failed with "@nuxtjs/axios": "^5.13.6"  "nuxt": "3.0.0-rc.4"

### ISSUE THREAD

**Issue by tonytony2020** [nuxt/framework#5789]
### Environment

Nuxt CLI v3.0.0-rc.4                                                                                                                                              23:38:27
RootDir: C:\work\src\nuxt-app                                                                                                                                     23:38:29
Nuxt project info:                                                                                                                                                23:38:29

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `yarn@1.22.11`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@nuxtjs/axios@5.13.6`, `@nuxtjs/proxy@2.1.0`
- Build Modules:    `-`
------------------------------

### Reproduction

- create a new project following https://v3.nuxtjs.org/getting-started/quick-start/
- add Axios module following https://axios.nuxtjs.org/setup
- configure nuxt walk around issue `ERROR [unhandledRejection] serialize is not defined` https://github.com/nuxt-community/axios-module/issues/560
- issue `npm run build`

### Describe the bug

npm run build failed with "@nuxtjs/axios": "^5.13.6"  "nuxt": "3.0.0-rc.4"

### Additional context

```
 ERROR  filename.split is not a function                                                                                                                          23:36:43  

  at normalizePath (node_modules\vite\dist\node\chunks\dep-c9998dc6.js:2417:21)
  at getMatcherString$1 (node_modules\vite\dist\node\chunks\dep-c9998dc6.js:2422:16)
  at Object.test (node_modules\vite\dist\node\chunks\dep-c9998dc6.js:2441:33)
  at result (node_modules\vite\dist\node\chunks\dep-c9998dc6.js:2457:25)
  at Array.filter (<anonymous>)
  at resolveSSRExternal (node_modules\vite\dist\node\chunks\dep-c9998dc6.js:41136:31)
  at doBuild (node_modules\vite\dist\node\chunks\dep-c9998dc6.js:41598:36)
  at async Module.build (node_modules\vite\dist\node\chunks\dep-c9998dc6.js:41552:16)
  at async buildServer (/C:/work/src/nuxt-app/node_modules/@nuxt/vite-builder/dist/index.mjs:642:5)
  at async bundle (/C:/work/src/nuxt-app/node_modules/@nuxt/vite-builder/dist/index.mjs:841:3)
```

### Logs

```shell
C:\work\src\nuxt-app>npm run build 

> build
> nuxt build

Nuxt CLI v3.0.0-rc.4                                                                                                                                              23:33:32
i Client built in 2090ms                                                                                                                                          23:33:37
i Building server...                                                                                                                                              23:33:37
i Vite client warmed up in 2144ms                                                                                                                                 23:33:37

 ERROR  filename.split is not a function                                                                                                                          23:33:37  

  at normalizePath (node_modules\vite\dist\node\chunks\dep-c9998dc6.js:2417:21)
  at getMatcherString$1 (node_modules\vite\dist\node\chunks\dep-c9998dc6.js:2422:16)
  at Object.test (node_modules\vite\dist\node\chunks\dep-c9998dc6.js:2441:33)
  at result (node_modules\vite\dist\node\chunks\dep-c9998dc6.js:2457:25)
  at Array.filter (<anonymous>)
  at resolveSSRExternal (node_modules\vite\dist\node\chunks\dep-c9998dc6.js:41136:31)
  at doBuild (node_modules\vite\dist\node\chunks\dep-c9998dc6.js:41598:36)
  at async Module.build (node_modules\vite\dist\node\chunks\dep-c9998dc6.js:41552:16)
  at async buildServer (/C:/work/src/nuxt-app/node_modules/@nuxt/vite-builder/dist/index.mjs:642:5)
  at async bundle (/C:/work/src/nuxt-app/node_modules/@nuxt/vite-builder/dist/index.mjs:841:3)

```
```

**Comment by danielroe** [comment]
This module is not yet compatible with Nuxt 3.
