### ISSUE TITLE
`nuxt dev` is failed by a module file name contain `entry`

### ISSUE THREAD

**Issue by toshusai** [nuxt/framework#5954]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.5`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/toshusai/nuxt3-vite-error

1. yarn install
2. yarn dev

### Describe the bug

`nuxt dev` is failed when module include a file that file name include 'entry', like 'BrandSentry.js'. 

### Logs

```shell
ERROR  Cannot start nuxt:  Error: Cannot find module /node_modules/@vicons/tabler/es/BrandSentry.js imported from file:///Users/XXXX/Develop/nuxt3-vite-error, file:///Users/XXXX/Develop/nuxt3-vite-error/node_modules

  at resolvePath (node_modules/mlly/dist/index.mjs:972:10)
  at isValidNodeImport (node_modules/mlly/dist/index.mjs:1055:30)
  at isExternal (node_modules/externality/dist/index.mjs:122:49)
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async transformRequest (node_modules/@nuxt/vite-builder/dist/index.mjs:388:7)
  at async transformRequestRecursive (node_modules/@nuxt/vite-builder/dist/index.mjs:420:15)
  at async transformRequestRecursive (node_modules/@nuxt/vite-builder/dist/index.mjs:429:5)
  at async transformRequestRecursive (node_modules/@nuxt/vite-builder/dist/index.mjs:429:5)
  at async transformRequestRecursive (node_modules/@nuxt/vite-builder/dist/index.mjs:429:5)
```

**Comment by mhsdev** [comment]
similar issue

 ```
ERROR  Cannot start nuxt:  Cannot find module '@nuxt/vite-builder'                                                          18:10:50
Require stack:
- /home/user/www/my-app/index.js

  Require stack:
  - index.js
  at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
  at Function.resolve (node:internal/modules/cjs/helpers:108:19)
  at Function._resolve [as resolve] (node_modules/jiti/dist/jiti.js:1:108226)
  at resolveModule (node_modules/@nuxt/kit/dist/index.mjs:276:29)
  at importModule (node_modules/@nuxt/kit/dist/index.mjs:299:24)
  at bundle (node_modules/nuxt/dist/index.mjs:1741:82)
  at build (node_modules/nuxt/dist/index.mjs:1717:11)
  at async Promise.all (index 1)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6752:9)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6795:5)
```
