### ISSUE TITLE
`[rc.5]` Cannot set properties of undefined (setting 'pinia')

### ISSUE THREAD

**Issue by ImamAlfariziSyahputra** [nuxt/framework#5955]
### Environment

Nuxt project info:

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.5`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `alias`, `modules`, `build`, `css`, `vite`, `plugins`, `runtimeConfig`, `colorMode`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.3.0`, `@nuxtjs/color-mode@3.1.4`, `@pinia/nuxt@0.1.9`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/github/piniajs/example-nuxt-3

### Describe the bug

After upgrading my project from rc.4 to rc.5, i got this pinia error. even i try the Demo of using Nuxt 3 with Pinia from Pinia's official github example, its got the same error too. how to fix this?

### Logs

```shell
500
Cannot set properties of undefined (setting 'pinia')

at PiniaNuxtPlugin (/C:/Users/Imam%20Alfarizi/Desktop/Code%202022/Work/systics-nuxt/.nuxt/dist/server/server.mjs:59681:31)
at /C:/Users/Imam%20Alfarizi/Desktop/Code%202022/Work/systics-nuxt/.nuxt/dist/server/server.mjs:518:27
at fn (/C:/Users/Imam%20Alfarizi/Desktop/Code%202022/Work/systics-nuxt/.nuxt/dist/server/server.mjs:547:27)
at Object.callAsync (/C:/Users/Imam%20Alfarizi/Desktop/Code%202022/Work/systics-nuxt/node_modules/unctx/dist/index.mjs:41:19)
at callWithNuxt (/C:/Users/Imam%20Alfarizi/Desktop/Code%202022/Work/systics-nuxt/.nuxt/dist/server/server.mjs:549:23)
at applyPlugin (/C:/Users/Imam%20Alfarizi/Desktop/Code%202022/Work/systics-nuxt/.nuxt/dist/server/server.mjs:493:29)
at Module.applyPlugins (/C:/Users/Imam%20Alfarizi/Desktop/Code%202022/Work/systics-nuxt/.nuxt/dist/server/server.mjs:503:11)
at async createNuxtAppServer (/C:/Users/Imam%20Alfarizi/Desktop/Code%202022/Work/systics-nuxt/.nuxt/dist/server/server.mjs:46:7)
at async Object.renderToString (/C:/Users/Imam%20Alfarizi/Desktop/Code%202022/Work/systics-nuxt/node_modules/vue-bundle-renderer/dist/index.mjs:264:19)
at async /C:/Users/Imam%20Alfarizi/Desktop/Code%202022/Work/systics-nuxt/.nuxt/dev/index.mjs:473:20
```

**Comment by ImamAlfariziSyahputra** [comment]
Working fine after upgrading  `@pinia/nuxt ` package to the latest version.
