### ISSUE TITLE
Missing "./dist/app/entry" export in "nuxt3" package 

### ISSUE THREAD

**Issue by aligzl** [nuxt/framework#6087]
### Environment

Operating System: Windows 11
Node Version: v16.15.1
Nuxt Version:3.0.0-rc.6-27641313.416f98b
Package Manager: yarn@1.22.19

Runtime Modules: -
Build Modules: - pinia tailwindcss

### Reproduction

I cant provide Reproduction this happens only windows

### Describe the bug

Cant start the nuxt after rc-6 on windows os

### Logs

```shell
ERROR  Missing "./dist/app/entry" export in "nuxt3" package                                                                              16:24:22

  at bail (/D:/git/honeymoon/honeymoon-frontend/node_modules/vite/dist/node/chunks/dep-1513d487.js:33603:8)
  at resolve (/D:/git/honeymoon/honeymoon-frontend/node_modules/vite/dist/node/chunks/dep-1513d487.js:33680:10)
  at resolveExports (/D:/git/honeymoon/honeymoon-frontend/node_modules/vite/dist/node/chunks/dep-1513d487.js:34417:12)
  at resolveDeepImport (/D:/git/honeymoon/honeymoon-frontend/node_modules/vite/dist/node/chunks/dep-1513d487.js:34435:31)
  at tryNodeResolve (/D:/git/honeymoon/honeymoon-frontend/node_modules/vite/dist/node/chunks/dep-1513d487.js:34160:20)
  at Context.resolveId (/D:/git/honeymoon/honeymoon-frontend/node_modules/vite/dist/node/chunks/dep-1513d487.js:33897:32)
  at Object.resolveId (/D:/git/honeymoon/honeymoon-frontend/node_modules/vite/dist/node/chunks/dep-1513d487.js:35209:55)
  at async Context.resolve (/D:/git/honeymoon/honeymoon-frontend/node_modules/vite/dist/node/chunks/dep-1513d487.js:34974:23)
  at async Object.resolveId (/D:/git/honeymoon/honeymoon-frontend/node_modules/vite/dist/node/chunks/dep-1513d487.js:35209:32)
  at async ModuleGraph.resolveUrl (/D:/git/honeymoon/honeymoon-frontend/node_modules/vite/dist/node/chunks/dep-1513d487.js:57784:26)


 WARN  [SSR] Error transforming D:/git/honeymoon/honeymoon-frontend/node_modules/nuxt/dist/app/entry: Missing "./dist/app/entry" export in "nuxt3" p
ackage

  at bail (/D:/git/honeymoon/honeymoon-frontend/node_modules/vite/dist/node/chunks/dep-1513d487.js:33603:8)
  at resolve (/D:/git/honeymoon/honeymoon-frontend/node_modules/vite/dist/node/chunks/dep-1513d487.js:33680:10)
  at resolveExports (/D:/git/honeymoon/honeymoon-frontend/node_modules/vite/dist/node/chunks/dep-1513d487.js:34417:12)
  at resolveDeepImport (/D:/git/honeymoon/honeymoon-frontend/node_modules/vite/dist/node/chunks/dep-1513d487.js:34435:31)
  at tryNodeResolve (/D:/git/honeymoon/honeymoon-frontend/node_modules/vite/dist/node/chunks/dep-1513d487.js:34160:20)
  at Context.resolveId (/D:/git/honeymoon/honeymoon-frontend/node_modules/vite/dist/node/chunks/dep-1513d487.js:33897:32)
  at Object.resolveId (/D:/git/honeymoon/honeymoon-frontend/node_modules/vite/dist/node/chunks/dep-1513d487.js:35209:55)
  at async ModuleGraph.resolveUrl (/D:/git/honeymoon/honeymoon-frontend/node_modules/vite/dist/node/chunks/dep-1513d487.js:57784:26)
  at async ModuleGraph.getModuleByUrl (/D:/git/honeymoon/honeymoon-frontend/node_modules/vite/dist/node/chunks/dep-1513d487.js:57661:23)
  at async doTransform (/D:/git/honeymoon/honeymoon-frontend/node_modules/vite/dist/node/chunks/dep-1513d487.js:39687:20)


 ERROR  Missing "./dist/app/entry" export in "nuxt3" package                                                                              16:24:22

  at bail (/D:/git/honeymoon/honeymoon-frontend/node_modules/vite/dist/node/chunks/dep-1513d487.js:33603:8)
  at resolve (/D:/git/honeymoon/honeymoon-frontend/node_modules/vite/dist/node/chunks/dep-1513d487.js:33680:10)
  at resolveExports (/D:/git/honeymoon/honeymoon-frontend/node_modules/vite/dist/node/chunks/dep-1513d487.js:34417:12)
  at resolveDeepImport (/D:/git/honeymoon/honeymoon-frontend/node_modules/vite/dist/node/chunks/dep-1513d487.js:34435:31)
  at tryNodeResolve (/D:/git/honeymoon/honeymoon-frontend/node_modules/vite/dist/node/chunks/dep-1513d487.js:34160:20)
  at Context.resolveId (/D:/git/honeymoon/honeymoon-frontend/node_modules/vite/dist/node/chunks/dep-1513d487.js:33897:32)
  at Object.resolveId (/D:/git/honeymoon/honeymoon-frontend/node_modules/vite/dist/node/chunks/dep-1513d487.js:35209:55)
  at async Context.resolve (/D:/git/honeymoon/honeymoon-frontend/node_modules/vite/dist/node/chunks/dep-1513d487.js:34974:23)
  at async Object.resolveId (/D:/git/honeymoon/honeymoon-frontend/node_modules/vite/dist/node/chunks/dep-1513d487.js:35209:32)
  at async ModuleGraph.resolveUrl (/D:/git/honeymoon/honeymoon-frontend/node_modules/vite/dist/node/chunks/dep-1513d487.js:57784:26)
```

**Comment by ironytr** [comment]
same, windows 11 nuxt3@latest

 ERROR  Missing "./dist/app/entry" export in "nuxt3" package

**Comment by szymonlankauf** [comment]
I have the same issue on Windows 10 with pnpm, after upgrading Nuxt version from `3.0.0-rc.6-27646047.133723f` to `3.0.0-rc.6-27647394.5e62e0f`

Env:
- Operating System: `Windows_NT`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.6-27647394.5e62e0f`
- Package Manager:  `pnpm@7.5.2`
- Builder:          `vite`
- User Config:      `buildModules`, `build`, `vue`, `vite`, `runtimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.3.1`, `@nuxtjs/tailwindcss@5.3.1`, `@vueuse/nuxt@9.0.0`

Installed packages with `pnpm i --shamfully-hoist` in case it turns out to be relevant

**Comment by ironytr** [comment]
> Would you provide a reproduction? A minimal github repo would be perfect. 🙏

Hello danielroe, create just new project
`
npx nuxi init nuxt-app
yarn upgrade nuxt@npm:nuxt3@latest
`

**Comment by a-witkowski** [comment]
@danielroe, same for me in https://github.com/a-witkowski/nuxt-app

```
 ERROR  Missing "./dist/app/entry" export in "nuxt3" package                                                                                                                                                                                                                20:01:57

  at bail (/D:/projects/nuxt-app/node_modules/vite/dist/node/chunks/dep-c6273c7a.js:33604:8)
  at resolve (/D:/projects/nuxt-app/node_modules/vite/dist/node/chunks/dep-c6273c7a.js:33681:10)
  at resolveExports (/D:/projects/nuxt-app/node_modules/vite/dist/node/chunks/dep-c6273c7a.js:34422:12)
  at resolveDeepImport (/D:/projects/nuxt-app/node_modules/vite/dist/node/chunks/dep-c6273c7a.js:34440:31)
  at tryNodeResolve (/D:/projects/nuxt-app/node_modules/vite/dist/node/chunks/dep-c6273c7a.js:34161:20)
  at Context.resolveId (/D:/projects/nuxt-app/node_modules/vite/dist/node/chunks/dep-c6273c7a.js:33898:32)
  at Object.resolveId (/D:/projects/nuxt-app/node_modules/vite/dist/node/chunks/dep-c6273c7a.js:35216:55)
  at async Context.resolve (/D:/projects/nuxt-app/node_modules/vite/dist/node/chunks/dep-c6273c7a.js:34981:23)
  at async Object.resolveId (/D:/projects/nuxt-app/node_modules/vite/dist/node/chunks/dep-c6273c7a.js:35216:32)
  at async ModuleGraph.resolveUrl (/D:/projects/nuxt-app/node_modules/vite/dist/node/chunks/dep-c6273c7a.js:57822:26)


 ERROR  Missing "./dist/app/entry" export in "nuxt3" package                                                                                                                                                                                                                20:01:57  

  at bail (/D:/projects/nuxt-app/node_modules/vite/dist/node/chunks/dep-c6273c7a.js:33604:8)
  at resolve (/D:/projects/nuxt-app/node_modules/vite/dist/node/chunks/dep-c6273c7a.js:33681:10)
  at resolveExports (/D:/projects/nuxt-app/node_modules/vite/dist/node/chunks/dep-c6273c7a.js:34422:12)
  at resolveDeepImport (/D:/projects/nuxt-app/node_modules/vite/dist/node/chunks/dep-c6273c7a.js:34440:31)
  at tryNodeResolve (/D:/projects/nuxt-app/node_modules/vite/dist/node/chunks/dep-c6273c7a.js:34161:20)
  at Context.resolveId (/D:/projects/nuxt-app/node_modules/vite/dist/node/chunks/dep-c6273c7a.js:33898:32)
  at Object.resolveId (/D:/projects/nuxt-app/node_modules/vite/dist/node/chunks/dep-c6273c7a.js:35216:55)
  at async Context.resolve (/D:/projects/nuxt-app/node_modules/vite/dist/node/chunks/dep-c6273c7a.js:34981:23)
  at async Object.resolveId (/D:/projects/nuxt-app/node_modules/vite/dist/node/chunks/dep-c6273c7a.js:35216:32)
  at async ModuleGraph.resolveUrl (/D:/projects/nuxt-app/node_modules/vite/dist/node/chunks/dep-c6273c7a.js:57822:26)


 WARN  [SSR] Error transforming D:/projects/nuxt-app/node_modules/nuxt/dist/app/entry: Missing "./dist/app/entry" export in "nuxt3" package                                                                                                                                 20:01:58  

  at bail (/D:/projects/nuxt-app/node_modules/vite/dist/node/chunks/dep-c6273c7a.js:33604:8)
  at resolve (/D:/projects/nuxt-app/node_modules/vite/dist/node/chunks/dep-c6273c7a.js:33681:10)
  at resolveExports (/D:/projects/nuxt-app/node_modules/vite/dist/node/chunks/dep-c6273c7a.js:34422:12)
  at resolveDeepImport (/D:/projects/nuxt-app/node_modules/vite/dist/node/chunks/dep-c6273c7a.js:34440:31)
  at tryNodeResolve (/D:/projects/nuxt-app/node_modules/vite/dist/node/chunks/dep-c6273c7a.js:34161:20)
  at Context.resolveId (/D:/projects/nuxt-app/node_modules/vite/dist/node/chunks/dep-c6273c7a.js:33898:32)
  at Object.resolveId (/D:/projects/nuxt-app/node_modules/vite/dist/node/chunks/dep-c6273c7a.js:35216:55)
  at async ModuleGraph.resolveUrl (/D:/projects/nuxt-app/node_modules/vite/dist/node/chunks/dep-c6273c7a.js:57822:26)
  at async ModuleGraph.getModuleByUrl (/D:/projects/nuxt-app/node_modules/vite/dist/node/chunks/dep-c6273c7a.js:57699:23)
  at async doTransform (/D:/projects/nuxt-app/node_modules/vite/dist/node/chunks/dep-c6273c7a.js:39714:20)

√ Vite server built in 34ms                                                                                                                                                                                                                                                 20:01:58  
√ Nitro built in 510 ms                                                                                                                                                                                                                                               nitro 20:01:58  
[h3] [unhandled] H3Error: _createApp is not a function
    at createError (file:///D:/projects/nuxt-app/node_modules/h3/dist/index.mjs:191:15)
    at Server.nodeHandler (file:///D:/projects/nuxt-app/node_modules/h3/dist/index.mjs:381:21) {
  statusCode: 500,
  fatal: false,
  unhandled: true,
  statusMessage: 'Internal Server Error'
}

**Comment by Luffyyy** [comment]
The issue seems to origin from here: https://github.com/nuxt/framework/pull/5398, going one commit back: https://github.com/nuxt/framework/commit/2e794e7a19e1fa92ad9cde0c6c052b77df308bc1 seems to not have that issue. Either vite 3.0 is causing it or whatever other changes were made in the commit.

**Comment by DamianGlowala** [comment]
Hi @danielroe 👋 How are things in regard to this issue? Have you got any findings?
