### ISSUE TITLE
Nuxt Bridge + vueuse/head - Cannot start nuxt:  Cannot find module 'nuxt'  

### ISSUE THREAD

**Issue by max5432112345** [nuxt/framework#6184]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.16.0`
- Nuxt Version:     `2.16.0-27616340.013f051b`
- Package Manager:  `npm@8.11.0`
- Builder:          `webpack`
- User Config:      `target`, `head`, `css`, `components`, `buildModules`, `build`, `bridge`, `serverHandlers`, `devServerHandlers`
- Runtime Modules:  `-`
- Build Modules:    `()`, `@pinia/nuxt@0.3.1`, `@nuxt/bridge@3.0.0-27639120.e7a7f9b`

### Reproduction

Install https://github.com/piniajs/example-nuxt-bridge
Install npm install --save @vueuse/head
Set   bridge: { meta: true }

### Describe the bug

Cannot start nuxt:  Cannot find module 'nuxt'

**Comment by max5432112345** [comment]
Aha ha ha I install nuxt but nuxt does not exists :) 
It's a shit not a framework
```
 ERROR  Cannot start nuxt:  Cannot find module 'nuxt'                                                                                                                                09:40:07
Require stack:
- /home/michael/Downloads/example-nuxt-bridge-main/index.js

  Require stack:
  - index.js
  at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
  at Function.resolve (node:internal/modules/cjs/helpers:108:19)
  at Function._resolve [as resolve] (node_modules/jiti/dist/jiti.js:1:108226)
  at resolveModule (node_modules/@nuxt/kit/dist/index.mjs:276:29)
  at importModule (node_modules/@nuxt/kit/dist/index.mjs:299:24)
  at loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:690:92)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6746:23)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6795:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:46:20)
```

**Comment by max5432112345** [comment]
npx nuxt dev

```
✖ Nuxt Fatal Error                                                                       │
   │                                                                                            │
   │   Error:                                                                                   │
   │                                                                                            │
   │   Vue packages version mismatch:                                                           │
   │                                                                                            │
   │   - vue@3.2.37                                                                             │
   │   - vue-server-renderer@2.7.8                                                              │
   │                                                                                            │
   │   This may cause things to work incorrectly. Make sure to use the same version for both.  
   ```

**Comment by max5432112345** [comment]
why ` WARN  [bridge] Could not find @vueuse/head. You may need to install it.  ` if vueuse/head is for vue 3?
