### ISSUE TITLE
inconsistent behavior of route middlewares 

### ISSUE THREAD

**Issue by mercs600** [nuxt/framework#6292]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `yarn@1.22.10`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/node-89wpqd?file=playground/app.vue

### Describe the bug

✋
I have noticed weird behavior when I work with route middlewares attached by module. 
I reproduced repository when you can check route middleware attached by file in middleware directory and also the same middleware but attached by plugin. 

https://github.com/mercs600/nuxt3-middleware-issue/blob/main/playground/middleware/example.global.ts 

https://github.com/mercs600/nuxt3-middleware-issue/blob/main/src/runtime/plugin.ts 

These middlewares do the same work - resolve async function and set some state. 

When I use middleware from plugin I get `500 error: nuxt instance unavailable`
When I use middleware from `playground/middleware` directory it works. 

In the reproduce app you can enable middleware in plugin by nuxt.config (by default it use middleware from directory)
```js
export default defineNuxtConfig({
  modules: [MyModule],
  myModule: {
    addPlugin: true,
  },
});
```

### Logs

```shell
[h3] [unhandled] H3Error: nuxt instance unavailable
    at createError (file:///Users/merc/Projects/Poligon/nuxt-module-middlwares/modules/mymodule/node_modules/h3/dist/index.mjs:196:15)
    at Server.nodeHandler (file:///Users/merc/Projects/Poligon/nuxt-module-middlwares/modules/mymodule/node_modules/h3/dist/index.mjs:386:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  statusCode: 500,
  fatal: false,
  unhandled: true,
  statusMessage: 'Internal Server Error'
}
[nuxt] [request error] nuxt instance unavailable
  at createError (./node_modules/h3/dist/index.mjs:196:15)
  at Server.nodeHandler (./node_modules/h3/dist/index.mjs:386:21)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
[Vue Router warn]: uncaught error during route navigation:
Error: nuxt instance unavailable
    at Module.useNuxtApp (file:///Users/merc/Projects/Poligon/nuxt-module-middlwares/modules/mymodule/playground/.nuxt/dist/server/server.mjs:411:13)
    at Module.useState (file:///Users/merc/Projects/Poligon/nuxt-module-middlwares/modules/mymodule/playground/.nuxt/dist/server/server.mjs:837:38)
    at Module.useExampleState2 (file:///Users/merc/Projects/Poligon/nuxt-module-middlwares/modules/mymodule/playground/.nuxt/dist/server/server.mjs:2923:46)
    at __vite_ssr_import_0__.addRouteMiddleware.global (file:///Users/merc/Projects/Poligon/nuxt-module-middlwares/modules/mymodule/playground/.nuxt/dist/server/server.mjs:2960:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.callAsync (file:///Users/merc/Projects/Poligon/nuxt-module-middlwares/modules/mymodule/node_modules/unctx/dist/index.mjs:45:16)
    at async file:///Users/merc/Projects/Poligon/nuxt-module-middlwares/modules/mymodule/playground/.nuxt/dist/server/server.mjs:2533:22
```

**Comment by danielroe** [comment]
We do a transform for middleware files to preserve the nuxt state across async operations, but in your case, adding an inline function from a plugin, we can't. So you can try something like this:

```ts
 addRouteMiddleware('global-test', async (to) => {
    await Promise.all([useExampleState(), useExampleState2()])
  }, { global: true })
```

Or otherwise rewrite the code so that you don't chain awaits that rely on the nuxt context.

Another potential solution would be to deliberately provide that state yourself:

```ts
 addRouteMiddleware('global-test', async (to) => {
    await callWithNuxt(nuxtApp, useExampleState)
    await callWithNuxt(nuxtApp, useExampleState2)
  }, { global: true })
```

**Comment by mercs600** [comment]
Thank you @danielroe for your explanation.
It works except last solution when I wrapped with `defineNuxtRouteMiddleware`. 
I have resolved it with `callWithNuxt`. 
I will create PR to update documentation

**Comment by dargmuesli** [comment]
`defineNuxtRouteMiddleware` did not work for me as well.

`callWithNuxt` works for me theoretically, but the typescript linter complains about not knowing it (a missing auto import?). When I import `callWithNuxt` from `#app` it does not give a linter warning, but the build fails ("already imported"). So now I don't know what to do :3
