### ISSUE TITLE
i18n/useRouter/useNuxtApp - Error nuxt instance unavailable

### ISSUE THREAD

**Issue by max5432112345** [nuxt/framework#6300]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `npm@8.11.0`
- Builder:          `vite`
- User Config:      `css`, `head`, `i18n`, `modules`, `target`, `telemetry`, `titleTemplate`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-alpha.0-27654621.987d743`
- Build Modules:    `-`

### Reproduction

https://github.com/max5432112345/nuxt-error-1

### Describe the bug

I18n with strategy: 'prefix' not work, but without that property work

### Logs

```shell
[nitro] [dev] [unhandledRejection] Error: nuxt instance unavailable
  at Module.useNuxtApp (file:///Downloads/nuxt3/nuxt-app/.nuxt/dist/server/server.mjs:415:13)
  at useRouter (file:///Downloads/nuxt3/nuxt-app/.nuxt/dist/server/server.mjs:1168:32)
  at Module.navigateTo (file:///Downloads/nuxt3/nuxt-app/.nuxt/dist/server/server.mjs:1207:18)
  at Module.navigate (file:///Downloads/nuxt3/nuxt-app/.nuxt/dist/server/server.mjs:10818:34)
  at file:///Downloads/nuxt3/nuxt-app/.nuxt/dist/server/server.mjs:3139:27
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async Object.callAsync (file:///Downloads/nuxt3/nuxt-app/node_modules/unctx/dist/index.mjs:45:16)
  at async applyPlugin (file:///Downloads/nuxt3/nuxt-app/.nuxt/dist/server/server.mjs:347:23)
  at async Module.applyPlugins (file:///Downloads/nuxt3/nuxt-app/.nuxt/dist/server/server.mjs:357:5)
  at async createNuxtAppServer (file:///Downloads/nuxt3/nuxt-app/.nuxt/dist/server/server.mjs:46:7)
```

**Comment by melrefaie** [comment]
yes same problem

**Comment by max5432112345** [comment]
> yes same problem

I am not alone :)

**Comment by max5432112345** [comment]
@danielroe  is ready? what to install? 
get error with ` [unhandledRejection] nuxtCtx.tryUse is not a function` with npm i nuxt3@3.0.0-rc.6-27660444.746d553

**Comment by danielroe** [comment]
@max5432112345 You may need to run `yarn upgrade unctx` to ensure you're on the latest version.

**Comment by max5432112345** [comment]
@danielroe `npm upgrade unctx` work but old issue remain
`[nitro] [dev] [unhandledRejection] Error: nuxt instance unavailable`

**Comment by max5432112345** [comment]
will try with yarn

**Comment by max5432112345** [comment]
@danielroe 
Deploy failed for nuxt3-docs
Today at 5:11 PM

PR#[6350](https://github.com/nuxt/framework/pull/6350): fix/unctx-plugins@[64a9656](https://github.com/nuxt/framework/commit/64a965677c9b0a0127bdd3ac91592a3fd0be53de)

**Comment by danielroe** [comment]
@max5432112345 What do you mean?

**Comment by danielroe** [comment]
@max5432112345 What do you mean?

**Comment by max5432112345** [comment]
> @max5432112345 What do you mean?

@danielroe that https://github.com/max5432112345/nuxt-error-1
```
ℹ Vite client warmed up in 1902ms                                                                                                                                                    20:38:28
ℹ Vite server warmed up in 303ms                                                                                                                                                     20:38:28
✔ Vite server built in 3199ms                                                                                                                                                        20:38:31
✔ Nitro built in 1164 ms                                                                                                                                                       nitro 20:38:33
[nitro] [dev] [unhandledRejection] Error: nuxt instance unavailable
    at Module.useNuxtApp (file:///home/test/Downloads/nuxt3/nuxt-app/.nuxt/dist/server/server.mjs:432:13)
    at useRouter (file:///home/test/Downloads/nuxt3/nuxt-app/.nuxt/dist/server/server.mjs:1185:32)
    at Module.navigateTo (file:///home/test/Downloads/nuxt3/nuxt-app/.nuxt/dist/server/server.mjs:1224:18)
    at Module.navigate (file:///home/test/Downloads/nuxt3/nuxt-app/.nuxt/dist/server/server.mjs:12395:34)
    at file:///home/test/Downloads/nuxt3/nuxt-app/.nuxt/dist/server/server.mjs:4313:27
    at async Object.callAsync (file:///home/test/Downloads/nuxt3/nuxt-app/node_modules/unctx/dist/index.mjs:46:16)
    at async applyPlugin (file:///home/test/Downloads/nuxt3/nuxt-app/.nuxt/dist/server/server.mjs:364:23)
    at async Module.applyPlugins (file:///home/test/Downloads/nuxt3/nuxt-app/.nuxt/dist/server/server.mjs:374:5)
    at async createNuxtAppServer (file:///home/test/Downloads/nuxt3/nuxt-app/.nuxt/dist/server/server.mjs:46:7)
    at async Object.renderToString (file:///home/test/Downloads/nuxt3/nuxt-app/node_modules/vue-bundle-renderer/dist/index.mjs:264:19)
```

**Comment by danielroe** [comment]
The fix is not available in RC6. See here for edge channel: https://v3.nuxtjs.org/guide/going-further/edge-channel.
