### ISSUE TITLE
Hyperscript function throws TypeError: Invalid value used as weak map key

### ISSUE THREAD

**Issue by tiborpino** [nuxt/framework#6344]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/nuxt-starter-miqseb?file=app.vue

### Describe the bug

When I want to use hyperscript h() function to dynamically render heading element I always get an error in the console `TypeError: Invalid value used as weak map key`

### Logs

```shell
[nitro] [dev] [unhandledRejection] TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at normalizePropsOptions (/home/projects/nuxt-starter-miqseb/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3966:11)
    at createComponentInstance (/home/projects/nuxt-starter-miqseb/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6957:23)
    at renderComponentVNode (/home/projects/nuxt-starter-miqseb/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:171:22)
    at Module.ssrRenderComponent (/home/projects/nuxt-starter-miqseb/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:608:12)
    at _sfc_ssrRender (file:///home/projects/nuxt-starter-miqseb/.nuxt/dist/server/server.mjs:3481:31)
    at renderComponentSubTree (/home/projects/nuxt-starter-miqseb/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:253:13)
    at renderComponentVNode (/home/projects/nuxt-starter-miqseb/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:188:16)
    at Module.ssrRenderComponent (/home/projects/nuxt-starter-miqseb/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:608:12)
    at _sfc_ssrRender (file:///home/projects/nuxt-starter-miqseb/.nuxt/dist/server/server.mjs:3418:31)
```

**Comment by danielroe** [comment]
This does not seem to work in Vue: https://stackblitz.com/edit/github-qeqtw4.

I believe you should instead do:

```vue
<template>
  <component :is="level">
    <slot />
  </component>
</template>
```

**Comment by tiborpino** [comment]
@danielroe I don't understand why it shouldn't. I figured it out. 

See the working example https://stackblitz.com/edit/nuxt-starter-h4qjca?file=app.vue

**Comment by danielroe** [comment]
Yes, that's another option.
