### ISSUE TITLE
Missing "./preload-helper" export in "vite" package 

### ISSUE THREAD

**Issue by amihhs** [nuxt/framework#6479]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.13.0`
- Nuxt Version:     `^3.0.0-rc.6`
- Package Manager:  `pnpm@7.5.2`
- Builder:          `webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

[https://github.com/amihhs/issue-nuxt3-preload-helper](https://github.com/amihhs/issue-nuxt3-preload-helper)
run `pnpm i` and `pnpm build`

### Describe the bug

![image](https://user-images.githubusercontent.com/59364234/183872220-7e35f893-bb19-46b7-9ca5-617d655d9962.png)

The cause may be `\node_modules\.pnpm\vite@2.9.14_sass@1.54.4\node_modules\vite\dist\node\chunks\dep-c9998dc6.js:38274`
```js
const preloadHelperId = 'vite/preload-helper';

....
// 38344
 name: 'vite:build-import-analysis',
      resolveId(id) {
          if (id === preloadHelperId) {
              return id;
          }
      },
```
But I don't know why it's here.

### Additional context

I'm not sure if this is `nuxt` problem, maybe he's `vite` problem.

### Logs

```shell
ERROR  [vite:resolve] Missing "./preload-helper" export in "vite" package     17:40:56  


 ERROR  Missing "./preload-helper" export in "vite" package                                                                         17:40:56

  at bail (node_modules\.pnpm\vite@2.9.14_sass@1.54.4\node_modules\vite\dist\node\chunks\dep-c9998dc6.js:38597:8)
  at resolve (node_modules\.pnpm\vite@2.9.14_sass@1.54.4\node_modules\vite\dist\node\chunks\dep-c9998dc6.js:38674:10)
  at resolveExports (node_modules\.pnpm\vite@2.9.14_sass@1.54.4\node_modules\vite\dist\node\chunks\dep-c9998dc6.js:40982:12)   
  at resolveDeepImport (node_modules\.pnpm\vite@2.9.14_sass@1.54.4\node_modules\vite\dist\node\chunks\dep-c9998dc6.js:41000:31)

  at tryNodeResolve (node_modules\.pnpm\vite@2.9.14_sass@1.54.4\node_modules\vite\dist\node\chunks\dep-c9998dc6.js:40773:20)   
  at Object.resolveId (node_modules\.pnpm\vite@2.9.14_sass@1.54.4\node_modules\vite\dist\node\chunks\dep-c9998dc6.js:40581:28) 
  at node_modules\.pnpm\rollup@2.77.2\node_modules\rollup\dist\shared\rollup.js:22826:37

 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by amihhs** [comment]
@danielroe I'm sorry. I've changed the permissions.

**Comment by danielroe** [comment]
Thanks - would you check edge channel? I believe we have fixed this issue since last release.

**Comment by amihhs** [comment]
Yeah, I tried. It seems to be working properly.thanks!
