### ISSUE TITLE
Missing components after rc6 -> rc8 upgrade

### ISSUE THREAD

**Issue by fabis94** [nuxt/framework#6569]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `yarn@3.2.2`
- Builder:          `vite`
- User Config:      `head`, `typescript`, `modules`, `runtimeConfig`, `hooks`, `build`, `alias`, `vite`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.3.1`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/fabis94/djw3c-frontend-nuxt/pull/1

### Describe the bug

These weird errors started showing up after upgrading from rc6 to rc8 as described in the changelog

1. yarn dev
2. try to open localhost:4000
3. you'll see something like this in the console:

```
[Vue warn]: Failed to resolve component: GlobalLogo
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[Vue warn]: Failed to resolve component: GlobalHeader
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[nuxt] [request error] [unhandled] [500] Invalid value used as weak map key
  at WeakMap.set (<anonymous>)  
  at normalizePropsOptions (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3966:11)  
  at createComponentInstance (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6957:23)  
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:171:22)  
  at Module.ssrRenderComponent (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:608:12)  
  at _sfc_ssrRender (./.nuxt/dist/server/server.mjs:27712:31)  
  at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:253:13)  
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:188:16)  
  at renderVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:295:22)  
  at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:259:13)
[Vue warn]: Failed to resolve component: GlobalLogo
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[Vue warn]: Failed to resolve component: GlobalHeader
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[nitro] [dev] [unhandledRejection] TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at normalizePropsOptions (/home/fabis/Code/other-of-mine/djw3c-frontend-nuxt/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3966:11)
    at createComponentInstance (/home/fabis/Code/other-of-mine/djw3c-frontend-nuxt/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6957:23)
    at renderComponentVNode (/home/fabis/Code/other-of-mine/djw3c-frontend-nuxt/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:171:22)
    at Module.ssrRenderComponent (/home/fabis/Code/other-of-mine/djw3c-frontend-nuxt/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:608:12)
    at _sfc_ssrRender (file:///home/fabis/Code/other-of-mine/djw3c-frontend-nuxt/.nuxt/dist/server/server.mjs:27712:31)
    at renderComponentSubTree (/home/fabis/Code/other-of-mine/djw3c-frontend-nuxt/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:253:13)
    at renderComponentVNode (/home/fabis/Code/other-of-mine/djw3c-frontend-nuxt/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:188:16)
    at renderVNode (/home/fabis/Code/other-of-mine/djw3c-frontend-nuxt/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:295:22)
    at renderComponentSubTree (/home/fabis/Code/other-of-mine/djw3c-frontend-nuxt/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:259:13)
```

**Comment by danielroe** [comment]
The global folder has a special meaning more. Components within it will not have a prefix but will be globally available.

**Comment by fabis94** [comment]
@danielroe Ah, I see, thanks I'll try removing the prefix. It would be nice if this detail would be added to the changelog, btw.

**Comment by pi0** [comment]
Thanks for the notice! I've updated rc.7 changelog with indicator and also related PR for breaking change note: https://github.com/nuxt/framework/pull/6070
