### ISSUE TITLE
Error:  [nuxt] [request error] Context is not available

### ISSUE THREAD

**Issue by Haythamasalama** [nuxt/framework#6583]
### Environment

node: 16.6
nuxtJs : v3.0.0-rc.8
https://github.com/Haythamasalama/haythamasalama.me/runs/7814172650?check_suite_focus=true

### Reproduction

https://github.com/Haythamasalama/haythamasalama.me/runs/7814172650?check_suite_focus=true

### Describe the bug

After I deploy my project on GitHub, I got this error. However, locally it works fine. 
```
[warn] [Vue warn]: Unhandled error during execution of setup function 
  at <NuxtRoot>
Error:  [nuxt] [request error] Context is not available
  at Object.use (./node_modules/unctx/dist/index.mjs:12:15)  
  at useNuxtApp (./.nuxt/prerender/chunks/app/server.mjs:605:38)  
  at setup (./.nuxt/prerender/chunks/app/server.mjs:3554:21)  
  at _sfc_main$1.setup (./.nuxt/prerender/chunks/app/server.mjs:3582:25)  
  at callWithErrorHandling (./.nuxt/prerender/chunks/renderer.mjs:2654:23)  
  at setupStatefulComponent (./.nuxt/prerender/chunks/renderer.mjs:9548:30)  
  at setupComponent (./.nuxt/prerender/chunks/renderer.mjs:9503:12)  
  at renderComponentVNode (./.nuxt/prerender/chunks/renderer.mjs:12068:[17](https://github.com/Haythamasalama/haythamasalama.me/runs/7814172650?check_suite_focus=true#step:8:18))  
  at Object.renderToString (./.nuxt/prerender/chunks/renderer.mjs:1[23](https://github.com/Haythamasalama/haythamasalama.me/runs/7814172650?check_suite_focus=true#step:8:24)42:[26](https://github.com/Haythamasalama/haythamasalama.me/runs/7814172650?check_suite_focus=true#step:8:27))  
  at Object.renderToString (./.nuxt/prerender/chunks/renderer.mjs:1[29](https://github.com/Haythamasalama/haythamasalama.me/runs/7814172650?check_suite_focus=true#step:8:30)71:47)
[warn] [Vue warn]: Unhandled error during execution of setup function 
  at <NuxtRoot>
[warn] [Vue warn]: Unhandled error during execution of setup function 
  at <NuxtRoot>
[warn] [Vue warn]: Unhandled error during execution of setup function 
  at <NuxtRoot>
[warn] [Vue warn]: Unhandled error during execution of setup function 
  at <NuxtRoot>
[warn] [Vue warn]: Unhandled error during execution of setup function 
  at <NuxtRoot>
[warn] [Vue warn]: Unhandled error during execution of setup function 
  at <NuxtRoot>
```

### Logs

```shell
generate
> nuxt generate

[log] Nuxt CLI v3.0.0-rc.8
[info] Client built in 2027ms
[info] Building server...
[success] Server built in 917ms
[success] [nitro] Generated public .output/public
[info] [nitro] Initializing prerenderer
[info] [nitro] Prerendering 9 initial routes with crawler
[warn] [Vue warn]: Unhandled error during execution of setup function 
  at <NuxtRoot>
Error:  [nuxt] [request error] Context is not available
  at Object.use (./node_modules/unctx/dist/index.mjs:12:15)  
  at useNuxtApp (./.nuxt/prerender/chunks/app/server.mjs:605:38)  
  at setup (./.nuxt/prerender/chunks/app/server.mjs:3554:21)  
  at _sfc_main$1.setup (./.nuxt/prerender/chunks/app/server.mjs:3582:25)  
  at callWithErrorHandling (./.nuxt/prerender/chunks/renderer.mjs:2654:23)  
  at setupStatefulComponent (./.nuxt/prerender/chunks/renderer.mjs:9548:30)  
  at setupComponent (./.nuxt/prerender/chunks/renderer.mjs:9503:12)  
  at renderComponentVNode (./.nuxt/prerender/chunks/renderer.mjs:12068:17)  
  at Object.renderToString (./.nuxt/prerender/chunks/renderer.mjs:12342:26)  
  at Object.renderToString (./.nuxt/prerender/chunks/renderer.mjs:12971:47)
[warn] [Vue warn]: Unhandled error during execution of setup function 
  at <NuxtRoot>
[warn] [Vue warn]: Unhandled error during execution of setup function 
  at <NuxtRoot>
[warn] [Vue warn]: Unhandled error during execution of setup function 
  at <NuxtRoot>
[warn] [Vue warn]: Unhandled error during execution of setup function 
  at <NuxtRoot>
[warn] [Vue warn]: Unhandled error during execution of setup function 
  at <NuxtRoot>
[warn] [Vue warn]: Unhandled error during execution of setup function 
  at <NuxtRoot>

<--- Last few GCs --->

[1893:0x4e186d0]    87852 ms: Scavenge (reduce) 2035.0 (2049.8) -> 2035.0 (2050.1) MB, 1.0 / 0.0 ms  (average mu = 0.378, current mu = 0.471) allocation failure 


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb0a860 node::Abort() [node]
 2: 0xa1c193 node::FatalError(char const*, char const*) [node]
 3: 0xcf9a6e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xcf9de7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xeb1685  [node]
 6: 0xeb2166  [node]
 7: 0xec068e  [node]
 8: 0xec10d0 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xec404e v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
10: 0xe852c2 v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [node]
11: 0xe7d8d4 v8::internal::FactoryBase<v8::internal::Factory>::AllocateRawWithImmortalMap(int, v8::internal::AllocationType, v8::internal::Map, v8::internal::AllocationAlignment) [node]
12: 0xe7f5e0 v8::internal::FactoryBase<v8::internal::Factory>::NewRawOneByteString(int, v8::internal::AllocationType) [node]
13: 0xe9239e v8::internal::Factory::NewStringFromOneByte(v8::base::Vector<unsigned char const> const&, v8::internal::AllocationType) [node]
14: 0x12609e9 v8::internal::Uri::Decode(v8::internal::Isolate*, v8::internal::Handle<v8::internal::String>, bool) [node]
15: 0xd73cfd v8::internal::Builtin_GlobalDecodeURIComponent(int, unsigned long*, v8::internal::Isolate*) [node]
16: 0x15f2e19  [node]
Aborted (core dumped)
Error: Process completed with exit code 134.

```
```

**Comment by fabiwlf** [comment]
Same here when using 3.0.0-rc.7, 3.0.0-rc.6 works fine.

**Comment by danielroe** [comment]
Seems to be working fine in rc8 when generating: https://stackblitz.com/edit/github-wfxcgn.

**Comment by Haythamasalama** [comment]
> Seems to be working fine in rc8 when generating: https://stackblitz.com/edit/github-wfxcgn. Would you ensure you've updated your lockfile/node_modules as appropriate?

I deleted the file package-lock.json and installed packages again and I deployed it again but the same error again.

https://github.com/Haythamasalama/haythamasalama.me/actions/runs/2849816945

**Comment by Haythamasalama** [comment]
I'm getting the same error locally now, and this is my environment.

- Operating System: `Windows_NT`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `npm@8.13.2`
- Builder:          `vite`
- User Config:      `app`, `modules`, `tailwindcss`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.3.2`
- Build Modules:    `-`

**Comment by Haythamasalama** [comment]
After updated next to ``3.0.0-rc.8``it works fine
