### ISSUE TITLE
RC8 ServerRequest carsh OOM

### ISSUE THREAD

**Issue by CV-souryu** [nuxt/framework#6620]
### Environment

Nuxt project info:                                                                                         
------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `app`, `alias`, `build`, `css`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/Genshin-Impact-Cult-of-Noelle/Noelle-Nuxt3-SLS/tree/NUXT3ERR

npm i
npm run dev    (is fine)
npm run build
npm run start
request it (ERR&OOM)

### Describe the bug

request it
loop console log "[nuxt] [request error] [unhandled] [500] CSSRender is not a function"
JavaScript heap out of memory

### Logs

```shell
[nuxt] [request error] [unhandled] [500] CSSRender is not a function
  at /C:/Users/EDZ/Desktop/work/Noelle-Nuxt3-SLS/Noelle-Nuxt3-SLS/.output/server/chunks/server.mjs:3457:14
  at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
  at async /C:/Users/EDZ/Desktop/work/Noelle-Nuxt3-SLS/Noelle-Nuxt3-SLS/.output/server/chunks/renderer.mjs:11096:24
  at async /C:/Users/EDZ/Desktop/work/Noelle-Nuxt3-SLS/Noelle-Nuxt3-SLS/.output/server/chunks/renderer.mjs:11150:64
  at async /C:/Users/EDZ/Desktop/work/Noelle-Nuxt3-SLS/Noelle-Nuxt3-SLS/.output/server/chunks/renderer.mjs:14:22
  at async /C:/Users/EDZ/Desktop/work/Noelle-Nuxt3-SLS/Noelle-Nuxt3-SLS/.output/server/node_modules/h3/dist/index.mjs:492:19
  at async Server.nodeHandler (/C:/Users/EDZ/Desktop/work/Noelle-Nuxt3-SLS/Noelle-Nuxt3-SLS/.output/server/node_modules/h3/dist/index.mjs:438:7)

<--- Last few GCs --->

[14328:00000240418DD970]    79248 ms: Mark-sweep (reduce) 4095.2 (4104.6) -> 4083.6 (4093.3) MB, 18.5 / 0.1 ms  (average mu = 0.720, current mu = 0.743) allocation failure scavenge might not succeed 
[14328:00000240418DD970]    79303 ms: Mark-sweep (reduce) 4095.1 (4104.9) -> 4095.1 (4104.7) MB, 28.9 / 0.0 ms  (average mu = 0.611, current mu = 0.470) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF79C047B7F v8::internal::CodeObjectRegistry::~CodeObjectRegistry+114079
 2: 00007FF79BFD4546 DSA_meth_get_flags+65542
 3: 00007FF79BFD53FD node::OnFatalError+301
 4: 00007FF79C90B29E v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF79C8F587D v8::SharedArrayBuffer::Externalize+781
 6: 00007FF79C798C4C v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1468
 7: 00007FF79C795D64 v8::internal::Heap::CollectGarbage+4244
 8: 00007FF79C7936E0 v8::internal::Heap::AllocateExternalBackingStore+2000
 9: 00007FF79C7B13F0 v8::internal::FreeListManyCached::Reset+1408
10: 00007FF79C7B1AA5 v8::internal::Factory::AllocateRaw+37
11: 00007FF79C7C717B v8::internal::FactoryBase<v8::internal::Factory>::NewRawOneByteString+75
12: 00007FF79C5AA9FB v8::internal::String::SlowFlatten+395
13: 00007FF79C314C5B v8::internal::WasmTableObject::Fill+603
14: 00007FF79C4FCB99 v8::internal::RegExp::ExperimentalOneshotExec+1161
15: 00007FF79C4FC657 v8::internal::RegExp::Exec+199
16: 00007FF79C4D850C v8::internal::DeclarationScope::was_lazily_parsed+21452
17: 00007FF79C998F91 v8::internal::SetupIsolateDelegate::SetupHeap+494417
18: 00007FF79C9F0383 v8::internal::SetupIsolateDelegate::SetupHeap+851779
19: 00007FF79C98CB14 v8::internal::SetupIsolateDelegate::SetupHeap+444116
20: 000002404353C00A

 ERROR  Command failed with exit code 134: node ./server/index.mjs                                                                                                                           15:40:17  

  at makeError (/C:/Users/EDZ/Desktop/work/Noelle-Nuxt3-SLS/Noelle-Nuxt3-SLS/node_modules/nuxi/dist/shared/nuxi.759d9bcf.mjs:1256:11)
  at handlePromise (/C:/Users/EDZ/Desktop/work/Noelle-Nuxt3-SLS/Noelle-Nuxt3-SLS/node_modules/nuxi/dist/shared/nuxi.759d9bcf.mjs:2088:26)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async Object.invoke (/C:/Users/EDZ/Desktop/work/Noelle-Nuxt3-SLS/Noelle-Nuxt3-SLS/node_modules/nuxi/dist/chunks/preview.mjs:62:5)
  at async _main (/C:/Users/EDZ/Desktop/work/Noelle-Nuxt3-SLS/Noelle-Nuxt3-SLS/node_modules/nuxi/dist/cli.mjs:46:20)
```

**Comment by CV-souryu** [comment]
because  package: @css-render/vue3-ssr?

**Comment by CV-souryu** [comment]
```JS
.output/server/chunks/server.mjs
//... like line 15
import { hash,CssRender as CSSRender } from 'css-render';
import { plugin as BEMPlugin} from '@css-render/plugin-bem';
```
its work!

**Comment by danielroe** [comment]
This is a bug in the CJS build of css-render itself: https://unpkg.com/browse/css-render@0.15.10/lib/index.js. You can see the default export is set to `void 0`.

**Comment by 07akioni** [comment]
> edit output file
> 
> ```js
> .output/server/chunks/server.mjs
> //... like line 15
> //import CSSRender, { hash } from 'css-render';
> //import BEMPlugin from '@css-render/plugin-bem';
> import { hash,CssRender as CSSRender } from 'css-render';
> import { plugin as BEMPlugin} from '@css-render/plugin-bem';
> ```
> 
> it's running!

This would be fixed in next version of naive ui.
