### ISSUE TITLE
[rc8] nuxt generate error

### ISSUE THREAD

**Issue by yunyuyuan** [nuxt/framework#6645]
### Environment

```
Nuxt CLI v3.0.0-rc.8                                                                                                       22:39:15
RootDir: C:/Users/yunyuyuan/Desktop/nuxt-app                                                                               22:39:19
Nuxt project info:                                                                                                         22:39:19

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

👉 Report an issue: https://github.com/nuxt/framework/issues/new                                                           22:39:19  

👉 Suggest an improvement: https://github.com/nuxt/framework/discussions/new

👉 Read documentation: https://v3.nuxtjs.org
```

### Reproduction

1. `npx nuxi init nuxt-app`
2. remove `app.vue`
3. add folder `/pages/` , add a vue file `/pages/index.vue` with below:
```
<script lang="ts">
definePageMeta({
  title: 'test'
});
</script>
```
4. `yarn install && npm run generate`

### Describe the bug

```
> nuxt generate

Nuxt CLI v3.0.0-rc.8                                                                                                       22:37:36  

 WARN  Error when using sourcemap for reporting an error: Can't resolve original location of error.                        22:37:48


 ERROR  'default' is not exported by pages/index.vue?vue&type=script&lang.ts, imported by pages/index.vue                  22:37:48
file: C:/Users/yunyuyuan/Desktop/nuxt-app/pages/index.vue:1:7
1: import _sfc_main from "C:/Users/yunyuyuan/Desktop/nuxt-app/pages/index.vue?vue&type=script&lang.ts";
          ^
2: export * from "C:/Users/yunyuyuan/Desktop/nuxt-app/pages/index.vue?vue&type=script&lang.ts";
3: export default _sfc_main;


 ERROR  'default' is not exported by pages/index.vue?vue&type=script&lang.ts, imported by pages/index.vue                  22:37:48

  at error (/C:/Users/yunyuyuan/Desktop/nuxt-app/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
  at Module.error (/C:/Users/yunyuyuan/Desktop/nuxt-app/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:12412:16)
  at Module.traceVariable (/C:/Users/yunyuyuan/Desktop/nuxt-app/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:12771:29)
  at ModuleScope.findVariable (/C:/Users/yunyuyuan/Desktop/nuxt-app/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:11423:39)
  at Identifier.bind (/C:/Users/yunyuyuan/Desktop/nuxt-app/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:7422:40)   
  at ExportDefaultDeclaration.bind (/C:/Users/yunyuyuan/Desktop/nuxt-app/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:5252:23)
  at Program.bind (/C:/Users/yunyuyuan/Desktop/nuxt-app/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:5248:73)      
  at Module.bindReferences (/C:/Users/yunyuyuan/Desktop/nuxt-app/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:12408:18)
  at Graph.sortModules (/C:/Users/yunyuyuan/Desktop/nuxt-app/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:22977:20)
  at Graph.build (/C:/Users/yunyuyuan/Desktop/nuxt-app/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:22855:14)  
```

**Comment by 516310460** [comment]
would you please provide a reproduction?

**Comment by yunyuyuan** [comment]
> would you please provide a reproduction?

Sorry,I have forgot `setup` inside `<script lang="ts">`🤣
