### ISSUE TITLE
@vitejs/plugin-legacy does not build

### ISSUE THREAD

**Issue by andresespinosapc** [nuxt/framework#6716]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-qzrpnn?file=nuxt.config.ts

### Describe the bug

When adding the Vite plugin `@vitejs/plugin-legacy` and trying to build using `nuxt build` I get this error:

```
ERROR  [vite:terser] _require2 is not defined                                                            11:12:21


 ERROR  [vite:legacy-generate-polyfill-chunk] _require2 is not defined                                    11:12:21


 ERROR  _require2 is not defined                                                                          11:12:21

  at doWork (eval at __global_eval__ (https://github-qzrpnn.w.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:8:32190), <anonymous>:5:20)
  at _0x51acfb.eval (eval at __global_eval__ (https://github-qzrpnn.w.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:8:32190), <anonymous>:12:21)
  at [nodejs.internal.kHybridDispatch] (https://github-qzrpnn.w.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:353083)
  at t.emitMessage (https://github-qzrpnn.w.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:1031392)
  at _started.<computed>._source.<computed> (https://github-qzrpnn.w.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:15:103757)
```

This error does not happen when using a clean Vite project, so I guess it is related to Nuxt.

**Comment by DrJume** [comment]
https://github.com/vitejs/vite/tree/main/packages/plugin-legacy#:~:text=Terser%20must%20be,add%20%2DD%20terser

**Comment by danielroe** [comment]
This is caused by the following code, inlined in `@vite/legacy-vue`:

```js
    const makeWorker = () => new Worker_1(async (terserPath, code, options) => {
        // test fails when using `import`. maybe related: https://github.com/nodejs/node/issues/43205
        // eslint-disable-next-line no-restricted-globals -- this function runs inside cjs
        const terser = require(terserPath);
        return terser.minify(code, options);
    });
```

The problem is that `jiti`, which transpiles `nuxt.config` and anything used within it, is mangling `require(terserPath)` => `require2(terserPath)` because this is an ES module and Babel doesn't understand that this is meant to run within a CJS context.

**Comment by together-mcar** [comment]
How to solve it?

**Comment by mmis1000** [comment]
> How to solve it?

A temporary hack

```diff
-         const terser = require(terserPath);
+         const terser = eval('require')(terserPath);
```

By make the require not a Identifier, so the babel won't touch it.

**Comment by Binaryify** [comment]
any update?

**Comment by xtoolkit** [comment]
any update?

**Comment by DrJume** [comment]
Installing `terser` fixed the issue for me.

**Comment by xtoolkit** [comment]
hi

i install with `yarn add --dev terser`. seen this errors:

```
Nuxt 3.0.0-rc.13 with Nitro 0.6.1                                                                                                                                                             19:36:50

 ERROR  [vite:terser] _require2 is not defined                                                                                                                                                19:37:18


 ERROR  [vite:legacy-generate-polyfill-chunk] _require2 is not defined                                                                                                                        19:37:18


 ERROR  _require2 is not defined
```

next remove node_module dir and lock file, but again error!

**Comment by zhancheng** [comment]
Please take this issue seriously

**Comment by JiatLn** [comment]
I have same problem, need to help :'(
