### ISSUE TITLE
nuxt dev with serverMiddleware occurs the error `File URL host must be "localhost" or empty on linux`

### ISSUE THREAD

**Issue by knokmki612** [nuxt/framework#6733]
### Environment

Nuxt CLI v3.0.0-rc.8
RootDir: /home/projects/nuxt-starter-qlsvtz
Nuxt project info:

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `serverMiddleware`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

1. access to https://stackblitz.com/edit/nuxt-starter-qlsvtz?file=express%2Findex.js
2. it automatically run `npm run dev` so wait until startup dev server
3. see the error

<details>
<summary>log</summary>

```
~/projects/nuxt-starter-qlsvtz
Nuxt CLI v3.0.0-rc.8                                                                                                                                          16:01:23
                                                                                                                                                              16:01:40
  > Local:    http://localhost:3000/ 
  > Network:  http://192.168.1.104:3000/

ℹ Vite server warmed up in 1007ms                                                                                                                             16:01:47
✔ Vite server built in 2097ms                                                                                                                                 16:01:49
ℹ Vite client warmed up in 4780ms                                                                                                                             16:01:49
✔ Nitro built in 1192 ms                                                                                                                                nitro 16:01:50

 ERROR  [worker reload] [worker init] File URL host must be "localhost" or empty on linux                                                                     16:01:51

  at get (https://nuxt-starter-qlsvtz-m3kj2t2l.w-corp.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:292488)
  at TryGetAllProperties/< (https://nuxt-starter-qlsvtz-m3kj2t2l.w-corp.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:974447)
  at TryGetAllProperties (https://nuxt-starter-qlsvtz-m3kj2t2l.w-corp.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:974356)
  at serializeError (https://nuxt-starter-qlsvtz-m3kj2t2l.w-corp.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:975032)
  at workerOnGlobalUncaughtException (https://nuxt-starter-qlsvtz-m3kj2t2l.w-corp.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:1605177)
  at triggerUncaughtException (https://nuxt-starter-qlsvtz-m3kj2t2l.w-corp.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:15:355344)
  at i.loadESM (https://nuxt-starter-qlsvtz-m3kj2t2l.w-corp.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:246694)
  at <anonymous> (<anonymous>)
```

</details>

### Describe the bug

- occur the error `File URL host must be "localhost" or empty on linux` when run `nuxt dev`
- remove serverMiddleware makes no longer reproduce
- case of run `npm run build && nuxt start` instead of `nuxt dev` doesn't reproduce and middleware fully works

**Comment by danielroe** [comment]
This should be resolved in nitropack v0.5.0+. which you can get with `yarn upgrade nuxt` or `npm upgrade nuxt`.

Let me know if not and I'll reopen.
