### ISSUE TITLE
Cannot start nuxt:  Cannot find module 'vue-tsc/out/proxy'   

### ISSUE THREAD

**Issue by shiftlabs1** [nuxt/framework#6797]
### Environment

Nuxt CLI v3.0.0-rc.8                                                                                                                                                     13:19:30

Nuxt project info:                                                                                                                                                       13:19:33

------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.4.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `npm@8.12.1`
- Builder:          `vite`
- User Config:      `AutoImports`, `vite`, `alias`, `modules`, `nitro`, `experimental`, `unocss`, `components`, `css`, `colorMode`, `typescript`, `runtimeConfig`, `hooks`
- Runtime Modules:  `@vueuse/nuxt@9.1.0`, `@unocss/nuxt@0.45.8`, `@pinia/nuxt@0.3.1`, `@nuxtjs/color-mode@3.1.4`, `@nuxt/image-edge@1.0.0-27657146.da85542`, `nuxt-lodash@2.2.0`, `@nuxtjs/supabase@0.1.23`
- Build Modules:    `-`
------------------------------

### Reproduction

I have created new projects without this issue. I have also deleted node_modules, .nuxt, lock files and installed again using yarn (v1) and npm , but still experiencing the exact same error. 

### Describe the bug

each time i run ```npm run dev```
I get the error below 

``` 
ERROR  Cannot start nuxt:  Cannot find module 'vue-tsc/out/proxy'                                                                                                       13:18:21
Require stack:
- /Users/abjo311/Documents/ShiftLabs/Projects/Vest/stokvest-web/node_modules/@nuxt/vite-builder/node_modules/vite-plugin-checker/lib/checkers/vueTsc/prepareVueTsc.js
- /Users/abjo311/Documents/ShiftLabs/Projects/Vest/stokvest-web/node_modules/@nuxt/vite-builder/node_modules/vite-plugin-checker/lib/checkers/vueTsc/main.js
- /Users/abjo311/Documents/ShiftLabs/Projects/Vest/stokvest-web/node_modules/@nuxt/vite-builder/node_modules/vite-plugin-checker/lib/main.js

  Require stack:
  - node_modules/@nuxt/vite-builder/node_modules/vite-plugin-checker/lib/checkers/vueTsc/prepareVueTsc.js
  - node_modules/@nuxt/vite-builder/node_modules/vite-plugin-checker/lib/checkers/vueTsc/main.js
  - node_modules/@nuxt/vite-builder/node_modules/vite-plugin-checker/lib/main.js
  at Module._resolveFilename (node:internal/modules/cjs/loader:946:15)
  at Function.resolve (node:internal/modules/cjs/helpers:108:19)
  at Object.<anonymous> (node_modules/@nuxt/vite-builder/node_modules/vite-plugin-checker/lib/checkers/vueTsc/prepareVueTsc.js:28:27)
  at Module._compile (node:internal/modules/cjs/loader:1112:14)
  at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
  at Module.load (node:internal/modules/cjs/loader:988:32)
  at Module._load (node:internal/modules/cjs/loader:834:12)
  at Module.require (node:internal/modules/cjs/loader:1012:19)
  at require (node:internal/modules/cjs/helpers:102:18)
  at Object.<anonymous> (node_modules/@nuxt/vite-builder/node_modules/vite-plugin-checker/lib/checkers/vueTsc/main.js:33:28)

ℹ Vite client warmed up in 2836ms        
```

### Additional context

I have created a new project and do not get this error. I am not sure which lib or plugin is causing this error as the stack trace on the nuxt project is honestly, not helpful at all

### Logs
```shell
on npm run build
yarn run v1.22.19
$ nuxi build
Nuxt CLI v3.0.0-rc.8                                                                                                                                                     13:24:59

 ERROR  (node:51358) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time                                                13:25:09
(Use `node --trace-warnings ...` to show where the warning was created)


 WARN                                                                                                                                                                    13:25:10
(!) Some chunks are larger than 500 KiB after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/guide/en/#outputmanualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.

ℹ Client built in 5906ms                                                                                                                                                 13:25:10
ℹ Building server...                                                                                                                                                     13:25:10

 ERROR  Cannot find module 'vue-tsc/out/proxy'                                                                                                                           13:25:10
Require stack:
- /Users/abjo311/Documents/ShiftLabs/Projects/Vest/stokvest-web/node_modules/@nuxt/vite-builder/node_modules/vite-plugin-checker/lib/checkers/vueTsc/prepareVueTsc.js
- /Users/abjo311/Documents/ShiftLabs/Projects/Vest/stokvest-web/node_modules/@nuxt/vite-builder/node_modules/vite-plugin-checker/lib/checkers/vueTsc/main.js
- /Users/abjo311/Documents/ShiftLabs/Projects/Vest/stokvest-web/node_modules/@nuxt/vite-builder/node_modules/vite-plugin-checker/lib/main.js

  Require stack:
  - node_modules/@nuxt/vite-builder/node_modules/vite-plugin-checker/lib/checkers/vueTsc/prepareVueTsc.js
  - node_modules/@nuxt/vite-builder/node_modules/vite-plugin-checker/lib/checkers/vueTsc/main.js
  - node_modules/@nuxt/vite-builder/node_modules/vite-plugin-checker/lib/main.js
  at Module._resolveFilename (node:internal/modules/cjs/loader:946:15)
  at Function.resolve (node:internal/modules/cjs/helpers:108:19)
  at Object.<anonymous> (node_modules/@nuxt/vite-builder/node_modules/vite-plugin-checker/lib/checkers/vueTsc/prepareVueTsc.js:28:27)
  at Module._compile (node:internal/modules/cjs/loader:1112:14)
  at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
  at Module.load (node:internal/modules/cjs/loader:988:32)
  at Module._load (node:internal/modules/cjs/loader:834:12)
  at Module.require (node:internal/modules/cjs/loader:1012:19)
  at require (node:internal/modules/cjs/helpers:102:18)
  at Object.<anonymous> (node_modules/@nuxt/vite-builder/node_modules/vite-plugin-checker/lib/checkers/vueTsc/main.js:33:28)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

```shell
on npm run dev
ERROR  Cannot start nuxt:  Cannot find module 'vue-tsc/out/proxy'                                                                                                       13:18:21
Require stack:
- /Users/abjo311/Documents/ShiftLabs/Projects/Vest/stokvest-web/node_modules/@nuxt/vite-builder/node_modules/vite-plugin-checker/lib/checkers/vueTsc/prepareVueTsc.js
- /Users/abjo311/Documents/ShiftLabs/Projects/Vest/stokvest-web/node_modules/@nuxt/vite-builder/node_modules/vite-plugin-checker/lib/checkers/vueTsc/main.js
- /Users/abjo311/Documents/ShiftLabs/Projects/Vest/stokvest-web/node_modules/@nuxt/vite-builder/node_modules/vite-plugin-checker/lib/main.js

  Require stack:
  - node_modules/@nuxt/vite-builder/node_modules/vite-plugin-checker/lib/checkers/vueTsc/prepareVueTsc.js
  - node_modules/@nuxt/vite-builder/node_modules/vite-plugin-checker/lib/checkers/vueTsc/main.js
  - node_modules/@nuxt/vite-builder/node_modules/vite-plugin-checker/lib/main.js
  at Module._resolveFilename (node:internal/modules/cjs/loader:946:15)
  at Function.resolve (node:internal/modules/cjs/helpers:108:19)
  at Object.<anonymous> (node_modules/@nuxt/vite-builder/node_modules/vite-plugin-checker/lib/checkers/vueTsc/prepareVueTsc.js:28:27)
  at Module._compile (node:internal/modules/cjs/loader:1112:14)
  at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
  at Module.load (node:internal/modules/cjs/loader:988:32)
  at Module._load (node:internal/modules/cjs/loader:834:12)
  at Module.require (node:internal/modules/cjs/loader:1012:19)
  at require (node:internal/modules/cjs/helpers:102:18)
  at Object.<anonymous> (node_modules/@nuxt/vite-builder/node_modules/vite-plugin-checker/lib/checkers/vueTsc/main.js:33:28)

ℹ Vite client warmed up in 2836ms        
```
```

**Comment by 516310460** [comment]
would you please pervide a reproduction?

**Comment by PrinceAtVidyaMantra** [comment]
Well, this issue is usually resolved after installing vue-tsc manually

**Comment by shiftlabs1** [comment]
@516310460  please read through the issue again

**Comment by shiftlabs1** [comment]
Thanks @PrinceAtVidyaMantra , strange as that is, it did fix the issue
