### ISSUE TITLE
Setting cookie with useCookie on redirect causes error

### ISSUE THREAD

**Issue by HampusLilja** [nuxt/framework#6926]
### Environment

Nuxt CLI v3.0.0-rc.8

### Reproduction

https://codesandbox.io/s/black-mountain-vft4sw?file=/app.vue

Click on the links to set new cookie value and make a redirect with middleware or script setup which causes an error in the terminal.

### Describe the bug

useCookie() successfully adds the Set-Cookie header to the response. However, it seems like it attempts to add the Set-Cookie header an additional time after the headers are sent which is causing an error.

Redirecting with router middleware and redirecting with a nuxt page is causing the same error.

### Logs

```shell
[nitro] [dev] [uncaughtException] Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at new NodeError (internal/errors.js:322:7)
    at writeAfterEnd (_http_outgoing.js:694:15)
    at ServerResponse.end (_http_outgoing.js:815:7)
    at ServerResponse.res.end (file:///sandbox/.nuxt/dev/index.mjs:75:10)
    at Immediate._onImmediate (file:///sandbox/node_modules/h3/dist/index.mjs:138:17)
    at processImmediate (internal/timers.js:464:21) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
```

**Comment by danielroe** [comment]
This has been resolved in https://github.com/nuxt/framework/pull/7288.
