### ISSUE TITLE
globalThis.__buildAssetsURL is not a function

### ISSUE THREAD

**Issue by typeoneerror** [nuxt/framework#7010]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `yarn@1.22.10`
- Builder:          `vite`
- User Config:      `css`, `modules`, `runtimeConfig`, `typescript`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.3.2`
- Build Modules:    `-`
------------------------------

### Reproduction

Repo: https://github.com/typeoneerror/typeoneerror.com

### Describe the bug

When running `yarn generate` I get the following errors and the build succeeds though the index.html ends up as a white page with a similar error message.

```
[Edea] ~/Dev/typeoneerror/typeoneerror (main) $ yarn generate
yarn run v1.22.10
$ nuxt generate
Nuxt CLI v3.0.0-rc.8                                                                                                 10:15:20
ℹ Using default Tailwind CSS file from runtime/tailwind.css                                         nuxt:tailwindcss 10:15:24
ℹ Client built in 2864ms                                                                                             10:15:28
ℹ Building server...                                                                                                 10:15:28
✔ Server built in 931ms                                                                                              10:15:29
✔ Generated public .output/public                                                                              nitro 10:15:29
ℹ Initializing prerenderer                                                                                     nitro 10:15:29
ℹ Prerendering 1 initial routes with crawler                                                                   nitro 10:15:35

 ERROR  globalThis.__buildAssetsURL is not a function                                                                10:15:35

  at .nuxt/prerender/chunks/app/_nuxt/index.19d031bf.mjs:21:36
  at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
  at async .nuxt/prerender/chunks/app/server.mjs:7150:7
  at async Object.callAsync (node_modules/@nuxt/kit/node_modules/unctx/dist/index.mjs:53:16)
  at async applyPlugin (.nuxt/prerender/chunks/app/server.mjs:3600:23)
  at async applyPlugins (.nuxt/prerender/chunks/app/server.mjs:3609:5)
  at async createNuxtAppServer (.nuxt/prerender/chunks/app/server.mjs:7473:7)
  at async Object.renderToString (.nuxt/prerender/chunks/renderer.mjs:270:19)


 ERROR  globalThis.__buildAssetsURL is not a function                                                                10:15:35

  at .nuxt/prerender/chunks/app/_nuxt/index.19d031bf.mjs:21:36
  at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
  at async .nuxt/prerender/chunks/app/server.mjs:7150:7
  at async Object.callAsync (node_modules/@nuxt/kit/node_modules/unctx/dist/index.mjs:53:16)
  at async applyPlugin (.nuxt/prerender/chunks/app/server.mjs:3600:23)
  at async applyPlugins (.nuxt/prerender/chunks/app/server.mjs:3609:5)
  at async createNuxtAppServer (.nuxt/prerender/chunks/app/server.mjs:7473:7)
  at async Object.renderToString (.nuxt/prerender/chunks/renderer.mjs:270:19)


 ERROR  [nuxt] [request error] globalThis.__buildAssetsURL is not a function                                         10:15:35
  at ./.nuxt/prerender/chunks/app/_nuxt/index.19d031bf.mjs:21:36
  at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
  at async ./.nuxt/prerender/chunks/app/server.mjs:7150:7
  at async Object.callAsync (./node_modules/@nuxt/kit/node_modules/unctx/dist/index.mjs:53:16)
  at async applyPlugin (./.nuxt/prerender/chunks/app/server.mjs:3600:23)
  at async applyPlugins (./.nuxt/prerender/chunks/app/server.mjs:3609:5)
  at async createNuxtAppServer (./.nuxt/prerender/chunks/app/server.mjs:7473:7)
  at async Object.renderToString (./.nuxt/prerender/chunks/renderer.mjs:270:19)


 ERROR  globalThis.__buildAssetsURL is not a function                                                                10:15:35

  at .nuxt/prerender/chunks/app/_nuxt/index.19d031bf.mjs:21:36
  at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
  at async .nuxt/prerender/chunks/app/server.mjs:7150:7
  at async Object.callAsync (node_modules/@nuxt/kit/node_modules/unctx/dist/index.mjs:53:16)
  at async applyPlugin (.nuxt/prerender/chunks/app/server.mjs:3600:23)
  at async applyPlugins (.nuxt/prerender/chunks/app/server.mjs:3609:5)
  at async createNuxtAppServer (.nuxt/prerender/chunks/app/server.mjs:7473:7)
  at async Object.renderToString (.nuxt/prerender/chunks/renderer.mjs:270:19)


 ERROR  globalThis.__buildAssetsURL is not a function                                                                10:15:35

  at .nuxt/prerender/chunks/app/_nuxt/index.19d031bf.mjs:21:36
  at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
  at async .nuxt/prerender/chunks/app/server.mjs:7150:7
  at async Object.callAsync (node_modules/@nuxt/kit/node_modules/unctx/dist/index.mjs:53:16)
  at async applyPlugin (.nuxt/prerender/chunks/app/server.mjs:3600:23)
  at async applyPlugins (.nuxt/prerender/chunks/app/server.mjs:3609:5)
  at async createNuxtAppServer (.nuxt/prerender/chunks/app/server.mjs:7473:7)
  at async Object.renderToString (.nuxt/prerender/chunks/renderer.mjs:270:19)

  ├─ / (69ms) (Error: [500] Internal Server Error)                                                             nitro 10:15:35
✔ You can now deploy .output/public to any static hosting!                                                           10:15:35
✨  Done in 14.73s.
```

**Comment by Axing-nxr** [comment]
how to resolve this problem

**Comment by yeonjulee1005** [comment]
me too..
please reply to your solution~ T.T
i have same issue.
