### ISSUE TITLE
Middleware is executed twice when an error gets thrown

### ISSUE THREAD

**Issue by svengt** [nuxt/framework#7107]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `srcDir`, `components`, `css`, `vite`, `modules`, `runtimeConfig`, `build`
- Runtime Modules:  `@pinia/nuxt@0.4.1`
- Build Modules:    `-`

### Reproduction

https://codesandbox.io/s/wonderful-tree-m15t6x?file=/middleware/test.global.ts

### Describe the bug

A middleware is executed twice on the server side when an error is thrown. The second time the middleware is executed you lose the ability to read cookie information. This is an issue in our case when we want to validate if the current user is allowed to see a certain page.

### Logs

```shell
i am called twice
[Vue Router warn]: uncaught error during route navigation:
i am called twice
H3Error: Forbidden
    at Module.createError (file:///sandbox/node_modules/h3/dist/index.mjs:239:15)
    at Module.createError (file:///sandbox/.nuxt/dist/server/server.mjs:948:38)
    at file:///sandbox/.nuxt/dist/server/server.mjs:2996:31
    at fn (file:///sandbox/.nuxt/dist/server/server.mjs:434:27)
    at Object.callAsync (file:///sandbox/node_modules/unctx/dist/index.mjs:49:19)
    at Module.callWithNuxt (file:///sandbox/.nuxt/dist/server/server.mjs:436:23)
    at file:///sandbox/.nuxt/dist/server/server.mjs:2654:50
    at file:///sandbox/node_modules/vue-router/dist/vue-router.mjs:1990:35
    at new Promise (<anonymous>)
    at file:///sandbox/node_modules/vue-router/dist/vue-router.mjs:1962:18 {
  statusCode: 403,
  fatal: false,
  unhandled: false,
  statusMessage: 'Forbidden',
  __nuxt_error: true
}
[Vue Router warn]: uncaught error during route navigation:
H3Error: Forbidden
    at Module.createError (file:///sandbox/node_modules/h3/dist/index.mjs:239:15)
    at Module.createError (file:///sandbox/.nuxt/dist/server/server.mjs:948:38)
    at file:///sandbox/.nuxt/dist/server/server.mjs:2996:31
    at fn (file:///sandbox/.nuxt/dist/server/server.mjs:434:27)
    at Object.callAsync (file:///sandbox/node_modules/unctx/dist/index.mjs:49:19)
    at Module.callWithNuxt (file:///sandbox/.nuxt/dist/server/server.mjs:436:23)
    at file:///sandbox/.nuxt/dist/server/server.mjs:2654:50
    at file:///sandbox/node_modules/vue-router/dist/vue-router.mjs:1990:35
    at new Promise (<anonymous>)
    at file:///sandbox/node_modules/vue-router/dist/vue-router.mjs:1962:18 {
  statusCode: 403,
  fatal: false,
  unhandled: false,
  statusMessage: 'Forbidden',
  __nuxt_error: true
}
```

**Comment by danielroe** [comment]
The middleware will be called the second time when rendering the error page. The headers, etc., are deliberately not present on this page so it can be cached. If you would like to render something on the error page dependent on user headers, then you should set it on the error object itself which can be passed to your custom `error.vue` file./
