### ISSUE TITLE
Cannot find module '.output/server/node_modules/pinia/dist/pinia.mjs' after RC9

### ISSUE THREAD

**Issue by Lonsho** [nuxt/framework#7223]
### Environment

Operating System: `Darwin`
Node Version: `v14.19.3`
Nuxt Version: 3.0.0-rc.9
Nitro Version: 0.5.0
Package Manager: npm@6.14.17
Builder: vite
User Config: nitro
Runtime Modules: -
Build Modules: -

### Reproduction

Run any nuxt v3 project with the pinia

package.json
```json
 "dependencies": {
    "@pinia/nuxt": "^0.4.1",
    "@types/qs": "^6.9.7",
    "axios": "^0.27.2",
    "pinia": "^2.0.21",
    "qs": "^6.10.3"
  },
  "devDependencies": {
    "@antfu/eslint-config": "0.25.2",
    "@css-render/vue3-ssr": "^0.15.10",
    "@intlify/nuxt3": "^0.2.3",
    "@nuxtjs/color-mode": "3.1.4",
    "@types/mockjs": "^1.0.6",
    "@types/qs": "^6.9.7",
    "@unocss/nuxt": "0.44.2",
    "@vueuse/nuxt": "8.9.2",
    "cross-env": "^7.0.3",
    "eslint": "8.19.0",
    "eslint-config-prettier": "8.5.0",
    "eslint-plugin-prettier": "4.2.1",
    "eslint-plugin-vue": "9.2.0",
    "mockjs": "^1.1.0",
    "naive-ui": "^2.31.0",
    "nuxt": "3.0.0-rc.9",
    "prettier": "2.7.1",
    "sass": "1.53.0",
    "sass-loader": "13.0.2",
    "typescript": "4.7.4",
    "unplugin-vue-components": "^0.21.1",
    "vite-plugin-vue-setup-extend": "^0.4.0"
  }
```

### Describe the bug

after `npx nuxi build` and `npx nuxi start `I get this error:

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Volumes/macDoc/WebstormProjects/chipoda-web/.output/server/node_modules/pinia/dist/pinia.mjs' imported from /Volumes/macDoc/WebstormProjects/chipoda-web/.output/server/index.mjs
    at new NodeError (internal/errors.js:322:7)
    at finalizeResolution (internal/modules/esm/resolve.js:318:11)
    at moduleResolve (internal/modules/esm/resolve.js:776:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:887:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:76:40)
    at link (internal/modules/esm/module_job.js:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @1.0.0 start: `cross-env PORT=13000 node .output/server/index.mjs`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
When I try to manually modify `.output/server/index.mjs` and  `.output/server/chunks/nitro/node-server.mjs` to fix  `pinia/dist/pinia.mjs` I can run it , but there's a new problem, i can't open the page in browser：

```
[nuxt] [request error] [unhandled] [500] Cannot find module '/Volumes/macDoc/WebstormProjects/chipoda-web/.output/server/node_modules/pinia/dist/pinia' imported from /Volumes/macDoc/WebstormProjects/chipoda-web/.output/server/chunks/handlers/renderer.mjs
  at new NodeError (internal/errors.js:322:7)  
  at finalizeResolution (internal/modules/esm/resolve.js:318:11)  
  at moduleResolve (internal/modules/esm/resolve.js:776:10)  
  at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:887:11)  
  at Loader.resolve (internal/modules/esm/loader.js:89:40)  
  at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)  
  at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:76:40)  
  at link (internal/modules/esm/module_job.js:75:36)
```

**Comment by kstraszewski** [comment]
Can you show your nuxt config or give some reproduction? I have working pinia@2.0.21 and @pinia/nuxt@0.4.1 on my Rc9 project.

**Comment by Lonsho** [comment]
> Can you show your nuxt config or give some reproduction? I have working pinia@2.0.21 and @pinia/nuxt@0.4.1 on my Rc9 project.

This is my nuxt config
```javascript
import { defineNuxtConfig } from 'nuxt'
import { presetAttributify, presetIcons, presetUno } from 'unocss'
import VueSetupExtend from 'vite-plugin-vue-setup-extend'

import Components from 'unplugin-vue-components/vite'
import { NaiveUiResolver } from 'unplugin-vue-components/resolvers'

export default defineNuxtConfig({
  srcDir: 'src',
  app: {
    buildAssetsDir: '/static/',
  },
  modules: [
    '@vueuse/nuxt',
    // pinia plugin - https://pinia.esm.dev
    '@pinia/nuxt',
    // unocss plugin - https://github.com/unocss/unocss
    '@unocss/nuxt',
    '@intlify/nuxt3',
    '@nuxtjs/color-mode',
  ],

  build: {
    transpile:
      process.env.NODE_ENV === 'production'
        ? ['naive-ui', 'vueuc', '@css-render/vue3-ssr', '@juggle/resize-observer']
        : ['@juggle/resize-observer'],
  },
  unocss: {
    uno: false,
    preflight: false,
    icons: true,
    presets: [
      presetUno(),
      presetAttributify(),
      presetIcons({
        scale: 1.2,
        extraProperties: {
          display: 'inline-block',
        },
      }),
    ],
  },

  // localization - i18n config
  intlify: {
    localeDir: 'locales',
    vueI18n: {
      locale: 'en',
      fallbackLocale: 'en',
      availableLocales: ['en', 'zh_CN'],
      sync: true,
    },
  },

  typescript: {
    tsConfig: {
      compilerOptions: {
        strict: true,
        skipLibCheck: true,
        types: ['@pinia/nuxt', '@intlify/nuxt3', './type.d.ts'],
      },
    },
  },
  colorMode: {
    classSuffix: '',
    fallback: 'light',
    storageKey: 'color-mode',
  },
  css: ['@/assets/css/style.scss', 'uno.css'],
  vite: {
    css: {
      preprocessorOptions: {
        scss: {
          additionalData: '@use "~/assets/css/theme.scss" as *;',
        },
      },
    },
    server: {
      hmr: {
        overlay: false,
      },
    },
    logLevel: 'info',
    plugins: [
      Components({
        resolvers: [NaiveUiResolver()],
      }),
      VueSetupExtend(),
    ],
    optimizeDeps: {
      include: process.env.NODE_ENV === 'development' ? ['naive-ui', 'vueuc', 'date-fns-tz/esm/formatInTimeZone'] : [],
    },
  },
})

```

**Comment by Lonsho** [comment]
I replace  all `'pinia/dist/pinia'` to `'pinia/dist/pinia.mjs' ` , it will be run.

**Comment by kstraszewski** [comment]
I have `'@pinia/nuxt'` in `buildModules`, and all imports like that `import {defineStore} from 'pinia';`

**Comment by ShaggyTech** [comment]
To the best of knowledge, all packages should be devDependencies and all modules should go in ‘modules’ array option in nuxt config.  ’buildModules’ is deprecated in Nuxt 3.

Also you shouldn’t need to have ‘pinia’ as a dependency at all.

So get rid of ‘pinia’ package, change all packages to devDependencies, move all modules to ‘modules’ array in nuxt config.  That is what works for me in my Nuxt 3 projects.

**Comment by Lonsho** [comment]
> To the best of knowledge, all packages should be devDependencies and all modules should go in ‘modules’ array option in nuxt config. ’buildModules’ is deprecated in Nuxt 3.
> 
> Also you shouldn’t need to have ‘pinia’ as a dependency at all.
> 
> So get rid of ‘pinia’ package, change all packages to devDependencies, move all modules to ‘modules’ array in nuxt config. That is what works for me in my Nuxt 3 projects.

Thanks，I find my problem. Cannot use createPinia again in code
