### ISSUE TITLE
bug(kit): necessary type annotation for the module

### ISSUE THREAD

**Issue by Lexpeartha** [nuxt/framework#7225]
### Environment

Nuxt module using `@nuxt/kit` on rc 9

### Reproduction

Main branch of my repo, stopping me from releasing the module:
https://github.com/Lexpeartha/nuxt-xstate

### Describe the bug

After rc 9, after trying to publish the module my `module.ts` file throws an error as:
```
src/module.ts(11,7): error TS2742: The inferred type of 'module' cannot be named without a reference to 'nuxt/node_modules/@nuxt/schema'. This is likely not portable. A type annotation is necessary.
```

Not sure what is happening, but after doing what is suggested in error
```ts
import type { NuxtModule } from '@nuxt/schema'

const module: NuxtModule<ModuleOptions> = defineNuxtModule<ModuleOptions>(
  // Module options...
)

export default module
```
I get a type error that module is not compatible with the set value (or more exactly `Types of property 'getOptions' are incompatible`). Considering I didn't change anything in `module.ts` file itself, and that this didn't occur before rc 9, I'm wondering what I'm doing wrong

### Logs

```shell
Error: Failed to compile. Check the logs above.
    at error (file:///home/aleksa/Desktop/Projects/nuxt-xstate/node_modules/unbuild/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
    at throwPluginError (file:///home/aleksa/Desktop/Projects/nuxt-xstate/node_modules/unbuild/node_modules/rollup/dist/es/shared/rollup.js:21764:12)
    at Object.error (file:///home/aleksa/Desktop/Projects/nuxt-xstate/node_modules/unbuild/node_modules/rollup/dist/es/shared/rollup.js:22486:20)
    at Object.error (file:///home/aleksa/Desktop/Projects/nuxt-xstate/node_modules/unbuild/node_modules/rollup/dist/es/shared/rollup.js:21941:42)
    at Object.transform (file:///home/aleksa/Desktop/Projects/nuxt-xstate/node_modules/unbuild/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.mjs:1590:26)
    at file:///home/aleksa/Desktop/Projects/nuxt-xstate/node_modules/unbuild/node_modules/rollup/dist/es/shared/rollup.js:22695:37
```
```

**Comment by pi0** [comment]
Can you please try updating lockfile to dedup schema version? 

@danielroe Do you know any better way to avoid issue with multiple versions of schema (if yes, we could probably track it)

**Comment by danielroe** [comment]
Adding it as an explicit dev-dependency is probably the best way: https://github.com/nuxt/starter/pull/99.

**Comment by Lexpeartha** [comment]
Adding it as explicit dependency solved it, thanks 😁
