### ISSUE TITLE
ERROR [unhandledRejection] The "path" argument must be of type string. Received an instance of Array

### ISSUE THREAD

**Issue by amirmms** [nuxt/framework#7229]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.15.0`
- Nuxt Version:     `2.16.0-27705624.7b3bab3`
- Nitro Version:    `0.4.24`
- Package Manager:  `npm@8.5.5`
- Builder:          `webpack`
- User Config:      `ssr`, `target`, `components`, `loading`, `runtimeConfig`, `head`, `css`, `plugins`, `buildModules`, `loadingIndicator`, `modules`, `axios`, `auth`, `pwa`, `build`, `serverHandlers`, `devServerHandlers`, `bridge`
- Runtime Modules:  `bootstrap-vue/nuxt`, `@nuxtjs/axios@5.13.6`, `@nuxtjs/pwa@3.3.5`, `@nuxtjs/auth-next@5.0.0-1648802546.c9880dc`
- Build Modules:    `()`, `@nuxtjs/google-analytics@2.4.0`, `@nuxtjs/fontawesome@1.1.2`, `@nuxt/postcss8@1.1.3`, `@nuxt/bridge@0.10.1`
------------------------------

### Reproduction

ERROR [unhandledRejection] The "path" argument must be of type string. Received an instance of Array

at new NodeError (node:internal/errors:372:5)
at validateString (node:internal/validators:120:11)
at Object.resolve (node:path:1098:7)
at Function.Module._nodeModulePaths (node:internal/modules/cjs/loader:631:17)
at Function.Module._resolveFilename (node:internal/modules/cjs/loader:872:37)
at Function.resolve (node:internal/modules/cjs/helpers:108:19)
at resolveModule (node_modules/nuxi/dist/shared/nuxi.a3ba4610.mjs:15:29)
at importModule (node_modules/nuxi/dist/shared/nuxi.a3ba4610.mjs:35:24)
at loadingHandler (node_modules/nuxi/dist/chunks/dev.mjs:6727:50)
at Server.serverHandler (node_modules/nuxi/dist/chunks/dev.mjs:6733:58)

### Describe the bug

after update from  Nuxi 3.0.0-rc.6  to Nuxi 3.0.0-rc.9  get this error

**Comment by 516310460** [comment]
Would you please prodive a reproduction?
