### ISSUE TITLE
bug(kit): added auto-imports don't work

### ISSUE THREAD

**Issue by Lexpeartha** [nuxt/framework#7253]
### Environment

Nuxt module using `@nuxt/kit` rc 9

### Reproduction

Blank project using my nuxt-xstate module which after updating relies on `imports:sources`

Online module playground: https://stackblitz.com/edit/nuxt-xstate-playground
Source code: https://github.com/Lexpeartha/nuxt-xstate

UPDATE: after bumping nuxt to rc 9 on stackblitz, it seems to work, however fresh project still doesn't work as it's supposed to

### Describe the bug

Types for auto-imports aren't generated, and when starting dev server errors are thrown:
```
ERROR  Failed to resolve import "ufo" from "virtual:nuxt:/home/aleksa/Desktop/Projects/xstate-test/.nuxt/paths.mjs". Does the file exist?

 ERROR  Failed to resolve import "defu" from ".nuxt/app.config.mjs". Does the file exist?                
 ```
 
 One very weird thing is that module works without any issues in my module playground, but behaves like this in any other environment

### Logs

```shell
[nuxt] [request error] [unhandled] [500] [vite-node] Failed to load ufo
  at ViteNodeRunner.directRequest (./node_modules/.pnpm/vite-node@0.22.1/node_modules/vite-node/dist/client.mjs:165:13)  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async ViteNodeRunner.cachedRequest (./node_modules/.pnpm/vite-node@0.22.1/node_modules/vite-node/dist/client.mjs:113:12)  
  at async request (./node_modules/.pnpm/vite-node@0.22.1/node_modules/vite-node/dist/client.mjs:136:16)  
  at async virtual:nuxt:./.nuxt/paths.mjs:1:238  
  at async ViteNodeRunner.directRequest (./node_modules/.pnpm/vite-node@0.22.1/node_modules/vite-node/dist/client.mjs:217:5)  
  at async ViteNodeRunner.cachedRequest (./node_modules/.pnpm/vite-node@0.22.1/node_modules/vite-node/dist/client.mjs:113:12)  
  at async request (./node_modules/.pnpm/vite-node@0.22.1/node_modules/vite-node/dist/client.mjs:136:16)  
  at async ./node_modules/.pnpm/nuxt@3.0.0-rc.9/node_modules/nuxt/dist/app/entry.mjs:5:31  
  at async ViteNodeRunner.directRequest (./node_modules/.pnpm/vite-node@0.22.1/node_modules/vite-node/dist/client.mjs:217:5)
[nuxt] [request error] [unhandled] [500] [vite-node] Failed to load ufo
  at ViteNodeRunner.directRequest (./node_modules/.pnpm/vite-node@0.22.1/node_modules/vite-node/dist/client.mjs:165:13)  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async ViteNodeRunner.cachedRequest (./node_modules/.pnpm/vite-node@0.22.1/node_modules/vite-node/dist/client.mjs:113:12)  
  at async request (./node_modules/.pnpm/vite-node@0.22.1/node_modules/vite-node/dist/client.mjs:136:16)  
  at async virtual:nuxt:./.nuxt/paths.mjs:1:238  
  at async ViteNodeRunner.directRequest (./node_modules/.pnpm/vite-node@0.22.1/node_modules/vite-node/dist/client.mjs:217:5)  
  at async ViteNodeRunner.cachedRequest (./node_modules/.pnpm/vite-node@0.22.1/node_modules/vite-node/dist/client.mjs:113:12)  
  at async request (./node_modules/.pnpm/vite-node@0.22.1/node_modules/vite-node/dist/client.mjs:136:16)  
  at async ./node_modules/.pnpm/nuxt@3.0.0-rc.9/node_modules/nuxt/dist/app/entry.mjs:5:31  
  at async ViteNodeRunner.directRequest (./node_modules/.pnpm/vite-node@0.22.1/node_modules/vite-node/dist/client.mjs:217:5)
```
```

**Comment by danielroe** [comment]
If you use the `addImports` hook from `@nuxt/kit` then it will take care of this. The issue is that using the new `imports.*` hook will not work on earlier versions of Nuxt (pre rc9). See https://github.com/nuxt/framework/pull/7158.
