### ISSUE TITLE
Server crash when redirect after set cookie

### ISSUE THREAD

**Issue by mmis1000** [nuxt/framework#7307]
### Environment

Nuxi 3.0.0-rc.9
RootDir: /home/projects/github-bbq8jh
Nuxt project info: 

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.9`
- Nitro Version:    `0.5.1`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-bbq8jh?file=app.vue

```js
const route = useRoute();
const k = useCookie('k');

if (route.query.k) {
  k.value = route.query.k;
  await navigateTo('/', { rediractCode: 302 });
}
```

Navigate to `/?k=2` in the view panel by change the url manually

### Describe the bug

The server(worker) completely crashed due to 2 Error

```txt
[nuxt] [request error] [unhandled] [500] Cannot set headers after they are sent to the client
[nitro] [dev] [unhandledRejection] Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
```

For detail. See logs below.

### Additional context

1. You should probably check whether header is sent before set cookie or it will blow up the server.
2. The error handling of error page is also faulty. You shouldn't try to send error page if the response is already sent.

### Logs

```shell
[nuxt] [request error] [unhandled] [500] Cannot set headers after they are sent to the client
  at get (https://github-bbq8jh.w-corp.staticblitz.com/blitz.2920c879366045e9300c0e5685ed32a2f19795be.js:6:292488)  
  at get (./node_modules/h3/dist/index.mjs:109:9)  
  at normalizeError (./.nuxt/dev/index.mjs:319:18)  
  at errorhandler (./.nuxt/dev/index.mjs:338:71)  
  at nodeHandler (./node_modules/h3/dist/index.mjs:627:23)  
  at <anonymous> (<anonymous>)
[nitro] [dev] [unhandledRejection] Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at get (https://github-bbq8jh.w-corp.staticblitz.com/blitz.2920c879366045e9300c0e5685ed32a2f19795be.js:6:292488)
    at getStackString (https://github-bbq8jh.w-corp.staticblitz.com/blitz.2920c879366045e9300c0e5685ed32a2f19795be.js:6:103704)
    at formatValue/</f< (https://github-bbq8jh.w-corp.staticblitz.com/blitz.2920c879366045e9300c0e5685ed32a2f19795be.js:6:99381)
    at formatValue/< (https://github-bbq8jh.w-corp.staticblitz.com/blitz.2920c879366045e9300c0e5685ed32a2f19795be.js:6:101164)
    at formatValue (https://github-bbq8jh.w-corp.staticblitz.com/blitz.2920c879366045e9300c0e5685ed32a2f19795be.js:6:103550)
    at inspect (https://github-bbq8jh.w-corp.staticblitz.com/blitz.2920c879366045e9300c0e5685ed32a2f19795be.js:6:92243)
    at formatWithOptionsInternal (https://github-bbq8jh.w-corp.staticblitz.com/blitz.2920c879366045e9300c0e5685ed32a2f19795be.js:6:115079)
    at formatWithOptions (https://github-bbq8jh.w-corp.staticblitz.com/blitz.2920c879366045e9300c0e5685ed32a2f19795be.js:6:116334)
    at value (https://github-bbq8jh.w-corp.staticblitz.com/blitz.2920c879366045e9300c0e5685ed32a2f19795be.js:6:1056320)
    at warn (https://github-bbq8jh.w-corp.staticblitz.com/blitz.2920c879366045e9300c0e5685ed32a2f19795be.js:6:1056414)
    at consoleCall (https://github-bbq8jh.w-corp.staticblitz.com/blitz.2920c879366045e9300c0e5685ed32a2f19795be.js:15:372941)
    at <anonymous> (file:///home/projects/github-bbq8jh/.nuxt/dev/index.mjs:453:53)
    at EventEmitter.prototype.emit (https://github-bbq8jh.w-corp.staticblitz.com/blitz.2920c879366045e9300c0e5685ed32a2f19795be.js:6:155574)
    at emit (https://github-bbq8jh.w-corp.staticblitz.com/blitz.2920c879366045e9300c0e5685ed32a2f19795be.js:6:1072781)
    at processPromiseRejections (https://github-bbq8jh.w-corp.staticblitz.com/blitz.2920c879366045e9300c0e5685ed32a2f19795be.js:6:1075283)
    at processTicksAndRejections (https://github-bbq8jh.w-corp.staticblitz.com/blitz.2920c879366045e9300c0e5685ed32a2f19795be.js:6:797228)
    at _0x258810 (https://github-bbq8jh.w-corp.staticblitz.com/blitz.2920c879366045e9300c0e5685ed32a2f19795be.js:8:256344)
    at <anonymous> (<anonymous>) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
```

**Comment by danielroe** [comment]
This should be resolved in the [edge channel](https://v3.nuxtjs.org/guide/going-further/edge-channel/), or in the next RC, via https://github.com/nuxt/framework/pull/7288.

Let me know if not and I'll reopen.

**Comment by kazupon** [comment]
We’ve met similar issues in nuxtjs/i18n. 
Is that related to this issue?
https://github.com/nuxt-community/i18n-module/issues/1611
