### ISSUE TITLE
request to http://0.0.0.0:3000/__nuxt_vite_node__/manifest failed, reason: socket hang up ()

### ISSUE THREAD

**Issue by OyewoleOyedeji** [nuxt/framework#7341]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.9`
- Nitro Version:    `0.5.1`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `typescript`, `modules`, `app`, `proxy`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.3.2`, `@pinia/nuxt@0.4.2`, `@nuxtjs/proxy@2.1.0`, `nuxt-svgo@1.0.1`
- Build Modules:    `-`
------------------------------

### Reproduction

I ran the following command

`npx nuxt dev --https --ssl-cert ../cert/cert.pem --ssl-key ../cert/key.pem --open`

### Describe the bug

500
request to http://0.0.0.0:3000/__nuxt_vite_node__/manifest failed, reason: socket hang up ()

at async $fetchRaw2 (./node_modules/ohmyfetch/dist/chunks/fetch.mjs:131:20)
at async ./.nuxt/dev/index.mjs:457:20
at async ./.nuxt/dev/index.mjs:520:64
at async ./.nuxt/dev/index.mjs:106:22
at async ./node_modules/h3/dist/index.mjs:592:19
at async Server.nodeHandler (./node_modules/h3/dist/index.mjs:538:7)

### Additional context

When I try running the server without `--https` and it flags, the server loads and serves the page. This only happens for `rc-9` as I upgraded from `rc-8`

### Logs

```shell
Nuxi 3.0.0-rc.9                                                                                               08:42:27
Nuxt 3.0.0-rc.9 with Nitro 0.5.1                                                                              08:42:27
                                                                                                              08:42:29
  > Local:    https://localhost:3000/ 
  > Network:  https://192.168.43.111:3000/

ℹ Using default Tailwind CSS file from runtime/tailwind.css                                  nuxt:tailwindcss 08:42:29
ℹ [HPM] Proxy created: /socket  -> https://localhost:4000/socket                                              08:42:29
ℹ Tailwind Viewer: https://localhost:3000/_tailwind/                                         nuxt:tailwindcss 08:42:30
ℹ Vite client warmed up in 2286ms                                                                             08:42:33
ℹ Vite server warmed up in 361ms                                                                              08:42:33
✔ Nitro built in 615 ms                                                                                 nitro 08:42:34
[nuxt] [request error] [unhandled] [500] request to http://0.0.0.0:3000/__nuxt_vite_node__/manifest failed, reason: socket hang up ()
  at async $fetchRaw2 (./node_modules/ohmyfetch/dist/chunks/fetch.mjs:131:20)  
  at async ./.nuxt/dev/index.mjs:457:20  
  at async ./.nuxt/dev/index.mjs:520:64  
  at async ./.nuxt/dev/index.mjs:106:22  
  at async ./node_modules/h3/dist/index.mjs:592:19  
  at async Server.nodeHandler (./node_modules/h3/dist/index.mjs:538:7)
[nuxt] [request error] [unhandled] [500] request to http://0.0.0.0:3000/__nuxt_vite_node__/manifest failed, reason: socket hang up ()
  at async $fetchRaw2 (./node_modules/ohmyfetch/dist/chunks/fetch.mjs:131:20)  
  at async ./.nuxt/dev/index.mjs:457:20  
  at async ./.nuxt/dev/index.mjs:520:64  
  at async ./.nuxt/dev/index.mjs:106:22  
  at async ./node_modules/h3/dist/index.mjs:592:19  
  at async nodeHandler (./node_modules/h3/dist/index.mjs:538:7)  
  at async ufetch (./node_modules/unenv/runtime/fetch/index.mjs:9:17)  
  at async $fetchRaw2 (./node_modules/ohmyfetch/dist/chunks/fetch.mjs:131:20)  
  at async Object.errorhandler [as onError] (./.nuxt/dev/index.mjs:354:29)  
  at async Server.nodeHandler (./node_modules/h3/dist/index.mjs:545:9)
[nuxt] [request error] [unhandled] [500] request to http://0.0.0.0:3000/__nuxt_vite_node__/manifest failed, reason: socket hang up ()
  at async $fetchRaw2 (./node_modules/ohmyfetch/dist/chunks/fetch.mjs:131:20)  
  at async ./.nuxt/dev/index.mjs:457:20  
  at async ./.nuxt/dev/index.mjs:520:64  
  at async ./.nuxt/dev/index.mjs:106:22  
  at async ./node_modules/h3/dist/index.mjs:592:19  
  at async nodeHandler (./node_modules/h3/dist/index.mjs:538:7)  
  at async ufetch (./node_modules/unenv/runtime/fetch/index.mjs:9:17)  
  at async $fetchRaw2 (./node_modules/ohmyfetch/dist/chunks/fetch.mjs:131:20)  
  at async Object.errorhandler [as onError] (./.nuxt/dev/index.mjs:354:29)  
  at async Server.nodeHandler (./node_modules/h3/dist/index.mjs:545:9)
[nuxt] [request error] [unhandled] [500] request to http://0.0.0.0:3000/__nuxt_vite_node__/manifest failed, reason: socket hang up ()
  at async $fetchRaw2 (./node_modules/ohmyfetch/dist/chunks/fetch.mjs:131:20)  
  at async ./.nuxt/dev/index.mjs:457:20  
  at async ./.nuxt/dev/index.mjs:520:64  
  at async ./.nuxt/dev/index.mjs:106:22  
  at async ./node_modules/h3/dist/index.mjs:592:19  
  at async Server.nodeHandler (./node_modules/h3/dist/index.mjs:538:7)
[nuxt] [request error] [unhandled] [500] request to http://0.0.0.0:3000/__nuxt_vite_node__/manifest failed, reason: socket hang up ()
  at async $fetchRaw2 (./node_modules/ohmyfetch/dist/chunks/fetch.mjs:131:20)  
  at async ./.nuxt/dev/index.mjs:457:20  
  at async ./.nuxt/dev/index.mjs:520:64  
  at async ./.nuxt/dev/index.mjs:106:22  
  at async ./node_modules/h3/dist/index.mjs:592:19  
  at async nodeHandler (./node_modules/h3/dist/index.mjs:538:7)  
  at async ufetch (./node_modules/unenv/runtime/fetch/index.mjs:9:17)  
  at async $fetchRaw2 (./node_modules/ohmyfetch/dist/chunks/fetch.mjs:131:20)  
  at async Object.errorhandler [as onError] (./.nuxt/dev/index.mjs:354:29)  
  at async Server.nodeHandler (./node_modules/h3/dist/index.mjs:545:9)
[nuxt] [request error] [unhandled] [500] request to http://0.0.0.0:3000/__nuxt_vite_node__/manifest failed, reason: socket hang up ()
  at async $fetchRaw2 (./node_modules/ohmyfetch/dist/chunks/fetch.mjs:131:20)  
  at async ./.nuxt/dev/index.mjs:457:20  
  at async ./.nuxt/dev/index.mjs:520:64  
  at async ./.nuxt/dev/index.mjs:106:22  
  at async ./node_modules/h3/dist/index.mjs:592:19  
  at async nodeHandler (./node_modules/h3/dist/index.mjs:538:7)  
  at async ufetch (./node_modules/unenv/runtime/fetch/index.mjs:9:17)  
  at async $fetchRaw2 (./node_modules/ohmyfetch/dist/chunks/fetch.mjs:131:20)  
  at async Object.errorhandler [as onError] (./.nuxt/dev/index.mjs:354:29)  
  at async Server.nodeHandler (./node_modules/h3/dist/index.mjs:545:9)
```

**Comment by danielroe** [comment]
Please see the note at the bottom of https://v3.nuxtjs.org/api/commands/dev#nuxi-dev.

https://github.com/nuxt/framework/pull/7271

**Comment by OyewoleOyedeji** [comment]
@danielroe I got this additional error

```log
 ERROR  (node:25779) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
```

and the same trace log errors

**Comment by danielroe** [comment]
Ah. You will need to be on edge channel to pull in the fix I linked above. See https://v3.nuxtjs.org/guide/going-further/edge-channel/.

**Comment by OyewoleOyedeji** [comment]
@danielroe but would this affect the `modules` I already have

**Comment by danielroe** [comment]
You could also set `vite.devBundler` to `legacy` to keep previous behaviour until next rc.
