### ISSUE TITLE
Identifier '_unref' has already been declared

### ISSUE THREAD

**Issue by baixiaoyu2997** [nuxt/framework#7343]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.9`
- Nitro Version:    `0.5.1`
- Package Manager:  `pnpm@7.9.0`
- Builder:          `vite`
- User Config:      `target`, `components`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://codesandbox.io/s/lpz45n

### Describe the bug

in repro , just run `yarn generate`,will show error logs, i posted the log below

### Logs

```shell
ℹ Building server...                                                                                                                                              17:07:25

 WARN  Error when using sourcemap for reporting an error: Can't resolve original location of error.                                                               17:07:26


 ERROR  Identifier '_unref' has already been declared (Note that you need plugins to import files that are not JavaScript)                                        17:07:26
file: /Users/l.rain/Documents/workspace/DEMO/deorder-copy/components/form/Select.vue:2:62
1: import { computed } from 'vue';
2: import { unref as _unref, mergeProps as _mergeProps, unref as _unref } from "vue"
                                                                 ^
3: import { ssrRenderAttrs as _ssrRenderAttrs } from "vue/server-renderer"


 ERROR  Identifier '_unref' has already been declared (Note that you need plugins to import files that are not JavaScript)                                        17:07:26

  at error (node_modules/.pnpm/rollup@2.77.3/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
  at Module.error (node_modules/.pnpm/rollup@2.77.3/node_modules/rollup/dist/es/shared/rollup.js:12412:16)
  at Module.tryParse (node_modules/.pnpm/rollup@2.77.3/node_modules/rollup/dist/es/shared/rollup.js:12789:25)
  at Module.setSource (node_modules/.pnpm/rollup@2.77.3/node_modules/rollup/dist/es/shared/rollup.js:12694:24)
  at ModuleLoader.addModuleSource (node_modules/.pnpm/rollup@2.77.3/node_modules/rollup/dist/es/shared/rollup.js:22136:20)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
```

**Comment by danielroe** [comment]
cc: @antfu

**Comment by Hironogawa** [comment]
Any update on this?

**Comment by LucaMargadant** [comment]
> Any update on this?

It seems like the error shows up when you use v-bind() in your stylesheets.
After removing them all and binding the styles directly to the DOM Element i've been able to build the app.

Maybe this helps anyone to locate the error.

**Comment by antfu** [comment]
Fix pr already made last week https://github.com/vuejs/core/pull/6664
