### ISSUE TITLE
Cloudflare worker build error

### ISSUE THREAD

**Issue by mehotkhan** [nuxt/framework#7402]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.0-rc.10-27711996.0ab29f6`
- Nitro Version:    `0.5.2-27709289.11cc5cd`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `ssr`, `app`, `css`, `plugins`, `build`, `modules`, `experimental`, `components`, `vite`, `intlify`, `vueuse`, `windicss`, `content`
- Runtime Modules:  `unplugin-icons/nuxt`, `@intlify/nuxt3@0.2.4`, `@nuxt/content@2.1.0`, `@vueuse/nuxt@9.2.0`, `@nuxtjs/eslint-module@3.1.0`, `nuxt-windicss@2.5.2`, `@nuxtjs/svg@0.4.0`
- Build Modules:    `-`
------------------------------

### Reproduction

-

### Describe the bug

` WARN  To preserve the export signature of the entry module "node_modules/nitropack/dist/runtime/entries/cloudflare.mjs", an empty facade chunk was created. This often happens when creating a bundle for a web app where chunks are placed in script tags and exports are ignored. In this case it is recommended to set "preserveEntrySignatures: false" to avoid this and reduce the number of chunks. Otherwise if this is intentional, set "preserveEntrySignatures: 'strict'" explicitly to silence this warning.

 ERROR  addEventListener is not defined                                                                               11:14:47

  at .output/server/chunks/nitro/cloudflare.mjs:3361:1
  at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
  at async prerender (node_modules/nitropack/dist/shared/nitro.eb16e208.mjs:2670:26)
  at async node_modules/nuxt/dist/index.mjs:1412:7
  at async build (node_modules/nuxt/dist/index.mjs:1969:5)
  at async Object.invoke (node_modules/nuxi/dist/chunks/build.mjs:45:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:50:20)`

**Comment by marvincaspar** [comment]
I have a similar issue. `NITRO_PRESET=cloudflare yarn build` works fine for me. 

Than I have tried to start the server with node and miniflare and both options throws an error.

- Node: `node .output/server/index.mjs` throws `ReferenceError: addEventListener is not defined`
- `npx miniflare .output/server/index.mjs --site .output/public` throws `ReferenceError: __dirname is not defined`

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏

**Comment by marvincaspar** [comment]
I have tried to reproduce it with a clean project and that worked. I than added more and more modules and configuration and the error appears after adding the nuxt image module. Seems like there is already an issue open https://github.com/nuxt/image/issues/602

**Comment by mehotkhan** [comment]
Nuxt config : 
`
import { defineNuxtConfig } from 'nuxt'
import { IntlifyModuleOptions } from '@intlify/nuxt3'
import UnpluginComponentsVite from 'unplugin-vue-components/vite'
import IconsResolver from 'unplugin-icons/resolver'

declare module '@nuxt/schema' {
  interface NuxtConfig {
    intlify?: IntlifyModuleOptions
  }
}

// https://v3.nuxtjs.org/docs/directory-structure/nuxt.config
export default defineNuxtConfig({
  // server side rendering mode
  // ssr: true,
  target: 'static',

  // app
 

  // css
  css: [
    'vue-easy-lightbox/external-css/vue-easy-lightbox.css',
    'vue3-carousel/dist/carousel.css',
    'virtual:windi-base.css',
    'virtual:windi-components.css',
    'virtual:windi-utilities.css',
    '~/assets/sass/vendor.scss',
    '~/assets/sass/app.scss',
    '~/assets/fonts.css',
  ],

  // plugins
  plugins: ['~/plugins/navbar.ts'],

  // build
  build: {
    transpile: ['@headlessui/vue'],
  },

  modules: [
    'unplugin-icons/nuxt',
    '@intlify/nuxt3',
    '@nuxt/content',
    '@vueuse/nuxt',
    '@nuxtjs/eslint-module',
    'nuxt-windicss',
    '@nuxtjs/svg',
  ],
  // experimental features
  experimental: {
    reactivityTransform: true,
  },

  // auto import components
  components: true,

  // vite plugins
  vite: {
    plugins: [
      UnpluginComponentsVite({
        dts: true,
        resolvers: [
          IconsResolver({
            prefix: 'Icon',
          }),
        ],
      }),
    ],
  },

  // localization - i18n config
  intlify: {
    localeDir: 'locales',
    vueI18n: {
      locale: 'en',
      fallbackLocale: 'en',
      availableLocales: ['en', 'ar', 'fr'],
    },
  },

  // vueuse
  vueuse: {
    ssrHandlers: true,
  },

  // windicss
  windicss: {
    analyze: {
      analysis: {
        interpretUtilities: false,
      },
      server: {
        port: 4000,
        open: false,
      },
    },
    scan: true,
  },

  // content
  content: {
    markdown: {
      mdc: true,
    },
    highlight: {
      theme: 'github-dark',
    },
  },
  nitro: {
    rollupConfig: {
      output: {
        generatedCode: {
          symbols: true,
        },
      },
    },
  },
})
`

package.json
`
{
  
  "scripts": {
    "build": "nuxt build",
    "build:cloudflare": "NITRO_PRESET=cloudflare nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "start": "node .output/server/index.mjs",
    "serve": "serve  .output/public",
    "lint": "eslint --ext \".ts,.js,.vue\" --ignore-path .eslintignore .",
    "lintfix": "eslint --fix --ext \".ts,.js,.vue\" --ignore-path .eslintignore .",
    "clean": "rm -rf .nuxt dist .output",
    "generate:locales": "node tools/translator.js ./locales en.yml"
  },
  "devDependencies": {
    "@headlessui/vue": "1.7.1",
    "@iconify/json": "^2.1.106",
    "@intlify/nuxt3": "0.2.4",
    "@nuxt/content": "^2.1.0",
    "@nuxtjs/eslint-config-typescript": "^11.0.0",
    "@nuxtjs/eslint-module": "3.1.0",
    "@nuxtjs/svg": "^0.4.0",
    "@vueuse/nuxt": "9.2.0",
    "eslint": "^8.23.1",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-nuxt": "^4.0.0",
    "eslint-plugin-prettier": "^4.2.1",
    "js-yaml": "^4.1.0",
    "nuxt": "npm:nuxt3@3.0.0-rc.10-27716896.3753ea0",
    "nuxt-windicss": "2.5.2",
    "postcss": "8.4.16",
    "postcss-loader": "^7.0.1",
    "prettier": "^2.7.1",
    "sass": "1.54.9",
    "sass-loader": "^13.0.2",
    "serve": "^14.0.1",
    "translate": "^1.4.1",
    "typescript": "^4.8.3",
    "unplugin-icons": "0.14.9",
    "unplugin-vue-components": "0.22.7"
  },
  "dependencies": {
    "@vue-leaflet/vue-leaflet": "^0.6.1",
    "leaflet": "^1.8.0",
    "vue-easy-lightbox": "^1.8.2",
    "vue3-carousel": "^0.1.46"
  },
  "resolutions": {
    "autoprefixer": "10.4.5"
  }
}

`

**Comment by marvincaspar** [comment]
Hi @danielroe, I could reproduce the issue from @mehotkhan. There is an other issue if you use `cloudflare_pages` as nitro preset. Is this the right place for this issue or should it be moved to https://github.com/unjs/nitro?

Here's the repo https://github.com/marvincaspar/nuxt-cloudflare

**Comment by danielroe** [comment]
If you can reproduce with nitro (but not nuxt) then filing an upstream issue would be very helpful. :pray:

**Comment by danielroe** [comment]
I can no longer reproduce with the linked repo. Steps:

1. clone [marvincaspar/nuxt-cloudflare](https://github.com/marvincaspar/nuxt-cloudflare)
2. install latest nuxt
3. run `build`
4. `npx wrangler dev .output/server/index.mjs --site .output/public --local`

If you are still experiencing this, please let me know with a reproduction and I will happily reopen.
