### ISSUE TITLE
ERROR  Cannot start nuxt:  moduleDirectories option must only contain directory names with rc.10-27716618.9382b42     

### ISSUE THREAD

**Issue by hermesalvesbr** [nuxt/framework#7453]
### Environment

```
npx nuxi info
Nuxi 3.0.0-rc.10-27716618.9382b42                                                                                15:00:34
RootDir: /home/dss/Projetos/nuxt/PMA                                                   15:00:35
Nuxt project info:                                                                                               15:00:35

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.10-27716618.9382b42`
- Nitro Version:    `0.5.2-27709289.11cc5cd`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `loading`, `modules`, `formkit`, `runtimeConfig`, `directus`, `head`, `build`, `publicRuntimeConfig`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.3.3`, `nuxt-directus@3.0.3`, `@formkit/nuxt@1.0.0-beta.11-1c50a05`, `@nuxtjs/dotenv@1.4.1`, `@vueuse/nuxt@9.2.0`
- Build Modules:    `-`
------------------------------

👉 Report an issue: https://github.com/nuxt/framework/issues/new                                                 15:00:35

👉 Suggest an improvement: https://github.com/nuxt/framework/discussions/new

👉 Read documentation: https://v3.nuxtjs.org
```

### Reproduction

yarn dev: 

 ```
ERROR  Cannot start nuxt:  moduleDirectories option must only contain directory names. If you want to load modules from somewhere not supported by the default module resolution algorithm, see modulePaths.

  at nodeResolve (node_modules/@rollup/plugin-node-resolve/dist/es/index.js:967:11)
  at getRollupConfig (node_modules/nitropack/dist/shared/nitro.eb16e208.mjs:1121:29)
  at build (node_modules/nitropack/dist/shared/nitro.eb16e208.mjs:1268:24)
  at node_modules/nuxt/dist/index.mjs:1417:13
  at async build (node_modules/nuxt/dist/index.mjs:1986:5)
```

ERROR  Cannot start nuxt:  moduleDirectories option must only contain directory names. If you want to load modules from somewhere not supported by the default module resolution algorithm, see modulePaths.

### Describe the bug

After upgrade nuxt for Nuxt 3.0.0-rc.10-27716618.9382b42 with Nitro 0.5.2-27709289.11cc5cd  show me this error: 

> ERROR  Cannot start nuxt:  moduleDirectories option must only contain directory names. If you want to load modules from somewhere not supported by the default module resolution algorithm, see modulePaths.

### Additional context

I'm using a custom publishConfig in my packpage.json:

```
"publishConfig": {
    "registry": "https://localhost:4983"
  },
```

### Logs

```shell
ERROR  Cannot start nuxt:  moduleDirectories option must only contain directory names. If you want to load modules from somewhere not supported by the default module resolution algorithm, see modulePaths.

  at nodeResolve (node_modules/@rollup/plugin-node-resolve/dist/es/index.js:967:11)
  at getRollupConfig (node_modules/nitropack/dist/shared/nitro.eb16e208.mjs:1121:29)
  at build (node_modules/nitropack/dist/shared/nitro.eb16e208.mjs:1268:24)
  at node_modules/nuxt/dist/index.mjs:1417:13
  at async build (node_modules/nuxt/dist/index.mjs:1986:5)
  at async Promise.all (index 1)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6784:9)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6827:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:50:20)

ℹ Vite server warmed up in 393ms                                                                                 14:51:42
ℹ Vite client warmed up in 2829ms
```

**Comment by Suyashtnt** [comment]
any updates on when the fix is going to be released?

**Comment by danielroe** [comment]
This fix was released in nitro 0.5.2. Ensure you have upgraded your dependencies with `nuxi upgrade` or `npm upgrade nuxt`. If that doesn't resolve it, please do reply with a reproduction and I'll happily reopen this and take a look.

**Comment by Suyashtnt** [comment]
hmm, it seems that when using `dream2nix`, using their builder doesn't work but manually running `npm i` and then `nuxt dev` does. strange

**Comment by danielroe** [comment]
Perhaps it is an issue with their builder, and they simply need a fix similar to the one in the linked PR.
