### ISSUE TITLE
 Unable to start

### ISSUE THREAD

**Issue by mendmania** [nuxt/framework#7564]
### Environment

Operating System: Windows 11 Edited Windows 10

Node Version: v16.17.0
Nuxt Version: 3.0.0-rc.10
Npm version: 8.19.2

### Reproduction

Create a minimal nuxt v3 project

npx nuxi init nuxt-app

code nuxt-app

npm install

### Describe the bug

 Unable to start

### Logs

```shell
[nuxt] [request error] [unhandled] [500] vue.defineComponent is not a function
  at Object.<anonymous> (C:\Users\arifa\node_modules\vue-router\dist\vue-router.cjs.js:2118:42)  
  at Module._compile (node:internal/modules/cjs/loader:1126:14)
  at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
  at Module.load (node:internal/modules/cjs/loader:1004:32)
  at Function.Module._load (node:internal/modules/cjs/loader:839:12)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29)
  at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
[nuxt] [request error] [unhandled] [500] vue.defineComponent is not a function
  at Object.<anonymous> (C:\Users\arifa\node_modules\vue-router\dist\vue-router.cjs.js:2118:42)
  at Module._compile (node:internal/modules/cjs/loader:1126:14)
  at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
  at Module.load (node:internal/modules/cjs/loader:1004:32)
  at Function.Module._load (node:internal/modules/cjs/loader:839:12)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29)
  at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
```

**Comment by mendmania** [comment]
Its just:

1. npx nuxi init nuxt-app

2. code nuxt-app

3. npm install 

4. cd nuxt-app npm run dev

**Comment by mendmania** [comment]
Problem: not knowing exact 'node_modules' folder where project is, trying to include from first node_modules found. I had a 'node_modules' folder on \Users\[username].

**Comment by marcodarko** [comment]
Same issue, keeps trying to load from global node modules

**Comment by danielroe** [comment]
I believe this is the same issue as https://github.com/nuxt/framework/issues/7564. Closing to follow there.
