### ISSUE TITLE
@nuxtjs/pwa: error after install

### ISSUE THREAD

**Issue by 524c** [nuxt/framework#7605]
### Environment

Nuxt project info: (copied to clipboard)                                       12:25:34

------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.8.0`
- Nuxt Version:     `3.0.0-rc.10`
- Nitro Version:    `0.5.3`
- Package Manager:  `pnpm@7.11.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

```
npx nuxi init app && cd app
pnpm install --shamefully-hoist
# 🆗
pnpm dev --open

# go back to the terminal, install @nuxt/pwa, and run again.
# ⛔
pnpm i @nuxtjs/pwa
pnpm dev --open
```

### Describe the bug

after installing the package @nuxt/pwa this error appears, even without the module being included in the project:
```[nuxt] [request error] [unhandled] [500] __vite_ssr_import_0__.defuFn is not a function```

### Logs

```shell
Nuxt 3.0.0-rc.10 with Nitro 0.5.3                                                                                                                                       12:26:19
                                                                                                                                                                        12:26:22
  > Local:    http://localhost:3000/

ℹ Vite client warmed up in 2767ms                                                                                                                                       12:26:31
✔ Nitro built in 2665 ms                                                                                                                                          nitro 12:26:33
(node:18593) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
[nuxt] [request error] [unhandled] [500] __vite_ssr_import_0__.defuFn is not a function
  at ./.nuxt/app.config.mjs:9:54
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async ViteNodeRunner.directRequest (./node_modules/.pnpm/vite-node@0.23.2/node_modules/vite-node/dist/client.mjs:251:5)
  at async ViteNodeRunner.cachedRequest (./node_modules/.pnpm/vite-node@0.23.2/node_modules/vite-node/dist/client.mjs:128:12)
  at async request (./node_modules/.pnpm/vite-node@0.23.2/node_modules/vite-node/dist/client.mjs:151:16)
  at async ./node_modules/.pnpm/nuxt@3.0.0-rc.10/node_modules/nuxt/dist/app/config.mjs:5:31
  at async ViteNodeRunner.directRequest (./node_modules/.pnpm/vite-node@0.23.2/node_modules/vite-node/dist/client.mjs:251:5)
  at async ViteNodeRunner.cachedRequest (./node_modules/.pnpm/vite-node@0.23.2/node_modules/vite-node/dist/client.mjs:128:12)
  at async request (./node_modules/.pnpm/vite-node@0.23.2/node_modules/vite-node/dist/client.mjs:151:16)
  at async ./node_modules/.pnpm/nuxt@3.0.0-rc.10/node_modules/nuxt/dist/app/index.mjs:7:31
```

**Comment by danielroe** [comment]
`@nuxtjs/pwa` is not yet compatible with Nuxt 3. You might check out https://github.com/kevinmarrec/nuxt-pwa-module in the meantime.
