### ISSUE TITLE
[RC 9] [RC 10] `Cannot read properties of undefined (reading 'modules')` when `vue` is installed in parent dir

### ISSUE THREAD

**Issue by pi0** [nuxt/framework#7609]
### Related issues

- #7532 
- #7220
- #7573
- sidestream-tech/sidebase#16

### Reproduction

Minimal reproduction: https://stackblitz.com/edit/github-2yn1ze?file=app%2Fpackage.json,app%2Fnuxt.config.ts

### Describe the bug

How it happens: If vue dependency is installed outside of project directory in an adjutant directory (usually home directory with `node_modules`), `vite-node` that is enabled by default for RC.9+ makes issues. (issue is with nuxt custom external options)

## Workaround 1 

Check you home directory. If there is any `node_modules` dir, remove it or rename it. It is probably created wrongly in the past.

## Workaround 2

It might be also because of a monorepo setup that has `../node_modules/vue` dependency. In this case, switch to the legacy vite bundler:

```ts
export default defineNuxtConfig({
  vite: {
    devBundler: 'legacy',
  },
});
```

**Comment by richardeschloss** [comment]
Thanks for the PR! FWIW, 3.0.0-rc.11-27722816.abd0feb seems to be having things working on my end 🤞

**Comment by andreas83** [comment]
i had this issue even with 3.0.0-rc.11-27722816.abd0feb, node_modules removed from project and parent dir as well adding legacy devBunder to nuxt.config.ts. 

At the end, removing the yarn.lock file fixed the issue for me. 

```

Nuxt 3.0.0-rc.11-27722816.abd0feb with Nitro 0.5.4-27719614.c3af02d                                                                                                      09:58:22
                        
[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: Server rendering context not provided. Make sure to only call useSSRContext() conditionally in the server build.
[Vue warn]: Unhandled error during execution of setup function 
  at <NuxtRoot>
[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'modules')
  at _sfc_main.setup (./node_modules/nuxt/dist/app/components/nuxt-root.vue:67:16)  
  at callWithErrorHandling (./node_modules/vue/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:157:22)  
  at setupStatefulComponent (./node_modules/vue/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7109:29)  
  at setupComponent (./node_modules/vue/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7064:11)  
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:172:17)  
  at renderToString (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:450:26)  
  at Object.renderToString$1 [as renderToString] (./.nuxt/dev/index.mjs:472:24)  
  at Object.renderToString (./node_modules/vue-bundle-renderer/dist/runtime.mjs:173:40)  
  at processTicksAndRejections (node:internal/process/task_queues:96:5)  
  at async ./.nuxt/dev/index.mjs:527:21

```


------------------------------
- Operating System: `Linux`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-rc.11-27722816.abd0feb`
- Nitro Version:    `0.5.4-27719614.c3af02d`
- Package Manager:  `yarn@1.21.1`
- Builder:          `vite`
- User Config:      `buildModules`, `publicRuntimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `nuxt-windicss@2.5.2`
------------------------------

**Comment by pi0** [comment]
Happy hearing finally issue fixed for you @andreas83. As mentioned in remarks, there might be other causes that shows this issue (basically for any reason if two versions of vue 3 being used in server-side). Renovating lockfile is a nice idea 👍🏼

**Comment by Maxp777** [comment]
. Renovating lockfile is a nice idea 👍🏼 is a shit idea that not work

**Comment by Maxp777** [comment]
second also is a shit solution

**Comment by Maxp777** [comment]
i am boring from yours nuxt

**Comment by theolavaux** [comment]
I'm creating a monorepo using Turborepo, pnpm and `nuxt@3.0.0` for my apps. I have installed `vue@3.2.45` into the root folder of the monorepo and I'm still seeing this issue pop up when I run `nuxt dev`. I tried installing the dependency either in the root folder or in the apps directly but it didn't get rid of the error. Neither did `vite.devBundler: 'legacy'` along with a clean of `node_modules`. Is anyone still seing this issue?

**Comment by theolavaux** [comment]
Found the issue, for people also stuck on this, make sure your `.npmrc` is at the root of the monorepo and not inside your apps 😉

**Comment by l4dybird** [comment]
@theolavaux 
It can be solved by modifying the package.json of each package as follows.

```json
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@vue/server-renderer": "3.2.45",
    "@vue/runtime-core": "3.2.45",
    "nuxt": "3.0.0",
    "vue": "3.2.45",
    "vue-bundle-renderer": "1.0.0"
  }
}
```

sample
https://github.com/l4dybird/nuxt3-monorepo

**Comment by maunzCache** [comment]
> @theolavaux It can be solved by modifying the package.json of each package as follows.
> 
> ```json
> {
>   "private": true,
>   "scripts": {
>     "build": "nuxt build",
>     "dev": "nuxt dev",
>     "generate": "nuxt generate",
>     "preview": "nuxt preview",
>     "postinstall": "nuxt prepare"
>   },
>   "devDependencies": {
>     "@vue/server-renderer": "3.2.45",
>     "@vue/runtime-core": "3.2.45",
>     "nuxt": "3.0.0",
>     "vue": "3.2.45",
>     "vue-bundle-renderer": "1.0.0"
>   }
> }
> ```
> 
> sample https://github.com/l4dybird/nuxt3-monorepo

Running a clean nuxt init via pnpm with this setup you mentioned results in a new error for me when running pnpm dev.

```
Error: Cannot find module '~/Projekte/github/node_modules/.pnpm/nuxt@3.0.0_iukboom6ndih5an6iafl45j2fe/node_modules/nuxt/bin/nuxt.mjs'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Module._load (node:internal/modules/cjs/loader:885:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

Not sure if this is my fault or if this is a general issue. Just wanted to mention it in this issue.
