### ISSUE TITLE
Fresh create nuxt app not starting properly on Windows 10

### ISSUE THREAD

**Issue by klausXR** [nuxt/framework#763]
### Environment

Nuxt CLI v3.0.0-27234123.a896c64   
OS: Windows 10 Build 19043
Node: 14.17.0
Npm: 6.14.8

### Describe the bug and expected behavior

When running `npm run dev -o`, it builds properly and starts for a second, but then the console fills with the following messages

```
  > Local:    http://localhost:3000/
  > Network:  http://192.168.56.1:3000/
  > Network:  http://192.168.0.102:3000/

√ Generated nuxt.d.ts                                                                                                                                            17:12:10
i Vite warmed up in 1580ms                                                                                                                                       17:12:10
√ Vite server built in 1915ms                                                                                                                                    17:12:11
√ Vite server built in 55ms                                                                                                                                      17:12:11
√ Nitro built in 304 ms                                                                                                                                          17:12:11
√ Vite server built in 32ms                                                                                                                                      17:12:11
√ Vite server built in 27ms                                                                                                                                      17:12:11
√ Vite server built in 60ms                                                                                                                                      17:12:11
√ Vite server built in 75ms                                                                                                                                      17:12:12
√ Vite server built in 29ms    
Server Side Rendering Error: Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:782:11)
    at Loader.resolve (internal/modules/esm/loader.js:88:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:241:28)
    at Loader.import (internal/modules/esm/loader.js:176:28)
    at importModuleDynamically (internal/modules/esm/translators.js:114:35)
    at exports.importModuleDynamicallyCallback (internal/process/esm_loader.js:30:14)
    at $id_60f0615f (file:///C:/Users/X/Desktop/projects/nuxt3-app/.nuxt/dist/server/server.mjs:84:185)
    at __instantiateModule__ (file:///C:/Users/X/Desktop/projects/nuxt3-app/.nuxt/dist/server/server.mjs:1798:9)
    at __ssrLoadModule__ (file:///C:/Users/X/Desktop/projects/nuxt3-app/.nuxt/dist/server/server.mjs:1746:25)
    at ssrImport (file:///C:/Users/X/Desktop/projects/nuxt3-app/.nuxt/dist/server/server.mjs:1770:13) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}
```

**The `Vite server build in XXX` is getting called recursively and doesnt stop.**

### Steps to reproduce

1. npx nuxi init nuxt3-app
2. code -r nuxt3-app
3. npm install
4. npm run dev -o

**Comment by madsh93** [comment]
Windows 10. Same issue here. Clean install

**Comment by clarkdo** [comment]
Checking now

**Comment by innocenzi** [comment]
That hotfix works for me on Windows 10 👍

**Comment by pi0** [comment]
Awesome! Thanks for confirming. Let's track the webpack issue (https://github.com/nuxt/framework/issues/763#issuecomment-941076192) in another issue :)

**Comment by mkhennoussi** [comment]
Hi @pi0 I removed the nodes_modules and yarn.lock but still not working.
Here is the `npx nuxi info` result :
```
- Operating System: `Windows_NT`
- Node Version:     `v16.8.0`
- Nuxt Version:     `3-3.0.0-27234169.3c132a8`
- Package Manager:  `Yarn`
- Bundler:          `Webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
```

**Comment by timstats91** [comment]
I'm still having this issue late in 2022. Will it not be resolved?
