### ISSUE TITLE
Nuxt Site created with `npx nuxi@latest init nuxt-app` not working within monorepo

### ISSUE THREAD

**Issue by m0dch3n** [nuxt/framework#7642]
### Environment

Nuxi 3.0.0-rc.10                                                                                                                 09:10:09
RootDir: /app/                                                                                                                     09:10:09
Nuxt project info:                                                                                                               09:10:09

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.10`
- Nitro Version:    `0.5.3`
- Package Manager:  `npm@8.18.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Since my monorepo is quite big, I unfortunately can't isolate the issue to reproduce it.

### Describe the bug

I'm trying to create a fresh nuxt app. Which is working!

**However**, creating the a fresh nuxt app in my monorepo (already containing vite, vuejs, etc...), it is no longer working.

When opening the app, I get

```
500
nuxtAppCtx.tryUse is not a function

at Module.useNuxtApp (/app/node_modules/nuxt/dist/app/nuxt.mjs:138:38)
at Module.useHead (/app/node_modules/nuxt/dist/head/runtime/composables.mjs:9:25)
at /app/node_modules/nuxt/dist/head/runtime/plugin.mjs:27:25
at fn (/app/node_modules/nuxt/dist/app/nuxt.mjs:128:27)
at Object.callAsync (/app/node_modules/unctx/dist/index.mjs:41:19)
at callWithNuxt (/app/node_modules/nuxt/dist/app/nuxt.mjs:130:23)
at applyPlugin (/app/node_modules/nuxt/dist/app/nuxt.mjs:74:29)
at Module.applyPlugins (/app/node_modules/nuxt/dist/app/nuxt.mjs:84:11)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async createNuxtAppServer (/app/node_modules/nuxt/dist/app/entry.mjs:30:7)
```

**Comment by danielroe** [comment]
See https://github.com/nuxt/framework/issues/6523. This is caused by having an older version of `unctx` installed. You can typically resolve by running `npx nuxi upgrade` or otherwise upgrading your dependencies or refreshing your lockfile.

**Comment by m0dch3n** [comment]
thank you Daniel, refreshing my lockfile helped!
