### ISSUE TITLE
Fail to import .scss async

### ISSUE THREAD

**Issue by ilyary** [nuxt/framework#7654]
### Environment

- Operating System: `Darwin`
- Node Version:     `v14.19.3`
- Nuxt Version:     `3.0.0-rc.10`
- Nitro Version:    `0.5.3`
- Package Manager:  `npm@8.12.1`
- Builder:          `vite`
- User Config:      `app`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`

"dependencies": {
    "@fortawesome/fontawesome-free": "^6.2.0",
    "vue": "^3.2.37"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^3.1.0",
    "sass": "^1.54.9",
    "sass-loader": "^13.0.2",
    "vite": "^3.0.9"
  }

### Reproduction

https://github.com/ilyary/hyve-gtm

### Describe the bug

Fails to import like this: import("@/styles/async.scss");

```
<template>
  <NuxtPage />
</template>

<script>
import "bootstrap/scss/bootstrap.scss";

//import "@/styles/async.scss"; // That works

import("@/styles/xxx.js"); // That works

import("@/styles/async.scss"); // Not working
/*
>npm run generate
...

ℹ Initializing prerenderer

ERROR  Rollup error: Could not resolve './_nuxt/async.744a712b.js' from .nuxt/dist/server/server.mjs                                         nitro 09:45:18


ERROR  Could not resolve './_nuxt/async.744a712b.js' from .nuxt/dist/server/server.mjs                                                             09:45:18

 at error (node_modules/rollup/dist/es/shared/rollup.js:1858:30)
 at ModuleLoader.handleResolveId (node_modules/rollup/dist/es/shared/rollup.js:22357:24)
 at ModuleLoader.resolveDynamicImport (node_modules/rollup/dist/es/shared/rollup.js:22411:120)
 at async node_modules/rollup/dist/es/shared/rollup.js:22306:32
 */
</script>
```

**Comment by danielroe** [comment]
This is true in general for Vite dynamic imports of CSS.

**Comment by ilyary** [comment]
> What are you trying to do with a dynamic import of CSS?
I'm trying to load heavy fontawesome assets after app bundle is loaded.

if(process.client) does the trick, thank you.
The reason I raised this issue is that "import("@/styles/async.scss")" works on origin Vue SSG both client/server but not on Nuxt

**Comment by wadaahmad** [comment]
> What are you trying to do with a dynamic import of CSS?
> 

Btw : I also waiting for this feature, since i created SaaS product which user can select their own template, I came from Nuxt 2 
 with bridge enabled, I have already migrated to nuxt3 but sadly it's not working yet so I just revert it (I love pain :') 

I really love nuxt and vue, thanks to all your works (nuxt team).
