### ISSUE TITLE
RC 11 - in Production Can't  Import External Packages

### ISSUE THREAD

**Issue by mohammad-ashrafi2020** [nuxt/framework#7698]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.11.0`
- Builder:          `vite`
- User Config:      `typescript`, `buildModules`, `vite`, `css`, `image`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.4.2`, `@nuxt/image-edge@1.0.0-27719579.87dcdf2`

### Reproduction

https://github.com/mohammad-ashrafi2020/hamcar-front

### Describe the bug

In development anything is Ok , But when Build your project and run this , Throw Exception

### Logs

```shell
[nuxt] [request error] [unhandled] [500] Named export 'useToast' not found. The requested module 'vue-toastification' is a CommonJS module, which may not support all module.exports as named exports.    
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'vue-toastification';
const { useToast: useToast$1 } = pkg;

  at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
-----------------------------------------------------------------------------


[nuxt] [request error] [unhandled] [500] Named export 'drop' not found. The requested module 'lodash' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'lodash';
const { drop } = pkg;

  at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
  at async /C:/inetpub/wwwroot/front.test13.ir/server/chunks/renderer.mjs:306:24
  at async /C:/inetpub/wwwroot/front.test13.ir/server/chunks/renderer.mjs:368:64
  at async /C:/inetpub/wwwroot/front.test13.ir/server/chunks/renderer.mjs:30:22
  at async /C:/inetpub/wwwroot/front.test13.ir/server/node_modules/h3/dist/index.mjs:592:19
  at async Server.nodeHandler (/C:/inetpub/wwwroot/front.test13.ir/server/node_modules/h3/dist/index.mjs:538:7)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
  at async /C:/Users/vivanit.ir/source/repos/hamcar-front/.output/server/chunks/renderer.mjs:306:24
  at async /C:/Users/vivanit.ir/source/repos/hamcar-front/.output/server/chunks/renderer.mjs:368:64
  at async /C:/Users/vivanit.ir/source/repos/hamcar-front/.output/server/chunks/renderer.mjs:30:22
  at async /C:/Users/vivanit.ir/source/repos/hamcar-front/.output/server/node_modules/h3/dist/index.mjs:592:19
  at async Server.nodeHandler (/C:/Users/vivanit.ir/source/repos/hamcar-front/.output/server/node_modules/h3/dist/index.mjs:538:7)
```

**Comment by mohammad-ashrafi2020** [comment]
This Error when Throwed , use object destructuring for import packages

**Comment by vaban-ru** [comment]
Same problem with 

```
 'vue-final-modal/lib.js' is imported by .nuxt/dist/server/server.mjs, but could not be resolved – treating it as an external dependency  
 ```

**Comment by danielroe** [comment]
Have you tried the syntax in the error message?

Apart from this issue, I would recommend importing directly from (e.g.) `lodash/pick.js` rather than `import { pick } from('lodash')`.

See also https://v3.nuxtjs.org/guide/concepts/esm/#troubleshooting-esm-issues. You can also follow https://github.com/nuxt/framework/issues/7206.
