### ISSUE TITLE
Production build doesn't work on fresh Nuxt3 project

### ISSUE THREAD

**Issue by proskurindima** [nuxt/framework#772]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v14.17.1`
- Nuxt Version:     `3-3.0.0-27234133.44f8904`
- Package Manager:  `Yarn`
- Bundler:          `Webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
-----------------------------

### Describe the bug and expected behavior

When running "yarn start", the following error occurs:
` yarn run v1.22.10
$ node .output/server
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '/home/user/projects/winepad/.output/server'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
} `

In this case, the command before "yarn build" is executed without errors. Folder ".output/server" generated, it contains the index.mjs file.

A similar problem is observed when using npm

### Steps to reproduce

1. yarn build
2. yarn start
3. See error

**Comment by takacspeter** [comment]
node .output/server/index.mjs

**Comment by proskurindima** [comment]
@pi0 Hi!
Yes, this file exists.

But when i run  "yarn start" the loader does not see it.
I'll clarify that I have not modified any files, this is the first launch of the fresh project.

If I start file directly, as I mentioned @takacspeter, everything works as expected.

**Comment by ismael-albert** [comment]
i'm still having the same error

->
npm run start

> @ start C:\Users\ismae\Documents\workspace\project
> node .output/server/index.mjs

Listening on http://localhost:3000/
Directory import 'C:\Users\ismae\Documents\workspace\project\.output\server\node_modules\@heroicons\vue\solid' is not supported resolving ES modules imported from C:\Users\ismae\Documents\workspace\project\.output\server\chunks\server2.mjs
Did you mean to import @heroicons/vue/solid/index.js?
  at new NodeError (internal/errors.js:322:7)
  at finalizeResolution (internal/modules/esm/resolve.js:304:17)
  at moduleResolve (internal/modules/esm/resolve.js:731:10)
  at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:842:11)        
  at Loader.resolve (internal/modules/esm/loader.js:89:40)
  at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
  at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:76:40)
  at link (internal/modules/esm/module_job.js:75:36)

**Comment by androot-dev** [comment]
Tengo el mismo problema

**Comment by ismael-albert** [comment]
tenta mudar o node para a versão 14.18.2
