### ISSUE TITLE
Dynamic component loading using addComponentsDir hook fails if template html is referenced using src on Windows

### ISSUE THREAD

**Issue by alexgrozav** [nuxt/framework#7882]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.1.2`
- Builder:          `vite`
- User Config:      `modules`, `inkline`
- Runtime Modules:  `@inkline/nuxt@3.1.4`
- Build Modules:    `-`

### Reproduction

Crashes on Windows only:

1. `npx nuxi init my-nuxt-app`
2. `cd my-nuxt-app`
3. `npm install`
4. `npm install --save @inkline/inkline @inkline/nuxt`
5. `npm install --save-dev sass`
6. Add `@inkline/nuxt` to your Nuxt config:
  ```js
  import { defineNuxtConfig } from 'nuxt';
  
  export default defineNuxtConfig({
      modules: [
          '@inkline/nuxt'
      ]
  });
  ```
7. Add some content to `app.vue`
  ```html
  <template>
    <div>
      <i-form>
        <i-form-group>
          <i-input-label>Example</i-input-label>
          <i-input value="Nuxt" />
        </i-form-group>
      </i-form>
    </div>
  </template>
  ```
8. `npm run dev`

### Describe the bug

This bug is happening only on a Windows environment. On Linux and MacOS it works as expected.

From what I understand, the `addComponentsDir` hook seems to be crashing when importing `.vue` component files that reference templates instead of defining them directly (`<template src="./somefile.html">`).

Inside of the [Inkline Nuxt Module](https://github.com/inkline/nuxt-module-inkline), the `addComponentsDir` is used as follows:

```ts
await addComponentsDir({
  path: join(dirname(inklineRequire.resolve("@inkline/inkline")), "components"),
  pathPrefix: false,
  pattern: "**/*.vue",
  ignore: ["**/examples/*.vue"],
  transpile: 'auto',
  global: global !== false
});
```

### Additional context

Inkline users have started reporting it since updating to the latest version of Nuxt, here: https://github.com/inkline/inkline/issues/312

The Inkline Nuxt Module source code can be found here: https://github.com/inkline/nuxt-module-inkline

### Logs

```shell
PS C:\Users\alexgrozav\Workspace\my-nuxt-app> npm run dev

> dev
> nuxt dev
Nuxi 3.0.0-rc.11                                                                                              08:03:08
Nuxt 3.0.0-rc.11 with Nitro 0.5.4                                                                             08:03:08
                                                                                                              08:03:11
  > Local:    http://localhost:3000/
  > Network:  http://10.211.55.3:3000/
  > Network:  http://[fdb2:2c26:f4e4:0:116a:7a11:f510:5b55]:3000/
  > Network:  http://[fdb2:2c26:f4e4:0:6dc4:ba75:2fe3:1c3e]:3000/

C:\Users\alexgrozav\Workspace\my-nuxt-app\node_modules\@inkline\inkline\components                            08:03:11

 ERROR  Failed to parse source for import analysis because the content contains invalid JS syntax. You may need to install appropriate plugins to handle the .html?v=148dbd1a file format, or if it's an asset, add "**/*.html?v=148dbd1a" to assetsInclude in your configuration.


 ERROR  Failed to parse source for import analysis because the content contains invalid JS syntax. You may need to install appropriate plugins to handle the .html?v=148dbd1a file format, or if it's an asset, add "**/*.html?v=148dbd1a" to assetsInclude in your configuration.


 ERROR  Failed to parse source for import analysis because the content contains invalid JS syntax. You may need to install appropriate plugins to handle the .html?v=148dbd1a file format, or if it's an asset, add "**/*.html?v=148dbd1a" to assetsInclude in your configuration.


 ERROR  Failed to parse source for import analysis because the content contains invalid JS syntax. You may need to install appropriate plugins to handle the .html?v=148dbd1a file format, or if it's an asset, add "**/*.html?v=148dbd1a" to assetsInclude in your configuration.


 ERROR  Failed to parse source for import analysis because the content contains invalid JS syntax. You may need to install appropriate plugins to handle the .html?v=148dbd1a file format, or if it's an asset, add "**/*.html?v=148dbd1a" to assetsInclude in your configuration.


 ERROR  Failed to parse source for import analysis because the content contains invalid JS syntax. You may need to install appropriate plugins to handle the .html?v=148dbd1a file format, or if it's an asset, add "**/*.html?v=148dbd1a" to assetsInclude in your configuration.

√ Nitro built in 1414 ms                                                                                nitro 08:04:12
i Vite client warmed up in 57618ms                                                                            08:04:17
[Vue warn]: Failed to resolve component: i-input-label
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[Vue warn]: Non-function value encountered for default slot. Prefer function slots for better performance.
[Vue warn]: Component <Anonymous> is missing template or render function.
[Vue warn]: Failed to resolve component: i-input-label
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[Vue warn]: Non-function value encountered for default slot. Prefer function slots for better performance.
[Vue warn]: Component <Anonymous> is missing template or render function.

 ERROR  8:04:25 AM [vite] Internal server error: Failed to parse source for import analysis because the content contains invalid JS syntax. You may need to install appropriate plugins to handle the .html?v=148dbd1a file format, or if it's an asset, add "**/*.html?v=148dbd1a" to assetsInclude in your configuration.
  Plugin: vite:import-analysis
  File: C:/Users/alexgrozav/Workspace/my-nuxt-app/node_modules/@inkline/inkline/components/IInput/template.html?v=148dbd1a
  2  |      <div class="input-prepend" v-if="$slots.prepend">
  3  |          <slot name="prepend" />
  4  |      </div>
     |            ^
  5  |      <div class="input">
  6  |          <span class="input-prefix" v-if="$slots.prefix">
      at formatError (file:///C:/Users/alexgrozav/Workspace/my-nuxt-app/node_modules/vite/dist/node/chunks/dep-557f29e6.js:40853:46)
      at TransformContext.error (file:///C:/Users/alexgrozav/Workspace/my-nuxt-app/node_modules/vite/dist/node/chunks/dep-557f29e6.js:40849:19)
      at TransformContext.transform (file:///C:/Users/alexgrozav/Workspace/my-nuxt-app/node_modules/vite/dist/node/chunks/dep-557f29e6.js:37521:22)
      at async Object.transform (file:///C:/Users/alexgrozav/Workspace/my-nuxt-app/node_modules/vite/dist/node/chunks/dep-557f29e6.js:41102:30)
      at async loadAndTransform (file:///C:/Users/alexgrozav/Workspace/my-nuxt-app/node_modules/vite/dist/node/chunks/dep-557f29e6.js:37364:29)

 ERROR  8:04:25 AM [vite] Internal server error: Failed to parse source for import analysis because the content contains invalid JS syntax. You may need to install appropriate plugins to handle the .html?v=148dbd1a file format, or if it's an asset, add "**/*.html?v=148dbd1a" to assetsInclude in your configuration.
  Plugin: vite:import-analysis
  File: C:/Users/alexgrozav/Workspace/my-nuxt-app/node_modules/@inkline/inkline/components/IForm/components/IFormGroup/template.html?v=148dbd1a
  4  |       role="group">
  5  |      <slot />
  6  |  </fieldset>
     |             ^
  7  |
      at formatError (file:///C:/Users/alexgrozav/Workspace/my-nuxt-app/node_modules/vite/dist/node/chunks/dep-557f29e6.js:40853:46)
      at TransformContext.error (file:///C:/Users/alexgrozav/Workspace/my-nuxt-app/node_modules/vite/dist/node/chunks/dep-557f29e6.js:40849:19)
      at TransformContext.transform (file:///C:/Users/alexgrozav/Workspace/my-nuxt-app/node_modules/vite/dist/node/chunks/dep-557f29e6.js:37521:22)
      at async Object.transform (file:///C:/Users/alexgrozav/Workspace/my-nuxt-app/node_modules/vite/dist/node/chunks/dep-557f29e6.js:41102:30)
      at async loadAndTransform (file:///C:/Users/alexgrozav/Workspace/my-nuxt-app/node_modules/vite/dist/node/chunks/dep-557f29e6.js:37364:29)


 ERROR  8:04:25 AM [vite] Internal server error: Failed to parse source for import analysis because the content contains invalid JS syntax. You may need to install appropriate plugins to handle the .html?v=148dbd1a file format, or if it's an asset, add "**/*.html?v=148dbd1a" to assetsInclude in your configuration.
  Plugin: vite:import-analysis
  File: C:/Users/alexgrozav/Workspace/my-nuxt-app/node_modules/@inkline/inkline/components/IForm/template.html?v=148dbd1a
  8  |  >
  9  |      <slot />
  10 |  </form>
     |         ^
  11 |
      at formatError (file:///C:/Users/alexgrozav/Workspace/my-nuxt-app/node_modules/vite/dist/node/chunks/dep-557f29e6.js:40853:46)
      at TransformContext.error (file:///C:/Users/alexgrozav/Workspace/my-nuxt-app/node_modules/vite/dist/node/chunks/dep-557f29e6.js:40849:19)
      at TransformContext.transform (file:///C:/Users/alexgrozav/Workspace/my-nuxt-app/node_modules/vite/dist/node/chunks/dep-557f29e6.js:37521:22)
      at async Object.transform (file:///C:/Users/alexgrozav/Workspace/my-nuxt-app/node_modules/vite/dist/node/chunks/dep-557f29e6.js:41102:30)
      at async loadAndTransform (file:///C:/Users/alexgrozav/Workspace/my-nuxt-app/node_modules/vite/dist/node/chunks/dep-557f29e6.js:37364:29)

[Vue warn]: Failed to resolve component: i-input-label
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[Vue warn]: Non-function value encountered for default slot. Prefer function slots for better performance.
[Vue warn]: Component <Anonymous> is missing template or render function.
[Vue warn]: Failed to resolve component: i-input-label
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[Vue warn]: Non-function value encountered for default slot. Prefer function slots for better performance.
[Vue warn]: Component <Anonymous> is missing template or render function.
[Vue warn]: Failed to resolve component: i-input-label
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[Vue warn]: Non-function value encountered for default slot. Prefer function slots for better performance.
[Vue warn]: Component <Anonymous> is missing template or render function.

 ERROR  8:04:39 AM [vite] Internal server error: Failed to parse source for import analysis because the content contains invalid JS syntax. You may need to install appropriate plugins to handle the .html?v=148dbd1a file format, or if it's an asset, add "**/*.html?v=148dbd1a" to assetsInclude in your configuration.
  Plugin: vite:import-analysis
  File: C:/Users/alexgrozav/Workspace/my-nuxt-app/node_modules/@inkline/inkline/components/IForm/components/IFormGroup/template.html?v=148dbd1a
  4  |       role="group">
  5  |      <slot />
  6  |  </fieldset>
     |             ^
  7  |
      at formatError (file:///C:/Users/alexgrozav/Workspace/my-nuxt-app/node_modules/vite/dist/node/chunks/dep-557f29e6.js:40853:46)
      at TransformContext.error (file:///C:/Users/alexgrozav/Workspace/my-nuxt-app/node_modules/vite/dist/node/chunks/dep-557f29e6.js:40849:19)
      at TransformContext.transform (file:///C:/Users/alexgrozav/Workspace/my-nuxt-app/node_modules/vite/dist/node/chunks/dep-557f29e6.js:37521:22)
      at async Object.transform (file:///C:/Users/alexgrozav/Workspace/my-nuxt-app/node_modules/vite/dist/node/chunks/dep-557f29e6.js:41102:30)
      at async loadAndTransform (file:///C:/Users/alexgrozav/Workspace/my-nuxt-app/node_modules/vite/dist/node/chunks/dep-557f29e6.js:37364:29)


 ERROR  8:04:39 AM [vite] Internal server error: Failed to parse source for import analysis because the content contains invalid JS syntax. You may need to install appropriate plugins to handle the .html?v=148dbd1a file format, or if it's an asset, add "**/*.html?v=148dbd1a" to assetsInclude in your configuration.
  Plugin: vite:import-analysis
  File: C:/Users/alexgrozav/Workspace/my-nuxt-app/node_modules/@inkline/inkline/components/IForm/template.html?v=148dbd1a
  8  |  >
  9  |      <slot />
  10 |  </form>
     |         ^
  11 |
      at formatError (file:///C:/Users/alexgrozav/Workspace/my-nuxt-app/node_modules/vite/dist/node/chunks/dep-557f29e6.js:40853:46)
      at TransformContext.error (file:///C:/Users/alexgrozav/Workspace/my-nuxt-app/node_modules/vite/dist/node/chunks/dep-557f29e6.js:40849:19)
      at TransformContext.transform (file:///C:/Users/alexgrozav/Workspace/my-nuxt-app/node_modules/vite/dist/node/chunks/dep-557f29e6.js:37521:22)
      at async Object.transform (file:///C:/Users/alexgrozav/Workspace/my-nuxt-app/node_modules/vite/dist/node/chunks/dep-557f29e6.js:41102:30)
      at async loadAndTransform (file:///C:/Users/alexgrozav/Workspace/my-nuxt-app/node_modules/vite/dist/node/chunks/dep-557f29e6.js:37364:29)

[Vue warn]: Failed to resolve component: i-input-label
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[Vue warn]: Non-function value encountered for default slot. Prefer function slots for better performance.
[Vue warn]: Component <Anonymous> is missing template or render function.
[Vue warn]: Failed to resolve component: i-input-label
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[Vue warn]: Non-function value encountered for default slot. Prefer function slots for better performance.
[Vue warn]: Component <Anonymous> is missing template or render function.
[Vue warn]: Failed to resolve component: i-input-label
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[Vue warn]: Non-function value encountered for default slot. Prefer function slots for better performance.
[Vue warn]: Component <Anonymous> is missing template or render function.
```

**Comment by danielroe** [comment]
Looking into this, this is not an issue with Nuxt, but is coming from Vite's import analysis plugin.

Here's a reproduction - https://stackblitz.com/edit/github-kurrn8 - download that on Windows and you should see the same error that you're getting here. I'd suggest raising on https://github.com/vitejs/vite.

**Comment by alexgrozav** [comment]
Thanks a lot for looking into this and providing a stackblitz repro, Daniel. Really appreciate it! 🙌

**Comment by danielroe** [comment]
Not at all - I'm only sorry it wasn't something I could fix internally. All the best with Inkline :blush:
