### ISSUE TITLE
defineProps is not defined

### ISSUE THREAD

**Issue by sdezza** [nuxt/framework#7900]
### Discussed in https://github.com/nuxt/framework/discussions/7899

<div type='discussions-op-text'>

<sup>Originally posted by **sdezza** September 29, 2022</sup>
Hi all,
I have a weird problem and cannot understand why I have this and how to solve this. 
I have a simple component:

**components/UI/Input.vue**

```
<template>
<div>
    <p>{{props.label}}</p>
</div>
</template>

<script script>

defineProps({
    label: {
        type: String,
    }
})

</script>
```

And I'm calling it simply like this:

```
<UIInput label="label here" />
```

Then error in console:
```
[nuxt] [request error] [unhandled] [500] defineProps is not defined
  at $id_c7YOYlNzeD (/C:/Users/sam/Desktop/Code%20snippets/projects/test_project/frontend/.nuxt/dist/server/server.mjs:4570:5)
  at __instantiateModule__ (/C:/Users/sam/Desktop/Code%20snippets/projects/test_project/frontend/.nuxt/dist/server/server.mjs:6672:9)
  at __ssrLoadModule__ (/C:/Users/sam/Desktop/Code%20snippets/projects/test_project/frontend/.nuxt/dist/server/server.mjs:6610:25)
  at ssrImport (/C:/Users/sam/Desktop/Code%20snippets/projects/test_project/frontend/.nuxt/dist/server/server.mjs:6635:13)
  at $id_IkXAF6dJ8C (/C:/Users/sam/Desktop/Code%20snippets/projects/test_project/frontend/.nuxt/dist/server/server.mjs:4524:37)
  at __instantiateModule__ (/C:/Users/sam/Desktop/Code%20snippets/projects/test_project/frontend/.nuxt/dist/server/server.mjs:6672:9)
  at __ssrLoadModule__ (/C:/Users/sam/Desktop/Code%20snippets/projects/test_project/frontend/.nuxt/dist/server/server.mjs:6610:25)
  at ssrImport (/C:/Users/sam/Desktop/Code%20snippets/projects/test_project/frontend/.nuxt/dist/server/server.mjs:6635:13)
  at $id_4iTDKLpejG (/C:/Users/sam/Desktop/Code%20snippets/projects/test_project/frontend/.nuxt/dist/server/server.mjs:2971:38)
  at async __instantiateModule__ (/C:/Users/sam/Desktop/Code%20snippets/projects/test_project/frontend/.nuxt/dist/server/server.mjs:6672:3)
```
Then the server is down:
![image](https://user-images.githubusercontent.com/30461090/192975964-1e663092-c03c-4f63-8348-89a9148d14dc.png)
</div>

**Comment by danielroe** [comment]
Do you mean `<script setup>` instead of `<script script>`?

**Comment by danielroe** [comment]
(Also, you should reference the prop in the template as `label` rather than `props.label` but that doesn't seem to be the issue.)

**Comment by sdezza** [comment]
Yes I mean `<script setup>` and changed to `{{label}}`
I updated, thx

**Comment by sdezza** [comment]
Godammit, time for some rest... It was indeed the `<script setup>` part causing problem....
