### ISSUE TITLE
 Unexpected character '�'  when generating build

### ISSUE THREAD

**Issue by arek125** [nuxt/framework#7923]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.15.0`
- Builder:          `vite`

### Reproduction

I Tried to reproduce but problem looks like problem appears only in local windows 10

https://github.com/arek125/nuxt3-ant-sql

### Describe the bug

Dev runs fine, but when tries to generate build: 

``` ERROR                                                                                                                                                                                          nitro 09:14:51  

1: MZ�♥♦���☺♫▼�♫�       �!�☺L�!This program cannot be run in DOS mode.
     ^
3�H��(H�%ÿ☺3�H��(�������������H�♣!H☻H�☺H�H�H�������������H�H�♣ED☻H��H☼E�����������������������������@SH�� H�♣�G☻H��H�☺��☺txt�☺►�☺♦ `.rdata^��☺��☺@@.datax▼�☻♫�☻@�.pdata�↓�☻→�☻@@.rsrc�☺�☻☻�☻@@.reloc�♠��☻@BH�   
3: �►�ҔH��H�� [������H�☺�������������@SH�� H�Q@H��H��►r-H�I(H��H��►r↑L�A�H��'I+�H�A�H��▼wMI���t�H�C8H�♣IG☻H�C@☼�C(H�♥H�S↑H��t↑�{ u


 ERROR  Unexpected character '�' (Note that you need plugins to import files that are not JavaScript)                                                                                                 09:14:51  

  at error (/C:/Users/agolen/Desktop/nuxt3/nuxt3-ant-sql/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
  at Module.error (/C:/Users/agolen/Desktop/nuxt3/nuxt3-ant-sql/node_modules/rollup/dist/es/shared/rollup.js:12429:16)
  at Module.tryParse (/C:/Users/agolen/Desktop/nuxt3/nuxt3-ant-sql/node_modules/rollup/dist/es/shared/rollup.js:12806:25)
  at Module.setSource (/C:/Users/agolen/Desktop/nuxt3/nuxt3-ant-sql/node_modules/rollup/dist/es/shared/rollup.js:12711:24)
  at ModuleLoader.addModuleSource (/C:/Users/agolen/Desktop/nuxt3/nuxt3-ant-sql/node_modules/rollup/dist/es/shared/rollup.js:21959:20)
```

**Comment by arek125** [comment]
Argon2 is causing the issue, for now i'm switching to bcrypt.

**Comment by jeremycoder** [comment]
Just had the same problem
