### ISSUE TITLE
Issue with imports after production build

### ISSUE THREAD

**Issue by marcodarko** [nuxt/framework#7991]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v17.9.0`
- Nuxt Version:     `3.0.0-rc.10`
- Nitro Version:    `0.5.3`
- Package Manager:  `npm@8.5.5`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Follow installation of tabulator-tables here:
http://tabulator.info/docs/5.4/install#setup-full

Please read the Minimal Reproducible Example guide:
http://tabulator.info/community/mre

build application, and try use app, immediately hit with a 500 error because of this import. 

### Describe the bug

Please note that this is not the only library that had this issue, I had the same exact issue with ChartJS but I was able to use the "recommended" solution to import as a constant then deconstruct.

eg:
```
import pkg from 'tabulator-tables';
const { TabulatorFull } = pkg;
```

This doesn't work tho..

The libraries work perfectly fine during development but after the build I can't get the app to work. And both seem to support ESM imports as indicated on their docs.

Is this a known issue? I can't find a solution to get past this issue.  Help greatly appreciated! 

### Additional context

Code in question: 
https://github.com/biothings/discovery-app/blob/vue3-app/nuxt-app/store/modules/schema_registry.js

### Logs

```shell
[nuxt] [request error] [unhandled] [500] Named export 'TabulatorFull' not found. The requested module 'tabulator-tables' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'tabulator-tables';
const { TabulatorFull } = pkg;

  at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
  at async ./.output/server/chunks/handlers/renderer.mjs:304:24
  at async ./.output/server/chunks/handlers/renderer.mjs:366:64
  at async ./.output/server/chunks/handlers/renderer.mjs:28:22
  at async ./.output/server/node_modules/h3/dist/index.mjs:592:19
  at async Server.nodeHandler (./.output/server/node_modules/h3/dist/index.mjs:538:7)
[nuxt] [request error] [unhandled] [500] Named export 'TabulatorFull' not found. The requested module 'tabulator-tables' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'tabulator-tables';
const { TabulatorFull } = pkg;

  at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
  at async ./.output/server/chunks/handlers/renderer.mjs:304:24
  at async ./.output/server/chunks/handlers/renderer.mjs:366:64
  at async ./.output/server/chunks/handlers/renderer.mjs:28:22
  at async ./.output/server/node_modules/h3/dist/index.mjs:592:19
  at async Server.nodeHandler (./.output/server/node_modules/h3/dist/index.mjs:538:7)
[nuxt] [request error] [unhandled] [500] Named export 'TabulatorFull' not found. The requested module 'tabulator-tables' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'tabulator-tables';
const { TabulatorFull } = pkg;

  at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
  at async ./.output/server/chunks/handlers/renderer.mjs:304:24
  at async ./.output/server/chunks/handlers/renderer.mjs:366:64
  at async ./.output/server/chunks/handlers/renderer.mjs:28:22
  at async ./.output/server/node_modules/h3/dist/index.mjs:592:19
  at async Server.nodeHandler (./.output/server/node_modules/h3/dist/index.mjs:538:7)
```

**Comment by marcodarko** [comment]
I get the same issue with another library (which runs fine in dev mode).
Only run into this issue when trying to run the prod build.

```
[nuxt] [request error] [unhandled] [500] Named export 'Chart' not found. The requested module 'chart.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'chart.js';
const { Chart: Chart$1, registerables } = pkg;

  at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
  at async ./.output/server/chunks/handlers/renderer.mjs:304:24
  at async ./.output/server/chunks/handlers/renderer.mjs:366:64
  at async ./.output/server/chunks/handlers/renderer.mjs:28:22
  at async ./.output/server/node_modules/h3/dist/index.mjs:592:19
  at async Server.nodeHandler (./.output/server/node_modules/h3/dist/index.mjs:538:7)
[nuxt] [request error] [unhandled] [500] Named export 'Chart' not found. The requested module 'chart.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'chart.js';
const { Chart: Chart$1, registerables } = pkg;

  at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
  at async ./.output/server/chunks/handlers/renderer.mjs:304:24
  at async ./.output/server/chunks/handlers/renderer.mjs:366:64
  at async ./.output/server/chunks/handlers/renderer.mjs:28:22
  at async ./.output/server/node_modules/h3/dist/index.mjs:592:19
  at async Server.nodeHandler (./.output/server/node_modules/h3/dist/index.mjs:538:7)
```

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/framework/issues/7206.
