### ISSUE TITLE
not understand, generated work or not?

### ISSUE THREAD

**Issue by n4an** [nuxt/framework#8052]
### Environment

---

### Reproduction

  nitro: {
    prerender: {
      crawlLinks: true,
      routes: ['/'],

### Describe the bug

Pages are generated without content which is fetched (api routes).

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by n4an** [comment]
I try to make minimal reproduction, but now get old error with  nuxt instance unavailable with the same package.json

```
[nitro] [dev] [unhandledRejection] Error: nuxt instance unavailable
    at Module.useNuxtApp (/home/test/node_modules/nuxt/dist/app/nuxt.mjs:142:13)
    at useRouter (/home/test/node_modules/nuxt/dist/app/composables/router.mjs:14:32)
    at Module.navigateTo (/home/test/node_modules/nuxt/dist/app/composables/router.mjs:64:18)
    at Module.navigate (virtual:nuxt:/home/test/.nuxt/i18n.utils.mjs:176:36)
    at __vite_ssr_import_0__.addRouteMiddleware.global (/home/test/node_modules/@nuxtjs/i18n/dist/runtime/plugin.mjs:289:29)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.callAsync (file:///home/test/node_modules/unctx/dist/index.mjs:53:16)
    at async /home/test/node_modules/nuxt/dist/pages/runtime/router.mjs:115:22

``

**Comment by n4an** [comment]
https://github.com/n4an/nuxt-error-7

**Comment by kazupon** [comment]
I've met same issue in nuxtjs/i18n
Reproduction is here:
https://stackblitz.com/edit/github-ih5gur?file=nuxt.config.ts

related issue: https://github.com/nuxt-community/i18n-module/issues/1555

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/framework/issues/6292 - see https://github.com/nuxt/framework/issues/6292#issuecomment-1202185116 for more info. I've raised [an upstream PR](https://github.com/nuxt-community/i18n-module/pull/1558) that I believe resolves the issue experienced in i18n.
