### ISSUE TITLE
ClearNuxtData import error

### ISSUE THREAD

**Issue by agracia-foticos** [nuxt/framework#8153]
### Environment

- Operating System: `Linux`
- Node Version:     `v18.7.0`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.15.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

We are using the clearNuxtData function and it throws us an import error.

With Script Setup lang="ts"
![image](https://user-images.githubusercontent.com/77386602/195523968-ce06337c-da10-414e-bbde-a3e27ed70a4d.png)

Without Script Setup lang="ts"
![image](https://user-images.githubusercontent.com/77386602/195524161-bec2d90c-5796-4a64-aa28-182872345591.png)

how to use clearNuxtData function?
There is any error?

### Describe the bug

We are using the clearNuxtData function and it throws us an import error.

With Script Setup lang="ts"
![image](https://user-images.githubusercontent.com/77386602/195523968-ce06337c-da10-414e-bbde-a3e27ed70a4d.png)

Without Script Setup lang="ts"
![image](https://user-images.githubusercontent.com/77386602/195524161-bec2d90c-5796-4a64-aa28-182872345591.png)

how to use clearNuxtData function?
There is any error?

### Logs

```shell
[nitro] [dev] [unhandledRejection] ReferenceError: clearNuxtData is not defined
    at setup (/home/foticos/var/www/wanapix_next/src/pages/cart.vue:59:2)
    at _sfc_main.setup (/home/foticos/var/www/wanapix_next/src/pages/cart.vue:279:23)
    at callWithErrorHandling (/home/foticos/var/www/wanapix_next/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:157:22)
    at setupStatefulComponent (/home/foticos/var/www/wanapix_next/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7109:29)
    at setupComponent (/home/foticos/var/www/wanapix_next/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7064:11)
    at renderComponentVNode (/home/foticos/var/www/wanapix_next/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:172:17)
    at renderVNode (/home/foticos/var/www/wanapix_next/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:299:22)
    at renderComponentSubTree (/home/foticos/var/www/wanapix_next/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:263:13)
    at renderComponentVNode (/home/foticos/var/www/wanapix_next/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:188:16)
    at renderVNode (/home/foticos/var/www/wanapix_next/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:299:22)
```

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by agracia-foticos** [comment]
I create a "template page"

clearnuxtdata.vue
========
<template>
	<div>
        Hola
	</div>
</template>

<script setup>	
    clearNuxtData()
</script> 

This page throws
![image](https://user-images.githubusercontent.com/77386602/195541634-5ea69ea1-0a4c-4b1b-985b-508bec7ac999.png)

If i use lang="ts"

![image](https://user-images.githubusercontent.com/77386602/195541941-d9c8a168-207c-4b40-b325-b3c43233bb7a.png)

**Comment by agracia-foticos** [comment]
`<template>
	<div>
        Hola
	</div>
</template>

<script setup lang="ts">	
    clearNuxtData()
</script> 
`

**Comment by agracia-foticos** [comment]
The page has this code

![image](https://user-images.githubusercontent.com/77386602/195542310-cf6073d4-232c-432e-b6ce-5e7108f86ff1.png)

**Comment by danielroe** [comment]
Ah, my apologies. This has already been resolved in the edge channel via https://github.com/nuxt/framework/pull/7710 and will be released in RC12 shortly.
