### ISSUE TITLE
`@vueuse/head` nuxt@3.0.0-rc.12 - upstream bug

### ISSUE THREAD

**Issue by cpreston321** [nuxt/framework#8293]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.9.0`
- Nuxt Version:     `3.0.0-rc.12-27768618.05fd222`
- Nitro Version:    `0.6.0-27768582.4603279`
- Package Manager:  `pnpm@7.13.5`
- Builder:          `vite`
- User Config:      `typescript`, `runtimeConfig`, `css`, `pageTransition`, `nitro`, `modules`, `schemaOrg`, `unocss`, `umami`, `content`
- Runtime Modules:  `@nuxt/image-edge@1.0.0-27768165.4b0219a`, `@nuxt/content@2.1.1`, `@vueuse/nuxt@9.3.1`, `@unocss/nuxt@0.45.30`, `@formkit/nuxt@1.0.0-beta.11`, `nuxt-swiper@0.1.6`, `nuxt-umami@1.1.0`, `nuxt-schema-org@1.1.0-beta.5`
- Build Modules:    `-`

### Reproduction

> **Note**
> I will add reproduction but for now I will have to decouple my current project that in private.

In the meantime I will try to re-produce this.

Thanks 

### Describe the bug

Upstream bug: https://github.com/vueuse/head/issues/142

### Logs

```shell
Upstream bug: https://github.com/vueuse/head/issues/142
```

**Comment by bitsnaps** [comment]
I got the error `Unexpected token '||='` on newly created project where v`3.0.0.rc-11` was working fine, full log:
```bash
Nuxi 3.0.0-rc.12                                                                                              22:19:40
Nuxt 3.0.0-rc.12 with Nitro 0.6.0                                                                             22:19:40
                                                                                                              22:19:41
  > Local:    http://localhost:3000/ 
  > Network:  http://192.168.1.2:3000/

ℹ Vite client warmed up in 2312ms                                                                             22:19:45
✔ Nitro built in 1640 ms                                                                                nitro 22:19:46
[nuxt] [request error] [unhandled] [500] Unexpected token '||='
  at new Script (vm.js:102:7)  
  at createScript (vm.js:262:10)  
  at Object.runInThisContext (vm.js:310:10)  
  at ViteNodeRunner.directRequest (./node_modules/.pnpm/vite-node@0.24.3/node_modules/vite-node/dist/client.mjs:246:19)  
  at processTicksAndRejections (internal/process/task_queues.js:95:5)  
  at async ViteNodeRunner.cachedRequest (./node_modules/.pnpm/vite-node@0.24.3/node_modules/vite-node/dist/client.mjs:128:12)  
  at async request (./node_modules/.pnpm/vite-node@0.24.3/node_modules/vite-node/dist/client.mjs:151:16)  
  at async ./node_modules/.pnpm/nuxt@3.0.0-rc.12/node_modules/nuxt/dist/app/composables/index.mjs:46:31  
  at async ViteNodeRunner.directRequest (./node_modules/.pnpm/vite-node@0.24.3/node_modules/vite-node/dist/client.mjs:251:5)  
  at async ViteNodeRunner.cachedRequest (./node_modules/.pnpm/vite-node@0.24.3/node_modules/vite-node/dist/client.mjs:128:12)
```

**Comment by cpreston321** [comment]
@harlan-zw Also I wasn't using `htmlAttr` or `bodyAttr`. I was using `pageTransition` which I saw trying to parse as a boolean.
