### ISSUE TITLE
v3.0.0-rc.12 - Google Firebase functions no longer generated by Nitro

### ISSUE THREAD

**Issue by Sandlens** [nuxt/framework#8301]
### Environment

```
------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `npm@8.5.0`
- Builder:          `vite`
- User Config:      `modules`, `ssr`, `nitro`, `app`
- Runtime Modules:  `@nuxt/content@2.1.1`, `@nuxtjs/tailwindcss@5.3.5`, `@pinia/nuxt@0.4.3`, `@nuxt/image-edge@1.0.0-27719579.87dcdf2`
- Build Modules:    `-`
------------------------------
```

### Reproduction

.

### Describe the bug

I am hosting my Nuxt project on Google Firebase.

Since upgrading to v3.0.0-rc.12, `npx nuxi build` no longer generates a `functions` folder in .output\server, despite setting the preset to Firebase with the following:

```
export default defineNuxtConfig({
  nitro: {
    preset: 'firebase'
  }
})
```

The issue also occurs if using `NITRO_PRESET=firebase npm run build`.

When attempting preview the project locally with `firebase emulators:start`, the following error occurs:

```
i  functions: Watching "C:\Users\<...>\<repo-name>\.output\server" for Cloud Functions...
The system cannot find the path specified.

Error: An unexpected error has occurred.
```

Hence, the project cannot be previewed locally or deployed.

**Comment by bituq** [comment]
The same issue is occurring for me

**Comment by bituq** [comment]
A temporary solution that worked for me is to reinstall the node modules in the `.output/folder` directory:

`cd .output/server && rm -rf node_modules && npm i`

**Comment by Sandlens** [comment]
> A temporary solution that worked for me is to reinstall the node modules in the `.output/folder` directory:
> 
> `cd .output/server && rm -rf node_modules && npm i`

That fixed it for me too. Thanks!

**Comment by Grapdevs** [comment]
> A temporary solution that worked for me is to reinstall the node modules in the `.output/folder` directory:
> 
> `cd .output/server && rm -rf node_modules && npm i`

This solution worked yesterday, but now I am having the same problem. Do you have any suggestions?

**Comment by danielroe** [comment]
@Grapdevs So was this an issue with the firebase library then? Is it resolved now?

**Comment by Sandlens** [comment]
I have to run `cd .output/server && rm -rf node_modules && npm i` after each `npx nuxi build`, so no, this is only a workaround and it is not resolved I believe.

firebase-functions recently upgraded from v3 to v4 which included a number of [breaking changes](https://github.com/firebase/firebase-functions/releases) - I wonder whether this is causing any issues if Nitro is still based on v3?

**Comment by davidstackio** [comment]
Adding a [`predeploy`](https://firebase.google.com/docs/hosting/test-preview-deploy#hooks) script to my `firebase.json` fixed it for me!

```
"hosting": {
    "predeploy": [
      "npm run build && cd .output/server && npm install"
    ],
    ...
```

Just make sure you have a [`nitro.config.ts` file](https://nitro.unjs.io/deploy#changing-the-deployment-preset) in your root directory with this (so you don't need the `NITRO_PRESET=firebase` bit):
```
import { defineNitroConfig } from 'nitropack';

export default defineNitroConfig({
  preset: 'firebase',
});
```

**Comment by danielroe** [comment]
Note, if you are using Nuxt you should configure this in `nuxt.config` - please do not create a `nitro.config.ts` in this case:

```js
export default defineNuxtConfig({
  nitro: {
    preset: 'firebase'
  }
})
```

**Comment by dosstx** [comment]
I tried the above fix and get this error. ANyone know why and how to fix?

```
√ You can deploy this build using npx firebase deploy                                                                                                    nitro 05:58:33
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: undefined@undefined
npm ERR! Found: firebase-functions@3.24.1
npm ERR! node_modules/firebase-functions
npm ERR!   firebase-functions@"3.24.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer firebase-functions@"^4.0.0" from firebase-functions-test@3.0.0
npm ERR! node_modules/firebase-functions-test
npm ERR!   firebase-functions-test@"latest" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\xxx\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users/xxx\AppData\Local\npm-cache\_logs\2022-11-12T11_58_33_971Z-debug-0.log
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm run build && cd .output\server && npm install ENOENT
    at notFoundError (C:\nvm4w\nvm\nvm\v16.18.0\node_modules\firebase-tools\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\nvm4w\nvm\nvm\v16.18.0\node_modules\firebase-tools\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\nvm4w\nvm\nvm\v16.18.0\node_modules\firebase-tools\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess.cp.emit (C:\nvm4w\nvm\nvm\v16.18.0\node_modules\firebase-tools\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:30:37)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12) {
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn npm run build && cd .output\\server && npm install',
  path: 'npm run build && cd .output\\server && npm install',
  spawnargs: []
}

Error: hosting predeploy error: Command terminated with non-zero exit code 1
```

**Comment by jofftiquez** [comment]
If this is inevitable, here's a little bit cleaner way to do the extra step. You can use `postbuild` and `rimraf`

```json
"build": "nuxt build",
"postbuild": "cd .output/server && rimraf node_modules && npm install",
```

**Comment by Sandlens** [comment]
> If this is inevitable, here's a little bit cleaner way to do the extra step. You can use `postbuild` and `rimraf`

This works very well. I prefer it over the `predeploy` workaround because it allows for testing with Firebase emulators before deployment. Thanks!
