### ISSUE TITLE
503 Server Unavailable

### ISSUE THREAD

**Issue by agracia-foticos** [nuxt/framework#8313]
### Environment

- Operating System: `Linux`
- Node Version:     `v18.7.0`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `npm@8.15.0`
- Builder:          `vite`
- User Config:      `srcDir`, `modules`, `compilerOptions`, `vue`, `vite`, `telemetry`, `algolia`, `head`, `auth`, `css`, `build`, `runtimeConfig`
- Runtime Modules:  `genesis-design-system/nuxt`, `@nuxtjs/tailwindcss@5.3.5`, `@nuxtjs/algolia@1.1.4`, `@nuxtjs-alt/auth@2.0.20`, `@nuxtjs/device@3.0.0`, `unplugin-icons/nuxt`, `@pinia/nuxt@0.4.3`, `@nuxtjs/i18n@8.0.0-alpha.3`
- Build Modules:    `-`

### Reproduction

we are crawling our website with screaming frog...

When we have about 1,500 urls tracked, the server crashes and starts throwing 503 errors.

![image](https://user-images.githubusercontent.com/77386602/196644111-09fe56d5-4a39-41c2-947b-c6cf2250299c.png)

And at that moment we try to make a request through the browser and it is already impossible.

You have to stop the server and start it again

![image](https://user-images.githubusercontent.com/77386602/196644330-9caca3e6-ff1b-41a2-82b8-2de54c3a85fe.png)

### Describe the bug

we are crawling our website with screaming frog...

When we have about 1,500 urls tracked, the server crashes and starts throwing 503 errors.

![image](https://user-images.githubusercontent.com/77386602/196644111-09fe56d5-4a39-41c2-947b-c6cf2250299c.png)

And at that moment we try to make a request through the browser and it is already impossible.

You have to stop the server and start it again

![image](https://user-images.githubusercontent.com/77386602/196644330-9caca3e6-ff1b-41a2-82b8-2de54c3a85fe.png)

### Logs

```shell
Error: socket hang up
    at connResetException (node:internal/errors:704:14)
    at Socket.socketOnEnd (node:_http_client:505:23)
    at Socket.emit (node:events:525:35)
    at Socket.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by agracia-foticos** [comment]
![image](https://user-images.githubusercontent.com/77386602/196697949-ce62959b-3453-4184-b323-909bc6a2c699.png)

before throwing the 503 errors, we see a 404 with the error "cannot find any route matching"

I don't know if you have a little more info

**Comment by agracia-foticos** [comment]
nuxt_app@ /home/var/www/nuxt_app
├── @adyen/adyen-web@5.28.1
├── @headlessui/vue@1.7.3
├── @iconify-json/fa6-brands@1.1.6
├── @iconify-json/fa6-solid@1.1.7
├── @intlify/nuxt3@0.2.4
├── @mapbox/mapbox-gl-geocoder@5.0.1
├── @nuxt/postcss8@1.1.3
├── @nuxtjs-alt/auth@2.0.20
├── @nuxtjs/algolia@1.1.4
├── @nuxtjs/auth-next@5.0.0-1648802546.c9880dc
├── @nuxtjs/device@3.0.0 (git+ssh://git@github.com/Redemption198/device-module.git#2136ea04d9b1281a1d14d1c91ed40641106bbfaf)
├── @nuxtjs/i18n@8.0.0-alpha.3
├── @nuxtjs/tailwindcss@5.3.5
├── @pinia/nuxt@0.4.3
├── @splidejs/vue-splide@0.6.12
├── @studiometa/vue-mapbox-gl@2.0.1
├── @tailwindcss/typography@0.5.7
├── autoprefixer@10.4.12
├── chart.js@3.9.1
├─┬ project-design-system@0.1.0 -> ./../project-design-system
│ ├── @babel/core@7.18.10
│ ├── @babel/eslint-parser@7.18.9
│ ├── @headlessui/vue@1.6.7
│ ├── @heroicons/vue@1.0.6
│ ├── @mdx-js/react@2.1.2
│ ├── @nuxt/kit@3.0.0-rc.7
│ ├── @storybook/addon-actions@6.5.10
│ ├── @storybook/addon-docs@6.5.10
│ ├── @storybook/addon-essentials@6.5.10
│ ├── @storybook/addon-interactions@6.5.10
│ ├── @storybook/addon-links@6.5.10
│ ├── @storybook/addon-postcss@2.0.0
│ ├── @storybook/builder-webpack5@6.5.10
│ ├── @storybook/manager-webpack5@6.5.10
│ ├── @storybook/testing-library@0.0.11
│ ├── @storybook/vue3@6.5.10
│ ├── @tailwindcss/forms@0.5.2
│ ├── @tailwindcss/typography@0.5.4
│ ├── @vue/cli-plugin-babel@5.0.8
│ ├── @vue/cli-plugin-eslint@5.0.8
│ ├── @vue/cli-service@5.0.8
│ ├── autoprefixer@10.4.8
│ ├── babel-loader@8.2.5
│ ├── core-js@3.24.1
│ ├── eslint-plugin-vue@8.7.1
│ ├── eslint@7.32.0
│ ├── postcss-cli@9.1.0
│ ├── postcss-copy@7.1.0
│ ├── postcss-import@14.1.0
│ ├── postcss-important@0.3.0
│ ├── postcss-nested@5.0.6
│ ├── postcss@8.4.16
│ ├── tailwindcss@3.1.8
│ ├── vue-loader@16.8.3
│ └── vue@3.2.37
├── mapbox-gl@2.10.0
├── npx@10.2.2
├── nuxt@3.0.0-rc.12
├── pinia@2.0.23
├── postcss@8.4.18
├── redis@4.3.1
├── unplugin-icons@0.14.12
├── vue-chart-3@3.1.8
├── vue-tel-input@6.0.5
├── vue@3.2.41
└── vue3-carousel@0.1.48

**Comment by danielroe** [comment]
Yes, there was a nasty bug fixed in 3.2.39 that would exhibit this behaviour (crash subsequent requests if one error was emitted). Try upgrading your project-design-system vue version and see if that resolves the issue for you.

**Comment by agracia-foticos** [comment]
I update project-design-system

nuxt-app@ /home/business/var/www/nuxt-app
├── @adyen/adyen-web@5.28.1
├── @headlessui/vue@1.7.3
├── @iconify-json/fa6-brands@1.1.6
├── @iconify-json/fa6-solid@1.1.7
├── @intlify/nuxt3@0.2.4
├── @mapbox/mapbox-gl-geocoder@5.0.1
├── @nuxt/postcss8@1.1.3
├── @nuxtjs-alt/auth@2.0.20
├── @nuxtjs/algolia@1.1.4
├── @nuxtjs/auth-next@5.0.0-1648802546.c9880dc
├── @nuxtjs/device@3.0.0 (git+ssh://git@github.com/Redemption198/device-module.git#2136ea04d9b1281a1d14d1c91ed40641106bbfaf)
├── @nuxtjs/i18n@8.0.0-alpha.3
├── @nuxtjs/tailwindcss@5.3.5
├── @pinia/nuxt@0.4.3
├── @splidejs/vue-splide@0.6.12
├── @studiometa/vue-mapbox-gl@2.0.1
├── @tailwindcss/typography@0.5.7
├── autoprefixer@10.4.12
├── chart.js@3.9.1
├─┬ project-design-system@0.1.0 -> ./../project-design-system
│ ├── @babel/core@7.19.3
│ ├── @babel/eslint-parser@7.19.1
│ ├── @headlessui/vue@1.7.3
│ ├── @heroicons/vue@1.0.6
│ ├── @mdx-js/react@2.1.5
│ ├── @nuxt/kit@3.0.0-rc.12
│ ├── @storybook/addon-actions@6.5.12
│ ├── @storybook/addon-docs@6.5.12
│ ├── @storybook/addon-essentials@6.5.12
│ ├── @storybook/addon-interactions@6.5.12
│ ├── @storybook/addon-links@6.5.12
│ ├── @storybook/addon-postcss@2.0.0
│ ├── @storybook/builder-webpack5@6.5.12
│ ├── @storybook/manager-webpack5@6.5.12
│ ├── @storybook/testing-library@0.0.11
│ ├── @storybook/vue3@6.5.12
│ ├── @tailwindcss/forms@0.5.3
│ ├── @tailwindcss/typography@0.5.7
│ ├── @vue/cli-plugin-babel@5.0.8
│ ├── @vue/cli-plugin-eslint@5.0.8
│ ├── @vue/cli-service@5.0.8
│ ├── autoprefixer@10.4.12
│ ├── babel-loader@8.2.5
│ ├── core-js@3.25.5
│ ├── eslint-plugin-vue@8.7.1
│ ├── eslint@7.32.0
│ ├── postcss-cli@9.1.0
│ ├── postcss-copy@7.1.0
│ ├── postcss-import@14.1.0
│ ├── postcss-important@0.3.0
│ ├── postcss-nested@5.0.6
│ ├── postcss@8.4.18
│ ├── tailwindcss@3.1.8
│ ├── vue-loader@16.8.3
│ └── vue@3.2.41
├── mapbox-gl@2.10.0
├── npx@10.2.2
├── nuxt@3.0.0-rc.12
├── pinia@2.0.23
├── postcss@8.4.18
├── redis@4.3.1
├── unplugin-icons@0.14.12
├── vue-chart-3@3.1.8
├── vue-tel-input@6.0.5
├── vue@3.2.41
└── vue3-carousel@0.1.48


Same error,

![image](https://user-images.githubusercontent.com/77386602/196705796-6168421b-4846-4c73-953c-e5cde8dfa4d3.png)

![image](https://user-images.githubusercontent.com/77386602/196705852-7165ba7c-57bd-43f9-8694-d2e2416916d0.png)

**Comment by danielroe** [comment]
A reproduction would be really the best way to go to help me investigate.

Can you trigger it yourself by fetching a 404 route and then trying to fetch another one? ie. not related to bulk requests?

**Comment by agracia-foticos** [comment]
When I load a url that does not exist, it throws me a 404 (correct behavior) but the same thing happens to me as in this incident

https://github.com/nuxt/framework/issues/3623

Me arroja errores 
[nitro] [dev] [unhandledRejection] Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:393:5)
    at ServerResponse.setHeader (node:_http_outgoing:644:11)
    at Object.errorhandler [as onError] (file:///home/foticos/var/www/wanapix_next/.nuxt/dev/index.mjs:441:13)
    at async Server.toNodeHandle (file:///home/foticos/var/www/wanapix_next/node_modules/h3/dist/index.mjs:637:9) {
  code: 'ERR_HTTP_HEADERS_SENT'
}

And go into an infinite loop

I can't exactly reproduce the error without making bulk requests through a crawler

**Comment by danielroe** [comment]
Even a reproduction that requires bulk requests would be fine 😊

**Comment by agracia-foticos** [comment]
Another error launching crawler
![image](https://user-images.githubusercontent.com/77386602/196961939-11f0962a-bc7f-4ba7-ad2d-d6376fd3e055.png)

**Comment by agracia-foticos** [comment]
Related with https://github.com/nuxt/framework/issues/8414 ?????

**Comment by amihhs** [comment]
some issue
![0ea06b91d31b063c07a4a6d86f4fda8](https://user-images.githubusercontent.com/59364234/199645126-1804f207-3b74-427a-a896-538290c48889.jpg)

[nitro\src\dev\server.ts](https://github.com/unjs/nitro/blob/ce7cc73f2d951c1cc2f70a6c10badf22013dc004/src/dev/server.ts#L138)
![image](https://user-images.githubusercontent.com/59364234/199645112-33b4023f-7128-453b-a550-d06a4537cc37.png)

I found that it was caused by the return of false by existsSync (address.socketPath)

**Comment by ae86jung** [comment]
> same issue ![0ea06b91d31b063c07a4a6d86f4fda8](https://user-images.githubusercontent.com/59364234/199645126-1804f207-3b74-427a-a896-538290c48889.jpg)
> 
> [nitro\src\dev\server.ts](https://github.com/unjs/nitro/blob/ce7cc73f2d951c1cc2f70a6c10badf22013dc004/src/dev/server.ts#L138) ![image](https://user-images.githubusercontent.com/59364234/199645112-33b4023f-7128-453b-a550-d06a4537cc37.png)
> 
> I found that it was caused by the return of false by existsSync (address.socketPath)

How to fix this? I have the same problem.

**Comment by agracia-foticos** [comment]
continue to fail

**Comment by amihhs** [comment]
hi @ae86jung  , for me,I sent him return void instead of errrorHandle. So that api can work properly.(Everything is fine at the moment)
