### ISSUE TITLE
FATAL ERROR: v8::FromJust Maybe value is Nothing.

### ISSUE THREAD

**Issue by nevadavid** [nuxt/framework#837]
### Environment

- Operating System: `Linux`
- Node Version:     `v14.18.1`
- Nuxt Version:     `3-3.0.0-27234368.47ea41d`
- Package Manager:  `Yarn`
- Bundler:          `Webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Steps to reproduce

1. Install a fresh Nuxt 3
2. Delete app.vue
3. Run `yarn dev -o`
4. Create ./pages directory
5. See error

```
ℹ Directory pages/ created. Restarting nuxt...                                                                     21:24:20
FATAL ERROR: v8::FromJust Maybe value is Nothing.
 1: 0xa389b0 node::Abort() [/usr/local/bin/node]
 2: 0x96e0af node::FatalError(char const*, char const*) [/usr/local/bin/node]
 3: 0xbb773a v8::Utils::ReportApiFailure(char const*, char const*) [/usr/local/bin/node]
 4: 0xa3c19d node::fs::FileHandle::CloseReq::Resolve() [/usr/local/bin/node]
 5: 0xa3c2f9  [/usr/local/bin/node]
 6: 0x13b992d  [/usr/local/bin/node]
 7: 0x13be0b6  [/usr/local/bin/node]
 8: 0x13d0524  [/usr/local/bin/node]
 9: 0x13be9e8 uv_run [/usr/local/bin/node]
10: 0xafab43 node::worker::Worker::Run() [/usr/local/bin/node]
11: 0xafb5f8  [/usr/local/bin/node]
12: 0x7f176d5e5609  [/lib/x86_64-linux-gnu/libpthread.so.0]
13: 0x7f176d50c293 clone [/lib/x86_64-linux-gnu/libc.so.6]
Aborted (core dumped)
error Command failed with exit code 134.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Expected behaviour
Restart Nuxt without error.

**Comment by nevadavid** [comment]
It is still running, but I got some new error:

```
ℹ Directory pages/ created. Restarting nuxt...                                                                     06:55:07

 WARN  [worker] exited with code: 1                                                                                06:55:07

  at Worker.<anonymous> (node_modules/@nuxt/nitro/dist/index.mjs:1694:18)
  at Object.onceWrapper (events.js:520:26)
  at Worker.emit (events.js:412:35)
  at Worker.emit (domain.js:475:12)
  at Worker.[kOnExit] (internal/worker.js:278:10)
  at Worker.<computed>.onexit (internal/worker.js:203:20)
```

**Comment by productdevbook** [comment]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27293390.a149225`
- Package Manager:  `yarn@1.22.15`
- Bundler:          `Vite`
- User Config:      `server`, `head`, `buildModules`, `build`, `unocss`
- Runtime Modules:  `-`
- Build Modules:    `@unocss/nuxt@0.12.1`, `@vueuse/core/nuxt@7.0.0`, `@pinia/nuxt@0.1.5`
------------------------------
### Logs

```shell
FATAL ERROR: v8::FromJust Maybe value is Nothing.
 1: 0x10d83c0e5 node::Abort() [/usr/local/bin/node]
 2: 0x10d83c268 node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 3: 0x10d9b45a0 v8::V8::FromJustIsNothing() [/usr/local/bin/node]
 4: 0x10d83f614 node::fs::FileHandle::CloseReq::Resolve() [/usr/local/bin/node]
 5: 0x10d8541e8 node::fs::FileHandle::ClosePromise()::$_0::__invoke(uv_fs_s*) [/usr/local/bin/node]
 6: 0x10e1e6828 uv__work_done [/usr/local/bin/node]
 7: 0x10e1eac6b uv__async_io [/usr/local/bin/node]
 8: 0x10e1fe37c uv__io_poll [/usr/local/bin/node]
 9: 0x10e1eb161 uv_run [/usr/local/bin/node]
10: 0x10d777f8f node::SpinEventLoop(node::Environment*) [/usr/local/bin/node]
11: 0x10d8df3ef node::worker::Worker::Run() [/usr/local/bin/node]
12: 0x10d8e2c22 node::worker::Worker::StartThread(v8::FunctionCallbackInfo<v8::Value> const&)::$_3::__invoke(void*) [/usr/local/bin/node]
13: 0x7ff80922f514 _pthread_start [/usr/lib/system/libsystem_pthread.dylib]
14: 0x7ff80922b02f thread_start [/usr/lib/system/libsystem_pthread.dylib]
```

**Comment by Tahul** [comment]
@nevadavid ; @bambo0cha ; @productdevbook ;

Do you guys have an idea on how to replicate this issue in a sandboxed environment ?

And how to get it 100% of the time ?

I think it would help @danielroe and @pi0 debugging this.

I tried to replicate it in my own contexts, but I fail getting a reproduction that hits this bug every time in the same place.

**Comment by nevadavid** [comment]
@Tahul I tried to replicate nowadays, but I didn't get this fatal error again. I think this issue may be closed.

**Comment by qnp** [comment]
Hello,
in a somehow consistent project, we encounter a similar issue. Sometimes it happens just right after starting the dev server !
```
FATAL ERROR: v8::FromJust Maybe value is Nothing.
 1: 0x103301a25 node::Abort() (.cold.1) [~/.nvm/versions/node/v16.14.0/bin/node]
 2: 0x101ff70f9 node::Abort() [~/.nvm/versions/node/v16.14.0/bin/node]
 3: 0x101ff726f node::OnFatalError(char const*, char const*) [~/.nvm/versions/node/v16.14.0/bin/node]
 4: 0x10217a510 v8::V8::FromJustIsNothing() [~/.nvm/versions/node/v16.14.0/bin/node]
 5: 0x101ffa6a4 node::fs::FileHandle::CloseReq::Resolve() [~/.nvm/versions/node/v16.14.0/bin/node]
 6: 0x10200fa88 node::fs::FileHandle::ClosePromise()::$_0::__invoke(uv_fs_s*) [~/.nvm/versions/node/v16.14.0/bin/node]
 7: 0x1029c1e18 uv__work_done [~/.nvm/versions/node/v16.14.0/bin/node]
 8: 0x1029c6fdb uv__async_io [~/.nvm/versions/node/v16.14.0/bin/node]
 9: 0x1029dadcb uv__io_poll [~/.nvm/versions/node/v16.14.0/bin/node]
10: 0x1029c7561 uv_run [~/.nvm/versions/node/v16.14.0/bin/node]
11: 0x101f27f9f node::SpinEventLoop(node::Environment*) [~/.nvm/versions/node/v16.14.0/bin/node]
12: 0x10209f06e node::worker::Worker::Run() [~/.nvm/versions/node/v16.14.0/bin/node]
13: 0x1020a2a62 node::worker::Worker::StartThread(v8::FunctionCallbackInfo<v8::Value> const&)::$_3::__invoke(void*) [~/.nvm/versions/node/v16.14.0/bin/node]
14: 0x7fff5d7352eb _pthread_body [/usr/lib/system/libsystem_pthread.dylib]
15: 0x7fff5d738249 _pthread_start [/usr/lib/system/libsystem_pthread.dylib]
16: 0x7fff5d73440d thread_start [/usr/lib/system/libsystem_pthread.dylib]
error Command failed with signal "SIGABRT".
```

Nuxt3 v3.0.0-27420403.16e2a54
Issue observed on MacOS
I cannot get a minimal reproduction...

**Comment by nrifki** [comment]
Hey @Tahul I still get this error with Nuxt Bridge. The server and client-side are compiled successfully but crash as soon as Nuxt starts.

```
FATAL ERROR: v8::FromJust Maybe value is Nothing.
 1: 0x101306bb5 node::Abort() (.cold.1) [/Users/nada/.nvm/versions/node/v14.17.6/bin/node]
 2: 0x1000ad6c9 node::Abort() [/Users/nada/.nvm/versions/node/v14.17.6/bin/node]
 3: 0x1000ad82f node::OnFatalError(char const*, char const*) [/Users/nada/.nvm/versions/node/v14.17.6/bin/node]
```

Our codebase is quite large but we are using Node `v14.17.6` and we followed the guideline from the documentation.

**Comment by kevinmarrec** [comment]
@danielroe 

Here's the minimal reproduction I got for this issue :
https://github.com/kevinmarrec/nuxt-maybe-value-repro

**Comment by pi0** [comment]
Thanks, @kevinmarrec for making smaller repro I will also try it. However by _minimal_, we need a repro without dependency on any nuxt module (yours is using content v2 which likely makes it more complicated to find a root cause)

**Comment by kevinmarrec** [comment]
@pi0 Yup, but `node` crashes due to an action performed by the module (it sounds to be related to its `storage` logic)

**Comment by Atinux** [comment]
Investigating at this issue, I found it reproductible when saving the plugin **and** having the http://localhost:3000 running with the WS to vite running.

The error happens right after the `full-reload` socket sent:
<img width="1728" alt="Screenshot 2022-03-29 at 18 59 51@2x" src="https://user-images.githubusercontent.com/904724/160666123-1299a45d-0ddd-428b-a5bc-abf335d314b2.png">

This one is actually reloading the page with `location.reload()`:

https://github.com/vitejs/vite/blob/f05a81387b6901622c86c2833f42420b8e18e95e/packages/vite/src/client/client.ts#L119

My current assumption is that the browser reload is hitting too early a worker that is handling a request by Nuxt Content v2 (which is using memory for querying based on `unstorage`) while this worker is being killed.

**Comment by Atinux** [comment]
Alright, made a reproduction without `@nuxt/content` v2: https://github.com/Atinux/nuxt-maybe-value-repro

You will need to save faster and more times the `~/plugins/foo.ts` because I did not add any parsing logic in it, but basically it is related to memory usage.

**Comment by Atinux** [comment]
Let's see once #3956 is merged first 😊

**Comment by Tahul** [comment]
I investigated again yesterday, and can give few clues I gathered:

It seem to happen after this is called:
https://github.com/nuxt/framework/blob/main/packages/nitro/src/server/dev.ts#L48

Here:
https://github.com/nuxt/framework/blob/main/packages/nitro/src/server/dev.ts#L70

One other strange thing is it will not happen if you did not opened your browser to access the page.

As seen here:
https://user-images.githubusercontent.com/1385263/160849988-c2b9a134-a3a8-46bf-9bf9-49e3b67e3e87.mp4

I think this might be related to something going on inside the worker while it gets terminated.

Maybe some actions related to filesystem that are either reading/writing while the process gets killed?

That would also (maybe) explain why this is more frequent when using nuxt/content v2.

As things gets parsed on-demand there, this might be related to that.

Of course, these are only theories.

The fact that it only happens after the browser has been opened could also make it related to Vite, or the socket server between client/browser.

**Comment by dsvgl** [comment]
Just came across this. Deleting the `.nuxt` folder fixed it for me!

**Comment by crstnmac** [comment]
I tried downgrading the nuxt package still the same issue
Node: 16.13.1
```√ Nitro built in 620 ms
√ Vite server built in 2345ms
FATAL ERROR: v8::FromJust Maybe value is Nothing.
 1: 00007FF6F6D030AF v8::internal::CodeObjectRegistry::~CodeObjectRegistry+112511
 2: 00007FF6F6C92216 DSA_meth_get_flags+65542
 3: 00007FF6F6C930CD node::OnFatalError+301
 4: 00007FF6F75AF4C5 v8::V8::FromJustIsNothing+53
 5: 00007FF6F6C7B203 v8::base::CPU::has_sse+31491
 6: 00007FF6F6D65BF7 uv_timer_stop+1207
 7: 00007FF6F6D621CB uv_async_send+331
 8: 00007FF6F6D6195C uv_loop_init+1292
 9: 00007FF6F6D61AFA uv_run+202
10: 00007FF6F6D30C05 node::SpinEventLoop+309
11: 00007FF6F6BCB4D0 v8::internal::wasm::SignatureMap::Freeze+35776
12: 00007FF6F6BC6B28 v8::internal::wasm::SignatureMap::Freeze+16920
13: 00007FF6F6D522DD uv_poll_stop+557
14: 00007FF6F7B63DF0 v8::internal::compiler::RepresentationChanger::Uint32OverflowOperatorFor+146416
15: 00007FFD4B55244D BaseThreadInitThunk+29
16: 00007FFD4CA8DF88 RtlUserThreadStart+40
error Command failed with exit code 134.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by qin-guan** [comment]
This seems to happen reliably for Webstorm on save but only sometimes in Visual Studio Code

**Comment by Aleksandr-Baranchuk** [comment]
Operating System: Ubuntu 21.04
Node Version: v16.16.0
Nuxt Version: 3.0.0-rc.6
Package Manager: Yarn

`FATAL ERROR: v8::FromJust Maybe value is Nothing.
 1: 0xb0a860 node::Abort() [/home/developer/.nvm/versions/node/v16.16.0/bin/node]
 2: 0xa1c193 node::FatalError(char const*, char const*) [/home/developer/.nvm/versions/node/v16.16.0/bin/node]
 3: 0xcf97aa v8::Utils::ReportApiFailure(char const*, char const*) [/home/developer/.nvm/versions/node/v16.16.0/bin/node]
 4: 0xb0e6cd node::fs::FileHandle::CloseReq::Resolve() [/home/developer/.nvm/versions/node/v16.16.0/bin/node]
 5: 0xb0e829  [/home/developer/.nvm/versions/node/v16.16.0/bin/node]
 6: 0x1560e0d  [/home/developer/.nvm/versions/node/v16.16.0/bin/node]
 7: 0x15655e6  [/home/developer/.nvm/versions/node/v16.16.0/bin/node]
 8: 0x1577d14  [/home/developer/.nvm/versions/node/v16.16.0/bin/node]
 9: 0x1565f38 uv_run [/home/developer/.nvm/versions/node/v16.16.0/bin/node]
10: 0xa43dd5 node::SpinEventLoop(node::Environment*) [/home/developer/.nvm/versions/node/v16.16.0/bin/node]
11: 0xbd43e2 node::worker::Worker::Run() [/home/developer/.nvm/versions/node/v16.16.0/bin/node]
12: 0xbd4b78  [/home/developer/.nvm/versions/node/v16.16.0/bin/node]
13: 0x7f3074ce1450  [/lib/x86_64-linux-gnu/libpthread.so.0]
14: 0x7f3074c01d53 clone [/lib/x86_64-linux-gnu/libc.so.6]
Aborted (core dumped)
error Command failed with exit code 134.
`

**Comment by attevaltojarvi** [comment]
This also happens to me constantly. The traceback is similar to others' posts:

```
FATAL ERROR: v8::FromJust Maybe value is Nothing.
 1: 0xb09c10 node::Abort() [/home/atte/.nvm/versions/node/v16.15.0/bin/node]
 2: 0xa1c193 node::FatalError(char const*, char const*) [/home/atte/.nvm/versions/node/v16.15.0/bin/node]
 3: 0xcf8afa v8::Utils::ReportApiFailure(char const*, char const*) [/home/atte/.nvm/versions/node/v16.15.0/bin/node]
 4: 0xb0da7d node::fs::FileHandle::CloseReq::Resolve() [/home/atte/.nvm/versions/node/v16.15.0/bin/node]
 5: 0xb0dbd9  [/home/atte/.nvm/versions/node/v16.15.0/bin/node]
 6: 0x156015d  [/home/atte/.nvm/versions/node/v16.15.0/bin/node]
 7: 0x1564936  [/home/atte/.nvm/versions/node/v16.15.0/bin/node]
 8: 0x1577064  [/home/atte/.nvm/versions/node/v16.15.0/bin/node]
 9: 0x1565288 uv_run [/home/atte/.nvm/versions/node/v16.15.0/bin/node]
10: 0xa43dd5 node::SpinEventLoop(node::Environment*) [/home/atte/.nvm/versions/node/v16.15.0/bin/node]
11: 0xbd3792 node::worker::Worker::Run() [/home/atte/.nvm/versions/node/v16.15.0/bin/node]
12: 0xbd3f28  [/home/atte/.nvm/versions/node/v16.15.0/bin/node]
13: 0x7f4da508c54d  [/usr/lib/libc.so.6]
14: 0x7f4da5111874 clone [/usr/lib/libc.so.6]
error Command failed with signal "SIGABRT".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This happens almost constantly when doing work inside my `composables` folder. Modifying stuff inside `components` doesn't seem to cause this. I have only TS files in composables folder. Some call `useRuntimeConfig`, some not.

**Comment by codeinfo** [comment]
OS：windows
Node： 16.15.1
Nuxt: 3.0.0-rc.6
Package manager: Yarn

refresh sometimes
`
FATAL ERROR: v8::FromJust Maybe value is Nothing.
 1: 00007FF607B779CF v8::internal::CodeObjectRegistry::~CodeObjectRegistry+114207
 2: 00007FF607B06096 DSA_meth_get_flags+65542
 3: 00007FF607B06F4D node::OnFatalError+301
 4: 00007FF608425BF5 v8::V8::FromJustIsNothing+53
 5: 00007FF607AEF083 v8::base::CPU::has_sse+31507
 6: 00007FF607BDA947 uv_timer_stop+1207
 7: 00007FF607BD6EDB uv_async_send+331
 8: 00007FF607BD666C uv_loop_init+1292
 9: 00007FF607BD680A uv_run+202
10: 00007FF607BA5675 node::SpinEventLoop+309
11: 00007FF607A3E6F0 v8::internal::interpreter::BytecodeLabel::bind+35712
12: 00007FF607A39D48 v8::internal::interpreter::BytecodeLabel::bind+16856
13: 00007FF607BC6EDD uv_poll_stop+557
14: 00007FF6089E0120 v8::internal::compiler::RepresentationChanger::Uint32OverflowOperatorFor+146416
15: 00007FF8AF727034 BaseThreadInitThunk+20
16: 00007FF8B1702651 RtlUserThreadStart+33
error Command failed with exit code 134.
`

**Comment by Vincebe** [comment]
Getting this Node ESM cache error very frequently.  Very painful...
Any workaround?

**Comment by Atinux** [comment]
Could you try with this option in your `nuxt.config`: 

```ts
experimental: {
  viteNode: true
}
```

**Comment by Vincebe** [comment]
I get h3 errors related to content v2 after enabling vite-node.
Probably (unrelated) errors in my code.

**Comment by OmgImAlexis** [comment]
Tracking this in https://github.com/nodejs/node/issues/6899

**Comment by danielroe** [comment]
Yes, that's very helpful, thanks for the link and some causes of this.

Haven't updated this in a while but this error is a node bug and almost always conceals an underlying error/issue. So it is not necessarily attributable to an issue in Nuxt or indeed any _one_ issue at all.
