### ISSUE TITLE
Property "$t" was accessed during render but is not defined on instance

### ISSUE THREAD

**Issue by agracia-foticos** [nuxt/framework#8494]
### Environment

Nuxt project info:                                                                                                 10:20:13

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.18.0`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `srcDir`, `modules`, `compilerOptions`, `vue`, `vite`, `telemetry`, `algolia`, `head`, `auth`, `css`, `build`, `runtimeConfig`
- Runtime Modules:  `genesis-design-system/nuxt`, `@nuxtjs/tailwindcss@5.3.5`, `@nuxtjs/algolia@1.1.4`, `@nuxtjs-alt/auth@2.0.20`, `@nuxtjs/device@3.0.0`, `unplugin-icons/nuxt`, `@pinia/nuxt@0.4.3`, `@nuxtjs/i18n@8.0.0-alpha.3`
- Build Modules:    `-`
------------------------------

### Reproduction

I am doing a crawl of the website and randomly it is throwing me this error in the server logs

[Vue warn]: Property "$t" was accessed during render but is not defined on instance.
[nitro] [dev] [unhandledRejection] TypeError: _ctx.$t is not a function
    at _sfc_ssrRender (/var/www/_next/src/pages/t/[slug].vue:152:239)
    at renderComponentSubTree (/var/www/_next/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:254:17)
    at /var/www/_next/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:185:29
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

### Describe the bug

I am doing a crawl of the website and randomly it is throwing me this error in the server logs

[Vue warn]: Property "$t" was accessed during render but is not defined on instance.
[nitro] [dev] [unhandledRejection] TypeError: _ctx.$t is not a function
    at _sfc_ssrRender (/var/www/_next/src/pages/t/[slug].vue:152:239)
    at renderComponentSubTree (/var/www/_next/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:254:17)
    at /var/www/_next/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:185:29
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

### Logs

```shell
[Vue warn]: Property "$t" was accessed during render but is not defined on instance.
[nitro] [dev] [unhandledRejection] TypeError: _ctx.$t is not a function
    at _sfc_ssrRender (/var/www/_next/src/pages/t/[slug].vue:152:239)
    at renderComponentSubTree (/var/www/_next/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:254:17)
    at /var/www/_next/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:185:29
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by agracia-foticos** [comment]
I'm browsing manually and I can't reproduce the error.

The error is reproduced when, with a crawling tool, I crawl the web. Then randomly those errors occur

**Comment by kazupon** [comment]
I think this issue is @nuxtjs/i18n or vue-i18n
If you can reproduce this issue, you should open the issue to these repos.
