### ISSUE TITLE
nuxt-i18n throw error: node_modules/nuxt-i18n/src/templates/head-meta.js',   fileName: 'nuxt-i18n/head-meta.js',

### ISSUE THREAD

**Issue by khunemz** [nuxt/framework#8542]
package.json
```javascript
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare",
    "lint": "eslint . --ext .js,.ts,.vue",
    "lint:fix": "yarn run lint -- --fix",
    "format": "yarn prettier --write ./",
    "format:fix": "yarn prettier --write ./",
    "prepare": "husky install",
    "test": "yarn vitest"
  },
  "devDependencies": {
    "@nuxt/postcss8": "^1.1.3",
    "@pinia/nuxt": "^0.4.3",
    "@vueuse/nuxt": "^9.4.0",
    "autoprefixer": "^10.4.12",
    "axios": "^1.1.3",
    "eslint": "^8.26.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-nuxt": "^4.0.0",
    "eslint-plugin-prettier": "^4.2.1",
    "husky": "^8.0.1",
    "msw": "^0.47.4",
    "nuxt": "3.0.0-rc.12",
    "postcss": "^8.4.18",
    "prettier": "2.7.1",
    "sass": "^1.55.0",
    "tailwindcss": "^3.2.1",
    "vitest": "^0.24.3"
  },
  "dependencies": {
    "lodash": "^4.17.21",
    "nuxt-i18n": "^6.28.1",
    "pinia": "^2.0.23"
  },
  "lint-staged": {
    "*.{js,vue,ts}": [
      "yarn lint"
    ]
  }
}
```

nuxt.config.js
```javascript
// https://v3.nuxtjs.org/api/configuration/nuxt.config

export default defineNuxtConfig({
  modules: ['@vueuse/nuxt', '@pinia/nuxt','nuxt-i18n'],
  vueuse: {
    ssrHandlers: true,
  },
  i18n: {
    locales: [
      {
        code: 'en',
        iso: 'en-US',
        name: 'English',
      },
      {
        code: 'th',
        iso: 'th-TH',
        name: 'ไทย',
      },
    ],
    defaultLocale: 'th',
    vueI18n: {
      messages: {
        th: require('./locales/th.json'),
        en: require('./locales/en.json'),
      },
    },
  },
  vite: {
    css: {
      preprocessorOptions: {
        scss: {
          additionalData: '@use "@/assets/_colors.scss" as *;',
        },
      },
    },
  },
  build: {
    postcss: {
      postcssOptions: {
        plugins: {
          tailwindcss: {},
          autoprefixer: {},
        },
      },
    },
  },
  css: ['~/assets/app.scss'],
  runtimeConfig: {
    apiSecret: 'super_secret_key',
    public: {
      baseURL: process.env.BASE_URL || 'localhost:3000',
      apiBase: '/api',
    },
  },
})
```

pages/index.vue
```javascript
<template>
  <div>
    Hi there
    <div>
      <NuxtLink to="products">List product</NuxtLink>
      <h1>{{ $t('hello', { name: 'Gold D Roger' }) }}</h1>
      <h1>{{ $t('message.greeting', { name: 'Gold D Roger' }) }}</h1>

      <label for="locale-select">{{ $t('language') }} : </label>
      <select id="locale-select" v-model="$i18n.locale">
        <option value="en">English</option>
        <option value="th">ภาษาไทย</option>
      </select>
    </div>

    <button @click="increment()">Click to increment</button>
    <p>{{ counter.count }}</p>
  </div>
</template>

<script setup>
import { useCounterStore } from '@/stores/counter'
const counter = useCounterStore()

definePageMeta({
  layout: 'default',
})
const config = useRuntimeConfig()
if (process.client) {
  console.log('API secret:', config.app)
  console.log('BASE URL :', config.public.baseURL)
}

const increment = () => {
  counter.$patch({ count: counter.count++ })
  counter.increment()
}
</script>
```

and when I run 
`yarn dev`

it thew error :
```

 ERROR  Error compiling template:  {                                                                                                                      08:10:05
  src: 'node_modules/nuxt-i18n/src/templates/head-meta.js',
  fileName: 'nuxt-i18n/head-meta.js',
  options: {
    Constants: {
      COMPONENT_OPTIONS_KEY: 'nuxtI18n',
      STRATEGIES: [Object]
    },
    nuxtOptions: {
      isUniversalMode: false,
      trailingSlash: undefined
    },
    options: {
      vueI18n: [Object],
      vueI18nLoader: false,
      locales: [Array],
      defaultLocale: 'th',
      defaultDirection: 'ltr',
      routesNameSeparator: '___',
      defaultLocaleRouteNameSuffix: 'default',
      sortRoutes: true,
      strategy: 'prefix_except_default',
      lazy: false,
      langDir: null,
      rootRedirect: null,
      detectBrowserLanguage: [Object],
      differentDomains: false,
      seo: false,
      baseUrl: '',
      vuex: [Object],
      parsePages: true,
      pages: {},
      skipSettingLocaleOnNavigate: false,
      beforeLanguageSwitch: [Function: beforeLanguageSwitch],
      onBeforeLanguageSwitch: [Function: onBeforeLanguageSwitch],
      onLanguageSwitched: [Function: onLanguageSwitched],
      normalizedLocales: [Array],
      localeCodes: [Array]
    }
  },
  write: true,
  filename: 'nuxt-i18n/head-meta.js',
  dst: '.nuxt/nuxt-i18n/head-meta.js'
}


 ERROR  Cannot start nuxt:  iso is not defined                                                                                                            08:10:05

  at eval (eval at <anonymous> (node_modules/lodash.template/index.js:1550:12), <anonymous>:8:10)
  at compileTemplate (node_modules/@nuxt/kit/dist/index.mjs:570:45)
  at async node_modules/nuxt/dist/index.mjs:1980:22
  at async Promise.all (index 16)
  at async generateApp (node_modules/nuxt/dist/index.mjs:1979:3)
  at async _applyPromised (node_modules/perfect-debounce/dist/index.mjs:54:10)


 ERROR  [unhandledRejection] iso is not defined                                                                                                           08:10:05

  at eval (eval at <anonymous> (node_modules/lodash.template/index.js:1550:12), <anonymous>:8:10)
  at compileTemplate (node_modules/@nuxt/kit/dist/index.mjs:570:45)
  at async node_modules/nuxt/dist/index.mjs:1980:22
  at async Promise.all (index 16)
  at async generateApp (node_modules/nuxt/dist/index.mjs:1979:3)
  at async _applyPromised (node_modules/perfect-debounce/dist/index.mjs:54:10)


 ERROR  Error compiling template:  {                                                                                                                      08:10:05
  src: '/node_modules/nuxt-i18n/src/templates/plugin.main.js',
  fileName: 'nuxt-i18n/plugin.main.js',
  options: {
    Constants: {
      COMPONENT_OPTIONS_KEY: 'nuxtI18n',
      STRATEGIES: [Object]
    },
    nuxtOptions: {
      isUniversalMode: false,
      trailingSlash: undefined
    },
    options: {
      vueI18n: [Object],
      vueI18nLoader: false,
      locales: [Array],
      defaultLocale: 'th',
      defaultDirection: 'ltr',
      routesNameSeparator: '___',
      defaultLocaleRouteNameSuffix: 'default',
      sortRoutes: true,
      strategy: 'prefix_except_default',
      lazy: false,
      langDir: null,
      rootRedirect: null,
      detectBrowserLanguage: [Object],
      differentDomains: false,
      seo: false,
      baseUrl: '',
      vuex: [Object],
      parsePages: true,
      pages: {},
      skipSettingLocaleOnNavigate: false,
      beforeLanguageSwitch: [Function: beforeLanguageSwitch],
      onBeforeLanguageSwitch: [Function: onBeforeLanguageSwitch],
      onLanguageSwitched: [Function: onLanguageSwitched],
      normalizedLocales: [Array],
      localeCodes: [Array]
    }
  },
  filename: 'nuxt-i18n/plugin.main.js',
  dst: '/.nuxt/nuxt-i18n/plugin.main.js'
}


 ERROR  Error compiling template:  {                                                                                                                      08:10:05
  src: '/node_modules/nuxt-i18n/src/templates/utils-common.js',
  fileName: 'nuxt-i18n/utils-common.js',
  options: {
    Constants: {
      COMPONENT_OPTIONS_KEY: 'nuxtI18n',
      STRATEGIES: [Object]
    },
    nuxtOptions: {
      isUniversalMode: false,
      trailingSlash: undefined
    },
    options: {
      vueI18n: [Object],
      vueI18nLoader: false,
      locales: [Array],
      defaultLocale: 'th',
      defaultDirection: 'ltr',
      routesNameSeparator: '___',
      defaultLocaleRouteNameSuffix: 'default',
      sortRoutes: true,
      strategy: 'prefix_except_default',
      lazy: false,
      langDir: null,
      rootRedirect: null,
      detectBrowserLanguage: [Object],
      differentDomains: false,
      seo: false,
      baseUrl: '',
      vuex: [Object],
      parsePages: true,
      pages: {},
      skipSettingLocaleOnNavigate: false,
      beforeLanguageSwitch: [Function: beforeLanguageSwitch],
      onBeforeLanguageSwitch: [Function: onBeforeLanguageSwitch],
      onLanguageSwitched: [Function: onLanguageSwitched],
      normalizedLocales: [Array],
      localeCodes: [Array]
    }
  },
  write: true,
  filename: 'nuxt-i18n/utils-common.js',
  dst: '/.nuxt/nuxt-i18n/utils-common.js'
}


 ERROR  Error compiling template:  {                                                                                                                      08:10:05
  src: '/node_modules/nuxt-i18n/src/templates/plugin.utils.js',
  fileName: 'nuxt-i18n/plugin.utils.js',
  options: {
    Constants: {
      COMPONENT_OPTIONS_KEY: 'nuxtI18n',
      STRATEGIES: [Object]
    },
    nuxtOptions: {
      isUniversalMode: false,
      trailingSlash: undefined
    },
    options: {
      vueI18n: [Object],
      vueI18nLoader: false,
      locales: [Array],
      defaultLocale: 'th',
      defaultDirection: 'ltr',
      routesNameSeparator: '___',
      defaultLocaleRouteNameSuffix: 'default',
      sortRoutes: true,
      strategy: 'prefix_except_default',
      lazy: false,
      langDir: null,
      rootRedirect: null,
      detectBrowserLanguage: [Object],
      differentDomains: false,
      seo: false,
      baseUrl: '',
      vuex: [Object],
      parsePages: true,
      pages: {},
      skipSettingLocaleOnNavigate: false,
      beforeLanguageSwitch: [Function: beforeLanguageSwitch],
      onBeforeLanguageSwitch: [Function: onBeforeLanguageSwitch],
      onLanguageSwitched: [Function: onLanguageSwitched],
      normalizedLocales: [Array],
      localeCodes: [Array]
    }
  },
  filename: 'nuxt-i18n/plugin.utils.js',
  dst: '/.nuxt/nuxt-i18n/plugin.utils.js'
}


 ERROR  Error compiling template:  {                                                                                                                      08:10:05
  src: '/node_modules/nuxt-i18n/src/templates/plugin.routing.js',
  fileName: 'nuxt-i18n/plugin.routing.js',
  options: {
    Constants: {
      COMPONENT_OPTIONS_KEY: 'nuxtI18n',
      STRATEGIES: [Object]
    },
    nuxtOptions: {
      isUniversalMode: false,
      trailingSlash: undefined
    },
    options: {
      vueI18n: [Object],
      vueI18nLoader: false,
      locales: [Array],
      defaultLocale: 'th',
      defaultDirection: 'ltr',
      routesNameSeparator: '___',
      defaultLocaleRouteNameSuffix: 'default',
      sortRoutes: true,
      strategy: 'prefix_except_default',
      lazy: false,
      langDir: null,
      rootRedirect: null,
      detectBrowserLanguage: [Object],
      differentDomains: false,
      seo: false,
      baseUrl: '',
      vuex: [Object],
      parsePages: true,
      pages: {},
      skipSettingLocaleOnNavigate: false,
      beforeLanguageSwitch: [Function: beforeLanguageSwitch],
      onBeforeLanguageSwitch: [Function: onBeforeLanguageSwitch],
      onLanguageSwitched: [Function: onLanguageSwitched],
      normalizedLocales: [Array],
      localeCodes: [Array]
    }
  },
  filename: 'nuxt-i18n/plugin.routing.js',
  dst: '/.nuxt/nuxt-i18n/plugin.routing.js'
}

```

**Comment by danielroe** [comment]
That package has been deprecated, and moreover, did not have support for Nuxt 3. See https://i18n.nuxtjs.org.
