### ISSUE TITLE
Unexpected token '||='

### ISSUE THREAD

**Issue by zachdyer** [nuxt/framework#8677]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v14.16.0`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.1`
- Package Manager:  `npm@6.14.11`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

npx nuxi init .
npm install    
npm run dev 

### Describe the bug

When you visit localhost:3000 you get the error.

### Logs

```shell
Unexpected token '||='

at new Script (vm.js:101:7)
at createScript (vm.js:262:10)
at Object.runInThisContext (vm.js:310:10)
at ViteNodeRunner.directRequest (/C:/Users/zachd/OneDrive/Documents/GitHub/nuxt3/node_modules/vite-node/dist/client.mjs:245:19)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async ViteNodeRunner.cachedRequest (/C:/Users/zachd/OneDrive/Documents/GitHub/nuxt3/node_modules/vite-node/dist/client.mjs:129:12)
at async request (/C:/Users/zachd/OneDrive/Documents/GitHub/nuxt3/node_modules/vite-node/dist/client.mjs:152:16)
at async C:/Users/zachd/OneDrive/Documents/GitHub/nuxt3/node_modules/nuxt/dist/app/composables/index.mjs:46:31
at async ViteNodeRunner.directRequest (/C:/Users/zachd/OneDrive/Documents/GitHub/nuxt3/node_modules/vite-node/dist/client.mjs:250:5)
at async ViteNodeRunner.cachedRequest (/C:/Users/zachd/OneDrive/Documents/GitHub/nuxt3/node_modules/vite-node/dist/client.mjs:129:12)
```

**Comment by dargmuesli** [comment]
I saw this error a few hours ago too while tracing another issue. It would surely help if you could provide a minimal reproduction! :raised_hands:

**Comment by lawrence-V** [comment]
I have the same issue.

**Comment by manniL** [comment]
Hey! This should be resolved when using [edge channel](https://v3.nuxtjs.org/guide/going-further/edge-channel/), or in the upcoming RC.

**Comment by zachdyer** [comment]
Maybe it has something to do with it running on Windows.

**Comment by manniL** [comment]
It has been resolved in RC.13 and was related logical assignments not being supported in some Node versions.
