### ISSUE TITLE
[nuxt] [request error] [unhandled] [500] window is not defined

### ISSUE THREAD

**Issue by ouyangzhigang** [nuxt/framework#8680]
### Environment

Nuxt project info:                                                                                            16:28:20

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `yarn@1.22.15`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

~

### Describe the bug

[nuxt] [request error] [unhandled] [500] window is not defined
  at Object.<anonymous> (D:\private\nuxt-app-workflow\node_modules\dhtmlx-gantt\codebase\dhtmlxgantt.js:13:218)
  at Module._compile (node:internal/modules/cjs/loader:1105:14)
  at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
  at Module.load (node:internal/modules/cjs/loader:981:32)
  at Function.Module._load (node:internal/modules/cjs/loader:822:12)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29)
  at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
[nuxt] [request error] [unhandled] [500] window is not defined
  at Object.<anonymous> (D:\private\nuxt-app-workflow\node_modules\dhtmlx-gantt\codebase\dhtmlxgantt.js:13:218)
  at Module._compile (node:internal/modules/cjs/loader:1105:14)
  at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
  at Module.load (node:internal/modules/cjs/loader:981:32)
  at Function.Module._load (node:internal/modules/cjs/loader:822:12)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29)
  at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:385:24)

**Comment by manniL** [comment]
Hey! Could you kindly provide a [reproduction](https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

This issue looks like a component or library is accessing `window` while being called on the server-side where it is not available. See also [this blog post](https://blog.lichter.io/posts/universal-ssr-vue-component-guide/#common-pitfalls).
