### ISSUE TITLE
 ERROR  Cannot start nuxt:  Cannot read property 'https' of undefined

### ISSUE THREAD

**Issue by RijaCloud** [nuxt/framework#8756]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v14.19.3`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `npm@6.14.17`
- Builder:          `vite`
- User Config:      `debug`, `meta`, `build`, `modules`, `proxy`, `vite`, `css`, `plugins`, `publicRuntimeConfig`, `components`, `experimental`, `ssr`
- Runtime Modules:  `@pinia/nuxt@0.3.1`, `nuxt-proxy@0.2.4`
- Build Modules:    `-`
------------------------------

👉 Report an issue: https://github.com/nuxt/framework/issues/new                                              08:30:03

👉 Suggest an improvement: https://github.com/nuxt/framework/discussions/new

👉 Read documentation: https://v3.nuxtjs.org

### Reproduction

I think it is specific to my local but here is my package.json for a reproduction purpose : 

###
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "https": "nuxt dev --https true",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "test": "vitest",
    "coverage": "vitest run --coverage"
  },
  "devDependencies": {
    "@types/chart.js": "^2.9.37",
    "@types/multer": "^1.4.7",
    "nuxt": "3.0.0-rc.8",
    "sass": "1.53.0",
    "unplugin-auto-import": "^0.11.1",
    "unplugin-vue-components": "^0.21.2",
    "vitest": "0.18.1"
  },
  "dependencies": {
    "@ant-design/icons-vue": "^6.1.0",
    "@googlemaps/js-api-loader": "^1.14.3",
    "@intlify/nuxt3": "^0.2.3",
    "@nuxt/ui-templates": "^0.3.2",
    "@nuxt/vite-builder": "^3.0.0-rc.8",
    "@pinia/nuxt": "^0.3.1",
    "@vuepic/vue-datepicker": "^3.5.2",
    "@vueup/vue-quill": "^1.0.0-beta.10",
    "animated-number-vue": "^1.0.0",
    "ant-design-vue": "^3.2.10",
    "axios": "^0.27.2",
    "bootstrap": "^4.4.1",
    "chart.js": "^3.9.1",
    "chartjs-adapter-date-fns": "^2.0.0",
    "chartjs-plugin-annotation": "^2.0.1",
    "chartjs-plugin-datalabels": "^2.1.0",
    "country-region-data": "^2.5.0",
    "croppie": "^2.6.5",
    "date-fns": "^2.29.1",
    "file-saver": "^2.0.5",
    "google-auth-library": "^8.6.0",
    "is-image": "^3.1.0",
    "jquery": "^3.6.1",
    "js-base64": "^3.7.2",
    "leaflet": "^1.9.1",
    "leaflet-gesture-handling": "^1.2.2",
    "leaflet.markercluster": "^1.5.3",
    "libphonenumber-js": "^1.10.8",
    "lodash": "^4.17.21",
    "nprogress": "^0.2.0",
    "numbro": "^2.3.6",
    "nuxt-proxy": "^0.2.4",
    "pinia": "^2.0.18",
    "qs": "^6.11.0",
    "query-string": "^7.1.1",
    "quill": "^1.3.7",
    "sortablejs": "^1.15.0",
    "vue-chart-3": "^3.1.8",
    "vue-chartjs": "^4.1.1",
    "vue-cropperjs": "^5.0.0",
    "vue-easy-lightbox": "^1.8.2",
    "vue-facebook-login-component-next": "^1.0.4",
    "vue-i18n": "^9.2.0",
    "vue-it-bigger": "^0.2.2",
    "vue-multiselect": "^3.0.0-alpha.2",
    "vue-range-component": "^1.0.3",
    "vue-simple-floating-labels": "^1.0.4",
    "vue-slide-toggle": "^1.1.1",
    "vue-slide-up-down": "^2.0.1",
    "vue3-dropzone": "^2.0.1",
    "vue3-google-login": "^2.0.12",
    "vue3-google-oauth2": "^1.0.6",
    "vue3-perfect-scrollbar": "^1.6.0",
    "vue3-quill": "^0.2.6",
    "vue3-slide-up-down": "^1.2.5",
    "vuedraggable": "^4.1.0",
    "workbox-window": "^6.5.3",
    "xlsx": "^0.18.5",
    "yup": "^0.32.11"
  }
}
###

### Describe the bug

Hi ,the bug appear when i run `'npm run dev` and nothing else.

###
 ERROR  Cannot start nuxt:  Cannot read property 'https' of undefined                                         09:29:42

  at buildClient (/C:/Users/Dilypse/Documents/maj/front-14-19-3/node_modules/@nuxt/vite-builder/dist/shared/vite-builder.3e79d8e0.mjs:287:41)
  at async bundle (/C:/Users/Dilypse/Documents/maj/front-14-19-3/node_modules/@nuxt/vite-builder/dist/shared/vite-builder.3e79d8e0.mjs:837:3)
  at async build (/C:/Users/Dilypse/Documents/maj/front-14-19-3/node_modules/nuxt/dist/index.mjs:1840:5)
  at async Promise.all (index 1)
  at async load (/C:/Users/Dilypse/Documents/maj/front-14-19-3/node_modules/nuxt/node_modules/nuxi/dist/chunks/dev.mjs:6770:9)
  at async Object.invoke (/C:/Users/Dilypse/Documents/maj/front-14-19-3/node_modules/nuxt/node_modules/nuxi/dist/chunks/dev.mjs:6813:5)
  at async _main (/C:/Users/Dilypse/Documents/maj/front-14-19-3/node_modules/nuxt/node_modules/nuxi/dist/cli.mjs:46:20)

###

**Comment by RijaCloud** [comment]
Hi @danielroe  you are right, I had to create a new project and reinstall all the libs. Now it works.
