### ISSUE TITLE
Module is not defined from definePageMeta

### ISSUE THREAD

**Issue by JohnnyEvo** [nuxt/framework#8762]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.7.0`
- Nuxt Version:     `3.0.0-rc.13`
- Nitro Version:    `0.6.1`
- Package Manager:  `npm@8.15.0`
- Builder:          `vite`
- User Config:      `typescript`, `build`, `modules`, `css`, `runtimeConfig`
- Runtime Modules:  `@lewebsimple/nuxt3-svg@0.1.1`, `@nuxtjs/tailwindcss@6.1.3`, `@pinia/nuxt@0.4.3`
- Build Modules:    `-`

### Reproduction

[Demonstration](https://stackblitz.com/edit/github-bm1tnv?file=pages/index.vue)

I create a reusable transition `/composables/transitions/translateContent.ts` :

```ts
import {timeline} from "motion";

export let useTranslateContent = {
    css: false,
    onLeave: async (el: HTMLElement, done: Function) => {
        // logic
        await timeline(<any>sequence).finished;

        done();
    },
    onEnter: async (el: Element, done: Function) => {
        // logic
        await timeline(<any>sequence).finished;

        done();
    }
}
```

I apply my transition with `definePageMeta` : 

```vue
<template>
  <div>
    <NuxtLayout>
      <!-- DOM -->
    </NuxtLayout>
  </div>
</template>

<script setup lang="ts">
import {useTranslateContent} from "../composables/transitions/translateContent";
definePageMeta({
  pageTransition: useTranslateContent
})

</script>
```

### Describe the bug

Nuxt indicates `useTranslateContent is not defined`.

### Additional context

With previous version, it works.

### Logs

```shell
[nuxt] [request error] [unhandled] [500] useTranslateContent is not defined
  at ./pages/index.vue?macro=true:2:23
  at ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:250:11)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:129:12)
  at async request (./node_modules/vite-node/dist/client.mjs:152:16)
  at async virtual:nuxt:./.nuxt/routes.mjs:1:238
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:250:5)
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:129:12)
  at async request (./node_modules/vite-node/dist/client.mjs:152:16)
  at async ./node_modules/nuxt/dist/pages/runtime/router.mjs:12:31
```
```

**Comment by DamianGlowala** [comment]
Let's track in https://github.com/nuxt/framework/issues/8676.
