### ISSUE TITLE
Nuxt rc13 - Failed to resolve import

### ISSUE THREAD

**Issue by Der-Alex** [nuxt/framework#8770]
### Environment

- Nuxi 3.0.0-rc.13 
- Operating System: `Linux`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.13`
- Nitro Version:    `0.6.1`
- Package Manager:  `npm@8.11.0`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `app`, `components`, `css`, `build`, `modules`, `apollo`, `postcss`, `vite`, `render`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.1.3`, `@nuxtjs/apollo@5.0.0-alpha.3`
- Build Modules:    `-`

### Reproduction

- 

### Describe the bug

I created an app with nuxt 3 rc-13 based on a project running nuxt 3 rc-11. I copied the complete folder structure except .nuxt, node_modules, package.json and  package-lock.json. I installed the modules  @nuxtjs/tailwindcss@6.1.3 and @nuxtjs/apollo@5.0.0-alpha.3. 

After starting the app with `npm run dev` I got an error that the module `@vue/apollo-composable` is missing. This was because I forgot to remove the associated import statements in several vue files. After I removed the imports and set `apollo: { autoImports: true, ... }` in my nuxt.config nuxt still complains `[plugin:vite:import-analysis] Failed to resolve import "@vue/apollo-composable" from "pages/[...pages].vue". Does the file exist?` 

It seems like vite or npm or some other unknown magic had cached my files and now still complains about imports in files that don't exist anymore... I double checked my files and removed all import statements related to `@vue/apollo-composable`. So what's happening there? 

### Logs

```shell
ERROR  13:14:48 [vite] Internal server error: Failed to resolve import "@vue/apollo-composable" from "pages/[...pages].vue". Does the file exist?
  Plugin: vite:import-analysis
  File: /home/aw/dev/ext/pages/[...pages].vue:5:27
  3  |  import { Head as __nuxt_component_2 } from "/home/aw/dev/ext/node_modules/nuxt/dist/head/runtime/components";
  4  |  import { useRoute, createError } from '#app';
  5  |  import { useQuery } from '@vue/apollo-composable';
     |                            ^
  6  |  import { useGetNodeByPath } from '~/composables/useMobileNav';
  7  |  import { useGetMeta } from '~/composables/useGetMeta';
      at formatError (file:///home/aw/dev/ext/node_modules/vite/dist/node/chunks/dep-51c4f80a.js:39971:46)
      at TransformContext.error (file:///home/aw/dev/ext/node_modules/vite/dist/node/chunks/dep-51c4f80a.js:39967:19)
      at normalizeUrl (file:///home/aw/dev/ext/node_modules/vite/dist/node/chunks/dep-51c4f80a.js:36835:33)
      at async TransformContext.transform (file:///home/aw/dev/ext/node_modules/vite/dist/node/chunks/dep-51c4f80a.js:36968:47)
      at async Object.transform (file:///home/aw/dev/ext/node_modules/vite/dist/node/chunks/dep-51c4f80a.js:40224:30)
      at async loadAndTransform (file:///home/aw/dev/ext/node_modules/vite/dist/node/chunks/dep-51c4f80a.js:36611:29)

[Vue Router warn]: uncaught error during route navigation:
Error: [vite-node] Failed to load @vue/apollo-composable
    at ViteNodeRunner.directRequest (file:///home/aw/dev/ext/node_modules/vite-node/dist/client.mjs:181:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ViteNodeRunner.cachedRequest (file:///home/aw/dev/ext/node_modules/vite-node/dist/client.mjs:129:12)
    at async request (file:///home/aw/dev/ext/node_modules/vite-node/dist/client.mjs:152:16)
    at async /home/aw/dev/ext/pages/[...pages].vue:9:31
    at async ViteNodeRunner.directRequest (file:///home/aw/dev/ext/node_modules/vite-node/dist/client.mjs:250:5)
    at async ViteNodeRunner.cachedRequest (file:///home/aw/dev/ext/node_modules/vite-node/dist/client.mjs:129:12)
    at async request (file:///home/aw/dev/ext/node_modules/vite-node/dist/client.mjs:152:16)
    at async /home/aw/dev/ext/node_modules/nuxt/dist/pages/runtime/router.mjs:75:94
[Vue Router warn]: uncaught error during route navigation:
Error: [vite-node] Failed to load @vue/apollo-composable
    at ViteNodeRunner.directRequest (file:///home/aw/dev/ext/node_modules/vite-node/dist/client.mjs:181:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ViteNodeRunner.cachedRequest (file:///home/aw/dev/ext/node_modules/vite-node/dist/client.mjs:129:12)
    at async request (file:///home/aw/dev/ext/node_modules/vite-node/dist/client.mjs:152:16)
    at async /home/aw/dev/ext/pages/[...pages].vue:9:31
    at async ViteNodeRunner.directRequest (file:///home/aw/dev/ext/node_modules/vite-node/dist/client.mjs:250:5)
    at async ViteNodeRunner.cachedRequest (file:///home/aw/dev/ext/node_modules/vite-node/dist/client.mjs:129:12)
    at async request (file:///home/aw/dev/ext/node_modules/vite-node/dist/client.mjs:152:16)
    at async /home/aw/dev/ext/node_modules/nuxt/dist/pages/runtime/router.mjs:75:94
```

**Comment by Der-Alex** [comment]
Hi @danielroe thanks for your help. 

`npx nuxi cleanup` didn't help. I also deleted the .nuxt, node_modules and package-lock.json again, did `npm cache clean --force` and also installed a new nodejs version with nvm. The errors remain. In these files I still use `useQuery` but this should be resolved by `@nuxtjs/apollo@next` and the config in my nuxt.config.ts.

**Comment by danielroe** [comment]
It sounds like this might be an issue with that module then. If you don't think so, would you provide a minimal reproduction?

**Comment by Der-Alex** [comment]
Yes, I also guess it's the module  `@nuxtjs/apollo@next`. I'll reach out to the maintainers first. 
Thanks
