### ISSUE TITLE
RC13 - dev SSR error with module 'mathjs'

### ISSUE THREAD

**Issue by matteomejia** [nuxt/framework#8774]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.0.0-rc.13`
- Nitro Version:    `0.6.1`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/matteomejia/mathjs-nuxt

### Describe the bug

When using the library mathjs in development mode, import fails with the following error:

```
[nuxt] [request error] [unhandled] [500] __vite_ssr_import_0__.default is not a function
  at ./node_modules/mathjs/lib/esm/entry/configReadonly.js:16:30
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:250:5)
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:129:12)
  at async request (./node_modules/vite-node/dist/client.mjs:152:16)
  at async ./node_modules/mathjs/lib/esm/entry/mainAny.js:2:31
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:250:5)
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:129:12)
  at async request (./node_modules/vite-node/dist/client.mjs:152:16)
  at async mathjs:1:238
```

Error happens on any server-side loaded page. 

### Additional context

1. Problem does not happen when using Vite SSR outside of Nuxt 3.
2. Opened an issue in the mathjs repo but the error could not be reproduced.
3. The error can also be reproduced by loading the library via a plugin

**Comment by sewalsh** [comment]
Appears to be a vite-node error. If you disable it, it works as expected in dev mode.

nuxt.config.ts:
``` typescript
    vite: {
        devBundler: "legacy"
    }
```

**Comment by matteomejia** [comment]
Thanks @sewalsh! Hadn't considered vite-node could be disabled.

**Comment by manniL** [comment]
I'd rather still keep this open as it is an issue, though a workaround is available.
