### ISSUE TITLE
error: nuxt instance unavailable at Module.useAsyncData #8826

### ISSUE THREAD

**Issue by Maxp777** [nuxt/framework#8844]
### Environment

Nuxi 3.0.0-rc.14-27796957.b60f136
Nuxt 3.0.0-rc.14-27796957.b60f136 with Nitro 0.6.1-27791756.086802d

### Reproduction

https://github.com/Maxp777/nuxt4

### Describe the bug

error: nuxt instance unavailable at Module.useNuxtApp

### Logs

```shell
[log error] Error: nuxt instance unavailable
    at Module.useNuxtApp (/home/user/Downloads/nuxt-error-7-main/node_modules/nuxt/dist/app/nuxt.mjs:162:13)
    at Module.useAsyncData (/home/user/Downloads/nuxt-error-7-main/node_modules/nuxt/dist/app/composables/asyncData.mjs:28:38)
    at Module.useFetch (/home/user/Downloads/nuxt-error-7-main/node_modules/nuxt/dist/app/composables/fetch.mjs:52:43)
    at Proxy.updateList (/home/user/Downloads/nuxt-error-7-main/store/list.store.ts:25:27)
    at Proxy.<anonymous> (file:///home/user/Downloads/nuxt-error-7-main/node_modules/pinia/dist/pinia.mjs:1365:30)
    at update (/home/user/Downloads/nuxt-error-7-main/pages/index.vue:43:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async setup (/home/user/Downloads/nuxt-error-7-main/pages/index.vue:55:83) {} setup function
[Vue Router warn]: No match found for location with path "/api/test"
```

**Comment by danielroe** [comment]
The issue is that you are calling multiple async methods that depend on the nuxt instance in a function handler. See https://github.com/nuxt/framework/issues/5740#issuecomment-1229197529 for more information about the issue.

**Comment by Maxp777** [comment]
@danielroe  in comment is say - Update: upstream issue fixed. You probably don't need this workaround anymore! Just update the lockfile

but is not fixed

**Comment by danielroe** [comment]
I linked a comment that explains the issue. It's not a Nuxt bug, but it's a limitation of running composables async. Please read it; I think it will help you. We also plan to write some documentation to help people understand how composables work under the hood: https://github.com/nuxt/framework/issues/6996.

**Comment by Maxp777** [comment]
if that is `It's not a Nuxt bug, but it's a limitation of running composables async. `why it work when enable some additional modules, and without it not work?
if that modules do something what help to work, why nuxt don't do the same?

**Comment by Maxp777** [comment]
if it's limitation, when it will not work in any case?
