### ISSUE TITLE
Error 500 on Windows trying to resolve file paths with custom buildDir

### ISSUE THREAD

**Issue by indiehjaerta** [nuxt/framework#8857]
### Environment

Nuxt project info:                                                                                           

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-rc.13`
- Nitro Version:    `0.6.1`
- Package Manager:  `pnpm@7.13.4`
- Builder:          `vite`
- User Config:      `buildDir`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Use a Windows laptop use a non-standard buildDir
Install depdencies with pnpm and start the dev environment. 

### Describe the bug

Running `pnpm run dev` gives this output in the terminal

![image](https://user-images.githubusercontent.com/14825674/200852777-7630906a-fc93-49b9-80d7-ed57c707d8eb.png)

### Additional context

Didn't create a Codesandbox or Stackblitz since I'm guessing they don't run Windows OS.

I checked the .nuxt output and some file output is missing the file:// but this is the same with the standard or any other buildDir so I don't know if this cause be causing this bug. I don't know if I can get a better stacktrace for more information.

**Comment by danielroe** [comment]
What is the content of your nuxt config?

**Comment by isimmons** [comment]
I can confirm on Windows 10, node 18, nuxt RC 13.

1. npx nuxi init foo
2. cd foo
3. npm i
4. npm run dev

Everything looks good until I open the browser and get the same error as above.

nuxt.config.ts taken from the docs but also tried several name variations just in case. Doesn't matter what I name the buildDir.

```
// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  buildDir: 'nuxt-dist',
});
```

Also this happens if I run `npm run build` instead. No errors until I try to view in browser.

```
C:\Users\isimm\code\nuxitests\foo>npm run build

> build     
> nuxt build

Nuxi 3.0.0-rc.13                                                                                      13:15:50
Nuxt 3.0.0-rc.13 with Nitro 0.6.1                                                                     13:15:50

 ERROR  (node:1708) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at 
any time
(Use `node --trace-warnings ...` to show where the warning was created)

i Client built in 1637ms                                                                              13:15:55
i Building server...                                                                                  13:15:55
√ Server built in 823ms                                                                               13:15:56
√ Generated public .output/public                                                               nitro 13:15:56
i Building Nitro Server (preset: node-server)                                                   nitro 13:15:56
√ Nitro server built                                                                            nitro 13:16:00
  ├─ .output/server/package.json (764 B) (327 B gzip)
  ├─ .output/server/index.mjs (477 B) (260 B gzip)
  ├─ .output/server/chunks/welcome-styles.84d3e35e.mjs.map (364 B) (226 B gzip)
  ├─ .output/server/chunks/welcome-styles.84d3e35e.mjs (4.86 kB) (1.49 kB gzip)
  ├─ .output/server/chunks/styles.mjs.map (455 B) (237 B gzip)
  ├─ .output/server/chunks/styles.mjs (540 B) (260 B gzip)
  ├─ .output/server/chunks/server.mjs.map (29.5 kB) (4.93 kB gzip)
  ├─ .output/server/chunks/server.mjs (35.7 kB) (11.2 kB gzip)
  ├─ .output/server/chunks/renderer.mjs.map (19.8 kB) (3.45 kB gzip)
  ├─ .output/server/chunks/renderer.mjs (15.8 kB) (4.87 kB gzip)
  ├─ .output/server/chunks/node-server.mjs.map (75.4 kB) (5.53 kB gzip)
  ├─ .output/server/chunks/node-server.mjs (21.1 kB) (6.4 kB gzip)
  ├─ .output/server/chunks/error-component.353a8a35.mjs.map (2.35 kB) (806 B gzip)
  ├─ .output/server/chunks/error-component.353a8a35.mjs (2.01 kB) (896 B gzip)
  ├─ .output/server/chunks/error-500.mjs.map (1.06 kB) (382 B gzip)
  ├─ .output/server/chunks/error-500.mjs (4.26 kB) (1.83 kB gzip)
  ├─ .output/server/chunks/error-500.53067f3b.mjs.map (1.7 kB) (616 B gzip)
  ├─ .output/server/chunks/error-500.53067f3b.mjs (3.17 kB) (1.41 kB gzip)
  ├─ .output/server/chunks/error-500-styles.ad145178.mjs.map (370 B) (228 B gzip)
  ├─ .output/server/chunks/error-500-styles.ad145178.mjs (2.22 kB) (864 B gzip)
  ├─ .output/server/chunks/error-404.11c519f1.mjs.map (2.36 kB) (802 B gzip)
  ├─ .output/server/chunks/error-404.11c519f1.mjs (4.03 kB) (1.7 kB gzip)
  ├─ .output/server/chunks/error-404-styles.3db9fdd2.mjs.map (370 B) (228 B gzip)
  ├─ .output/server/chunks/error-404-styles.3db9fdd2.mjs (3.92 kB) (1.25 kB gzip)
  ├─ .output/server/chunks/client.manifest.mjs.map (1.84 kB) (431 B gzip)
  └─ .output/server/chunks/client.manifest.mjs (2.6 kB) (516 B gzip)
Σ Total size: 2.94 MB (684 kB gzip)
√ You can preview this build using node .output/server/index.mjs                                nitro 13:16:01  

C:\Users\isimm\code\nuxitests\foo>node .output/server/index.mjs 
Listening http://[::]:3000
[Vue warn]: Unhandled error during execution of setup function 
  at <Error500 statusCode=500 statusMessage="Internal Server Error" description="head.addEntry is not a function"  ... >
[nuxt] [request error] [unhandled] [500] head.addEntry is not a function
  at /C:/Users/isimm/code/nuxitests/foo/.output/server/chunks/server.mjs:461:8
  at fn (/C:/Users/isimm/code/nuxitests/foo/.output/server/chunks/server.mjs:139:27)
  at Object.callAsync (/C:/Users/isimm/code/nuxitests/foo/.output/server/node_modules/unctx/dist/index.mjs:49:19)
  at callWithNuxt (/C:/Users/isimm/code/nuxitests/foo/.output/server/chunks/server.mjs:141:23)
  at applyPlugin (/C:/Users/isimm/code/nuxitests/foo/.output/server/chunks/server.mjs:110:39)
  at applyPlugins (/C:/Users/isimm/code/nuxitests/foo/.output/server/chunks/server.mjs:119:11)
  at async createNuxtAppServer (/C:/Users/isimm/code/nuxitests/foo/.output/server/chunks/server.mjs:786:7)      
  at async Object.renderToString (/C:/Users/isimm/code/nuxitests/foo/.output/server/node_modules/vue-bundle-renderer/dist/runtime.mjs:172:19)
  at async /C:/Users/isimm/code/nuxitests/foo/.output/server/chunks/renderer.mjs:373:21
  at async /C:/Users/isimm/code/nuxitests/foo/.output/server/chunks/renderer.mjs:29:22
[Vue warn]: Unhandled error during execution of setup function
  at <Error500 statusCode=500 statusMessage="" description="head.addEntry is not a function"  ... >
```

**Comment by indiehjaerta** [comment]
Still exists in latest.
------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.18.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `pnpm@7.16.1`
- Builder:          `vite`
- User Config:      `buildDir`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
