### ISSUE TITLE
Error on nuxi install

### ISSUE THREAD

**Issue by adityafawzan** [nuxt/framework#889]
error while trying to install nuxi
![Screenshot_20211013_112702](https://user-images.githubusercontent.com/48414316/137067506-4e8e0fe0-7183-452d-8e0f-c7799b19fd53.png)

**Comment by productfrontenddeveloper** [comment]
Please detail, windows or mac, node, npm version

**Comment by liuxsen** [comment]
> Please add detail, windows or mac, node, npm version

mac
![image](https://user-images.githubusercontent.com/12598696/137078176-13d2897c-93b7-4a03-9369-df1f651abd12.png)

========

![image](https://user-images.githubusercontent.com/12598696/137078212-7f83d7d9-44b3-49ab-9677-c8e19d9e2817.png)

**Comment by adityafawzan** [comment]
> @adityafawzan https://v3.nuxtjs.org/getting-started/introduction#prerequisites
> 
> * If you already have Node.js installed, check with node --version that you are using v14 or v16.

Thanks a lot, by upgrading my Node version, problem resolved

but now after i did yarn install and yarn dev, app running, but i dont see any project folder/directory excep .nuxt and node_modules

![image](https://user-images.githubusercontent.com/48414316/137080711-28b9be21-f13c-4422-93a9-10291d0c92d3.png)

**Comment by liuxsen** [comment]
it's not ok with me ;

![image](https://user-images.githubusercontent.com/12598696/137080996-d8247ca7-9b27-4a8f-9998-802fc9d754ba.png)

**Comment by andysay** [comment]
C:\Users\Andy\Desktop\nuxt3>npm -v
8.0.0

C:\Users\Andy\Desktop\nuxt3>node -v
v16.11.0


C:\Users\Andy\Desktop\nuxt3>npx nuxi init nuxt3-app
Nuxt CLI v3.0.0-27234503.d5127e9                                                                              10:01:03

 WARN  could not fetch remote https://github.com/nuxt/starter                                                 10:01:04


 ERROR  could not find commit hash for v3                                                                     10:01:04

  at Degit._cloneWithTar (/C:/Users/Andy/AppData/Local/npm-cache/_npx/a95e0f536cf9a537/node_modules/nuxi-edge/dist/chunks/init.mjs:14288:10)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async Degit.clone (/C:/Users/Andy/AppData/Local/npm-cache/_npx/a95e0f536cf9a537/node_modules/nuxi-edge/dist/chunks/init.mjs:14126:4)
  at async Object.invoke (/C:/Users/Andy/AppData/Local/npm-cache/_npx/a95e0f536cf9a537/node_modules/nuxi-edge/dist/chunks/init.mjs:14684:5)
  at async _main (/C:/Users/Andy/AppData/Local/npm-cache/_npx/a95e0f536cf9a537/node_modules/nuxi-edge/dist/chunks/index.mjs:417:7)

**Comment by productfrontenddeveloper** [comment]
@adityafawzan please open because @andysay  and @liuxsen some problems continue :)

**Comment by andysay** [comment]
> @andysay @liuxsen It looks like the issue might be to do with your git version. Can you try running:
> 
> ```
> npx degit "nuxt/starter#v3" sample-project
> ```
> 
> and see if there are any errors?

C:\Users\Andy\Desktop\nuxt3>npx degit "nuxt/starter#v3" udc
Need to install the following packages:
  degit
Ok to proceed? (y) y
! could not fetch remote https://github.com/nuxt/starter
! could not find commit hash for v3

**Comment by danielroe** [comment]
@andysay Make sure you have `git` installed. Check [this issue](https://github.com/Rich-Harris/degit/issues/37) for more info.

**Comment by pi0** [comment]
Error message should be better by #923. I've also made #924 to migrate to an alternative, hopefully removing git command dependency
