### ISSUE TITLE
[nitro] [dev] [unhandledRejection] TypeError: Cannot read properties of undefined (reading 'meta')

### ISSUE THREAD

**Issue by michealroberts** [nuxt/framework#8932]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.1`
- Package Manager:  `pnpm@7.9.0`
- Builder:          `vite`
- User Config:      `ssr`, `app`, `css`, `modules`, `windicss`, `build`, `runtimeConfig`
- Runtime Modules:  `nuxt-windicss@2.5.0`, `@vueuse/nuxt@9.1.1`, `@pinia/nuxt@0.4.1`
- Build Modules:    `-`

### Reproduction

I can provide reproduction access to the repository if needed. Please request and I can grant access.

### Describe the bug

I'm not quite sure what has gone wrong, I installed the `nuxt-schema-org` package, and then duly uninstalled it after issues. I then ensured I was on the latest version of the Nuxt release candidate (13) and now the server side rendering is blowing up.

### Logs

```shell
nitro] [dev] [unhandledRejection] TypeError: Cannot read properties of undefined (reading 'meta')
    at ReactiveEffect.fn (/Users/michael/Developer/kinandconscious/kindandconscious-nuxt3/node_modules/.pnpm/nuxt@3.0.0-rc.12_43do2nblp6dlbagpqygyz2j2ka/node_modules/nuxt/dist/app/components/layout.mjs:49:106)
    at ReactiveEffect.run (/Users/michael/Developer/kinandconscious/kindandconscious-nuxt3/node_modules/.pnpm/@vue+reactivity@3.2.39/node_modules/@vue/reactivity/dist/reactivity.cjs.js:168:25)
    at ComputedRefImpl.get value [as value] (/Users/michael/Developer/kinandconscious/kindandconscious-nuxt3/node_modules/.pnpm/@vue+reactivity@3.2.39/node_modules/@vue/reactivity/dist/reactivity.cjs.js:1139:39)
    at Proxy.<anonymous> (/Users/michael/Developer/kinandconscious/kindandconscious-nuxt3/node_modules/.pnpm/nuxt@3.0.0-rc.12_43do2nblp6dlbagpqygyz2j2ka/node_modules/nuxt/dist/app/components/layout.mjs:62:32)
    at renderComponentRoot (/Users/michael/Developer/kinandconscious/kindandconscious-nuxt3/node_modules/.pnpm/@vue+runtime-core@3.2.39/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:885:44)
    at renderComponentSubTree (/Users/michael/Developer/kinandconscious/kindandconscious-nuxt3/node_modules/.pnpm/@vue+server-renderer@3.2.39_vue@3.2.39/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:263:51)
    at renderComponentVNode (/Users/michael/Developer/kinandconscious/kindandconscious-nuxt3/node_modules/.pnpm/@vue+server-renderer@3.2.39_vue@3.2.39/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:188:16)
    at Module.ssrRenderComponent (/Users/michael/Developer/kinandconscious/kindandconscious-nuxt3/node_modules/.pnpm/@vue+server-renderer@3.2.39_vue@3.2.39/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:612:12)
    at _sfc_ssrRender (/Users/michael/Developer/kinandconscious/kindandconscious-nuxt3/app.vue:15:31)
    at renderComponentSubTree (/Users/michael/Developer/kinandconscious/kindandconscious-nuxt3/node_modules/.pnpm/@vue+server-renderer@3.2.39_vue@3.2.39/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:254:17)
    at renderComponentVNode (/Users/michael/Developer/kinandconscious/kindandconscious-nuxt3/node_modules/.pnpm/@vue+server-renderer@3.2.39_vue@3.2.39/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:188:16)
    at Module.ssrRenderComponent (/Users/michael/Developer/kinandconscious/kindandconscious-nuxt3/node_modules/.pnpm/@vue+server-renderer@3.2.39_vue@3.2.39/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:612:12)
    at default (/Users/michael/Developer/kinandconscious/kindandconscious-nuxt3/node_modules/.pnpm/nuxt@3.0.0-rc.12_43do2nblp6dlbagpqygyz2j2ka/node_modules/nuxt/dist/app/components/nuxt-root.vue:54:37)
    at Module.ssrRenderSuspense (/Users/michael/Developer/kinandconscious/kindandconscious-nuxt3/node_modules/.pnpm/@vue+server-renderer@3.2.39_vue@3.2.39/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:954:9)
    at _sfc_ssrRender (/Users/michael/Developer/kinandconscious/kindandconscious-nuxt3/node_modules/.pnpm/nuxt@3.0.0-rc.12_43do2nblp6dlbagpqygyz2j2ka/node_modules/nuxt/dist/app/components/nuxt-root.vue:49:25)
    at renderComponentSubTree (/Users/michael/Developer/kinandconscious/kindandconscious-nuxt3/node_modules/.pnpm/@vue+server-renderer@3.2.39_vue@3.2.39/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:254:17)
[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: Unhandled error during execution of render function 
  at <Anonymous >
[nitro] [dev] [unhandledRejection] TypeError: Cannot read properties of undefined (reading 'meta')
    at ReactiveEffect.fn (/Users/michael/Developer/kinandconscious/kindandconscious-nuxt3/node_modules/.pnpm/nuxt@3.0.0-rc.12_43do2nblp6dlbagpqygyz2j2ka/node_modules/nuxt/dist/app/components/layout.mjs:49:106)
    at ReactiveEffect.run (/Users/michael/Developer/kinandconscious/kindandconscious-nuxt3/node_modules/.pnpm/@vue+reactivity@3.2.39/node_modules/@vue/reactivity/dist/reactivity.cjs.js:168:25)
    at ComputedRefImpl.get value [as value] (/Users/michael/Developer/kinandconscious/kindandconscious-nuxt3/node_modules/.pnpm/@vue+reactivity@3.2.39/node_modules/@vue/reactivity/dist/reactivity.cjs.js:1139:39)
    at Proxy.<anonymous> (/Users/michael/Developer/kinandconscious/kindandconscious-nuxt3/node_modules/.pnpm/nuxt@3.0.0-rc.12_43do2nblp6dlbagpqygyz2j2ka/node_modules/nuxt/dist/app/components/layout.mjs:62:32)
    at renderComponentRoot (/Users/michael/Developer/kinandconscious/kindandconscious-nuxt3/node_modules/.pnpm/@vue+runtime-core@3.2.39/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:885:44)
    at renderComponentSubTree (/Users/michael/Developer/kinandconscious/kindandconscious-nuxt3/node_modules/.pnpm/@vue+server-renderer@3.2.39_vue@3.2.39/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:263:51)
    at renderComponentVNode (/Users/michael/Developer/kinandconscious/kindandconscious-nuxt3/node_modules/.pnpm/@vue+server-renderer@3.2.39_vue@3.2.39/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:188:16)
    at Module.ssrRenderComponent (/Users/michael/Developer/kinandconscious/kindandconscious-nuxt3/node_modules/.pnpm/@vue+server-renderer@3.2.39_vue@3.2.39/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:612:12)
    at _sfc_ssrRender (/Users/michael/Developer/kinandconscious/kindandconscious-nuxt3/app.vue:15:31)
    at renderComponentSubTree (/Users/michael/Developer/kinandconscious/kindandconscious-nuxt3/node_modules/.pnpm/@vue+server-renderer@3.2.39_vue@3.2.39/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:254:17)
    at renderComponentVNode (/Users/michael/Developer/kinandconscious/kindandconscious-nuxt3/node_modules/.pnpm/@vue+server-renderer@3.2.39_vue@3.2.39/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:188:16)
    at Module.ssrRenderComponent (/Users/michael/Developer/kinandconscious/kindandconscious-nuxt3/node_modules/.pnpm/@vue+server-renderer@3.2.39_vue@3.2.39/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:612:12)
    at default (/Users/michael/Developer/kinandconscious/kindandconscious-nuxt3/node_modules/.pnpm/nuxt@3.0.0-rc.12_43do2nblp6dlbagpqygyz2j2ka/node_modules/nuxt/dist/app/components/nuxt-root.vue:54:37)
    at Module.ssrRenderSuspense (/Users/michael/Developer/kinandconscious/kindandconscious-nuxt3/node_modules/.pnpm/@vue+server-renderer@3.2.39_vue@3.2.39/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:954:9)
    at _sfc_ssrRender (/Users/michael/Developer/kinandconscious/kindandconscious-nuxt3/node_modules/.pnpm/nuxt@3.0.0-rc.12_43do2nblp6dlbagpqygyz2j2ka/node_modules/nuxt/dist/app/components/nuxt-root.vue:49:25)
    at renderComponentSubTree (/Users/michael/Developer/kinandconscious/kindandconscious-nuxt3/node_modules/.pnpm/@vue+server-renderer@3.2.39_vue@3.2.39/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:254:17)
```
```

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/framework/issues/8897.
