### ISSUE TITLE
Server imports missing file extension

### ISSUE THREAD

**Issue by brtinney** [nuxt/framework#8937]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.0-rc.13`
- Nitro Version:    `0.6.1`
- Package Manager:  `yarn@3.1.1`
- Builder:          `vite`
- User Config:      `app`, `css`, `build`, `modules`, `publicRuntimeConfig`, `nitro`
- Runtime Modules:  `@pinia/nuxt@0.4.3`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-wvuvnj?file=app.vue,server%2Froutes%2Froute.ts

### Describe the bug

As per reported in #6652 (specifically, [my comment](https://github.com/nuxt/framework/issues/6652#issuecomment-1229216788)), importing `pinia` on the server results in an improperly set path.

### Additional context

This only occurs when `build` is used, and does not occur in `dev`.

### Logs

```shell
[nuxt] [request error] [unhandled] [500] Cannot find module '/home/projects/nuxt-starter-wvuvnj/.output/server/node_modules/pinia/dist/pinia' imported from /home/projects/nuxt-starter-wvuvnj/.output/server/chunks/route.mjs
  at InternalError.get (https://nuxt-starter-wvuvnj.w-credentialless.staticblitz.com/blitz.bba8d0a5a025db74852964077975228459d6d20b.js:6:292488)  
  at H3Error.get (./server/node_modules/h3/dist/index.mjs:134:22)  
  at normalizeError (./server/chunks/nitro/node-server.mjs:381:24)  
  at Object.errorhandler [as onError] (./server/chunks/nitro/node-server.mjs:400:57)  
  at toNodeHandle (./server/node_modules/h3/dist/index.mjs:787:27)  
  at async ufetch (./server/node_modules/unenv/runtime/fetch/index.mjs:28:17)  
  at async $fetchRaw2 (./server/node_modules/ohmyfetch/dist/shared/ohmyfetch.d1948a88.mjs:161:20)  
  at async setup (./server/chunks/app/server.mjs:1609:94)
```

**Comment by japhethkiptoo** [comment]
I am still stack on this issues
I am using joi validator on the server.
joi has dependencies like @hapi/hoek which doesn`t import well after build but works in production.

`import * as assert from @hapi/hoek/lib/assert`

nuxt version 3.0.0
