### ISSUE TITLE
head.addHeadObjs is not a function,vuetify3

### ISSUE THREAD

**Issue by ecfex** [nuxt/framework#8960]
### Environment

vuetify3.0.1，NuxtRC13，windows10

### Reproduction

NO

### Describe the bug

500，head.addHeadObjs is not a function。
at Object.install (http://localhost:3000/_nuxt/node_modules/vuetify/lib/composables/theme.mjs?v=fba58adb:191:12)
at Object.install (http://localhost:3000/_nuxt/node_modules/vuetify/lib/framework.mjs?v=fba58adb:43:11)
at Object.use (http://localhost:3000/_nuxt/node_modules/.vite/deps/vue.js?v=fba58adb:4690:18)
at http://localhost:3000/_nuxt/plugins/vuetify.js:13:18
at fn (http://localhost:3000/_nuxt/node_modules/nuxt/dist/app/nuxt.mjs?v=fba58adb:138:27)
at callWithNuxt (http://localhost:3000/_nuxt/node_modules/nuxt/dist/app/nuxt.mjs?v=fba58adb:143:12)
at applyPlugin (http://localhost:3000/_nuxt/node_modules/nuxt/dist/app/nuxt.mjs?v=fba58adb:89:29)
at applyPlugins (http://localhost:3000/_nuxt/node_modules/nuxt/dist/app/nuxt.mjs?v=fba58adb:98:11)
at async initApp (http://localhost:3000/_nuxt/F:/webApp/z/nuxt-app/node_modules/nuxt/dist/app/entry.mjs:41:7)

**Comment by harlan-zw** [comment]
Hey @ecfex 

Can you confirm which version of @vueuse/head you're using?

`npm why @vueuse/head`

There's a fix for this specific error in 1.0.6, so if you're using under that you should try updating the package. (Deleting node_modules & lock file and re-install should also work).

**Comment by ecfex** [comment]
The problem has been solved. Thank you very much。
