### ISSUE TITLE
Two more ways to trigger "nuxt instance unavailable", one inside a pinia store action, one inside a plugin

### ISSUE THREAD

**Issue by henk23** [nuxt/framework#9044]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.12.0`
- Nuxt Version:     `3.0.0-rc.14`, `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `css`, `modules`, `nitro`, `runtimeConfig`
- Runtime Modules:  `@pinia/nuxt@0.4.3`, `@pinia/nuxt@0.4.4`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/nuxt-starter-4tlygh?file=plugins%2F01.api.js,stores%2Fmain.js

### Describe the bug

There are two points in my code where I get "nuxt instance unavailable", probably because of calling `useNuxtApp` and `useRuntimeConfig` repeatedly in nested function calls.

One looks roughly like this:

```
// inside a plugin

// This works fine
nuxtApp.$log.info('Sending request...');

setTimeout(() => {

  // FIXME: nuxt instance unavailable
  nuxtApp.$log.info('Got response: Dummy data');

  resolve({ dummy: 'data' });
}, 2000);
```

The other one looks like this:

```
// inside a store

const { $api, $log } = useNuxtApp();

// This works fine
$log.info('Loading external data...');

const extData = await $api.getData();

// FIXME: nuxt instance unavailable
$log.info('External data loaded.', extData);
```

### Logs

```shell
Error inside the store looks like this:

[nuxt] [request error] [unhandled] [500] nuxt instance unavailable                                                10:27:46
  at useNuxtApp (./node_modules/nuxt/dist/app/nuxt.mjs:165:13)  
  at Module.useRuntimeConfig (./node_modules/nuxt/dist/app/nuxt.mjs:173:10)                                       10:27:40
  at log (./utils/logger.js:11:40)  
  at Object.info (./utils/logger.js:24:5)  
  at Proxy.loadExternalData (./stores/main.js:23:12)  
  at async eval (./plugins/02.init.server.js:11:95)  
  at async Object.callAsync (./node_modules/unctx/dist/index.mjs:72:16)  
  at async applyPlugin (./node_modules/nuxt/dist/app/nuxt.mjs:97:23)  
  at async Module.applyPlugins (./node_modules/nuxt/dist/app/nuxt.mjs:107:5)  
  at async createNuxtAppServer (./node_modules/nuxt/dist/app/entry.mjs:29:7)

Error inside the plugin looks like this:

[nitro] [dev] [uncaughtException] Error: nuxt instance unavailable                                                10:13:52
    at useNuxtApp (/home/projects/nuxt-starter-4tlygh/node_modules/nuxt/dist/app/nuxt.mjs:165:13)
    at Module.useRuntimeConfig (/home/projects/nuxt-starter-4tlygh/node_modules/nuxt/dist/app/nuxt.mjs:173:10)
    at log (/home/projects/nuxt-starter-4tlygh/utils/logger.js:11:40)                                             10:13:46
    at Object.info (/home/projects/nuxt-starter-4tlygh/utils/logger.js:24:5)
    at Timeout.eval [as _onTimeout] (/home/projects/nuxt-starter-4tlygh/plugins/01.api.js:12:24)
    at listOnTimeout (https://nuxt-starter-4tlygh.w-credentialless.staticblitz.com/blitz.bba8d0a5a025db74852964077975228459d6d20b.js:6:306541)
    at processTimers (https://nuxt-starter-4tlygh.w-credentialless.staticblitz.com/blitz.bba8d0a5a025db74852964077975228459d6d20b.js:6:307364)
    at https://nuxt-starter-4tlygh.w-credentialless.staticblitz.com/blitz.bba8d0a5a025db74852964077975228459d6d20b.js:15:258211
    at https://nuxt-starter-4tlygh.w-credentialless.staticblitz.com/blitz.bba8d0a5a025db74852964077975228459d6d20b.js:15:258522
```

**Comment by maxtomczyk** [comment]
I think you should use callWithNuxt in this cases

**Comment by Maxp777** [comment]
why not store nuxt context with reflect-metadata like NestJs or AsyncLocalStorage like mikro-orm store needed data.
why is not possible in every place to get context?

**Comment by henk23** [comment]
> I think you should use callWithNuxt in this cases

Hey @maxtomczyk, thanks for the suggestion. Where/how would I use that? Can't find anything in the docs.

**Comment by henk23** [comment]
Still an issue with v3.0.0 "stable". :/

Using `callWithNuxt` does not work whatsoever.

**Comment by Maxp777** [comment]
> Still an issue with v3.0.0 "stable". :/
> 
> Using `callWithNuxt` does not work whatsoever.

don't know, all modules with and without plugins work some how

**Comment by henk23** [comment]
Okay, seems like you cannot just use `useRuntimeConfig()` whenever you need it, which is a little sad, but okay.

Fixed it like this: 

    // plugins/00.log.js
    
    export default defineNuxtPlugin(async (nuxtApp) => {
      const config = useRuntimeConfig();
      logger.init(config);
    
      nuxtApp.provide('log', logger);
    });

**Comment by agracia-foticos** [comment]
```
[[nitro] [dev] [unhandledRejection] Error: nuxt instance unavailable
    at Module.useNuxtApp (/home/business/var/www/project/node_modules/nuxt/dist/app/nuxt.mjs:165:13)
    at Module.useRequestHeaders (/home/business/var/www/project/node_modules/nuxt/dist/app/composables/ssr.mjs:7:41)
    at parseParams (/composables/useFetch.ts:21:21)
    at Module.useFetch (/composables/useFetch.ts:5:53)
    at __vite_ssr_import_5__.watch.deep (/home/business/var/www/project/src/pages/t/[slug].vue:141:62)
    at callWithErrorHandling (/home/business/var/www/project/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:157:22)
    at callWithAsyncErrorHandling (/home/business/var/www/project/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:166:21)
    at job (/home/business/var/www/project/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:1786:17)
    at callWithErrorHandling (/home/business/var/www/project/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:157:36)
    at flushJobs (/home/business/var/www/project/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:384:17) {stack: 'Error: nuxt instance unavailable
    at Modul…runtime-core/dist/runtime-core.cjs.js:384:17)', message: 'nuxt instance unavailable'}
```
Another way.

when I launch a web crawl, after X requests, it throws me this error

options.headers = useRequestHeaders(['cookie']); // to pass the cookie from

**Comment by daniluk4000** [comment]
I've been able to trigger this in Nuxt Bridge (Nuxt 2) in plugin because of multiple awaits.

This is not script setup, this is a plugin. How can context be lost after awaits in plugin?

@danielroe do you have any plans to deal with this? This is breaking change even for Nuxt 2. I simply can't move my legacy code and I have no clue what to do here. I guess I'll have to rollback everything now. 

Previous case: 
- I have plugin with context
- I have Vuex
- I have injected methods
- I have context everywhere here and can use Vuex and injected methods with as many awaits as I want

New case:
- If I use single await it dies even if it's not setup function

**Comment by danielroe** [comment]
@daniluk4000 Are you migrating to Nuxt 3 or to Nuxt Bridge? You can see more in https://github.com/nuxt/framework/issues/6996 and in https://github.com/nuxt/framework/issues/5740#issuecomment-1229197529, including a workaround that should _probably_ help in your situation.

**Comment by danielroe** [comment]
I'm closing this in favour of https://github.com/nuxt/framework/issues/6996.

**Comment by henk23** [comment]
Thanks @danielroe, https://github.com/nuxt/framework/issues/5740#issuecomment-1229197529 explains it very well :) This comment should be much more prominent, maybe add a link in the docs until it's properly documented.
