### ISSUE TITLE
 ERROR  [nuxt:imports-transform] [unimport] failed to find "useMeta" imported from "#imports"

### ISSUE THREAD

**Issue by mlsjla** [nuxt/framework#9105]
### Environment

```


 WARN  Using experimental payload extraction for full-static output. You can opt-out by setting experimental.payloadExtraction to false.

ℹ Using Tailwind CSS from ~/assets/css/tailwind.css              nuxt:tailwindcss 16:45:07

 ERROR  [nuxt:imports-transform] [unimport] failed to find "useMeta" imported from "#imports"
file: /Users/mac/.webcode/gin-nuxt/web/node_modules/@vueuse/nuxt/ssr-plugin.mjs


 ERROR  [unimport] failed to find "useMeta" imported from "#imports"              16:45:13

  at node_modules/unimport/dist/shared/unimport.d5d80c71.mjs:782:17
  at Array.forEach (<anonymous>)
  at node_modules/unimport/dist/shared/unimport.d5d80c71.mjs:779:44
  at Array.forEach (<anonymous>)
  at detectImports (node_modules/unimport/dist/shared/unimport.d5d80c71.mjs:777:20)
  at async injectImports (node_modules/unimport/dist/shared/unimport.d5d80c71.mjs:804:44)
  at async Object.transform (node_modules/nuxt/dist/index.mjs:1107:21)
  at async transform (node_modules/rollup/dist/es/shared/rollup.js:21734:16)
  at async ModuleLoader.addModuleSource (node_modules/rollup/dist/es/shared/rollup.js:21959:30)



```

### Reproduction

"nuxt": "^3.0.0",

### Describe the bug

when upgrade to "nuxt": "^3.0.0"

npm run generate  ... show error..

**Comment by shtse8** [comment]
I have the same issue.

**Comment by Vincebe** [comment]
Same issue

**Comment by isimmons** [comment]
I believe useMeta was replaced with useHead
[SEO and Meta](https://nuxt.com/docs/getting-started/seo-meta/)

Also a heads up, useBody renamed to readBody and useCookies renamed to parseCookies in case you run into those two.

**Comment by Vincebe** [comment]
Correct @isimmons 
https://github.com/vueuse/vueuse/pull/2449

**Comment by danielroe** [comment]
Closing as this is an upstream issue.
