### ISSUE TITLE
installModule doesn't work with nuxt 2 modules

### ISSUE THREAD

**Issue by dkrdj8989** [nuxt/framework#9115]

**Comment by SchnapsterDog** [comment]
It happens on both  Node Versions:
-16.13.0
-14.17.3

**Comment by oikewll** [comment]
I remove "@nuxt/tailwindcss" , and follow Tailwind official website guide to resolve this issue:

https://tailwindcss.com/docs/guides/nuxtjs

**Comment by SchnapsterDog** [comment]
> I remove "@nuxtjs/tailwindcss" , and follow Tailwind official website guide to resolved this issue:
> 
> https://tailwindcss.com/docs/guides/nuxtjs

It is working only that way atm

**Comment by pencilcheck** [comment]
I revert my yarn.lock file and it worked, not sure what happened

**Comment by chamyeongdo** [comment]
temporarily solved by using [overrides](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides) property.

npm version >= 8.3

```
// package.json
...
  "overrides": {
    "@nuxtjs/tailwindcss": {
      "@nuxt/kit": "3.0.0-rc.13"
    }
  },
```

```
> npm list @nuxt/kit
└─┬ @nuxtjs/tailwindcss@5.3.5
  └── @nuxt/kit@3.0.0-rc.13 overridden
  ```

**Comment by anime-shed** [comment]
### Environment
Operating System: Windows
Node Version: v18.12.1
Nuxt Version: 2.15.8
Nitro Version: -
Package Manager: npm@8.19.2, yarn@1.22.19
Builder: nxut2(webpack )
User Config: -
Runtime Modules: -
Build Modules: -


Still facing the same issue even with overriding as suggested by @chamyeongdo 
```
dashboard@1.3.9 C:\Users\sam\source\repos\fa_nuxtjs_sfa_dashboard
├─┬ @nuxtjs/tailwindcss@5.3.5
│ └── @nuxt/kit@3.0.0 overridden
└─┬ nuxt-icon@0.1.7
  └── @nuxt/kit@3.0.0 deduped
```

```
yarn run v1.22.19
$ cross-env NUXT_ENV_API_URL=https://dashboard.azurewebsites.net nuxt
i Using Tailwind CSS from ~/assets/css/tailwind.css                                                               nuxt:tailwindcss 10:20:19

 FATAL  Cannot destructure property 'nuxt' of 'this' as it is undefined.                                                           10:20:19  

  at postcss8Module (node_modules\@nuxt\postcss8\dist\index.js:15:10)
  at installModule (/C:/Users/sam/source/repos/dashboard/node_modules/@nuxt/kit/dist/index.mjs:416:9)
  at async setup (/C:/Users/sam/source/repos/dashboard/node_modules/@nuxtjs/tailwindcss/dist/module.mjs:186:7)
  at async ModuleContainer.normalizedModule (/C:/Users/sam/source/repos/dashboard/node_modules/@nuxt/kit/dist/index.mjs:167:5)
  at async ModuleContainer.addModule (node_modules\@nuxt\core\dist\core.js:239:20)
  at async ModuleContainer.ready (node_modules\@nuxt\core\dist\core.js:51:7)
  at async Nuxt._init (node_modules\@nuxt\core\dist\core.js:478:5)


   ╭─────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                 │
   │   ✖ Nuxt Fatal Error                                                            │
   │                                                                                 │
   │   TypeError: Cannot destructure property 'nuxt' of 'this' as it is undefined.   │
   │                                                                                 │
   ╰─────────────────────────────────────────────────────────────────────────────────╯

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by anime-shed** [comment]
### Environment
Operating System: Windows
Node Version: v18.12.1
Nuxt Version: 2.15.8
Nitro Version: -
Package Manager: npm@8.19.2, yarn@1.22.19
Builder: nxut2(webpack )
User Config: -
Runtime Modules: -
Build Modules: -


Still facing the same issue even with overriding as suggested by @chamyeongdo 
```
dashboard@1.3.9 C:\Users\sam\source\repos\dashboard
├─┬ @nuxtjs/tailwindcss@5.3.5
│ └── @nuxt/kit@3.0.0 overridden
└─┬ nuxt-icon@0.1.7
  └── @nuxt/kit@3.0.0 deduped
```

```
yarn run v1.22.19
$ cross-env NUXT_ENV_API_URL=https://dashboard.azurewebsites.net nuxt
i Using Tailwind CSS from ~/assets/css/tailwind.css                                                               nuxt:tailwindcss 10:20:19

 FATAL  Cannot destructure property 'nuxt' of 'this' as it is undefined.                                                           10:20:19  

  at postcss8Module (node_modules\@nuxt\postcss8\dist\index.js:15:10)
  at installModule (/C:/Users/sam/source/repos/dashboard/node_modules/@nuxt/kit/dist/index.mjs:416:9)
  at async setup (/C:/Users/sam/source/repos/dashboard/node_modules/@nuxtjs/tailwindcss/dist/module.mjs:186:7)
  at async ModuleContainer.normalizedModule (/C:/Users/sam/source/repos/dashboard/node_modules/@nuxt/kit/dist/index.mjs:167:5)
  at async ModuleContainer.addModule (node_modules\@nuxt\core\dist\core.js:239:20)
  at async ModuleContainer.ready (node_modules\@nuxt\core\dist\core.js:51:7)
  at async Nuxt._init (node_modules\@nuxt\core\dist\core.js:478:5)


   ╭─────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                 │
   │   ✖ Nuxt Fatal Error                                                            │
   │                                                                                 │
   │   TypeError: Cannot destructure property 'nuxt' of 'this' as it is undefined.   │
   │                                                                                 │
   ╰─────────────────────────────────────────────────────────────────────────────────╯

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by asadullakkh** [comment]
I had same issue. I solved this by updating tailwindcss version

https://tailwindcss.com/docs/guides/nuxtjs

**Comment by anime-shed** [comment]
> I remove "@nuxtjs/tailwindcss" , and follow Tailwind official website guide to resolved this issue:
> 
> https://tailwindcss.com/docs/guides/nuxtjs

Does not work for me, still have a similar error.

**Comment by jamaltun** [comment]
Same error ! And none of the solutions written above fixed the problem.

**Comment by CSalih** [comment]
for yarn you can override the package as shown:
```json
  "resolutions": {
    "@nuxt/kit": "3.0.0-rc.13"
  }
```

**Comment by anime-shed** [comment]
@CSalih can you tell me what npm version are you using?

**Comment by CSalih** [comment]
@anime-shed  here are my versions:

Operating System: Ubuntu
Node Version: v16.15.1
Nuxt Version: v2.15.8
Package Manager: yarn 1.22.19

I do have npm with version 8.9.0 installed but i do not use it.

**Comment by akinoriakatsuka** [comment]
Removing package-lock.json file and redoing `npm run dev` works for me. 

like
> I revert my yarn.lock file and it worked, not sure what happened

**Comment by mamiline6** [comment]
I have the same problem, 5 days ago. 

MacOS: Monterey 12.6
Node Version: v14.15.4
Nuxt Version: v2.15.8

In my case, delete nuxt.config.js file, redoing `npm run dev`, and works!

But, i get the following message:
WARN   You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.

**Comment by calebeaires** [comment]
I had the same problem using Vercel


```


warning vscode-languageclient@7.0.0: The engine "vscode" appears to be invalid.
--
22:16:32.135 | [3/4] Linking dependencies...
22:16:32.137 | warning "@nuxtjs/tailwindcss > @nuxt/postcss8 > css-loader@5.2.7" has unmet peer dependency "webpack@^4.27.0 \|\| ^5.0.0".
22:16:32.138 | warning "@nuxtjs/tailwindcss > @nuxt/postcss8 > postcss-loader@4.3.0" has unmet peer dependency "webpack@^4.0.0 \|\| ^5.0.0".
22:16:32.139 | warning "@unocss/nuxt > @unocss/vite@0.46.5" has unmet peer dependency "vite@^2.9.0 \|\| ^3.0.0-0".
22:16:32.140 | warning "@unocss/nuxt > @unocss/webpack@0.46.5" has unmet peer dependency "webpack@^4 \|\| ^5".
22:16:32.140 | warning "nuxt-windicss > vite-plugin-windicss@1.8.8" has unmet peer dependency "vite@^2.0.1 \|\| ^3.0.0".
22:16:37.005 | [4/4] Building fresh packages...
22:16:37.249 | success Saved lockfile.
22:16:37.253 | $ nuxt prepare
22:16:37.355 | [log] Nuxi 3.0.0
22:16:38.499 | [info] [nuxt:tailwindcss] Using default Tailwind CSS file from runtime/tailwind.css
22:16:38.574 | [error] Cannot destructure property 'nuxt' of 'this' as it is undefined.
22:16:38.574 | at webVitalsModule (node_modules/@nuxtjs/web-vitals/dist/index.js:47:11)
22:16:38.574 | at installModule (node_modules/@nuxt/kit/dist/index.mjs:416:9)
22:16:38.575 | at async initNuxt (node_modules/nuxt/dist/index.mjs:1825:7)
22:16:38.575 | at async loadNuxt (node_modules/nuxt/dist/index.mjs:1857:5)
22:16:38.575 | at async loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:493:19)
22:16:38.575 | at async Object.invoke (node_modules/nuxi/dist/chunks/prepare.mjs:30:18)
22:16:38.575 | at async _main (node_modules/nuxi/dist/cli.mjs:50:20)
22:16:38.593 | error Command failed with exit code 1.
22:16:38.594 | info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
22:16:38.637 | Error: Command "yarn install" exited with 1



```

**Comment by pencilcheck** [comment]
> for yarn you can override the package as shown:
> 
> ```
> // package.json
> ...
>   "resolutions": {
>     "@nuxt/kit": "3.0.0-rc.13"
>   }
> ...
> ```

If  you are using monorepo, add this into your root's package.json and that will solve it.

This is a well known issue with yarn 1.x
https://github.com/yarnpkg/yarn/issues/5039

**Comment by njiels** [comment]
I tried all options that have been suggested here, now i get another error :

`node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at module.exports (/Users/nielsvanleenen/Documents/Opdrachten/Hidde/hidde-tuinte/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/nielsvanleenen/Documents/Opdrachten/Hidde/hidde-tuinte/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/nielsvanleenen/Documents/Opdrachten/Hidde/hidde-tuinte/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/nielsvanleenen/Documents/Opdrachten/Hidde/hidde-tuinte/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/nielsvanleenen/Documents/Opdrachten/Hidde/hidde-tuinte/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/nielsvanleenen/Documents/Opdrachten/Hidde/hidde-tuinte/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/nielsvanleenen/Documents/Opdrachten/Hidde/hidde-tuinte/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/Users/nielsvanleenen/Documents/Opdrachten/Hidde/hidde-tuinte/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/nielsvanleenen/Documents/Opdrachten/Hidde/hidde-tuinte/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/nielsvanleenen/Documents/Opdrachten/Hidde/hidde-tuinte/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /Users/nielsvanleenen/Documents/Opdrachten/Hidde/hidde-tuinte/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}`

**Comment by njiels** [comment]
I tried all options that have been suggested here, now i get another error :

`node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at module.exports (/Users/nielsvanleenen/Documents/Opdrachten/Hidde/hidde-tuinte/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/nielsvanleenen/Documents/Opdrachten/Hidde/hidde-tuinte/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/nielsvanleenen/Documents/Opdrachten/Hidde/hidde-tuinte/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/nielsvanleenen/Documents/Opdrachten/Hidde/hidde-tuinte/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/nielsvanleenen/Documents/Opdrachten/Hidde/hidde-tuinte/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/nielsvanleenen/Documents/Opdrachten/Hidde/hidde-tuinte/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/nielsvanleenen/Documents/Opdrachten/Hidde/hidde-tuinte/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/Users/nielsvanleenen/Documents/Opdrachten/Hidde/hidde-tuinte/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/nielsvanleenen/Documents/Opdrachten/Hidde/hidde-tuinte/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/nielsvanleenen/Documents/Opdrachten/Hidde/hidde-tuinte/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /Users/nielsvanleenen/Documents/Opdrachten/Hidde/hidde-tuinte/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v19.2.0
error Command failed with exit code 1.`

**Comment by CSalih** [comment]
@njiels this is because you are using Node 17+, there is a [issue](https://github.com/webpack/webpack/issues/14532) with openssl and webpack. 
Either try using it with ’NODE_OPTIONS=--openssl-legacy-provider’ or use a Node Version less than 17.

**Comment by calebeaires** [comment]
Hey folks, 

My site is on Vercel. I just turn of analytics and the site come back.

**Comment by fifle** [comment]
I'll just remind everyone to delete `@nuxtjs/tailwindcss` mentions from nuxt.config.js after Tailwind package installation

**Comment by damircast** [comment]
> I'll just remind everyone to delete `@nuxtjs/tailwindcss` mentions from nuxt.config.js after Tailwind package installation.

This worked for me. I did simply what you said: I removed  `@nuxtjs/tailwindcss` from the `nuxt.config.js` file. Thanks
