### ISSUE TITLE
unplugin-icons - error

### ISSUE THREAD

**Issue by agracia-foticos** [nuxt/framework#9123]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v18.11.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `srcDir`, `modules`, `compilerOptions`, `vue`, `vite`, `schemaOrg`, `telemetry`, `algolia`, `head`, `auth`, `css`, `build`, `runtimeConfig`
- Runtime Modules:  `genesis-design-system/nuxt`, `@nuxtjs/tailwindcss@6.1.3`, `@nuxtjs/algolia@1.2.0`, `@nuxtjs-alt/auth@2.1.5`, `@nuxtjs-alt/http@1.5.0`, `@nuxtjs/device@3.0.0`, `@nuxtjs/partytown@1.2.2`, `@vueuse/nuxt@9.5.0`, `nuxt-schema-org@1.1.0-beta.6`, `unplugin-icons/nuxt`, `@pinia/nuxt@0.4.4`, `@nuxtjs/i18n@8.0.0-beta.4`
- Build Modules:    `-`
------------------------------

### Reproduction

Nuxi 3.0.0
Nuxt 3.0.0 with Nitro 1.0.0

  > Local:    http://localhost:3000/ 
  > Network:  http://172.17.0.2:3000/

ℹ Using default Tailwind CSS file from runtime/tailwind.css

 ERROR  Cannot start nuxt:  Cannot read properties of undefined (reading 'nuxt')

  at nuxt_default (node_modules/unplugin-icons/dist/nuxt.js:9:24)
  at installModule (node_modules/@nuxt/kit/dist/index.mjs:416:9)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:1825:7)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6779:9)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6840:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:50:20)

### Describe the bug

I have upgraded from RC14 to Stable 3.0.0 and it is giving me errors when starting the server

### Logs

```shell
Nuxi 3.0.0
Nuxt 3.0.0 with Nitro 1.0.0

  > Local:    http://localhost:3000/ 
  > Network:  http://172.17.0.2:3000/

ℹ Using default Tailwind CSS file from runtime/tailwind.css

 ERROR  Cannot start nuxt:  Cannot read properties of undefined (reading 'nuxt')

  at nuxt_default (node_modules/unplugin-icons/dist/nuxt.js:9:24)
  at installModule (node_modules/@nuxt/kit/dist/index.mjs:416:9)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:1825:7)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6779:9)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6840:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:50:20)
```

**Comment by danielroe** [comment]
It's an upstream issue. You can track this PR: https://github.com/antfu/unplugin-icons/pull/250.
