### ISSUE TITLE
Cannot start nuxt:  Cannot find module '@intlify/vue-i18n-bridge/lib/index.mjs'

### ISSUE THREAD

**Issue by agracia-foticos** [nuxt/framework#9127]
### Environment

- Operating System: `Linux`
- Node Version:     `v18.11.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `srcDir`, `modules`, `compilerOptions`, `vue`, `vite`, `schemaOrg`, `telemetry`, `algolia`, `head`, `auth`, `css`, `build`, `runtimeConfig`
- Runtime Modules:  `genesis-design-system/nuxt`, `@nuxtjs/tailwindcss@6.1.3`, `@nuxtjs/algolia@1.2.0`, `@nuxtjs-alt/auth@2.1.5`, `@nuxtjs-alt/http@1.5.0`, `@nuxtjs/device@3.0.0`, `@nuxtjs/partytown@1.2.2`, `@vueuse/nuxt@9.5.0`, `nuxt-schema-org@1.1.0-beta.6`, `@pinia/nuxt@0.4.4`, `@nuxtjs/i18n@8.0.0-beta.4`
- Build Modules:    `-`

### Reproduction

I have upgraded from version RC14 to 3.0.0 STABLE and the server does not start

### Describe the bug

Nuxi 3.0.0
Nuxt 3.0.0 with Nitro 1.0.0

  > Local:    http://localhost:3000/ 
  > Network:  http://172.17.0.2:3000/

ℹ Using default Tailwind CSS file from runtime/tailwind.css

 ERROR  Cannot start nuxt:  Cannot find module '@intlify/vue-i18n-bridge/lib/index.mjs'
Require stack:
- /var/www/project/index.js

  Require stack:
  - index.js
  at Function.Module._resolveFilename (node:internal/modules/cjs/loader:985:15)
  at Function.resolve (node:internal/modules/cjs/helpers:109:19)
  at Function._resolve [as resolve] (node_modules/jiti/dist/jiti.js:1:243257)
  at resolveModule (node_modules/@nuxt/kit/dist/index.mjs:260:29)
  at setupAlias (node_modules/@nuxtjs/i18n/dist/module.mjs:48:52)
  at setup (node_modules/@nuxtjs/i18n/dist/module.mjs:641:11)
  at async normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:167:5)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:416:3)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:1825:7)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6779:9)

### Logs

```shell
Nuxi 3.0.0
Nuxt 3.0.0 with Nitro 1.0.0

  > Local:    http://localhost:3000/ 
  > Network:  http://172.17.0.2:3000/

ℹ Using default Tailwind CSS file from runtime/tailwind.css

 ERROR  Cannot start nuxt:  Cannot find module '@intlify/vue-i18n-bridge/lib/index.mjs'
Require stack:
- /var/www/project/index.js

  Require stack:
  - index.js
  at Function.Module._resolveFilename (node:internal/modules/cjs/loader:985:15)
  at Function.resolve (node:internal/modules/cjs/helpers:109:19)
  at Function._resolve [as resolve] (node_modules/jiti/dist/jiti.js:1:243257)
  at resolveModule (node_modules/@nuxt/kit/dist/index.mjs:260:29)
  at setupAlias (node_modules/@nuxtjs/i18n/dist/module.mjs:48:52)
  at setup (node_modules/@nuxtjs/i18n/dist/module.mjs:641:11)
  at async normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:167:5)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:416:3)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:1825:7)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6779:9)
```

**Comment by danielroe** [comment]
Would you either provide a reproduction or raise this in the `@intlify/vue-i18n-bridge` repository?

**Comment by manniL** [comment]
Track in https://github.com/nuxt-community/i18n-module/issues/1640

**Comment by agracia-foticos** [comment]
This could be a scenario, however it is giving me an error regarding defu

https://stackblitz.com/edit/nuxt-starter-f6cpnf
