### ISSUE TITLE
Module '"nuxt"' has no exported member 'defineNuxtConfig'.

### ISSUE THREAD

**Issue by donmb1** [nuxt/framework#9170]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.4.2`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@7.18.1`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Should be obvious. Error occurs after installing nuxt 3
Here is my package:

```
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev --hostname 'localhost' --port 8083",
    "start": "node .output/server/index.mjs",
    "generate": "nuxt generate",
    "preview": "nuxt preview"
  },
  "devDependencies": {
    "@nuxtjs/vuetify": "^1.12.3",
    "nuxt": "^3.0.0"
  },
  "dependencies": {
    "@mdi/font": "^7.0.96",
    "@nuxt/types": "^2.15.8",
    "@pinia/nuxt": "^0.4.4",
    "@types/leaflet": "^1.7.11",
    "@types/luxon": "^2.3.2",
    "@vuepic/vue-datepicker": "^3.3.0",
    "axios": "^0.27.2",
    "click-outside-vue3": "^4.0.1",
    "leaflet": "^1.8.0",
    "luxon": "^2.4.0",
    "pinia": "^2.0.24",
    "sass": "^1.56.1",
    "vue-advanced-cropper": "^2.8.3",
    "vue-dndrop": "^1.2.13",
    "vue-waypoint": "^4.2.1",
    "vuetify": "^3.0.0"
  }
}
```

### Describe the bug

![Screenshot 2022-11-18 at 16 03 04](https://user-images.githubusercontent.com/3296757/202735132-a99ce798-ad2e-4569-86f6-d8fa257c6244.png)

`nuxt.config.ts` 

```
import { defineNuxtConfig } from 'nuxt'

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  css: ['vuetify/lib/styles/main.sass', '@mdi/font/css/materialdesignicons.min.css', '@/assets/sass/main.sass', 'leaflet/dist/leaflet.css'],
  build: {
    transpile: ['vuetify'],
  },
  serverMiddleware: [
    '~/server-middleware/https-redirect'
  ],
  vite: {
    define: {
      'process.env.DEBUG': false,
    },
  },
  modules: [
    '@pinia/nuxt'
  ],
  runtimeConfig: {
    public: {
      API_BASE_URL: process.env.API_BASE_URL,
      PUBLIC_API_USERNAME: process.env.PUBLIC_API_USERNAME,
      PUBLIC_API_PASSWORD: process.env.PUBLIC_API_PASSWORD,
    }
  },
  ssr: false, // Disable server side rendering
  meta: {
    title: 'Smart Wendeler Land',
  }
})

```

### Logs

```shell
ERROR  Cannot start nuxt:  (0 , _nuxt.defineNuxtConfig) is not a function                                                                                                                                 16:03:58

  at nuxt.config.ts:4:43
  at Object.jiti (node_modules/jiti/dist/jiti.js:1:247502)
  at resolveConfig (node_modules/c12/dist/index.mjs:221:24)
  at loadConfig (node_modules/c12/dist/index.mjs:104:40)
  at async loadNuxtConfig (node_modules/@nuxt/kit/dist/index.mjs:446:18)
  at async loadNuxt (node_modules/nuxt/dist/index.mjs:1835:19)
  at async loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:493:19)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6768:23)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6840:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:50:20)

```
```

**Comment by agracia-foticos** [comment]
same problem!

**Comment by tkofh** [comment]
As described [here](https://nuxt.com/docs/guide/directory-structure/nuxt.config#nuxt-config-file), if you need/want to manually import the function it should be from `nuxt/config`:

```typescript
import { defineNuxtConfig } from 'nuxt/config'

export default defineNuxtConfig({
  // My Nuxt config
})
```

**Comment by donmb1** [comment]
@tkofh that fixed but now `serverMiddleware` is broke

<img width="789" alt="Screenshot 2022-11-18 at 17 03 42" src="https://user-images.githubusercontent.com/3296757/202748641-ce12a008-98b8-4b57-b82f-ac74762466db.png">

**Comment by tkofh** [comment]
Not broken, that message tells you that `serverMiddleware` is not a property of `NuxtConfig`. Check out the [server directory documentation](https://nuxt.com/docs/guide/directory-structure/server) for how to work with server middleware, and the [`nuxt.config.ts` documentation](https://nuxt.com/docs/api/configuration/nuxt-config) for what properties are allowed in your config.

**Comment by danielroe** [comment]
We removed some deprecated properties in the final release. Check the release notes if you are migrating from rc14.
