### ISSUE TITLE
Error: Nuxt Instance unavailable - when accessing env variables with useRuntimeConfig() 

### ISSUE THREAD

**Issue by SPH73** [nuxt/framework#9174]
### Environment

- Operating System: `Darwin`
- Node Version:     `v14.20.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@9.1.1`
- Builder:          `vite`
- User Config:      `modules`, `tailwindcss`, `css`, `runtimeConfig`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.1.3`
- Build Modules:    `-`

### Reproduction

```
//package.json
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxtjs/google-fonts": "^3.0.0-1",
    "@nuxtjs/tailwindcss": "^6.1.3",
    "@tailwindcss/typography": "^0.5.8",
    "nuxt": "3.0.0"
  },
  "dependencies": {
    "airtable": "^0.11.5"
  }
}
```

```
// nuxt.config.ts
// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
// { ... }
   runtimeConfig: {
    public: {
      atApikey: process.env.NUXT_AT_API_KEY,
      atEndpointUrl: 'https://api.airtable.com',
      atBaseId: process.env.NUXT_AT_BASE_ID,
    }
  }
})

```
```
// ./composables/airtable.js
import Airtable from "airtable";
const atApiKey = useRuntimeConfig();
const base = new Airtable({ apiKey: atApiKey }).base(
    'appU8bucIO9xC3CCS',
);
```

### Describe the bug

(Apologies in advance if there is a lack of correct terminology) 

I need to pull data from an Airtable base. The apiKey is stored in a `.env` and defined in the `runtimeConfig` option of the `nuxt.config.ts`  file as shown above. 

In the composable file and the page importing the composable file, I get the data initially but the moment I refresh the browser I get the Nuxt instance unavailable error.

I am extremely new to Nuxt in general so I have had some confusion around how to get access to the runtimeConfig but as I did initially get the data I believe I was on the right path.

Testing with the apikey hardcoded directly into the Airtable config know the composable causes no problems on refresh.

What am I missing? 

TIA

### Additional context

Testing with the apikey hardcoded directly into the Airtable config in the composable causes no errors on refresh.

What am I missing? 

TIA

### Logs

```shell
Error: nuxt instance unavailable                                                                 17:35:10
    at useNuxtApp (/Users/sueholder/Development/Nuxt3/absoluteSport/webapp/node_modules/nuxt/dist/app/nuxt.mjs:165:13)
    at Module.useRuntimeConfig (/Users/sueholder/Development/Nuxt3/absoluteSport/webapp/node_modules/nuxt/dist/app/nuxt.mjs:173:10)
    at /Users/sueholder/Development/Nuxt3/absoluteSport/webapp/composables/getParties.js:5:38
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ViteNodeRunner.directRequest (file:///Users/sueholder/Development/Nuxt3/absoluteSport/webapp/node_modules/vite-node/dist/client.mjs:270:5)
    at async ViteNodeRunner.cachedRequest (file:///Users/sueholder/Development/Nuxt3/absoluteSport/webapp/node_modules/vite-node/dist/client.mjs:146:12)
    at async request (file:///Users/sueholder/Development/Nuxt3/absoluteSport/webapp/node_modules/vite-node/dist/client.mjs:169:16)
    at async /Users/sueholder/Development/Nuxt3/absoluteSport/webapp/pages/index.vue:3:31
    at async ViteNodeRunner.directRequest (file:///Users/sueholder/Development/Nuxt3/absoluteSport/webapp/node_modules/vite-node/dist/client.mjs:270:5)
    at async ViteNodeRunner.cachedRequest (file:///Users/sueholder/Development/Nuxt3/absoluteSport/webapp/node_modules/vite-node/dist/client.mjs:146:12)
```

**Comment by ianfortier** [comment]
<script setup> <-----
vs 
<script>

**Comment by SPH73** [comment]
> <script setup> <----- vs <script>

I am sorry, I am not following because I am not using a script tag in the composable?

**Comment by wadaahmad** [comment]
> useRuntimeConfig

you can pass nuxt instance inside the function, i'm use axios and working fine 
```
import axios from 'axios'
export function $axios() {
    const config = useRuntimeConfig()
    let $axios = axios.create({ baseURL: config.public.url })
    return $axios
}
```

**Comment by SPH73** [comment]
> > useRuntimeConfig
> 
> you can pass nuxt instance inside the function, i'm use axios and working fine
> 
> ```
> Thanks for your reply, I have moved it inside the function and it doesn't give a nuxt instance error, HOWEVER,  now it's evident that I can get any of the runtime configs EXCEPT the atApiKey even though it is public (I know it shouldn't be I still need to figure out how to use private env vars).

The difference here is that outside the function, it reads the atApiKey initially and then errors on page refresh while inside the function it doesn't read that one config at all so I change the variable name to TOKEN and now it reads it so I understand now that its Nuxt being very clever about the name because an apikey shouldn't be public.
