### ISSUE TITLE
Chrome extension minifist v3 not working

### ISSUE THREAD

**Issue by terwer** [nuxt/framework#9184]
### Environment

版本 107.0.5304.110（正式版本） (x86_64)

### Reproduction

1. add a minifist v3 file for chrome extension

2. use `nuxt generate` build static output, and debug using chrome

### Describe the bug

When I use static output as a chrome extension, it say error:

```
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-vSsBu6K77ua/ICL6OULrwKrxxjjCzkaZglpc94PteuE='), or a nonce ('nonce-...') is required to enable inline execution.

index.html:6 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-vSsBu6K77ua/ICL6OULrwKrxxjjCzkaZglpc94PteuE='), or a nonce ('nonce-...') is required to enable inline execution.

3entry.c5f4a5ff.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'baseURL')
    at oh (entry.c5f4a5ff.js:1:74799)
    at entry.c5f4a5ff.js:27:53299
```

### Logs

```shell
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-vSsBu6K77ua/ICL6OULrwKrxxjjCzkaZglpc94PteuE='), or a nonce ('nonce-...') is required to enable inline execution.

index.html:6 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-vSsBu6K77ua/ICL6OULrwKrxxjjCzkaZglpc94PteuE='), or a nonce ('nonce-...') is required to enable inline execution.

3entry.c5f4a5ff.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'baseURL')
    at oh (entry.c5f4a5ff.js:1:74799)
    at entry.c5f4a5ff.js:27:53299
```

**Comment by danielroe** [comment]
We can probably track in https://github.com/nuxt/framework/issues/591.
