### ISSUE TITLE
Failed to create nuxt3 project

### ISSUE THREAD

**Issue by kangyanbin** [nuxt/framework#9244]
### Environment

window10  node v18.12.1  npx 9.1.2

### Reproduction

npx nuxi init nuxt-app

### Describe the bug

 ERROR  (node:2728) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

 ERROR  Failed to download template from registry: fetch failed

  at /C:/Users/Administrator/AppData/Local/npm-cache/_npx/a95e0f536cf9a537/node_modules/nuxi/dist/chunks/init.mjs:15133:11
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async downloadTemplate (/C:/Users/Administrator/AppData/Local/npm-cache/_npx/a95e0f536cf9a537/node_modules/nuxi/dist/chunks/init.mjs:15132:20)
  at async Object.invoke (/C:/Users/Administrator/AppData/Local/npm-cache/_npx/a95e0f536cf9a537/node_modules/nuxi/dist/chunks/init.mjs:15200:15)
  at async _main (/C:/Users/Administrator/AppData/Local/npm-cache/_npx/a95e0f536cf9a537/node_modules/nuxi/dist/cli.mjs:50:20)

**Comment by manniL** [comment]
This is not an issue with Nuxt, but more likely with your proxy or firewall. See e.g. https://github.com/nuxt/framework/issues/8002

You can try `node -e "require('https').get('https://raw.githubusercontent.com/nuxt/starter/templates/templates/v3.json')"` and see what the problem is.
