### ISSUE TITLE
StoryBook in Nuxt 3 Stable

### ISSUE THREAD

**Issue by agracia-foticos** [nuxt/framework#9292]
### Environment

- Operating System: `Linux`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `srcDir`, `modules`, `compilerOptions`, `vite`, `schemaOrg`, `telemetry`, `algolia`, `head`, `auth`, `viewport`, `build`, `runtimeConfig`
- Runtime Modules:  `genesis-design-system/nuxt`, `@nuxtjs/tailwindcss@6.1.3`, `@nuxtjs/algolia@1.2.0`, `@nuxtjs-alt/auth@2.1.5`, `@nuxtjs-alt/http@1.5.0`, `nuxt-viewport@2.0.3`, `@nuxtjs/partytown@1.2.2`, `@vueuse/nuxt@9.6.0`, `@nuxtjs/i18n-edge@8.0.0-beta.4-27812700.b832f07`, `nuxt-schema-org@1.1.0-beta.6`, `@pinia/nuxt@0.4.5`, `@nuxtjs/i18n@8.0.0-beta.4`
- Build Modules:    `-`

### Reproduction

StoryBook/nuxt.js

`import { defineNuxtModule } from '@nuxt/kit'
import { fileURLToPath } from 'node:url'

export default defineNuxtModule({
  meta: {
      name: '@business/storybook',
      compatibility: {
          nuxt: '^3.0.0'
      }
  },
  hooks: {
    'components:dirs'(dirs) {
      // Add ./components dir to the list
      dirs.push({
        path: fileURLToPath(new URL('./src/components', import.meta.url)),
        prefix: ''
      })
    }
  },
  setup (options, nuxt) {
    nuxt.options.css.push('./src/styles/main.css')
  }
})`

![image](https://user-images.githubusercontent.com/77386602/203722502-7e54cf6e-175f-410c-9151-4e330ab98bfa.png)

ERROR when we runs the server

![image](https://user-images.githubusercontent.com/77386602/203722597-b5b3948e-719c-4638-8def-4e4aa940ee91.png)

### Describe the bug

We are implementing a StoryBook to our nuxt 3 Stable project.

When we start the project, referring to the StoryBook throws an error.

However, the definition of the StoryBook module is correct in principle, following the documentation at https://nuxt.com/docs/guide/going-further/modules

### Logs

```shell
4
[nuxt] [request error] [unhandled] [500] [vite-node] Failed to load /src/styles
  at ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:198:13)  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:146:12)  
  at async request (./node_modules/vite-node/dist/client.mjs:169:16)  
  at async virtual:nuxt:./.nuxt/css.mjs:3:31  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:270:5)  
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:146:12)  
  at async request (./node_modules/vite-node/dist/client.mjs:169:16)  
  at async ./node_modules/nuxt/dist/app/entry.mjs:9:31  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:270:5)
```

**Comment by danielroe** [comment]
I think you should likely do something like this:

```js
nuxt.options.css.push('~/styles/main.css')
// or
nuxt.options.css.push(fileURLToPath(new URL('./src/styles/main.css', import.meta.url))),
```

**Comment by agracia-foticos** [comment]
with 

`setup (options, nuxt) {
    nuxt.options.css.push('~/styles/main.css')
  }`

[vite-node] Failed to load /styles/main.css

at ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:198:13)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:146:12)
at async request (./node_modules/vite-node/dist/client.mjs:169:16)
at async virtual:nuxt:./.nuxt/css.mjs:5:31
at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:270:5)
at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:146:12)
at async request (./node_modules/vite-node/dist/client.mjs:169:16)
at async ./node_modules/nuxt/dist/app/entry.mjs:9:31
at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:270:5)


 THIS OPTION WORKS nuxt.options.css.push(fileURLToPath(new URL('./src/styles/main.css', import.meta.url))) !!

Thanks
