### ISSUE TITLE
_nuxt.defineNuxtConfig is not a function v3.0.0

### ISSUE THREAD

**Issue by morganics** [nuxt/framework#9330]
### Environment

```
Nuxt project info:                                                                                            12:33:54

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@9.1.2`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
```

### Reproduction

With the following in devDependencies:

```
"devDependencies": {
    "@nuxt/image-edge": "^1.0.0-27769790.4b27db3",
    "@nuxtjs/tailwindcss": "^6.1.3",
    "@vueuse/core": "^9.6.0",
    "@vueuse/nuxt": "^9.6.0",
    "nuxt": "3.0.0"
},
```

Spin up with npm run dev (calling nuxt dev), and results in the following error. 

Running with v3.0.0-rc.12 and earlier works fine, but same error in v3.0.0-rc.13 and 14.

### Describe the bug

Results in:

```
Nuxi 3.0.0                                                                                                    12:30:23
Nuxt 3.0.0 with Nitro 1.0.0                                                                                   12:30:23

 ERROR  Cannot start nuxt:  (0 , _nuxt.defineNuxtConfig) is not a function                                    12:30:27

  at C:/Users/user/PycharmProjects/nuxt-app/nuxt.config.ts:4:43
  at Object.jiti (node_modules\jiti\dist\jiti.js:1:247502)
  at resolveConfig (/C:/Users/user/PycharmProjects/nuxt-app/node_modules/c12/dist/index.mjs:221:24)
  at loadConfig (/C:/Users/user/PycharmProjects/nuxt-app/node_modules/c12/dist/index.mjs:104:40)
  at async loadNuxtConfig (/C:/Users/user/PycharmProjects/nuxt-app/node_modules/@nuxt/kit/dist/index.mjs:446:18)
  at async loadNuxt (/C:/Users/user/PycharmProjects/nuxt-app/node_modules/nuxt/dist/index.mjs:1835:19)
  at async loadNuxt (/C:/Users/user/PycharmProjects/nuxt-app/node_modules/@nuxt/kit/dist/index.mjs:493:19)
  at async load (/C:/Users/user/PycharmProjects/nuxt-app/node_modules/nuxi/dist/chunks/dev.mjs:6768:23)
  at async Object.invoke (/C:/Users/user/PycharmProjects/nuxt-app/node_modules/nuxi/dist/chunks/dev.mjs:6840:5)
  at async _main (/C:/Users/user/PycharmProjects/nuxt-app/node_modules/nuxi/dist/cli.mjs:50:20)
  
 ```
  
 

### Additional context

The nuxt.config.ts file looks like, though is currently highlighting that 'nuxt' cannot be found (which I'd guess is the source of the issue, but not one I can figure out how to fix...)

```
import { defineNuxtConfig } from 'nuxt'

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  meta: {
    title: '',
  },
  modules: [
    '@vueuse/nuxt','@nuxtjs/tailwindcss', '@pinia/nuxt', '@nuxt/image-edge'
  ],
  runtimeConfig: {
    public: {
      
    },
  },
  css: ['~/assets/css/style.css'],
  alias: {
    pinia: '/node_modules/@pinia/nuxt/node_modules/pinia/dist/pinia.mjs',
  }
})
```

**Comment by Teranode** [comment]
change `import { defineNuxtConfig } from 'nuxt'` to `import { defineNuxtConfig } from 'nuxt/config'`

**Comment by imrim12** [comment]
> change `import { defineNuxtConfig } from 'nuxt'` to `import { defineNuxtConfig } from 'nuxt/config'`

Thanks, this works 👍🏼 

This happens for newly created nuxt app

**Comment by manniL** [comment]
> This happens for newly created nuxt app

You might use an old version of `nuxi` then ☺️
