### ISSUE TITLE
Nuxt v3 - Fatal error when running yarn install

### ISSUE THREAD

**Issue by hades200082** [nuxt/framework#9347]
### Environment

Nuxi 3.0.0                                                                                                    20:09:13
                                                                                                              20:09:14
RootDir: D:/Projects/Personal/wood.leeconlin.co.uk                                                            20:09:14
Nuxt project info:                                                                                            20:09:14

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `-`
- Package Manager:  `yarn@3.2.3`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Using NodyJS 18.12.1 and Yarn 3.2.3 on Windows 11.

In PowerShell...

1. Run `npx nuxi init nuxt-app`
2. Run `cd nuxt-app`
3. Run `yarn install`

### Describe the bug

`yarn install` command results in the following error output in console:

```text
YN0000: ┌ Resolution step
➤ YN0002: │ @vue/babel-plugin-jsx@npm:1.1.1 doesn't provide @babel/core (pbd4eb), requested by @babel/plugin-syntax-jsx
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 765ms
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0007: │ root-workspace-0b6124@workspace:. must be built because it never has been before or the last one failed
➤ YN0009: │ root-workspace-0b6124@workspace:. couldn't be built successfully (exit code 1, logs can be found here: C:\Users\lee20\AppData\Local\Temp\xfs-f632300a\build.log)
➤ YN0000: └ Completed in 0s 330ms
➤ YN0000: Failed with errors in 1s 228ms
```

The following is the contents of the build.log file:

```
# This file contains the result of Yarn building a package (root-workspace-0b6124@workspace:.)
# Script name: postinstall

[90mNuxi [1m3.0.0[22m[39m

 ERROR  nuxi tried to access @nuxt/kit, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: @nuxt/kit (via "@nuxt\kit\package.json")
Required by: nuxi@npm:3.0.0 (via D:\Projects\Personal\wood.leeconlin.co.uk\.yarn\cache\nuxi-npm-3.0.0-fe4a3aa3f4-adee2b4dd0.zip\node_modules\nuxi\dist\chunks\prepare.mjs)


  
  Required package: @nuxt/kit (via "@nuxt\kit\package.json")
  Required by: nuxi@npm:3.0.0 (via .yarn\cache\nuxi-npm-3.0.0-fe4a3aa3f4-adee2b4dd0.zip\node_modules\nuxi\dist\chunks\prepare.mjs)
  
  at makeError (.pnp.cjs:16058:34)
  at resolveToUnqualified (.pnp.cjs:16977:21)
  at Object.resolveToUnqualified (.pnp.cjs:17121:26)
  at resolve$1 (/D:/Projects/Personal/wood.leeconlin.co.uk/.pnp.loader.mjs:224:31)
  at nextResolve (node:internal/modules/esm/loader:163:28)
  at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
  at link (node:internal/modules/esm/module_job:75:36)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Additional context

This was a clean install for a completely new project, following instructions at https://nuxt.com/docs/getting-started/installation

### Logs

```shell
# This file contains the result of Yarn building a package (root-workspace-0b6124@workspace:.)
# Script name: postinstall

[90mNuxi [1m3.0.0[22m[39m

 ERROR  nuxi tried to access @nuxt/kit, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: @nuxt/kit (via "@nuxt\kit\package.json")
Required by: nuxi@npm:3.0.0 (via D:\Projects\Personal\wood.leeconlin.co.uk\.yarn\cache\nuxi-npm-3.0.0-fe4a3aa3f4-adee2b4dd0.zip\node_modules\nuxi\dist\chunks\prepare.mjs)


  
  Required package: @nuxt/kit (via "@nuxt\kit\package.json")
  Required by: nuxi@npm:3.0.0 (via .yarn\cache\nuxi-npm-3.0.0-fe4a3aa3f4-adee2b4dd0.zip\node_modules\nuxi\dist\chunks\prepare.mjs)
  
  at makeError (.pnp.cjs:16058:34)
  at resolveToUnqualified (.pnp.cjs:16977:21)
  at Object.resolveToUnqualified (.pnp.cjs:17121:26)
  at resolve$1 (/D:/Projects/Personal/wood.leeconlin.co.uk/.pnp.loader.mjs:224:31)
  at nextResolve (node:internal/modules/esm/loader:163:28)
  at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
  at link (node:internal/modules/esm/module_job:75:36)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by danielroe** [comment]
You should use the `nodeModules` linker with yarn 3 for the moment. (We are working on this, though, with initial support through https://github.com/nuxt/framework/issues/5411.)

**Comment by OliverRC** [comment]
I am confused as to why this is closed.
These are the very simplest steps to getting started (off of the home page) yet they do not function.

These are literally the first steps to learning a new framework and they are broken. 

Providing some obtuse comment without any further information is pretty unhelpful and not having used Yarn before a google search also yielded no meaningful results for `nodeModules linker with yarn 3`

**Comment by danielroe** [comment]
Create a `.yarnrc.yml` file with the following content:

```yaml
nodeLinker: node-modules
```

More info: https://yarnpkg.com/configuration/yarnrc/#nodeLinker
