### ISSUE TITLE
[bug] 500 nuxt instance unavailable | whenever I use nuxt pages and the Strapi module

### ISSUE THREAD

**Issue by malgamves** [nuxt/framework#9392]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `modules`, `strapi`
- Runtime Modules:  `@nuxtjs/strapi@1.6.3`
- Build Modules:    `-`

### Reproduction

Here is a link to a [stack blitz repo](https://stackblitz.com/edit/nuxt-starter-jgaxk1?file=app.vue) to help reproduce. 

### Describe the bug

Hello, I can't seem to wrap my head around what this issue might me. For context, I'm using the Strapi Module to pull data from my Strapi CMS and display it in my next application. There seems to be a problem only when i use both the Strapi module and the the Nuxt pages feature. When I pull data from Strapi with the Nuxt module in my `app.vue` it displays as expected. When start to use Nuxt pages and my components, everything seems to stop working and  get the error that says "500 nuxt instance unavailable".

Wasn't really sure where to add the issue but i don't think it comes from the Nuxt module, everything seems to be working well. I wonder if I missed something in my implementation of Nuxt pages or is there something specific I need to do? Otherwise, the stack trace is shown below and hopefully that's enough context for someone to help out. 

### Additional context

if you change `pages` to `somepages` to deactivate the pages feature and reload the application, you will see the CMS data on displayed on your page (coming from `app.vue`) but once you change the name back to pages you get the same error :/

### Logs

```shell
Nuxt 3.0.0 with Nitro 1.0.0                                                                                                      03:13:42
                                                                                                                                 03:13:43
  > Local:    http://localhost:3000/
  > Network:  http://172.25.251.116:3000/

ℹ Vite client warmed up in 3231ms                                                                                                03:13:47
✔ Nitro built in 1277 ms                                                                                                   nitro 03:13:48
[Vue Router warn]: uncaught error during route navigation:                                                                       03:13:52
Error: nuxt instance unavailable                                                                                                 03:13:52
    at Module.useNuxtApp (/home/malgamves/code/strapi-dynamic-zones-company-site/client/node_modules/nuxt/dist/app/nuxt.mjs:165:13)
    at Module.useStrapiClient (/home/malgamves/code/strapi-dynamic-zones-company-site/client/node_modules/@nuxtjs/strapi/dist/runtime/composables/useStrapiClient.mjs:27:38)
    at Module.useStrapiGraphQL (/home/malgamves/code/strapi-dynamic-zones-company-site/client/node_modules/@nuxtjs/strapi/dist/runtime/composables/useStrapiGraphQL.mjs:8:40)
    at /home/malgamves/code/strapi-dynamic-zones-company-site/client/pages/index.vue:11:39
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ViteNodeRunner.directRequest (file:///home/malgamves/code/strapi-dynamic-zones-company-site/client/node_modules/vite-node/dist/client.mjs:270:5)
    at async ViteNodeRunner.cachedRequest (file:///home/malgamves/code/strapi-dynamic-zones-company-site/client/node_modules/vite-node/dist/client.mjs:146:12)
    at async request (file:///home/malgamves/code/strapi-dynamic-zones-company-site/client/node_modules/vite-node/dist/client.mjs:169:16)
    at async /home/malgamves/code/strapi-dynamic-zones-company-site/client/node_modules/nuxt/dist/pages/runtime/router.mjs:75:94
    at async Object.callAsync (file:///home/malgamves/code/strapi-dynamic-zones-company-site/client/node_modules/unctx/dist/index.mjs:53:16)
[Vue Router warn]: uncaught error during route navigation:                                                                       03:13:52
Error: nuxt instance unavailable                                                                                                 03:13:52
    at Module.useNuxtApp (/home/malgamves/code/strapi-dynamic-zones-company-site/client/node_modules/nuxt/dist/app/nuxt.mjs:165:13)
    at Module.useStrapiClient (/home/malgamves/code/strapi-dynamic-zones-company-site/client/node_modules/@nuxtjs/strapi/dist/runtime/composables/useStrapiClient.mjs:27:38)
    at Module.useStrapiGraphQL (/home/malgamves/code/strapi-dynamic-zones-company-site/client/node_modules/@nuxtjs/strapi/dist/runtime/composables/useStrapiGraphQL.mjs:8:40)
    at /home/malgamves/code/strapi-dynamic-zones-company-site/client/pages/index.vue:11:39
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ViteNodeRunner.directRequest (file:///home/malgamves/code/strapi-dynamic-zones-company-site/client/node_modules/vite-node/dist/client.mjs:270:5)
    at async ViteNodeRunner.cachedRequest (file:///home/malgamves/code/strapi-dynamic-zones-company-site/client/node_modules/vite-node/dist/client.mjs:146:12)
    at async request (file:///home/malgamves/code/strapi-dynamic-zones-company-site/client/node_modules/vite-node/dist/client.mjs:169:16)
    at async /home/malgamves/code/strapi-dynamic-zones-company-site/client/node_modules/nuxt/dist/pages/runtime/router.mjs:75:94
    at async Object.callAsync (file:///home/malgamves/code/strapi-dynamic-zones-company-site/client/node_modules/unctx/dist/index.mjs:53:16)
[Vue Router warn]: uncaught error during route navigation:                                                                       03:13:52
Error: nuxt instance unavailable                                                                                                 03:13:52
    at Module.useNuxtApp (/home/malgamves/code/strapi-dynamic-zones-company-site/client/node_modules/nuxt/dist/app/nuxt.mjs:165:13)
    at Module.useStrapiClient (/home/malgamves/code/strapi-dynamic-zones-company-site/client/node_modules/@nuxtjs/strapi/dist/runtime/composables/useStrapiClient.mjs:27:38)
    at Module.useStrapiGraphQL (/home/malgamves/code/strapi-dynamic-zones-company-site/client/node_modules/@nuxtjs/strapi/dist/runtime/composables/useStrapiGraphQL.mjs:8:40)
    at /home/malgamves/code/strapi-dynamic-zones-company-site/client/pages/index.vue:11:39
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ViteNodeRunner.directRequest (file:///home/malgamves/code/strapi-dynamic-zones-company-site/client/node_modules/vite-node/dist/client.mjs:270:5)
    at async ViteNodeRunner.cachedRequest (file:///home/malgamves/code/strapi-dynamic-zones-company-site/client/node_modules/vite-node/dist/client.mjs:146:12)
    at async request (file:///home/malgamves/code/strapi-dynamic-zones-company-site/client/node_modules/vite-node/dist/client.mjs:169:16)
    at async /home/malgamves/code/strapi-dynamic-zones-company-site/client/node_modules/nuxt/dist/pages/runtime/router.mjs:75:94
    at async Object.callAsync (file:///home/malgamves/code/strapi-dynamic-zones-company-site/client/node_modules/unctx/dist/index.mjs:53:16)
[Vue Router warn]: uncaught error during route navigation:                                                                       03:13:52
Error: nuxt instance unavailable                                                                                                 03:13:52
    at Module.useNuxtApp (/home/malgamves/code/strapi-dynamic-zones-company-site/client/node_modules/nuxt/dist/app/nuxt.mjs:165:13)
    at Module.useStrapiClient (/home/malgamves/code/strapi-dynamic-zones-company-site/client/node_modules/@nuxtjs/strapi/dist/runtime/composables/useStrapiClient.mjs:27:38)
    at Module.useStrapiGraphQL (/home/malgamves/code/strapi-dynamic-zones-company-site/client/node_modules/@nuxtjs/strapi/dist/runtime/composables/useStrapiGraphQL.mjs:8:40)
    at /home/malgamves/code/strapi-dynamic-zones-company-site/client/pages/index.vue:11:39
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ViteNodeRunner.directRequest (file:///home/malgamves/code/strapi-dynamic-zones-company-site/client/node_modules/vite-node/dist/client.mjs:270:5)
    at async ViteNodeRunner.cachedRequest (file:///home/malgamves/code/strapi-dynamic-zones-company-site/client/node_modules/vite-node/dist/client.mjs:146:12)
    at async request (file:///home/malgamves/code/strapi-dynamic-zones-company-site/client/node_modules/vite-node/dist/client.mjs:169:16)
    at async /home/malgamves/code/strapi-dynamic-zones-company-site/client/node_modules/nuxt/dist/pages/runtime/router.mjs:75:94
    at async Object.callAsync (file:///home/malgamves/code/strapi-dynamic-zones-company-site/client/node_modules/unctx/dist/index.mjs:53:16)
```

**Comment by manniL** [comment]
Your page misses the `setup` of `<script setup>`.
