### ISSUE TITLE
throw createError not working in async try/catch

### ISSUE THREAD

**Issue by IzakJackson** [nuxt/framework#9416]
### Environment

- Operating System: `Darwin`
- Node Version:     `v14.17.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@6.14.13`
- Builder:          `vite`
- User Config:      `app`, `modules`, `googleFonts`, `tailwindcss`, `colorMode`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.1.3`, `@nuxtjs/google-fonts@3.0.0-1`, `@nuxtjs/supabase@0.3.0`, `@nuxtjs/color-mode@3.1.8`, `@pinia/nuxt@0.4.5`, `@formkit/nuxt@1.0.0-beta.12`
- Build Modules:    `-`

### Reproduction

```
const getContact = async () => {
    loading.value = true;
    try {
      const { data, error } = await client
        .from("contacts")
        .select()
        .eq("id", route.params.id);
      if (data) {
        contact.value = data[0];
      }
      if (!contact.value || error) {
        throw error;
      }
    } catch (error) {
      console.log("Contact not found");
      throw createError({
        statusCode: 404,
        statusMessage: "Contact not found.",
        fatal: true,
      });
    } finally {
      loading.value = false;
    }
  };
  getContact();

```

### Describe the bug

throw createError does not work inside an async function with try/catch.

I can console.log or throw alert however.

Terminal error:
```
[nitro] [dev] [unhandledRejection] H3Error: Contact not found.                                                                                                                             11:32:37
    at Module.createError (file:///Users/izakjackson/Documents/GitHub/CRM/node_modules/h3/dist/index.mjs:48:15)
    at Module.createError (/Users/izakjackson/Documents/GitHub/CRM/node_modules/nuxt/dist/app/composables/error.mjs:35:38)
    at getContact (/Users/izakjackson/Documents/GitHub/CRM/pages/contacts/[id].vue:57:35)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  statusCode: 404,
  fatal: true,
  unhandled: false,
  statusMessage: 'Contact not found.',
  __nuxt_error: true
}
```

Console error:
```
Uncaught (in promise) Error: Contact not found.
```

**Comment by danielroe** [comment]
let's track this in https://github.com/nuxt/framework/issues/8880
