### ISSUE TITLE
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by artmarydotir** [nuxt/framework#9438]
### Environment

------------------------------
- Operating System: `Linux`
 - Description:	Ubuntu 20.04.5 LTS
 - Release:	20.04
- Node Version:     `v16.18.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `css`, `ssr`, `app`, `postcss`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Created an error.vue page

```
<template>
  <div>
    <div class="container max-w-200">
      <h1>{{ error.message }}</h1>
      There was an error 😱
      <br />
      <button @click="handleError">Clear error</button>
      <br />
      <NuxtLink to="/404"> Trigger another error </NuxtLink>
      <br />
      <NuxtLink to="/"> Navigate home </NuxtLink>
    </div>
  </div>
</template>

<script setup>
const router = useRouter();
const props = defineProps({ error: Object });

if (router.currentRoute.value.fullPath === "/old-slug") {
  await navigateTo("/new-slug", {
    redirectCode: 301,
  });
}

const handleError = () => clearError({ redirect: "/" });
</script>


```

### Describe the bug

When i curl this url :

```
$ curl http://192.168.0.117:3000/old-slug -v
...
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Access-Control-Allow-Origin: *
< location: /new-slug
< content-type: text/html
< server-timing: -;dur=0;desc="Generate"
< date: Wed, 30 Nov 2022 18:25:24 GMT
< connection: close
< content-length: 95
< 
* Closing connection 0
<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0; url=/new-slug"></head></html>
```

**everything works correctly except get this error on server:**

```
[nitro] [dev] [unhandledRejection] Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:387:5)
    at ServerResponse.setHeader (node:_http_outgoing:644:11)
    at Object.errorhandler [as onError] (file:///artmary/rog/mary_projects/1400learning/frontendmaster/nuxt3test/nuxt-app/.nuxt/dev/index.mjs:427:20)
    at Server.toNodeHandle (file:///artmary/rog/mary_projects/1400learning/frontendmaster/nuxt3test/nuxt-app/node_modules/h3/dist/index.mjs:752:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_HTTP_HEADERS_SENT'
}

```

**Comment by mhf-ir** [comment]
Typical http server error on many program language if you send body first instead of sending headers. seems be that's h3 bug or buggy implementation in nuxt framework.

**Comment by Upose** [comment]
i got the same problem

**Comment by IsraelOrtuno** [comment]
I was able to debug this (for my case). I was experiencing this in Vercel when having URL query parameters containing spaces or other symbols like slashes `/?redirect=/my-account`. Not sure if it's the problem here but since the error doesn't say too much I'll leave the comment that helped me here: https://github.com/nuxt/framework/issues/5902#issuecomment-1288381159

**Comment by adriaanvanrossum** [comment]
I have the same issue in `middleware/redirects.global.js`:

```js
const redirects = [
  {
    type: "replace",
    from: "/google-analytics-countries",
    to: "/google-analytics-is-illegal-in-these-countries",
  }
];

const options = { redirectCode: 308 }; // 308 Permanent Redirect

export default defineNuxtRouteMiddleware(({ path, query, hash }) => {
  for (const redirect of redirects) {
    if (redirect.type === "replace" && path.includes(redirect.from)) {
      const nextPath = path.replace(redirect.from, redirect.to);
      return navigateTo({ path: nextPath, query, hash }, options);
    }
  }
});
```

Console:

```
✔ Vite server hmr 8 files in 11.244ms
Error from Nuxt: H3Error: Page not found: /en/google-analytics-henk
    at Module.createError (file:///user/node_modules/h3/dist/index.mjs:48:15)
    at /user/node_modules/nuxt/dist/pages/runtime/router.mjs:132:107
    at triggerAfterEach (file:///user/node_modules/vue-router/dist/vue-router.mjs:3306:13)
    at file:///user/node_modules/vue-router/dist/vue-router.mjs:3209:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /user/node_modules/nuxt/dist/pages/runtime/router.mjs:146:7
    at async createNuxtAppServer (/user/node_modules/nuxt/dist/app/entry.mjs:30:7)
    at async default (file:///user/node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:27:18)
    at async Object.renderToString (file:///user/node_modules/vue-bundle-renderer/dist/runtime.mjs:172:19)
    at async file:///user/.nuxt/dev/index.mjs:980:21 {
  statusCode: 404,
  fatal: false,
  unhandled: false,
  statusMessage: 'Page not found: /en/google-analytics-henk',
  __nuxt_error: true
}
Error from Nuxt: {
  url: '/en/google-analytics-henk',
  statusCode: '404',
  statusMessage: 'Page not found: /en/google-analytics-henk',
  message: 'Page not found: /en/google-analytics-henk',
  stack: ''
}
[nitro] [dev] [unhandledRejection] Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:393:5)
    at ServerResponse.setHeader (node:_http_outgoing:644:11)
    at setResponseHeader (file:///user/node_modules/nitropack/node_modules/h3/dist/index.mjs:296:18)
    at Object.errorhandler [as onError] (file:///user/.nuxt/dev/index.mjs:447:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Server.toNodeHandle (file:///user/node_modules/nitropack/node_modules/h3/dist/index.mjs:805:9) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
```

Is there a way to tell Nuxt 3 it can stop doing anything else for that request?
