### ISSUE TITLE
bug: error handling examples broke

### ISSUE THREAD

**Issue by cpreston321** [nuxt/framework#9515]
### Environment

N/A

### Reproduction

https://nuxt.com/docs/examples/app/error-handling#error-handling

### Describe the bug

The example should be working but is broke both in code sandbox and stackblitz examples

**Comment by mieky** [comment]
Can confirm, getting a HTTP 503 from both Codesandbox and Stackblitz with this stacktrace:

```
file:///sandbox/.nuxt/dev/index.mjs:8
import { eventHandler, setHeaders, sendRedirect, defineEventHandler, handleCacheHeaders, createEvent, getRequestHeader, getRequestHeaders, setResponseHeader, defineMiddleware, getQuery, createApp, createRouter as createRouter$1, lazyEventHandler, toNodeListener, createError } from 'file:///sandbox/node_modules/h3/dist/index.mjs';
                                                                                                                                                              ^^^^^^^^^^^^^^^^
SyntaxError: The requested module 'file:///sandbox/node_modules/h3/dist/index.mjs' does not provide an export named 'defineMiddleware'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:124:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:179:5)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
    at async handleMainPromise (internal/modules/run_main.js:59:12)
```
