### ISSUE TITLE
nuxt-edge+ nuxt/bridge

### ISSUE THREAD

**Issue by arthur-fontaine** [nuxt/framework#955]
`nuxt/bridge` does not find `node_modules/vue/dist/vue.runtime.esm.js`. Indeed, the Vue package doesn't have that file, but it has these ones:

```
vue.cjs.js                      vue.esm-browser.prod.js         vue.runtime.esm-browser.js      vue.runtime.global.prod.js
vue.cjs.prod.js                 vue.esm-bundler.js              vue.runtime.esm-browser.prod.js
vue.d.ts                        vue.global.js                   vue.runtime.esm-bundler.js
vue.esm-browser.js              vue.global.prod.js              vue.runtime.global.js
```

Maybe nuxt/bridge should look for `node_modules/vue/dist/vue.runtime.esm-bundler.js` as indicated in the `package.json` of the Vue package:

```
{
  ...
  "module": "dist/vue.runtime.esm-bundler.js",
  ...
}
```

### Versions

- nuxt-edge: latest
- node: v14.17.1
- vue: 3.2.20

### Reproduction

<details>
<summary>nuxt.config</summary>
<br>
<pre>
import { defineNuxtConfig } from '@nuxt/bridge';

export default defineNuxtConfig({
  // Target (https://go.nuxtjs.dev/config-target)
  target: 'server',

  // ssr: false,

  server: {
    port: 8000, // default: 3000
    host: '0.0.0.0' // default: localhost
  },

  // Global page headers (https://go.nuxtjs.dev/config-head)
  head: {...},

  // Global CSS (https://go.nuxtjs.dev/config-css)
  css: [...],

  // Plugins to run before rendering page (https://go.nuxtjs.dev/config-plugins)
  plugins: [],

  // Auto import components (https://go.nuxtjs.dev/config-components)
  components: true,

  // Modules for dev and build (recommended) (https://go.nuxtjs.dev/config-modules)
  buildModules: [
    // https://go.nuxtjs.dev/stylelint
    '@nuxtjs/stylelint-module',
    // https://go.nuxtjs.dev/tailwindcss
    '@nuxtjs/tailwindcss',
    // https://color-mode.nuxtjs.org/
    '@nuxtjs/color-mode',
    // https://github.com/fumeapp/nuxt-storm
    'nuxt-storm'
  ],

  // Modules (https://go.nuxtjs.dev/config-modules)
  modules: [
    // https://go.nuxtjs.dev/axios
    '@nuxtjs/axios',
    // https://go.nuxtjs.dev/pwa
    '@nuxtjs/pwa',
    // https://github.com/nuxt-community/dotenv-module
    '@nuxtjs/dotenv',
    // https://www.npmjs.com/package/vue-sweetalert2
    'vue-sweetalert2/nuxt',
    // https://i18n.nuxtjs.org/
    'nuxt-i18n'
  ],

  // Axios module configuration (https://go.nuxtjs.dev/config-axios)
  axios: {},

  // i18n module configuration (https://i18n.nuxtjs.org/options-reference)
  i18n: {
    locales: [
      { code: 'en', iso: 'en-US', file: 'en.js', dir: 'ltr' },
      { code: 'fr', iso: 'fr-FR', file: 'fr.js' },
      { code: 'it', iso: 'it-IT', file: 'it.js' },
      { code: 'de', iso: 'de-DE', file: 'de.js' },
      { code: 'pt', iso: 'pt-PT', file: 'pt.js' },
      { code: 'es', iso: 'es-ES', file: 'es.js' }
    ],
    lazy: true,
    langDir: './locales/',
    detectBrowserLanguage: {
      useCookie: true,
      alwaysRedirect: true
    },
    defaultLocale: 'en'
  },

  // Build Configuration (https://go.nuxtjs.dev/config-build)
  build: {},

  // PWA Configuration (https://pwa.nuxtjs.org/)
  pwa: {...}
});
</pre>
</details>

<details>
<summary>package.json</summary>
<pre>
{
  ...
  "dependencies": {
    "@nuxtjs/axios": "^5.13.1",
    "@nuxtjs/color-mode": "^2.0.5",
    "@nuxtjs/dotenv": "^1.4.1",
    "@types/crypto-js": "^4.0.1",
    "@types/qrcode": "^1.4.0",
    "axios": "^0.21.1",
    "core-js": "^3.11.0",
    "crypto-js": "^4.0.0",
    "dropzone": "^5.9.2",
    "eslint-plugin-vue": "^7.18.0",
    "jszip": "^3.6.0",
    "nuxt-edge": "latest",
    "nuxt-i18n": "^6.26.0",
    "nuxt-property-decorator": "^2.9.1",
    "qrcode": "^1.4.4",
    "vue-pets": "^1.0.10",
    "vue-sweetalert2": "^4.3.1"
  },
  "devDependencies": {
    "@nuxt/bridge": "npm:@nuxt/bridge-edge@^3.0.0-27235451.ece0e01",
    "@nuxt/types": "^2.15.4",
    "@nuxt/typescript-build": "^2.1.0",
    "@nuxtjs/eslint-config": "^6.0.0",
    "@nuxtjs/eslint-config-typescript": "^6.0.0",
    "@nuxtjs/eslint-module": "^3.0.2",
    "@nuxtjs/pwa": "^3.3.5",
    "@nuxtjs/stylelint-module": "^4.0.0",
    "@nuxtjs/tailwindcss": "^4.0.3",
    "babel-eslint": "^10.1.0",
    "eslint": "^7.25.0",
    "eslint-config-prettier": "^8.2.0",
    "eslint-plugin-nuxt": "^2.0.0",
    "eslint-plugin-prettier": "^3.4.0",
    "nuxt-storm": "^1.1.2",
    "prettier": "^2.1.2",
    "stylelint": "^13.13.0",
    "stylelint-config-prettier": "^8.0.2",
    "stylelint-config-standard": "^22.0.0",
    "tailwindcss-dark-mode": "^1.1.7"
  },
  ...
}
</pre>
</details>

### What is actually happening?

<details>
<summary>Console output</summary>
<pre>
❯ nuxt dev
ℹ Merging Tailwind config from ~/tailwind.config.js                                                                             nuxt:tailwindcss 15:55:23

 FATAL  Cannot find module '.../node_modules/vue/dist/vue.runtime.esm.js'                   15:55:24

  at createEsmNotFoundErr (internal/modules/cjs/loader.js:929:15)
  at finalizeEsmResolution (internal/modules/cjs/loader.js:922:15)
  at resolveExports (internal/modules/cjs/loader.js:450:14)
  at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
  at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
  at Function.resolve (internal/modules/cjs/helpers.js:98:19)
  at Function.p [as resolve] (node_modules/jiti/dist/jiti.js:1:53328)
  at resolveModule (node_modules/@nuxt/kit/dist/index.mjs:67:29)
  at setupAppBridge (node_modules/@nuxt/bridge/dist/module.mjs:284:58)
  at setup (node_modules/@nuxt/bridge/dist/module.mjs:859:13)

   ╭─────────────────────────────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                                         │
   │   ✖ Nuxt Fatal Error                                                                                    │
   │                                                                                                         │
   │   Error: Cannot find module                                                                             │
   │   '.../node_modules/vue/dist/vue.runtime.esm.js'   │
   │                                                                                                         │
   ╰─────────────────────────────────────────────────────────────────────────────────────────────────────────╯

</pre>
</details>

**Comment by arthur-fontaine** [comment]
On my current project, I tried to `npm install vue@2.6.14`.
It seems to resolve some problems. Nuxt succeeded to start the compilation. But some of my dependencies (`nuxt-i18n` and `tailwind`) seems to not be compatible with `nuxt-bridge`.

To resolve the `nuxt-i18n` problem, I `npm install vue-template-compiler@2.6.14`.
But I don't find yet a fix for the `tailwind` problem. `nuxt-nitro` is not supporting the ES importing, and then cannot understand this line: `import createServer from 'tailwind-config-viewer/server';`.

So I will try to make a new project without dependencies to provide a reproduction.

**Comment by arthur-fontaine** [comment]
I created a Nuxt2 project and follow the guide to use `nuxt-bridge`. I don't know why, when I `npm install -D @nuxt/bridge@npm:@nuxt/bridge-edge`, it is `vue@2.6.14` which has been installed. However, I don't know if it is normal, `nuxt-nitro` still require `vue@3.2.20`, but this version is not installed. So I can't provide a reproduction...
Maybe a previous dependencies of my project installed `vue@^3.0.0` without my knowledge. Perhaps it is useful to prevent the installation of `nuxt-bridge` if Vue3 is installed?
