### ISSUE TITLE
Running `nuxi init` results in error

### ISSUE THREAD

**Issue by vedxp** [nuxt/framework#9604]
### Discussed in https://github.com/nuxt/framework/discussions/9569

<div type='discussions-op-text'>

<sup>Originally posted by **vedxp** December  7, 2022</sup>
#### When I run `pnpm dlx nuxi init <any-name>`, it gives this error:
```
Failed to download template from registry: fetch failed

  at .local/share/pnpm/store/v3/tmp/dlx-20687/node_modules/.pnpm/nuxi@3.0.0/node_modules/nuxi/dist/chunks/init.mjs:15133:11
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async downloadTemplate (.local/share/pnpm/store/v3/tmp/dlx-20687/node_modules/.pnpm/nuxi@3.0.0/node_modules/nuxi/dist/chunks/init.mjs:15132:20)
  at async Object.invoke (.local/share/pnpm/store/v3/tmp/dlx-20687/node_modules/.pnpm/nuxi@3.0.0/node_modules/nuxi/dist/chunks/init.mjs:15200:15)
  at async _main (.local/share/pnpm/store/v3/tmp/dlx-20687/node_modules/.pnpm/nuxi@3.0.0/node_modules/nuxi/dist/cli.mjs:50:20)

 ERROR  Command failed with exit code 1: /data/data/com.termux/files/home/.local/share/pnpm/store/v3/tmp/dlx-20687/node_modules/.bin/nuxi init port

pnpm: Command failed with exit code 1: /data/data/com.termux/files/home/.local/share/pnpm/store/v3/tmp/dlx-20687/node_modules/.bin/nuxi init port
    at makeError (/data/data/com.termux/files/home/.cache/node/corepack/pnpm/7.18.0/dist/pnpm.cjs:22852:17)
    at handlePromise (/data/data/com.termux/files/home/.cache/node/corepack/pnpm/7.18.0/dist/pnpm.cjs:23423:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler [as dlx] (/data/data/com.termux/files/home/.cache/node/corepack/pnpm/7.18.0/dist/pnpm.cjs:202440:7)
    at async /data/data/com.termux/files/home/.cache/node/corepack/pnpm/7.18.0/dist/pnpm.cjs:209882:21
    at async main (/data/data/com.termux/files/home/.cache/node/corepack/pnpm/7.18.0/dist/pnpm.cjs:209853:34)
    at async runPnpm (/data/data/com.termux/files/home/.cache/node/corepack/pnpm/7.18.0/dist/pnpm.cjs:210079:5)
    at async /data/data/com.termux/files/home/.cache/node/corepack/pnpm/7.18.0/dist/pnpm.cjs:210071:7
```

- pnpm version: `7.18.0`

#### I need help installing Nuxt, latter much appreciated :)</div>

**Comment by danielroe** [comment]
I can't reproduce this. Can you provide any more information about your setup?

**Comment by vedxp** [comment]
> I can't reproduce this. Can you provide any more information about your setup?

- Npm version: 9.1.3
- Termux version: 0.118.0

Adding more:
- Results in [this error](https://github.com/termux/termux-packages/issues/13293) when using `npm` instead of `pnpm`.

**Comment by danielroe** [comment]
Seems like there is a network issue between your computer and GitHub - I would investigate your firewall/proxy setup?

**Comment by vedxp** [comment]
> Seems like there is a network issue between your computer and GitHub - I would investigate your firewall/proxy setup?

I'm not using any firewall or proxy.

**Comment by vedxp** [comment]
@danielroe the issue got fixed by changing dns.

Still, it should be working without doing such changes too, which would be much appreciated!

Closing the issue for now.
Regards :)
