### ISSUE TITLE
Reactivity Transform

### ISSUE THREAD

**Issue by mohamad68** [nuxt/framework#9647]
### Environment

client and server

### Reproduction

null

### Describe the bug

Reactivity Transform id not working anywhere in Nuxt?

```
<script setup>
let x = $ref(30)
console.log(x)
</script>

```
nuxt throw error 500 "$ref not define"

**Comment by cpreston321** [comment]
@mohamad68 since you are using setup comp api use `ref()` instead

```ts
<script setup>
const x = ref(10)
console.log(x.value)
</script>
```

**Comment by cpreston321** [comment]
Check stackblitz link: https://stackblitz.com/edit/github-hncs2a?file=app.vue

**Comment by mohamad68** [comment]
yes I know I can use ref but I want to use $ref() ` because I don want to use `.value `

**Comment by danielroe** [comment]
You can enable it with `experimental.reactivityTransform`: https://nuxt.com/docs/api/configuration/nuxt-config/#reactivitytransform.

**Comment by NexZhu** [comment]
@danielroe Vite support passing a path as reactivityTransform in addition to `true` or `false`:
```json
{
  reactivityTransform: path.resolve(__dirname, 'src'),
}
```

This is neccessary because passing only `true` may cause errors in pnpm/yarn workspace because workspace dependencies are linked to `node_modules/xxx`.

For example in my pnpm workspace, `@fgfe/vue-components` package in the same pnpm workspace is added as a dependency of the app with `package.json`:
```json
"dependencies": {
  ...
  "@fgfe/vue-components": "workspace:*",
  ...
}
```

Causing this error when setting `reactivityTransform: true`:
```
 ERROR  [vite:vue] $ can only be used as the initializer of a variable declaration.                                                                               16:49:01
file: /Users/xxx/Desktop/baas/lib/fgfe-vue-components/dist/index.e1d876b7.js


 ERROR  $ can only be used as the initializer of a variable declaration.                                                                                          16:49:01

  at error (/Users/xxx/Desktop/baas/node_modules/.pnpm/@vue+reactivity-transform@3.2.45/node_modules/@vue/reactivity-transform/dist/reactivity-transform.cjs.js:141:19)
  at Object.enter (/Users/xxx/Desktop/baas/node_modules/.pnpm/@vue+reactivity-transform@3.2.45/node_modules/@vue/reactivity-transform/dist/reactivity-transform.cjs.js:508:28)
  at SyncWalker.visit (/Users/xxx/Desktop/baas/node_modules/.pnpm/estree-walker@2.0.2/node_modules/estree-walker/dist/umd/estree-walker.js:116:17)
  at SyncWalker.visit (/Users/xxx/Desktop/baas/node_modules/.pnpm/estree-walker@2.0.2/node_modules/estree-walker/dist/umd/estree-walker.js:153:12)
  at SyncWalker.visit (/Users/xxx/Desktop/baas/node_modules/.pnpm/estree-walker@2.0.2/node_modules/estree-walker/dist/umd/estree-walker.js:153:12)
  at SyncWalker.visit (/Users/xxx/Desktop/baas/node_modules/.pnpm/estree-walker@2.0.2/node_modules/estree-walker/dist/umd/estree-walker.js:153:12)
  at SyncWalker.visit (/Users/xxx/Desktop/baas/node_modules/.pnpm/estree-walker@2.0.2/node_modules/estree-walker/dist/umd/estree-walker.js:153:12)
  at SyncWalker.visit (/Users/xxx/Desktop/baas/node_modules/.pnpm/estree-walker@2.0.2/node_modules/estree-walker/dist/umd/estree-walker.js:146:19)
  at SyncWalker.visit (/Users/xxx/Desktop/baas/node_modules/.pnpm/estree-walker@2.0.2/node_modules/estree-walker/dist/umd/estree-walker.js:153:12)
  at SyncWalker.visit (/Users/xxx/Desktop/baas/node_modules/.pnpm/estree-walker@2.0.2/node_modules/estree-walker/dist/umd/estree-walker.js:153:12)
  at SyncWalker.visit (/Users/xxx/Desktop/baas/node_modules/.pnpm/estree-walker@2.0.2/node_modules/estree-walker/dist/umd/estree-walker.js:146:19)
  at SyncWalker.visit (/Users/xxx/Desktop/baas/node_modules/.pnpm/estree-walker@2.0.2/node_modules/estree-walker/dist/umd/estree-walker.js:153:12)
  at SyncWalker.visit (/Users/xxx/Desktop/baas/node_modules/.pnpm/estree-walker@2.0.2/node_modules/estree-walker/dist/umd/estree-walker.js:146:19)
  at Object.walk (/Users/xxx/Desktop/baas/node_modules/.pnpm/estree-walker@2.0.2/node_modules/estree-walker/dist/umd/estree-walker.js:322:19)
  at transformAST (/Users/xxx/Desktop/baas/node_modules/.pnpm/@vue+reactivity-transform@3.2.45/node_modules/@vue/reactivity-transform/dist/reactivity-transform.cjs.js:456:18)
  at Object.transform [as transformRef] (/Users/xxx/Desktop/baas/node_modules/.pnpm/@vue+reactivity-transform@3.2.45/node_modules/@vue/reactivity-transform/dist/reactivity-transform.cjs.js:38:17)
  at Object.transform (/Users/xxx/Desktop/baas/node_modules/.pnpm/@vitejs+plugin-vue@3.2.0_vite@3.2.5+vue@3.2.45/node_modules/@vitejs/plugin-vue/dist/index.mjs:2693:35)
  at /Users/xxx/Desktop/baas/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:22748:40
```

**Comment by danielroe** [comment]
@NexZhu Would you be able to open a new issue with a reproduction so we can fix this? 🙏

**Comment by NexZhu** [comment]
@danielroe I'm sorry, I'm not sure what code in the dependency project is causing the error, and the code is private.

But from the above log it's clear that some `$` signs in the dependency project code's build output (`dist/index.e1d876b7.js`) is causing the error, the dependency project may or maynot use `reactivityTransorm` so we need to limit the transformation to some directory/files.

Vite already support this so we just need to do the same. I've found a related issue in the Vite repo:
https://github.com/vitejs/vite/issues/7854#issuecomment-1107651723
