### ISSUE TITLE
Big integer literals are not available

### ISSUE THREAD

**Issue by AndreyKindin** [nuxt/framework#9813]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `pnpm@7.18.2`
- Builder:          `vite`
- User Config:      `css`, `build`, `vite`, `modules`
- Runtime Modules:  `()`
- Build Modules:    `-`
------------------------------

### Reproduction

in server/api create test file
test.js
with this content
export default () => 1n

### Describe the bug

i get this error
server\api\test.js:1:21: ERROR: Big integer literals are not available in the configured target environment ("es2019")

### Logs

```shell
i Client built in 7971ms                                                                          15:45:37
i Building server...                                                                              15:45:37
√ Server built in 7674ms                                                                          15:45:44
√ Generated public .output/public                                                           nitro 15:45:44
i Building Nitro Server (preset: node-server)                                               nitro 15:45:45

 ERROR                                                                                      nitro 15:45:45  

Big integer literals are not available in the configured target environment ("es2019")


 ERROR  Transform failed with 1 error:                                                            15:45:45  
XXXXX\server\api\test.js:1:21: ERROR: Big integer literals are not available in the configured target environment ("es2019")

  server\api\test.js:1:21: ERROR: Big integer literals are not available in the configured target environment ("es2019")
  at failureErrorWithLog (node_modules\.pnpm\esbuild@0.15.18\node_modules\esbuild\lib\main.js:1575:15)      
  at node_modules\.pnpm\esbuild@0.15.18\node_modules\esbuild\lib\main.js:814:29
  at responseCallbacks.<computed> (node_modules\.pnpm\esbuild@0.15.18\node_modules\esbuild\lib\main.js:680:9)
  at handleIncomingPacket (node_modules\.pnpm\esbuild@0.15.18\node_modules\esbuild\lib\main.js:735:9)       
  at Socket.readFromStdout (node_modules\.pnpm\esbuild@0.15.18\node_modules\esbuild\lib\main.js:656:7)      
  at Socket.emit (node:events:513:28)
  at Socket.emit (node:domain:489:12)
  at addChunk (node:internal/streams/readable:324:12)
  at readableAddChunk (node:internal/streams/readable:297:9)
  at Readable.push (node:internal/streams/readable:234:10)
  at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Comment by AndreyKindin** [comment]
Sorry i found the solution
in https://github.com/nuxt/framework/issues/6040
