### ISSUE TITLE
 ERROR  Cannot start nuxt:  Cannot read properties of undefined (reading 'options')

### ISSUE THREAD

**Issue by RijaCloud** [nuxt/framework#9822]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@9.2.0`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@nuxtjs/i18n@7.3.0`
- Build Modules:    `-`
------------------------------

### Reproduction

1. Create a new nuxt v3 project
2. Install the i18n module
3. Add i18n to the modules in `nuxt.config.ts`
4. create a `locales` directory and a `fr,en` json file that contains your traduction 

### Describe the bug

```
import fr from "./locales/fr.json";
import en from "./locales/en.json";
import ca from "./locales/ca.json";
import nl from "./locales/nl.json";

export default defineNuxtConfig({
    modules: ['@nuxtjs/i18n'], 
    i18n: {
        vueI18n: {
            legacy: false,
            locale: 'fr',
            messages: {
                en,
                fr,
                ca,
                nl
            }
        },
        detectBrowserLanguage: {
            useCookie: true,
            cookieKey: 'i18n_redirected',
            redirectOn: 'root',  // recommended
        }
    },
})


```

### Logs

```shell
Nuxi 3.0.0                                                                                                    14:01:53
Nuxt 3.0.0 with Nitro 1.0.0                                                                                   14:01:53
                                                                                                              14:01:56
  > Local:    http://localhost:3000/
  > Network:  http://192.168.1.101:3000/
  > Network:  http://[fd82:88e1:5c9c:8300:58e1:f878:dbee:da69]:3000/
  > Network:  http://[fd82:88e1:5c9c:8300:e6ea:6ff0:3e91:e5b7]:3000/


 ERROR  Cannot start nuxt:  Cannot read properties of undefined (reading 'options')                           14:01:57

  at _default (C:/Users/Dilypse/Documents/maj/dilypse-front/node_modules/@nuxtjs/i18n/src/index.js:13:92)
  at installModule (/C:/Users/Dilypse/Documents/maj/dilypse-front/node_modules/@nuxt/kit/dist/index.mjs:416:9)
  at async initNuxt (/C:/Users/Dilypse/Documents/maj/dilypse-front/node_modules/nuxt/dist/index.mjs:1825:7)
  at async load (/C:/Users/Dilypse/Documents/maj/dilypse-front/node_modules/nuxi/dist/chunks/dev.mjs:6779:9)
  at async Object.invoke (/C:/Users/Dilypse/Documents/maj/dilypse-front/node_modules/nuxi/dist/chunks/dev.mjs:6840:5)
  at async _main (/C:/Users/Dilypse/Documents/maj/dilypse-front/node_modules/nuxi/dist/cli.mjs:50:20)
```

**Comment by oritwoen** [comment]
`@nuxtjs/i18n@7.x.x` it is incompatible with Nuxt 3. You should install `@nuxtjs/i18n@next`.

See documentation for i18n version 8: https://v8.i18n.nuxtjs.org/getting-started/setup

**Comment by RijaCloud** [comment]
Thanks @oritwoen  it has resolved my issues.
