### ISSUE TITLE
Unexpected character '@'

### ISSUE THREAD

**Issue by veerdone** [nuxt/framework#9861]
### Environment
- Operating System: `Windows 11`
- Node Version: `v16.14.2`
- Nuxt Version: `3.0.0`
- Nitro Version: `1.0.0`
- Package Manager: `npm@8.5.0`
- Builder: `Vite`
- User Config: `-`
- Runtime Modules: `-`
- Build Modules: `-`

### Reproduction
Repro link: https://github.com/veerdone/nuxt-demo-issue

### Describe the bug
When I run build, I get the error

#### Log
```
 WARN  rollup-plugin-inject: failed to parse /root/nuxt-demo/node_modules/@arco-design/web-vue/es/style/index.less. Consider restricting the plugin to particular files via options.include


 WARN  rollup-plugin-inject: failed to parse /root/nuxt-demo/node_modules/@arco-design/web-vue/es/message/style/index.less. Consider restricting the plugin to particular files via options.include


 WARN  rollup-plugin-inject: failed to parse /root/nuxt-demo/node_modules/@arco-design/web-vue/es/space/style/index.less. Consider restricting the plugin to particular files via options.include


 WARN  rollup-plugin-inject: failed to parse /root/nuxt-demo/node_modules/@arco-design/web-vue/es/button/style/index.less. Consider restricting the plugin to particular files via options.include


 ERROR                                                                                                                                       nitro 14:48:00

1: @import './normalize.less';
   ^
2: @import './icon.less';
3: @import './animation/index.less';


 ERROR  Unexpected character '@' (Note that you need plugins to import files that are not JavaScript)                                              14:48:00

  at error (node_modules/rollup/dist/es/shared/rollup.js:1858:30)
  at Module.error (node_modules/rollup/dist/es/shared/rollup.js:12429:16)
  at Module.tryParse (node_modules/rollup/dist/es/shared/rollup.js:12806:25)
  at Module.setSource (node_modules/rollup/dist/es/shared/rollup.js:12711:24)
  at ModuleLoader.addModuleSource (node_modules/rollup/dist/es/shared/rollup.js:21959:20)
```

**Comment by veerdone** [comment]
when I add config
```
build {
  transpile: ['@arco-design/web-vue']
}
```
It was worked
