### ISSUE TITLE
useFetch not compatible with node 18+ (nuxt instance unavailable), has solve

### ISSUE THREAD

**Issue by evdevru** [nuxt/framework#9901]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `modules`, `vite`, `imports`, `css`, `app`, `build`, `tailwindcss`
- Runtime Modules:  `@pinia/nuxt@0.4.6`, `@pinia-plugin-persistedstate/nuxt@1.0.0`, `@nuxtjs/tailwindcss@6.1.3`
- Build Modules:    `-`
------------------------------

### Reproduction

Top-level page:
```const { data, error } = await useApi('url')```

useApi composable:

```import type { NitroFetchRequest } from 'nitropack'
import type { KeyOfRes } from 'nuxt/dist/app/composables/asyncData'
import type { UseFetchOptions } from '#app'

export async function useApi<T>(
  request: NitroFetchRequest,
  opts?:
  | UseFetchOptions<
        T extends void ? unknown : T,
        (res: T extends void ? unknown : T) => T extends void ? unknown : T,
        KeyOfRes<
          (res: T extends void ? unknown : T) => T extends void ? unknown : T
        >
      >
  | undefined,
) {
  const config = useRuntimeConfig()

  const { body, ...rest } = opts || {}

  return await useFetch<T>(request, {
    baseURL: config.public.BASE_URL,
    body: JSON.parse(JSON.stringify(body || null)),
    ...rest,
  })
}
```

### Describe the bug

Thats bug only on 18 node+
SOLVE: downgrade to 16 node

### Logs

```shell
Error: nuxt instance unavailable
      at Module.useNuxtApp (C:/Users/sonic/Documents/GitHub/rubi-front-n3-1/node_modules/nuxt/dist/app/nuxt.mjs:165:13)
      at Module.useRequestEvent (C:/Users/sonic/Documents/GitHub/rubi-front-n3-1/node_modules/nuxt/dist/app/composables/ssr.mjs:14:58)
      at readRawCookies (C:/Users/sonic/Documents/GitHub/rubi-front-n3-1/node_modules/nuxt/dist/app/composables/cookie.mjs:46:62)
      at Module.useCookie (C:/Users/sonic/Documents/GitHub/rubi-front-n3-1/node_modules/nuxt/dist/app/composables/cookie.mjs:22:19)
      at Proxy.getToken (C:/Users/sonic/Documents/GitHub/rubi-front-n3-1/stores/auth.ts:25:44)
      at Proxy.<anonymous> (file:///C:/Users/sonic/Documents/GitHub/rubi-front-n3-1/node_modules/pinia/dist/pinia.mjs:1365:30)
      at Object.onRequest (C:/Users/sonic/Documents/GitHub/rubi-front-n3-1/composables/useApi.ts:14:27)
      at $fetchRaw2 (file:///C:/Users/sonic/Documents/GitHub/rubi-front-n3-1/node_modules/ofetch/dist/shared/ofetch.5cb01515.mjs:122:29)
      at onError (file:///C:/Users/sonic/Documents/GitHub/rubi-front-n3-1/node_modules/ofetch/dist/shared/ofetch.5cb01515.mjs:102:16)
      at file:///C:/Users/sonic/Documents/GitHub/rubi-front-n3-1/node_modules/ofetch/dist/shared/ofetch.5cb01515.mjs:147:14,
```

**Comment by evdevru** [comment]
Already created https://github.com/nuxt/framework/issues/9885
